---
permalink: switch-cisco-3232c/cn1610-replace-CL1.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Cisco Nexus 3232C 스위치를 AFF 또는 FAS 클러스터에서 클러스터 스위치로 사용할 수 있습니다. 
---
= CN1610 스위치 CL1을 3232C 스위치 C1로 교체합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 단계에 따라 CN1610(CL1) 스위치를 Nexus 3232C(C1) 스위치로 교체하세요.

.단계
. 클러스터 상태를 확인하세요.
+
`network interface show -role cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 필수 클러스터 LIF가 클러스터 스위치 C2에 호스팅된 적절한 클러스터 포트로 마이그레이션되었음을 보여줍니다.

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
(network interface show)
         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0b      false
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0c      false
         n2_clus1   up/up       10.10.0.5/24   n2       e0b      false
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0c      false

8 entries were displayed.
----
====
. 모든 노드에서 CL1에 연결된 노드 포트를 종료합니다.
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 노드 n1과 n2에서 특정 포트가 종료되는 것을 보여줍니다.

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0a -up-admin false*
cluster::*> *network port modify -node n1 -port e0d -up-admin false*
cluster::*> *network port modify -node n2 -port e0a -up-admin false*
cluster::*> *network port modify -node n2 -port e0d -up-admin false*
----
====
. 활성화된 3232C 스위치 C2에서 ISL 포트 24, 31, 32를 종료합니다.
+
Cisco 명령에 대한 자세한 내용은 다음 가이드를 참조하세요. https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^] .

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 활성 3232C 스위치 C2에서 ISL 24, 31, 32가 종료되는 것을 보여줍니다.

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *interface ethernet 1/24/1-4*
C2(config-if-range)# *shutdown*
C2(config-if-range)# *exit*
C2(config)# *interface ethernet 1/31-32*
C2(config-if-range)# *shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
C2#
----
====
. 모든 노드의 CN1610 스위치 CL1에 연결된 케이블을 제거합니다.
+
적절한 케이블을 사용하여 모든 노드의 연결이 끊긴 포트를 Nexus 3232C 스위치 C1에 다시 연결해야 합니다.

. Nexus 3232C C2 포트 e1/24에서 QSFP28 케이블을 제거합니다.
+
지원되는 Cisco QSFP28 광섬유 또는 직접 연결 케이블을 사용하여 C1의 포트 e1/31 및 e1/32를 C2의 포트 e1/31 및 e1/32에 연결해야 합니다.

. 포트 24의 구성을 복원하고 C2의 임시 포트 채널 2를 제거합니다.
+
Cisco 명령에 대한 자세한 내용은 다음 가이드를 참조하세요. https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^] .

+
.예를 보여주세요
[%collapsible]
====
다음 예는 다음을 보여줍니다. `running-configuration` 복사되는 파일 `startup-configuration` 파일:

[listing, subs="+quotes"]
----
C2# configure
C2(config)# *no interface breakout module 1 port 24 map 10g-4x*
C2(config)# *no interface port-channel 2*
C2(config-if)# *interface e1/24*
C2(config-if)# *description 100GbE/40GbE Node Port*
C2(config-if)# *spanning-tree port type edge*
Edge port type (portfast) should only be enabled on ports connected to a single
host. Connecting hubs, concentrators, switches, bridges, etc...  to this
interface when edge port type (portfast) is enabled, can cause temporary bridging loops.
Use with CAUTION

Edge Port Type (Portfast) has been configured on Ethernet 1/24 but will only
have effect when the interface is in a non-trunking mode.

C2(config-if)# *spanning-tree bpduguard enable*
C2(config-if)# *mtu 9216*
C2(config-if-range)# *exit*
C2(config)# *exit*
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====
. 활성 3232C 스위치인 C2에서 ISL 포트 31과 32를 켭니다.
+
Cisco 명령에 대한 자세한 내용은 다음 가이드를 참조하세요. https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^] .

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 ISL 31과 32가 3232C 스위치 C2에 적용되는 것을 보여줍니다.

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *interface ethernet 1/31-32*
C2(config-if-range)# *no shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
C2# copy running-config startup-config
[########################################] 100%
Copy Complete.
----
====
. ISL 연결이 올바른지 확인하십시오. `up` 3232C 스위치 C2에 있습니다.
+
Cisco 명령에 대한 자세한 내용은 다음 가이드를 참조하세요. https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^] .

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 ISL 연결이 검증되는 것을 보여줍니다.  포트 Eth1/31 및 Eth1/32는 다음을 나타냅니다. `(P)` 즉, 두 ISL 포트 모두 `up` 항구 채널에서:

[listing, subs="+quotes"]
----
C1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        S - Switched    R - Routed
        U - Up (port-channel)
        M - Not in use. Min-links not met
------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
-----------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)

C2# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        S - Switched    R - Routed
        U - Up (port-channel)
        M - Not in use. Min-links not met
------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/31(P)   Eth1/32(P)
----
====
. 모든 노드에서 새로운 3232C 스위치 C1에 연결된 모든 클러스터 상호 연결 포트를 불러옵니다.
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 새로운 3232C 스위치 C1에 연결된 모든 클러스터 상호 연결 포트가 활성화되는 모습을 보여줍니다.

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0a -up-admin true*
cluster::*> *network port modify -node n1 -port e0d -up-admin true*
cluster::*> *network port modify -node n2 -port e0a -up-admin true*
cluster::*> *network port modify -node n2 -port e0d -up-admin true*
----
====
. 클러스터 노드 포트의 상태를 확인하세요.
+
`network port show -role cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 새 3232C 스위치 C1의 노드 n1 및 n2에 있는 클러스터 상호 연결 포트가 다음과 같은지 확인하는 출력을 보여줍니다. `up` :

[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
       (network port show)

Node: n1
                Broadcast              Speed (Mbps) Health   Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status   Health Status
----- --------- ---------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster    up    9000  auto/10000     -
e0b   cluster   cluster    up    9000  auto/10000     -
e0c   cluster   cluster    up    9000  auto/10000     -        -
e0d   cluster   cluster    up    9000  auto/10000     -        -

Node: n2
                Broadcast              Speed (Mbps) Health   Ignore
Port  IPspace   Domain     Link  MTU   Admin/Open   Status   Health Status
----- --------- ---------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster    up    9000  auto/10000     -
e0b   cluster   cluster    up    9000  auto/10000     -
e0c   cluster   cluster    up    9000  auto/10000     -
e0d   cluster   cluster    up    9000  auto/10000     -

8 entries were displayed.
----
====


.다음은 무엇인가요?
link:cn1610-complete-migration.html["마이그레이션을 완료하세요"].
