---
permalink: switch-cisco-3232c/cn1610-replace-CL2.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Cisco Nexus 3232C 스위치를 AFF 또는 FAS 클러스터에서 클러스터 스위치로 사용할 수 있습니다. 
---
= CN1610 스위치 CL2를 3232C 스위치 C2로 교체합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 단계에 따라 CN1610(CL2) 스위치를 Nexus 3232C(C2) 스위치로 교체하세요.

.단계
. 스위치 CL2에 물리적으로 연결된 클러스터 상호 연결 포트를 종료합니다.
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 노드 n1과 노드 n2에 대해 4개의 클러스터 상호 연결 포트가 종료되는 것을 보여줍니다.

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin false*
cluster::*> *network port modify -node n1 -port e0c -up-admin false*
cluster::*> *network port modify -node n2 -port e0b -up-admin false*
cluster::*> *network port modify -node n2 -port e0c -up-admin false*
----
====
. 원격 클러스터 인터페이스의 연결성을 확인하세요.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
당신은 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령:

`network interface check cluster-connectivity start`그리고 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*참고:* 실행하기 전에 몇 초 동안 기다리십시오. `show` 세부 정보를 표시하는 명령입니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스의 경우 다음을 사용할 수도 있습니다. `cluster ping-cluster -node <name>` 연결성을 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[3단계]] 적절한 명령을 사용하여 활성 CN1610 스위치 CL1의 ISL 포트 13~16을 종료합니다.
+
Cisco 명령에 대한 자세한 내용은 다음 가이드를 참조하세요. https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^] .

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 CN1610 스위치 CL1에서 ISL 포트 13~16이 종료되는 것을 보여줍니다.

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/13-0/16*
(CL1)(Interface 0/13-0/16)# *shutdown*
(CL1)(Interface 0/13-0/16)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. CL1과 C2 사이에 임시 ISL을 구축합니다.
+
Cisco 명령에 대한 자세한 내용은 다음 가이드를 참조하세요. https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^] .

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 Cisco 사용하여 CL1(포트 13-16)과 C2(포트 e1/24/1-4) 사이에 임시 ISL이 구축되는 것을 보여줍니다. `switchport mode trunk` 명령:

[listing, subs="+quotes"]
----
C2# configure
C2(config)# *interface port-channel 2*
C2(config-if)# *switchport mode trunk*
C2(config-if)# *spanning-tree port type network*
C2(config-if)# *mtu 9216*
C2(config-if)# *interface breakout module 1 port 24 map 10g-4x*
C2(config)# *interface e1/24/1-4*
C2(config-if-range)# *switchport mode trunk*
C2(config-if-range)# *mtu 9216*
C2(config-if-range)# *channel-group 2 mode active*
C2(config-if-range)# *exit*
C2(config-if)# *exit*
----
====
. 모든 노드의 CN1610 스위치 CL2에 연결된 케이블을 제거합니다.
+
지원되는 케이블을 사용하여 모든 노드의 연결이 끊긴 포트를 Nexus 3232C 스위치 C2에 다시 연결해야 합니다.

. CN1610 스위치 CL1의 포트 13~16에서 ISL 케이블 4개를 제거합니다.
+
새로운 Cisco 3232C 스위치 C2의 포트 1/24를 기존 CN1610 스위치 CL1의 포트 13~16에 연결하는 적절한 Cisco QSFP28-SFP+ 브레이크아웃 케이블을 연결해야 합니다.

+
[NOTE]
====
새로운 Cisco 3232C 스위치에 케이블을 다시 연결할 때는 광섬유 케이블이나 Cisco Twinax 케이블을 사용해야 합니다.

====
. 활성 CN1610 스위치에서 ISL 인터페이스 3/1을 구성하여 정적 모드를 비활성화하여 ISL을 동적으로 만듭니다.
+
이 구성은 두 스위치 모두에서 ISL이 활성화될 때 3232C 스위치 C2의 ISL 구성과 일치합니다.

+
Cisco 명령에 대한 자세한 내용은 다음 가이드를 참조하세요. https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^] .

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 ISL 인터페이스 3/1이 ISL을 동적으로 만들기 위해 구성된 것을 보여줍니다.

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 3/1*
(CL1)(Interface 3/1)# *no port-channel static*
(CL1)(Interface 3/1)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. 활성 CN1610 스위치 CL1에서 ISL 13~16을 불러옵니다.
+
Cisco 명령에 대한 자세한 내용은 다음 가이드를 참조하세요. https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^] .

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 ISL 포트 13~16이 포트 채널 인터페이스 3/1에서 활성화되는 것을 보여줍니다.

[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/13-0/16,3/1*
(CL1)(Interface 0/13-0/16,3/1)# *no shutdown*
(CL1)(Interface 0/13-0/16,3/1)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
====
. ISL이 있는지 확인하세요 `up` CN1610 스위치 CL1에서.
+
"링크 상태"는 다음과 같아야 합니다. `Up` , "유형"은 다음과 같아야 합니다. `Dynamic` , 그리고 "포트 활성" 열은 다음과 같아야 합니다. `True` 포트 0/13 ~ 0/16용.

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 ISL이 다음과 같이 검증되는 것을 보여줍니다. `up` CN1610 스위치 CL1에서:

[listing, subs="+quotes"]
----
(CL1)# *show port-channel 3/1*
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port        Port
Ports  Timeout       Speed       Active
------ ------------- ----------  -------
0/13   actor/long    10 Gb Full  True
       partner/long
0/14   actor/long    10 Gb Full  True
       partner/long
0/15   actor/long    10 Gb Full  True
       partner/long
0/16   actor/long    10 Gb Full  True
       partner/long
----
====
. ISL이 있는지 확인하세요 `up` 3232C 스위치 C2에서:
+
`show port-channel summary`

+
Cisco 명령에 대한 자세한 내용은 다음 가이드를 참조하세요. https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^] .

+
Eth1/24/1부터 Eth1/24/4까지의 포트는 다음을 표시해야 합니다. `(P)` 즉, 4개의 ISL 포트가 모두 포트 채널에 연결되어 있다는 의미입니다.  Eth1/31 및 Eth1/32는 다음을 표시해야 합니다. `(D)` 서로 연결되어 있지 않기 때문입니다.

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 ISL이 다음과 같이 검증되는 것을 보여줍니다. `up` 3232C 스위치 C2에서:

[listing, subs="+quotes"]
----
C2# *show port-channel summary*

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        S - Switched    R - Routed
        U - Up (port-channel)
        M - Not in use. Min-links not met
------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
------------------------------------------------------------------------------
1	    Po1(SU)     Eth      LACP      Eth1/31(D)   Eth1/32(D)
2	    Po2(SU)     Eth      LACP      Eth1/24/1(P) Eth1/24/2(P) Eth1/24/3(P)
                                     Eth1/24/4(P)
----
====
. 모든 노드의 3232C 스위치 C2에 연결된 모든 클러스터 상호 연결 포트를 불러옵니다.
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.예를 보여주세요
[%collapsible]
====
다음 예제에서는 3232C 스위치 C2에 연결된 클러스터 상호 연결 포트를 불러오는 방법을 보여줍니다.

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e0b -up-admin true*
cluster::*> *network port modify -node n1 -port e0c -up-admin true*
cluster::*> *network port modify -node n2 -port e0b -up-admin true*
cluster::*> *network port modify -node n2 -port e0c -up-admin true*
----
====
. 모든 노드에서 C2에 연결된 모든 마이그레이션된 클러스터 상호 연결 LIF를 되돌립니다.
+
`network interface revert -vserver cluster -lif _lif-name_`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver cluster -lif n1_clus3*
cluster::*> *network interface revert -vserver cluster -lif n2_clus2*
cluster::*> *network interface revert -vserver cluster -lif n2_clus3*
----
====
. 모든 클러스터 상호 연결 포트가 홈 포트로 되돌아갔는지 확인하세요.
+
`network interface show -role cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 clus2의 LIF가 홈 포트로 되돌아가는 것을 보여줍니다. "현재 포트" 열의 포트 상태가 다음과 같으면 LIF가 성공적으로 되돌아간 것입니다. `true` "집" 열에 있습니다.  "Is Home" 값이 `false` 그러면 LIF는 되돌려지지 않습니다.

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
(network interface show)
         Logical    Status      Network        Current  Current  Is
Vserver  Interface  Admin/Oper  Address/Mask   Node     Port     Home
-------- ---------- ----------- -------------- -------- -------- -----
Cluster
         n1_clus1   up/up       10.10.0.1/24   n1       e0a      true
         n1_clus2   up/up       10.10.0.2/24   n1       e0b      true
         n1_clus3   up/up       10.10.0.3/24   n1       e0c      true
         n1_clus4   up/up       10.10.0.4/24   n1       e0d      true
         n2_clus1   up/up       10.10.0.5/24   n2       e0a      true
         n2_clus2   up/up       10.10.0.6/24   n2       e0b      true
         n2_clus3   up/up       10.10.0.7/24   n2       e0c      true
         n2_clus4   up/up       10.10.0.8/24   n2       e0d      true

8 entries were displayed.
----
====
. 모든 클러스터 포트가 연결되었는지 확인하세요.
+
`network port show -role cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 모든 클러스터 상호 연결이 확인되는 출력을 보여줍니다. `up` :

[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
       (network port show)

Node: n1
                Broadcast               Speed (Mbps) Health   Ignore
Port  IPspace   Domain      Link  MTU   Admin/Open   Status   Health Status
----- --------- ----------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster     up    9000  auto/10000     -
e0b   cluster   cluster     up    9000  auto/10000     -
e0c   cluster   cluster     up    9000  auto/10000     -        -
e0d   cluster   cluster     up    9000  auto/10000     -        -
Node: n2

                Broadcast               Speed (Mbps) Health   Ignore
Port  IPspace   Domain      Link  MTU   Admin/Open   Status   Health Status
----- --------- ----------- ----- ----- ------------ -------- -------------
e0a   cluster   cluster     up    9000  auto/10000     -
e0b   cluster   cluster     up    9000  auto/10000     -
e0c   cluster   cluster     up    9000  auto/10000     -
e0d   cluster   cluster     up    9000  auto/10000     -

8 entries were displayed.
----
====
. 원격 클러스터 인터페이스의 연결성을 확인하세요.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
당신은 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령:

`network interface check cluster-connectivity start`그리고 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*참고:* 실행하기 전에 몇 초 동안 기다리십시오. `show` 세부 정보를 표시하는 명령입니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스의 경우 다음을 사용할 수도 있습니다. `cluster ping-cluster -node <name>` 연결성을 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1       e0a    10.10.0.1
Cluster n1_clus2 n1       e0b    10.10.0.2
Cluster n1_clus3 n1       e0c    10.10.0.3
Cluster n1_clus4 n1       e0d    10.10.0.4
Cluster n2_clus1 n2       e0a    10.10.0.5
Cluster n2_clus2 n2       e0b    10.10.0.6
Cluster n2_clus3 n2       e0c    10.10.0.7
Cluster n2_clus4 n2       e0d    10.10.0.8
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8

Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step16]] 첫 번째 CN1610 스위치 CL1과 연관된 LIF를 마이그레이션합니다.
+
`network interface migrate -vserver cluster -lif _lif-name_ -source-node _node-name_`

+
.예를 보여주세요
[%collapsible]
====
다음 예와 같이 각 클러스터 LIF를 클러스터 스위치 C2에 호스팅된 적절한 클러스터 포트로 개별적으로 마이그레이션해야 합니다.

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e0b*
cluster::*> *network interface migrate -vserver cluster -lif n1_clus4 -source-node n1
-destination-node n1 -destination-port e0c*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e0b*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus4 -source-node n2
-destination-node n2 -destination-port e0c*
----
====


.다음은 무엇인가요?
CN1610 스위치 CL2를 교체한 후에는 다음을 수행할 수 있습니다.link:cn1610-replace-CL1.html["CN1610 스위치 CL1을 3232C 스위치 C1로 교체"] .
