---
permalink: switch-cisco-3232c/cn1610-migrate-to-3232c-overview.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Cisco Nexus 32c 스위치를 구성하기 전에 프로세스 개요 및 명명법을 검토하십시오. 
---
= 마이그레이션 요구 사항
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C 스위치는 AFF 또는 FAS 클러스터에서 클러스터 스위치로 사용할 수 있습니다. 클러스터 스위치를 사용하면 2개 이상의 노드로 ONTAP 클러스터를 구축할 수 있습니다.


NOTE: 이 절차를 수행하려면 ONTAP 명령과 Cisco Nexus 3000 시리즈 스위치 명령을 모두 사용해야 합니다. ONTAP 명령은 별도의 표시가 없는 한 사용됩니다.

필요한 경우 다음 정보를 참조하십시오.

* http://support.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 및 CN1610 설명 페이지"^]
* http://support.netapp.com/NOW/download/software/cm_switches/["Cisco 이더넷 스위치 설명 페이지"^]
* http://hwu.netapp.com["Hardware Universe"^]




== CN1610 마이그레이션 요구 사항

클러스터 스위치는 다음과 같은 노드 연결을 지원합니다.

* NetApp CN1610: 포트 0/1~0/12(10GbE)
* Cisco Nexus 3232C: 포트 e1/1-30(40 또는 100 또는 4x10GbE)


클러스터 스위치는 다음과 같은 ISL(Inter-Switch Link) 포트를 사용합니다.

* NetApp CN1610: 포트 0/13~0/16(10GbE)
* Cisco Nexus 3232C: 포트 1/31-32(100GbE)


[NOTE]
====
Cisco Nexus 3232C 클러스터 스위치에서 4x10G 브레이크아웃 케이블을 사용해야 합니다.

====
다음 표에는 NetApp CN1610 스위치에서 Cisco Nexus 3232C 클러스터 스위치로 전환할 때 각 단계에서 필요한 케이블 연결 연결이 나와 있습니다.

|===
| 단계 | 설명 | 필수 케이블 


 a| 
초기
 a| 
CN1610 대 CN1610(SFP+에서 SFP+)
 a| 
4 SFP+ 광 파이버 또는 구리 직접 연결 케이블



 a| 
전환
 a| 
3232C(QSFP-SFP+) CN1610
 a| 
1 QSFP 및 4 SFP+ 광 파이버 또는 구리 브레이크아웃 케이블



 a| 
최종
 a| 
3232C~3232C(QSFP에서 QSFP로)
 a| 
QSFP 광 파이버 또는 구리 직접 연결 케이블 2개

|===
해당 참조 구성 파일(RCFs)을 다운로드해야 합니다. 10GbE 및 40/100 GbE 포트 수는 에서 사용할 수 있는 RCFs에 정의되어 있습니다 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] 페이지.

이 절차에서 지원되는 ONTAP 및 NX-OS 버전이 에 나열되어 있습니다 link:https://mysupport.netapp.com/NOW/download/software/cm_switches/.html["Cisco 이더넷 스위치 페이지"^].

이 절차에서 지원되는 ONTAP 및 FASTPATH 버전은 에 나열되어 있습니다 link:http://support.netapp.com/NOW/download/software/cm_switches_ntap/.html["NetApp CN1601 및 CN1610 스위치 페이지"^].

.사용된 예제에 대해 설명합니다
마이그레이션 절차의 예에서는 네 개의 노드를 사용합니다.

* 2개 노드에서 4개의 10GbE 클러스터 인터커넥트 포트 * e0a *, * e0b *, * e0c * 및 * e0d * 를 사용합니다.
* 다른 2개 노드는 2개의 40GbE 클러스터 상호 연결 파이버 케이블 * e4a * 및 * e4e * 을 사용합니다.
+
에는 link:https://hwu.netapp.com/["_Hardware Universe _"^]플랫폼에 대한 클러스터 파이버 케이블에 대한 정보가 있습니다.



이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 노드는 * n1 *, * n2 *, * n3 * 및 * n4 * 입니다.
* 명령 출력은 ONTAP 소프트웨어의 릴리스에 따라 다를 수 있습니다.
* 교체할 CN1610 스위치는 * CL1 * 및 * CL2 * 입니다.
* CN1610 스위치를 대체하는 Nexus 3232C 스위치는 * C1 * 및 * C2 * 입니다.
* * n1_clus1 * 은 노드 * n1 * 의 클러스터 스위치 1(CL1 또는 C1)에 연결된 첫 번째 클러스터 논리 인터페이스(LIF)입니다.
* * n1_clus2 * 는 노드 * n1 * 의 클러스터 스위치 2(CL2 또는 C2)에 연결된 첫 번째 클러스터 LIF입니다.
* * n1_clus3 * 은 노드 * n1 * 의 클러스터 스위치 2(CL2 또는 C2)에 연결된 두 번째 LIF입니다.
* * n1_clus4 * 는 노드 * n1 * 의 클러스터 스위치 1(CL1 또는 C1)에 연결된 두 번째 LIF입니다.
* 10GbE 및 40/100 GbE 포트 수는 에서 사용할 수 있는 RCFs(참조 구성 파일)에 정의되어 있습니다 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] 페이지.


.다음 단계
link:cn1610-prepare-to-migrate.html["마이그레이션을 준비합니다"]..
