---
permalink: switch-cisco-3232c/cn1610-migrate-to-3232c-overview.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Cisco Nexus 3232c 스위치를 구성하기 전에 프로세스 개요와 명명법을 살펴보세요. 
---
= 이주 요구 사항
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C 스위치는 AFF 또는 FAS 클러스터에서 클러스터 스위치로 사용할 수 있습니다. 클러스터 스위치를 사용하면 두 개 이상의 노드로 ONTAP 클러스터를 구축할 수 있습니다.


NOTE: 이 절차에서는 ONTAP 명령과 Cisco Nexus 3000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 지정되지 않는 한 ONTAP 명령을 사용합니다.

필요한 경우 자세한 내용은 다음을 참조하세요.

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 및 CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== CN1610 마이그레이션 요구 사항

클러스터 스위치는 다음 노드 연결을 지원합니다.

* NetApp CN1610: 포트 0/1~0/12(10GbE)
* Cisco Nexus 3232C: 포트 e1/1-30(40 또는 100 또는 4x10GbE)


클러스터 스위치는 다음의 ISL(스위치 간 링크) 포트를 사용합니다.

* NetApp CN1610: 포트 0/13~0/16(10GbE)
* Cisco Nexus 3232C: 포트 1/31-32(100GbE)


[NOTE]
====
Cisco Nexus 3232C 클러스터 스위치에서는 4x10G 브레이크아웃 케이블을 사용해야 합니다.

====
다음 표는 NetApp CN1610 스위치에서 Cisco Nexus 3232C 클러스터 스위치로 전환할 때 각 단계에 필요한 케이블 연결을 보여줍니다.

|===
| 단계 | 설명 | 필요한 케이블 


 a| 
초기의
 a| 
CN1610 대 CN1610(SFP+ 대 SFP+)
 a| 
4개의 SFP+ 광섬유 또는 구리 직접 연결 케이블



 a| 
이행
 a| 
CN1610~3232C(QSFP~SFP+)
 a| 
1개의 QSFP 및 4개의 SFP+ 광섬유 또는 구리 분기 케이블



 a| 
결정적인
 a| 
3232C에서 3232C로(QSFP에서 QSFP로)
 a| 
2개의 QSFP 광섬유 또는 구리 직접 연결 케이블

|===
해당 참조 구성 파일(RCF)을 다운로드했어야 합니다.  10GbE 및 40/100GbE 포트의 수는 다음에서 사용 가능한 RCF에 정의되어 있습니다.link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] .

이 절차에서 지원되는 ONTAP 및 NX-OS 버전은 다음에 나열되어 있습니다.link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^] .

이 절차에서 지원되는 ONTAP 및 FASTPATH ​​버전은 다음에 나열되어 있습니다.link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 및 CN1610 스위치"^] .

.사용된 예에 관하여
마이그레이션 절차의 예에서는 4개의 노드를 사용합니다.

* 두 노드는 4개의 10GbE 클러스터 상호 연결 포트(*e0a*, *e0b*, *e0c*, *e0d*)를 사용합니다.
* 나머지 두 노드는 두 개의 40GbE 클러스터 상호 연결 파이버 케이블인 *e4a*와 *e4e*를 사용합니다.
+
그만큼link:https://hwu.netapp.com/["_하드웨어 유니버스_"^] 귀하의 플랫폼에 맞는 클러스터 파이버 케이블에 대한 정보가 있습니다.



이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 노드는 *n1*, *n2*, *n3*, *n4*입니다.
* 명령 출력은 ONTAP 소프트웨어 릴리스에 따라 달라질 수 있습니다.
* 교체할 CN1610 스위치는 *CL1*과 *CL2*입니다.
* CN1610 스위치를 대체하는 Nexus 3232C 스위치는 *C1*과 *C2*입니다.
* *n1_clus1*은 노드 *n1*의 클러스터 스위치 1(CL1 또는 C1)에 연결된 첫 번째 클러스터 논리 인터페이스(LIF)입니다.
* *n1_clus2*는 노드 *n1*의 클러스터 스위치 2(CL2 또는 C2)에 연결된 첫 번째 클러스터 LIF입니다.
* *n1_clus3*는 노드 *n1*의 클러스터 스위치 2(CL2 또는 C2)에 연결된 두 번째 LIF입니다.
* *n1_clus4*는 노드 *n1*의 클러스터 스위치 1(CL1 또는 C1)에 연결된 두 번째 LIF입니다.
* 10GbE 및 40/100GbE 포트의 수는 다음에서 사용 가능한 참조 구성 파일(RCF)에 정의되어 있습니다.link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] .


.다음은 무엇인가요?
link:cn1610-prepare-to-migrate.html["이주 준비"].
