---
permalink: switch-cisco-3232c/cn5596-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Cisco Nexus 3232c 스위치를 구성하기 전에 프로세스 개요와 명명법을 살펴보세요. 
---
= 이주 요구 사항
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C 스위치는 AFF 또는 FAS 클러스터에서 클러스터 스위치로 사용할 수 있습니다. 클러스터 스위치를 사용하면 두 개 이상의 노드로 ONTAP 클러스터를 구축할 수 있습니다.

[NOTE]
====
이 절차에서는 ONTAP 명령과 Cisco Nexus 3000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 지정되지 않는 한 ONTAP 명령을 사용합니다.

====
자세한 내용은 다음을 참조하세요.

* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== Cisco Nexus 5596 요구 사항

클러스터 스위치는 노드에 연결하기 위해 다음 포트를 사용합니다.

* Nexus 5596: 포트 e1/1-40(10GbE)
* Nexus 3232C: 포트 e1/1-30(10/40/100GbE)


클러스터 스위치는 다음의 ISL(Inter-Switch Link) 포트를 사용합니다.

* Nexus 5596: 포트 e1/41-48(10GbE)
* Nexus 3232C: 포트 e1/31-32(40/100GbE)


그만큼link:https://hwu.netapp.com/["_하드웨어 유니버스_"^] Nexus 3232C 스위치에 지원되는 케이블에 대한 정보가 포함되어 있습니다.

* 10GbE 클러스터 연결이 있는 노드에는 QSFP-SFP+ 광섬유 분기 케이블이나 QSFP-SFP+ 구리 분기 케이블이 필요합니다.
* 40/100GbE 클러스터 연결이 있는 노드에는 파이버 케이블이나 QSFP/QSFP28 구리 직접 연결 케이블이 있는 지원되는 QSFP/QSFP28 광 모듈이 필요합니다.


클러스터 스위치는 적절한 ISL 케이블을 사용합니다.

* 시작: Nexus 5596(SFP+에서 SFP+로)
+
** 8x SFP+ 파이버 또는 구리 직접 연결 케이블


* 중간: Nexus 5596에서 Nexus 3232C로(QSFP에서 4xSFP+로 분리)
+
** 1x QSFP-SFP+ 파이버 브레이크아웃 또는 구리 브레이크아웃 케이블


* 최종: Nexus 3232C에서 Nexus 3232C로(QSFP28에서 QSFP28로)
+
** 2x QSFP28 파이버 또는 구리 직접 연결 케이블


* Nexus 3232C 스위치에서는 QSFP/QSFP28 포트를 40/100 기가비트 이더넷 또는 4 x 10 기가비트 이더넷 모드로 작동할 수 있습니다.
+
기본적으로 40/100 기가비트 이더넷 모드에는 32개의 포트가 있습니다.  이 40개의 기가비트 이더넷 포트는 2-튜플 명명 규칙에 따라 번호가 매겨집니다.  예를 들어, 두 번째 40기가비트 이더넷 포트는 1/2로 번호가 매겨집니다.

+
40기가비트 이더넷에서 10기가비트 이더넷으로 구성을 변경하는 과정을 _breakout_이라고 하고, 10기가비트 이더넷에서 40기가비트 이더넷으로 구성을 변경하는 과정을 _breakin_이라고 합니다.

+
40/100 기가비트 이더넷 포트를 10 기가비트 이더넷 포트로 분리하면, 생성된 포트는 3-튜플 명명 규칙을 사용하여 번호가 지정됩니다.  예를 들어, 두 번째 40/100 기가비트 이더넷 포트의 브레이크아웃 포트는 1/2/1, 1/2/2, 1/2/3, 1/2/4로 번호가 매겨집니다.

* Nexus 3232C 스위치의 왼쪽에는 1/33과 1/34라고 하는 SFP+ 포트 2개가 있습니다.
* Nexus 3232C 스위치의 일부 포트를 10GbE 또는 40/100GbE로 실행하도록 구성했습니다.
+
[NOTE]
====
다음을 사용하여 첫 번째 6개 포트를 4x10 GbE 모드로 분리할 수 있습니다. `interface breakout module 1 port 1-6 map 10g-4x` 명령.  마찬가지로, 다음을 사용하여 브레이크아웃 구성에서 처음 6개의 QSFP+ 포트를 다시 그룹화할 수 있습니다. `no interface breakout module 1 port 1-6 map 10g-4x` 명령.

====
* 노드에서 Nexus 3232C 클러스터 스위치로 10GbE 및 40/100GbE 연결을 구축하기 위한 계획, 마이그레이션을 완료하고 필요한 문서를 읽었습니다.
* 이 절차에서 지원되는 ONTAP 및 NX-OS 버전은 다음과 같습니다.link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^] .


.사용된 예에 관하여
이 절차의 예에서는 Cisco Nexus 5596 스위치를 Cisco Nexus 3232C 스위치로 교체하는 방법을 설명합니다.  이러한 단계(수정 사항 포함)는 다른 오래된 Cisco 스위치(예: 3132Q-V)에도 사용할 수 있습니다.

이 절차에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 명령 출력은 ONTAP 릴리스에 따라 달라질 수 있습니다.
* 교체할 Nexus 5596 스위치는 *CL1*과 *CL2*입니다.
* Nexus 5596 스위치를 대체하는 Nexus 3232C 스위치는 *C1*과 *C2*입니다.
* *n1_clus1*은 노드 *n1*의 클러스터 스위치 1(CL1 또는 C1)에 연결된 첫 번째 클러스터 논리 인터페이스(LIF)입니다.
* *n1_clus2*는 노드 *n1*의 클러스터 스위치 2(CL2 또는 C2)에 연결된 첫 번째 클러스터 LIF입니다.
* *n1_clus3*는 노드 *n1*의 클러스터 스위치 2(CL2 또는 C2)에 연결된 두 번째 LIF입니다.
* *n1_clus4*는 노드 *n1*의 클러스터 스위치 1(CL1 또는 C1)에 연결된 두 번째 LIF입니다.
* 10GbE 및 40/100GbE 포트의 수는 다음에서 사용 가능한 참조 구성 파일(RCF)에 정의되어 있습니다.link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] .
* 노드는 *n1*, *n2*, *n3*, *n4*입니다.


이 절차의 예에서는 4개의 노드를 사용합니다.

* 두 노드는 4개의 10GbE 클러스터 상호 연결 포트(*e0a*, *e0b*, *e0c*, *e0d*)를 사용합니다.
* 나머지 두 노드는 두 개의 40GbE 클러스터 상호 연결 포트인 *e4a*와 *e4e*를 사용합니다.
+
그만큼link:https://hwu.netapp.com/["_하드웨어 유니버스_"^] 플랫폼의 실제 클러스터 포트를 나열합니다.



.다루는 시나리오
이 절차는 다음과 같은 시나리오를 다룹니다.

* 클러스터는 두 개의 노드가 연결되어 두 개의 Nexus 5596 클러스터 스위치에서 작동하는 것으로 시작합니다.
* 클러스터 스위치 CL2를 C2로 교체합니다(1~19단계):
+
** CL2에 연결된 모든 노드의 모든 클러스터 포트와 LIF의 트래픽은 CL1에 연결된 첫 번째 클러스터 포트와 LIF로 마이그레이션됩니다.
** CL2에 연결된 모든 노드의 모든 클러스터 포트에서 케이블 연결을 끊은 다음, 지원되는 분리 케이블을 사용하여 포트를 새 클러스터 스위치 C2에 다시 연결합니다.
** CL1과 CL2 사이의 ISL 포트 간 케이블을 분리한 다음, 지원되는 분리 케이블을 사용하여 CL1에서 C2까지 포트를 다시 연결합니다.
** 모든 노드의 C2에 연결된 모든 클러스터 포트와 LIF의 트래픽이 되돌려집니다.


* 클러스터 스위치 CL2를 C2로 교체합니다.
+
** CL1에 연결된 모든 노드의 모든 클러스터 포트 또는 LIF의 트래픽은 C2에 연결된 두 번째 클러스터 포트 또는 LIF로 마이그레이션됩니다.
** CL1에 연결된 모든 노드의 모든 클러스터 포트에서 케이블 연결을 끊고 지원되는 분리 케이블을 사용하여 새 클러스터 스위치 C1에 다시 연결합니다.
** CL1과 C2 사이의 ISL 포트 간 케이블을 분리하고, 지원되는 케이블을 사용하여 C1에서 C2까지 다시 연결합니다.
** 모든 노드의 C1에 연결된 모든 클러스터 포트 또는 LIF의 트래픽이 되돌려집니다.


* 클러스터에 두 개의 FAS9000 노드가 추가되었으며, 클러스터 세부 정보를 보여주는 예가 있습니다.


.다음은 무엇인가요?
link:cn5596-prepare-to-migrate.html["이주 준비"].
