---
permalink: switch-cisco-3232c/cn5596-prepare-to-migrate.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Cisco Nexus 3232C 스위치를 AFF 또는 FAS 클러스터에서 클러스터 스위치로 사용할 수 있습니다. 
---
= Nexus 5596 스위치에서 Nexus 3232C 스위치로 마이그레이션 준비
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 5596 스위치를 Cisco Nexus 3232C 스위치로 마이그레이션하기 위해 다음 단계를 따르세요.

.단계
. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_는 유지 관리 기간(시간)입니다.

+
[NOTE]
====
AutoSupport 메시지는 기술 지원팀에 이 유지 관리 작업을 알려 유지 관리 기간 동안 자동 케이스 생성이 억제되도록 합니다.

====
. 구성에 있는 장치에 대한 정보를 표시합니다.
+
`network device-discovery show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 각 클러스터 상호 연결 스위치에 대해 각 노드에 구성된 클러스터 상호 연결 인터페이스의 수를 보여줍니다.

[listing, subs="+quotes"]
----
cluster::> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    CL1                 Ethernet1/1      N5K-C5596UP
            e0b    CL2                 Ethernet1/1      N5K-C5596UP
            e0c    CL2                 Ethernet1/2      N5K-C5596UP
            e0d    CL1                 Ethernet1/2      N5K-C5596UP
n2         /cdp
            e0a    CL1                 Ethernet1/3      N5K-C5596UP
            e0b    CL2                 Ethernet1/3      N5K-C5596UP
            e0c    CL2                 Ethernet1/4      N5K-C5596UP
            e0d    CL1                 Ethernet1/4      N5K-C5596UP
8 entries were displayed.
----
====
. 각 클러스터 인터페이스의 관리 또는 운영 상태를 확인합니다.
+
.. 네트워크 포트 속성을 표시합니다.
+
`network port show -role cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 노드 n1과 n2의 네트워크 포트 속성을 표시합니다.

[listing, subs="+quotes"]
----
cluster::*> *network port show –role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
.. 논리적 인터페이스에 대한 정보를 표시합니다.
+
`network interface show -role cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예제에서는 현재 포트를 포함하여 클러스터의 모든 LIF에 대한 일반 정보를 표시합니다.

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
.. 검색된 클러스터 스위치에 대한 정보를 표시합니다.
+
`system cluster-switch show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 활성 클러스터 스위치를 보여줍니다.

[listing, subs="+quotes"]
----
cluster::*> *system cluster-switch show*

Switch                        Type               Address         Model
----------------------------- ------------------ --------------- ---------------
CL1                           cluster-network    10.10.1.101     NX5596
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP
CL2                           cluster-network    10.10.1.102     NX5596
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP

2 entries were displayed.
----
====


. 요구 사항에 맞게 새로운 3232C 스위치에 적절한 RCF와 이미지가 설치되어 있는지 확인하고 사용자 및 비밀번호, 네트워크 주소, 기타 사용자 지정과 같은 필수적인 사이트 사용자 지정을 수행합니다.
+
[NOTE]
====
이때 두 스위치를 모두 준비해야 합니다.

====
+
RCF와 이미지를 업그레이드해야 하는 경우 다음 단계를 완료해야 합니다.

+
.. NetApp 지원 사이트의 _Cisco 이더넷 스위치_ 페이지로 이동합니다.
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^]

.. 해당 페이지의 표에서 스위치와 필요한 소프트웨어 버전을 확인하세요.
.. 적절한 버전의 RCF를 다운로드하세요.
.. *설명* 페이지에서 *계속*을 선택하고 라이선스 계약에 동의한 다음, *다운로드* 페이지의 지침에 따라 RCF를 다운로드합니다.
.. 적절한 버전의 이미지 소프트웨어를 다운로드하세요.
+
__ONTAP 8.x 이상 클러스터 및 관리 네트워크 스위치 참조 구성 파일__ 다운로드 페이지를 확인한 다음, 적절한 버전을 선택하세요.

+
올바른 버전을 찾으려면 _ONTAP 8.x 이상 클러스터 네트워크 스위치 다운로드 페이지_를 참조하세요.



. 교체할 두 번째 Nexus 5596 스위치와 관련된 LIF를 마이그레이션합니다.
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ -source-node _source-node-name_ - destination-node _node-name_ -destination-port _destination-port-name_`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 노드 n1과 n2에 대한 LIF가 마이그레이션되는 것을 보여줍니다. LIF 마이그레이션은 모든 노드에서 수행되어야 합니다.

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1 -
destination-node n1 -destination-port e0a*
cluster::*> *network interface migrate -vserver Cluster -lif n1_clus3 -source-node n1 -
destination-node n1 -destination-port e0d*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2 -
destination-node n2 -destination-port e0a*
cluster::*> *network interface migrate -vserver Cluster -lif n2_clus3 -source-node n2 -
destination-node n2 -destination-port e0d*
----
====
. 클러스터의 상태를 확인하세요.
+
`network interface show -role cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예는 각 클러스터의 현재 상태를 보여줍니다.

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0a     false
            n1_clus3   up/up      10.10.0.3/24       n1            e0d     false
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0a     false
            n2_clus3   up/up      10.10.0.7/24       n2            e0d     false
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====


.다음은 무엇인가요?
스위치 마이그레이션을 준비한 후에는 다음을 수행할 수 있습니다.link:cn5596-configure-ports.html["포트 구성"] .
