---
permalink: switch-cisco-3232c/migrate-requirements-3232c.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: CN1610 클러스터 스위치를 Cisco Nexus 3232C 클러스터 스위치로 교체할 때 특정 구성 정보, 포트 연결, 케이블 연결 요구사항을 알고 있어야 합니다. 
---
= Cisco Nexus 3232C 클러스터 스위치의 마이그레이션 요구사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C 클러스터 스위치로 마이그레이션하려면 먼저 다음을 수행합니다. 구성 정보, 포트 연결 및 케이블 연결 요구 사항을 검토합니다.



== CN1610 마이그레이션 요구 사항

클러스터 스위치는 다음과 같은 노드 연결을 지원합니다.

* NetApp CN1610: 포트 0/1~0/12(10GbE)
* Cisco Nexus 3232C: 포트 e1/1-30(40 또는 100 또는 4x10GbE)


클러스터 스위치는 다음과 같은 ISL(Inter-Switch Link) 포트를 사용합니다.

* NetApp CN1610: 포트 0/13~0/16(10GbE)
* Cisco Nexus 3232C: 포트 1/31-32(100GbE)


[NOTE]
====
Cisco Nexus 3232C 클러스터 스위치에서 4x10G 브레이크아웃 케이블을 사용해야 합니다.

====
다음 표에는 NetApp CN1610 스위치에서 Cisco Nexus 3232C 클러스터 스위치로 전환할 때 각 단계에서 필요한 케이블 연결 연결이 나와 있습니다.

|===
| 단계 | 설명 | 필수 케이블 


 a| 
초기
 a| 
CN1610 대 CN1610(SFP+에서 SFP+)
 a| 
4 SFP+ 광 파이버 또는 구리 직접 연결 케이블



 a| 
전환
 a| 
3232C(QSFP-SFP+) CN1610
 a| 
1 QSFP 및 4 SFP+ 광 파이버 또는 구리 브레이크아웃 케이블



 a| 
최종
 a| 
3232C~3232C(QSFP에서 QSFP로)
 a| 
QSFP 광 파이버 또는 구리 직접 연결 케이블 2개

|===
해당 참조 구성 파일(RCFs)을 다운로드해야 합니다. 10GbE 및 40/100 GbE 포트 수는 에서 사용할 수 있는 RCFs에 정의되어 있습니다 https://["Cisco ® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] 페이지.

이 절차에서 지원되는 ONTAP 및 NX-OS 버전이 에 나열되어 있습니다 link:https://mysupport.netapp.com/NOW/download/software/cm_switches/.html["Cisco 이더넷 스위치 페이지"^].

이 절차에서 지원되는 ONTAP 및 FASTPATH 버전은 에 나열되어 있습니다 link:http://support.netapp.com/NOW/download/software/cm_switches_ntap/.html["NetApp CN1601 및 CN1610 스위치 페이지"^].



== CN5596 요구 사항

클러스터 스위치는 노드 연결에 다음 포트를 사용합니다.

* 포트 e1/1-40(10GbE): Nexus 5596
* 포트 e1/1-30(10/40/100 GbE): Nexus 3232C
+
** 클러스터 스위치는 다음과 같은 ISL(Inter-Switch Link) 포트를 사용합니다.


* 포트 e1/41-48(10GbE): Nexus 5596
* 포트 e1/31-32(40/100 GbE): Nexus 3232C
+
** 를 클릭합니다 link:https://hwu.netapp.com/["_Hardware Universe _"^] Nexus 3232C 스위치에 대해 지원되는 케이블 연결에 대한 정보를 포함합니다.


* 10GbE 클러스터 연결이 있는 노드는 QSFP-SFP+ 광 파이버 브레이크아웃 케이블 또는 QSFP-SFP+ 구리 브레이크아웃 케이블이 필요합니다.
* 40/100 GbE 클러스터 연결이 있는 노드에는 파이버 케이블 또는 QSFP/QSFP28 구리 직접 연결 케이블이 있는 지원되는 QSFP/QSFP28 광 모듈이 필요합니다.
+
** 클러스터 스위치는 적절한 ISL 케이블 연결을 사용합니다.


* 시작:Nexus 5596(SFP+에서 SFP+로)
+
** 8x SFP+ 파이버 또는 구리 직접 연결 케이블


* 중간: Nexus 5596 ~ Nexus 3232C(QSFP - 4xSFP+ 브레이크아웃)
+
** QSFP-SFP+ 파이버 브레이크아웃 또는 구리 브레이크아웃 케이블 1개


* 최종: Nexus 3232C~Nexus 3232C(QSFP28~QSFP28)
+
** QSFP28 파이버 또는 구리 직접 연결 케이블 2개
+
*** Nexus 3232C 스위치에서 QSFP/QSFP28 포트는 40/100 기가비트 이더넷 또는 4개의 10기가비트 이더넷 모드로 작동할 수 있습니다.
+
기본적으로 40기가비트 이더넷 모드에는 32개의 포트가 있습니다. 이러한 40기가비트 이더넷 포트에는 2 튜플 명명 규칙이 적용됩니다. 예를 들어, 두 번째 40기가비트 이더넷 포트의 번호는 1/2로 지정됩니다. 구성을 40기가비트 이더넷에서 10기가비트 이더넷으로 변경하는 프로세스를 _breakout_이라고 하며, 구성을 10기가비트 이더넷에서 40기가비트 이더넷으로 변경하는 프로세스를 _breakin_이라고 합니다. 40/100 기가비트 이더넷 포트를 10기가비트 이더넷 포트로 분리하면 3 튜플 명명 규칙을 사용하여 결과 포트에 번호가 지정됩니다. 예를 들어, 두 번째 40/100 기가비트 이더넷 포트의 분리 포트는 1/2/1, 1/2/2, 1/2/3 및 1/2/4로 번호가 지정됩니다.

*** Nexus 3232C 스위치 왼쪽에는 1/33 및 1/34라고 하는 SFP+ 포트 2개가 있습니다.
*** Nexus 3232C 스위치에서 일부 포트를 10GbE 또는 40/100GbE에서 실행하도록 구성했습니다.
+
[NOTE]
====
'interface breakout module 1 port 1-6 map 10g-4x' 명령어를 이용하여 처음 6개의 포트를 4x10 GbE 모드로 분리할 수 있다. 마찬가지로 'no interface breakout module 1 port 1-6 map 10g-4x' 명령을 사용하여 브레이크아웃 구성에서 처음 6개의 QSFP+ 포트를 다시 그룹화할 수 있습니다.

====
*** 귀사는 계획, 마이그레이션 작업을 완료했으며 노드에서 Nexus 3232C 클러스터 스위치까지 10GbE 및 40/100 GbE 연결에 대한 필수 문서를 읽었습니다.
*** 이 절차에서 지원되는 ONTAP 및 NX-OS 버전은 에 나와 있습니다 link:http://support.netapp.com/NOW/download/software/cm_switches/.html["Cisco 이더넷 스위치 페이지"^].





