---
permalink: switch-cisco-3232c/migrate-requirements-3232c.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: CN1610 클러스터 스위치를 Cisco Nexus 3232C 클러스터 스위치로 교체하는 경우 특정 구성 정보, 포트 연결 및 케이블 요구 사항을 알고 있어야 합니다. 
---
= Cisco Nexus 3232C 클러스터 스위치에 대한 마이그레이션 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C 클러스터 스위치로 마이그레이션하기 전에 구성 정보, 포트 연결 및 케이블 요구 사항을 검토하세요.



== CN1610 마이그레이션 요구 사항

클러스터 스위치는 다음 노드 연결을 지원합니다.

* NetApp CN1610: 포트 0/1~0/12(10GbE)
* Cisco Nexus 3232C: 포트 e1/1-30(40 또는 100 또는 4x10GbE)


클러스터 스위치는 다음의 ISL(스위치 간 링크) 포트를 사용합니다.

* NetApp CN1610: 포트 0/13~0/16(10GbE)
* Cisco Nexus 3232C: 포트 1/31-32(100GbE)


[NOTE]
====
Cisco Nexus 3232C 클러스터 스위치에서는 4x10G 브레이크아웃 케이블을 사용해야 합니다.

====
다음 표는 NetApp CN1610 스위치에서 Cisco Nexus 3232C 클러스터 스위치로 전환할 때 각 단계에 필요한 케이블 연결을 보여줍니다.

|===
| 단계 | 설명 | 필요한 케이블 


 a| 
초기의
 a| 
CN1610 대 CN1610(SFP+ 대 SFP+)
 a| 
4개의 SFP+ 광섬유 또는 구리 직접 연결 케이블



 a| 
이행
 a| 
CN1610~3232C(QSFP~SFP+)
 a| 
1개의 QSFP 및 4개의 SFP+ 광섬유 또는 구리 분기 케이블



 a| 
결정적인
 a| 
3232C에서 3232C로(QSFP에서 QSFP로)
 a| 
2개의 QSFP 광섬유 또는 구리 직접 연결 케이블

|===
해당 참조 구성 파일(RCF)을 다운로드했어야 합니다.  10GbE 및 40/100GbE 포트의 수는 다음에서 사용 가능한 RCF에 정의되어 있습니다.link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] .

이 절차에서 지원되는 ONTAP 및 NX-OS 버전은 다음에 나열되어 있습니다.link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^] .

이 절차에서 지원되는 ONTAP 및 FASTPATH ​​버전은 다음에 나열되어 있습니다.link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 및 CN1610 스위치"^] .



== CN5596 요구 사항

클러스터 스위치는 노드에 연결하기 위해 다음 포트를 사용합니다.

* 포트 e1/1-40(10GbE): Nexus 5596
* 포트 e1/1-30(10/40/100GbE): Nexus 3232C
+
** 클러스터 스위치는 다음의 ISL(Inter-Switch Link) 포트를 사용합니다.


* 포트 e1/41-48(10GbE): Nexus 5596
* 포트 e1/31-32(40/100GbE): Nexus 3232C
+
** 그만큼link:https://hwu.netapp.com/["_하드웨어 유니버스_"^] Nexus 3232C 스위치에 지원되는 케이블에 대한 정보가 포함되어 있습니다.


* 10GbE 클러스터 연결이 있는 노드에는 QSFP-SFP+ 광섬유 분기 케이블이나 QSFP-SFP+ 구리 분기 케이블이 필요합니다.
* 40/100GbE 클러스터 연결이 있는 노드에는 파이버 케이블이나 QSFP/QSFP28 구리 직접 연결 케이블이 있는 지원되는 QSFP/QSFP28 광 모듈이 필요합니다.
+
** 클러스터 스위치는 적절한 ISL 케이블을 사용합니다.


* 시작: Nexus 5596(SFP+에서 SFP+로)
+
** 8x SFP+ 파이버 또는 구리 직접 연결 케이블


* 중간: Nexus 5596에서 Nexus 3232C로(QSFP에서 4xSFP+로 분리)
+
** 1x QSFP-SFP+ 파이버 브레이크아웃 또는 구리 브레이크아웃 케이블


* 최종: Nexus 3232C에서 Nexus 3232C로(QSFP28에서 QSFP28로)
+
** 2x QSFP28 파이버 또는 구리 직접 연결 케이블
+
*** Nexus 3232C 스위치에서는 QSFP/QSFP28 포트를 40/100 기가비트 이더넷 또는 4 x 10 기가비트 이더넷 모드로 작동할 수 있습니다.
+
기본적으로 40/100 기가비트 이더넷 모드에는 32개의 포트가 있습니다.  이 40개의 기가비트 이더넷 포트는 2-튜플 명명 규칙에 따라 번호가 매겨집니다.  예를 들어, 두 번째 40기가비트 이더넷 포트는 1/2로 번호가 매겨집니다.  40기가비트 이더넷에서 10기가비트 이더넷으로 구성을 변경하는 과정을 _breakout_이라고 하고, 10기가비트 이더넷에서 40기가비트 이더넷으로 구성을 변경하는 과정을 _breakin_이라고 합니다.  40/100 기가비트 이더넷 포트를 10 기가비트 이더넷 포트로 분리하면, 생성된 포트는 3-튜플 명명 규칙을 사용하여 번호가 지정됩니다.  예를 들어, 두 번째 40/100 기가비트 이더넷 포트의 브레이크아웃 포트는 1/2/1, 1/2/2, 1/2/3, 1/2/4로 번호가 매겨집니다.

*** Nexus 3232C 스위치의 왼쪽에는 1/33과 1/34라고 하는 SFP+ 포트 2개가 있습니다.
*** Nexus 3232C 스위치의 일부 포트를 10GbE 또는 40/100GbE로 실행하도록 구성했습니다.
+
[NOTE]
====
다음을 사용하여 첫 번째 6개 포트를 4x10 GbE 모드로 분리할 수 있습니다. `interface breakout module 1 port 1-6 map 10g-4x` 명령.  마찬가지로, 다음을 사용하여 브레이크아웃 구성에서 처음 6개의 QSFP+ 포트를 다시 그룹화할 수 있습니다. `no interface breakout module 1 port 1-6 map 10g-4x` 명령.

====
*** 노드에서 Nexus 3232C 클러스터 스위치로 10GbE 및 40/100GbE 연결을 구축하기 위한 계획, 마이그레이션을 완료하고 필요한 문서를 읽었습니다.
*** 이 절차에서 지원되는 ONTAP 및 NX-OS 버전은 다음과 같습니다.link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^] .





