---
permalink: switch-cisco-3232c/migrate-from-switchless-configure-ports.html 
sidebar: sidebar 
keywords: cisco 3232c, cluster switches 
summary: Cisco Nexus 3232C 스위치를 AFF 또는 FAS 클러스터에서 클러스터 스위치로 사용할 수 있습니다. 
---
= 스위치가 없는 2노드 클러스터에서 스위치가 있는 2노드 클러스터로 마이그레이션하도록 포트를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스위치가 없는 2노드 클러스터에서 Nexus 3232C 스위치의 2노드 스위치 클러스터로 마이그레이션하도록 포트를 구성하려면 다음 단계를 따르십시오.

.단계
. n1_clus1 및 n2_clus1 LIF를 대상 노드의 물리적 포트로 마이그레이션합니다.
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ source-node _source-node-name_ -destination-port _destination-port-name_`

+
.예제 보기
[%collapsible]
====
다음 예제와 같이 각 로컬 노드에 대해 명령을 실행해야 합니다.

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e4e*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e4e*
----
====
. 클러스터 인터페이스가 성공적으로 마이그레이션되었는지 확인합니다.
+
네트워크 인터페이스 show-role cluster

+
.예제 보기
[%collapsible]
====
다음 예에서는 마이그레이션이 완료된 후 n1_clus1 및 n2_clus1 LIF의 "홈" 상태가 "거짓"으로 되었음을 보여 줍니다.

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
 4 entries were displayed.
----
====
. 9단계에서 마이그레이션한 n1_clus1 및 n2_clus1 LIF의 클러스터 포트 종료:
+
'network port modify -node_node -name_-port_port -name_-up-admin false'

+
.예제 보기
[%collapsible]
====
다음 예에 표시된 대로 각 포트에 대해 명령을 실행해야 합니다.

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin false*
cluster::*> *network port modify -node n2 -port e4a -up-admin false*
----
====
. 원격 클러스터 인터페이스의 연결을 확인합니다.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
를 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령입니다.

`network interface check cluster-connectivity start` 및 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
* 참고: * 몇 초 동안 기다린 후 `show` 명령을 실행하여 세부 정보를 표시합니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스에 대해 을 사용할 수도 있습니다 `cluster ping-cluster -node <name>` 연결 상태를 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step5]] 노드 n1의 e4a에서 케이블을 분리합니다.
+
실행 중인 구성을 참조하여 Nexus 3232C 스위치에 지원되는 케이블 연결을 사용하여 스위치 C1(이 예에서는 포트 1/7)의 첫 번째 40GbE 포트를 n1의 e4a에 연결할 수 있습니다.

. 노드 n2의 e4a에서 케이블을 분리합니다.
+
지원되는 케이블 연결을 사용하여 실행 중인 구성을 참조하여 다음 사용 가능한 C1, 포트 1/8의 40GbE 포트에 e4a를 연결할 수 있습니다.

. C1에서 모든 노드 연결 포트를 활성화합니다.
+
Cisco 명령에 대한 자세한 내용은 에 나와 있는 가이드를 참조하십시오 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^].

+
.예제 보기
[%collapsible]
====
다음 예에서는 RCF 'NX3232_RCF_v1.0_24p10g_26p100g.txt'에서 지원되는 구성을 사용하여 Nexus 3232C 클러스터 스위치 C1 및 C2에서 포트 1부터 30까지 사용 중인 것을 보여 줍니다.

[listing, subs="+quotes"]
----
C1# *configure*
C1(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C1(config-if-range)# *no shutdown*
C1(config-if-range)# *exit*
C1(config)# *exit*
----
====
. 각 노드에서 첫 번째 클러스터 포트 e4a를 활성화합니다.
+
'network port modify -node_node -name_-port_port -name_-up-admin TRUE'

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin true*
cluster::*> *network port modify -node n2 -port e4a -up-admin true*
----
====
. 클러스터가 두 노드에 모두 있는지 확인합니다.
+
네트워크 포트 show-role cluster

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

4 entries were displayed.
----
====
. 각 노드에서 마이그레이션된 모든 클러스터 인터커넥트 LIF를 되돌립니다.
+
'network interface revert-vserver cluster-lif_lif-name_'

+
.예제 보기
[%collapsible]
====
다음 예제와 같이 각 LIF를 홈 포트로 개별적으로 되돌려야 합니다.

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver cluster -lif n1_clus1*
cluster::*> *network interface revert -vserver cluster -lif n2_clus1*
----
====
. 모든 LIF가 이제 홈 포트로 되돌려졌는지 확인합니다.
+
네트워크 인터페이스 show-role cluster

+
현재 포트 열에 나열된 모든 포트에 대해 "홈"이라는 값이 표시되어야 합니다. 표시된 값이 false이면 포트가 복구되지 않은 것입니다.

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 각 노드의 클러스터 포트 연결을 표시합니다.
+
네트워크 디바이스 발견 쇼

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    n1                  e4e              FAS9000
----
====
. 각 노드의 콘솔에서 포트 e4a로 clus2를 마이그레이션합니다.
+
'network interface migrate cluster-lif_lif-name_-source-node_source-node-name_-destination-node_destination-node-name_-destination-port_destination-port-name_'

+
.예제 보기
[%collapsible]
====
다음 예에 표시된 대로 각 LIF를 홈 포트로 개별적으로 마이그레이션해야 합니다.

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus2 -source-node n1
-destination-node n1 -destination-port e4a*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus2 -source-node n2
-destination-node n2 -destination-port e4a*
----
====
. 두 노드 모두에서 클러스터 포트 clus2 LIF를 종료합니다.
+
네트워크 포트 수정

+
.예제 보기
[%collapsible]
====
다음 예는 두 노드에서 포트를 종료하면서 "false"로 설정된 지정된 포트를 보여줍니다.

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin false*
cluster::*> *network port modify -node n2 -port e4e -up-admin false*
----
====
. 클러스터 LIF 상태를 확인합니다.
+
네트워크 인터페이스 쇼

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
====
. 노드 n1의 e4e에서 케이블을 분리합니다.
+
실행 중인 구성을 참조하여 Nexus 3232C 스위치 모델에 적합한 케이블을 사용하여 스위치 C2(이 예의 경우 포트 1/7)의 첫 번째 40GbE 포트를 노드 n1의 e4e에 연결할 수 있습니다.

. 노드 n2의 e4e에서 케이블을 분리합니다.
+
실행 중인 구성을 참조하여 Nexus 3232C 스위치 모델에 적합한 케이블을 사용하여 C2, 포트 1/8에서 사용 가능한 다음 40 GbE 포트에 e4e를 연결할 수 있습니다.

. C2에서 모든 노드 대상 포트를 활성화합니다.
+
.예제 보기
[%collapsible]
====
다음 예에서는 RCF 'NX3232C_RCF_v1.0_24p10g_26p100g.txt'에서 지원되는 구성을 사용하여 Nexus 3132Q-V 클러스터 스위치 C1 및 C2에서 포트 1부터 30까지 사용 중인 것을 보여 줍니다.

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C2(config-if-range)# *no shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
----
====
. 각 노드에서 두 번째 클러스터 포트 e4e를 활성화합니다.
+
네트워크 포트 수정

+
.예제 보기
[%collapsible]
====
다음 예에서는 각 노드에서 두 번째 클러스터 포트 e4e가 발생하는 것을 보여 줍니다.

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin true*
cluster::*> *network port modify -node n2 -port e4e -up-admin true*s
----
====
. 각 노드에서 마이그레이션된 모든 클러스터 인터커넥트 LIF를 되돌립니다.
+
네트워크 인터페이스 복원

+
.예제 보기
[%collapsible]
====
다음 예에서는 마이그레이션된 LIF가 홈 포트로 되돌아가는 것을 보여 줍니다.

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver Cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus2*
----
====


.다음 단계
link:migrate-from-switchless-complete-migration.html["마이그레이션을 완료하십시오"]..
