---
permalink: switch-cisco-3232c/migrate-from-two-node-switchless-cluster.html 
sidebar: sidebar 
keywords: migrate, two-node cluster, switchless, cisco nexus 3232c 
summary: 2노드 스위치리스 클러스터가 있는 경우 Cisco Nexus 3232C 클러스터 네트워크 스위치가 포함된 2노드 스위치 클러스터로 중단 없이 마이그레이션할 수 있습니다. 
---
= 2노드 스위치리스 클러스터에서 Cisco Nexus 3232C 클러스터 스위치가 있는 클러스터로 마이그레이션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
2노드 _스위치리스_ 클러스터가 있는 경우 Cisco Nexus 3232C 클러스터 네트워크 스위치를 포함하는 2노드 _스위치_ 클러스터로 마이그레이션할 수 있습니다. 이것은 방해가 되지 않는 절차입니다.



== 검토 요구 사항

.시작하기 전에
다음 설치 및 연결을 확인하세요.

* 노드 연결에 사용할 수 있는 포트가 있습니다.  클러스터 스위치는 ISL(Inter-Switch Link) 포트 e1/31-32를 사용합니다.
* 클러스터 연결에 적합한 케이블이 있습니다.
+
** 10GbE 클러스터 연결이 있는 노드에는 브레이크아웃 파이버 케이블이나 QSFP-SFP+ 구리 브레이크아웃 케이블이 있는 QSFP 광 모듈이 필요합니다.
** 40/100 GbE 클러스터 연결이 있는 노드에는 파이버 케이블이나 QSFP/QSFP28 구리 직접 연결 케이블이 있는 지원되는 QSFP/QSFP28 광 모듈이 필요합니다.
** 클러스터 스위치에는 적절한 ISL 케이블이 필요합니다. 2개의 QSFP28 파이버 또는 구리 직접 연결 케이블입니다.


* 구성이 올바르게 설정되어 작동하고 있습니다.
+
두 노드는 연결되어 있어야 하며 2노드 스위치리스 클러스터 설정에서 작동해야 합니다.

* 모든 클러스터 포트가 *작동* 상태입니다.
* Cisco Nexus 3232C 클러스터 스위치가 지원됩니다.
* 기존 클러스터 네트워크 구성은 다음과 같습니다.
+
** 두 스위치 모두에 중복되고 완벽하게 기능하는 Nexus 3232C 클러스터 인프라
** 스위치의 최신 RCF 및 NX-OS 버전
** 두 스위치 모두의 관리 연결
** 두 스위치 모두에 대한 콘솔 액세스
** 마이그레이션되지 않은 *up* 상태의 모든 클러스터 논리 인터페이스(LIF)
** 스위치의 초기 사용자 정의
** 모든 ISL 포트가 활성화되고 케이블이 연결됨




.예시에 관하여
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* Nexus 3232C 클러스터 스위치, C1 및 C2.
* 노드는 n1과 n2입니다.


이 절차의 예에서는 두 개의 노드를 사용하며, 각각은 두 개의 40GbE 클러스터 상호 연결 포트 e4a 및 e4e를 활용합니다.  그만큼link:https://hwu.netapp.com/["_하드웨어 유니버스_"^] 플랫폼의 클러스터 포트에 대한 세부 정보가 있습니다.

* n1_clus1은 노드 n1의 클러스터 스위치 C1에 연결되는 첫 번째 클러스터 논리 인터페이스(LIF)입니다.
* n1_clus2는 노드 n1의 클러스터 스위치 C2에 연결된 첫 번째 클러스터 LIF입니다.
* n2_clus1은 노드 n2의 클러스터 스위치 C1에 연결된 첫 번째 클러스터 LIF입니다.
* n2_clus2는 노드 n2의 클러스터 스위치 C2에 연결되는 두 번째 클러스터 LIF입니다.
* 10GbE 및 40/100GbE 포트의 수는 다음에서 사용 가능한 참조 구성 파일(RCF)에 정의되어 있습니다.link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] .


[NOTE]
====
이 절차에서는 ONTAP 명령과 Cisco Nexus 3000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 지정되지 않는 한 ONTAP 명령을 사용합니다.

====


== 1단계: 물리적 및 논리적 포트 표시 및 마이그레이션

. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_는 유지 관리 기간(시간)입니다.

+
[NOTE]
====
AutoSupport 메시지는 기술 지원팀에 이 유지 관리 작업을 알려 유지 관리 기간 동안 자동 케이스 생성이 억제되도록 합니다.

====
. 각 클러스터 인터페이스의 관리 또는 운영 상태를 확인합니다.
+
.. 네트워크 포트 속성을 표시합니다.
+
`network port show -role cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -
4 entries were displayed.
----
====
.. 논리적 인터페이스와 지정된 홈 노드에 대한 정보를 표시합니다.
+
`network interface show -role cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ---
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true

4 entries were displayed.
----
====
.. 고급 권한 명령을 사용하여 스위치리스 클러스터 감지가 활성화되었는지 확인하세요.
+
`network options detect-switchless-cluster show``

+
.예를 보여주세요
[%collapsible]
====
다음 예제의 출력은 스위치 없는 클러스터 감지가 활성화되었음을 보여줍니다.

[listing, subs="+quotes"]
----
cluster::*> *network options detect-switchless-cluster show*
Enable Switchless Cluster Detection: true
----
====


. 새로운 3232C 스위치에 적절한 RCF와 이미지가 설치되어 있는지 확인하고 사용자, 비밀번호, 네트워크 주소 추가 등 필요한 사이트 사용자 지정을 수행합니다.
+
이때 두 스위치를 모두 준비해야 합니다.  RCF 및 이미지 소프트웨어를 업그레이드해야 하는 경우 다음 단계를 따라야 합니다.

+
.. NetApp 지원 사이트의 _Cisco 이더넷 스위치_ 페이지로 이동합니다.
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^]

.. 해당 페이지의 표에서 스위치와 필요한 소프트웨어 버전을 확인하세요.
.. 적절한 버전의 RCF를 다운로드하세요.
.. *설명* 페이지에서 *계속*을 클릭하고 라이선스 계약에 동의한 다음, *다운로드* 페이지의 지침에 따라 RCF를 다운로드합니다.
.. 적절한 버전의 이미지 소프트웨어를 다운로드하세요.
+
link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco 클러스터 및 관리 네트워크 스위치 참조 구성 파일 다운로드"^].



. *설명* 페이지에서 *계속*을 클릭하고 라이선스 계약에 동의한 다음, *다운로드* 페이지의 지침에 따라 RCF를 다운로드합니다.
. Nexus 3232C 스위치 C1 및 C2에서 모든 노드 연결 포트 C1 및 C2를 비활성화하지만 ISL 포트 e1/31-32는 비활성화하지 마세요.
+
Cisco 명령에 대한 자세한 내용은 다음 가이드를 참조하세요. https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^] .

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 RCF에서 지원하는 구성을 사용하여 Nexus 3232C 클러스터 스위치 C1 및 C2에서 포트 1~30이 비활성화되는 것을 보여줍니다. `NX3232_RCF_v1.0_24p10g_24p100g.txt` :

[listing, subs="+quotes"]
----
C1# copy running-config startup-config
[########################################] 100% Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit
C2# copy running-config startup-config
[########################################] 100% Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. 지원되는 케이블을 사용하여 C1의 포트 1/31과 1/32를 C2의 동일한 포트에 연결합니다.
. C1 및 C2에서 ISL 포트가 작동하는지 확인하세요.
+
`show port-channel summary`

+
Cisco 명령에 대한 자세한 내용은 다음 가이드를 참조하세요. https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^] .

+
.예를 보여주세요
[%collapsible]
====
다음 예는 Cisco 보여줍니다. `show port-channel summary` C1 및 C2에서 ISL 포트가 작동하는지 확인하는 데 사용되는 명령:

[listing, subs="+quotes"]
----
C1# *show port-channel summary*
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
      Port-
Group Channel      Type   Protocol  Member Ports
-------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------

Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. 스위치에 있는 인접 장치 목록을 표시합니다.
+
Cisco 명령에 대한 자세한 내용은 다음 가이드를 참조하세요. https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^] .

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 Cisco 명령을 보여줍니다. `show cdp neighbors` 스위치의 이웃 장치를 표시하는 데 사용됩니다.

[listing, subs="+quotes"]
----
C1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3232C  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3232C  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
----
====
. 각 노드의 클러스터 포트 연결을 표시합니다.
+
`network device-discovery show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 2노드 스위치리스 클러스터 구성에 대해 표시되는 클러스터 포트 연결을 보여줍니다.

[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
====
. n1_clus1 및 n2_clus1 LIF를 대상 노드의 물리적 포트로 마이그레이션합니다.
+
`network interface migrate -vserver _vserver-name_ -lif _lif-name_ source-node _source-node-name_ -destination-port _destination-port-name_`

+
.예를 보여주세요
[%collapsible]
====
다음 예와 같이 각 로컬 노드에 대해 명령을 실행해야 합니다.

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e4e*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e4e*
----
====




== 2단계: 재할당된 LIF를 종료하고 케이블 연결을 끊습니다.

. 클러스터 인터페이스가 성공적으로 마이그레이션되었는지 확인하세요.
+
`network interface show -role cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 마이그레이션이 완료된 후 n1_clus1 및 n2_clus1 LIF의 "홈" 상태가 "거짓"이 되었음을 보여줍니다.

[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
 4 entries were displayed.
----
====
. 9단계에서 마이그레이션된 n1_clus1 및 n2_clus1 LIF에 대한 클러스터 포트를 종료합니다.
+
`network port modify -node _node-name_ -port _port-name_ -up-admin false`

+
.예를 보여주세요
[%collapsible]
====
다음 예와 같이 각 포트에 대해 명령을 실행해야 합니다.

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin false*
cluster::*> *network port modify -node n2 -port e4a -up-admin false*
----
====
. 원격 클러스터 인터페이스의 연결성을 확인하세요.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
당신은 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령:

`network interface check cluster-connectivity start`그리고 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*참고:* 실행하기 전에 몇 초 동안 기다리십시오. `show` 세부 정보를 표시하는 명령입니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스의 경우 다음을 사용할 수도 있습니다. `cluster ping-cluster -node <name>` 연결성을 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step4]] 노드 n1의 e4a에서 케이블을 분리합니다.
+
실행 구성을 참조하고 Nexus 3232C 스위치에서 지원하는 케이블을 사용하여 스위치 C1의 첫 번째 40GbE 포트(이 예에서는 포트 1/7)를 n1의 e4a에 연결할 수 있습니다.





== 3단계: 클러스터 포트 활성화

. 노드 n2의 e4a에서 케이블을 분리합니다.
+
실행 구성을 참조하고 지원되는 케이블을 사용하여 e4a를 C1의 다음 사용 가능한 40GbE 포트, 포트 1/8에 연결할 수 있습니다.

. C1에서 모든 노드 연결 포트를 활성화합니다.
+
Cisco 명령에 대한 자세한 내용은 다음 가이드를 참조하세요. https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^] .

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 RCF에서 지원하는 구성을 사용하여 Nexus 3232C 클러스터 스위치 C1 및 C2에서 포트 1~30이 활성화되는 것을 보여줍니다. `NX3232_RCF_v1.0_24p10g_26p100g.txt` :

[listing, subs="+quotes"]
----
C1# *configure*
C1(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C1(config-if-range)# *no shutdown*
C1(config-if-range)# *exit*
C1(config)# *exit*
----
====
. 각 노드에서 첫 번째 클러스터 포트 e4a를 활성화합니다.
+
`network port modify -node _node-name_ -port _port-name_ -up-admin true`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4a -up-admin true*
cluster::*> *network port modify -node n2 -port e4a -up-admin true*
----
====
. 두 노드 모두에서 클러스터가 작동하는지 확인하세요.
+
`network port show -role cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port show -role cluster*
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

4 entries were displayed.
----
====
. 각 노드에 대해 마이그레이션된 모든 클러스터 상호 연결 LIF를 되돌립니다.
+
`network interface revert -vserver cluster -lif _lif-name_`

+
.예를 보여주세요
[%collapsible]
====
다음 예와 같이 각 LIF를 개별적으로 홈 포트로 되돌려야 합니다.

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver cluster -lif n1_clus1*
cluster::*> *network interface revert -vserver cluster -lif n2_clus1*
----
====
. 모든 LIF가 이제 홈 포트로 되돌아갔는지 확인하세요.
+
`network interface show -role cluster`

+
그만큼 `Is Home` 열에는 값이 표시되어야 합니다. `true` 나열된 모든 포트에 대해 `Current Port` 열.  표시된 값이 `false` , 포트가 복귀되지 않았습니다.

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====




== 4단계: 재할당된 LIF 활성화

. 각 노드의 클러스터 포트 연결을 표시합니다.
+
`network device-discovery show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    n1                  e4e              FAS9000
----
====
. 각 노드의 콘솔에서 clus2를 포트 e4a로 마이그레이션합니다.
+
`network interface migrate cluster -lif _lif-name_ -source-node _source-node-name_ -destination-node _destination-node-name_ -destination-port _destination-port-name_`

+
.예를 보여주세요
[%collapsible]
====
다음 예와 같이 각 LIF를 개별적으로 홈 포트로 마이그레이션해야 합니다.

[listing, subs="+quotes"]
----
cluster::*> *network interface migrate -vserver cluster -lif n1_clus2 -source-node n1
-destination-node n1 -destination-port e4a*
cluster::*> *network interface migrate -vserver cluster -lif n2_clus2 -source-node n2
-destination-node n2 -destination-port e4a*
----
====
. 두 노드 모두에서 클러스터 포트 clus2 LIF를 종료합니다.
+
`network port modify`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 지정된 포트가 다음과 같이 설정되는 것을 보여줍니다. `false` 두 노드 모두에서 포트를 종료합니다.

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin false*
cluster::*> *network port modify -node n2 -port e4e -up-admin false*
----
====
. 클러스터 LIF 상태를 확인하세요.
+
`network interface show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
====
. 노드 n1의 e4e에서 케이블을 분리합니다.
+
실행 구성을 참조하고 Nexus 3232C 스위치 모델에 적합한 케이블을 사용하여 스위치 C2의 첫 번째 40GbE 포트(이 예에서는 포트 1/7)를 노드 n1의 e4e에 연결할 수 있습니다.

. 노드 n2의 e4e에서 케이블을 분리합니다.
+
Nexus 3232C 스위치 모델에 적합한 케이블을 사용하여 실행 구성을 참조하고 e4e를 C2의 다음 사용 가능한 40GbE 포트, 포트 1/8에 연결할 수 있습니다.

. C2에서 모든 노드 연결 포트를 활성화합니다.
+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 RCF에서 지원하는 구성을 사용하여 Nexus 3132Q-V 클러스터 스위치 C1 및 C2에서 포트 1~30이 활성화되는 것을 보여줍니다. `NX3232C_RCF_v1.0_24p10g_26p100g.txt` :

[listing, subs="+quotes"]
----
C2# *configure*
C2(config)# *int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30*
C2(config-if-range)# *no shutdown*
C2(config-if-range)# *exit*
C2(config)# *exit*
----
====
. 각 노드에서 두 번째 클러스터 포트 e4e를 활성화합니다.
+
`network port modify`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 각 노드에서 두 번째 클러스터 포트 e4e가 활성화되는 것을 보여줍니다.

[listing, subs="+quotes"]
----
cluster::*> *network port modify -node n1 -port e4e -up-admin true*
cluster::*> *network port modify -node n2 -port e4e -up-admin true*s
----
====
. 각 노드에 대해 마이그레이션된 모든 클러스터 상호 연결 LIF를 되돌립니다. `network interface revert`
+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 마이그레이션된 LIF가 홈 포트로 복귀되는 모습을 보여줍니다.

[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver Cluster -lif n1_clus2*
cluster::*> *network interface revert -vserver Cluster -lif n2_clus2*
----
====
. 모든 클러스터 상호 연결 포트가 이제 홈 포트로 돌아갔는지 확인하세요.
+
`network interface show -role cluster`

+
그만큼 `Is Home` 열에는 값이 표시되어야 합니다. `true` 나열된 모든 포트에 대해 `Current Port` 열.  표시된 값이 `false` , 포트가 복귀되지 않았습니다.

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface show -role cluster*
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 모든 클러스터 상호 연결 포트가 다음 위치에 있는지 확인하십시오. `up` 상태:
+
`network port show -role cluster`

. 각 클러스터 포트가 각 노드에 연결된 클러스터 스위치 포트 번호를 표시합니다. `network device-discovery show`
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network device-discovery show*
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1          /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    C2                  Ethernet1/7      N3K-C3232C
n2          /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    C2                  Ethernet1/8      N3K-C3232C
----
====
. 검색 및 모니터링된 클러스터 스위치를 표시합니다.
+
`system cluster-switch show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *system cluster-switch show*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.101      NX3232CV
Serial Number: FOX000001
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP

C2                          cluster-network     10.10.1.102      NX3232CV
Serial Number: FOX000002
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP 2 entries were displayed.
----
====
. 스위치리스 클러스터 감지가 스위치리스 클러스터 옵션을 비활성화로 변경했는지 확인하세요.
+
`network options switchless-cluster show`

. 원격 클러스터 인터페이스의 연결성을 확인하세요.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
당신은 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령:

`network interface check cluster-connectivity start`그리고 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*참고:* 실행하기 전에 몇 초 동안 기다리십시오. `show` 세부 정보를 표시하는 명령입니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2         n2-clus1         none
       3/5/2022 19:21:20 -06:00   n1_clus2         n2_clus2         none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2         n1_clus1         none
       3/5/2022 19:21:20 -06:00   n2_clus2         n1_clus2         none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스의 경우 다음을 사용할 수도 있습니다. `cluster ping-cluster -node <name>` 연결성을 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step16]] 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.다음은 무엇인가요?
link:../switch-cshm/config-overview.html["스위치 상태 모니터링 구성"].
