---
permalink: switch-cisco-3232c/migrate-from-switchless-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Cisco Nexus 32c 스위치를 구성하기 전에 프로세스 개요 및 명명법을 검토하십시오. 
---
= 마이그레이션 요구 사항
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
스위치가 없는 2노드 클러스터가 있는 경우 Cisco Nexus 3232C 클러스터 네트워크 스위치를 포함하는 2노드 스위치 클러스터로 마이그레이션할 수 있습니다. 이는 무중단으로 수행할 수 있는 절차입니다.

.시작하기 전에
다음 설치 및 연결을 확인합니다.

* 노드 접속에 포트를 사용할 수 있습니다. 클러스터 스위치는 ISL(Inter-Switch Link) 포트 e1/31-32를 사용합니다.
* 클러스터 연결에 적합한 케이블이 있습니다.
+
** 10GbE 클러스터 연결이 있는 노드에는 브레이크아웃 파이버 케이블 또는 QSFP-SFP+ 구리 브레이크아웃 케이블이 있는 QSFP 광 모듈이 필요합니다.
** 40/100 GbE 클러스터 연결이 있는 노드에는 파이버 케이블 또는 QSFP/QSFP28 구리 직접 연결 케이블이 있는 지원되는 QSFP/QSFP28 광 모듈이 필요합니다.
** 클러스터 스위치에는 적절한 ISL 케이블 연결이 필요합니다.
+
*** QSFP28 파이버 또는 구리 직접 연결 케이블 2개




* 구성이 올바르게 설정되고 작동합니다.
+
스위치가 없는 2노드 클러스터 설정에서 2노드가 연결되어 작동 중이어야 합니다.

* 모든 클러스터 포트는 * UP * 상태입니다.
* Cisco Nexus 3232C 클러스터 스위치가 지원됩니다.
* 기존 클러스터 네트워크 구성은 다음과 같습니다.
+
** 두 스위치 모두에서 중복되고 완벽하게 작동하는 Nexus 3232C 클러스터 인프라
** 최신 RCF 및 NX-OS 버전을 스위치에서 사용할 수 있습니다
** 두 스위치 모두에서 관리 접속 구성
** 두 스위치에 대한 콘솔 액세스
** 마이그레이션 없이 * UP * 상태인 모든 클러스터 논리 인터페이스(LIF
** 스위치의 초기 사용자 정의
** 모든 ISL 포트 설정 및 케이블 연결




.사용된 예제에 대해 설명합니다
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* Nexus 3232C 클러스터 스위치, * C1 * 및 * C2 *.
* 노드는 * n1 * 및 * n2 * 입니다.


이 절차의 예에서는 각각 2개의 40GbE 클러스터 인터커넥트 포트 * e4a * 및 * e4e * 를 사용하는 2개의 노드를 사용합니다. 는 link:https://hwu.netapp.com/["_Hardware Universe _"^]사용자 플랫폼의 클러스터 포트에 대한 세부 정보를 제공합니다.

* * n1_clus1 * 은 클러스터 스위치에 연결되는 첫 번째 클러스터 논리 인터페이스(LIF)입니다 * n1 * 노드의 경우 * C1 *.
* * n1_clus2 * 는 클러스터 스위치에 연결되는 첫 번째 클러스터 LIF입니다 * n1 * 노드의 경우 * C2 *.
* * n2_clus1 * 은 클러스터 스위치에 연결되는 첫 번째 클러스터 LIF입니다. * n2 * 노드의 경우 * C1 *.
* * n2_clus2 * 는 클러스터 스위치에 연결할 두 번째 클러스터 LIF입니다. * c2 * for n2 *.
* 10GbE 및 40/100 GbE 포트 수는 에서 사용할 수 있는 RCFs(참조 구성 파일)에 정의되어 있습니다 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] 페이지.


[NOTE]
====
이 절차를 수행하려면 ONTAP 명령과 Cisco Nexus 3000 시리즈 스위치 명령을 모두 사용해야 합니다. ONTAP 명령은 별도의 표시가 없는 한 사용됩니다.

====
.다음 단계
link:migrate-from-switchless-prepare-to-migrate.html["마이그레이션을 준비합니다"]..
