---
permalink: switch-cisco-3232c/migrate-from-switchless-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3232c switch, 
summary: Cisco Nexus 3232c 스위치를 구성하기 전에 프로세스 개요와 명명법을 살펴보세요. 
---
= 이주 요구 사항
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
2노드 스위치리스 클러스터가 있는 경우 Cisco Nexus 3232C 클러스터 네트워크 스위치를 포함하는 2노드 스위치 클러스터로 마이그레이션할 수 있습니다. 이것은 방해가 되지 않는 절차입니다.

.시작하기 전에
다음 설치 및 연결을 확인하세요.

* 노드 연결에 사용할 수 있는 포트가 있습니다.  클러스터 스위치는 ISL(Inter-Switch Link) 포트 e1/31-32를 사용합니다.
* 클러스터 연결에 적합한 케이블이 있습니다.
+
** 10GbE 클러스터 연결이 있는 노드에는 브레이크아웃 파이버 케이블이나 QSFP-SFP+ 구리 브레이크아웃 케이블이 있는 QSFP 광 모듈이 필요합니다.
** 40/100GbE 클러스터 연결이 있는 노드에는 파이버 케이블이나 QSFP/QSFP28 구리 직접 연결 케이블이 있는 지원되는 QSFP/QSFP28 광 모듈이 필요합니다.
** 클러스터 스위치에는 적절한 ISL 케이블이 필요합니다.
+
*** 2x QSFP28 파이버 또는 구리 직접 연결 케이블.




* 구성이 올바르게 설정되어 작동하고 있습니다.
+
두 노드는 연결되어 있어야 하며 2노드 스위치리스 클러스터 설정에서 작동해야 합니다.

* 모든 클러스터 포트가 *작동* 상태입니다.
* Cisco Nexus 3232C 클러스터 스위치가 지원됩니다.
* 기존 클러스터 네트워크 구성은 다음과 같습니다.
+
** 두 스위치 모두에 중복되고 완벽하게 기능하는 Nexus 3232C 클러스터 인프라
** 스위치의 최신 RCF 및 NX-OS 버전
** 두 스위치 모두의 관리 연결
** 두 스위치 모두에 대한 콘솔 액세스
** 마이그레이션되지 않은 *up* 상태의 모든 클러스터 논리 인터페이스(LIF)
** 스위치의 초기 사용자 정의
** 모든 ISL 포트가 활성화되고 케이블이 연결됨




.사용된 예에 관하여
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* Nexus 3232C 클러스터 스위치, *C1* 및 *C2*.
* 노드는 *n1*과 *n2*입니다.


이 절차의 예에서는 두 개의 노드를 사용하며, 각 노드는 두 개의 40GbE 클러스터 상호 연결 포트 *e4a*와 *e4e*를 사용합니다.  그만큼link:https://hwu.netapp.com/["_하드웨어 유니버스_"^] 플랫폼의 클러스터 포트에 대한 세부 정보가 있습니다.

* *n1_clus1*은 노드 *n1*의 클러스터 스위치 *C1*에 연결된 첫 번째 클러스터 논리 인터페이스(LIF)입니다.
* *n1_clus2*는 노드 *n1*의 클러스터 스위치 *C2*에 연결된 첫 번째 클러스터 LIF입니다.
* *n2_clus1*은 노드 *n2*의 클러스터 스위치 *C1*에 연결된 첫 번째 클러스터 LIF입니다.
* *n2_clus2*는 노드 *n2*의 클러스터 스위치 *C2*에 연결되는 두 번째 클러스터 LIF입니다.
* 10GbE 및 40/100GbE 포트의 수는 다음에서 사용 가능한 참조 구성 파일(RCF)에 정의되어 있습니다. https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] 페이지.


[NOTE]
====
이 절차에서는 ONTAP 명령과 Cisco Nexus 3000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 지정되지 않는 한 ONTAP 명령을 사용합니다.

====
.다음은 무엇인가요?
link:migrate-from-switchless-prepare-to-migrate.html["이주 준비"].
