---
permalink: switch-cisco-3232c/migrate-requirements-3232c.html 
sidebar: sidebar 
keywords: migrate, cn1610 switch, cisco nexus 3232c cluster 
summary: CN1610 클러스터 스위치를 Cisco Nexus 3232C 클러스터 스위치로 교체하기 전에 마이그레이션 요구 사항을 검토하십시오. 
---
= Cisco Nexus 3232C 클러스터 스위치의 마이그레이션 요구 사항을 검토합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CN1610 클러스터 스위치를 Cisco Nexus 3232C 클러스터 스위치로 교체하기 전에 구성 정보, 포트 연결 및 케이블 요구 사항을 검토하십시오.



[[cn1610-migrate-requirements]]
== CN1610 마이그레이션 요구 사항

클러스터 스위치는 다음 노드 연결을 지원합니다.

* NetApp CN1610: 포트 0/1 ~ 0/12 (10 GbE)
* Cisco Nexus 3232C: 포트 e1/1-30 (40 또는 100 또는 4x10GbE)


클러스터 스위치는 다음과 같은 스위치 간 링크(ISL) 포트를 사용합니다.

* NetApp CN1610: 포트 0/13 ~ 0/16 (10 GbE)
* Cisco Nexus 3232C: 포트 1/31-32 (100GbE)


[NOTE]
====
Cisco Nexus 3232C 클러스터 스위치에서는 4x10G 브레이크아웃 케이블을 사용해야 합니다.

====
다음 표는 NetApp CN1610 스위치에서 Cisco Nexus 3232C 클러스터 스위치로 전환하는 과정에서 각 단계별로 필요한 케이블 연결을 보여줍니다.

|===
| 단계 | 설명 | 필요한 케이블 


 a| 
초기의
 a| 
CN1610에서 CN1610(SFP+에서 SFP+)
 a| 
4개의 SFP+ 광섬유 또는 구리 직접 연결 케이블



 a| 
전환
 a| 
CN1610에서 3232C로 (QSFP에서 SFP+로)
 a| 
1개의 QSFP 및 4개의 SFP+ 광섬유 또는 구리 브레이크아웃 케이블



 a| 
최종
 a| 
3232C에서 3232C로 (QSFP에서 QSFP로)
 a| 
2개의 QSFP 광섬유 또는 구리 직접 연결 케이블

|===
해당 참조 구성 파일(RCF)을 다운로드해야 합니다. 10GbE 및 40/100GbE 포트 수는 link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^]에서 제공되는 RCF에 정의되어 있습니다.

이 절차에서 지원되는 ONTAP 및 NX-OS 버전은 link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^]에 나열되어 있습니다.

이 절차에서 지원되는 ONTAP 및 FASTPATH 버전은 link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 및 CN1610 스위치"^]에 나열되어 있습니다.



[[cn5596-requirements]]
== CN5596 요구사항

클러스터 스위치는 노드와의 연결을 위해 다음 포트를 사용합니다.

* 포트 e1/1-40(10 GbE): Nexus 5596
* 포트 e1/1-30 (10/40/100 GbE): Nexus 3232C
+
** 클러스터 스위치는 다음과 같은 ISL(Inter-Switch Link) 포트를 사용합니다.


* 포트 e1/41-48(10GbE): Nexus 5596
* 포트 e1/31-32 (40/100 GbE): Nexus 3232C
+
** link:https://hwu.netapp.com/["Hardware Universe"^]에는 Nexus 3232C 스위치에서 지원되는 케이블에 대한 정보가 포함되어 있습니다.


* 10GbE 클러스터 연결을 사용하는 노드에는 QSFP-SFP+ 광섬유 브레이크아웃 케이블 또는 QSFP-SFP+ 구리 브레이크아웃 케이블이 필요합니다.
* 40/100 GbE 클러스터 연결이 있는 노드에는 광섬유 케이블을 사용하는 지원되는 QSFP/QSFP28 광 모듈 또는 QSFP/QSFP28 구리 직접 연결 케이블이 필요합니다.
+
** 클러스터 스위치는 적절한 ISL 케이블을 사용합니다.


* 시작: Nexus 5596 (SFP+에서 SFP+로)
+
** 8x SFP+ 광섬유 또는 구리 직접 연결 케이블


* 임시: Nexus 5596에서 Nexus 3232C로 (QSFP에서 4xSFP+ 브레이크아웃)
+
** 1x QSFP-SFP+ 광섬유 브레이크아웃 또는 구리 브레이크아웃 케이블


* 최종: Nexus 3232C에서 Nexus 3232C로 (QSFP28에서 QSFP28로)
+
** 2x QSFP28 광섬유 또는 구리 직접 연결 케이블
+
*** Nexus 3232C 스위치에서는 QSFP/QSFP28 포트를 40/100기가비트 이더넷 모드 또는 4 x 10기가비트 이더넷 모드로 작동시킬 수 있습니다.
+
기본적으로 40/100기가비트 이더넷 모드에는 32개의 포트가 있습니다. 이 40기가비트 이더넷 포트는 2-튜플 명명 규칙을 사용하여 번호가 매겨집니다. 예를 들어, 두 번째 40기가비트 이더넷 포트는 1/2로 번호가 매겨집니다. 40기가비트 이더넷에서 10기가비트 이더넷으로 구성을 변경하는 과정을 _breakout_이라고 하고, 10기가비트 이더넷에서 40기가비트 이더넷으로 구성을 변경하는 과정을 _breakin_이라고 합니다. 40/100기가비트 이더넷 포트를 10기가비트 이더넷 포트로 브레이크아웃하면, 결과적으로 생성되는 포트들은 3-튜플 명명 규칙을 사용하여 번호가 매겨집니다. 예를 들어, 두 번째 40/100기가비트 이더넷 포트의 브레이크아웃 포트는 1/2/1, 1/2/2, 1/2/3, 1/2/4로 번호가 매겨집니다.

*** Nexus 3232C 스위치의 왼쪽에는 1/33 및 1/34라고 하는 2개의 SFP+ 포트가 있습니다.
*** Nexus 3232C 스위치의 일부 포트를 10GbE 또는 40/100GbE로 구성했습니다.
+
[NOTE]
====
 `interface breakout module 1 port 1-6 map 10g-4x` 명령어를 사용하면 처음 6개 포트를 4x10 GbE 모드로 분리할 수 있습니다. 마찬가지로,  `no interface breakout module 1 port 1-6 map 10g-4x` 명령어를 사용하면 분리 구성에서 처음 6개 QSFP+ 포트를 다시 그룹화할 수 있습니다.

====
*** 노드에서 Nexus 3232C 클러스터 스위치로의 10GbE 및 40/100GbE 연결에 대한 계획, 마이그레이션 및 필요한 문서 검토를 완료했습니다.
*** 이 절차에서 지원되는 ONTAP 및 NX-OS 버전은 link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^]에 있습니다.





