---
permalink: switch-cisco-3232c/replace-storage-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus, 3232c storage switch 
summary: 특정 작업 순서를 수행하면 결함이 있는 Cisco Nexus 3232C 스토리지 스위치를 중단 없이 교체할 수 있습니다. 
---
= Cisco Nexus 3232C 스토리지 스위치 교체
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
결함이 있는 Cisco Nexus 3232C 스토리지 스위치를 교체하려면 다음 단계를 따르세요. 이는 방해가 되지 않는 절차입니다.



== 검토 요구 사항

기존 네트워크 구성에는 다음과 같은 특성이 있어야 합니다.

* Cisco 이더넷 스위치 페이지에는 스위치에 설치된 최신 RCF 및 NX-OS 버전이 있습니다.
* 두 스위치 모두에 관리 연결이 있어야 합니다.
+
[NOTE]
====
모든 문제 해결 단계가 완료되어 스위치를 교체해야 한다는 것을 확인하세요.

====


교체용 Cisco Nexus 3232C 스위치는 다음과 같은 특성을 가져야 합니다.

* 관리 네트워크 연결이 작동해야 합니다.
* 교체 스위치에 대한 콘솔 접근이 가능해야 합니다.
* 적절한 RCF 및 NX-OS 운영 체제 이미지를 스위치에 로드해야 합니다.
* 스위치의 초기 사용자 정의가 완료되어야 합니다.




== 스위치를 교체하세요

이 절차에서는 두 번째 Nexus 3232C 스토리지 스위치 S2를 새로운 3232C 스위치 NS2로 교체합니다.  두 노드는 node1과 node2입니다.



=== 1단계: 교체할 스위치가 S2인지 확인하세요

. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_는 유지 관리 기간(시간)입니다.

+
[NOTE]
====
AutoSupport 메시지는 기술 지원팀에 이 유지 관리 작업을 알려 유지 관리 기간 동안 자동 케이스 생성이 억제되도록 합니다.

====
. 스토리지 노드 포트의 상태를 확인하여 스토리지 스위치 S1에 연결되어 있는지 확인하세요.
+
`storage port show -port-type ENET`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                     VLAN
Node               Port Type  Mode    (Gb/s) State    Status      ID
------------------ ---- ----- ------- ------ -------- --------- ----
node1
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
node2
                   e3a  ENET  storage    100 enabled  online      30
                   e3b  ENET  storage      0 enabled  offline     30
                   e7a  ENET  storage      0 enabled  offline     30
                   e7b  ENET  storage      0 enabled  offline     30
----
====
. 저장 스위치 S1을 사용할 수 있는지 확인하세요.
+
`network device-discovery show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- ----------------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
----
====
. 실행하다 `show lldp neighbors` 작동 스위치에서 명령을 실행하여 두 노드와 모든 선반을 볼 수 있는지 확인하세요.
+
`show lldp neighbors`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
S1# *show lldp neighbors*
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID               Local Intf      Hold-time  Capability  Port ID
node1                   Eth1/1          121        S           e3a
node2                   Eth1/2          121        S           e3a
SHFGD2008000011         Eth1/5          121        S           e0a
SHFGD2008000011         Eth1/6          120        S           e0a
SHFGD2008000022         Eth1/7          120        S           e0a
SHFGD2008000022         Eth1/8          120        S           e0a
----
====




=== 2단계: 케이블링 구성

. [[5]]저장 시스템의 선반 포트를 확인하세요.
+
`storage shelf port show -fields remote-device,remote-port`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage shelf port show -fields remote-device,remote-port*

shelf  id  remote-port  remote-device
-----  --  -----------  -------------
3.20   0   Ethernet1/5  S1
3.20   1   -            -
3.20   2   Ethernet1/6  S1
3.20   3   -            -
3.30   0   Ethernet1/7  S1
3.20   1   -            -
3.30   2   Ethernet1/8  S1
3.20   3   -            -
----
====
. 저장 스위치 S2에 연결된 모든 케이블을 제거합니다.
. 모든 케이블을 교체 스위치 NS2에 다시 연결합니다.




=== 3단계: 스위치 NS2의 모든 장치 구성 확인

. 스토리지 노드 포트의 상태를 확인하세요.
+
`storage port show -port-type ENET`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ------------ ---
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
====
. 두 스위치가 모두 사용 가능한지 확인하세요.
+
`network device-discovery show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
node1/cdp
            e3a    S1                        Ethernet1/1       NX3232C
            e4a    node2                     e4a               AFF-A700
            e4e    node2                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/1       NX3232C
node1/lldp
            e3a    S1                        Ethernet1/1       -
            e4a    node2                     e4a               -
            e4e    node2                     e4e               -
            e7b    NS2                       Ethernet1/1       -
node2/cdp
            e3a    S1                        Ethernet1/2       NX3232C
            e4a    node1                     e4a               AFF-A700
            e4e    node1                     e4e               AFF-A700
            e7b    NS2                       Ethernet1/2       NX3232C
node2/lldp
            e3a    S1                        Ethernet1/2       -
            e4a    node1                     e4a               -
            e4e    node1                     e4e               -
            e7b    NS2                       Ethernet1/2       -
----
====
. 스토리지 시스템의 선반 포트를 확인하세요.
+
`storage shelf port show -fields remote-device,remote-port`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage shelf port show -fields remote-device,remote-port*
shelf id remote-port remote-device
----- -- ----------- -------------
3.20  0  Ethernet1/5 S1
3.20  1  Ethernet1/5 NS2
3.20  2  Ethernet1/6 S1
3.20  3  Ethernet1/6 NS2
3.30  0  Ethernet1/7 S1
3.20  1  Ethernet1/7 NS2
3.30  2  Ethernet1/8 S1
3.20  3  Ethernet1/8 NS2
----
====
. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.다음은 무엇인가요?
link:../switch-cshm/config-overview.html["스위치 상태 모니터링 구성"]
