---
permalink: switch-cisco-3232c/task-how-to-replace-a-cisco-nexus-3232c-cluster-switch.html 
sidebar: sidebar 
keywords: replace, cisco nexus 3232c, cluster switch 
summary: 특정 작업 시퀀스를 실행하여 클러스터에서 결함 있는 Cisco Nexus 3232C 스위치를 중단 없이 교체할 수 있습니다. 
---
= Cisco Nexus 3232C 클러스터 스위치를 교체하는 방법
:icons: font
:imagesdir: ../media/


[role="lead"]
특정 작업 시퀀스를 실행하여 클러스터에서 결함 있는 Cisco Nexus 3232C 스위치를 중단 없이 교체할 수 있습니다.



== 필요한 것

기존 클러스터 및 네트워크 구성에는 다음과 같은 특성이 있어야 합니다.

* Nexus 3232C 클러스터 인프라는 두 스위치에서 모두 중복되고 완전히 작동해야 합니다.
+
Cisco 이더넷 스위치 페이지에는 스위치에 최신 RCF 및 NX-OS 버전이 있습니다.

* 모든 클러스터 포트는 UP 상태여야 합니다.
* 두 스위치 모두에 관리 연결이 있어야 합니다.
* 모든 클러스터 논리 인터페이스(LIF)는 UP 상태여야 하며 마이그레이션되지 않습니다.


교체 Cisco Nexus 3232C 스위치의 특징은 다음과 같습니다.

* 관리 네트워크 연결이 작동해야 합니다.
* 교체 스위치에 대한 콘솔 액세스가 있어야 합니다.
* 적절한 RCF 및 NX-OS 운영 체제 이미지를 스위치에 로드해야 합니다.
* 스위치의 초기 사용자 정의를 완료해야 합니다.




== 이 작업에 대해

* 절차 요약 *

* * 클러스터 포트를 표시 및 스위치 C2로 마이그레이션(1-7단계) *
* * 스위치 CL2에서 스위치 C2로 ISL 케이블을 다시 연결한 다음 ISL을 스위치 CL1 및 C2로 마이그레이션합니다(8-14단계) *
* * 모든 LIF를 원래 할당된 포트로 되돌리기(15-18단계) *
* * 모든 포트와 LIF가 올바르게 마이그레이션되었는지 확인(19-21단계) *


이 절차는 두 번째 Nexus 3232C 클러스터 스위치 CL2를 새 3232C 스위치 C2로 대체합니다. 이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 4개의 노드는 n1, n2, n3 및 n4입니다.
* N1_clus1 은 노드 n1의 클러스터 스위치 C1에 연결된 첫 번째 클러스터 논리 인터페이스(LIF)입니다.
* N1_clus2 는 노드 n1의 클러스터 스위치 CL2 또는 C2에 연결된 첫 번째 클러스터 LIF입니다.
* N1_clus3 은 노드 n1의 클러스터 스위치 C2에 연결된 두 번째 LIF입니다.
* N1_clus4 는 노드 n1에 대해 클러스터 스위치 CL1에 연결된 두 번째 LIF입니다.


10GbE 및 40/100 GbE 포트 수는 에서 사용할 수 있는 RCFs(참조 구성 파일)에 정의되어 있습니다 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] 페이지.

이 절차의 예에서는 4개의 노드를 사용합니다. 노드 중 2개에서 10GB 클러스터 인터커넥트 포트 4개, e0a, e0b, e0c, e0d를 사용합니다. 다른 두 노드는 두 개의 40GB 클러스터 인터커넥트 포트(e4a 및 e4e)를 사용합니다. Hardware Universe를 참조하여 플랫폼에 맞는 클러스터 포트를 확인하십시오.

https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^]

이 절차에서는 다음 시나리오에 대해 설명합니다.

* 클러스터는 처음에 2개의 Nexus 3232C 클러스터 스위치인 CL1 및 CL2에 4개의 노드를 연결합니다.
* 클러스터 스위치 CL2를 C2로 교체하려는 경우(1-21단계):
+
** 각 노드에서 클러스터 스위치 CL2에 연결된 클러스터 LIF를 클러스터 스위치 CL1에 연결된 클러스터 포트로 마이그레이션합니다.
** 클러스터 스위치 CL2의 모든 포트에서 케이블 연결을 끊고 교체용 클러스터 스위치 C2의 동일한 포트에 케이블을 다시 연결합니다.
** 마이그레이션된 클러스터 LIF를 각 노드에서 되돌릴 수 있습니다.






== 단계

. 이 클러스터에서 AutoSupport가 활성화되어 있는 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
'System node AutoSupport invoke-node * -type all-message maINT=xh'

+
_x_는 유지보수 기간(시간)입니다.

+
[NOTE]
====
AutoSupport 메시지는 유지보수 기간 동안 자동 케이스 생성이 억제되도록 이 유지보수 작업의 기술 지원에 알립니다.

====
. 구성에 있는 장치에 대한 정보를 표시합니다.
+
네트워크 디바이스 발견 쇼

+
[listing]
----
cluster::> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface         Platform
----------- ------ ------------------- ----------------  ----------------
n1         /cdp
            e0a    CL1                 Ethernet1/1/1    N3K-C3232C
            e0b    CL2                 Ethernet1/1/1    N3K-C3232C
            e0c    CL2                 Ethernet1/1/2    N3K-C3232C
            e0d    CL1                 Ethernet1/1/2    N3K-C3232C

n2         /cdp
            e0a    CL1                 Ethernet1/1/3    N3K-C3232C
            e0b    CL2                 Ethernet1/1/3    N3K-C3232C
            e0c    CL2                 Ethernet1/1/4    N3K-C3232C
            e0d    CL1                 Ethernet1/1/4    N3K-C3232C

n3         /cdp
            e4a    CL1                 Ethernet1/7      N3K-C3232C
            e4e    CL2                 Ethernet1/7      N3K-C3232C

n4         /cdp
            e4a    CL1                 Ethernet1/8      N3K-C3232C
            e4e    CL2                 Ethernet1/8      N3K-C3232C

12 entries were displayed
----
. 각 클러스터 인터페이스의 관리 또는 운영 상태를 확인합니다.
+
.. 네트워크 포트 속성을 표시합니다.
+
네트워크 포트 show-role cluster

+
[listing]
----
cluster::*> network port show -role cluster
(network port show)
Node: n1
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- ------------
e0a       Cluster      Cluster          up   9000 auto/10000  -
e0b       Cluster      Cluster          up   9000 auto/10000  -
e0c       Cluster      Cluster          up   9000 auto/10000  -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                      Ignore
                                                  Speed(Mbps) Health  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status  Status
--------- ------------ ---------------- ---- ---- ----------- ------------
e0a       Cluster      Cluster          up   9000  auto/10000 -
e0b       Cluster      Cluster          up   9000  auto/10000 -
e0c       Cluster      Cluster          up   9000  auto/10000 -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

12 entries were displayed.
----
.. 논리 인터페이스(LIF)에 대한 정보를 표시합니다.
+
네트워크 인터페이스 show-role cluster

+
[listing]
----
cluster::*> network interface show -role cluster
             Logical    Status     Network          Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port   Home
----------- ---------- ---------- ------------------ ------------- ------- ---
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e0a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e0e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e0a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e0e     true

12 entries were displayed.
----
.. 검색된 클러스터 스위치를 표시합니다.
+
'system cluster-switch show'

+
다음 출력 예에서는 클러스터 스위치를 표시합니다.

+
[listing]
----
cluster::> system cluster-switch show
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                         cluster-network    10.10.1.101      NX3232C
Serial Number: FOX000001
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                   7.0(3)I6(1)
Version Source: CDP

CL2                         cluster-network    10.10.1.102      NX3232C
Serial Number: FOX000002
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                   7.0(3)I6(1)
Version Source: CDP

2 entries were displayed.
----


. 새 Nexus 3232C 스위치에 적절한 RCF 및 이미지가 설치되었는지 확인하고 필요한 사이트 사용자 지정을 수행합니다.
+
.. NetApp Support 사이트 로 이동합니다.
+
http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. Cisco 이더넷 스위치 * 페이지로 이동하여 표에 필요한 소프트웨어 버전을 기록합니다.
+
https://mysupport.netapp.com/NOW/download/software/cm_switches/["Cisco 이더넷 스위치"^]

.. RCF의 적절한 버전을 다운로드합니다.
.. 설명 * 페이지에서 * 계속 * 을 클릭하고 사용권 계약에 동의한 다음 * 다운로드 * 페이지로 이동합니다.
.. Cisco ® 클러스터 및 관리 네트워크 스위치 참조 구성 파일 다운로드 * 페이지에서 올바른 버전의 이미지 소프트웨어를 다운로드하십시오.
+
http://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 클러스터 및 관리 네트워크 스위치 참조 구성 파일 다운로드"^]



. 클러스터 LIF를 교체 스위치 C2에 연결된 물리적 노드 포트로 마이그레이션합니다.
+
'network interface migrate-vserver cluster-lif_lif-name_-source-node_node-name_-destination-node_node-name_-destination-port_port-name_'

+
다음 예에 표시된 대로 모든 클러스터 LIF를 개별적으로 마이그레이션해야 합니다.

+
[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1 –destination-
node n1 -destination-port e0a
cluster::*> network interface migrate -vserver Cluster -lif n1_clus3 -source-node n1 –destination-
node n1 -destination-port e0d
cluster::*> network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2 –destination-
node n2 -destination-port e0a
cluster::*> network interface migrate -vserver Cluster -lif n2_clus3 -source-node n2 –destination-
node n2 -destination-port e0d
cluster::*> network interface migrate -vserver Cluster -lif n3_clus2 -source-node n3 –destination-
node n3 -destination-port e4a
cluster::*> network interface migrate -vserver Cluster -lif n4_clus2 -source-node n4 –destinationnode
n4 -destination-port e4a
----
. 클러스터 포트의 상태와 해당 홈 지정을 확인합니다.
+
네트워크 인터페이스 show-role cluster

+
[listing]
----
cluster::*> network interface show -role cluster
(network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0a     false
            n1_clus3   up/up      10.10.0.3/24       n1            e0d     false
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0a     false
            n2_clus3   up/up      10.10.0.7/24       n2            e0d     false
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4a     false
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4a     false
12 entries were displayed.
----
. 원래 스위치 CL2에 물리적으로 연결된 클러스터 상호 연결 포트를 종료합니다. 'network port modify -node_node -name_-port_port -name_-up-admin false'
+
다음 예는 모든 노드에서 클러스터 인터커넥트 포트가 종료되었음을 보여 줍니다.

+
[listing]
----
cluster::*> network port modify -node n1 -port e0b -up-admin false
cluster::*> network port modify -node n1 -port e0c -up-admin false
cluster::*> network port modify -node n2 -port e0b -up-admin false
cluster::*> network port modify -node n2 -port e0c -up-admin false
cluster::*> network port modify -node n3 -port e4e -up-admin false
cluster::*> network port modify -node n4 -port e4e -up-admin false
----
. 원격 클러스터 인터페이스에 대해 ping을 수행하고 RPC 서버 검사를 수행합니다.
+
'cluster ping-cluster-node_node-name_'

+
다음 예제에서는 ping이 진행되고 있는 노드 n1과 이후에 나타난 RPC 상태를 보여 줍니다.

+
[listing]
----
cluster::*> cluster ping-cluster -node n1
Host is n1 Getting addresses from network interface table...
Cluster n1_clus1 n1        e0a    10.10.0.1
Cluster n1_clus2 n1        e0b    10.10.0.2
Cluster n1_clus3 n1        e0c    10.10.0.3
Cluster n1_clus4 n1        e0d    10.10.0.4
Cluster n2_clus1 n2        e0a    10.10.0.5
Cluster n2_clus2 n2        e0b    10.10.0.6
Cluster n2_clus3 n2        e0c    10.10.0.7
Cluster n2_clus4 n2        e0d    10.10.0.8
Cluster n3_clus1 n4        e0a    10.10.0.9
Cluster n3_clus2 n3        e0e    10.10.0.10
Cluster n4_clus1 n4        e0a    10.10.0.11
Cluster n4_clus2 n4        e0e    10.10.0.12
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8 10.10.0.9 10.10.0.10 10.10.0.11
10.10.0.12 Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 32 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.1 to Remote 10.10.0.9
    Local 10.10.0.1 to Remote 10.10.0.10
    Local 10.10.0.1 to Remote 10.10.0.11
    Local 10.10.0.1 to Remote 10.10.0.12
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.9
    Local 10.10.0.2 to Remote 10.10.0.10
    Local 10.10.0.2 to Remote 10.10.0.11
    Local 10.10.0.2 to Remote 10.10.0.12
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.9
    Local 10.10.0.3 to Remote 10.10.0.10
    Local 10.10.0.3 to Remote 10.10.0.11
    Local 10.10.0.3 to Remote 10.10.0.12
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.9
    Local 10.10.0.4 to Remote 10.10.0.10
    Local 10.10.0.4 to Remote 10.10.0.11
    Local 10.10.0.4 to Remote 10.10.0.12
Larger than PMTU communication succeeds on 32 path(s) RPC status:
8 paths up, 0 paths down (tcp check)
8	paths up, 0 paths down (udp check)
----
. 클러스터 스위치 CL1에서 포트 1/31 및 1/32 를 종료합니다.
+
Cisco 명령에 대한 자세한 내용은 에 나와 있는 가이드를 참조하십시오 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^].

+
[listing]
----
(CL1)# configure
(CL1)(Config)# interface e1/31-32
(CL1(config-if-range)# shutdown
(CL1(config-if-range)# exit
(CL1)(Config)# exit (CL1)#
----
. 클러스터 스위치 CL2에 연결된 모든 케이블을 분리하고 모든 노드의 교체 스위치 C2에 다시 연결합니다.
. 클러스터 스위치 CL2의 포트 e1/31 및 e1/32에서 ISL(Inter-Switch Link) 케이블을 분리하고 교체 스위치 C2의 동일한 포트에 다시 연결합니다.
. 클러스터 스위치 CL1에서 ISL 포트 1/31 및 1/32 를 불러옵니다.
+
Cisco 명령에 대한 자세한 내용은 에 나와 있는 가이드를 참조하십시오 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^].

+
[listing]
----
(CL1)# configure
(CL1)(Config)# interface e1/31-32
(CL1(config-if-range)# no shutdown
(CL1(config-if-range)# exit
(CL1)(Config)# exit
(CL1)#
----
. CL1에서 ISL이 작동 중인지 확인합니다.
+
Cisco 명령에 대한 자세한 내용은 에 나와 있는 가이드를 참조하십시오 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^].

+
포트 Eth1/31과 Eth1/32는 '(P)'를 나타내야 합니다. 즉, ISL 포트가 포트 채널에서 작동 중임을 나타냅니다.

+
[listing]
----
CL1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
. 클러스터 스위치 C2에서 ISL이 작동 중인지 확인합니다.
+
Cisco 명령에 대한 자세한 내용은 에 나와 있는 가이드를 참조하십시오 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^].

+
[listing]
----
Ports Eth1/31 and Eth1/32 should indicate (P), which means that both ISL ports are up in the port-channel.
Example
C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
. 모든 노드에서 교체 스위치 C2에 연결된 모든 클러스터 상호 연결 포트를 불러옵니다. 'network port modify -node_node -name_-port_port -name_-up-admin true'
+
[listing]
----
cluster::*> network port modify -node n1 -port e0b -up-admin true
cluster::*> network port modify -node n1 -port e0c -up-admin true
cluster::*> network port modify -node n2 -port e0b -up-admin true
cluster::*> network port modify -node n2 -port e0c -up-admin true
cluster::*> network port modify -node n3 -port e4e -up-admin true
cluster::*> network port modify -node n4 -port e4e -up-admin true
----
. 마이그레이션된 모든 클러스터 인터커넥트 LIF를 모든 노드에 되돌리기:
+
'network interface revert-vserver cluster-lif_lif-name_'

+
다음 예에 표시된 대로 모든 클러스터 인터커넥트 LIF를 개별적으로 되돌려야 합니다.

+
[listing]
----
cluster::*> network interface revert -vserver cluster -lif n1_clus2
cluster::*> network interface revert -vserver cluster -lif n1_clus3
cluster::*> network interface revert -vserver cluster -lif n2_clus2
cluster::*> network interface revert -vserver cluster -lif n2_clus3
Cluster::*> network interface revert –vserver cluster –lif n3_clus2
Cluster::*> network interface revert –vserver cluster –lif n4_clus2
----
. 클러스터 인터커넥트 포트가 이제 홈 으로 되돌려졌는지 확인합니다.
+
네트워크 인터페이스 쇼

+
다음 예에서는 현재 포트 열에 나열된 포트가 홈(is Home) 열에 참(true) 상태가 있기 때문에 모든 LIF가 성공적으로 되돌려진 것을 보여 줍니다. 포트의 값이 false이면 LIF를 되돌릴 수 없습니다.

+
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
             n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
             n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
             n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
             n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
             n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
             n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
             n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
             n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
             n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
             n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
             n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
             n4_clus2   up/up      10.10.0.12/24      n4            e4e     true
12 entries were displayed.
----
. 클러스터 포트가 연결되어 있는지 확인합니다.
+
네트워크 포트 show-role cluster

+
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000 auto/10000  -
e0b       Cluster      Cluster          up   9000 auto/10000  -
e0c       Cluster      Cluster          up   9000 auto/10000  -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
 --------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/10000 -
e0b       Cluster      Cluster          up   9000  auto/10000 -
e0c       Cluster      Cluster          up   9000  auto/10000 -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -
        12 entries were displayed.
----
. 원격 클러스터 인터페이스에 대해 ping을 수행하고 RPC 서버 검사를 수행합니다.
+
'cluster ping-cluster-node_node-name_'

+
다음 예제에서는 ping이 진행되고 있는 노드 n1과 이후에 나타난 RPC 상태를 보여 줍니다.

+
[listing]
----
cluster::*> cluster ping-cluster -node n1
Host is n1 Getting addresses from network interface table...
Cluster n1_clus1 n1        e0a    10.10.0.1
Cluster n1_clus2 n1        e0b    10.10.0.2
Cluster n1_clus3 n1        e0c    10.10.0.3
Cluster n1_clus4 n1        e0d    10.10.0.4
Cluster n2_clus1 n2        e0a    10.10.0.5
Cluster n2_clus2 n2        e0b    10.10.0.6
Cluster n2_clus3 n2        e0c    10.10.0.7
Cluster n2_clus4 n2        e0d    10.10.0.8
Cluster n3_clus1 n3        e0a    10.10.0.9
Cluster n3_clus2 n3        e0e    10.10.0.10
Cluster n4_clus1 n4        e0a    10.10.0.11
Cluster n4_clus2 n4        e0e    10.10.0.12
Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8 10.10.0.9 10.10.0.10 10.10.0.11 10.10.0.12
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 32 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 1500 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.1 to Remote 10.10.0.9
    Local 10.10.0.1 to Remote 10.10.0.10
    Local 10.10.0.1 to Remote 10.10.0.11
    Local 10.10.0.1 to Remote 10.10.0.12
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.9
    Local 10.10.0.2 to Remote 10.10.0.10
    Local 10.10.0.2 to Remote 10.10.0.11
    Local 10.10.0.2 to Remote 10.10.0.12
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.9
    Local 10.10.0.3 to Remote 10.10.0.10
    Local 10.10.0.3 to Remote 10.10.0.11
    Local 10.10.0.3 to Remote 10.10.0.12
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.9
    Local 10.10.0.4 to Remote 10.10.0.10
    Local 10.10.0.4 to Remote 10.10.0.11
    Local 10.10.0.4 to Remote 10.10.0.12
Larger than PMTU communication succeeds on 32 path(s) RPC status:
8 paths up, 0 paths down (tcp check)
8	paths up, 0 paths down (udp check)
----
. 다음 명령을 입력하여 구성의 장치에 대한 정보를 표시합니다.
+
다음 명령은 순서에 상관없이 실행할 수 있습니다.

+
** 네트워크 디바이스 발견 쇼
** 네트워크 포트 show-role cluster
** 네트워크 인터페이스 show-role cluster
** 'system cluster-switch show'
+
[listing]
----
cluster::> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    C1                 Ethernet1/1/1    N3K-C3232C
            e0b    C2                 Ethernet1/1/1    N3K-C3232C
            e0c    C2                 Ethernet1/1/2    N3K-C3232C
            e0d    C1                 Ethernet1/1/2    N3K-C3232C
n2         /cdp
            e0a    C1                 Ethernet1/1/3    N3K-C3232C
            e0b    C2                 Ethernet1/1/3    N3K-C3232C
            e0c    C2                 Ethernet1/1/4    N3K-C3232C
            e0d    C1                 Ethernet1/1/4    N3K-C3232C
n3         /cdp
            e4a    C1                 Ethernet1/7      N3K-C3232C
            e4e    C2                 Ethernet1/7      N3K-C3232C

n4         /cdp
            e4a    C1                 Ethernet1/8      N3K-C3232C
            e4e    C2                 Ethernet1/8      N3K-C3232C

12 entries were displayed.
----
+
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
 --------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000 auto/10000  -
e0b       Cluster      Cluster          up   9000 auto/10000  -
e0c       Cluster      Cluster          up   9000 auto/10000  -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
 --------- ------------ ---------------- ---- ---- ----------- -------- -----
e0a       Cluster      Cluster          up   9000  auto/10000 -
e0b       Cluster      Cluster          up   9000  auto/10000 -
e0c       Cluster      Cluster          up   9000  auto/10000 -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -

Node: n3
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
Node: n4
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

12 entries were displayed.
----
+
[listing]
----
cluster::*> network interface show -role cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            nm1_clus1  up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
            n3_clus1   up/up      10.10.0.9/24       n3            e4a     true
            n3_clus2   up/up      10.10.0.10/24      n3            e4e     true
            n4_clus1   up/up      10.10.0.11/24      n4            e4a     true
            n4_clus2   up/up      10.10.0.12/24      n4            e4e     true
 12 entries were displayed.
----


+
[listing]
----
cluster::*> system cluster-switch show
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                          cluster-network   10.10.1.101      NX3232C
Serial Number: FOX000001
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP
CL2                          cluster-network   10.10.1.102      NX3232C
Serial Number: FOX000002
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP

C2                          cluster-network    10.10.1.103      NX3232C
Serial Number: FOX000003
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I6(1)     Version Source: CDP 3 entries were displayed.
----
. 교체된 클러스터 스위치 CL2가 자동으로 제거되지 않은 경우 삭제합니다.
+
'system cluster-switch delete-device cluster-switch-name'

. 적절한 클러스터 스위치가 모니터링되는지 확인합니다. 'system cluster-switch show'
+
다음 예에서는 "모니터링 상태"가 "참"이기 때문에 클러스터 스위치가 모니터링되는 경우를 보여 줍니다.

+
[listing]
----
cluster::> system cluster-switch show
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
CL1                         cluster-network    10.10.1.101      NX3232C
Serial Number: FOX000001
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP

C2                          cluster-network    10.10.1.103      NX3232C
Serial Number: FOX000002
Is Monitored: true
Reason:

Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP
2 entries were displayed.
----
. 스위치 관련 로그 파일을 수집하기 위해 클러스터 스위치 상태 모니터 로그 수집 기능을 활성화합니다.
+
'system cluster-switch log setup-password

+
'system cluster-switch log enable-collection'을 선택합니다

+
[listing]
----
cluster::*> system cluster-switch log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
CL1
C2

cluster::*> system cluster-switch log setup-password

Enter the switch name: CL1
**RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster::*> system cluster-switch log setup-password

Enter the switch name: C2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster::*> system cluster-switch log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster::*>
----
+
[NOTE]
====
이러한 명령에서 오류가 반환되면 NetApp 지원에 문의하십시오.

====
. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화합니다.
+
'System node AutoSupport invoke-node * -type all-message maINT=end'



* 관련 정보 *

http://support.netapp.com/NOW/download/software/cm_switches/["Cisco 이더넷 스위치 설명 페이지"^]

http://hwu.netapp.com["Hardware Universe"^]
