---
permalink: switch-cisco-3232c/task-how-to-migrate-from-a-two-node-switchless-cluster-to-a-cluster-with-cisco-nexus-3132q-v-cluster-switches.html 
sidebar: sidebar 
keywords: migrate, two-node cluster, switchless, cisco nexus 3232c 
summary: 스위치가 없는 2노드 클러스터가 있는 경우, Cisco Nexus 3232C 클러스터 네트워크 스위치를 포함하는 2노드 스위치 클러스터로 중단 없이 마이그레이션할 수 있습니다. 
---
= 스위치가 없는 2노드 클러스터에서 Cisco Nexus 3232C 클러스터 스위치를 사용하는 클러스터로 마이그레이션하는 방법
:icons: font
:imagesdir: ../media/


[role="lead"]
스위치가 없는 2노드 클러스터가 있는 경우, Cisco Nexus 3232C 클러스터 네트워크 스위치를 포함하는 2노드 스위치 클러스터로 중단 없이 마이그레이션할 수 있습니다.



== 필요한 것

* 구성이 올바르게 설정되고 작동해야 합니다.
+
스위치가 없는 2노드 클러스터 설정에서 2노드가 연결되어 작동 중이어야 합니다.

* 모든 클러스터 포트는 UP 상태여야 합니다.
* TH-Cisco Nexus 3232C 클러스터 스위치를 지원해야 합니다.
* 기존 클러스터 네트워크 구성에는 다음이 있어야 합니다.
+
** 두 스위치 모두에서 중복되고 완벽하게 작동하는 Nexus 3232C 클러스터 인프라
** 최신 RCF 및 NX-OS 버전을 스위치에서 사용할 수 있습니다
** 두 스위치 모두에서 관리 접속 구성
** 두 스위치에 대한 콘솔 액세스
** 마이그레이션 없이 "UP" 상태의 모든 클러스터 논리 인터페이스(LIF
** 스위치의 초기 사용자 정의
** 모든 ISL 포트 설정 및 케이블 연결






== 이 작업에 대해

* 절차 요약 *

* 저는 물리적 및 논리적 포트 표시 및 마이그레이션(1-10단계) *
* *II. 재할당된 LIF를 종료하고 케이블 연결을 끊습니다(11-14단계)
* * III. 클러스터 포트를 활성화합니다(15-20단계) *
* IV 재할당된 LIF를 설정합니다(21-33단계)


이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* Nexus 3232C 클러스터 스위치, C1 및 C2.
* 노드는 n1과 n2 이다.


[NOTE]
====
이 절차의 예에서는 각각 2개의 40GbE 클러스터 인터커넥트 포트 e4a 및 e4e를 사용하는 2개의 노드를 사용합니다. Hardware Universe_에는 플랫폼의 클러스터 포트에 대한 자세한 정보가 있습니다.

====
* N1_clus1 은 노드 n1의 클러스터 스위치 C1에 연결되는 첫 번째 클러스터 논리 인터페이스(LIF)입니다.
* N1_clus2 는 노드 n1의 클러스터 스위치 C2에 연결되는 첫 번째 클러스터 LIF입니다.
* N2_clus1 은 노드 n2의 클러스터 스위치 C1에 연결되는 첫 번째 클러스터 LIF입니다.
* N2_clus2 는 노드 n2의 클러스터 스위치 C2에 연결되는 두 번째 클러스터 LIF입니다.
* 10GbE 및 40/100 GbE 포트 수는 에서 사용할 수 있는 RCFs(참조 구성 파일)에 정의되어 있습니다 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] 페이지.


[NOTE]
====
이 절차를 수행하려면 ONTAP 명령과 Cisco Nexus 3000 시리즈 스위치 명령을 모두 사용해야 합니다. ONTAP 명령은 별도의 표시가 없는 한 사용됩니다.

====


== 단계

. 이 클러스터에서 AutoSupport가 활성화되어 있는 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
'System node AutoSupport invoke-node * -type all-message maINT=xh'

+
_x_는 유지보수 기간(시간)입니다.

+
[NOTE]
====
AutoSupport 메시지는 유지보수 기간 동안 자동 케이스 생성이 억제되도록 이 유지보수 작업의 기술 지원에 알립니다.

====
. 각 클러스터 인터페이스의 관리 또는 운영 상태 확인:
+
.. 네트워크 포트 속성을 표시합니다.
+
네트워크 포트 show-role cluster

+
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -
4 entries were displayed.
----
.. 논리 인터페이스 및 지정된 홈 노드에 대한 정보를 표시합니다.
+
네트워크 인터페이스 show-role cluster

+
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ---
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true

4 entries were displayed.
----
.. 고급 권한 명령을 사용하여 스위치가 없는 클러스터 검색이 설정되었는지 확인합니다.
+
네트워크 옵션 detect-switchless-cluster show

+
다음 예제의 출력은 스위치가 없는 클러스터 검색이 설정되었음을 보여 줍니다.

+
[listing]
----
cluster::*> network options detect-switchless-cluster show
Enable Switchless Cluster Detection: true
----


. 새 3232C 스위치에 적절한 RCFs 및 이미지가 설치되었는지 확인하고 사용자, 암호 및 네트워크 주소 추가와 같은 필요한 사이트 사용자 지정을 수행합니다.
+
이때 두 스위치를 모두 준비해야 합니다. RCF 및 이미지 소프트웨어를 업그레이드해야 하는 경우 다음 단계를 따라야 합니다.

+
.. NetApp Support 사이트의 _Cisco 이더넷 스위치_ 페이지로 이동하십시오.
+
http://support.netapp.com/NOW/download/software/cm_switches/["Cisco 이더넷 스위치"^]

.. 스위치 및 필요한 소프트웨어 버전을 해당 페이지의 표에 기록합니다.
.. 적절한 버전의 RCF를 다운로드합니다.
.. Description * 페이지에서 * continue * 를 클릭하고 사용권 계약에 동의한 다음 * Download * 페이지의 지침에 따라 RCF를 다운로드합니다.
.. 해당 버전의 이미지 소프트웨어를 다운로드합니다.
+
https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco 클러스터 및 관리 네트워크 스위치 참조 구성 파일 다운로드 페이지"^]



. Description * 페이지에서 * continue * 를 클릭하고 사용권 계약에 동의한 다음 * Download * 페이지의 지침에 따라 RCF를 다운로드합니다.
. Nexus 3232C 스위치 C1 및 C2에서 모든 노드 대상 포트 C1 및 C2를 사용하지 않도록 설정하되, ISL 포트 e1/31-32를 사용하지 않도록 설정하지 마십시오.
+
Cisco 명령에 대한 자세한 내용은 에 나와 있는 가이드를 참조하십시오 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^].

+
다음 예에서는 RCF 'NX3232_RCF_v1.0_24p10g_24p100g.txt'에서 지원되는 구성을 사용하여 Nexus 3232C 클러스터 스위치 C1 및 C2에서 포트 1부터 30까지 비활성화되는 것을 보여 줍니다.

+
[listing]
----
C1# copy running-config startup-config
[########################################] 100% Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit
C2# copy running-config startup-config
[########################################] 100% Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
. 지원되는 케이블 연결을 사용하여 C1의 포트 1/31 및 1/32를 C2의 동일한 포트에 연결합니다.
. ISL 포트가 C1 및 C2에서 작동하는지 확인합니다.
+
'포트-채널 요약

+
Cisco 명령에 대한 자세한 내용은 에 나와 있는 가이드를 참조하십시오 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^].

+
다음 예에서는 ISL 포트가 C1 및 C2에서 작동하는지 확인하는 데 사용되는 Cisco의 show port-channel summary" 명령을 보여 줍니다.

+
[listing]
----
C1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
      Port-
Group Channel      Type   Protocol  Member Ports
-------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)        s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------

Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
. 스위치에 있는 인접 장치 목록을 표시합니다.
+
Cisco 명령에 대한 자세한 내용은 에 나와 있는 가이드를 참조하십시오 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^].

+
다음 예에서는 스위치에 인접 장치를 표시하는 데 사용되는 Cisco 명령 'show CDP neighbors'를 보여 줍니다.

+
[listing]
----
C1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3232C  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,                   s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3232C  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3232C  Eth1/32
Total entries displayed: 2
----
. 각 노드의 클러스터 포트 연결을 표시합니다.
+
네트워크 디바이스 발견 쇼

+
다음 예는 스위치가 없는 2노드 클러스터 구성에 대해 표시된 클러스터 포트 접속을 보여줍니다.

+
[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
. n1_clus1 및 n2_clus1 LIF를 대상 노드의 물리적 포트로 마이그레이션합니다.
+
'network interface migrate-vserver cluster-lif_lif-name_source-node_source-node-name_-destination-port_destination-port-name_'

+
다음 예제와 같이 각 로컬 노드에 대해 명령을 실행해야 합니다.

+
[listing]
----
cluster::*> network interface migrate -vserver cluster -lif n1_clus1 -source-node n1
–destination-node n1 -destination-port e4e
cluster::*> network interface migrate -vserver cluster -lif n2_clus1 -source-node n2
–destination-node n2 -destination-port e4e
----
. 클러스터 인터페이스가 성공적으로 마이그레이션되었는지 확인합니다.
+
네트워크 인터페이스 show-role cluster

+
다음 예에서는 마이그레이션이 완료된 후 n1_clus1 및 n2_clus1 LIF의 "홈" 상태가 "거짓"으로 되었음을 보여 줍니다.

+
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
 4 entries were displayed.
----
. 9단계에서 마이그레이션한 n1_clus1 및 n2_clus1 LIF의 클러스터 포트 종료:
+
'network port modify -node_node -name_-port_port -name_-up-admin false'

+
다음 예에 표시된 대로 각 포트에 대해 명령을 실행해야 합니다.

+
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin false
cluster::*> network port modify -node n2 -port e4a -up-admin false
----
. 원격 클러스터 인터페이스에 대해 ping을 수행하고 RPC 서버 검사를 수행합니다.
+
'cluster ping-cluster-node_node-name_'

+
다음 예제에서는 ping이 진행되고 있는 노드 n1과 이후에 나타난 RPC 상태를 보여 줍니다.

+
[listing]
----
cluster::*> cluster ping-cluster -node n1

Host is n1 Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293 Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
. 노드 n1의 e4a에서 케이블을 분리합니다.
+
실행 중인 구성을 참조하여 Nexus 3232C 스위치에 지원되는 케이블 연결을 사용하여 스위치 C1(이 예에서는 포트 1/7)의 첫 번째 40GbE 포트를 n1의 e4a에 연결할 수 있습니다.

. 노드 n2의 e4a에서 케이블을 분리합니다.
+
지원되는 케이블 연결을 사용하여 실행 중인 구성을 참조하여 다음 사용 가능한 C1, 포트 1/8의 40GbE 포트에 e4a를 연결할 수 있습니다.

. C1에서 모든 노드 연결 포트를 활성화합니다.
+
Cisco 명령에 대한 자세한 내용은 에 나와 있는 가이드를 참조하십시오 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^].

+
다음 예에서는 RCF 'NX3232_RCF_v1.0_24p10g_26p100g.txt'에서 지원되는 구성을 사용하여 Nexus 3232C 클러스터 스위치 C1 및 C2에서 포트 1부터 30까지 사용 중인 것을 보여 줍니다.

+
[listing]
----
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# no shutdown
C1(config-if-range)# exit
C1(config)# exit
----
. 각 노드에서 첫 번째 클러스터 포트 e4a를 활성화합니다.
+
'network port modify -node_node -name_-port_port -name_-up-admin TRUE'

+
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin true
cluster::*> network port modify -node n2 -port e4a -up-admin true
----
. 클러스터가 두 노드에 모두 있는지 확인합니다.
+
네트워크 포트 show-role cluster

+
[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- -----
e4a       Cluster      Cluster          up   9000 auto/40000  -
e4e       Cluster      Cluster          up   9000 auto/40000  -

4 entries were displayed.
----
. 각 노드에서 마이그레이션된 모든 클러스터 인터커넥트 LIF를 되돌립니다.
+
'network interface revert-vserver cluster-lif_lif-name_'

+
다음 예제와 같이 각 LIF를 홈 포트로 개별적으로 되돌려야 합니다.

+
[listing]
----
cluster::*> network interface revert -vserver cluster -lif n1_clus1
cluster::*> network interface revert -vserver cluster -lif n2_clus1
----
. 모든 LIF가 이제 홈 포트로 되돌려졌는지 확인합니다.
+
네트워크 인터페이스 show-role cluster

+
현재 포트 열에 나열된 모든 포트에 대해 "홈"이라는 값이 표시되어야 합니다. 표시된 값이 false이면 포트가 복구되지 않은 것입니다.

+
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
. 각 노드의 클러스터 포트 연결을 표시합니다.
+
네트워크 디바이스 발견 쇼

+
[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    n1                  e4e              FAS9000
----
. 각 노드의 콘솔에서 포트 e4a로 clus2를 마이그레이션합니다.
+
'network interface migrate cluster-lif_lif-name_-source-node_source-node-name_-destination-node_destination-node-name_-destination-port_destination-port-name_'

+
다음 예에 표시된 대로 각 LIF를 홈 포트로 개별적으로 마이그레이션해야 합니다.

+
[listing]
----
cluster::*> network interface migrate -vserver cluster -lif n1_clus2 -source-node n1
–destination-node n1 -destination-port e4a
cluster::*> network interface migrate -vserver cluster -lif n2_clus2 -source-node n2 –destination-node n2 -destination-port e4a
----
. 두 노드 모두에서 클러스터 포트 clus2 LIF를 종료합니다.
+
네트워크 포트 수정

+
다음 예는 두 노드에서 포트를 종료하면서 "false"로 설정된 지정된 포트를 보여줍니다.

+
[listing]
----
cluster::*> network port modify -node n1 -port e4e -up-admin false
cluster::*> network port modify -node n2 -port e4e -up-admin false
----
. 클러스터 LIF 상태를 확인합니다.
+
네트워크 인터페이스 쇼

+
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
. 노드 n1의 e4e에서 케이블을 분리합니다.
+
실행 중인 구성을 참조하여 Nexus 3232C 스위치 모델에 적합한 케이블을 사용하여 스위치 C2(이 예의 경우 포트 1/7)의 첫 번째 40GbE 포트를 노드 n1의 e4e에 연결할 수 있습니다.

. 노드 n2의 e4e에서 케이블을 분리합니다.
+
실행 중인 구성을 참조하여 Nexus 3232C 스위치 모델에 적합한 케이블을 사용하여 C2, 포트 1/8에서 사용 가능한 다음 40 GbE 포트에 e4e를 연결할 수 있습니다.

. C2에서 모든 노드 대상 포트를 활성화합니다.
+
다음 예에서는 RCF 'NX3232C_RCF_v1.0_24p10g_26p100g.txt'에서 지원되는 구성을 사용하여 Nexus 3132Q-V 클러스터 스위치 C1 및 C2에서 포트 1부터 30까지 사용 중인 것을 보여 줍니다.

+
[listing]
----
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# no shutdown
C2(config-if-range)# exit
C2(config)# exit
----
. 각 노드에서 두 번째 클러스터 포트 e4e를 활성화합니다.
+
네트워크 포트 수정

+
다음 예에서는 각 노드에서 두 번째 클러스터 포트 e4e가 발생하는 것을 보여 줍니다.

+
[listing]
----
cluster::*> network port modify -node n1 -port e4e -up-admin true
cluster::*> network port modify -node n2 -port e4e -up-admin true
----
. 각 노드에 대해 마이그레이션된 모든 클러스터 인터커넥트 LIF를 '네트워크 인터페이스 복원'으로 되돌립니다
+
다음 예에서는 마이그레이션된 LIF가 홈 포트로 되돌아가는 것을 보여 줍니다.

+
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
. 모든 클러스터 인터커넥트 포트가 이제 홈 포트로 되돌려졌는지 확인합니다.
+
네트워크 인터페이스 show-role cluster

+
현재 포트 열에 나열된 모든 포트에 대해 "홈"이라는 값이 표시되어야 합니다. 표시된 값이 false이면 포트가 복구되지 않은 것입니다.

+
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
. 모든 클러스터 인터커넥트 포트가 'UP' 상태인지 확인합니다.
+
네트워크 포트 show-role cluster

. 각 클러스터 포트가 각 노드에 연결되는 클러스터 스위치 포트 번호 'network device-discovery show'를 표시합니다
+
[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1          /cdp
            e4a    C1                  Ethernet1/7      N3K-C3232C
            e4e    C2                  Ethernet1/7      N3K-C3232C
n2          /cdp
            e4a    C1                  Ethernet1/8      N3K-C3232C
            e4e    C2                  Ethernet1/8      N3K-C3232C
----
. 검색 및 모니터링되는 클러스터 스위치 표시:
+
'system cluster-switch show'

+
[listing]
----
cluster::*> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.101      NX3232CV
Serial Number: FOX000001
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP

C2                          cluster-network     10.10.1.102      NX3232CV
Serial Number: FOX000002
Is Monitored: true
Reason:
Software Version: Cisco Nexus Operating System (NX-OS) Software, Version 7.0(3)I6(1)
Version Source: CDP 2 entries were displayed.
----
. 스위치가 없는 클러스터 검색이 스위치가 없는 클러스터 옵션을 사용 안 함으로 변경했는지 확인합니다.
+
네트워크 옵션 스위치 없는 클러스터 쇼

. 원격 클러스터 인터페이스에 대해 ping을 수행하고 RPC 서버 검사를 수행합니다.
+
'cluster ping-cluster-node_node-name_'

+
[listing]
----
cluster::*> cluster ping-cluster -node n1
Host is n1 Getting addresses from network interface table...
Cluster n1_clus1 n1        e4a    10.10.0.1
Cluster n1_clus2 n1        e4e    10.10.0.2
Cluster n2_clus1 n2        e4a    10.10.0.3
Cluster n2_clus2 n2        e4e    10.10.0.4
Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s) ................
Detected 9000 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s) RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
. 스위치 관련 로그 파일 수집을 위한 클러스터 스위치 상태 모니터 로그 수집 기능 사용: + 'system cluster-switch log setup-password
+
'system cluster-switch log enable-collection'을 선택합니다

+
[listing]
----
cluster::*> system cluster-switch log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
C1
C2

cluster::*> system cluster-switch log setup-password

Enter the switch name: C1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster::*> system cluster-switch log setup-password

Enter the switch name: C2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster::*> system cluster-switch log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster::*>
----
+
[NOTE]
====
이러한 명령에서 오류가 반환되면 NetApp 지원에 문의하십시오.

====
. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화합니다.
+
'System node AutoSupport invoke-node * -type all-message maINT=end'


