---
permalink: switch-cisco-9336/9336-overview.html 
sidebar: sidebar 
keywords: cisco nexus 9336c-fx2 
summary: 2개 이상의 노드로 ONTAP 클러스터를 구축하려면 두 개의 지원되는 클러스터 네트워크 스위치가 필요합니다. 선택 사항인 관리 스위치를 추가로 사용할 수 있습니다. 
---
= Cisco 9336C-FX2 스위치 개요
:icons: font
:imagesdir: ../media/


[role="lead"]
2개 이상의 노드로 ONTAP 클러스터를 구축하려면 두 개의 지원되는 클러스터 네트워크 스위치가 필요합니다. 선택 사항인 관리 스위치를 추가로 사용할 수 있습니다.

Cisco Nexus 9336C-FX2 스위치(X190200/X190210)는 스위치에 포함된 표준 브래킷을 사용하여 NetApp 시스템 캐비닛 또는 타사 캐비닛에 설치할 수 있습니다.

다음 표에는 9336C-FX2 스위치, 팬 및 전원 공급 장치에 대한 부품 번호 및 설명이 나와 있습니다.

[cols="1,2"]
|===
| 부품 번호 | 설명 


 a| 
X190200-CS-PE
 a| 
N9K-9336C-FX2, CS, PTSX, 36PT10/25/40/100GQSFP28



 a| 
X190200-CS-PI
 a| 
N9K-9336C-FX2, CS, PSIN, 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PE
 a| 
N9K-9336C, FTE, PTSX, 36PT10/25/40/100GQSFP28



 a| 
X190210-FE-PI
 a| 
N9K-9336C, FTE, PSIN, 36PT10/25/40/100GQSFP28



 a| 
X190002
 a| 
액세서리 키트 X190001/X190003



 a| 
X-NXA-PAC-1100W-PE2
 a| 
N9K-9336C AC 1100W PSU - 포트 쪽 배기구 통기구



 a| 
X-NXA-PAC-1100W-PI2
 a| 
N9K-9336C AC 1100W PSU - 포트 쪽 흡입 공기 흐름



 a| 
X-NXA-FAN-65CFM-PE
 a| 
N9K-9336C 65CFM, 포트 쪽 배기구 통기구



 a| 
X-NXA-FAN-65CFM-PI
 a| 
N9K-9336C 65CFM, 포트 쪽 흡입 공기 흐름

|===


== 기타 지원되는 스위치

* Nexus 3232C
+
스위치와 함께 제공된 사용자 지정 브래킷을 사용하여 Cisco Nexus 3232C 스위치(X190100) NetApp 시스템 캐비닛을 설치하거나, 스위치에 포함되어 있는 표준 브래킷이 있는 랙에 설치할 수 있습니다.

* Nexus 3132Q-V
+
Cisco Nexus 3132Q-V 스위치(X190001)를 NetApp 시스템 캐비닛 또는 타사 캐비닛에 설치하고 스위치에 포함된 표준 브래킷을 사용할 수 있습니다.



다음 클러스터 스위치는 더 이상 NetApp에서 사용할 수 없지만 Cisco에서는 제한적으로 지원합니다.

* Nexus 5596UP/5596T
+
Cisco Nexus 5596UP 스위치(X1967-R6) 또는 5596T(X1989-R6)를 스위치와 함께 제공된 사용자 지정 브래킷이 있는 NetApp 시스템 캐비닛에 설치하거나 스위치에 포함되어 있는 표준 브래킷이 있는 랙에 설치할 수 있습니다.

+
Nexus 5596UP 스위치는 1개 또는 2개의 16포트 확장 모듈(X1988-R6)도 지원합니다.

+
Nexus 5596T 스위치는 FAS2520의 클러스터 인터커넥트 스위치로만 지원되며 무중단 하드웨어 업그레이드를 수행하는 데 사용하도록 설계되었습니다.

+
http://support.netapp.com/info/communications/ECMP12454150.html["공급 종료"^] 세부 정보.


