---
permalink: switch-cisco-9336/replace_9336c_storage_switch.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: '클러스터 네트워크에서 결함이 있는 Nexus 9336C-FX2 스위치를 교체하는 것은 무중단 절차(NDU\)입니다.' 
---
= Cisco Nexus 9336C-FX2 스토리지 스위치를 교체합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9336C-FX2 스토리지 스위치를 교체할 때 특정 구성 정보, 포트 연결 및 케이블 연결 요구 사항을 알고 있어야 합니다.

Cisco Nexus 9336C-FX2 스토리지 스위치에 NX-OS 소프트웨어 및 RCF를 설치하기 전에 다음 조건이 존재하는지 확인해야 합니다.

* 이 시스템은 Cisco Nexus 9336C-FX2 스토리지 스위치를 지원할 수 있습니다.
* 지원되는 ONTAP, NX-OS 및 RCF 버전은 Cisco 이더넷 스위치 페이지의 스위치 호환성 표를 참조하십시오.
+

NOTE: RCF 및 NX-OS 버전의 명령 구문 간에는 종속 관계가 있을 수 있습니다.

* Cisco 스위치 업그레이드 및 다운그레이드 절차에 대한 전체 문서를 보려면 Cisco 웹 사이트에서 제공하는 적절한 소프트웨어 및 업그레이드 가이드를 참조해야 합니다. Cisco Nexus 3000 시리즈 스위치
* 해당 RCFs를 다운로드해야 합니다.


기존 네트워크 구성에는 다음과 같은 특성이 있어야 합니다.

* Cisco 이더넷 스위치 페이지에는 스위치에 최신 RCF 및 NX-OS 버전이 있습니다.
* 두 스위치 모두에 관리 연결이 있어야 합니다.
+

NOTE: 모든 문제 해결 단계가 완료되었는지 확인하여 스위치를 교체해야 하는지 확인합니다.

+
교체 Cisco Nexus 9336C-FX2 스위치의 특징은 다음과 같습니다.

* 관리 네트워크 연결이 작동해야 합니다.
* 교체 스위치에 대한 콘솔 액세스가 있어야 합니다.
* 적절한 RCF 및 NX-OS 운영 체제 이미지를 스위치에 로드해야 합니다.
* 스위치의 초기 사용자 정의를 완료해야 합니다.




== 절차 요약

이 절차는 두 번째 Nexus 9336C-FX2 스토리지 스위치 S2를 새로운 9336C-FX2 스위치 NS2로 대체합니다. 두 노드는 노드 1과 노드 2입니다.

완료 단계:

* 교체할 스위치가 S2인지 확인합니다.
* 스위치 S2에서 케이블을 분리합니다.
* 케이블을 스위치 NS2에 다시 연결합니다.
* 스위치 NS2의 모든 장치 구성을 확인합니다.


.단계
. 이 클러스터에서 AutoSupport가 활성화되어 있으면 'system node AutoSupport invoke -node * -type all-message maINT=xh' AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다
+
_x_는 유지보수 기간(시간)입니다.

. 스토리지 노드 포트의 상태를 확인하여 스토리지 스위치 S1에 대한 접속이 있는지 확인합니다.
+
'Storage port show-port-type ENET'입니다

+
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
node2
               e3a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
               e7a  ENET  storage   0    enabled  offline     30
               e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
. 스토리지 스위치 S1을 사용할 수 있는지 확인합니다. 'network device-discovery show
+
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
node1/cdp
           e3a   S1                        Ethernet1/1 NX9336C
           e4a   node2                     e4a         AFF-A700
           e4e   node2                     e4e         AFF-A700
node1/lldp
           e3a   S1                        Ethernet1/1 -
           e4a   node2                     e4a         -
           e4e   node2                     e4e         -
node2/cdp
           e3a   S1                        Ethernet1/2 NX9336C
           e4a   node1                     e4a         AFF-A700
           e4e   node1                     e4e         AFF-A700
node2/lldp
           e3a   S1                        Ethernet1/2 -
           e4a   node1                     e4a         -
           e4e   node1                     e4e         -
storage::*>
----
. 'show ll dp neighbors' 명령을 작업 스위치에 실행하여 노드와 모든 shelf를 모두 볼 수 있는지 확인합니다
+
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
node1            Eth1/1       121          S             e3a
node2            Eth1/2       121          S             e3a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
. 스토리지 시스템의 Shelf port show-fields remote-device, remote-port를 확인한다
+
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   S1
3.20    1   -             -
3.20    2   Ethernet1/6   S1
3.20    3   -             -
3.30    0   Ethernet1/7   S1
3.20    1   -             -
3.30    2   Ethernet1/8   S1
3.20    3   -             -
storage::*>
----
. 스토리지 스위치 S2에 연결된 모든 케이블을 분리합니다.
. 교체 스위치 NS2에 모든 케이블을 다시 연결합니다.
. 스토리지 노드 포트의 상태를 다시 확인합니다. 스토리지 포트 show-port-type ENET입니다
+
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
node1
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
node2
                 e3a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
storage::*>
----
. 두 스위치를 모두 사용할 수 있는지 확인합니다. 'network device-discovery show'
+
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
node1/cdp
          e3a  S1                         Ethernet1/1 NX9336C
          e4a  node2                      e4a         AFF-A700
          e4e  node2                      e4e         AFF-A700
          e7b   NS2                       Ethernet1/1 NX9336C
node1/lldp
          e3a  S1                         Ethernet1/1 -
          e4a  node2                      e4a         -
          e4e  node2                      e4e         -
          e7b  NS2                        Ethernet1/1 -
node2/cdp
          e3a  S1                         Ethernet1/2 NX9336C
          e4a  node1                      e4a         AFF-A700
          e4e  node1                      e4e         AFF-A700
          e7b  NS2                        Ethernet1/2 NX9336C
node2/lldp
          e3a  S1                         Ethernet1/2 -
          e4a  node1                      e4a         -
          e4e  node1                      e4e         -
          e7b  NS2                        Ethernet1/2 -
storage::*>
----
. 스토리지 시스템의 Shelf port show-fields remote-device, remote-port를 확인한다
+
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     S1
3.20    1     Ethernet1/5     NS2
3.20    2     Ethernet1/6     S1
3.20    3     Ethernet1/6     NS2
3.30    0     Ethernet1/7     S1
3.20    1     Ethernet1/7     NS2
3.30    2     Ethernet1/8     S1
3.20    3     Ethernet1/8     NS2
storage::*>
----
. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지 '시스템 노드 AutoSupport invoke -node * -type all-message MAINT=end'를 호출하여 다시 활성화합니다

