---
sidebar: sidebar 
permalink: switch-cisco-9336c-shared/9336c_migrate_from_a_switchless_cluster_with_dat_storage_by_adding_two_new_shared_switches.html 
keywords:  
summary:  
---
= 2개의 새 공유 스위치를 추가하여 DAT 스토리지가 있는 스위치가 없는 클러스터에서 마이그레이션합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/




==== DAT 스토리지를 사용하여 스위치가 없는 클러스터에서 마이그레이션합니다

스위치가 없는 2노드 클러스터를 Cisco Nexus 9336C-FX2 클러스터 스위치가 있는 클러스터로 중단 없이 마이그레이션할 경우 특정 구성 정보, 포트 연결 및 케이블 연결 요구 사항을 알고 있어야 합니다. 사용하는 절차는 각 컨트롤러에 전용 클러스터 네트워크 포트가 2개 있는지, 각 컨트롤러에 단일 클러스터 포트가 있는지 여부에 따라 다릅니다. 문서화된 프로세스는 광 또는 Twinax 포트를 사용하는 모든 노드에 대해 작동하지만, 노드가 클러스터 네트워크 포트에 온보드 10Gb BASE-T RJ45 포트를 사용하는 경우 이 스위치에서 지원되지 않습니다.

대부분의 시스템에는 각 컨트롤러에 전용 클러스터 네트워크 포트 2개가 필요합니다. 을 참조하십시오  https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"] 를 참조하십시오.

스위치가 없는 기존 2노드 클러스터 환경이 구축된 경우 Cisco Nexus 9336C-FX2 스위치를 사용하여 2노드 스위치 클러스터 환경으로 마이그레이션하여 클러스터 내의 2개 노드 이상으로 확장할 수 있습니다.

.시작하기 전에
* 스위치가 없는 2노드 구성:
+
** 스위치가 없는 2노드 구성이 올바르게 설정 및 작동해야 합니다.
** 노드는 ONTAP 9.8 이상을 실행해야 합니다.
** 모든 클러스터 포트는 * UP * 상태여야 합니다.
** 모든 클러스터 논리 인터페이스(LIF)는 * UP * 상태 및 해당 * 홈 * 포트에 있어야 합니다.


* Cisco Nexus 9336C-FX2 스위치 구성:
+
** 두 스위치 모두 관리 네트워크 연결이 있어야 합니다.
** 클러스터 스위치에 대한 콘솔 액세스가 있어야 합니다.
** Nexus 9336C-FX2 노드 간 스위치 및 스위치 간 연결은 Twinax 또는 파이버 케이블을 사용해야 합니다.
** 넷엡 https://hwu.netapp.com["Hardware Universe"] 케이블 연결에 대한 자세한 내용은 에 나와 있습니다.
** ISL(Inter-Switch Link) 케이블은 두 9336C-FX2 스위치에서 포트 1/35 및 1/36 에 연결해야 합니다.


* 9336C-FX2 스위치의 초기 사용자 정의를 완료해야 합니다. 따라서 다음을 수행합니다.
+
** 9336C-FX2 스위치는 최신 버전의 소프트웨어를 실행하고 있습니다
** RCF(Reference Configuration Files)가 스위치에 적용되었습니다
** SMTP, SNMP, SSH 등의 사이트 사용자 지정은 새 스위치에서 구성해야 합니다.




.이 작업에 대해
이 절차의 예에서는 다음과 같은 클러스터 스위치 및 노드 명명법을 사용합니다.

* 9336C-FX2 스위치의 이름은 _CS1_과 _CS2_입니다.
* 클러스터 SVM의 이름은_node1_and_node2_입니다.
* LIF의 이름은 노드 1의 _node1_clus1_과 _node1_clus2_이고, 노드 2의 _node2_clus1_과 _node2_clus2_입니다.
* cluster1:: * > 프롬프트는 클러스터의 이름을 나타냅니다.
* 이 절차에 사용되는 클러스터 포트는 AFF A400 컨트롤러에 따라 _e3a_와 _e3b_입니다. 를 클릭합니다 https://hwu.netapp.com["Hardware Universe"] 에는 해당 플랫폼의 실제 클러스터 포트에 대한 최신 정보가 나와 있습니다.


.단계
. 이 클러스터에서 AutoSupport가 활성화되어 있으면 'system node AutoSupport invoke -node * -type all-message maINT=xh' AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
여기서 x는 유지 보수 기간(시간)입니다.




NOTE: AutoSupport 메시지는 유지보수 기간 동안 자동 케이스 생성이 억제되도록 이 유지보수 작업의 기술 지원에 알립니다.

. [[step2]]권한 수준을 고급으로 변경하고, ' Set-Privilege advanced ' 메시지가 표시되면 y를 입력합니다
+
고급 프롬프트(*>)가 나타납니다.

. 새 클러스터 스위치 CS1과 CS2 모두에서 ISL 포트가 아닌 모든 노드 대상 포트를 비활성화합니다. ISL 포트를 비활성화해서는 안 됩니다.
+
다음 예에서는 스위치 CS1에서 노드 방향 포트 1부터 34까지 비활성 상태를 보여 줍니다.



[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e/1-34
cs1(config-if-range)# shutdown
----
. [[4단계] 두 9336C-FX2 스위치 CS1과 CS2 사이의 ISL과 ISL의 물리적 포트가 포트 1/35 및 1/36:'포트-채널 요약 정보'에 있는지 확인합니다
+
다음 예에서는 스위치 CS1에서 ISL 포트가 작동 중인 것을 보여 줍니다.



[listing]
----
cs1# show port-channel summary
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
다음 예에서는 스위치 CS2에서 ISL 포트가 작동 중인 것을 보여 줍니다.

[listing]
----
       cs2# show port-channel summary
        Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
. [[5단계] 주변 디바이스 목록 표시: CDP 네이버 표시
+
이 명령은 시스템에 연결된 장치에 대한 정보를 제공합니다. 다음 예에서는 스위치 CS1의 인접 장치를 나열합니다.



[listing]
----
cs1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 2
----
다음 예에서는 스위치 CS2의 인접 장치를 나열합니다.

[listing]
----
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
. [[step6]] 모든 클러스터 포트가 작동 중인지 확인합니다. 'network port show - IPSpace Cluster'
+
각 포트는 Link 및 Health Status에 대해 Healthy로 표시되어야 합니다.



[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: node2
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.
----
. [[step7] 모든 클러스터 LIF가 작동 중인지 확인합니다. 'network interface show -vserver Cluster'
+
각 클러스터 LIF는 '홈'에 대해 '참'으로 표시되고 상태 관리/권한 상승/위에서는 '참'으로 표시되어야 합니다.



[listing]
----
cluster1::*> network interface show -vserver Cluster
            Logical     Status     Network            Current       Current Is
Vserver     Interface   Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.
----
. [[step8]] 모든 클러스터 LIF에서 자동 복원이 활성화되어 있는지 확인합니다. 'network interface show -vserver Cluster-fields auto-revert'


[listing]
----
cluster1::*> network interface show -vserver Cluster -fields auto-revert
       Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
4 entries were displayed.
----
. [[step9]] 노드 1의 클러스터 포트 e3a에서 케이블을 분리한 다음 9336C-FX2 스위치가 지원하는 적절한 케이블을 사용하여 클러스터 스위치 CS1의 포트 1에 e3a를 연결합니다.
+
넷엡 https://hwu.netapp.com["Hardware Universe"] 케이블 연결에 대한 자세한 내용은 에 나와 있습니다.

. 노드 2의 클러스터 포트 e3a에서 케이블을 분리한 다음 9336C-FX2 스위치가 지원하는 적절한 케이블을 사용하여 클러스터 스위치 CS1의 포트 2에 e3a를 연결합니다.
. 클러스터 스위치 CS1에서 모든 노드 대상 포트를 활성화합니다.
+
다음 예에서는 스위치 CS1에서 포트 1/1에서 1/34 사이의 포트가 활성화되어 있음을 보여 줍니다.



[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e1/1-34
cs1(config-if-range)# no shutdown
----
. [[step12]]모든 클러스터 LIF가 * 업 *, 운영 및 '홈'에 대해 TRUE로 표시되는지 확인합니다. 네트워크 인터페이스 show-vserver Cluster
+
다음 예에서는 node1과 node2에 모든 LIF가 * up * 이고 "is Home" 결과가 * TRUE * 임을 보여 줍니다.



[listing]
----
cluster1::*> network interface show -vserver Cluster
          Logical      Status     Network            Current     Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node        Port    Home
--------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2       e3b     true
4 entries were displayed.
----
. [[step13]] 클러스터의 노드 상태에 대한 정보를 표시합니다: "cluster show"
+
다음 예제에는 클러스터에 있는 노드의 상태 및 자격에 대한 정보가 표시됩니다.



[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
. [[단계 14]] 노드 1의 클러스터 포트 e3b에서 케이블을 분리한 다음 9336C-FX2 스위치가 지원하는 적절한 케이블을 사용하여 클러스터 스위치 CS2의 포트 1에 e3b를 연결합니다.
. 노드 2의 클러스터 포트 e3b에서 케이블을 분리한 다음 9336C-FX2 스위치가 지원하는 적절한 케이블을 사용하여 e3b를 클러스터 스위치 CS2의 포트 2에 연결합니다.
. 클러스터 스위치 CS2에서 모든 노드 대상 포트를 활성화합니다.
+
다음 예에서는 스위치 CS2에서 포트 1/1 ~ 1/34 가 활성화되어 있음을 보여 줍니다.



[listing]
----
cs2# config
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# interface e1/1-34
cs2(config-if-range)# no shutdown
----
. [[step17]] 모든 클러스터 포트가 작동 중인지 확인합니다. 'network port show - IPSpace Cluster'
+
다음 예제에서는 모든 클러스터 포트가 노드 1과 노드 2에 있는 것을 보여 줍니다.



[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
----
. [[step18]]모든 인터페이스가 '홈'에 대해 '참'으로 표시되는지 확인합니다. 네트워크 인터페이스 show -vserver Cluster'입니다



NOTE: 이 작업을 완료하는 데 몇 분 정도 걸릴 수 있습니다.

다음 예에서는 node1과 node2에 모든 LIF가 * up * 이고 "is Home" 결과가 true인 것을 보여 줍니다.

[listing]
----
cluster1::*> network interface show -vserver Cluster
          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true
4 entries were displayed.
----
. [[step19]] 양 노드 모두 각 스위치에 대해 CDP 인접 항목(havi cdp neighbors) 연결을 하나씩 가지고 있는지 확인합니다
+
다음 예에서는 두 스위치에 대해 적절한 결과를 보여 줍니다.



[listing]
----
cs1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3a
node2              Eth1/2         133    H           AFFA400       e3a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3b
node2              Eth1/2         133    H           AFFA400       e3b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
. [[step20] 클러스터에서 검색된 네트워크 장치에 대한 정보를 표시합니다: "network device-discovery show-protocol CDP"


[listing]
----
cluster1::*> network device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2       /cdp
            e3a    cs1                       0/2               N9K-C9336C
            e3b    cs2                       0/2               N9K-C9336C

node1       /cdp
            e3a    cs1                       0/1               N9K-C9336C
            e3b    cs2                       0/1               N9K-C9336C
4 entries were displayed.
----
. [[step21]]HA Pair 1(및 HA Pair 2)의 스토리지 구성이 올바르고 오류가 없는지 확인합니다. 'system switch ethernet show'


[listing]
----
storage::*> system switch ethernet show
Switch                    Type                   Address         Model
------------------------- ---------------------- --------------- ----------
sh1
                          storage-network        172.17.227.5    C9336C

       Serial Number: FOC221206C2
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[step22]]설정이 비활성화되었는지 확인합니다. 'network options switchless-cluster show'



NOTE: 명령이 완료되는 데 몇 분 정도 걸릴 수 있습니다. '3분 수명 만료' 메시지가 표시될 때까지 기다립니다.

다음 예제의 "false" 출력은 구성 설정이 비활성화되어 있음을 보여 줍니다.

[listing]
----
cluster1::*> network options switchless-cluster show
Enable Switchless Cluster: false
----
. [[step23]]클러스터의 노드 멤버 상태를 확인하십시오: 'cluster show'
+
다음 예는 클러스터에 있는 노드의 상태 및 적격성에 대한 정보를 보여줍니다.



[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
. [[step24]] 클러스터 네트워크에 'cluster ping-cluster-node-name'(클러스터 ping-cluster-node-node-name)이 완전히 연결되어 있는지 확인합니다


[listing]
----
cluster1::*> cluster ping-cluster -node node2
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
...
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
...
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. [[25단계] 권한 수준을 admin:'et-Privilege admin'으로 다시 변경합니다
. 다음 명령을 사용하여 스위치 관련 로그 파일을 수집하기 위해 이더넷 스위치 상태 모니터 로그 수집 기능을 활성화합니다.
+
** 'System switch Ethernet log setup - password'(시스템 스위치 이더넷 로그 설정 - 암호)
** System switch Ethernet log enable-collection




[listing]
----
cluster1::*> system switch ethernet log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.

Choose from the following list:
cs1
cs2
cluster1::*> system switch ethernet log setup-password
Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system switch ethernet log setup-password
Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system  switch ethernet log enable-collection
Do you want to enable cluster log collection for all nodes in the cluster? {y|n}: [n] y
Enabling cluster switch log collection.
cluster1::*>
----


==== 공유 스위치를 설정합니다

이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 두 공유 스위치의 이름은 _SH1_와 _SH2_입니다.
* 노드는 _node1_ 및 _node2_입니다.



NOTE: 이 절차를 수행하려면 ONTAP 명령과 Cisco Nexus 9000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 표시되지 않는 한 ONTAP 명령이 사용됩니다.

.단계
. HA 쌍 1(및 HA 쌍 2)의 스토리지 구성이 올바르고 오류가 없는지 확인합니다. '시스템 스위치 이더넷 표시'입니다


[listing]
----
storage::*> system switch ethernet show
Switch                    Type                   Address         Model
------------------------- ---------------------  --------------- -------
sh1
                          storage-network        172.17.227.5    C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[step2]] 스토리지 노드 포트가 정상 작동 중인지 확인합니다. 스토리지 포트 show-port-type ENET


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage          100      enabled  online        30
        e5a     ENET   storage          100      enabled  online        30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage           100      enabled  online        30
        e5a     ENET  storage           100      enabled  online        30
        e5b     ENET  storage           100      enabled  online        30
----
. [[step3] HA 쌍 1, NSM224 경로 A 포트를 SH1 포트 범위 11-22로 이동합니다.
. HA 쌍 1, 노드 1, 경로 A에서 SH1 포트 범위 11-22까지 케이블을 설치합니다. 예를 들어, AFF A400의 스토리지 포트 경로는 e0c입니다.
. HA 쌍 1, 노드 2, 경로 A에서 SH1 포트 범위 11-22까지 케이블을 설치합니다.
. 노드 포트가 정상 작동 중인지 'Storage port show-port-type ENET'인지 확인합니다


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
. [[step7] 클러스터에 스토리지 스위치 또는 케이블 연결 문제가 없는지 확인합니다. 'system health alert show-instance'


[listing]
----
storage::*> system health alert show -instance
There are no entries matching your query.
----
. [[step8]] HA 쌍 1, NSM224 경로 B 포트를 SH2 포트 범위 11-22로 이동합니다.
. HA 쌍 1, 노드 1, 경로 B에서 SH2 포트 범위 11-22까지 케이블을 설치합니다. 예를 들어, AFF A400의 경로 B 스토리지 포트는 e5b입니다.
. HA 쌍 1, 노드 2, 경로 B에서 SH2 포트 범위 11-22까지 케이블을 설치합니다.
. 노드 포트가 정상 작동 중인지 'Storage port show-port-type ENET'인지 확인합니다


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
. [[12단계] HA Pair 1의 스토리지 구성이 올바르고 오류가 없는지 확인합니다. 'system switch ethernet show'


[listing]
----
storage::*> system switch ethernet show
Switch                    Type                   Address          Model
------------------------- ---------------------- ---------------- ----------
sh1
                          storage-network        172.17.227.5     C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6     C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[13단계] HA 쌍 1의 사용되지 않은(컨트롤러) 2차 스토리지 포트를 스토리지에서 네트워킹으로 재구성합니다. 둘 이상의 NS224가 직접 연결된 경우 포트를 재구성해야 합니다.


[listing]
----
storage port modify –node [node name] –port [port name] –mode network
----
스토리지 포트를 브로드캐스트 도메인에 배치하려면

* 'Network port broadcast-domain create'(필요한 경우 새 도메인 생성)
* 'Network port broadcast-domain add-ports'(기존 도메인에 포트 추가)


. [[step14]] 자동 케이스 생성을 억제한 경우 AutoSupport 메시지 '시스템 노드 AutoSupport invoke -node * -type all-message MAINT=end'를 호출하여 다시 활성화합니다

