---
permalink: switch-nvidia-sn2100/configure-reqs-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: NVIDIA SN2100 스위치 설치 및 유지관리를 위해서는 모든 요구 사항과 권장 문서를 검토하세요. 
---
= NVIDIA SN2100 스위치에 대한 구성 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVIDIA SN2100 스위치 설치 및 유지관리를 위해서는 모든 구성 요구 사항을 검토하세요.



== 설치 요구 사항

두 개 이상의 노드가 있는 ONTAP 클러스터를 구축하려면 지원되는 클러스터 네트워크 스위치가 두 개 필요합니다.  선택 사항인 추가 관리 스위치를 사용할 수 있습니다.

스위치와 함께 제공되는 표준 브래킷을 사용하여 NVIDIA 듀얼/싱글 스위치 캐비닛에 NVIDIA SN2100 스위치(X190006)를 설치합니다.

케이블링 지침은 다음을 참조하세요.link:cabling-considerations-sn2100-cluster.html["케이블링 및 구성 고려 사항 검토"] .



== ONTAP 및 Linux 지원

NVIDIA SN2100 스위치는 Cumulus Linux를 실행하는 10/25/40/100GbE 스위치입니다.  스위치는 다음을 지원합니다.

* ONTAP 9.10.1P3 이상
+
SN2100 스위치는 ONTAP 9.10.1P3 이상에서 다양한 스위치 쌍을 통해 클러스터 및 스토리지 애플리케이션을 제공합니다.

* Cumulus Linux(CL) OS 버전
+
** 특정 CL 버전은 NetApp 에서 인증 및 지원을 받습니다.  현재 호환성 정보는 다음을 참조하세요.link:https://mysupport.netapp.com/site/info/nvidia-cluster-switch["NVIDIA 이더넷 스위치 정보"^] 페이지 또는link:https://hwu.netapp.com["NetApp Hardware Universe"^] .
** NVIDIA 에서 SN2100 Cumulus 소프트웨어를 다운로드하려면 NVIDIA의 Enterprise Support Portal에 액세스할 수 있는 로그인 자격 증명이 있어야 합니다.  지식 기반 문서를 참조하세요 https://kb.netapp.com/onprem/Switches/Nvidia/How_To_Register_With_NVIDIA_For_Enterprise_Support_Portal_Access["NVIDIA Enterprise Support Portal Access에 등록하는 방법"^] .




* 스위치에서 Cumulus Linux 또는 ONIE를 실행하는 경우 Cumulus Linux를 설치할 수 있습니다.


.다음은 무엇인가요?
구성 요구 사항을 검토한 후 다음을 확인할 수 있습니다. link:components-sn2100-cluster.html["구성 요소 및 부품 번호"].
