---
permalink: switch-nvidia-sn2100/configure-reqs-sn2100-cluster.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: NVIDIA SN2100 스위치 설치 및 유지 보수의 경우 모든 요구 사항 및 권장 설명서를 검토하십시오. 
---
= NVIDIA SN2100 스위치의 구성 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVIDIA SN2100 스위치 설치 및 유지 보수의 경우 모든 구성 요구 사항을 검토하십시오.



== 설치 요구 사항

2개 이상의 노드로 ONTAP 클러스터를 구축하려면 두 개의 지원되는 클러스터 네트워크 스위치가 필요합니다. 선택 사항인 관리 스위치를 추가로 사용할 수 있습니다.

NVIDIA SN2100 스위치(X190006)는 스위치에 포함된 표준 브래킷과 함께 NVIDIA 이중/단일 스위치 캐비닛에 설치합니다.

케이블 연결 지침은 을 참조하십시오 link:cabling-considerations-sn2100-cluster.html["케이블 연결 및 구성 고려 사항을 검토합니다"].



== ONTAP 및 Linux 지원

NVIDIA SN2100 스위치는 Cumulus Linux를 실행하는 10/25/40/100GbE 스위치입니다. 스위치는 다음을 지원합니다.

* ONTAP 9.10.1P3 이상
+
SN2100 스위치는 ONTAP 9.10.1P3 이상의 다양한 스위치 쌍을 통해 클러스터 및 스토리지 애플리케이션을 지원합니다.

* Cumulus Linux(CL) OS 버전
+
** 특정 CL 버전은 NetApp에 의해 검증되고 지원됩니다. 최신 호환성 정보는 link:https://mysupport.netapp.com/site/info/nvidia-cluster-switch["NVIDIA 이더넷 스위치 정보"^]페이지 또는 를 link:https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]참조하십시오.
** NVIDIA에서 SN2100 Cumulus 소프트웨어를 다운로드하려면 NVIDIA의 엔터프라이즈 지원 포털에 액세스하려면 로그인 자격 증명이 있어야 합니다. 기술 자료 문서를 https://kb.netapp.com/onprem/Switches/Nvidia/How_To_Register_With_NVIDIA_For_Enterprise_Support_Portal_Access["엔터프라이즈 지원 포털 액세스를 위해 NVIDIA에 등록하는 방법"^]참조하십시오.




* Cumulus Linux 또는 ONIE를 실행 중인 스위치에서 Cumulus Linux를 설치할 수 있습니다.


.다음 단계
구성 요구 사항을 검토한 후 다음을 확인할 수 있습니다. link:components-sn2100-cluster.html["구성 요소 및 부품 번호"].
