---
permalink: switch-nvidia-sn2100/configure-overview-sn2100-cluster.html 
sidebar: sidebar 
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux 
summary: NVIDIA SN2100 스위치는 Cumulus Linux를 실행하는 10/25/40/100 GbE 이더넷 스위치입니다. SN2100 스위치는 ONTAP 9.10.1에서 서로 다른 스위치 쌍에 대한 클러스터 및 스토리지 애플리케이션을 지원합니다. 
---
= NVIDIA SN2100 스위치의 설치 및 구성 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVIDIA SN2100은 2개 이상의 노드로 ONTAP 클러스터를 구축할 수 있는 클러스터 스위치입니다.



== 초기 구성 개요

ONTAP를 실행하는 시스템에서 NVIDIA SN2100 스위치를 구성하려면 다음 단계를 수행하십시오.

. link:install-hardware-sn2100-cluster.html["NVIDIA SN2100 스위치용 하드웨어를 설치합니다"].
+
지침은 _NVIDIA 스위치 설치 안내서_에서 확인할 수 있습니다.

. link:configure-sn2100-cluster.html["스위치를 구성합니다"].
+
지침은 NVIDIA 설명서에 나와 있습니다.

. link:cabling-considerations-sn2100-cluster.html["케이블 연결 및 구성 고려 사항을 검토합니다"].
+
광 연결, QSA 어댑터 및 스위치 포트 속도에 대한 요구 사항을 검토합니다.

. link:install-cable-shelves-sn2100-cluster.html["NS224 쉘프를 스위치 연결 스토리지로 케이블로 연결합니다"].
+
NS224 드라이브 쉘프를 스위치 연결 스토리지(직접 연결 스토리지 아님)로 케이블로 연결해야 하는 시스템이 있는 경우 케이블 연결 절차를 따르십시오.

. link:install-cumulus-mode-sn2100-cluster.html["Cumulus 모드에서 Cumulus Linux를 설치합니다"] 또는 link:install-onie-mode-sn2100-cluster.html["ONIE 모드에서 Cumulus Linux를 설치합니다"].
+
스위치가 Cumulus Linux 또는 ONIE를 실행 중일 경우 Cumulus Linux(CL) OS를 설치할 수 있습니다.

. link:install-rcf-sn2100-cluster.html["RCF(Reference Configuration File) 스크립트를 설치합니다"].
+
클러스터링과 스토리지 애플리케이션에 사용 가능한 RCF 스크립트는 두 가지가 있습니다. 각각의 절차는 동일합니다.

. link:install-snmpv3-sn2100-cluster.html["스위치 로그 수집을 위해 SNMPv3을 구성합니다"].
+
이 릴리스에는 스위치 로그 수집용 SNMPv3 및 스위치 상태 모니터링(SHM)에 대한 지원이 포함되어 있습니다.



이 절차에서는 Cumulus Linux에 완벽하게 액세스할 수 있도록 하는 명령줄 인터페이스인 NCLU(Network Command Line Utility)를 사용합니다. NET 명령은 터미널에서 작업을 실행하는 데 사용하는 래퍼 유틸리티입니다.



== 추가 정보

설치 또는 유지 관리를 시작하기 전에 다음을 검토하십시오.

* link:configure-reqs-sn2100-cluster.html["구성 요구 사항"]
* link:components-sn2100-cluster.html["부품 및 부품 번호"]
* link:required-documentation-sn2100-cluster.html["필수 문서"]
* https://hwu.netapp.com["Hardware Universe"^] 지원되는 모든 ONTAP 버전.

