---
permalink: switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html 
sidebar: sidebar 
keywords: two-node switchless cluster environments,migrating to a two-node switched NVIDIA SN2100 cluster environment,switchless cluster environments,NVIDIA SN2100 switches 
summary: 기존의 2노드 스위치리스 클러스터 환경이 있는 경우 NVIDIA SN2100 스위치를 사용하여 2노드 스위치 클러스터 환경으로 마이그레이션하면 클러스터에서 노드를 두 개 이상으로 확장할 수 있습니다. 
---
= NVIDIA SN2100 클러스터 스위치를 사용하여 2노드 스위치 클러스터로 마이그레이션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존의 2노드 스위치리스 클러스터 환경이 있는 경우 NVIDIA SN2100 스위치를 사용하여 2노드 스위치 클러스터 환경으로 마이그레이션하면 클러스터에서 노드를 두 개 이상으로 확장할 수 있습니다.

사용하는 절차는 각 컨트롤러에 전용 클러스터 네트워크 포트가 두 개 있는지, 아니면 각 컨트롤러에 단일 클러스터 포트가 있는지에 따라 달라집니다.  문서화된 프로세스는 광 포트나 Twinax 포트를 사용하는 모든 노드에서 작동하지만 노드가 클러스터 네트워크 포트에 온보드 10GBASE-T RJ45 포트를 사용하는 경우 이 스위치에서는 지원되지 않습니다.



== 검토 요구 사항

.2노드 스위치리스 구성
다음 사항을 확인하세요.

* 2노드 스위치리스 구성이 올바르게 설정되고 작동하고 있습니다.
* 노드는 ONTAP 9.10.1P3 이상을 실행합니다.
* 모든 클러스터 포트가 *작동* 상태입니다.
* 모든 클러스터 논리 인터페이스(LIF)는 *작동* 상태이며 홈 포트에 있습니다.


.NVIDIA SN2100 클러스터 스위치 구성
다음 사항을 확인하세요.

* 두 스위치 모두 관리 네트워크 연결 기능을 갖추고 있습니다.
* 클러스터 스위치에 콘솔로 접근할 수 있습니다.
* NVIDIA SN2100 노드 간 스위치와 스위치 간 연결은 Twinax 또는 파이버 케이블을 사용합니다.
+

IMPORTANT: 보다link:cabling-considerations-sn2100-cluster.html["케이블링 및 구성 고려 사항 검토"] 주의사항 및 자세한 내용은 다음을 참조하세요.  그만큼 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - 스위치"^] 케이블링에 대한 자세한 정보도 포함되어 있습니다.

* ISL(Inter-Switch Link) 케이블은 두 NVIDIA SN2100 스위치의 포트 swp15와 swp16에 연결됩니다.
* 두 SN2100 스위치의 초기 사용자 정의가 완료되어 다음과 같은 결과가 나왔습니다.
+
** SN2100 스위치는 최신 버전의 Cumulus Linux를 실행하고 있습니다.
** 참조 구성 파일(RCF)은 스위치에 적용됩니다.
** SMTP, SNMP, SSH 등의 모든 사이트 사용자 정의는 새 스위치에서 구성됩니다.
+
그만큼 https://hwu.netapp.com["Hardware Universe"^] 플랫폼의 실제 클러스터 포트에 대한 최신 정보가 포함되어 있습니다.







== 스위치 마이그레이션

.예시에 관하여
이 절차의 예에서는 다음 클러스터 스위치와 노드 명명법을 사용합니다.

* SN2100 스위치의 이름은 _sw1_과 _sw2_입니다.
* 클러스터 SVM의 이름은 _node1_과 _node2_입니다.
* LIF의 이름은 노드 1에서는 각각 _node1_clus1_과 _node1_clus2_이고, 노드 2에서는 각각 _node2_clus1_과 _node2_clus2_입니다.
* 그만큼 `cluster1::*>` 프롬프트는 클러스터의 이름을 나타냅니다.
* 이 절차에서 사용되는 클러스터 포트는 _e3a_와 _e3b_입니다.
* 브레이크아웃 포트는 swp[포트]s[브레이크아웃 포트 0-3] 형식을 따릅니다.  예를 들어, swp1의 4개 브레이크아웃 포트는 _swp1s0_, _swp1s1_, _swp1s2_, _swp1s3_입니다.




=== 1단계: 마이그레이션 준비

. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다. `system node autosupport invoke -node * -type all -message MAINT=xh`
+
여기서 _x_는 유지 관리 기간(시간)입니다.

. 권한 수준을 고급으로 변경하려면 다음을 입력하세요. `y` 계속하라는 메시지가 표시되면: `set -privilege advanced`
+
고급 프롬프트(`*>` )이 나타납니다.





=== 2단계: 포트 및 케이블 구성

[role="tabbed-block"]
====
.큐물러스 리눅스 4.4.x
--
. 새로운 클러스터 스위치 sw1과 sw2에서 노드에 연결된 모든 포트(ISL 포트 제외)를 비활성화합니다.
+
ISL 포트를 비활성화하면 안 됩니다.

+
다음 명령은 스위치 sw1 및 sw2에서 노드 연결 포트를 비활성화합니다.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*

cumulus@sw2:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
. 두 SN2100 스위치 sw1과 sw2 사이의 ISL과 ISL의 물리적 포트가 포트 swp15와 swp16에서 작동하는지 확인하세요.
+
`net show interface`

+
다음 명령은 ISL 포트가 스위치 sw1과 sw2에서 작동 중임을 보여줍니다.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name       Spd   MTU    Mode        LLDP         Summary
-----  ---------  ----  -----  ----------  -----------  -----------------------
...
...
UP     swp15      100G  9216   BondMember  sw2 (swp15)  Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  sw2 (swp16)  Master: cluster_isl(UP)

cumulus@sw2:~$ *net show interface*

State  Name       Spd   MTU    Mode        LLDP         Summary
-----  ---------  ----  -----  ----------  -----------  -----------------------
...
...
UP     swp15      100G  9216   BondMember  sw1 (swp15)  Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  sw1 (swp16)  Master: cluster_isl(UP)
----


--
.큐물러스 리눅스 5.x
--
. 새로운 클러스터 스위치 sw1과 sw2에서 노드에 연결되는 모든 포트(ISL 포트 제외)를 비활성화합니다.
+
ISL 포트를 비활성화하면 안 됩니다.

+
다음 명령은 스위치 sw1 및 sw2에서 노드 연결 포트를 비활성화합니다.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set interface swp1s0-3,swp2s0-3,swp3-14 link state down*
cumulus@sw1:~$ *nv config apply*
cumulus@sw1:~$ *nv config save*

cumulus@sw2:~$ *nv set interface swp1s0-3,swp2s0-3,swp3-14 link state down*
cumulus@sw2:~$ *nv config apply*
cumulus@sw2:~$ *nv config save*
----
. 두 SN2100 스위치 sw1과 sw2 사이의 ISL과 ISL의 물리적 포트가 포트 swp15와 swp16에서 작동하는지 확인하세요.
+
`nv show interface`

+
다음 예는 ISL 포트가 스위치 sw1 및 sw2에서 작동 중임을 보여줍니다.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface*

Interface     MTU    Speed  State  Remote Host  Remote Port                          Type    Summary
------------- ------ -----  ------ ------------ ------------------------------------ ------- -------
...
...
+ swp14       9216          down                                                     swp
+ swp15       9216   100G   up     ossg-rcf1    Intra-Cluster Switch ISL Port swp15  swp
+ swp16       9216   100G   up     ossg-rcf2    Intra-Cluster Switch ISL Port swp16  swp


cumulus@sw2:~$ *nv show interface*

Interface     MTU    Speed  State  Remote Host  Remote Port                          Type    Summary
------------- ------ -----  ------ ------------ ------------------------------------ ------- -------
...
...
+ swp14       9216          down                                                     swp
+ swp15       9216   100G   up     ossg-rcf1    Intra-Cluster Switch ISL Port swp15  swp
+ swp16       9216   100G   up     ossg-rcf2    Intra-Cluster Switch ISL Port swp16  swp
----


--
====
. [[3단계]] 모든 클러스터 포트가 작동 중인지 확인합니다.
+
`network port show`

+
각 포트에는 다음이 표시되어야 합니다. `up` ~을 위한 `Link` 그리고 건강하다 `Health Status` .

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show*

Node: node1

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

----
====
. 모든 클러스터 LIF가 작동 중인지 확인하세요.
+
`network interface show`

+
각 클러스터 LIF는 다음과 같이 표시되어야 합니다. `Is Home` 그리고 가지고있다 `Status Admin/Oper` ~의 `up/up` .

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
----
====
. 클러스터 LIF에서 자동 되돌리기를 비활성화합니다.
+
`network interface modify -vserver Cluster -lif * -auto-revert false`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   false
          node1_clus2   false
          node2_clus1   false
          node2_clus2   false

----
====
. 노드 3의 클러스터 포트 e3a에서 케이블을 분리한 다음, SN2100 스위치에서 지원하는 적절한 케이블을 사용하여 e3a를 클러스터 스위치 sw1의 포트 1에 연결합니다.
+
그만큼 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - 스위치"^] 케이블링에 대한 자세한 정보가 포함되어 있습니다.

. 노드4의 클러스터 포트 e3a에서 케이블을 분리한 다음, SN2100 스위치에서 지원하는 적절한 케이블을 사용하여 e3a를 클러스터 스위치 sw1의 포트 2에 연결합니다.


[role="tabbed-block"]
====
.큐물러스 리눅스 4.4.x
--
. [[step8]] 스위치 sw1에서 모든 노드 방향 포트를 활성화합니다.
+
다음 명령은 스위치 sw1의 모든 노드 연결 포트를 활성화합니다.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----


. [[단계]] 스위치 sw1에서 모든 포트가 작동하는지 확인합니다.
+
`net show interface all`

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP            Summary
-----  --------- ----  -----  ---------- --------------- --------
...
DN     swp1s0    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s1    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s2    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s3    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s0    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s1    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s2    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s3    25G   9216   Trunk/L2                   Master: br_default(UP)
UP     swp3      100G  9216   Trunk/L2    node1 (e3a)    Master: br_default(UP)
UP     swp4      100G  9216   Trunk/L2    node2 (e3a)    Master: br_default(UP)
...
...
UP     swp15     100G  9216   BondMember  swp15          Master: cluster_isl(UP)
UP     swp16     100G  9216   BondMember  swp16          Master: cluster_isl(UP)
...
----


--
.큐물러스 리눅스 5.x
--
. [[step8]] 스위치 sw1에서 모든 노드 방향 포트를 활성화합니다.
+
다음 명령은 스위치 sw1의 모든 노드 연결 포트를 활성화합니다.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set interface swp1s0-3,swp2s0-3,swp3-14 link state up*
cumulus@sw1:~$ *nv config apply*
cumulus@sw1:~$ *nv config save*
----


. [[step9]] 스위치 sw1에서 모든 포트가 작동하는지 확인합니다.
+
`nv show interface`

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface*

Interface    State  Speed  MTU    Type      Remote Host                 Remote Port  Summary
-----------  -----  -----  -----  --------  --------------------------  -----------  ----------
...
...
swp1s0       up     10G    9216   swp       odq-a300-1a                         e0a
swp1s1       up     10G    9216   swp       odq-a300-1b                         e0a
swp1s2       down   10G    9216   swp
swp1s3       down   10G    9216   swp
swp2s0       down   25G    9216   swp
swp2s1       down   25G    9216   swp
swp2s2       down   25G    9216   swp
swp2s3       down   25G    9216   swp
swp3         down          9216   swp
swp4         down          9216   swp
...
...
swp14        down          9216   swp
swp15        up     100G   9216   swp       ossg-int-rcf10                    swp15
swp16        up     100G   9216   swp       ossg-int-rcf10                    swp16
----


--
====
. [[step10]] 모든 클러스터 포트가 작동 중인지 확인하세요.
+
`network port show -ipspace Cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 모든 클러스터 포트가 node1과 node2에서 작동 중임을 보여줍니다.

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

----
====
. 클러스터의 노드 상태에 대한 정보를 표시합니다.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 클러스터 내 노드의 상태와 적격성에 대한 정보를 표시합니다.

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

----
====
. 노드 3의 클러스터 포트 e3b에서 케이블을 분리한 다음, SN2100 스위치에서 지원하는 적절한 케이블을 사용하여 e3b를 클러스터 스위치 sw2의 포트 1에 연결합니다.
. 노드4의 클러스터 포트 e3b에서 케이블을 분리한 다음, SN2100 스위치에서 지원하는 적절한 케이블을 사용하여 e3b를 클러스터 스위치 sw2의 포트 2에 연결합니다.


[role="tabbed-block"]
====
.큐물러스 리눅스 4.4.x
--
. [[step14]] 스위치 sw2에서 모든 노드 연결 포트를 활성화합니다.
+
다음 명령은 스위치 sw2에서 노드에 연결된 포트를 활성화합니다.

+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net del interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
. [[step15]] 스위치 sw2에서 모든 포트가 작동하는지 확인합니다.
+
`net show interface all`

+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP            Summary
-----  --------- ----  -----  ---------- --------------- --------
...
DN     swp1s0    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s1    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s2    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s3    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s0    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s1    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s2    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s3    25G   9216   Trunk/L2                   Master: br_default(UP)
UP     swp3      100G  9216   Trunk/L2    node1 (e3b)    Master: br_default(UP)
UP     swp4      100G  9216   Trunk/L2    node2 (e3b)    Master: br_default(UP)
...
...
UP     swp15     100G  9216   BondMember  swp15          Master: cluster_isl(UP)
UP     swp16     100G  9216   BondMember  swp16          Master: cluster_isl(UP)
...
----


. [[step16]] 두 스위치 sw1과 sw2에서 두 노드가 각각 스위치에 대한 연결을 하나씩 가지고 있는지 확인합니다.
+
`net show lldp`

+
다음 예는 sw1과 sw2 스위치 모두에 대한 적절한 결과를 보여줍니다.



[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3a
swp4       100G   Trunk/L2    node2              e3a
swp15      100G   BondMember  sw2                swp15
swp16      100G   BondMember  sw2                swp16

cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3b
swp4       100G   Trunk/L2    node2              e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
--
.큐물러스 리눅스 5.x
--
. [[step14]] 스위치 sw2에서 모든 노드 연결 포트를 활성화합니다.
+
다음 명령은 스위치 sw2에서 노드에 연결된 포트를 활성화합니다.

+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *nv set interface swp1s0-3,swp2s0-3,swp3-14 link state up*
cumulus@sw2:~$ *nv config apply*
cumulus@sw2:~$ *nv config save*
----
. [[step15]] 스위치 sw2에서 모든 포트가 작동하는지 확인합니다.
+
`nv show interface`

+
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *nv show interface*

Interface    State  Speed  MTU    Type      Remote Host                 Remote Port  Summary
-----------  -----  -----  -----  --------  --------------------------  -----------  ----------
...
...
swp1s0       up     10G    9216   swp       odq-a300-1a                         e0a
swp1s1       up     10G    9216   swp       odq-a300-1b                         e0a
swp1s2       down   10G    9216   swp
swp1s3       down   10G    9216   swp
swp2s0       down   25G    9216   swp
swp2s1       down   25G    9216   swp
swp2s2       down   25G    9216   swp
swp2s3       down   25G    9216   swp
swp3         down          9216   swp
swp4         down          9216   swp
...
...
swp14        down          9216   swp
swp15        up     100G   9216   swp       ossg-int-rcf10                    swp15
swp16        up     100G   9216   swp       ossg-int-rcf10                    swp16
----


. [[step16]] 두 스위치 sw1과 sw2에서 두 노드가 각각 스위치에 대한 연결을 하나씩 가지고 있는지 확인합니다.
+
`nv show interface --view=lldp`

+
다음 예는 스위치 sw1과 sw2에 대한 적절한 결과를 보여줍니다.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface --view=lldp*

Interface    Speed  Type      Remote Host                         Remote Port
-----------  -----  --------  ----------------------------------  -----------
...
...
swp1s0       10G    swp       odq-a300-1a                         e0a
swp1s1       10G    swp       odq-a300-1b                         e0a
swp1s2       10G    swp
swp1s3       10G    swp
swp2s0       25G    swp
swp2s1       25G    swp
swp2s2       25G    swp
swp2s3       25G    swp
swp3                swp
swp4                swp
...
...
swp14               swp
swp15        100G   swp       ossg-int-rcf10                      swp15
swp16        100G   swp       ossg-int-rcf10                      swp16

cumulus@sw2:~$ *nv show interface --view=lldp*

Interface    Speed  Type      Remote Host                         Remote Port
-----------  -----  --------  ----------------------------------  -----------
...
...
swp1s0       10G    swp       odq-a300-1a                         e0a
swp1s1       10G    swp       odq-a300-1b                         e0a
swp1s2       10G    swp
swp1s3       10G    swp
swp2s0       25G    swp
swp2s1       25G    swp
swp2s2       25G    swp
swp2s3       25G    swp
swp3                swp
swp4                swp
...
...
swp14               swp
swp15        100G   swp       ossg-int-rcf10                      swp15
swp16        100G   swp       ossg-int-rcf10                      swp16
----


--
====
. [[step17]] 클러스터에서 검색된 네트워크 장치에 대한 정보를 표시합니다.
+
`network device-discovery show -protocol lldp`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3          -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4          -
----
====
. 모든 클러스터 포트가 작동 중인지 확인하세요.
+
`network port show -ipspace Cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 모든 클러스터 포트가 node1과 node2에서 작동 중임을 보여줍니다.

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

----
====




=== 3단계: 구성 확인

. 모든 클러스터 LIF에서 자동 되돌리기를 활성화합니다.
+
`net interface modify -vserver Cluster -lif * -auto-revert true`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *net interface modify -vserver Cluster -lif * -auto-revert true*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
----
====
. 모든 인터페이스가 표시되는지 확인하세요 `true` ~을 위한 `Is Home` :
+
`net interface show -vserver Cluster`

+

NOTE: 완료하는 데 1분 정도 걸릴 수 있습니다.

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 모든 LIF가 node1과 node2에 있고 `Is Home` 결과는 사실입니다:

[listing, subs="+quotes"]
----
cluster1::*> *net interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true

----
====
. 설정이 비활성화되었는지 확인하세요.
+
`network options switchless-cluster show`

+
.예를 보여주세요
[%collapsible]
====
다음 예제의 잘못된 출력은 구성 설정이 비활성화되었음을 보여줍니다.

[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: *false*
----
====
. 클러스터의 노드 멤버 상태를 확인하세요.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 클러스터 내 노드의 상태와 적격성에 대한 정보를 보여줍니다.

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. 원격 클러스터 인터페이스의 연결성을 확인하세요.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
당신은 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령:

`network interface check cluster-connectivity start`그리고 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*참고:* 실행하기 전에 몇 초 동안 기다리십시오. `show` 세부 정보를 표시하는 명령입니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스의 경우 다음을 사용할 수도 있습니다. `cluster ping-cluster -node <name>` 연결성을 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node1
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step6]] 권한 수준을 다시 관리자로 변경합니다.
+
`set -privilege admin`

. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.다음은 무엇인가요?
스위치를 마이그레이션한 후에는 다음을 수행할 수 있습니다. link:../switch-cshm/config-overview.html["스위치 상태 모니터링 구성"].
