---
permalink: switch-nvidia-sn2100/migrate-cn1610-sn2100-cluster-switch.html 
sidebar: sidebar 
keywords: migrate cluster NVIDIA SN2100 cluster switches cn1610 
summary: ONTAP 클러스터용 NetApp CN1610 클러스터 스위치를 NVIDIA SN2100 클러스터 네트워크 스위치로 중단 없이 마이그레이션할 수 있습니다. 
---
= CN1610 클러스터 스위치를 NVIDIA SN2100 클러스터 스위치로 마이그레이션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 클러스터용 NetApp CN1610 클러스터 스위치를 NVIDIA SN2100 클러스터 스위치로 마이그레이션할 수 있습니다. 이것은 방해가 되지 않는 절차입니다.



== 검토 요구 사항

NetApp CN1610 클러스터 스위치를 NVIDIA SN2100 클러스터 스위치로 교체하는 경우 특정 구성 정보, 포트 연결 및 케이블 요구 사항을 알고 있어야 합니다. 보다link:configure-overview-sn2100-cluster.html["NVIDIA SN2100 스위치 설치 및 구성 개요"] .

.지원되는 스위치
다음 클러스터 스위치가 지원됩니다.

* NetApp CN1610
* NVIDIA SN2100


지원되는 포트 및 해당 구성에 대한 자세한 내용은 다음을 참조하세요. https://hwu.netapp.com/["Hardware Universe"^] .

.시작하기 전에
구성에 대한 다음 요구 사항을 충족하는지 확인하세요.

* 기존 클러스터가 올바르게 설정되어 작동하고 있습니다.
* 모든 클러스터 포트는 중단 없는 작업을 보장하기 위해 *작동* 상태입니다.
* NVIDIA SN2100 클러스터 스위치는 참조 구성 파일(RCF)이 적용된 올바른 버전의 Cumulus Linux에서 구성되고 작동합니다.
* 기존 클러스터 네트워크 구성은 다음과 같습니다.
+
** CN1610 스위치를 사용하는 중복되고 완벽한 기능을 갖춘 NetApp 클러스터입니다.
** CN1610 스위치와 새로운 스위치 모두에 대한 관리 연결 및 콘솔 액세스가 가능합니다.
** 모든 클러스터 LIF가 홈 포트에 있는 클러스터 LIF를 사용하여 업 상태에 있습니다.
** CN1610 스위치와 새로운 스위치 사이에 ISL 포트가 활성화되고 케이블이 연결되었습니다.


* 일부 포트는 NVIDIA SN2100 스위치에서 40GbE 또는 100GbE로 실행되도록 구성됩니다.
* 노드에서 NVIDIA SN2100 클러스터 스위치로 40GbE 및 100GbE 연결을 계획, 마이그레이션 및 문서화했습니다.




== 스위치 마이그레이션

.예시에 관하여
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 기존 CN1610 클러스터 스위치는 _c1_과 _c2_입니다.
* 새로운 NVIDIA SN2100 클러스터 스위치는 _sw1_과 _sw2_입니다.
* 노드는 _node1_과 _node2_입니다.
* 클러스터 LIF는 각각 노드 1의 _node1_clus1_과 _node1_clus2_이고, 노드 2의 _node2_clus1_과 _node2_clus2_입니다.
* 그만큼 `cluster1::*>` 프롬프트는 클러스터의 이름을 나타냅니다.
* 이 절차에서 사용되는 클러스터 포트는 _e3a_와 _e3b_입니다.
* 브레이크아웃 포트는 swp[포트]s[브레이크아웃 포트 0-3] 형식을 따릅니다.  예를 들어, swp1의 4개 브레이크아웃 포트는 _swp1s0_, _swp1s1_, _swp1s2_, _swp1s3_입니다.


.이 작업에 관하여
이 절차는 다음 시나리오를 다룹니다.

* 스위치 c2는 먼저 스위치 sw2로 교체됩니다.
+
** 클러스터 노드의 포트를 종료합니다.  클러스터 불안정성을 방지하려면 모든 포트를 동시에 종료해야 합니다.
** 그런 다음 노드와 c2 사이의 케이블이 c2에서 분리되고 sw2에 다시 연결됩니다.


* 스위치 c1은 스위치 sw1로 교체됩니다.
+
** 클러스터 노드의 포트를 종료합니다.  클러스터 불안정성을 방지하려면 모든 포트를 동시에 종료해야 합니다.
** 그런 다음 노드와 c1 사이의 케이블이 c1에서 분리되고 sw1에 다시 연결됩니다.





NOTE: 이 절차 중에는 작동 중인 ISL(스위치 간 링크)이 필요하지 않습니다. 이는 RCF 버전 변경으로 인해 ISL 연결에 일시적으로 영향을 미칠 수 있기 때문에 설계된 기능입니다. 중단 없는 클러스터 운영을 보장하기 위해 다음 절차에서는 대상 스위치에서 단계를 수행하는 동안 모든 클러스터 LIF를 운영 파트너 스위치로 마이그레이션합니다.



=== 1단계: 마이그레이션 준비

. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
여기서 _x_는 유지 관리 기간(시간)입니다.

. 계속할지 묻는 메시지가 나타나면 *y*를 입력하여 권한 수준을 고급으로 변경합니다.
+
`set -privilege advanced`

+
고급 프롬프트(*>)가 나타납니다.

. 클러스터 LIF에서 자동 되돌리기를 비활성화합니다.
+
`network interface modify -vserver Cluster -lif * -auto-revert false`





=== 2단계: 포트 및 케이블 구성

. 각 클러스터 인터페이스의 관리 또는 운영 상태를 확인합니다.
+
각 포트는 다음과 같이 표시되어야 합니다. `Link` 그리고 `healthy` ~을 위한 `Health Status` .

+
.. 네트워크 포트 속성을 표시합니다.
+
`network port show -ipspace Cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
.. LIF와 지정된 홈 노드에 대한 정보를 표시합니다.
+
`network interface show -vserver Cluster`

+
각 LIF는 다음을 표시해야 합니다. `up/up` ~을 위한 `Status Admin/Oper` 그리고 `true` ~을 위한 `Is Home` .

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current     Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node        Port    Home
----------- -----------  ---------- ------------------ ----------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
            node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
            node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
            node2_clus2  up/up      169.254.19.183/16  node2       e3b     true

----
====


. 각 노드의 클러스터 포트는 다음 명령을 사용하여 (노드 관점에서) 다음과 같은 방식으로 기존 클러스터 스위치에 연결됩니다.
+
`network device-discovery show -protocol`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e3a    c1 (6a:ad:4f:98:3b:3f)    0/1               -
            e3b    c2 (6a:ad:4f:98:4c:a4)    0/1               -
node2      /cdp
            e3a    c1 (6a:ad:4f:98:3b:3f)    0/2               -
            e3b    c2 (6a:ad:4f:98:4c:a4)    0/2               -
----
====
. 클러스터 포트와 스위치는 다음 명령을 사용하여 (스위치 관점에서) 다음과 같은 방식으로 연결됩니다.
+
`show cdp neighbors`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 0/1           124     H          AFF-A400         e3a
node2                 0/2           124     H          AFF-A400         e3a
c2                    0/13          179     S I s      CN1610           0/13
c2                    0/14          175     S I s      CN1610           0/14
c2                    0/15          179     S I s      CN1610           0/15
c2                    0/16          175     S I s      CN1610           0/16

c2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute


Device-ID             Local Intrfce Hldtme Capability  Platform         Port ID
node1                 0/1           124    H           AFF-A400         e3b
node2                 0/2           124    H           AFF-A400         e3b
c1                    0/13          175    S I s       CN1610           0/13
c1                    0/14          175    S I s       CN1610           0/14
c1                    0/15          175    S I s       CN1610           0/15
c1                    0/16          175    S I s       CN1610           0/16
----
====
. 원격 클러스터 인터페이스의 연결성을 확인하세요.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
당신은 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령:

`network interface check cluster-connectivity start`그리고 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*참고:* 실행하기 전에 몇 초 동안 기다리십시오. `show` 세부 정보를 표시하는 명령입니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스의 경우 다음을 사용할 수도 있습니다. `cluster ping-cluster -node <name>` 연결성을 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e3a
Cluster node1_clus2 169.254.49.125 node1     e3b
Cluster node2_clus1 169.254.47.194 node2     e3a
Cluster node2_clus2 169.254.19.183 node2     e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[5단계]] 스위치 c2에서 클러스터 LIF를 장애 조치하기 위해 노드의 클러스터 포트에 연결된 포트를 종료합니다.
+
[listing, subs="+quotes"]
----
(c2)# *configure*
(c2)(Config)# *interface 0/1-0/12*
(c2)(Interface 0/1-0/12)# *shutdown*
(c2)(Interface 0/1-0/12)# *exit*
(c2)(Config)# *exit*
(c2)#
----
. NVIDIA SN2100에서 지원하는 적절한 케이블을 사용하여 노드 클러스터 포트를 이전 스위치 c2에서 새 스위치 sw2로 이동합니다.
. 네트워크 포트 속성을 표시합니다.
+
`network port show -ipspace Cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
. 각 노드의 클러스터 포트는 이제 노드 관점에서 다음과 같은 방식으로 클러스터 스위치에 연결됩니다.
+
`network device-discovery show -protocol`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /lldp
            e3a    c1  (6a:ad:4f:98:3b:3f)   0/1               -
            e3b    sw2 (b8:ce:f6:19:1a:7e)   swp3              -
node2      /lldp
            e3a    c1  (6a:ad:4f:98:3b:3f)   0/2               -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4              -
----
====
. 스위치 sw2에서 모든 노드 클러스터 포트가 작동 중인지 확인하세요.
+
`net show interface`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
====
. 스위치 c1에서 클러스터 LIF에 대한 장애 조치를 취하기 위해 노드의 클러스터 포트에 연결된 포트를 종료합니다.
+
[listing, subs="+quotes"]
----
(c1)# *configure*
(c1)(Config)# *interface 0/1-0/12*
(c1)(Interface 0/1-0/12)# *shutdown*
(c1)(Interface 0/1-0/12)# *exit*
(c1)(Config)# *exit*
(c1)#
----
. NVIDIA SN2100에서 지원하는 적절한 케이블을 사용하여 노드 클러스터 포트를 이전 스위치 c1에서 새 스위치 sw1로 이동합니다.
. 클러스터의 최종 구성을 확인하세요.
+
`network port show -ipspace Cluster`

+
각 포트에는 다음이 표시되어야 합니다. `up` ~을 위한 `Link` 그리고 `healthy` ~을 위한 `Health Status` .

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                       Ignore
                                                 Speed(Mbps)  Health   Health
Port      IPspace    Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ---------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster    Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster    Cluster          up   9000  auto/100000  healthy  false
----
====
. 각 노드의 클러스터 포트는 이제 노드 관점에서 다음과 같은 방식으로 클러스터 스위치에 연결됩니다.
+
`network device-discovery show -protocol`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3            -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3            -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4            -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4            -
----
====
. 스위치 sw1 및 sw2에서 모든 노드 클러스터 포트가 작동 중인지 확인합니다.
+
`net show interface`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3a               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3a               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw2 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw2 (swp16)       Master: cluster_isl(UP)


cumulus@sw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- -----------------------
...
...
UP     swp3         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2    e3b               Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
====
. 두 노드 모두 각 스위치에 하나의 연결이 있는지 확인하세요.
+
`net show lldp`

+
.예를 보여주세요
[%collapsible]
====
다음 예는 두 스위치에 대한 적절한 결과를 보여줍니다.

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost          RemotePort
---------  -----  ----------  ------------------  -----------
swp3       100G   Trunk/L2    node1               e3a
swp4       100G   Trunk/L2    node2               e3a
swp15      100G   BondMember  sw2                 swp15
swp16      100G   BondMember  sw2                 swp16

cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost          RemotePort
---------  -----  ----------  ------------------  -----------
swp3       100G   Trunk/L2    node1               e3b
swp4       100G   Trunk/L2    node2               e3b
swp15      100G   BondMember  sw1                 swp15
swp16      100G   BondMember  sw1                 swp16
----
====




=== 3단계: 구성 확인

. 클러스터 LIF에서 자동 되돌리기를 활성화합니다.
+
`cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true`

. 모든 클러스터 네트워크 LIF가 홈 포트로 돌아왔는지 확인하세요.
+
`network interface show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
----
====
. 권한 수준을 다시 관리자로 변경합니다.
+
`set -privilege admin`

. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.다음은 무엇인가요?
스위치를 마이그레이션한 후에는 다음을 수행할 수 있습니다. link:../switch-cshm/config-overview.html["스위치 상태 모니터링 구성"].
