---
permalink: switch-nvidia-sn2100/migrate-cisco-storage-switch-sn2100-cluster.html 
sidebar: sidebar 
keywords: migrating to a storage switch with NVIDIA SN2100 storage switches, how to migrate 
summary: ONTAP 클러스터용 기존 Cisco 스위치를 NVIDIA SN2100 스토리지 스위치로 중단 없이 마이그레이션할 수 있습니다. 
---
= Cisco 스토리지 스위치에서 NVIDIA SN2100 스토리지 스위치로 마이그레이션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 클러스터용 기존 Cisco 스위치에서 NVIDIA SN2100 스토리지 스위치로 마이그레이션할 수 있습니다. 이것은 방해가 되지 않는 절차입니다.



== 검토 요구 사항

일부 오래된 Cisco 스위치를 NVIDIA SN2100 스토리지 스위치로 교체하는 경우 특정 구성 정보, 포트 연결 및 케이블 요구 사항을 알고 있어야 합니다. 보다link:configure-overview-sn2100-cluster.html["NVIDIA SN2100 스위치 설치 및 구성 개요"] .

.지원되는 스위치
다음 스토리지 스위치가 지원됩니다.

* Cisco 넥서스 9336C-FX2
* Cisco 넥서스 3232C


지원되는 포트 및 해당 구성에 대한 자세한 내용은 다음을 참조하세요. https://hwu.netapp.com/["Hardware Universe"^] .

.필요한 것
다음 사항을 확인하세요.

* 기존 클러스터가 제대로 설정되어 작동하고 있습니다.
* 모든 스토리지 포트는 중단 없는 운영을 보장하기 위해 작동 상태입니다.
* NVIDIA SN2100 스토리지 스위치는 참조 구성 파일(RCF)이 적용된 적절한 버전의 Cumulus Linux에서 구성되고 작동합니다.
* 기존 스토리지 네트워크 구성은 다음과 같습니다.
+
** 두 가지 이전 Cisco 스위치를 모두 사용하는 중복되고 완벽한 기능을 갖춘 NetApp 클러스터입니다.
** 기존 Cisco 스위치와 새로운 스위치 모두에 대한 관리 연결 및 콘솔 액세스가 가능합니다.
** 클러스터 LIf가 있는 *up* 상태의 모든 클러스터 LIF는 홈 포트에 있습니다.
** 기존 Cisco 스위치와 새로운 스위치 사이에 ISL 포트가 활성화되어 있고 케이블로 연결되어 있습니다.


* NVIDIA SN2100 스위치의 일부 포트는 100GbE에서 실행되도록 구성되어 있습니다.
* 노드에서 NVIDIA SN2100 스토리지 스위치로 100GbE 연결을 계획, 마이그레이션 및 문서화했습니다.




== 스위치 마이그레이션

.예시에 관하여
이 절차에서는 Cisco Nexus 9336C-FX2 스토리지 스위치가 예제 명령과 출력에 사용됩니다.

이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 기존의 Cisco Nexus 9336C-FX2 스토리지 스위치는 _S1_과 _S2_입니다.
* 새로운 NVIDIA SN2100 스토리지 스위치는 _sw1_과 _sw2_입니다.
* 노드는 _node1_과 _node2_입니다.
* 클러스터 LIF는 각각 노드 1의 _node1_clus1_과 _node1_clus2_이고, 노드 2의 _node2_clus1_과 _node2_clus2_입니다.
* 그만큼 `cluster1::*>` 프롬프트는 클러스터의 이름을 나타냅니다.
* 이 절차에서 사용되는 네트워크 포트는 _e5a_와 _e5b_입니다.
* 브레이크아웃 포트는 swp1s0-3 형식을 따릅니다.  예를 들어 swp1의 4개 브레이크아웃 포트는 _swp1s0_, _swp1s1_, _swp1s2_, _swp1s3_입니다.
* 스위치 S2는 먼저 스위치 sw2로 교체되고, 그 다음 스위치 S1은 스위치 sw1로 교체됩니다.
+
** 그런 다음 노드와 S2 사이의 케이블이 S2에서 분리되고 sw2에 다시 연결됩니다.
** 그런 다음 노드와 S1 간의 케이블이 S1에서 분리되고 sw1에 다시 연결됩니다.






=== 1단계: 마이그레이션 준비

. AutoSupport 가 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
여기서 _x_는 유지 관리 기간(시간)입니다.

. 계속할지 묻는 메시지가 나타나면 *y*를 입력하여 권한 수준을 고급으로 변경합니다. `set -privilege advanced`
+
고급 프롬프트(*>)가 나타납니다.





=== 2단계: 포트 및 케이블 구성

. 각 스토리지 인터페이스의 관리 또는 운영 상태를 확인합니다.
+
각 포트는 활성화되어 표시되어야 합니다. `Status` .

+
네트워크 포트 속성을 표시합니다.

+
`storage port show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. 각 노드의 스토리지 포트는 다음 명령을 사용하여 (노드 관점에서) 다음과 같은 방식으로 기존 스토리지 스위치에 연결됩니다.
+
`network device-discovery show -protocol lldp`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/1           -
            e5b    S2 (7c:ad:4f:98:8e:3c)    Eth1/1           -
node2      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/2           -
            e5b    S2 (7c:ad:4f:98:8e:3c)    Eth1/2           -
----
====
. 스위치 S1과 S2에서 스토리지 포트와 스위치는 다음 명령을 사용하여 (스위치 관점에서) 다음과 같은 방식으로 연결됩니다.
+
`show lldp neighbors`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
S1# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability           Port ID
node1                 Eth1/1         121         S                    e0c
node2                 Eth1/2         121         S                    e0c
SHFGD1947000186       Eth1/10        120         S                    e0a         
SHFGD1947000186       Eth1/11        120         S                    e0a         
SHFGB2017000269       Eth1/12        120         S                    e0a         
SHFGB2017000269       Eth1/13        120         S                    e0a

S2# *show lldp neighbors*

Capability Codes: (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device,
                  (W) WLAN Access Point, (P) Repeater, (S) Station (O) Other

Device-ID             Local Intf     Holdtime    Capability          Port ID
node1                 Eth1/1         121         S                   e5b
node2                 Eth1/2         121         S                   e5b
SHFGD1947000186       Eth1/10        120         S                   e0b         
SHFGD1947000186       Eth1/11        120         S                   e0b         
SHFGB2017000269       Eth1/12        120         S                   e0b         
SHFGB2017000269       Eth1/13        120         S                   e0b
----
====
. 스위치 sw2에서 디스크 선반의 스토리지 포트와 노드에 연결된 포트를 종료합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net add interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. NVIDIA SN2100에서 지원하는 적절한 케이블을 사용하여 컨트롤러와 디스크 쉘프의 노드 스토리지 포트를 기존 스위치 S2에서 새 스위치 sw2로 이동합니다.
. 스위치 sw2에서 노드의 스토리지 포트와 디스크 쉘프에 연결된 포트를 불러옵니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net del interface swp1-16 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. 각 노드의 저장 포트는 이제 노드 관점에서 다음과 같은 방식으로 스위치에 연결됩니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface      Platform
----------- ------ ------------------------- -------------  ----------------
node1      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/1         -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp1           -

node2      /lldp
            e0c    S1 (7c:ad:4f:98:6d:f0)    Eth1/2         -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp2           -
----
====
. 네트워크 포트 속성을 확인하세요.
+
`storage port show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. 스위치 sw2에서 모든 노드 스토리지 포트가 작동하는지 확인하세요.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. 스위치 sw1에서 노드의 스토리지 포트와 디스크 쉘프에 연결된 포트를 종료합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp1-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. NVIDIA SN2100에서 지원하는 적절한 케이블을 사용하여 컨트롤러의 노드 스토리지 포트와 디스크 쉘프를 기존 스위치 S1에서 새 스위치 sw1로 이동합니다.
. 스위치 sw1에서 노드의 스토리지 포트와 디스크 쉘프에 연결된 포트를 불러옵니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp1-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. 각 노드의 저장 포트는 이제 노드 관점에서 다음과 같은 방식으로 스위치에 연결됩니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface       Platform
----------- ------ ------------------------- --------------  ----------------
node1      /lldp
            e0c    sw1 (b8:ce:f6:19:1b:96)   swp1            -
            e5b    sw2 (b8:ce:f6:19:1a:7e)   swp1            -

node2      /lldp
            e0c    sw1  (b8:ce:f6:19:1b:96)  swp2            -
            e5b    sw2  (b8:ce:f6:19:1a:7e)  swp2            -
----
====
. 최종 구성을 확인하세요.
+
`storage port show`

+
각 포트는 활성화되어 표시되어야 합니다. `State` 그리고 활성화됨 `Status` .

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
node1
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
node2
               e0c  ENET  storage  100   enabled  online      30
               e0d  ENET  storage    0   enabled  offline     30
               e5a  ENET  storage    0   enabled  offline     30
               e5b  ENET  storage  100   enabled  online      30
cluster1::*>
----
====
. 스위치 sw2에서 모든 노드 스토리지 포트가 작동하는지 확인하세요.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name    Spd   MTU    Mode        LLDP                  Summary
-----  ------  ----  -----  ----------  --------------------  --------------------
...
...
UP     swp1    100G  9216   Trunk/L2   node1 (e5b)             Master: bridge(UP)
UP     swp2    100G  9216   Trunk/L2   node2 (e5b)             Master: bridge(UP)
UP     swp3    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp4    100G  9216   Trunk/L2   SHFFG1826000112 (e0b)   Master: bridge(UP)
UP     swp5    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP)
UP     swp6    100G  9216   Trunk/L2   SHFFG1826000102 (e0b)   Master: bridge(UP))
...
...
----
====
. 두 노드 모두 각 스위치에 하나의 연결이 있는지 확인하세요.
+
`net show lldp`

+
.예를 보여주세요
[%collapsible]
====
다음 예는 두 스위치에 대한 적절한 결과를 보여줍니다.

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*
LocalPort  Speed  Mode      RemoteHost             RemotePort
---------  -----  --------  ---------------------  -----------
...
swp1       100G   Trunk/L2  node1                  e0c
swp2       100G   Trunk/L2  node2                  e0c
swp3       100G   Trunk/L2  SHFFG1826000112        e0a
swp4       100G   Trunk/L2  SHFFG1826000112        e0a
swp5       100G   Trunk/L2  SHFFG1826000102        e0a
swp6       100G   Trunk/L2  SHFFG1826000102        e0a

cumulus@sw2:~$ *net show lldp*
LocalPort  Speed  Mode      RemoteHost             RemotePort
---------  -----  --------  ---------------------  -----------
...
swp1       100G   Trunk/L2  node1                  e5b
swp2       100G   Trunk/L2  node2                  e5b
swp3       100G   Trunk/L2  SHFFG1826000112        e0b
swp4       100G   Trunk/L2  SHFFG1826000112        e0b
swp5       100G   Trunk/L2  SHFFG1826000102        e0b
swp6       100G   Trunk/L2  SHFFG1826000102        e0b
----
====




=== 3단계: 절차 완료

. 이더넷 스위치 상태 모니터 로그 수집 기능에 대한 비밀번호를 만듭니다.
+
`system switch ethernet log setup-password`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*sw1*
*sw2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. 이더넷 스위치 상태 모니터 로그 수집 기능을 활성화합니다.
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
10분간 기다린 후 로그 수집이 완료되었는지 확인하세요.

+
`system switch ethernet log show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> system switch ethernet log show
Log Collection Enabled: true

Index  Switch                       Log Timestamp        Status
------ ---------------------------- -------------------  ---------    
1      sw1 (b8:ce:f6:19:1b:42)      4/29/2022 03:05:25   complete   
2      sw2 (b8:ce:f6:19:1b:96)      4/29/2022 03:07:42   complete
----
====
+

CAUTION: 이러한 명령 중 하나라도 오류를 반환하거나 로그 수집이 완료되지 않으면 NetApp 지원팀에 문의하세요.

. 권한 수준을 다시 관리자로 변경합니다.
+
`set -privilege admin`

. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`


