---
permalink: switch-nvidia-sn2100/replace-sn2100-switch-cluster.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nvidia, switch, cluster, network, nondisruptive, procedure, ndu, replace a nvidia msn2100 cluster switch - nvidia SN2100 
summary: '클러스터 네트워크에서 결함이 있는 NVIDIA SN2100 스위치를 교체하는 것은 중단 없는 절차(NDU)입니다.' 
---
= NVIDIA SN2100 클러스터 스위치 교체
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 네트워크에서 결함이 있는 NVIDIA SN2100 스위치를 교체하려면 다음 절차를 따르세요. 이는 중단 없는 절차(NDU)입니다.



== 검토 요구 사항

.기존 클러스터 및 네트워크 인프라
다음 사항을 확인하세요.

* 기존 클러스터는 적어도 하나의 완전히 연결된 클러스터 스위치를 갖추고 완벽하게 작동하는 것으로 검증되었습니다.
* 모든 클러스터 포트가 작동 중입니다.
* 모든 클러스터 논리 인터페이스(LIF)가 작동 중이며 홈 포트에 있습니다.
* ONTAP `cluster ping-cluster -node node1` 명령은 기본 연결과 PMTU보다 큰 통신이 모든 경로에서 성공적임을 나타냅니다.


.NVIDIA SN2100 교체 스위치
다음 사항을 확인하세요.

* 교체 스위치의 관리 네트워크 연결이 작동합니다.
* 교체 스위치에 대한 콘솔 접근이 가능합니다.
* 노드 연결은 swp1부터 swp14까지의 포트입니다.
* 모든 ISL(Inter-Switch Link) 포트는 swp15 및 swp16 포트에서 비활성화됩니다.
* 원하는 참조 구성 파일(RCF)과 Cumulus 운영 체제 이미지 스위치가 스위치에 로드됩니다.
* 스위치의 초기 사용자 정의가 완료되었습니다.


또한 STP, SNMP, SSH 등 이전 사이트 사용자 정의가 새 스위치에 복사되었는지 확인하세요.


NOTE: 클러스터 LIF가 호스팅되는 노드에서 클러스터 LIF를 마이그레이션하는 명령을 실행해야 합니다.



== 콘솔 로깅 활성화

NetApp 사용 중인 장치에서 콘솔 로깅을 활성화하고 스위치를 교체할 때 다음 작업을 수행할 것을 강력히 권장합니다.

* 유지관리 중에는 AutoSupport 활성화해 두세요.
* 유지 관리 기간 동안 케이스 생성을 비활성화하려면 유지 관리 전후에 유지 관리 AutoSupport 트리거합니다.  이 지식 기반 문서를 참조하세요. https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: 예약된 유지 관리 기간 동안 자동 케이스 생성을 억제하는 방법"^] 자세한 내용은.
* 모든 CLI 세션에 대한 세션 로깅을 활성화합니다.  세션 로깅을 활성화하는 방법에 대한 지침은 이 기술 자료 문서의 "세션 출력 로깅" 섹션을 검토하세요. https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP 시스템에 대한 최적의 연결을 위해 PuTTY를 구성하는 방법"^] .




== 스위치를 교체하세요

.예시에 관하여
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 기존 NVIDIA SN2100 스위치의 이름은 _sw1_과 _sw2_입니다.
* 새로운 NVIDIA SN2100 스위치의 이름은 _nsw2_입니다.
* 노드 이름은 _node1_과 _node2_입니다.
* 각 노드의 클러스터 포트는 _e3a_와 _e3b_로 명명됩니다.
* 클러스터 LIF 이름은 node1의 경우 _node1_clus1_과 _node1_clus2_이고, node2의 경우 _node2_clus1_과 _node2_clus2_입니다.
* 모든 클러스터 노드에 대한 변경 사항에 대한 프롬프트는 다음과 같습니다. `cluster1::*>`
* 브레이크아웃 포트는 swp[포트]s[브레이크아웃 포트 0-3] 형식을 따릅니다.  예를 들어, swp1의 4개 브레이크아웃 포트는 _swp1s0_, _swp1s1_, _swp1s2_, _swp1s3_입니다.


.클러스터 네트워크 토폴로지에 대하여
이 절차는 다음 클러스터 네트워크 토폴로지를 기반으로 합니다.

.예시 토폴로지 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false


cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true


cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3          -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4          -
----
+

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    sw2                e3a
swp4       100G   Trunk/L2    sw2                e3a
swp15      100G   BondMember  sw2                swp15
swp16      100G   BondMember  sw2                swp16


cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    sw1                e3b
swp4       100G   Trunk/L2    sw1                e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
====


=== 1단계: 교체 준비

. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
여기서 _x_는 유지 관리 기간(시간)입니다.

. 계속할지 묻는 메시지가 나타나면 *y*를 입력하여 권한 수준을 고급으로 변경합니다.
+
`set -privilege advanced`

+
고급 프롬프트(*>)가 나타납니다.

. 스위치 nsw2에 적절한 RCF와 이미지를 설치하고 필요한 현장 준비를 합니다.
+
필요한 경우, 새로운 스위치에 적합한 RCF 및 Cumulus 소프트웨어 버전을 확인하고 다운로드하고 설치하세요.

+
.. _NVIDIA 지원_ 사이트에서 클러스터 스위치에 적용되는 Cumulus 소프트웨어를 다운로드할 수 있습니다.  다운로드 페이지의 단계에 따라 설치하려는 ONTAP 소프트웨어 버전에 맞는 Cumulus Linux를 다운로드하세요.
.. 해당 RCF는 다음에서 사용할 수 있습니다.link:https://mysupport.netapp.com/site/products/all/details/nvidia-cluster-storage-switch/downloads-tab["_NVIDIA 클러스터 및 스토리지 스위치_"^] 페이지.  다운로드 페이지의 단계에 따라 설치하려는 ONTAP 소프트웨어 버전에 맞는 올바른 RCF를 다운로드하세요.






=== 2단계: 포트 및 케이블 구성

[role="tabbed-block"]
====
.큐물러스 리눅스 4.4.3
--
. 새로운 스위치 nsw2에서 admin으로 로그인하고 노드 클러스터 인터페이스에 연결될 모든 포트(swp1~swp14 포트)를 종료합니다.
+
클러스터 노드의 LIF는 이미 각 노드의 다른 클러스터 포트로 장애 조치되었어야 합니다.

+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@nsw2:~$ *net pending*
cumulus@nsw2:~$ *net commit*
----
. 클러스터 LIF에서 자동 되돌리기를 비활성화합니다.
+
`network interface modify -vserver Cluster -lif * -auto-revert false`

+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

Warning: Disabling the auto-revert feature of the cluster logical interface may effect the availability of your cluster network. Are you sure you want to continue? {y|n}: *y*
----
. 모든 클러스터 LIF에서 자동 되돌리기가 비활성화되었는지 확인하세요.
+
`net interface show -vserver Cluster -fields auto-revert`

. SN2100 스위치 sw1에서 ISL 포트 swp15와 swp16을 종료합니다.
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp15-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
. SN2100 sw1 스위치에서 모든 케이블을 제거한 다음 SN2100 nsw2 스위치의 동일한 포트에 연결합니다.
. sw1과 nsw2 스위치 사이에 ISL 포트 swp15와 swp16을 연결합니다.
+
다음 명령은 스위치 sw1에서 ISL 포트 swp15 및 swp16을 활성화합니다.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp15-16 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
+
다음 예에서는 ISL 포트가 스위치 sw1에서 작동 중임을 보여줍니다.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP           Summary
-----  -----------  ----  -----  ----------  -------------- ----------------------
...
...
UP     swp15        100G  9216   BondMember  nsw2 (swp15)   Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  nsw2 (swp16)   Master: cluster_isl(UP)
----
+
다음 예에서는 ISL 포트가 스위치 nsw2에서 작동 중임을 보여줍니다.

+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP           Summary
-----  -----------  ----  -----  ----------  -------------  -----------------------
...
...
UP     swp15        100G  9216   BondMember  sw1 (swp15)    Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)    Master: cluster_isl(UP)
----
. 포트를 확인하세요 `e3b` 모든 노드에 적용됩니다.
+
`network port show -ipspace Cluster`

+
출력은 다음과 유사해야 합니다.

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                         Ignore
                                                   Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ----- ------------ -------- -------
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false


Node: node2
                                                                         Ignore
                                                   Speed(Mbps) Health    Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status    Status
--------- ------------ ---------------- ---- ----- ----------- --------- -------
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false
----
. 각 노드의 클러스터 포트는 이제 노드 관점에서 다음과 같은 방식으로 클러스터 스위치에 연결됩니다.
+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1  (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    nsw2 (b8:ce:f6:19:1b:b6)   swp3          -
node2      /lldp
            e3a    sw1  (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    nsw2 (b8:ce:f6:19:1b:b6)   swp4          -
----
. 모든 노드 클러스터 포트가 작동 중인지 확인하세요.
+
`net show interface`

+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2                      Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2                      Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
. 두 노드 모두 각 스위치에 하나의 연결이 있는지 확인하세요.
+
`net show lldp`

+
다음 예는 두 스위치에 대한 적절한 결과를 보여줍니다.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3a
swp4       100G   Trunk/L2    node2              e3a
swp15      100G   BondMember  nsw2               swp15
swp16      100G   BondMember  nsw2               swp16


cumulus@nsw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1                e3b
swp4       100G   Trunk/L2    node2                e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
. 클러스터 LIF에서 자동 되돌리기를 활성화합니다.
+
`cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true`

. 스위치 nsw2에서 노드의 네트워크 포트에 연결된 포트를 불러옵니다.
+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *net del interface swp1-14 link down*
cumulus@nsw2:~$ *net pending*
cumulus@nsw2:~$ *net commit*
----
. 클러스터의 노드에 대한 정보를 표시합니다.
+
`cluster show`

+
이 예에서는 이 클러스터의 node1과 node2에 대한 노드 상태가 참임을 보여줍니다.

+
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node          Health  Eligibility
------------- ------- ------------
node1         true    true
node2         true    true
----
. 모든 물리적 클러스터 포트가 작동 중인지 확인하세요.
+
`network port show ipspace Cluster`

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node node1                                                               Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace     Broadcast Domain  Link  MTU   Admin/Oper  Status   Status
--------- ----------- ----------------- ----- ----- ----------- -------- ------
e3a       Cluster     Cluster           up    9000  auto/10000  healthy  false
e3b       Cluster     Cluster           up    9000  auto/10000  healthy  false

Node: node2
                                                                         Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link  MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ----- ----- ----------- -------- ------
e3a       Cluster      Cluster          up    9000  auto/10000  healthy  false
e3b       Cluster      Cluster          up    9000  auto/10000  healthy  false
----


--
.큐물러스 리눅스 5.x
--
. 새로운 스위치 nsw2에서 admin으로 로그인하고 노드 클러스터 인터페이스에 연결될 모든 포트(swp1~swp14 포트)를 종료합니다.
+
클러스터 노드의 LIF는 이미 각 노드의 다른 클러스터 포트로 장애 조치되었어야 합니다.

+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *nv set interface swp15-16 link state down*
cumulus@nsw2:~$ *nv config apply*
----
. 클러스터 LIF에서 자동 되돌리기를 비활성화합니다.
+
`network interface modify -vserver Cluster -lif * -auto-revert false`

+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

Warning: Disabling the auto-revert feature of the cluster logical interface may effect the availability of your cluster network. Are you sure you want to continue? {y|n}: *y*
----
. 모든 클러스터 LIF에서 자동 되돌리기가 비활성화되었는지 확인하세요.
+
`network interface show -vserver Cluster -fields auto-revert`

. SN2100 스위치 sw1에서 ISL 포트 swp15와 swp16을 종료합니다.
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set interface swp15-16 link state down*
cumulus@sw1:~$ *nv config apply*
----
. SN2100 sw1 스위치에서 모든 케이블을 제거한 다음 SN2100 nsw2 스위치의 동일한 포트에 연결합니다.
. sw1과 nsw2 스위치 사이에 ISL 포트 swp15와 swp16을 연결합니다.
+
다음 명령은 스위치 sw1에서 ISL 포트 swp15 및 swp16을 활성화합니다.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv set interface swp15-16 link state down*
cumulus@sw1:~$ *nv config apply*
----
+
다음 예에서는 ISL 포트가 스위치 sw1에서 작동 중임을 보여줍니다.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface*

State  Name         Spd   MTU    Mode        LLDP           Summary
-----  -----------  ----  -----  ----------  -------------- ----------------------
...
...
UP     swp15        100G  9216   BondMember  nsw2 (swp15)   Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  nsw2 (swp16)   Master: cluster_isl(UP)
----
+
다음 예에서는 ISL 포트가 스위치 nsw2에서 작동 중임을 보여줍니다.

+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *nv show interface*

State  Name         Spd   MTU    Mode        LLDP           Summary
-----  -----------  ----  -----  ----------  -------------  -----------------------
...
...
UP     swp15        100G  9216   BondMember  sw1 (swp15)    Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)    Master: cluster_isl(UP)
----
. 포트를 확인하세요 `e3b` 모든 노드에 적용됩니다.
+
`network port show -ipspace Cluster`

+
출력은 다음과 유사해야 합니다.

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                         Ignore
                                                   Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ----- ------------ -------- -------
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false


Node: node2
                                                                         Ignore
                                                   Speed(Mbps) Health    Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status    Status
--------- ------------ ---------------- ---- ----- ----------- --------- -------
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false
----
. 각 노드의 클러스터 포트는 이제 노드 관점에서 다음과 같은 방식으로 클러스터 스위치에 연결됩니다.
+
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1  (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    nsw2 (b8:ce:f6:19:1b:b6)   swp3          -
node2      /lldp
            e3a    sw1  (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    nsw2 (b8:ce:f6:19:1b:b6)   swp4          -
----
. 모든 노드 클러스터 포트가 작동 중인지 확인하세요.
+
`nv show interface`

+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *nv show interface*

State  Name         Spd   MTU    Mode        LLDP              Summary
-----  -----------  ----  -----  ----------  ----------------- ----------------------
...
...
UP     swp3         100G  9216   Trunk/L2                      Master: bridge(UP)
UP     swp4         100G  9216   Trunk/L2                      Master: bridge(UP)
UP     swp15        100G  9216   BondMember  sw1 (swp15)       Master: cluster_isl(UP)
UP     swp16        100G  9216   BondMember  sw1 (swp16)       Master: cluster_isl(UP)
----
. 두 노드 모두 각 스위치에 하나의 연결이 있는지 확인하세요.
+
`nv show interface lldp`

+
다음 예는 두 스위치에 대한 적절한 결과를 보여줍니다.

+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3a
swp4       100G   Trunk/L2    node2              e3a
swp15      100G   BondMember  nsw2               swp15
swp16      100G   BondMember  nsw2               swp16


cumulus@nsw2:~$ *nv show interface lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1                e3b
swp4       100G   Trunk/L2    node2                e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
. 클러스터 LIF에서 자동 되돌리기를 활성화합니다.
+
`cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true`

. 스위치 nsw2에서 노드의 네트워크 포트에 연결된 포트를 불러옵니다.
+
[listing, subs="+quotes"]
----
cumulus@nsw2:~$ *nv set interface swp1-14 link state up*
cumulus@nsw2:~$ *nv config apply*
----
. 클러스터의 노드에 대한 정보를 표시합니다.
+
`cluster show`

+
이 예에서는 이 클러스터의 node1과 node2에 대한 노드 상태가 참임을 보여줍니다.

+
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node          Health  Eligibility
------------- ------- ------------
node1         true    true
node2         true    true
----
. 모든 물리적 클러스터 포트가 작동 중인지 확인하세요.
+
`network port show ipspace Cluster`

+
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node node1                                                               Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace     Broadcast Domain  Link  MTU   Admin/Oper  Status   Status
--------- ----------- ----------------- ----- ----- ----------- -------- ------
e3a       Cluster     Cluster           up    9000  auto/10000  healthy  false
e3b       Cluster     Cluster           up    9000  auto/10000  healthy  false

Node: node2
                                                                         Ignore
                                                    Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link  MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ----- ----- ----------- -------- ------
e3a       Cluster      Cluster          up    9000  auto/10000  healthy  false
e3b       Cluster      Cluster          up    9000  auto/10000  healthy  false
----


--
====


=== 3단계: 구성 확인

[role="tabbed-block"]
====
.큐물러스 리눅스 4.4.3
--
. 클러스터 네트워크가 정상인지 확인하세요.
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost      RemotePort
---------  -----  ----------  --------------  -----------
swp3       100G   Trunk/L2    node1           e3a
swp4       100G   Trunk/L2    node2           e3a
swp15      100G   BondMember  nsw2            swp15
swp16      100G   BondMember  nsw2            swp16
----


--
.큐물러스 리눅스 5.x
--
. 클러스터 네트워크가 정상인지 확인하세요.
+
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *nv show interface lldp*

LocalPort  Speed  Mode        RemoteHost      RemotePort
---------  -----  ----------  --------------  -----------
swp3       100G   Trunk/L2    node1           e3a
swp4       100G   Trunk/L2    node2           e3a
swp15      100G   BondMember  nsw2            swp15
swp16      100G   BondMember  nsw2            swp16
----


--
====
. [[step2]] 권한 수준을 다시 관리자로 변경합니다.
+
`set -privilege admin`

. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.다음은 무엇인가요?
스위치를 교체한 후에는 다음을 수행할 수 있습니다. link:../switch-cshm/config-overview.html["스위치 상태 모니터링 구성"].
