---
permalink: switch-nvidia-sn2100/sn2100-overview.html 
sidebar: sidebar 
keywords: nvidia SN2100 switches 
summary: 2개 이상의 노드로 ONTAP 클러스터를 구축하려면 두 개의 지원되는 클러스터 네트워크 스위치가 필요합니다. 선택 사항인 관리 스위치를 추가로 사용할 수 있습니다. 
---
= 개요 및 요구 사항: NVIDIA SN2100 스위치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVIDIA SN2100 스위치 설치 및 유지 보수의 경우 모든 요구 사항 및 권장 설명서를 검토하십시오.

2개 이상의 노드로 ONTAP 클러스터를 구축하려면 두 개의 지원되는 클러스터 네트워크 스위치가 필요합니다. 선택 사항인 관리 스위치를 추가로 사용할 수 있습니다.



== ONTAP 및 Linux 지원

NVIDIA SN2100 스위치는 Cumulus Linux를 실행하는 10Gb/25/40/100 Gb 이더넷 스위치입니다. 스위치는 다음을 지원합니다.

* ONTAP 9.10.1P3 SN2100 스위치는 ONTAP 9.10.1P3에서 서로 다른 스위치 쌍을 통해 클러스터 및 스토리지 애플리케이션을 제공합니다. ONTAP 9.10.1P3에서 NVIDIA SN2100 스위치를 사용하여 스토리지 및 클러스터 기능을 공유 스위치 구성으로 결합할 수 있습니다.
* Cumulus Linux(CL) OS 버전 4.4.3. 최신 호환성 정보는 를 참조하십시오 https://mysupport.netapp.com/site/info/nvidia-cluster-switch["NVIDIA 이더넷 스위치"^] 정보 페이지.
* Cumulus Linux 또는 ONIE를 실행 중인 스위치에서 Cumulus Linux를 설치할 수 있습니다.




== 캐비닛 및 레일 키트 세부 정보

NVIDIA SN2100 스위치(X190006/X190106)는 스위치에 포함된 표준 브래킷을 사용하여 NVIDIA 이중/단일 스위치 캐비닛에 설치합니다.

다음 표에는 MSN2100 스위치 및 레일 키트에 대한 부품 번호 및 설명이 나와 있습니다.

[cols="1,2"]
|===
| 부품 번호 | 설명 


 a| 
X190006-PE
 a| 
클러스터 스위치, NVIDIA SN2100, 16pt 100G, PTSX



 a| 
X190006-PI
 a| 
클러스터 스위치, NVIDIA SN2100, 16pt 100G, PSIN



 a| 
X190106-FE-PE
 a| 
스위치, NVIDIA SN2100, 16pt 100G, PTSX, 프론트 엔드



 a| 
X190106-FE-PI
 a| 
스위치, NVIDIA SN2100, 16pt 100G, PSIN, 프런트 엔드



 a| 
X-MTEF-KIT-D
 a| 
레일 키트, NVIDIA 이중 스위치



 a| 
X-MTEF-KIT-E
 a| 
레일 키트, NVIDIA 단일 스위치 깊이

|===

NOTE: 에 대한 자세한 내용은 NVIDIA 설명서를 참조하십시오 https://docs.nvidia.com/networking/display/sn2000pub/Installation["SN2100 스위치 및 레일 키트 설치"^].



== 사용 가능한 설명서

다음 표에는 NVIDIA SN2100 스위치에 사용할 수 있는 설명서가 나열되어 있습니다.

[cols="1,2"]
|===
| 제목 | 설명 


 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/install-hardware-sn2100-cluster.html["_NVIDIA SN2100 스위치를 설정하고 구성하십시오 _"^]
 a| 
에서는 Cumulus Linux 및 해당 RCFs 설치를 포함하여 NVIDIA SN2100 스위치를 설정하고 구성하는 방법을 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-cisco-sn2100-cluster-switch.html["_Cisco 클러스터 스위치에서 NVIDIA SN2100 클러스터 스위치로 마이그레이션 _"^]
 a| 
Cisco 클러스터 스위치를 사용하는 환경에서 NVIDIA SN2100 클러스터 스위치를 사용하는 환경으로 마이그레이션하는 방법을 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-cisco-storage-switch-sn2100-storage.html["_Cisco 스토리지 스위치에서 NVIDIA 스토리지 스위치로 마이그레이션 _"^]
 a| 
Cisco 스토리지 스위치를 사용하는 환경에서 NVIDIA SN2100 스토리지 스위치를 사용하는 환경으로 마이그레이션하는 방법을 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html["_NVIDIA SN2100 클러스터 스위치를 사용하여 2노드 스위치 클러스터로 마이그레이션 _"^]
 a| 
에서는 NVIDIA SN2100 클러스터 스위치를 사용하여 2노드 스위치 환경으로 마이그레이션하는 방법을 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/replace-sn2100-switch-cluster.html["_NVIDIA SN2100 클러스터 스위치 _ 을(를) 교체합니다"^]
 a| 
에서는 클러스터의 결함 있는 NVIDIA SN2100 스위치를 교체하고 Cumulus Linux 및 참조 구성 파일을 다운로드하는 절차를 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/replace-sn2100-switch-storage.html["_NVIDIA SN2100 스토리지 스위치 _ 를 교체합니다"^]
 a| 
결함 있는 NVIDIA SN2100 스토리지 스위치를 교체하고 Cumulus Linux 및 참조 구성 파일을 다운로드하는 절차를 설명합니다.

|===