---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-storage/configure-reqs-9336c-storage.html 
keywords: shared storage cluster switch 
summary: ONTAP 9.9.1부터 Cisco Nexus 9336C-FX2 스위치를 사용하여 스토리지와 클러스터 기능을 공유 스위치 시나리오로 결합할 수 있습니다. 
---
= Cisco Nexus 9336C-FX2 및 9336C-FX2-T 스토리지 스위치에 대한 구성 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9336C-FX2 및 9336C-FX2-T 스위치 설치 및 유지관리를 위해서는 구성 및 네트워크 요구 사항을 검토하세요.



== ONTAP 지원

[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
ONTAP 9.9.1부터 Cisco Nexus 9336C-FX2 스위치를 사용하여 스토리지와 클러스터 기능을 공유 스위치 구성으로 결합할 수 있습니다.

두 개 이상의 노드가 있는 ONTAP 클러스터를 구축하려면 지원되는 네트워크 스위치가 두 개 필요합니다.


NOTE: 이더넷 스위치 상태 모니터는 ONTAP 9.13.1P8 및 이전 버전, 9.14.1P3 및 이전 버전 또는 NX-OS 버전 10.3(4a)(M)을 지원하지 않습니다.

--
.ONTAP 9.10.1 이상
--
또한 ONTAP 9.10.1부터 Cisco Nexus 9336C-FX2-T 스위치를 사용하여 스토리지와 클러스터 기능을 공유 스위치 구성으로 결합할 수 있습니다.

두 개 이상의 노드가 있는 ONTAP 클러스터를 구축하려면 지원되는 네트워크 스위치가 두 개 필요합니다.

--
====


== 구성 요구 사항

구성을 위해서는 스위치에 맞는 적절한 수와 유형의 케이블과 케이블 커넥터가 필요합니다.

처음 구성하는 스위치 유형에 따라 포함된 콘솔 케이블을 사용하여 스위치 콘솔 포트에 연결해야 합니다. 또한 특정 네트워크 정보도 제공해야 합니다.



== 네트워크 요구 사항

모든 스위치 구성에는 다음 네트워크 정보가 필요합니다.

* 관리 네트워크 트래픽을 위한 IP 서브넷
* 각 스토리지 시스템 컨트롤러와 모든 해당 스위치에 대한 호스트 이름 및 IP 주소
* 대부분의 스토리지 시스템 컨트롤러는 이더넷 서비스 포트(렌치 아이콘)에 연결하여 e0M 인터페이스를 통해 관리됩니다. AFF A800 및 AFF A700s 시스템에서 e0M 인터페이스는 전용 이더넷 포트를 사용합니다.
* 를 참조하세요 https://hwu.netapp.com["Hardware Universe"] 최신 정보를 확인하세요.


스위치의 초기 구성에 대한 자세한 내용은 다음 가이드를 참조하세요. https://www.cisco.com/c/en/us/td/docs/dcn/hw/nx-os/nexus9000/9336c-fx2-e/cisco-nexus-9336c-fx2-e-nx-os-mode-switch-hardware-installation-guide.html["Cisco Nexus 9336C-FX2 설치 및 업그레이드 가이드"] .

.다음은 무엇입니까?
구성 요구 사항을 검토한 후 다음을 확인할 수 있습니다. link:components-9336c-storage.html["구성 요소 및 부품 번호"].
