---
permalink: switch-cisco-9336c-fx2-storage/install-nxos-overview-9336c-storage.html 
sidebar: sidebar 
keywords: cisco, nx-os, software, reference, configuration, file, rcf, install, fx2, cluster, switch, install nx-os software and rcfs on cisco nexus 9336-fx2 cluster switches - cisco nexus 9336x-fx2 
summary: 'Cisco NX-OS 소프트웨어와 참조 구성 파일(RCF)은 Cisco Nexus 9336C-FX2 클러스터 스위치에 설치되어야 합니다.' 
---
= NX-OS 소프트웨어 및 RCF 설치 또는 업그레이드 준비
:allow-uri-read: 


[role="lead"]
NX-OS 소프트웨어와 참조 구성 파일(RCF)을 설치하기 전에 다음 절차를 따르세요.

.예시에 관하여
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 두 Cisco 스위치의 이름은 s1과 s2입니다.
* 노드 이름은 cluster1-01과 cluster1-02입니다.


.이 작업에 관하여
이 절차에서는 ONTAP 명령과 Cisco Nexus 9000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 지정되지 않는 한 ONTAP 명령을 사용합니다.

.단계
. AutoSupport가 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제하십시오. `system node autosupport invoke -node * -type all -message MAINT=xh`
+
여기서 x는 유지 관리 기간(시간)입니다.

+

NOTE: AutoSupport 메시지는 기술 지원팀에 이 유지 관리 작업을 알려 유지 관리 기간 동안 자동 케이스 생성이 억제되도록 합니다.

. 계속할지 묻는 메시지가 나타나면 *y*를 입력하여 권한 수준을 고급으로 변경합니다.
+
[source, cli]
----
set -privilege advanced
----
+
고급 프롬프트(`*>` )이 나타납니다.

. 각 스위치의 각 노드에 구성된 인터페이스 수를 표시합니다.
+
[source, cli]
----
network device-discovery show -protocol lldp
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/lldp
            e5a    s1                        Eth1/2            N9K-C9336C
            e3b    s2                        Eth1/2            N9K-C9336C
cluster1-01/lldp
            e5a    s1                        Eth1/1            N9K-C9336C
            e3b    s2                        Eth1/1            N9K-C9336C
.
.
----
====
. 각 노드 스토리지 포트 및 스토리지 쉘프 포트의 관리 또는 운영 상태를 확인하십시오.
+
.. 노드 스토리지 포트 속성을 표시합니다.
+
[source, cli]
----
storage port show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show*
Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -
cluster1-02

               e5a  ENET  storage    100 enabled  online      -
               e3b  ENET  storage    100 enabled  online      -

.
.
----
====
.. 스토리지 셸프 포트 속성을 표시합니다.
+
[source, cli]
----
storage shelf port show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. 스위치가 모니터링되도록 스위치에 대해 스위치 상태 모니터링(CSHM)이 활성화되어 있는지 확인하십시오.
+
[source, cli]
----
system switch ethernet show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.2.3.4          N9K-C9336C-FX2
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    2.3.4.5          N9K-C9336C-FX2
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====




.다음은 무엇인가요?
NX-OS 소프트웨어와 RCF를 설치할 준비가 되면 다음을 수행할 수 있습니다. link:install-nxos-software-9336c-storage.html["NX-OS 소프트웨어를 설치하거나 업그레이드하세요"].
