---
permalink: switch-cisco-9336c-fx2-storage/install-upgrade-rcf-overview-9336c-storage.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9336c-fx2 
summary: Nexus 9336C-FX2 스위치를 처음 설정한 후 RCF를 설치할 수 있습니다. 이 절차를 사용하여 RCF 버전을 업그레이드할 수도 있습니다. 
---
= RCF(Reference Configuration File) 개요를 설치 또는 업그레이드합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nexus 9336C-FX2 스토리지 스위치를 처음 설정한 후 참조 구성 파일(RCF)을 설치합니다. 스위치에 기존 RCF 파일 버전이 설치되어 있는 경우 RCF 버전을 업그레이드합니다.

RCF를 설치하거나 업그레이드할 때 자세한 내용은 기술 자료 문서를 link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["원격 연결을 유지하면서 Cisco 상호 연결 스위치의 구성을 지우는 방법"^]참조하십시오.

.사용 가능한 RCF 구성
다음 표에서는 다양한 구성에 사용할 수 있는 RCF에 대해 설명합니다. 구성에 적용할 RCF를 선택합니다.

특정 포트 및 VLAN 사용에 대한 자세한 내용은 RCF의 배너 및 중요 참고 사항 섹션을 참조하십시오.

[cols="1,2"]
|===
| RCF 이름입니다 | 설명 


 a| 
2-클러스터-HA-브레이크아웃
 a| 
공유 클러스터 + HA 포트를 사용하는 노드를 포함하여 8개 이상의 노드로 구성된 ONTAP 클러스터 2개를 지원합니다.



 a| 
4-클러스터-HA-브레이크아웃
 a| 
공유 클러스터 + HA 포트를 사용하는 노드를 포함하여 4개 이상의 노드로 구성된 ONTAP 클러스터 4개를 지원합니다.



 a| 
1-클러스터-HA
 a| 
모든 포트는 40/100GbE용으로 구성됩니다. 포트에서 공유 클러스터/HA 트래픽을 지원합니다. AFF A320, AFF A250 및 FAS500f 시스템에 필요 또한 모든 포트를 전용 클러스터 포트로 사용할 수 있습니다.



 a| 
1-클러스터-HA-브레이크아웃
 a| 
포트는 4x10GbE 브레이크아웃, 4x25GbE 브레이크아웃(100GbE 스위치의 RCF 1.6 이상) 및 40/100GbE용으로 구성됩니다. 공유 클러스터/HA 포트를 사용하는 AFF A320, AFF A250 및 FAS500f 시스템과 같은 노드를 위해 포트에서 공유 클러스터/HA 트래픽을 지원합니다. 또한 모든 포트를 전용 클러스터 포트로 사용할 수 있습니다.



 a| 
Cluster-HA-스토리지
 a| 
포트는 클러스터+HA의 경우 40/100GbE, 클러스터의 경우 4x10GbE 브레이크아웃, 클러스터+HA의 경우 4x25GbE 브레이크아웃, 각 스토리지 HA 쌍의 경우 100GbE로 구성됩니다.



 a| 
클러스터
 a| 
4x10GbE 포트(브레이크아웃)와 40/100GbE 포트를 다르게 할당한 두 가지 RCF 유형입니다.  AFF A320, AFF A250, FAS500f 시스템을 제외한 모든 FAS 및 AFF 노드가 지원됩니다.



 a| 
스토리지
 a| 
모든 포트는 100GbE NVMe 스토리지 연결용으로 구성됩니다.

|===
.추천 문서
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^]
+
NetApp Support 사이트에서 지원되는 ONTAP 및 RCF 버전은 스위치 호환성 표를 참조하십시오. RCF의 명령 구문과 특정 버전의 NX-OS에 있는 구문 사이에 명령 종속성이 있을 수 있습니다.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 시리즈 스위치"^]
+
Cisco 스위치 업그레이드 및 다운그레이드 절차에 대한 자세한 내용은 Cisco 웹 사이트에 있는 해당 소프트웨어 및 업그레이드 가이드를 참조하십시오.



.예를 참조하십시오
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 두 Cisco 스위치의 이름은 CS1과 CS2입니다.
* 노드 이름은 node1-01, node1-02, node1-03, node1-04입니다.
* 클러스터 LIF 이름은 node1-01_clus1, node1-01_clus2, node1-02_clus1, node1-02_clus2, node1-03_clus1, node1-03_clus2, node1-04_clus1 및 node1-04_clus2입니다.
* 'cluster1:: *>' 프롬프트는 클러스터의 이름을 나타냅니다.


를 참조하십시오 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] 플랫폼에서 올바른 포트를 확인하세요.


NOTE: 명령 출력은 ONTAP의 릴리즈별로 다를 수 있습니다.

.사용된 명령
이 절차를 수행하려면 ONTAP 명령과 Cisco Nexus 9000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 표시되지 않는 한 ONTAP 명령이 사용됩니다.

.다음 단계
RCF 설치 또는 RCF 업그레이드 절차를 검토한 후 다음을 수행할 수 있습니다.link:install-rcf-software-9336c-storage.html["RCF를 설치하다"] 또는link:upgrade-rcf-software-9336c-storage.html["RCF를 업그레이드하세요"] 필요에 따라.
