---
permalink: switch-cisco-9336c-fx2-storage/install-upgrade-rcf-overview-9336c-storage.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9336c-fx2 
summary: Nexus 9336C-FX2 스위치를 처음 설정한 후 RCF를 설치할 수 있습니다. 이 절차를 사용하여 RCF 버전을 업그레이드할 수도 있습니다. 
---
= 참조 구성 파일(RCF) 개요 설치 또는 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nexus 9336C-FX2 스토리지 스위치를 처음 설정한 후 참조 구성 파일(RCF)을 설치합니다. 스위치에 기존 RCF 파일 버전이 설치되어 있는 경우 RCF 버전을 업그레이드합니다.

지식 기반 문서를 참조하세요link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["원격 연결을 유지하면서 Cisco 상호 연결 스위치의 구성을 지우는 방법"^] RCF를 설치하거나 업그레이드할 때 자세한 내용을 알아보세요.

.사용 가능한 RCF 구성
다음 표에서는 다양한 구성에 사용할 수 있는 RCF를 설명합니다. 귀하의 구성에 적용 가능한 RCF를 선택하세요. 보다link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^] 자세한 내용은.

특정 포트 및 VLAN 사용에 대한 자세한 내용은 RCF의 배너 및 중요 참고 사항 섹션을 참조하세요.

[cols="1,2"]
|===
| RCF 이름 | 설명 


 a| 
2-클러스터-HA-브레이크아웃
 a| 
공유 클러스터+HA 포트를 사용하는 노드를 포함하여 최소 8개의 노드가 있는 두 개의 ONTAP 클러스터를 지원합니다.



 a| 
4-클러스터-HA-브레이크아웃
 a| 
공유 클러스터+HA 포트를 사용하는 노드를 포함하여 최소 4개의 노드가 있는 4개의 ONTAP 클러스터를 지원합니다.



 a| 
1-클러스터-HA
 a| 
모든 포트는 40/100GbE로 구성되어 있습니다.  포트에서 공유 클러스터/HA 트래픽을 지원합니다.  AFF A320, AFF A250 및 FAS500f 시스템에 필요합니다.  또한 모든 포트는 전용 클러스터 포트로 사용될 수 있습니다.



 a| 
1-클러스터-HA-브레이크아웃
 a| 
포트는 4x10GbE 브레이크아웃, 4x25GbE 브레이크아웃(100GbE 스위치의 RCF 1.6+), 40/100GbE에 맞게 구성됩니다.  공유 클러스터/HA 포트를 사용하는 노드의 포트에서 공유 클러스터/HA 트래픽을 지원합니다: AFF A320, AFF A250 및 FAS500f 시스템.  또한 모든 포트는 전용 클러스터 포트로 사용될 수 있습니다.



 a| 
클러스터-HA-스토리지
 a| 
포트는 클러스터+HA의 경우 40/100GbE, 클러스터의 경우 4x10GbE 브레이크아웃, 클러스터+HA의 경우 4x25GbE 브레이크아웃, 각 스토리지 HA 쌍의 경우 100GbE로 구성됩니다.



 a| 
무리
 a| 
4x10GbE 포트(브레이크아웃)와 40/100GbE 포트를 다르게 할당한 두 가지 RCF 유형입니다. AFF A320, AFF A250, FAS500f 시스템을 제외한 모든 FAS 및 AFF 노드가 지원됩니다.



 a| 
스토리지
 a| 
모든 포트는 100GbE NVMe 스토리지 연결에 맞게 구성되어 있습니다.

|===
.사용 가능한 RCF
다음 표에는 9336C-FX2 및 9336C-FX2-T 스위치에 사용 가능한 RCF가 나열되어 있습니다.  구성에 맞는 RCF 버전을 선택하세요. 보다link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^] 자세한 내용은.

[cols="1"]
|===
| RCF 이름 


 a| 
클러스터-HA-브레이크아웃 RCF 1._xx_



 a| 
클러스터-HA-스토리지 RCF 1._xx_



 a| 
저장 RCF 1._xx_



 a| 
멀티클러스터-HA RCF 1._xx_

|===
.제안된 문서
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^]
+
NetApp 지원 사이트에서 지원되는 ONTAP 및 RCF 버전에 대한 스위치 호환성 표를 참조하세요.  RCF의 명령 구문과 특정 NX-OS 버전의 구문 사이에는 명령 종속성이 있을 수 있습니다.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 시리즈 스위치"^]
+
Cisco 스위치 업그레이드 및 다운그레이드 절차에 대한 전체 문서는 Cisco 웹사이트에서 제공하는 해당 소프트웨어 및 업그레이드 가이드를 참조하세요.



.예시에 관하여
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 두 Cisco 스위치의 이름은 cs1과 cs2입니다.
* 노드 이름은 node1-01, node1-02, node1-03, node1-04입니다.
* 클러스터 LIF 이름은 node1-01_clus1, node1-01_clus2, node1-02_clus1, node1-02_clus2, node1-03_clus1, node1-03_clus2, node1-04_clus1 및 node1-04_clus2입니다.
* 그만큼 `cluster1::*>` 프롬프트는 클러스터의 이름을 나타냅니다.


를 참조하십시오 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] 플랫폼에서 올바른 포트를 확인하세요.


NOTE: 명령 출력은 ONTAP 릴리스에 따라 달라질 수 있습니다.

.사용된 명령어
이 절차에서는 ONTAP 명령과 Cisco Nexus 9000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 지정되지 않는 한 ONTAP 명령을 사용합니다.

.다음은 무엇인가요?
RCF 설치 또는 RCF 업그레이드 절차를 검토한 후 다음을 수행할 수 있습니다.link:install-rcf-software-9336c-storage.html["RCF를 설치하다"] 또는link:upgrade-rcf-software-9336c-storage.html["RCF를 업그레이드하세요"] 필요에 따라.
