---
permalink: switch-cisco-9336c-fx2-storage/install-9336c-storage.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: 아직 필요한 구성 정보와 문서가 없다면 클러스터와 관리 네트워크 스위치를 설정하기 전에 해당 정보를 수집해야 합니다. 
---
= 9336C-FX2 및 9336C-FX2-T 스토리지 스위치 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9336C-FX2 및 9336C-FX2-T 스토리지 스위치를 설치하려면 다음 절차를 따르세요.

.시작하기 전에
다음 사항이 있는지 확인하세요.

* 설치 사이트의 HTTP, FTP 또는 TFTP 서버에 액세스하여 해당 NX-OS 및 참조 구성 파일(RCF) 릴리스를 다운로드합니다.
* 적용 가능한 NX-OS 버전은 다음에서 다운로드합니다. https://software.cisco.com/download/home["Cisco 소프트웨어 다운로드"^] 페이지.
* 적용 가능한 라이센스, 네트워크 및 구성 정보, 케이블.
* 완전한link:setup-worksheet-9336c-storage.html["케이블링 워크시트"] .
* NetApp 지원 사이트에서 다운로드한 적용 가능한 NetApp 클러스터 네트워크 및 관리 네트워크 RCF http://mysupport.netapp.com/["mysupport.netapp.com"^] .  모든 Cisco 클러스터 네트워크와 관리 네트워크 스위치는 표준 Cisco 공장 기본 구성으로 제공됩니다. 이러한 스위치에도 최신 버전의 NX-OS 소프트웨어가 있지만 RCF가 로드되어 있지 않습니다.
* 필수 스위치 문서. 보다link:required-documentation-9336c-storage.html["필수 서류"] 자세한 내용은.


.단계
. 클러스터 네트워크와 관리 네트워크 스위치 및 컨트롤러를 랙에 설치합니다.
+
[cols="1,2"]
|===
| ...을 설치하는 경우 | 그 다음에... 


 a| 
NetApp 시스템 캐비닛의 Cisco Nexus 9336C-FX2
 a| 
보다link:install-switch-and-passthrough-panel-9336c-storage.html["NetApp 캐비닛에 스위치 설치"] NetApp 캐비닛에 스위치를 설치하는 방법에 대한 지침입니다.



 a| 
통신사 랙의 장비
 a| 
스위치 하드웨어 설치 가이드와 NetApp 설치 및 설정 지침에 제공된 절차를 참조하세요.

|===
. 완성된 케이블링 워크시트를 사용하여 클러스터 네트워크와 관리 네트워크 스위치를 컨트롤러에 케이블로 연결합니다.
. 클러스터 네트워크와 관리 네트워크 스위치 및 컨트롤러의 전원을 켭니다.


.다음은 무엇인가요?
선택적으로 다음을 수행할 수 있습니다. link:install-switch-and-passthrough-panel-9336c-storage.html["NetApp 캐비닛에 Cisco Nexus 9336C-FX2 스위치 설치"]. 그렇지 않으면 다음으로 이동하세요. link:setup-switch-9336c-storage.html["스위치 구성"].
