---
permalink: switch-cisco-9336c-fx2-storage/replace-storage-switch-9336c-storage.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9336c-fx2 cluster switch - cisco nexus 9336c-fx2 
summary: '클러스터 네트워크에서 결함이 있는 Nexus 9336C-FX2 스위치를 교체하는 것은 중단 없는 절차(NDU)입니다.' 
---
= Cisco Nexus 9336C-FX2 및 9336C-FX2-T 스토리지 스위치 교체
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 네트워크에서 결함이 있는 Nexus 9336C-FX2 및 9336C-FX2-T 스위치를 교체할 수 있습니다. 이것은 방해가 되지 않는 절차입니다.

.시작하기 전에
Cisco Nexus 9336C-FX2 및 9336C-FX2-T 스토리지 스위치에 NX-OS 소프트웨어와 RCF를 설치하기 전에 다음 사항을 확인하세요.

* 귀하의 시스템은 Cisco Nexus 9336C-FX2 및 9336C-FX2-T 스토리지 스위치를 지원할 수 있습니다.
* 지원되는 ONTAP , NX-OS 및 RCF 버전에 대한 Cisco 이더넷 스위치 페이지의 스위치 호환성 표를 참조했습니다.
* Cisco 웹 사이트에서 제공되는 적절한 소프트웨어 및 업그레이드 가이드를 참조했습니다.
* 해당 RCF를 다운로드했습니다.
* 기존 네트워크 구성은 다음과 같은 특징을 가지고 있습니다.
+
** Cisco 이더넷 스위치 페이지에는 스위치에 설치된 최신 RCF 및 NX-OS 버전이 있습니다.
** 두 스위치 모두에 관리 연결이 있어야 합니다.


* 교체용 Cisco Nexus 9336C-FX2 스위치는 다음과 같은 특징을 가지고 있습니다.
+
** 관리 네트워크 연결이 작동합니다.
** 교체 스위치에 대한 콘솔 접근이 가능합니다.
** 적절한 RCF 및 NX-OS 운영 체제 이미지가 스위치에 로드됩니다.
** 스위치의 초기 구성이 완료되었습니다.




.이 작업에 관하여
이 절차는 두 번째 Nexus 9336C-FX2 스토리지 스위치 s2를 새 9336C-FX 스위치 ns2로 교체합니다. 두 노드는 cluster1-01과 cluster1-02입니다.

완료 단계:

* 교체할 스위치가 s2인지 확인하십시오.
* 스위치 s2에서 케이블을 분리하십시오.
* ns2 스위치에 케이블을 다시 연결합니다.
* 스위치 ns2의 모든 디바이스 구성을 확인하십시오.
+

NOTE: RCF 버전과 NX-OS 버전의 명령 구문 사이에 종속성이 있을 수 있습니다.



.단계
. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
_x_는 유지 관리 기간(시간)입니다.

. 스토리지 노드 포트의 상태를 확인하여 스토리지 스위치 s1에 연결되어 있는지 확인하십시오.
+
`storage port show -port-type ENET`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                  Speed                     VLAN
Node           Port Type  Mode    (Gb/s) State    Status      ID
-------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
cluster1-02
               e5a  ENET  storage 100    enabled  online      30
               e3b  ENET  storage   0    enabled  offline     30
.
.
----
====
. 스토리지 스위치 s1을 사용할 수 있는지 확인합니다.
+
`network device-discovery show`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/      Local Discovered
Protocol   Port	 Device (LLDP: ChassisID)  Interface  Platform
--------   ----  -----------------------   ---------   ---------
cluster1-01/cdp
           e5a   s1                        Ethernet1/1 NX9336C
           e4a   cluster1-02               e4a         AFF-A700
           e4e   cluster1-02               e4e         AFF-A700
cluster1-01/lldp
           e5a   s1                        Ethernet1/1 -
           e4a   cluster1-02               e4a         -
           e4e   cluster1-02               e4e         -
cluster1-02/cdp
           e3b   s1                        Ethernet1/2 NX9336C
           e4a   cluster1-01               e4a         AFF-A700
           e4e   cluster1-01               e4e         AFF-A700
cluster1-02/lldp
           e3b   s1                        Ethernet1/2 -
           e4a   cluster1-01               e4a         -
           e4e   cluster1-01               e4e         -
.
.
----
====
. 쇼를 진행하다 `lldp neighbors` 작동 스위치에서 명령을 실행하여 두 노드와 모든 선반을 볼 수 있는지 확인하세요.
+
`show lldp neighbors`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
S1# show lldp neighbors
Capability codes:
   (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
   (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID        Local Intf   Hold-time    Capability    Port ID
cluster1-01      Eth1/1       121          S             e5a
cluster1-02      Eth1/2       121          S             e5a
SHFGD2008000011  Eth1/5       121          S             e0a
SHFGD2008000011  Eth1/6       120          S             e0a
SHFGD2008000022  Eth1/7       120          S             e0a
SHFGD2008000022  Eth1/8       120          S             e0a
----
====
. 스토리지 시스템의 스토리지 쉘프 포트를 확인합니다.
+
`storage shelf port show -fields remote-device,remote-port`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id  remote-port   remote-device
-----   --  -----------   -------------
3.20    0   Ethernet1/5   s1
3.20    1   -             -
3.20    2   Ethernet1/6   s1
3.20    3   -             -
3.30    0   Ethernet1/7   s1
3.20    1   -             -
3.30    2   Ethernet1/8   s1
3.20    3   -             -
.
.
----
====
. 스토리지 스위치 s2에 연결된 모든 케이블을 제거하십시오.
. 교체용 스위치 ns2에 모든 케이블을 다시 연결하십시오.
. 스토리지 노드 포트의 상태를 다시 확인하세요.
+
`storage port show -port-type ENET`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
storage::*> storage port show -port-type ENET
                                    Speed                     VLAN
Node             Port Type  Mode    (Gb/s) State    Status      ID
---------------- ---- ----- ------- ------ -------- --------- ----
cluster1-01
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
cluster1-02
                 e5a  ENET  storage 100    enabled  online      30
                 e3b  ENET  storage   0    enabled  offline     30
                 e7a  ENET  storage   0    enabled  offline     30
                 e7b  ENET  storage   0    enabled  offline     30
.
.
----
====
. 두 스위치가 모두 사용 가능한지 확인하세요.
+
`network device-discovery show`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
storage::*> network device-discovery show
Node/     Local Discovered
Protocol  Port  Device (LLDP: ChassisID)  Interface	  Platform
--------  ----  -----------------------   ---------   ---------
cluster1-01/cdp
          e3a  s1                         Ethernet1/1 NX9336C
          e4a  cluster1-02                e4a         AFF-A700
          e4e  cluster1-02                e4e         AFF-A700
          e7b  ns2                       Ethernet1/1 NX9336C
cluster1-01/lldp
          e3a  s1                         Ethernet1/1 -
          e4a  cluster1-02                e4a         -
          e4e  cluster1-02                e4e         -
          e7b  ns2                        Ethernet1/1 -
cluster1-02/cdp
          e3a  s1                         Ethernet1/2 NX9336C
          e4a  cluster1-01                e4a         AFF-A700
          e4e  cluster1-01                e4e         AFF-A700
          e7b  ns2                        Ethernet1/2 NX9336C
cluster1-02/lldp
          e3a  s1                         Ethernet1/2 -
          e4a  cluster1-01                e4a         -
          e4e  cluster1-01                e4e         -
          e7b  ns2                        Ethernet1/2 -
.
.
----
====
. 스토리지 시스템의 선반 포트를 확인하세요.
+
`storage shelf port show -fields remote-device,remote-port`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
storage::*> storage shelf port show -fields remote-device,remote-port
shelf   id    remote-port     remote-device
-----   --    -----------     -------------
3.20    0     Ethernet1/5     s1
3.20    1     Ethernet1/5     ns2
3.20    2     Ethernet1/6     s1
3.20    3     Ethernet1/6     ns2
3.30    0     Ethernet1/7     s1
3.20    1     Ethernet1/7     ns2
3.30    2     Ethernet1/8     s1
3.20    3     Ethernet1/8     ns2
storage::*>
----
====
. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.다음은 무엇인가요?
스위치를 교체한 후에는 다음을 수행할 수 있습니다. link:../switch-cshm/config-overview.html["스위치 상태 모니터링 구성"].
