---
permalink: switch-cisco-9336c-fx2-storage/upgrade-rcf-software-9336c-storage.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: 이 절차를 사용하여 RCF 버전을 업그레이드할 수 있습니다. 
---
= 참조 구성 파일(RCF) 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
운영 스위치에 기존 RCF 파일 버전이 설치되어 있는 경우 RCF 버전을 업그레이드합니다.

.시작하기 전에
다음 사항이 있는지 확인하세요.

* 스위치 구성의 현재 백업입니다.
* 완벽하게 작동하는 클러스터(로그에 오류나 유사한 문제가 없음).
* 현재의 RCF.
* RCF 버전을 업데이트하는 경우 원하는 부트 이미지를 반영하는 RCF의 부트 구성이 필요합니다.
+
현재 부트 이미지를 반영하도록 부트 구성을 변경해야 하는 경우 RCF를 다시 적용하기 전에 변경해야 합니다. 이렇게 하면 향후 재부팅 시 올바른 버전이 인스턴스화됩니다.




CAUTION: 새로운 스위치 소프트웨어 버전과 RCF를 설치하기 전에 스위치 설정을 지우고 기본 구성을 수행해야 합니다.  스위치 설정을 지우려면 직렬 콘솔을 사용하여 스위치에 연결해야 하거나 기본 구성 정보를 보존해야 합니다.



== 1단계: 업그레이드 준비

. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
여기서 _x_는 유지 관리 기간(시간)입니다.

. 계속할지 묻는 메시지가 나타나면 *y*를 입력하여 권한 수준을 고급으로 변경합니다.
+
`set -privilege advanced`

+
고급 프롬프트(*>)가 나타납니다.

. 스위치에 연결된 각 노드의 포트를 표시합니다.
+
[source, cli]
----
network device-discovery show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID) Interface       Platform
----------- ------ ------------------------ --------------- ---------
cluster1-01/cdp
            e5a    s1                       Ethernet1/7     N9K-C9336C
            e3b    s2                       Ethernet1/7     N9K-C9336C
cluster1-02/cdp
            e5a    s1                       Ethernet1/8     N9K-C9336C
            e3b    s2                       Ethernet1/8     N9K-C9336C
.
.
.
----
====
. 각 노드 스토리지 포트 및 스토리지 쉘프 포트의 관리 또는 운영 상태를 확인하십시오.
+
.. 모든 노드 스토리지 포트가 정상 상태로 작동 중인지 확인하십시오.
+
[source, cli]
----
storage port show -port-type ENET
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e5a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
cluster1-02
                   e5a ENET  -         100   enabled  online
                   e3b ENET  -         100   enabled  online
.
.
----
====
.. 모든 저장 선반 포트가 정상 상태로 작동하는지 확인하세요.
+
[source, cli]
----
storage shelf port show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. 스위치가 모니터링되고 있는지 확인합니다.
+
[source, cli]
----
system switch ethernet show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show*
  Switch            Type               Address          Model
  ----------------- ------------------ ---------------- ---------------
  s1                storage-network    1.2.3.4          N9K-C9336C-FX2
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2                storage-network    2.3.4.5          N9K-C9336C-FX2
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====






== 2단계: RCF 업그레이드

. SSH 또는 시리얼 콘솔을 사용하여 스위치 s2에 로그인하십시오.
. 노드의 모든 포트에 연결된 포트를 종료합니다.
+
[listing, subs="+quotes"]
----
s2> *enable*
s2# *configure*
s2(config)# *interface e1/1-36*
s2(config-if-range)# *shutdown*
s2(config-if-range)# *exit*
s2(config)# *exit*
----
+

CAUTION: 네트워크 연결 문제를 방지하려면 연결된 *모든* 포트를 종료해야 합니다. 자세한 내용은 기술 자료 문서 link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["스위치 OS 업그레이드 중 클러스터 LIF를 마이그레이션할 때 노드가 쿼럼을 벗어났습니다."^]를 참조하십시오.

. 아직 저장하지 않았다면 다음 명령의 출력을 텍스트 파일에 복사하여 현재 스위치 구성의 사본을 저장하세요.
+
`show running-config`

+
.. 현재 사이의 사용자 정의 추가 사항을 기록합니다. `running-config` 그리고 사용 중인 RCF 파일(예: 조직의 SNMP 구성)
.. NX-OS 10.2 이상의 경우 다음을 사용하세요. `show diff running-config` 부트플래시에 저장된 RCF 파일과 비교하는 명령입니다. 그렇지 않은 경우 타사의 diff 또는 비교 도구를 사용하세요.


. 기본 구성 세부 정보를 저장합니다. `write_erase.cfg` 부트플래시에 있는 파일입니다.
+
[NOTE]
====
다음 사항을 구성해야 합니다.

** 사용자 이름과 비밀번호
** 관리 IP 주소
** 기본 게이트웨이
** 스위치 이름


====
+
`s2# show run | i "username admin password" > bootflash:write_erase.cfg`

+
`s2# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`s2# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
`s2# show run | section "switchname" >> bootflash:write_erase.cfg`

+
자세한 내용은 기술 자료 문서 link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["원격 연결을 유지하면서 Cisco 상호 연결 스위치의 구성을 지우는 방법"^]를 참조하십시오.

. 다음을 확인하십시오. `write_erase.cfg` 예상대로 파일이 채워졌습니다.
+
`*show file bootflash:write_erase.cfg*`

. 발행하다 `write erase` 현재 저장된 구성을 지우는 명령:
+
`s2# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. 이전에 저장된 기본 구성을 시작 구성에 복사합니다.
+
`s2# *copy bootflash:write_erase.cfg startup-config*`

. 스위치를 재부팅하세요:
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 관리 IP 주소에 다시 접근할 수 있게 되면 SSH를 통해 스위치에 로그인합니다.
+
SSH 키와 관련된 호스트 파일 항목을 업데이트해야 할 수도 있습니다.

. FTP, TFTP, SFTP 또는 SCP 중 하나의 전송 프로토콜을 사용하여 RCF를 스위치 s2의 bootflash에 복사하십시오.
+
Cisco 명령에 대한 자세한 내용은 link:https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 시리즈 NX-OS 명령 참조"^]의 해당 가이드를 참조하십시오.

+
.예를 보여주세요
[%collapsible]
====
이 예에서는 TFTP를 사용하여 스위치 s2의 bootflash에 RCF를 복사하는 방법을 보여줍니다.

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX9336C-FX2-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 이전에 다운로드한 RCF를 부트플래시에 적용합니다.
+
Cisco 명령에 대한 자세한 내용은 link:https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 시리즈 NX-OS 명령 참조"^]의 해당 가이드를 참조하십시오.

+
이 예시는 스위치 s2에 RCF 파일 `NX9336C-FX2-RCF-v1.13-1-Storage.txt`이 설치되는 과정을 보여줍니다.

+
[listing, subs="+quotes"]
----
s2# *copy NX9336C-FX2-RCF-v1.13-1-Storage.txt running-config echo-commands*
----
+
[CAUTION]
====
RCF의 *설치 참고 사항*, *중요 참고 사항* 및 *배너* 섹션을 자세히 읽으세요. 스위치의 올바른 구성과 작동을 보장하려면 이 지침을 읽고 따라야 합니다.

====
. RCF 파일이 올바른 최신 버전인지 확인하세요.
+
`show running-config`

+
올바른 RCF가 있는지 확인하기 위해 출력을 확인할 때 다음 정보가 올바른지 확인하세요.

+
** RCF 배너
** 노드 및 포트 설정
** 사용자 정의
+
출력은 사이트 구성에 따라 달라집니다.  포트 설정을 확인하고 설치한 RCF에 대한 특정 변경 사항이 있는지 릴리스 노트를 참조하세요.



. 스위치 구성에 이전의 사용자 정의를 다시 적용합니다.
. RCF 버전, 사용자 정의 추가 및 스위치 설정이 올바른지 확인한 후 복사하십시오. `running-config` 파일을 `startup-config` 파일.
+
Cisco 명령에 대한 자세한 내용은 link:https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html#CommandReferences["Cisco Nexus 9000 시리즈 NX-OS 명령 참조"^]의 해당 가이드를 참조하십시오.

+
`s2# *copy running-config startup-config*`

+
`[########################################] 100% Copy complete`

. 스위치 s2를 재부팅하십시오. 스위치가 재부팅되는 동안 노드에서 보고되는 "`cluster switch health monitor`" 경고 및 "`cluster ports down`" 이벤트는 무시해도 됩니다.
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 각 노드 스토리지 포트 및 스토리지 쉘프 포트의 관리 또는 운영 상태를 확인하십시오.
+
.. 모든 스토리지 포트가 정상 상태로 작동하는지 확인하세요.
+
[source, cli]
----
storage port show -port-type ENET
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
cluster1-01
                   e5a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
cluster1-02
                   e5a  ENET  -          100 enabled  online
                   e3b  ENET  -          100 enabled  online
.
.
----
====
.. 모든 저장 선반 포트가 정상 상태로 작동하는지 확인하세요.
+
[source, cli]
----
storage shelf port show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.4
       0 A      connected    false
       1 A      connected    false
       2 B      connected    false
       3 B      connected    false
.
.
----
====
.. 스위치가 모니터링되고 있는지 확인합니다.
+
[source, cli]
----
system switch ethernet show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
  Switch           Type               Address          Model
  ---------------- ------------------ ---------------- ---------------
  s1               storage-network    1.2.3.4          N9K-C9336C-FX2
     Serial Number: FFFXXXXXXX1
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
  s2               storage-network    2.3.4.5          N9K-C9336C-FX2
     Serial Number: FEEXXXXXXX2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.3(4a)
    Version Source: CDP/ISDP
----
====


. 스위치 s1에서 1단계부터 16단계까지 반복합니다.




== 3단계: 스토리지 네트워크 확인

RCF 업그레이드 후 스토리지 네트워크가 제대로 작동하는지 확인하려면 각 스토리지 스위치에서 다음 단계를 완료하십시오.

. 노드 스토리지 포트와 스토리지 셸프 포트에 연결된 스위치 포트가 *up* 상태인지 확인하십시오.
+
[source, cli]
----
show interface brief
----
. 예상되는 노드 스토리지 포트가 여전히 연결되어 있는지 확인하십시오.
+
[source, cli]
----
show cdp neighbors
----
. 예상되는 스토리지 셸프 포트가 여전히 연결되어 있는지 확인하십시오.
+
[source, cli]
----
show lldp neighbors
----
. 다음 명령을 사용하여 노드 스토리지 포트와 스토리지 쉘프 포트가 올바른 VLAN에 있는지 확인합니다.
+
[source, cli]
----
show vlan brief
----
+
[source, cli]
----
show interface trunk
----


.다음은 무엇인가요?
RCF를 업그레이드한 후에는 다음을 수행할 수 있습니다.link:configure-ssh-keys.html["SSH 구성을 확인하세요"] .
