---
permalink: switch-cisco-9808/configure-upgrade-rcf-9808.html 
sidebar: sidebar 
keywords: install rcf, cisco switches 
summary: 'Cisco Nexus 9808 스위치의 참조 구성 파일(RCF) 버전을 업그레이드하여 새로운 하드웨어, 새로운 ONTAP 버전을 지원하거나 AFX 2K 시스템 구성에서 새로운 NX-OS 버전에 맞게 조정합니다.' 
---
= Cisco Nexus 9808의 RCF 버전 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9808 스위치에서 참조 구성 파일(RCF) 버전을 업그레이드하여 새로운 하드웨어, 새로운 ONTAP 버전을 지원하거나 AFX 2K 시스템 구성에서 새로운 NX-OS 버전에 맞게 조정합니다.


NOTE: 지원되지 않는 버전으로 RCF 버전을 업그레이드하거나 다운그레이드하지 마십시오.

.시작하기 전에
* link:configure-install-upgrade-rcf-overview-9808.html["RCF 설치 또는 업그레이드 개요"] 페이지를 읽어야 합니다.
* 스위치에 시리얼 콘솔로 연결되어 있거나 기본 구성 정보를 저장해 두어야 합니다. RCF 업그레이드 절차에서는 스위치 설정을 삭제하고 기본 구성을 수행해야 하기 때문입니다.
* 스위치 구성의 현재 백업이 있는지 확인하십시오.
* 클러스터가 완전히 정상적으로 작동하는지, 즉 로그에 오류가 없거나 유사한 문제가 없는지 확인하십시오.
* 최신 RCF 버전을 사용해야 합니다.
* 원하는 부팅 이미지를 반영하는 부팅 구성이 RCF에 있어야 합니다.
+
현재 부트 이미지를 반영하도록 부트 구성을 변경해야 하는 경우 RCF를 다시 적용하기 전에 변경해야 합니다. 이렇게 하면 향후 재부팅 시 올바른 버전이 인스턴스화됩니다.



.이 작업에 관하여
* 두 스위치의 RCF를 업그레이드하는 것은 시스템 중단 없이 진행되는 절차입니다.
+
** 이 절차를 수행하는 동안에는 운영 중인 스위치 간 링크(ISL)가 필요하지 않습니다. 이는 RCF 버전 변경으로 인해 ISL 연결에 일시적인 영향을 줄 수 있기 때문에 의도적으로 설계된 것입니다. 클러스터 운영에 지장이 없도록 하기 위해, 이 절차에서는 대상 스위치에서 단계를 수행하는 동안 모든 클러스터 LIF를 운영 파트너 스위치로 마이그레이션합니다.
** 이 절차에서는 먼저 첫 번째 스위치(cs1)의 RCF를 업그레이드한 다음 두 번째 스위치(cs2)에 대해 동일한 단계를 반복합니다.


* 이 절차에서는 ONTAP 명령과 Cisco Nexus 9000 시리즈 스위치 명령을 사용해야 하며, 각 단계에서는 명령을 입력하는 데 사용하는 CLI를 나타냅니다.
* 이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.
+
** 두 Cisco 스위치의 이름은 cs1과 cs2입니다.
** 노드 이름은 node1-01, node1-02, node1-03, node1-04입니다.
** 클러스터 LIF 이름은 다음과 같습니다.
+
*** node1-01에 대한 node1-01_clus1 및 node1-01_clus2
*** node1-02에 대한 node1-02_clus1 및 node1-02_clus2
*** node1-03에 대한 node1-03_clus1 및 node1-03_clus2
*** node1-04에 대한 node1-04_clus1 및 node1-04_clus2


** 그만큼 `cluster1::*>` 프롬프트는 클러스터의 이름을 나타냅니다.






[[step-1-prepare-for-the-upgrade]]
== 1단계: 업그레이드 준비

다음 단계에 대한 명령은 ONTAP CLI에서 입력합니다.

. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
[source, cli]
----
system node autosupport invoke -node * -type all -message MAINT=xh
----
+
여기서 _x_는 유지 관리 기간(시간)입니다.

. 계속할지 묻는 메시지가 나타나면 *y*를 입력하여 권한 수준을 고급으로 변경합니다.
+
[source, cli]
----
set -privilege advanced
----
+
고급 프롬프트(*>)가 나타납니다.

. 스위치에 연결된 각 노드의 포트를 표시합니다.
+
[source, cli]
----
network device-discovery show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/5       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/14      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/7       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/16      N9K-C9808
            e2a    cs1(FOXXXXXXXXX)          Ethernet1/3       N9K-C9808
            e2b    cs2(FOXXXXXXXXX)          Ethernet1/12      N9K-C9808
node1-01/lldp
            e10a   cs1 (ec:bb:78:9e:c7:e8)   Ethernet1/5       -
            e10b   cs2 (ec:bb:78:9e:c8:0c)   Ethernet1/14      -
            e8a    cs1 (ec:bb:78:9e:c7:f0)   Ethernet1/7       -
            e8b    cs2 (ec:bb:78:9e:c8:14)   Ethernet1/16      -
            e1a    cs1 (ec:bb:78:9e:c7:d8)   Ethernet1/1       -
            e1b    cs2 (ec:bb:78:9e:c7:fc)   Ethernet1/10      -
            e2a    cs1 (ec:bb:78:9e:c7:e0)   Ethernet1/3       -
            e2b    cs2 (ec:bb:78:9e:c8:04)   Ethernet1/12      -
node1-02/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/6       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/15      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/8       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/17      N9K-C9808
            e2a    cs1(FOXXXXXXXXXX)         Ethernet1/2       N9K-C9808
            e2b    cs2(FOX3005Q66Q)          Ethernet1/13      N9K-C9808
node1-02/lldp
            e10a   cs1 (ec:bb:78:9e:c7:ec)   Ethernet1/6       -
            e10b   cs2 (ec:bb:78:9e:c8:10)   Ethernet1/15      -
            e8a    cs1 (ec:bb:78:9e:c7:f4)   Ethernet1/8       -
            e8b    cs2 (ec:bb:78:9e:c8:18)   Ethernet1/17      -
            e1a    cs1 (ec:bb:78:9e:c7:dc)   Ethernet1/2       -
            e1b    cs2 (ec:bb:78:9e:c8:00)   Ethernet1/11      -
            e2a    cs1 (ec:bb:78:9e:c7:e4)   Ethernet1/4       -
            e2b    cs2 (ec:bb:78:9e:c8:08)   Ethernet1/13      -
.
.
.
----
====
. 각 항구의 행정 및 운영 상태를 확인하세요.
+
.. *클러스터 포트*
+
... 모든 클러스터 포트가 정상 상태로 작동하는지 확인하세요.
+
[source, cli]
----
network port show -ipspace Cluster
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-02
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-03

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-04
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false
----
====
... 모든 클러스터 인터페이스(LIF)가 홈 포트에 있는지 확인하세요.
+
[source, cli]
----
network interface show -role cluster
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
            Logical            Status     Network           Current      Current Is
Vserver     Interface          Admin/Oper Address/Mask      Node         Port    Home
----------- ------------------ ---------- ----------------- ------------ ------- ----
Cluster
            node1-01_clus1     up/up      169.254.3.4/23     node1-01    e2a     true
            node1-01_clus2     up/up      169.254.3.5/23     node1-01    e2b     true
            node1-02_clus1     up/up      169.254.3.8/23     node1-02    e2a     true
            node1-02_clus2     up/up      169.254.3.9/23     node1-02    e2b     true
            node1-03_clus1     up/up      169.254.1.3/23     node1-03    e2a     true
            node1-03_clus2     up/up      169.254.1.1/23     node1-03    e2b     true
            node1-04_clus1     up/up      169.254.1.6/23     node1-04    e2a     true
            node1-04_clus2     up/up      169.254.1.7/23     node1-04    e2b     true
----
====
... 클러스터가 두 스위치에 대한 정보를 모두 표시하는지 확인하세요.
+
[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs2(FDOXXXXXXXX)            cluster-network    10.228.137.233   N9K-C9808
     Serial Number: FDOXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.5(3)(F)
    Version Source: CDP/ISDP


cs1(FOXXXXXXXXX)            cluster-network    10.228.137.234   N9K-C9808
     Serial Number: FOXXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.5(3)(F)
    Version Source: CDP/ISDP
----
====


.. *HA 포트*
+
... 모든 HA 포트가 정상 상태로 작동하는지 확인하세요.
+
[source, cli]
----
ha interconnect status show -node <node-name>
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====
... 모든 HA 포트가 올바르게 구성되었는지, 그리고 상호 연결 유형이 RoCE인지 확인하십시오.
+
[source, cli]
----
ha interconnect config show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect config show*
  (system ha interconnect config show)
                       Node: node1-01
          Interconnect Type: RoCE
            Local System ID: 542023071
          Partner System ID: 542022984
       Connection Initiator: local
                  Interface: external


Port    IP Address         Flags
------  -----------------  -----------
e1a-17  169.254.17.111     0x0
e1b-18  169.254.18.242     0x0



                       Node: node1-02
          Interconnect Type: RoCE
            Local System ID: 542022984
          Partner System ID: 542023071
       Connection Initiator: partner
                  Interface: external


Port    IP Address         Flags
------  -----------------  -----------
e1a-17  169.254.17.208     0x0
e1b-18  169.254.18.169     0x0
.
.
.
----
====


.. *저장 포트*
+
... 모든 스토리지 포트가 정상 상태로 작동하는지 확인하세요.
+
[source, cli]
----
storage port show -port-type ENET
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-02
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-03
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-04
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
----
====


.. *보관 선반 포트*
+
... 모든 저장 선반 포트가 정상 상태로 작동하는지 확인하세요.
+
[source, cli]
----
storage shelf port show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.0
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false
----
====
... 모든 저장 선반 포트가 정상 상태로 작동하는지 확인하세요.
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 cs1(FOXXXXXXXXX)
1.1   1  connected       Ethernet1/15/1 cs2(FDOXXXXXXXX)
1.1   2  connected       Ethernet1/17/2 cs1(FOXXXXXXXXX)
1.1   3  connected       Ethernet1/15/2 cs2(FDOXXXXXXXX)
1.1   4  connected       Ethernet1/17/3 cs1(FOXXXXXXXXX)
1.1   5  connected       Ethernet1/15/3 cs2(FDOXXXXXXXX)
1.1   6  connected       Ethernet1/17/4 cs1(FOXXXXXXXXX)
1.1   7  connected       Ethernet1/15/4 cs2(FDOXXXXXXXX)
1.1   8  connected       Ethernet1/19/1 cs1(FOXXXXXXXXX)
1.1   9  connected       Ethernet1/17/1 cs2(FDOXXXXXXXX)
1.1   10 connected       Ethernet1/19/2 cs1(FOXXXXXXXXX)
1.1   11 connected       Ethernet1/17/2 cs2(FDOXXXXXXXX)
1.1   12 connected       Ethernet1/19/3 cs1(FOXXXXXXXXX)
1.1   13 connected       Ethernet1/17/3 cs2(FDOXXXXXXXX)
1.1   14 connected       Ethernet1/19/4 cs1(FOXXXXXXXXX)
1.1   15 connected       Ethernet1/17/4 cs2(FDOXXXXXXXX)
----
====




. 클러스터 LIF에서 자동 복구 기능을 비활성화합니다. 클러스터 LIF는 파트너 클러스터 스위치로 페일오버되어 대상 스위치에서 이 절차를 수행하는 동안 해당 상태를 유지합니다.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert false
----




[[step-2-configure-ports]]
== 2단계: 포트 구성

. 스위치 CLI를 사용하여 스위치 cs1에서 각 라인 카드에 대해 노드의 모든 포트에 연결된 포트를 모두 종료합니다.
+
다음 예는 라인 카드 1 `e1`, `e1-1/1-18`, `e1/19/1-4`, `e1/20/1-4` ......... `e1/35/1-4`의 모든 포트를 종료하는 명령을 보여줍니다. 스위치의 각 라인 카드에 대해 이 명령을 반복하십시오.

+
[listing, subs="+quotes"]
----
cs1# *config terminal*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-18*
cs1(config-if-range)# *shutdown*
cs1(config)# *interface e1/19/1-4,e1/20/1-4,e1/21/1-4,e1/22/1-4,e1/23/1-4,e1/24/1-4,e1/25/1-4,e1/26/1-4,e1/27/1-4,e1/28/1-4,e1/29/1-4,e1/30/1-4,e1/31/1-4,e1/32/1-4,e1/33/1-4,e1/34/1-4,e1/35/1-4*
cs1(config-if-range)# *shutdown*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
----
+

CAUTION: 네트워크 연결 문제를 방지하려면 연결된 *모든* 포트를 종료해야 합니다. 자세한 내용은 기술 자료 문서 link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Node_out_of_quorum_when_migrating_cluster_lif_during_switch_OS_upgrade["스위치 OS 업그레이드 중 클러스터 LIF를 마이그레이션할 때 노드가 쿼럼을 벗어났습니다."^]를 참조하십시오.

. ONTAP CLI를 사용하여 클러스터 LIF가 스위치 cs1에서 호스팅되는 포트로 페일오버되었는지 확인하십시오. 몇 초 정도 소요될 수 있습니다.
+
[source, cli]
----
network interface show -role cluster
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*

            Logical         Status     Network            Current     Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node        Port    Home
----------- --------------- ---------- ------------------ ----------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.36.44/16   node1-01    e2a     true
            node1-01_clus2  up/up      169.254.7.5/16     node1-01    e2b     true
            node1-02_clus1  up/up      169.254.197.206/16 node1-02    e2a     true
            node1-02_clus2  up/up      169.254.195.186/16 node1-02    e2b     true
            node1-03_clus1  up/up      169.254.192.49/16  node1-03    e2a     true
            node1-03_clus2  up/up      169.254.182.76/16  node1-03    e2b     true
            node1-04_clus1  up/up      169.254.59.49/16   node1-04    e2a     true
            node1-04_clus2  up/up      169.254.62.244/16  node1-04    e2b     true

8 entries were displayed.
----
====
. ONTAP CLI를 사용하여 클러스터가 정상인지 확인합니다.
+
[source, cli]
----
cluster show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health  Eligibility   Epsilon
----------------- ------- ------------  -------
node1-01          true    true          false
node1-02          true    true          false
node1-03          true    true          true
node1-04          true    true          false
----
====
. 아직 수행하지 않은 경우 스위치 CLI를 사용하여 다음 명령의 출력을 텍스트 파일에 복사하여 현재 스위치 구성의 사본을 저장하십시오.
+
`show running-config`

+
..  `show diff running-config` 명령을 사용하여 부트플래시에 저장된 RCF 파일과 비교하십시오. 또는 타사 diff/compare 도구를 사용하십시오.


. 기본 구성 세부 정보를 저장합니다. `write_erase.cfg` 부트플래시에 있는 파일입니다.
+
[NOTE]
====
다음 사항을 구성해야 합니다.

** 사용자 이름과 비밀번호
** 관리 IP 주소
** 기본 게이트웨이
** 스위치 이름


====
+
[CAUTION]
====
 `write_erase.cfg` 파일이 이미 존재하는 경우 다음과 같이  `write_erase_old.cfg`로 이름을 변경하십시오.

`cs1# move bootflash:write_erase.cfg write_erase_old.cfg`

====
+
`cs1# show run | i "username admin password" > bootflash:write_erase.cfg`

+
`cs1# show run | section "vrf context management" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "interface mgmt0" >> bootflash:write_erase.cfg`

+
`cs1# show run | section "switchname" >> bootflash:write_erase.cfg`

+
자세한 내용은 기술 자료 문서 link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["원격 연결을 유지하면서 Cisco 상호 연결 스위치의 구성을 지우는 방법"^]를 참조하십시오.

. 스위치 CLI를 사용하여  `write_erase.cfg` 파일이 예상대로 채워졌는지 확인하십시오.
+
`show file bootflash:write_erase.cfg`

. 스위치 CLI를 사용하여  `write erase` 명령을 실행하여 현재 저장된 구성을 지웁니다.
+
`cs1# *write erase*`

+
`Warning: This command will erase the startup-configuration.`

+
`Do you wish to proceed anyway? (y/n)  [n] *y*`

. 스위치 CLI를 사용하여 이전에 저장한 기본 구성을 시작 구성에 복사합니다.
+
`cs1# *copy bootflash:write_erase.cfg startup-config*`

. 스위치 CLI를 사용하여 스위치를 재부팅하십시오.
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 관리 IP 주소에 다시 접근할 수 있게 되면 SSH를 통해 스위치에 로그인합니다.
+
SSH 키와 관련된 호스트 파일 항목을 업데이트해야 할 수도 있습니다.

. 스위치 CLI를 사용하여 다음 전송 프로토콜 중 하나(FTP, TFTP, SFTP 또는 SCP)를 이용해 RCF 파일을 스위치 cs1의 부트플래시에 복사합니다.
+
Cisco 명령어에 대한 자세한 내용은 link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 시리즈 NX-OS 명령 참조"^] 가이드의 해당 가이드를 참조하십시오.

+
`copy <protocol>: bootflash: vrf management`

+
.예를 보여주세요
[%collapsible]
====
이 예에서는 TFTP를 사용하여 RCF를 스위치 cs1의 부트플래시에 복사하는 방법을 보여줍니다.

[listing, subs="+quotes"]
----
cs1# *copy tftp: bootflash: vrf management*
Enter source filename: *RCF-v10.1-NX9808-CL1-ST1.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 스위치 CLI를 사용하여 이전에 다운로드한 RCF를 부트플래시에 적용합니다.
+
Cisco 명령어에 대한 자세한 내용은 link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 시리즈 NX-OS 명령 참조"^] 가이드의 해당 가이드를 참조하십시오.

+
이 예에서는 스위치 cs1에 RCF `RCF-v10.1-NX9808-CL1-ST1.txt`가 설치되는 것을 보여줍니다.

+
[listing, subs="+quotes"]
----
cs1# *copy RCF-v10.1-NX9808-CL1-ST1.txt running-config echo-commands*
----
+
[CAUTION]
====
RCF의 *설치 참고 사항*, *중요 참고 사항* 및 *배너* 섹션을 자세히 읽으세요. 스위치의 올바른 구성과 작동을 보장하려면 이 지침을 읽고 따라야 합니다.

====
. 스위치 CLI를 사용하여 RCF가 올바른 최신 버전인지 확인하십시오.
+
`show running-config`

+
올바른 RCF가 있는지 확인하기 위해 출력을 확인할 때 다음 정보가 올바른지 확인하세요.

+
** RCF 배너
** 노드 및 포트 설정
** 사용자 정의
+
출력은 사이트 구성에 따라 달라집니다.  포트 설정을 확인하고 설치한 RCF에 대한 특정 변경 사항이 있는지 릴리스 노트를 참조하세요.



. 스위치 구성에 이전의 사용자 정의를 다시 적용합니다.
+
스위치가 RCF 10.1 이상을 실행 중인 경우 필요에 따라 link:configure-install-upgrade-rcf-overview-9808.html#change-port-speed-configuration["포트 속도 구성 변경"] 할 수 있습니다.

. 스위치 CLI를 사용하여 RCF 버전, 사용자 지정 추가 기능 및 스위치 설정이 올바른지 확인한 후  `running-config` 파일을  `startup-config` 파일로 복사합니다.
+
Cisco 명령에 대한 자세한 내용은 https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 시리즈 NX-OS 명령 참조"^] 가이드의 해당 가이드를 참조하십시오.

+
`cs1# *copy running-config startup-config*`

+
`[########################################] 100% Copy complete`

. 스위치 CLI를 사용하여 스위치 cs1을 재부팅하십시오. 스위치가 재부팅되는 동안 노드에서 보고되는 "`cluster switch health monitor`" 경고 및 "`cluster ports down`" 이벤트는 무시해도 됩니다.
+
`cs1# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. ONTAP CLI를 사용하여 클러스터의 모든 포트 상태를 확인합니다.
+
.. *클러스터 포트*
+
... 클러스터의 모든 노드에서 클러스터 포트가 작동 중이고 정상인지 확인하세요.
+
[source, cli]
----
network port show -ipspace Cluster
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-02
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-03
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false

Node: node1-04
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e2a       Cluster      Cluster          up   9000  auto/400000 healthy  false
e2b       Cluster      Cluster          up   9000  auto/400000 healthy  false
----
====
... 클러스터에서 스위치 상태를 확인합니다.
+
[source, cli]
----
network device-discovery show -protocol cdp
----
+
[source, cli]
----
system cluster-switch show -is-monitoring-enabled-operational true
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/5       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/14      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/7       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/16      N9K-C9808
            e2a    cs1(FOXXXXXXXXX)          Ethernet1/3       N9K-C9808
            e2b    cs2(FOXXXXXXXXX)          Ethernet1/12      N9K-C9808
node1-02/cdp
            e10a   cs1(FOXXXXXXXXX)          Ethernet1/6       N9K-C9808
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/15      N9K-C9808
            e8a    cs1(FOXXXXXXXXX)          Ethernet1/8       N9K-C9808
            e8b    cs2(FDOXXXXXXXX)          Ethernet1/17      N9K-C9808
            e2a    cs1(FOXXXXXXXXXX)         Ethernet1/2       N9K-C9808
            e2b    cs2(FOX3005Q66Q)          Ethernet1/13      N9K-C9808
.
.
.
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
cs2(FDOXXXXXXXX)           cluster-network    10.228.137.233    N9K-C9808
     Serial Number: FDOXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.6(3)(F)
    Version Source: CDP/ISDP

cs1(FOXXXXXXXXX)           cluster-network    10.228.137.234    N9K-C9808
     Serial Number: FOXXXXXXXXX
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    10.6(3)(F)
    Version Source: CDP/ISDP
----
====


.. *HA 포트*
+
... 모든 HA 포트가 정상 상태로 작동하는지 확인하세요.
+
[source, cli]
----
ha interconnect status show -node <node-name>
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====
... 모든 HA 포트가 올바르게 구성되었는지, 그리고 상호 연결 유형이 RoCE인지 확인하십시오.
+
[source, cli]
----
ha interconnect config show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect config show*
  (system ha interconnect config show)
                       Node: node1-01
          Interconnect Type: RoCE
            Local System ID: 542023071
          Partner System ID: 542022984
       Connection Initiator: local
                  Interface: external


Port    IP Address         Flags
------  -----------------  -----------
e1a-17  169.254.17.111     0x0
e1b-18  169.254.18.242     0x0



                       Node: node1-02
          Interconnect Type: RoCE
            Local System ID: 542022984
          Partner System ID: 542023071
       Connection Initiator: partner
                  Interface: external


Port    IP Address         Flags
------  -----------------  -----------
e1a-17  169.254.17.208     0x0
e1b-18  169.254.18.169     0x0
.
.
.
----
====


.. *저장 포트*
+
... 모든 스토리지 포트가 정상 상태로 작동하는지 확인하세요.
+
[source, cli]
----
storage port show -port-type ENET
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-02
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-03
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
node1-04
                   e10a ENET  -          400 enabled  online
                   e10b ENET  -            0 enabled  offline
                   e8a ENET   -          400 enabled  online
                   e8b ENET   -            0 enabled  offline
----
====


.. *보관 선반 포트*
+
... 모든 저장 선반 포트가 정상 상태로 작동하는지 확인하세요.
+
[source, cli]
----
storage shelf port show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.0
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false
----
====
... 모든 저장 선반 포트의 연결 상태를 확인하세요.
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 cs1(FOXXXXXXXXX)
1.1   1  connected       Ethernet1/15/1 cs2(FDOXXXXXXXX)
1.1   2  connected       Ethernet1/17/2 cs1(FOXXXXXXXXX)
1.1   3  connected       Ethernet1/15/2 cs2(FDOXXXXXXXX)
1.1   4  connected       Ethernet1/17/3 cs1(FOXXXXXXXXX)
1.1   5  connected       Ethernet1/15/3 cs2(FDOXXXXXXXX)
1.1   6  connected       Ethernet1/17/4 cs1(FOXXXXXXXXX)
1.1   7  connected       Ethernet1/15/4 cs2(FDOXXXXXXXX)
1.1   8  connected       Ethernet1/19/1 cs1(FOXXXXXXXXX)
1.1   9  connected       Ethernet1/17/1 cs2(FDOXXXXXXXX)
1.1   10 connected       Ethernet1/19/2 cs1(FOXXXXXXXXX)
1.1   11 connected       Ethernet1/17/2 cs2(FDOXXXXXXXX)
1.1   12 connected       Ethernet1/19/3 cs1(FOXXXXXXXXX)
1.1   13 connected       Ethernet1/17/3 cs2(FDOXXXXXXXX)
1.1   14 connected       Ethernet1/19/4 cs1(FOXXXXXXXXX)
1.1   15 connected       Ethernet1/17/4 cs2(FDOXXXXXXXX)
----
====




. ONTAP CLI를 사용하여 클러스터가 정상인지 확인합니다.
+
[source, cli]
----
cluster show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health   Eligibility   Epsilon
----------------- -------- ------------- -------
node1-01          true     true          false
node1-02          true     true          false
node1-03          true     true          true
node1-04          true     true          false

4 entries were displayed.
----
====
. 스위치 cs2에서 4~18단계를 반복합니다.
. ONTAP CLI를 사용하여 클러스터 LIF에서 자동 복원 기능을 활성화합니다.
+
[source, cli]
----
network interface modify -vserver Cluster -lif * -auto-revert true
----




[[step-3-verify-the-cluster-network-configuration-and-cluster-health]]
== 3단계: 클러스터 네트워크 구성 및 클러스터 상태 확인

. 스위치 CLI를 사용하여 클러스터 포트에 연결된 스위치 포트가 *up* 상태인지 확인합니다.
+
[source, cli]
----
show interface brief
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show interface brief | grep up*
--------------------------------------------------------------------------------
Ethernet        VLAN    Type Mode   Status  Reason                 Speed     Port
Interface                                                                    Ch #
--------------------------------------------------------------------------------
Eth1/1          1       eth  trunk  up      none                     400G(D) --
Eth1/2          1       eth  trunk  up      none                     400G(D) --
Eth1/3          1       eth  trunk  up      none                     400G(D) --
Eth1/4          1       eth  trunk  up      none                     400G(D) --
Eth1/5          1       eth  trunk  up      none                     400G(D) --
Eth1/6          1       eth  trunk  up      none                     400G(D) --
Eth1/7          1       eth  trunk  up      none                     400G(D) --
Eth1/8          1       eth  trunk  up      none                     400G(D) --
Eth1/9          1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/10         1       eth  trunk  up      none                     400G(D) --
Eth1/11         1       eth  trunk  up      none                     400G(D) --
Eth1/12         1       eth  trunk  up      none                     400G(D) --
Eth1/13         1       eth  trunk  up      none                     400G(D) --
Eth1/14         1       eth  trunk  up      none                     400G(D) --
Eth1/15         1       eth  trunk  up      none                     400G(D) --
Eth1/16         1       eth  trunk  up      none                     400G(D) --
Eth1/17         1       eth  trunk  up      none                     400G(D) --
Eth1/18         1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/19/1       1       eth  trunk  up      none                     100G(D) --
Eth1/19/2       1       eth  trunk  up      none                     100G(D) --
Eth1/19/3       1       eth  trunk  up      none                     100G(D) --
Eth1/19/4       1       eth  trunk  up      none                     100G(D) --
Eth1/20/1       1       eth  trunk  up      none                     100G(D) --
Eth1/20/2       1       eth  trunk  up      none                     100G(D) --
Eth1/20/3       1       eth  trunk  up      none                     100G(D) --
Eth1/20/4       1       eth  trunk  up      none                     100G(D) --
.
.
.
Eth1/30/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/30/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/30/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/30/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/31/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/31/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/31/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/31/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/32/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/32/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/32/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/32/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/33/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/33/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/33/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/33/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/34/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/34/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/34/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/34/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/35/1       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/35/2       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/35/3       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/35/4       1       eth  trunk  down    XCVR not inserted        auto(D) --
Eth1/36         1       eth  trunk  down    XCVR not inserted        auto(D) 1

------------------------------------------------------------------------------------
Port-channel VLAN    Type Mode   Status  Reason                    Speed   Protocol
								                                                           Interface
------------------------------------------------------------------------------------
Po1          1       eth  trunk  down    No operational members    auto(D)  lacp
Po998        1       eth  access down    Administratively down     auto(I)  none
Po999        1       eth  access down    Administratively down     auto(I)  none
----
====
. 스위치 CLI를 사용하여 예상 노드가 여전히 연결되어 있는지 확인합니다.
+
[source, cli]
----
show cdp neighbors
----
+
[source, cli]
----
show lldp neighbors
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                  Eth1/3         179    H         AFX-2K          e7a
cs2                  Eth1/4         123    H         AFX-2K          e7a
cs1                  Eth1/5         179    H         AFX-2K          e10a
cs2                  Eth1/6         123    H         AFX-2K          e10a
cs1                  Eth1/7         179    H         AFX-2K          e11a
cs2                  Eth1/8         123    H         AFX-2K          e11a
cs1                  Eth1/12        179    H         AFX-2K          e7b
cs2                  Eth1/13        123    H         AFX-2K          e7b
cs1                  Eth1/14        179    H         AFX-2K          e10b
cs2                  Eth1/15        123    H         AFX-2K          e10b
cs1                  Eth1/16        179    H         AFX-2K          e11b
cs2                  Eth1/17        123    H         AFX-2K          e11b

cs1# *show lldp neighbors*
Capability codes:
  (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device
  (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other
Device ID            Local Intf      Hold-time  Capability  Port ID
cs1                    Eth1/1          121        S           e1a
cs2                    Eth1/2          121        S           e1a
cs1                    Eth1/3          121        S           e7a
cs2                    Eth1/4          121        S           e7a
cs1                    Eth1/5          121        S           e10a
cs2                    Eth1/6          121        S           e10a
cs1                    Eth1/7          121        S           e11a
cs2                    Eth1/8          121        S           e11a
cs1                    Eth1/10         121        S           e1b
cs2                    Eth1/11         121        S           e1b
cs1                    Eth1/12         121        S           e7b
cs2                    Eth1/13         121        S           e7b
cs1                    Eth1/14         121        S           e10b
cs2                    Eth1/15         121        S           e10b
cs1                    Eth1/16         121        S           e11b
cs2                    Eth1/17         121        S           e11b
952551000983           Eth1/19/1       120        S           e1a
952551000983           Eth1/19/2       120        S           e3a
952551000983           Eth1/19/3       120        S           e1a
952551000983           Eth1/19/4       120        S           e3a
952551000983           Eth1/20/1       120        S           e2a
952551000983           Eth1/20/2       120        S           e4a
952551000983           Eth1/20/3       120        S           e2a
952551000983           Eth1/20/4       120        S           e4a
.
.
.
----
====
. 스위치 CLI를 사용하여 다음 명령을 통해 클러스터 노드가 올바른 클러스터 VLAN에 있는지 확인하십시오.
+
[source, cli]
----
show vlan brief
----
+
[source, cli]
----
show interface trunk
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show vlan brief*

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
1    default                          active    Po1, Po998, Po999, Eth1/1
                                                Eth1/2, Eth1/3, Eth1/4, Eth1/5
                                                Eth1/6, Eth1/7, Eth1/8, Eth1/9
                                                Eth1/10, Eth1/11, Eth1/12
                                                Eth1/13, Eth1/14, Eth1/15
                                                Eth1/16, Eth1/17, Eth1/18
                                                Eth1/36, Eth1/19/1, Eth1/19/2
                                                Eth1/19/3, Eth1/19/4, Eth1/20/1
.
.

                                                Eth1/33/4, Eth1/34/1, Eth1/34/2
                                                Eth1/34/3, Eth1/34/4, Eth1/35/1
                                                Eth1/35/2, Eth1/35/3, Eth1/35/4
17   VLAN0017                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
                                                Eth1/9, Eth1/10, Eth1/11
                                                Eth1/12, Eth1/13, Eth1/14
                                                Eth1/15, Eth1/16, Eth1/17
                                                Eth1/18, Eth1/19/1, Eth1/19/2
                                                Eth1/19/3, Eth1/19/4, Eth1/20/1
                                                Eth1/20/2, Eth1/20/3, Eth1/20/4
                                                Eth1/21/1, Eth1/21/2, Eth1/21/3
.
.
                                                Eth1/30/4, Eth1/31/1, Eth1/31/2
                                                Eth1/31/3, Eth1/31/4, Eth1/32/1
                                                Eth1/32/2, Eth1/32/3, Eth1/32/4
                                                Eth1/33/1, Eth1/33/2, Eth1/33/3
                                                Eth1/33/4, Eth1/34/1, Eth1/34/2
                                                Eth1/34/3, Eth1/34/4, Eth1/35/1
                                                Eth1/35/2, Eth1/35/3, Eth1/35/4
18   VLAN0018                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
                                                Eth1/9, Eth1/10, Eth1/11
                                                Eth1/12, Eth1/13, Eth1/14
                                                Eth1/15, Eth1/16, Eth1/17
                                                Eth1/18, Eth1/19/1, Eth1/19/2
                                                Eth1/19/3, Eth1/19/4, Eth1/20/1
.
.
                                                Eth1/30/1, Eth1/30/2, Eth1/30/3
                                                Eth1/30/4, Eth1/31/1, Eth1/31/2
                                                Eth1/31/3, Eth1/31/4, Eth1/32/1
                                                Eth1/32/2, Eth1/32/3, Eth1/32/4
                                                Eth1/33/1, Eth1/33/2, Eth1/33/3
                                                Eth1/33/4, Eth1/34/1, Eth1/34/2
                                                Eth1/34/3, Eth1/34/4, Eth1/35/1
                                                Eth1/35/2, Eth1/35/3, Eth1/35/4
30   VLAN0030                         active    Eth1/1, Eth1/2, Eth1/3, Eth1/4
                                                Eth1/5, Eth1/6, Eth1/7, Eth1/8
                                                Eth1/9, Eth1/10, Eth1/11
                                                Eth1/12, Eth1/13, Eth1/14
                                                Eth1/15, Eth1/16, Eth1/17
                                                Eth1/18, Eth1/19/1, Eth1/19/2
                                                Eth1/19/3, Eth1/19/4, Eth1/20/1
                                                Eth1/20/2, Eth1/20/3, Eth1/20/4
.
.
                                                Eth1/33/1, Eth1/33/2, Eth1/33/3
                                                Eth1/33/4, Eth1/34/1, Eth1/34/2
                                                Eth1/34/3, Eth1/34/4, Eth1/35/1
                                                Eth1/35/2, Eth1/35/3, Eth1/35/4
40   VLAN0040                         active    Po1, Eth1/1, Eth1/2, Eth1/3
                                                Eth1/4, Eth1/5, Eth1/6, Eth1/7
                                                Eth1/8, Eth1/9, Eth1/10, Eth1/11
                                                Eth1/12, Eth1/13, Eth1/14
                                                Eth1/15, Eth1/16, Eth1/17
                                                Eth1/18, Eth1/36, Eth1/19/1
                                                Eth1/19/2, Eth1/19/3, Eth1/19/4
                                                Eth1/20/1, Eth1/20/2, Eth1/20/3
                                                Eth1/20/4, Eth1/21/1, Eth1/21/2
                                                Eth1/21/3, Eth1/21/4, Eth1/22/1
                                                Eth1/22/2, Eth1/22/3, Eth1/22/4
                                                Eth1/23/1, Eth1/23/2, Eth1/23/3
                                                Eth1/23/4, Eth1/24/1, Eth1/24/2
                                                Eth1/24/3, Eth1/24/4, Eth1/25/1
                                                Eth1/25/2, Eth1/25/3, Eth1/25/4
                                                Eth1/26/1, Eth1/26/2, Eth1/26/3
                                                Eth1/26/4, Eth1/27/1, Eth1/27/2
                                                Eth1/27/3, Eth1/27/4, Eth1/28/1
.
.
                                                Eth1/34/2, Eth1/34/3, Eth1/34/4
                                                Eth1/35/1, Eth1/35/2, Eth1/35/3
                                                Eth1/35/4

cs1# *show interface trunk*

--------------------------------------------------------------------------------
Port          Native  Status        Port
              Vlan                  Channel
--------------------------------------------------------------------------------

Eth1/1        1       trunking      --
Eth1/2        1       trunking      --
Eth1/3        1       trunking      --
Eth1/4        1       trunking      --
Eth1/5        1       trunking      --
Eth1/6        1       trunking      --
Eth1/7        1       trunking      --
Eth1/8        1       trunking      --
Eth1/9        1       trunking      --
Eth1/10       1       trunking      --
.
.
.
Eth1/30/1     1       trunking      --
Eth1/30/2     1       trunking      --
Eth1/30/3     1       trunking      --
Eth1/30/4     1       trunking      --
Eth1/31/1     1       trunking      --
Eth1/31/2     1       trunking      --
Eth1/31/3     1       trunking      --
Eth1/31/4     1       trunking      --
Eth1/32/1     1       trunking      --
Eth1/32/2     1       trunking      --
Eth1/32/3     1       trunking      --
Eth1/32/4     1       trunking      --
Eth1/33/1     1       trunking      --
Eth1/33/2     1       trunking      --
Eth1/33/3     1       trunking      --
Eth1/33/4     1       trunking      --
Eth1/34/1     1       trunking      --
Eth1/34/2     1       trunking      --
Eth1/34/3     1       trunking      --
Eth1/34/4     1       trunking      --
Eth1/35/1     1       trunking      --
Eth1/35/2     1       trunking      --
Eth1/35/3     1       trunking      --
Eth1/35/4     1       trunking      --
Eth1/36       1       trnk-bndl     Po1
Po1           1       not-trunking  --


--------------------------------------------------------------------------------
Port          Vlans Allowed on Trunk
--------------------------------------------------------------------------------
Eth1/1        1,17-18,30,40
Eth1/2        1,17-18,30,40
Eth1/3        1,17-18,30,40
Eth1/4        1,17-18,30,40
Eth1/5        1,17-18,30,40
Eth1/6        1,17-18,30,40
Eth1/7        1,17-18,30,40
Eth1/8        1,17-18,30,40
Eth1/9        1,17-18,30,40
Eth1/10       1,17-18,30,40
Eth1/11       1,17-18,30,40
.
.
.
Eth1/30/1     1,17-18,30,40
Eth1/30/2     1,17-18,30,40
Eth1/30/3     1,17-18,30,40
Eth1/30/4     1,17-18,30,40
Eth1/31/1     1,17-18,30,40
Eth1/31/2     1,17-18,30,40
Eth1/31/3     1,17-18,30,40
Eth1/31/4     1,17-18,30,40
Eth1/32/1     1,17-18,30,40
Eth1/32/2     1,17-18,30,40
Eth1/32/3     1,17-18,30,40
Eth1/32/4     1,17-18,30,40
Eth1/33/1     1,17-18,30,40
Eth1/33/2     1,17-18,30,40
Eth1/33/3     1,17-18,30,40
Eth1/33/4     1,17-18,30,40
Eth1/34/1     1,17-18,30,40
Eth1/34/2     1,17-18,30,40
Eth1/34/3     1,17-18,30,40
Eth1/34/4     1,17-18,30,40
Eth1/35/1     1,17-18,30,40
Eth1/35/2     1,17-18,30,40
Eth1/35/3     1,17-18,30,40
Eth1/35/4     1,17-18,30,40
Eth1/36       1,40
Po1           1,40


--------------------------------------------------------------------------------
Port          Vlans Err-disabled on Trunk
--------------------------------------------------------------------------------
Eth1/1        none
Eth1/2        none
Eth1/3        none
Eth1/4        none
Eth1/5        none
Eth1/6        none
Eth1/7        none
Eth1/8        none
Eth1/9        none
Eth1/10       none
.
.
.
Eth1/30/1     none
Eth1/30/2     none
Eth1/30/3     none
Eth1/30/4     none
Eth1/31/1     none
Eth1/31/2     none
Eth1/31/3     none
Eth1/31/4     none
Eth1/32/1     none
Eth1/32/2     none
Eth1/32/3     none
Eth1/32/4     none
Eth1/33/1     none
Eth1/33/2     none
Eth1/33/3     none
Eth1/33/4     none
Eth1/34/1     none
Eth1/34/2     none
Eth1/34/3     none
Eth1/34/4     none
Eth1/35/1     none
Eth1/35/2     none
Eth1/35/3     none
Eth1/35/4     none
Eth1/36       none
Po1           none


--------------------------------------------------------------------------------
Port          STP Forwarding
--------------------------------------------------------------------------------
Eth1/1        1,17-18,30,40
Eth1/2        1,17-18,30,40
Eth1/3        1,17-18,30,40
Eth1/4        1,17-18,30,40
Eth1/5        1,17-18,30,40
Eth1/6        1,17-18,30,40
Eth1/7        1,17-18,30,40
Eth1/8        1,17-18,30,40
Eth1/9        none
Eth1/10       1,17-18,30,40
.
.
.
Eth1/30/1     none
Eth1/30/2     none
Eth1/30/3     none
Eth1/30/4     none
Eth1/31/1     none
Eth1/31/2     none
Eth1/31/3     none
Eth1/31/4     none
Eth1/32/1     none
Eth1/32/2     none
Eth1/32/3     none
Eth1/32/4     none
Eth1/33/1     none
Eth1/33/2     none
Eth1/33/3     none
Eth1/33/4     none
Eth1/34/1     none
Eth1/34/2     none
Eth1/34/3     none
Eth1/34/4     none
Eth1/35/1     none
Eth1/35/2     none
Eth1/35/3     none
Eth1/35/4     none
Eth1/36       none
Po1           none


--------------------------------------------------------------------------------
Port          Vlans in spanning tree forwarding state and not pruned
--------------------------------------------------------------------------------
Eth1/1        Feature VTP is not enabled 1,17-18,30,40
Eth1/2        Feature VTP is not enabled 1,17-18,30,40
Eth1/3        Feature VTP is not enabled 1,17-18,30,40
Eth1/4        Feature VTP is not enabled 1,17-18,30,40
Eth1/5        Feature VTP is not enabled 1,17-18,30,40
Eth1/6        Feature VTP is not enabled 1,17-18,30,40
Eth1/7        Feature VTP is not enabled 1,17-18,30,40
Eth1/8        Feature VTP is not enabled 1,17-18,30,40
Eth1/9        Feature VTP is not enabled 1,17-18,30,40
Eth1/10       Feature VTP is not enabled 1,17-18,30,40
.
.
.
Eth1/30/1     Feature VTP is not enabled none
Eth1/30/2     Feature VTP is not enabled none
Eth1/30/3     Feature VTP is not enabled none
Eth1/30/4     Feature VTP is not enabled none
Eth1/31/1     Feature VTP is not enabled none
Eth1/31/2     Feature VTP is not enabled none
Eth1/31/3     Feature VTP is not enabled none
Eth1/31/4     Feature VTP is not enabled none
Eth1/32/1     Feature VTP is not enabled none
Eth1/32/2     Feature VTP is not enabled none
Eth1/32/3     Feature VTP is not enabled none
Eth1/32/4     Feature VTP is not enabled none
Eth1/33/1     Feature VTP is not enabled none
Eth1/33/2     Feature VTP is not enabled none
Eth1/33/3     Feature VTP is not enabled none
Eth1/33/4     Feature VTP is not enabled none
Eth1/34/1     Feature VTP is not enabled none
Eth1/34/2     Feature VTP is not enabled none
Eth1/34/3     Feature VTP is not enabled none
Eth1/34/4     Feature VTP is not enabled none
Eth1/35/1     Feature VTP is not enabled none
Eth1/35/2     Feature VTP is not enabled none
Eth1/35/3     Feature VTP is not enabled none
Eth1/35/4     Feature VTP is not enabled none
Eth1/36       Feature VTP is not enabled none
Po1           Feature VTP is not enabled none
----
====
+

NOTE: 특정 포트 및 VLAN 사용에 대한 자세한 내용은 RCF의 배너 및 중요 참고 사항 섹션을 참조하세요.

. 스위치 CLI를 사용하여 cs1과 cs2 간의 ISL이 정상적으로 작동하는지 확인하십시오.
+
[source, cli]
----
show port-channel summary
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SD)     Eth      LACP      Eth1/36(D)
998   Po998(SD)   Eth      NONE      --
999   Po999(SD)   Eth      NONE      --
----
====
. ONTAP CLI를 사용하여 클러스터 LIF가 홈 포트로 되돌아갔는지 확인합니다.
+
[source, cli]
----
network interface show -role cluster
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*

            Logical         Status     Network            Current     Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node        Port    Home
----------- --------------- ---------- ------------------ ----------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.36.44/16   node1-01    e2a     true
            node1-01_clus2  up/up      169.254.7.5/16     node1-01    e2b     true
            node1-02_clus1  up/up      169.254.197.206/16 node1-02    e2a     true
            node1-02_clus2  up/up      169.254.195.186/16 node1-02    e2b     true
            node1-03_clus1  up/up      169.254.192.49/16  node1-03    e2a     true
            node1-03_clus2  up/up      169.254.182.76/16  node1-03    e2b     true
            node1-04_clus1  up/up      169.254.59.49/16   node1-04    e2a     true
            node1-04_clus2  up/up      169.254.62.244/16  node1-04    e2b     true
----
====
+
클러스터 LIF가 홈 포트로 돌아오지 않은 경우 로컬 노드에서 수동으로 되돌립니다.

+
`network interface revert -vserver vserver_name -lif <lif-name>`

. ONTAP CLI를 사용하여 클러스터가 정상인지 확인합니다.
+
[source, cli]
----
cluster show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node              Health  Eligibility   Epsilon
----------------- ------- ------------- -------
node1-01          true    true          false
node1-02          true    true          false
node1-03          true    true          true
node1-04          true    true          false
----
====
. ONTAP CLI를 사용하여 원격 클러스터 인터페이스의 연결 상태를 확인합니다.
+
.. 당신은 사용할 수 있습니다 `network interface check cluster-connectivity show` 클러스터 연결에 대한 접근성 검사 세부 정보를 표시하는 명령:
+
[source, cli]
----
network interface check cluster-connectivity show
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*

                                  Source           Destination     Packet
Node   Date                       LIF              LIF             Loss
------ -------------------------- ---------------- --------------- -----------
node1-01
       6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1   none
       6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus1   none


node1-02
       6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1   none
       6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2   none
.
.
.
----
====
.. 또는 다음을 사용할 수 있습니다. `cluster ping-cluster -node <node-name>` 연결성을 확인하는 명령:
+
[source, cli]
----
cluster ping-cluster -node <node-name>
----
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node1-04
Getting addresses from network interface table...
Cluster node1-01_clus1 169.254.36.44 node1-01 e7a
Cluster node1-01_clus2 169.254.7.5   node1-01 e7b
Cluster node1-02_clus1 169.254.197.206 node1-02 e7a
Cluster node1-02_clus2 169.254.195.186 node1-02 e7b
Cluster node1-03_clus1 169.254.192.49 node1-03 e7a
Cluster node1-03_clus2 169.254.182.76 node1-03 e7b
Cluster node1-04_clus1 169.254.59.49 node1-04 e7a
Cluster node1-04_clus2 169.254.62.244 node1-04 e7b
Local = 169.254.59.49 169.254.62.244
Remote = 169.254.36.44 169.254.7.5 169.254.197.206 169.254.195.186 169.254.192.49 169.254.182.76
Cluster Vserver Id = 4294967293
Ping status:
............
Basic connectivity succeeds on 12 path(s)
Basic connectivity fails on 0 path(s)
................................................
Detected 9000 byte MTU on 12 path(s):
    Local 169.254.59.49 to Remote 169.254.182.76
    Local 169.254.59.49 to Remote 169.254.192.49
    Local 169.254.59.49 to Remote 169.254.195.186
    Local 169.254.59.49 to Remote 169.254.197.206
    Local 169.254.59.49 to Remote 169.254.36.44
    Local 169.254.59.49 to Remote 169.254.7.5
    Local 169.254.62.244 to Remote 169.254.182.76
    Local 169.254.62.244 to Remote 169.254.192.49
    Local 169.254.62.244 to Remote 169.254.195.186
    Local 169.254.62.244 to Remote 169.254.197.206
    Local 169.254.62.244 to Remote 169.254.36.44
    Local 169.254.62.244 to Remote 169.254.7.5
Larger than PMTU communication succeeds on 12 path(s)
RPC status:
6 paths up, 0 paths down (tcp check)
6 paths up, 0 paths down (udp check)
----
====




.다음은 무엇인가요?
스위치의 RCF를 업그레이드한 후에는 link:configure-verify-ssh-9808.html["로그 수집을 위한 SSH 확인"].
