---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/9336c_migrate_from_a_switched_configuration_with_dat_storage_by_adding_two_new_shared_switches.html 
keywords:  
summary:  
---
= 새 공유 스위치 2개를 추가하여 DAT 스토리지를 사용하는 스위치 구성에서 마이그레이션합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/




== DAT 스토리지를 사용하여 스위치 구성에서 마이그레이션합니다

일부 구형 Cisco Nexus 클러스터 스위치를 Cisco Nexus 9336C-FX2 공유 스위치로 교체하는 경우 특정 구성 정보, 포트 연결 및 케이블 연결 요구 사항을 알고 있어야 합니다.

* 지원되는 스위치는 다음과 같습니다.
+
** Nexus 9336C-FX2
** Nexus 3232C


* 스위치는 노드 연결에 다음 포트를 사용합니다.
* Nexus 9336C-FX2:
+
** 포트 1-3: 중단모드(4x10G) 클러스터 내 포트, int e1/1/1-4, e1/2/1-4, e1/3/1-4
** 포트 4-6: 클러스터 내부/HA 포트(4x25G), 내부 e1/4/1-4, e1/5/1-4, e1/6/1-4
** 포트 7-34:40/100GbE 내부 클러스터/HA 포트, int e1/7-34


* Nexus 3232C:
+
** 포트 1 - 30:10/40/100 GbE


* 스위치는 다음과 같은 ISL(Inter-Switch Link) 포트를 사용합니다.
+
** 포트 int e1/35-36: Nexus 9336C-FX2
** 포트 e1/31-32: Nexus 3232C


* Hardware Universe에는 모든 클러스터 스위치에 대해 지원되는 케이블 연결에 대한 정보가 포함되어 있습니다.
+
을 참조하십시오 https://hwu.netapp.com["Hardware Universe"] 를 참조하십시오.

* Nexus 9336C-FX2 스위치의 일부 포트가 100GbE에서 실행되도록 구성했습니다.
* 노드에서 Nexus 9336C-FX2 스위치로 100GbE 연결을 계획, 마이그레이션 및 문서화했습니다.
* 이 절차에서 지원되는 ONTAP 및 NX-OS 버전은 Cisco 이더넷 스위치 페이지에 있습니다. 을 참조하십시오 https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"].
* ONTAP 클러스터에서 Cisco Nexus 9336C-FX2 네트워크 스위치로 무중단으로 다른 Cisco 클러스터 스위치를 마이그레이션할 수 있습니다.


.시작하기 전에
* 기존 스위치 네트워크가 올바르게 설정되고 작동해야 합니다.
* 무중단 운영을 보장하려면 모든 포트가 * 가동 * 상태여야 합니다.
* Nexus 9336C-FX2 스위치는 적절한 버전의 NX-OS 설치 및 RCF(Reference Configuration File)를 적용하여 구성 및 작동해야 합니다.
* 기존 네트워크 구성에는 다음이 있어야 합니다.
+
** 구형 Cisco 스위치를 사용하는 완전히 기능이 정상 작동하는 중복 NetApp 클러스터입니다.
** 이전 Cisco 스위치와 새 스위치 모두에 대한 관리 연결 및 콘솔 액세스
** 클러스터 LIF를 사용하는 * UP * 상태의 모든 클러스터 LIF는 홈 포트에 있습니다.
** 다른 Cisco 스위치 간에 또는 새 스위치 간에 연결되고 연결된 ISL 포트




이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 기존 Cisco Nexus 3232C 클러스터 스위치는 _C1_과 _C2_입니다.
* 새로운 Nexus 9336C-FX2 스위치는 _SH1_와 _SH2_입니다.
* 노드는 _node1_ 및 _node2_입니다.
* 클러스터 LIF는 각각 노드 1의 _node1_clus1_과 _node1_clus2_이고, 노드 2의 _node2_clus1_과 _node2_clus2_입니다.
* 스위치 C2가 먼저 스위치 SH2로 대체된 다음 스위치 C1이 스위치 SH1로 대체됩니다.


.단계
. 이 클러스터에서 AutoSupport가 활성화되어 있으면 'system node AutoSupport invoke -node * -type all-message MAINT=x h' AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다
+
여기서 x는 유지 보수 기간(시간)입니다.

. 각 클러스터 포트의 관리 및 운영 상태를 확인합니다.
. 모든 클러스터 포트가 'network port show –role cluster' 상태가 양호한지 확인합니다


[listing]
----
cluster1::*> network port show -role cluster
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
. [[step4]] 모든 클러스터 인터페이스(LIF)가 홈 포트 'network interface show-role cluster'에 있는지 확인합니다


[listing]
----
cluster1::*> network interface show -role cluster
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
. [[5단계] 클러스터가 'system cluster-switch show-is-monitoring-enabled-operational true'라는 두 클러스터 스위치에 대한 정보를 표시하는지 확인합니다


[listing]
----
cluster1::*> system cluster-switch show -is-monitoring-enabled-operational true
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
. [[step6]] 클러스터 LIF에서 자동 복원을 사용하지 않도록 설정합니다.


[listing]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert false
----
. [[7단계]] C2 스위치를 종료합니다.


[listing]
----
c2# configure terminal
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# interface ethernet <int range>
c2(config)#shutdown
----
. [[step8]] 클러스터 LIF가 클러스터 스위치 SH1에 호스팅된 포트로 마이그레이션되었는지 확인합니다. 'network interface show-role cluster' 이 작업은 몇 초 정도 걸릴 수 있습니다.


[listing]
----
cluster1::*> network interface show -role cluster
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
. [[9단계]] 스위치 C2를 새 스위치 SH2로 교체하고 새 스위치를 다시 연결합니다.
. 포트가 SH2에 백업되어 있는지 확인합니다. * LIF는 아직 스위치 C1에 있습니다.
. C1 스위치를 종료합니다.


[listing]
----
c1# configure terminal
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# interface ethernet <int range>
c1(config)#shutdown
----
. [[step12]] 클러스터 LIF가 클러스터 스위치 SH2에 호스팅된 포트로 마이그레이션되었는지 확인합니다. 이 작업은 몇 초 정도 걸릴 수 있습니다.


[listing]
----
cluster1::*> network interface show -role cluster
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
. [[13단계]] 스위치 C1을 새 스위치 SH1로 교체하고 새 스위치를 다시 연결합니다.
. 포트가 SH1에 백업되어 있는지 확인합니다. * LIF는 아직 스위치 C2에 있습니다.
. 클러스터 LIF에서 자동 되돌리기 사용:


[listing]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert True
----
. [[step16]] 클러스터의 상태가 양호한지 확인합니다. '클러스터 쇼'


[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----