---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switchless-cluster-dat-storage.html 
keywords:  
summary:  
---
= 직접 연결 스토리지를 사용하여 스위치리스 클러스터에서 마이그레이션
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
두 개의 새로운 공유 스위치를 추가하여 직접 연결된 스토리지가 있는 스위치리스 클러스터에서 마이그레이션할 수 있습니다.

사용하는 절차는 각 컨트롤러에 전용 클러스터 네트워크 포트가 두 개 있는지, 아니면 각 컨트롤러에 단일 클러스터 포트가 있는지에 따라 달라집니다.  문서화된 프로세스는 광 포트나 Twinax 포트를 사용하는 모든 노드에서 작동하지만, 노드가 클러스터 네트워크 포트에 온보드 10Gb BASE-T RJ45 포트를 사용하는 경우 이 스위치에서는 지원되지 않습니다.

대부분의 시스템에는 각 컨트롤러에 전용 클러스터 네트워크 포트가 두 개 필요합니다. 보다 https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"] 자세한 내용은.

기존에 2노드 스위치리스 클러스터 환경이 있는 경우 Cisco Nexus 9336C-FX2 스위치를 사용하여 2노드 스위치 클러스터 환경으로 마이그레이션하면 클러스터에서 노드를 두 개 이상으로 확장할 수 있습니다.



== 검토 요구 사항

다음 사항을 확인하세요.

* 2노드 스위치리스 구성의 경우:
+
** 2노드 스위치리스 구성이 올바르게 설정되고 작동하고 있습니다.
** 노드는 ONTAP 9.8 이상을 실행합니다.
** 모든 클러스터 포트가 *작동* 상태입니다.
** 모든 클러스터 논리 인터페이스(LIF)는 *작동* 상태이며 *홈* 포트에 있습니다.


* Cisco Nexus 9336C-FX2 스위치 구성의 경우:
+
** 두 스위치 모두 관리 네트워크 연결 기능을 갖추고 있습니다.
** 클러스터 스위치에 콘솔로 접근할 수 있습니다.
** Nexus 9336C-FX2 노드 간 스위치와 스위치 간 연결에는 Twinax 또는 파이버 케이블을 사용합니다.
** NetApp https://hwu.netapp.com["Hardware Universe"] 케이블링에 대한 자세한 정보가 포함되어 있습니다.
** ISL(Inter-Switch Link) 케이블은 두 9336C-FX2 스위치의 포트 1/35와 1/36에 연결됩니다.


* 9336C-FX2 스위치의 초기 사용자 정의가 완료되었습니다.  그래서:
+
** 9336C-FX2 스위치는 최신 버전의 소프트웨어를 실행 중입니다.
** 참조 구성 파일(RCF)이 스위치에 적용되었습니다.
** SMTP, SNMP, SSH 등의 모든 사이트 사용자 정의는 새 스위치에서 구성됩니다.






== 스위치 마이그레이션

.예시에 관하여
이 절차의 예에서는 다음 클러스터 스위치와 노드 명명법을 사용합니다.

* 9336C-FX2 스위치의 이름은 _cs1_과 _cs2_입니다.
* 클러스터 SVM의 이름은 _node1_과 _node2_입니다.
* LIF의 이름은 노드 1에서는 각각 _node1_clus1_과 _node1_clus2_이고, 노드 2에서는 각각 _node2_clus1_과 _node2_clus2_입니다.
* cluster1::*> 프롬프트는 클러스터의 이름을 나타냅니다.
* 이 절차에서 사용되는 클러스터 포트는 AFF A400 컨트롤러에 따라 _e3a_와 _e3b_입니다.  그만큼 https://hwu.netapp.com["Hardware Universe"] 플랫폼의 실제 클러스터 포트에 대한 최신 정보가 포함되어 있습니다.




=== 1단계: 직접 연결된 스위치리스 클러스터에서 마이그레이션

. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다. `system node autosupport invoke -node * -type all -message MAINT=xh` .
+
여기서 x는 유지 관리 기간(시간)입니다.




NOTE: AutoSupport 메시지는 기술 지원팀에 이 유지 관리 작업을 알려 유지 관리 기간 동안 자동 케이스 생성이 억제되도록 합니다.

. [[step2]]계속할지 묻는 메시지가 나타나면 y를 입력하여 권한 수준을 고급으로 변경합니다.
+
`set -privilege advanced`

+
고급 프롬프트(*>)가 나타납니다.

. 새로운 클러스터 스위치 cs1과 cs2에서 노드에 연결된 모든 포트(ISL 포트 제외)를 비활성화합니다.  ISL 포트를 비활성화하면 안 됩니다.
+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 스위치 cs1에서 노드에 연결된 포트 1~34가 비활성화되어 있음을 보여줍니다.

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *shutdown*
----
====


. [[step4]] 두 9336C-FX2 스위치 cs1과 cs2 사이의 ISL과 ISL의 물리적 포트가 포트 1/35와 1/36에서 작동하는지 확인합니다.
+
`show port-channel summary`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 ISL 포트가 스위치 cs1에서 작동 중임을 보여줍니다.

[listing, subs="+quotes"]
----
cs1# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
다음 예에서는 ISL 포트가 스위치 cs2에서 작동 중임을 보여줍니다.

[listing, subs="+quotes"]
----
       cs2# *show port-channel summary*
        Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
====


. [[step5]]인접 장치 목록을 표시합니다.
+
`show cdp neighbors`

+
이 명령은 시스템에 연결된 장치에 대한 정보를 제공합니다.

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 스위치 cs1의 인접 장치를 나열합니다.

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 2
----
다음 예에서는 스위치 cs2의 인접 장치를 나열합니다.

[listing, subs="+quotes"]
----
cs2# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1           )    Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
====


. [[step6]]모든 클러스터 포트가 작동 중인지 확인하세요.
+
`network port show - ipspace Cluster`

+
각 포트는 Link에 대해 표시되어야 하고 Health Status에 대해 정상으로 표시되어야 합니다.

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: node2
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ---------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.
----
====


. [[step7]]모든 클러스터 LIF가 작동 중인지 확인합니다.
+
`network interface show - vserver Cluster`

+
각 클러스터 LIF는 다음과 같이 표시되어야 합니다. `Is Home` 그리고 관리자/운영자 상태가 up/up입니다.

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical     Status     Network            Current       Current Is
Vserver     Interface   Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.
----
====


. [[step8]]모든 클러스터 LIF에서 자동 되돌리기가 활성화되어 있는지 확인하세요.
+
`network interface show - vserver Cluster -fields auto-revert`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*
       Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
4 entries were displayed.
----
====


. [[step9]]노드1의 클러스터 포트 e3a에서 케이블을 분리한 다음 9336C-FX2 스위치에서 지원하는 적절한 케이블을 사용하여 e3a를 클러스터 스위치 cs1의 포트 1에 연결합니다.
+
NetApp https://hwu.netapp.com["Hardware Universe"] 케이블링에 대한 자세한 정보가 포함되어 있습니다. 보다 link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["HWU에 없는 추가 정보 중 장비를 설치하는 데 필요한 정보는 무엇입니까?"^] 스위치 설치 요구 사항에 대한 자세한 내용은 다음을 참조하십시오.

. 노드2의 클러스터 포트 e3a에서 케이블을 분리한 다음, 9336C-FX2 스위치에서 지원하는 적절한 케이블을 사용하여 e3a를 클러스터 스위치 cs1의 포트 2에 연결합니다.
. 클러스터 스위치 cs1에서 모든 노드 연결 포트를 활성화합니다.
+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 스위치 cs1에서 포트 1/1~1/34가 활성화되어 있음을 보여줍니다.

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/1-34*
cs1(config-if-range)# *no shutdown*
----
====


. [[step12]]모든 클러스터 LIF가 *작동*하고 작동 중이며 true로 표시되는지 확인합니다. `Is Home` :
+
`network interface show - vserver Cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 모든 LIF가 node1과 node2에서 *작동*하고 있음을 보여줍니다. `Is Home` 결과는 *참*입니다:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current     Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node        Port    Home
--------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1       e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1       e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2       e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2       e3b     true
4 entries were displayed.
----
====


. [[step13]]클러스터의 노드 상태에 대한 정보를 표시합니다.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 클러스터 내 노드의 상태와 적격성에 대한 정보를 표시합니다.

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====


. [[step14]]노드1의 클러스터 포트 e3b에서 케이블을 분리한 다음, 9336C-FX2 스위치에서 지원하는 적절한 케이블을 사용하여 e3b를 클러스터 스위치 cs2의 포트 1에 연결합니다.
. 노드2의 클러스터 포트 e3b에서 케이블을 분리한 다음, 9336C-FX2 스위치에서 지원하는 적절한 케이블을 사용하여 e3b를 클러스터 스위치 cs2의 포트 2에 연결합니다.
. 클러스터 스위치 cs2에서 모든 노드 연결 포트를 활성화합니다.
+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 스위치 cs2에서 포트 1/1~1/34가 활성화되어 있음을 보여줍니다.

[listing, subs="+quotes"]
----
cs2# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# *interface e1/1-34*
cs2(config-if-range)# *no shutdown*
----
====


. [[step17]]모든 클러스터 포트가 작동 중인지 확인하세요.
+
`network port show - ipspace Cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 모든 클러스터 포트가 node1과 node2에서 작동 중임을 보여줍니다.

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
----
====


. [[step18]]모든 인터페이스가 true로 표시되는지 확인합니다. `Is Home` :
+
`network interface show - vserver Cluster`

+

NOTE: 완료하는 데 몇 분 정도 걸릴 수 있습니다.

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 모든 LIF가 node1과 node2에서 *작동*하고 있음을 보여줍니다. `Is Home` 결과는 사실입니다:

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true
4 entries were displayed.
----
====


. [[step19]]두 노드 모두 각 스위치에 하나의 연결이 있는지 확인합니다.
+
`show cdp neighbors`

+
.예를 보여주세요
[%collapsible]
====
다음 예는 두 스위치에 대한 적절한 결과를 보여줍니다.

[listing, subs="+quotes"]
----
cs1# *show cdp neighbors*
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3a
node2              Eth1/2         133    H           AFFA400       e3a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
cs2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           AFFA400       e3b
node2              Eth1/2         133    H           AFFA400       e3b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
====


. [[step20]]클러스터에서 검색된 네트워크 장치에 대한 정보를 표시합니다.
+
`network device-discovery show -protocol cdp`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2       /cdp
            e3a    cs1                       0/2               N9K-C9336C
            e3b    cs2                       0/2               N9K-C9336C

node1       /cdp
            e3a    cs1                       0/1               N9K-C9336C
            e3b    cs2                       0/1               N9K-C9336C
4 entries were displayed.
----
====


. [[step21]]HA 쌍 1(및 HA 쌍 2)의 스토리지 구성이 올바르고 오류가 없는지 확인합니다.
+
`system switch ethernet show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------- --------------- ----------
sh1
                          storage-network        172.17.227.5    C9336C

       Serial Number: FOC221206C2
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====


. [[step22]]설정이 비활성화되었는지 확인하세요.
+
`network options switchless-cluster show`

+

NOTE: 명령을 완료하는 데 몇 분이 걸릴 수 있습니다.  '3분 유효기간 만료' 공지를 기다리세요.

+
그만큼 `false` 다음 예제의 출력은 구성 설정이 비활성화되었음을 보여줍니다.

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: false
----
====


. [[step23]]클러스터의 노드 멤버 상태를 확인합니다.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 클러스터 내 노드의 상태와 적격성에 대한 정보를 보여줍니다.

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. 원격 클러스터 인터페이스의 연결성을 확인하세요.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
당신은 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령:

`network interface check cluster-connectivity start`그리고 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*참고:* 실행하기 전에 몇 초 동안 기다리십시오. `show` 세부 정보를 표시하는 명령입니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스의 경우 다음을 사용할 수도 있습니다. `cluster ping-cluster -node <name>` 연결성을 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step25]] 권한 수준을 다시 관리자로 변경합니다.
+
`set -privilege admin`





=== 2단계: 공유 스위치 설정

이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 두 공유 스위치의 이름은 _sh1_과 _sh2_입니다.
* 노드는 _node1_과 _node2_입니다.



NOTE: 이 절차에서는 ONTAP 명령과 Cisco Nexus 9000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 지정되지 않는 한 ONTAP 명령을 사용합니다.

. HA 쌍 1(및 HA 쌍 2)의 스토리지 구성이 올바르고 오류가 없는지 확인하세요.
+
`system switch ethernet show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address         Model
------------------------- ---------------------  --------------- -------
sh1
                          storage-network        172.17.227.5    C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6    C9336C
       Serial Number: FOC220443LZ
        Is Monitored: true
              Reason: None
    Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                      9.3(5)
      Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. 스토리지 노드 포트가 정상적이고 작동하는지 확인하세요.
+
`storage port show -port-type ENET`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage          100      enabled  online        30
        e5a     ENET   storage          100      enabled  online        30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage           100      enabled  online        30
        e5a     ENET  storage           100      enabled  online        30
        e5b     ENET  storage           100      enabled  online        30
----
====


. [[step3]]HA 쌍 1, NSM224 경로 A 포트를 sh1 포트 범위 11-22로 이동합니다.
. HA 쌍 1, 노드 1, 경로 A에서 sh1 포트 범위 11-22까지 케이블을 설치합니다.  예를 들어, AFF A400 의 경로 A 저장 포트는 e0c입니다.
. HA 쌍 1, 노드 2, 경로 A에서 sh1 포트 범위 11-22까지 케이블을 설치합니다.
. 노드 포트가 정상적이고 작동하는지 확인하세요.
+
`storage port show -port-type ENET`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. 클러스터에 스토리지 스위치나 케이블 문제가 없는지 확인하세요.
+
`system health alert show -instance`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====
. HA 쌍 1, NSM224 경로 B 포트를 sh2 포트 범위 11-22로 이동합니다.
. HA 쌍 1, 노드 1, 경로 B에서 sh2 포트 범위 11-22로 케이블을 설치합니다.  예를 들어, AFF A400 의 경로 B 저장 포트는 e5b입니다.
. HA 쌍 1, 노드 2, 경로 B에서 sh2 포트 범위 11-22로 케이블을 설치합니다.
. 노드 포트가 정상적이고 작동하는지 확인하세요.
+
`storage port show -port-type ENET`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                   Speed                             VLAN
Node    Port    Type    Mode       (Gb/s)      State      Status       ID
------- ------- ------- ---------- ----------- ---------- ---------- -----
node1
        e0c     ENET   storage          100      enabled  online        30
        e0d     ENET   storage            0      enabled  offline       30
        e5a     ENET   storage            0      enabled  offline       30
        e5b     ENET   storage          100      enabled  online        30

node2
        e0c     ENET  storage           100      enabled  online        30
        e0d     ENET  storage             0      enabled  offline       30
        e5a     ENET  storage             0      enabled  offline       30
        e5b     ENET  storage           100      enabled  online        30
----
====
. HA 쌍 1의 스토리지 구성이 올바르고 오류가 없는지 확인하세요.
+
`system switch ethernet show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                    Type                   Address          Model
------------------------- ---------------------- ---------------- ----------
sh1
                          storage-network        172.17.227.5     C9336C

      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
sh2
                          storage-network        172.17.227.6     C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
====
. HA 쌍 1의 사용되지 않는 (컨트롤러) 보조 스토리지 포트를 스토리지에서 네트워킹으로 재구성합니다.  두 개 이상의 NS224가 직접 연결된 경우 재구성해야 할 포트가 있습니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage port modify –node [node name] –port [port name] –mode network
----
====
+
브로드캐스트 도메인에 저장 포트를 배치하려면:

+
** `network port broadcast-domain create`(필요한 경우 새 도메인을 생성하려면)
** `network port broadcast-domain add-ports`(기존 도메인에 포트를 추가하려면)


. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.다음은 무엇인가요?
스위치를 마이그레이션한 후에는 다음을 수행할 수 있습니다. link:../switch-cshm/config-overview.html["스위치 상태 모니터링 구성"].
