---
sidebar: sidebar 
permalink: switch-cisco-9336c-fx2-shared/migrate-from-switched-configuration-dat-storage.html 
keywords:  
summary:  
---
= 직접 연결 스토리지를 사용하여 스위치 구성에서 마이그레이션
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
두 개의 새로운 공유 스위치를 추가하여 직접 연결 스토리지를 사용하는 스위치 구성에서 마이그레이션할 수 있습니다.

.지원되는 스위치
다음 스위치가 지원됩니다.

* 넥서스 9336C-FX2
* 넥서스 3232C


이 절차에서 지원되는 ONTAP 및 NX-OS 버전은 Cisco 이더넷 스위치 페이지에 있습니다. 보다 https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"] .

.연결 포트
스위치는 다음 포트를 사용하여 노드에 연결합니다.

* 넥서스 9336C-FX2:
+
** 포트 1-3: 브레이크아웃 모드(4x10G) 클러스터 내 포트, int e1/1/1-4, e1/2/1-4, e1/3/1-4
** 포트 4-6: 브레이크아웃 모드(4x25G) 클러스터 내/HA 포트, int e1/4/1-4, e1/5/1-4, e1/6/1-4
** 포트 7-34: 40/100GbE 클러스터 내/HA 포트, int e1/7-34


* 넥서스 3232C:
+
** 포트 1-30: 10/40/100GbE


* 스위치는 다음의 ISL(Inter-Switch Link) 포트를 사용합니다.
+
** 포트 int e1/35-36: Nexus 9336C-FX2
** 포트 e1/31-32: Nexus 3232C




그만큼 https://hwu.netapp.com["Hardware Universe"] 모든 클러스터 스위치에 지원되는 케이블에 대한 정보가 포함되어 있습니다.

.필요한 것
* 다음 작업을 완료했는지 확인하세요.
+
** Nexus 9336C-FX2 스위치의 일부 포트를 100GbE로 실행하도록 구성했습니다.
** 노드에서 Nexus 9336C-FX2 스위치로 100GbE 연결을 계획, 마이그레이션 및 문서화했습니다.
** ONTAP 클러스터에서 Cisco Nexus 9336C-FX2 네트워크 스위치로 다른 Cisco 클러스터 스위치를 중단 없이 마이그레이션했습니다.


* 기존 스위치 네트워크가 제대로 설정되어 작동하고 있습니다.
* 모든 포트는 중단 없는 운영을 보장하기 위해 *작동* 상태입니다.
* Nexus 9336C-FX2 스위치는 적절한 버전의 NX-OS가 설치되고 참조 구성 파일(RCF)이 적용되어 구성 및 작동합니다.
* 기존 네트워크 구성은 다음과 같습니다.
+
** 두 가지 이전 Cisco 스위치를 모두 사용하는 중복되고 완벽한 기능을 갖춘 NetApp 클러스터입니다.
** 기존 Cisco 스위치와 새로운 스위치 모두에 대한 관리 연결 및 콘솔 액세스가 가능합니다.
** 클러스터 LIF가 있는 *up* 상태의 모든 클러스터 LIF는 홈 포트에 있습니다.
** ISL 포트가 활성화되어 다른 Cisco 스위치와 새 스위치 간에 케이블이 연결되었습니다.




.예시에 관하여
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 기존의 Cisco Nexus 3232C 클러스터 스위치는 _c1_과 _c2_입니다.
* 새로운 Nexus 9336C-FX2 스위치는 _sh1_과 _sh2_입니다.
* 노드는 _node1_과 _node2_입니다.
* 클러스터 LIF는 각각 노드 1의 _node1_clus1_과 _node1_clus2_이고, 노드 2의 _node2_clus1_과 _node2_clus2_입니다.
* 스위치 c2는 먼저 스위치 sh2로 교체되고, 그 다음 스위치 c1은 스위치 sh1로 교체됩니다.


.단계
. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=x h`

+
여기서 x는 유지 관리 기간(시간)입니다.

. 각 클러스터 포트의 관리 및 운영 상태를 확인합니다.
. 모든 클러스터 포트가 정상 상태로 작동하는지 확인하세요.
+
`network port show –role cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -role cluster*
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
====


. [[4단계]]모든 클러스터 인터페이스(LIF)가 홈 포트에 있는지 확인합니다.
+
`network interface show -role cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
====


. [[step5]]클러스터가 두 클러스터 스위치에 대한 정보를 모두 표시하는지 확인합니다.
+
`system cluster-switch show -is-monitoring-enabled-operational true`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
====


. [[step6]]클러스터 LIF에서 자동 복귀를 비활성화합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
====


. [[step7]]c2 스위치를 종료합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
c2# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# *interface ethernet <int range>*
c2(config)# *shutdown*
----
====


. [[step8]]클러스터 LIF가 클러스터 스위치 sh1에 호스팅된 포트로 마이그레이션되었는지 확인합니다.
+
`network interface show -role cluster`

+
몇 초 정도 걸릴 수 있습니다.

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
====


. [[step9]]스위치 c2를 새 스위치 sh2로 교체하고 새 스위치에 다시 케이블을 연결합니다.
. sh2에서 포트가 백업되었는지 확인하세요.  *참고* LIF는 여전히 스위치 c1에 있습니다.
. c1 스위치를 끕니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
c1# *configure terminal*
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# *interface ethernet <int range>*
c1(config)# *shutdown*
----
====


. [[step12]]클러스터 LIF가 클러스터 스위치 sh2에 호스팅된 포트로 마이그레이션되었는지 확인합니다. 몇 초 정도 걸릴 수 있습니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -role cluster*
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
====


. [[step13]]스위치 c1을 새로운 스위치 sh1로 교체하고 새로운 스위치에 다시 케이블을 연결합니다.
. sh1에서 포트가 다시 활성화되었는지 확인하세요.  *참고* LIF는 여전히 스위치 c2에 있습니다.
. 클러스터 LIF에서 자동 되돌리기를 활성화합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert True*
----
====


. [[step16]]클러스터가 정상인지 확인하세요.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----
====


.다음은 무엇인가요?
스위치를 마이그레이션한 후에는 다음을 수행할 수 있습니다. link:../switch-cshm/config-overview.html["스위치 상태 모니터링 구성"].
