---
permalink: switch-cisco-9364d-gx2a/configure-complete-initial-setup-9364d.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9364d-gx2a 
summary: 새로운 AFX 1K 또는 AFX 2K 시스템 설치 또는 스위치 교체의 일환으로 Cisco Nexus 9364D-GX2A 스위치의 전원을 켜거나 스위치를 공장 초기 설정으로 재설정한 후에는 구성 마법사를 사용하여 스위치의 초기 설정을 완료하라는 메시지가 표시됩니다. 다음 구성 마법사 질문과 권장 응답을 참조하여 스위치의 초기 설정을 완료하십시오. 
---
= Cisco Nexus 9364D-GX2A 스위치 초기 설정 완료
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새로운 AFX 1K 또는 AFX 2K 시스템 설치 또는 스위치 교체의 일환으로 Cisco Nexus 9364D-GX2A 스위치의 전원을 켜거나 스위치를 공장 초기 설정으로 재설정한 후에는 구성 마법사를 사용하여 스위치의 초기 설정을 완료하라는 메시지가 표시됩니다. 다음 구성 마법사 질문과 권장 응답을 참조하여 스위치의 초기 설정을 완료하십시오.

.시작하기 전에
각 스위치에 대한 네트워크 및 구성 정보와 해당 라이선스를 확보했는지 확인하십시오.

.이 작업에 관하여
* 각 스위치에서 초기 설정을 완료해야 합니다.
* 필요한 경우, 스위치 설정에 대한 자세한 내용은 "Cisco NX-OS 설정 유틸리티 사용" 장에서 link:https://www.cisco.com/c/en/us/td/docs/dcn/nx-os/nexus9000/104x/configuration/fundamentals/cisco-nexus-9000-series-nx-os-fundamentals-configuration-guide-release-104x.html["Cisco Nexus 9000 시리즈 NX-OS 기본 구성 가이드"^]의 NX-OS 버전을 참조하십시오. 터미널 설정에 대한 정보는 "터미널 설정 및 세션 구성" 장에서 확인할 수 있습니다.


.단계
. 노트북을 스위치의 시리얼 콘솔 포트에 연결하십시오.
+
.. 노트북의 시리얼 콘솔 포트를 9,600보드, N-8-1로 설정합니다.


. 안내에 따라 관리자 사용자의 비밀번호를 설정하십시오.
. 다음 질문에 답변하여 초기 스위치 설정을 완료하십시오.
+

NOTE: 사이트의 보안 정책은 활성화할 응답과 서비스를 정의합니다.

+
[cols="1,2"]
|===
| 즉각적인 | 응답 


 a| 
자동 프로비저닝을 중단하고 일반 설정을 계속하시겠습니까?  (예/아니요)
 a| 
*예*라고 대답하세요.  기본값은 아니요입니다.



 a| 
안전한 비밀번호 표준을 시행하고 싶으신가요?  (예/아니요)
 a| 
*예*라고 대답하세요.  기본값은 '예'입니다.



 a| 
관리자 비밀번호를 입력하세요.
 a| 
기본 비밀번호는 "`admin`"입니다. 새롭고 강력한 비밀번호를 만들어야 합니다.  약한 비밀번호는 거부될 수 있습니다.



 a| 
기본 구성 대화 상자를 표시하시겠습니까?  (예/아니요)
 a| 
스위치의 초기 구성에서 *예*로 응답합니다.



 a| 
다른 로그인 계정을 만드시겠습니까?  (예/아니요)
 a| 
귀하의 답변은 대체 관리자에 대한 귀하 사이트의 정책에 따라 달라집니다.  기본값은 *아니요*입니다.



 a| 
읽기 전용 SNMP 커뮤니티 문자열을 구성하시겠습니까?  (예/아니요)
 a| 
*아니요*라고 대답하세요.  기본값은 아니요입니다.



 a| 
읽기-쓰기 SNMP 커뮤니티 문자열을 구성하시겠습니까?  (예/아니요)
 a| 
*아니요*라고 대답하세요.  기본값은 아니요입니다.



 a| 
스위치 이름을 입력하세요.
 a| 
최대 63자의 영숫자로 구성된 스위치 이름을 입력하세요.



 a| 
대역외(mgmt0) 관리 구성을 계속하시겠습니까?  (예/아니요)
 a| 
해당 프롬프트에서 *예* (기본값)로 응답합니다.  mgmt0 IPv4 주소: 프롬프트에서 IP 주소 ip_address를 입력합니다.



 a| 
기본 게이트웨이를 구성하시겠습니까?  (예/아니요)
 a| 
*예*라고 대답하세요.  default-gateway: 프롬프트의 IPv4 주소에 default_gateway를 입력합니다.



 a| 
고급 IP 옵션을 구성하시겠습니까?  (예/아니요)
 a| 
*아니요*라고 대답하세요.  기본값은 아니요입니다.



 a| 
Telnet 서비스를 활성화하시겠습니까?  (예/아니요)
 a| 
*아니요*라고 대답하세요.  기본값은 아니요입니다.



 a| 
SSH 서비스를 활성화하셨나요?  (예/아니요)
 a| 
*예*라고 대답하세요.  기본값은 '예'입니다.


NOTE: CSHM(Ethernet Switch Health Monitor)의 로그 수집 기능을 사용할 경우 SSH를 사용하는 것이 좋습니다.  보안 강화를 위해 SSHv2도 권장됩니다.



 a| 
생성하려는 SSH 키 유형(dsa/rsa/rsa1)을 입력합니다.
 a| 
기본값은 *rsa*입니다.



 a| 
키 비트 수(1024-2048)를 입력하세요.
 a| 
1024에서 2048까지 키 비트 수를 입력하세요.



 a| 
NTP 서버를 구성하시겠습니까?  (예/아니요)
 a| 
*아니요*라고 대답하세요.  기본값은 아니요입니다.



 a| 
기본 인터페이스 계층(L3/L2) 구성
 a| 
*L2*로 응답하세요.  기본값은 L2입니다.



 a| 
기본 스위치 포트 인터페이스 상태(shut/noshut) 구성
 a| 
*안 돼*라고 대답하세요.  기본값은 noshut입니다.



 a| 
CoPP 시스템 프로필 구성(엄격/중간/관대/고밀도)
 a| 
*엄격하게* 대응하세요.  기본값은 엄격합니다.



 a| 
구성을 편집하시겠습니까?  (예/아니요)
 a| 
이 시점에서 새로운 구성을 볼 수 있습니다.  방금 입력한 구성을 검토하고 필요한 변경 사항을 적용합니다.  구성에 만족하는 경우 프롬프트에서 *아니요*로 응답하세요.  구성 설정을 편집하려면 *예*로 응답하세요.



 a| 
이 구성을 사용하고 저장하시겠습니까?  (예/아니요)
 a| 
구성을 저장하려면 *예*로 응답하세요.  이렇게 하면 킥스타트와 시스템 이미지가 자동으로 업데이트됩니다.


NOTE: 이 단계에서 구성을 저장하지 않으면 다음에 스위치를 재부팅할 때 변경 사항이 적용되지 않습니다.

|===
. 설치가 끝나면 나타나는 화면에서 선택한 구성을 확인하고, 구성을 저장하세요.


.다음은 무엇인가요?
초기 스위치 설정을 완료한 후에는 link:configure-review-cabling-config-requirements-9364d.html["케이블 및 구성 요구 사항을 검토하십시오"].
