---
permalink: switch-cisco-9364d-gx2a/install-upgrade-rcf-overview-cluster.html 
sidebar: sidebar 
keywords: install, upgarde, cluster, switch, cisco 9364d-gx2a 
summary: Nexus 9364d-gx2a 스위치를 처음 설정한 후 RCF를 설치할 수 있습니다. 이 절차를 사용하여 RCF를 업그레이드할 수도 있습니다. 
---
= 참조 구성 파일(RCF) 개요 설치 또는 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nexus 9364D-GX2A 스위치를 처음 설정한 후 참조 구성 파일(RCF)을 설치합니다. 스위치에 기존 RCF 파일 버전이 설치되어 있는 경우 RCF 버전을 업그레이드합니다.

지식 기반 문서를 참조하세요link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["원격 연결을 유지하면서 Cisco 상호 연결 스위치의 구성을 지우는 방법"^] RCF를 설치하거나 업그레이드할 때 자세한 내용을 알아보세요.

.사용 가능한 RCF 구성
* *클러스터-HA-스토리지* - 포트(NX9364D-GX2A-RCF-v10.0-Shared.txt)에서 공유 클러스터/HA/스토리지 트래픽을 지원합니다.


특정 포트 및 VLAN 사용에 대한 자세한 내용은 RCF의 배너 및 중요 참고 사항 섹션을 참조하세요.

.제안된 문서
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치(NSS)"^]
+
NetApp 지원 사이트에서 지원되는 ONTAP 및 RCF 버전에 대한 스위치 호환성 표를 참조하세요.  RCF의 명령 구문과 특정 NX-OS 버전의 구문 사이에는 명령 종속성이 있을 수 있습니다.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-installation-guides-list.html["Cisco Nexus 3=9000 시리즈 스위치"^]
+
Cisco 스위치 업그레이드 및 다운그레이드 절차에 대한 전체 문서는 Cisco 웹사이트에서 제공하는 해당 소프트웨어 및 업그레이드 가이드를 참조하세요.



.예시에 관하여
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 두 Cisco 스위치의 이름은 cs1과 cs2입니다.
* 노드 이름은 node1-01, node1-02, node1-03, node1-04입니다.
* 클러스터 LIF 이름은 node1-01_clus1, node1-01_clus2, node1-02_clus1, node1-02_clus2, node1-03_clus1, node1-03_clus2, node1-04_clus1 및 node1-04_clus2입니다.
* 그만큼 `cluster1::*>` 프롬프트는 클러스터의 이름을 나타냅니다.


를 참조하십시오 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] 플랫폼에서 올바른 클러스터 포트를 확인하세요.


NOTE: 명령 출력은 ONTAP 릴리스에 따라 달라질 수 있습니다.

.사용된 명령어
이 절차에서는 ONTAP 명령과 Cisco Nexus 9000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 지정되지 않는 한 ONTAP 명령을 사용합니다.

.다음은 무엇인가요?
RCF 설치 또는 RCF 업그레이드 절차를 검토한 후link:install-rcf-software-9364d-cluster.html["RCF를 설치하다"] 또는link:upgrade-rcf-software-9364d-cluster.html["RCF를 업그레이드하세요"] 필요에 따라.
