---
permalink: switch-cisco-9364d-gx2a/replace-9364d-cluster.html 
sidebar: sidebar 
keywords: replacing, replace, defective, nexus, switch, cluster, network, nondisruptive, procedure, ndu, replace a cisco nexus 9364d-gx2a cluster switch - cisco nexus 9364d-gx2a 
summary: '클러스터 네트워크에서 결함이 있는 Nexus 9364d-gx2a 스위치를 교체하는 것은 중단 없는 절차(NDU)입니다.' 
---
= Cisco Nexus 9364D-GX2A 스위치 교체
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 네트워크에서 결함이 있는 Nexus 9364D-GX2A 스위치를 교체하려면 다음 단계를 따르세요. 이는 중단 없는 절차(NDU)입니다.



== 요구사항 검토

스위치 교체를 수행하기 전에 다음 사항을 확인하십시오.

* 올바른 스위치가 교체되었는지 확인하기 위해 스위치 일련 번호를 확인했습니다.
* 기존 클러스터 및 네트워크 인프라:
+
** 기존 클러스터가 완전히 연결된 클러스터 스위치를 한 개 이상 사용하여 완전하게 작동하는 것으로 확인되었습니다.
** 모든 클러스터 포트가 작동 중입니다.
** 모든 클러스터 논리 인터페이스(LIF)가 홈 포트에 있습니다.
** ONTAP `cluster ping-cluster -node <node-name>` 명령은 기본 연결과 PMTU보다 큰 통신이 모든 경로에서 성공적임을 나타내야 합니다.


* Nexus 9364D-GX2A 교체 스위치:
+
** 교체 스위치의 관리 네트워크 연결이 작동합니다.
** 교체 스위치에 대한 콘솔 액세스가 있습니다.
** 노드 연결은 포트 1/1부터 1/62까지입니다.
** 모든 ISL(Inter-Switch Link) 포트는 포트 1/63 및 1/64에서 비활성화됩니다.
** 원하는 RCF(Reference Configuration File) 및 NX-OS 운영 체제 이미지 스위치가 스위치에 로드됩니다.
** 스위치의 초기 사용자 정의가 완료되었습니다.link:setup-switch-9364d-cluster.html["9364D-GX2A 클러스터 스위치 구성"] .
+
STP, SNMP, SSH 등의 이전 사이트 사용자 지정이 새 스위치에 복사됩니다.



* 클러스터 LIF가 호스팅된 노드에서 클러스터 LIF를 마이그레이션하기 위한 명령을 실행했습니다.




== 콘솔 로깅을 활성화합니다

NetApp은 사용 중인 장치에서 콘솔 로깅을 사용하도록 설정하고 스위치를 교체할 때 다음 작업을 수행할 것을 적극 권장합니다.

* 유지 관리 중에는 AutoSupport를 활성화된 상태로 둡니다.
* 유지 관리 전후에 유지 관리 AutoSupport를 트리거하여 유지 보수 기간 동안 케이스 생성을 비활성화합니다. 이 기술 자료 문서를 참조하십시오 https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: 예약된 유지 관리 기간 동안 자동 케이스 생성을 억제하는 방법"^] 를 참조하십시오.
* 모든 CLI 세션에 대해 세션 로깅을 설정합니다. 세션 로깅을 활성화하는 방법에 대한 지침은 이 기술 자료 문서의 "로깅 세션 출력" 섹션을 참조하십시오 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP 시스템에 대한 최적의 연결을 위해 PuTTY를 구성하는 방법"^].




== 스위치를 교체합니다

.예를 참조하십시오
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 기존 Nexus 9364D-GX2A 스위치의 이름은 cs1과 cs2입니다.
* 새로운 Nexus 9364D-GX2A 스위치의 이름은 newcs2입니다.
* 노드 이름은 node1-01, node1-02, node1-03, node1-04입니다.
* 클러스터 LIF 이름은 node1-01의 경우 node1-01_clus1과 node1-01_clus2, node1-02의 경우 node1-02_clus1과 node1-02_clus2, node1-03의 경우 node1-03_clus1과 node1-03_clus2, node1-04의 경우 node1-04_clus1과 node1-04_clus2입니다.
* 모든 클러스터 노드에 대한 변경 프롬프트는 cluster1:: *>입니다


.이 작업에 대해
다음 절차는 클러스터 네트워크 토폴로지를 기준으로 합니다.

.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e7b       Cluster      Cluster          up   9000  auto/10000 healthy  false


cluster1::*> *network interface show -vserver Cluster*
            Logical         Status     Network            Current       Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node          Port    Home
----------- --------------- ---------- ------------------ ------------- ------- ----
Cluster
            node1-01_clus1  up/up      169.254.209.69/16  node1-01      e7a     true
            node1-01_clus2  up/up      169.254.49.125/16  node1-01      e7b     true
            node1-02_clus1  up/up      169.254.47.194/16  node1-02      e7a     true
            node1-02_clus2  up/up      169.254.19.183/16  node1-02      e7b     true
.
.
.

cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FLMXXXXXXXX)          Ethernet1/16/3    N9K-C9364D-GX2A
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/16/3    N9K-C9364D-GX2A
            e11a   cs1(FLMXXXXXXXX)          Ethernet1/16/4    N9K-C9364D-GX2A
            e11b   cs2(FDOXXXXXXXX)          Ethernet1/16/4    N9K-C9364D-GX2A
            e1a    cs1(FLMXXXXXXXX)          Ethernet1/16/1    N9K-C9364D-GX2A
            e1b    cs2(FDOXXXXXXXX)          Ethernet1/16/1    N9K-C9364D-GX2A
            .
            .
            .
            e7a    cs1(FLMXXXXXXXX)          Ethernet1/16/2    N9K-C9364D-GX2A
            e7b    cs2(FDOXXXXXXXX)          Ethernet1/16/2    N9K-C9364D-GX2A
.
.
.

cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
Device-ID             Local Intrfce  Hldtme Capability  Platform          Port ID
newcs2(FDOXXXXXXXX)   Eth1/63        179    R S I s     N9K-C9332D-GX2B   Eth1/31
newcs2(FDOXXXXXXXX)   Eth1/64        179    R S I s     N9K-C9332D-GX2B   Eth1/32
node1-01              Eth1/4/1       123    H           AFX-1K            e1a
node1-01              Eth1/4/2       123    H           AFX-1K            e7a
node1-01              Eth1/4/3       123    H           AFX-1K            e10a
node1-01              Eth1/4/4       123    H           AFX-1K            e11a
node1-02              Eth1/9/1       138    H           AFX-1K            e1a
node1-02              Eth1/9/2       138    H           AFX-1K            e7a
node1-02              Eth1/9/3       138    H           AFX-1K            e10a
node1-02              Eth1/9/4       138    H           AFX-1K            e11a
node1-03              Eth1/15/1      138    H           AFX-1K            e1a
node1-03              Eth1/15/2      138    H           AFX-1K            e7a
node1-03              Eth1/15/3      138    H           AFX-1K            e10a
node1-03              Eth1/15/4      138    H           AFX-1K            e11a
node1-04              Eth1/16/1      173    H           AFX-1K            e1a
node1-04              Eth1/16/2      173    H           AFX-1K            e7a
node1-04              Eth1/16/3      173    H           AFX-1K            e10a
node1-04              Eth1/16/4      173    H           AFX-1K            e11a

Total entries displayed: 18


newcs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform          Port ID
cs1(FDOXXXXXXXX)   Eth1/63        179    R S I s     N9K-C9332D-GX2B   Eth1/31
cs1(FDOXXXXXXXX)   Eth1/64        179    R S I s     N9K-C9332D-GX2B   Eth1/32
node1-01           Eth1/4/1       123    H           AFX-1K            e1a
node1-01           Eth1/4/2       123    H           AFX-1K            e7a
node1-01           Eth1/4/3       123    H           AFX-1K            e10a
node1-01           Eth1/4/4       123    H           AFX-1K            e11a
node1-02           Eth1/9/1       138    H           AFX-1K            e1a
node1-02           Eth1/9/2       138    H           AFX-1K            e7a
node1-02           Eth1/9/3       138    H           AFX-1K            e10a
node1-02           Eth1/9/4       138    H           AFX-1K            e11a
node1-03           Eth1/15/1      138    H           AFX-1K            e1a
node1-03           Eth1/15/2      138    H           AFX-1K            e7a
node1-03           Eth1/15/3      138    H           AFX-1K            e10a
node1-03           Eth1/15/4      138    H           AFX-1K            e11a
node1-04           Eth1/16/1      173    H           AFX-1K            e1a
node1-04           Eth1/16/2      173    H           AFX-1K            e7a
node1-04           Eth1/16/3      173    H           AFX-1K            e10a
node1-04           Eth1/16/4      173    H           AFX-1K            e11a

Total entries displayed: 18
----
====


=== 1단계: 교체 준비

. 이 클러스터에서 AutoSupport가 활성화되어 있는 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
'System node AutoSupport invoke-node * -type all-message maINT=xh'

+
여기서 x는 유지 보수 기간(시간)입니다.

+

NOTE: AutoSupport 메시지는 유지보수 기간 동안 자동 케이스 생성이 억제되도록 이 유지보수 작업의 기술 지원에 알립니다.

. 스위치에 적절한 RCF 및 이미지를 설치하고 newcs2를 설치한 후 필요한 현장 준비를 합니다.
+
필요한 경우 새 스위치에 적합한 버전의 RCF 및 NX-OS 소프트웨어를 확인, 다운로드 및 설치합니다. 새 스위치가 올바르게 설정되어 있고 RCF 및 NX-OS 소프트웨어 업데이트가 필요하지 않은 경우 2단계를 계속 진행하십시오.

+
.. NetApp Support 사이트에서 _NetApp 클러스터 및 관리 네트워크 스위치 참조 구성 파일 설명 페이지_로 이동하십시오.
.. 클러스터 네트워크 및 관리 네트워크 호환성 매트릭스 _ 에 대한 링크를 클릭한 다음 필요한 스위치 소프트웨어 버전을 확인합니다.
.. 브라우저의 뒤로 화살표를 클릭하여 설명 페이지로 돌아가 * 계속 * 을 클릭하고 사용권 계약에 동의한 다음 다운로드 페이지로 이동합니다.
.. 다운로드 페이지의 단계에 따라 설치할 ONTAP 소프트웨어 버전에 맞는 올바른 RCF 및 NX-OS 파일을 다운로드하십시오.


. 새 스위치에서 admin으로 로그인하고 노드 클러스터 인터페이스(포트 1/1 - 1/64)에 연결할 모든 포트를 종료합니다.
+
교체 중인 스위치가 작동하지 않고 전원이 꺼진 경우 4단계로 이동합니다. 클러스터 노드의 LIF는 각 노드의 다른 클러스터 포트로 페일오버했어야 합니다.

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
newcs2# *config*
newcs2(config)# *interface e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7/1-4,e1/8/1-4*
newcs2(config-if-range)# *shutdown*
newcs2(config)# *interface e1/9/1-4,e1/10/1-4,e1/11/1-4,e1/12/1-4,e1/13/1-4,e1/14/1-4,e1/15/1-4,e1/16/1-4*
newcs2(config-if-range)# *shutdown*
newcs2(config)# *interface e1/17/1-4,e1/18/1-4,e1/19/1-4,e1/20/1-4,e1/21/1-4,e1/22/1-4,e1/23/1-4,e1/24/1-4*
csnewcs21(config-if-range)# *shutdown*
newcs2(config)# *interface e1/25/1-4,e1/26/1-4,e1/27/1-4,e1/28/1-4,e1/29/1-4,e1/30/1-4,e1/31/1-4,e1/32/1-4*
newcs2(config-if-range)# *shutdown*
newcs2(config)# *interface e1/33/1-4,e1/34/1-4,e1/35/1-4,e1/36/1-4,e1/37/1-4,e1/38/1-4,e1/39/1-4,e1/40/1-4*
newcs2(config-if-range)# *shutdown*
newcs2(config)# *interface e1/41/1-4,e1/42/1-4,e1/43/1-4,e1/44/1-4,e1/35/1-4,e1/46/1-4,e1/47/1-4,e1/48/1-4*
newcs2(config-if-range)# *shutdown*
newcs2(config)# *interface e1/49/1-4,e1/50/1-4,e1/51/1-4,e1/52/1-4,e1/53/1-4,e1/54/1-4,e1/55/1-4,e1/56/1-4*
newcs2(config-if-range)# *shutdown*\
newcs2(config)# *interface e1/57/1-4,e1/58/1-4,e1/59/1-4,e1/60/1-4,e1/61/1-4,e1/62/1-4*
newcs2(config-if-range)# *shutdown*
newcs2(config-if-range)# exit
newcs2(config)# exit
----
====
. 모든 클러스터 LIF에서 자동 되돌리기 기능이 설정되어 있는지 확인합니다.
+
[source, cli]
----
network interface show -vserver Cluster -fields auto-revert
----
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster -fields auto-revert*

             Logical
Vserver      Interface        Auto-revert
------------ ---------------- -------------
Cluster      node1-01_clus1   true
Cluster      node1-01_clus2   true
Cluster      node1-02_clus1   true
Cluster      node1-02_clus2   true
Cluster      node1-03_clus1   true
Cluster      node1-03_clus2   true
Cluster      node1-04_clus1   true
Cluster      node1-04_clus2   true

8 entries were displayed.
----
====
. 원격 클러스터 인터페이스의 연결을 확인합니다.
+
.. 당신은 사용할 수 있습니다 `network interface check cluster-connectivity show` 클러스터 연결에 대한 접근성 검사 세부 정보를 표시하는 명령:
+
[source, cli]
----
network interface check cluster-connectivity show
----
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                     Source          Destination     Packet
Node      Date                       LIF             LIF             Loss
--------- -------------------------- --------------- --------------- -----------
node1-01
          6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1  none
          6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus2  none
node1-02
          6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1  none
          6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2  none
.
.
.
----
====
.. 또는 다음을 사용할 수도 있습니다. `cluster ping-cluster -node <node-name>` 연결성을 확인하는 명령:
+
`cluster ping-cluster -node <node-name>`

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====






=== 2단계: 케이블 및 포트 구성

. Nexus 9364D-GX2A 스위치 cs1에서 ISL 포트 1/63과 1/64를 종료합니다.
+
[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/63-64*
cs1(config-if-range)# *shutdown*
cs1(config-if-range)# exit
cs1(config)# exit
----
. Nexus 9364D-GX2B cs2 스위치에서 모든 케이블을 제거한 다음, 이를 Nexus 9364D-GX2A newcs2 스위치의 동일한 포트에 연결합니다.
. cs1과 newcs2 스위치 사이의 ISL 포트 1/63과 1/64를 가동한 후 포트 채널 작동 상태를 확인합니다.
+
포트 채널은 Po1(SU)를 표시해야 하고, 멤버 포트는 Eth1/63(P) 및 Eth1/64(P)를 표시해야 합니다.

+
.예제 보기
[%collapsible]
====
이 예제에서는 ISL 포트 1/63 및 1/64를 활성화하고 스위치 cs1의 포트 채널 요약을 표시합니다.

[listing, subs="+quotes"]
----
cs1# *config*
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# *interface e1/63-64*
cs1(config-if-range)# *no shutdown*
cs1(config-if-range)# *exit*
cs1(config)# *exit*
cs1#
cs1(config-if-range)# *show port-channel summary*
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
11     Po1(SU)     Eth      LACP      Eth1/63(P)   Eth1/64(P)
999    Po999(SD)   Eth      NONE      --
----
====
. 모든 노드에서 포트 e7b가 작동하는지 확인하세요.
+
[source, cli]
----
network port show ipspace Cluster
----
+
.예제 보기
[%collapsible]
====
출력은 다음과 비슷해야 합니다.

[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false

8 entries were displayed.
----
====
. 이전 단계에서 사용한 것과 동일한 노드에서 네트워크 인터페이스 되돌리기 명령을 사용하여 이전 단계의 포트에 연결된 클러스터 LIF를 되돌립니다.
+
.예제 보기
[%collapsible]
====
이 예에서 Home 값이 true이고 포트가 e7b이면 node1-01의 LIF node1-01_clus2가 성공적으로 되돌려집니다.

다음 명령은 LIF를 반환합니다. `node1-01_clus2` ~에 `node1-01` 모항으로 `e7a` 두 노드의 LIF에 대한 정보를 표시합니다.  이 예에서 Is Home 열이 두 클러스터 인터페이스 모두에 대해 참이고 올바른 포트 할당을 표시하는 경우 첫 번째 노드를 가져오는 것이 성공적입니다. `e7a` 그리고 `e7b` node1-01에서.

[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical         Status     Network            Current    Current Is
Vserver     Interface       Admin/Oper Address/Mask       Node       Port    Home
----------- --------------- ---------- ------------------ ---------- ------- -----
Cluster
            node1-01_clus1  up/up      169.254.209.69/16  node1-01   e7a     true
            node1-01_clus2  up/up      169.254.49.125/16  node1-01   e7b     true
            node1-02_clus1  up/up      169.254.47.194/16  node1-02   e7b     true
            node1-02_clus2  up/up      169.254.19.183/16  node1-02   e7a     false
            .
            .
            .
----
====
. 클러스터의 노드에 대한 정보를 표시합니다.
+
'클러스터 쇼'

+
.예제 보기
[%collapsible]
====
이 예제에서는 이 클러스터의 노드 1과 노드 2에 대한 노드 상태가 true인 것을 보여 줍니다.

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node          Health  Eligibility
------------- ------- ------------
node1-01      false   true
node1-02      true    true
node1-03      true    true
node1-04      true    true
----
====
. 모든 물리적 클러스터 포트가 작동하는지 확인합니다.
+
[source, cli]
----
network port show ipspace Cluster
----
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false
.
.
.
----
====
. 원격 클러스터 인터페이스의 연결을 확인합니다.
+
.. 당신은 사용할 수 있습니다 `network interface check cluster-connectivity show` 클러스터 연결에 대한 접근성 검사 세부 정보를 표시하는 명령:
+
[source, cli]
----
network interface check cluster-connectivity show
----


+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                     Source          Destination     Packet
Node      Date                       LIF             LIF             Loss
--------- -------------------------- --------------- --------------- -----------
node1-01
          6/4/2025 03:13:33 -04:00   node1-01_clus2  node1-02_clus1  none
          6/4/2025 03:13:34 -04:00   node1-01_clus2  node1-02_clus2  none
node1-02
          6/4/2025 03:13:33 -04:00   node1-02_clus2  node1-01_clus1  none
          6/4/2025 03:13:34 -04:00   node1-02_clus2  node1-01_clus2  none
.
.
.
----
====
+
.. 또는 다음을 사용할 수도 있습니다. `cluster ping-cluster -node <node-name>` 연결성을 확인하는 명령:
+
`cluster ping-cluster -node <node-name>`

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
====






=== 3단계: 구성을 확인합니다

. 클러스터의 모든 포트 상태를 확인합니다.
+
.. *클러스터 포트*
+
... 클러스터 포트가 클러스터의 모든 노드에서 정상 작동하는지 확인합니다.
+
[source, cli]
----
network port show ipspace Cluster
----
+
[source, cli]
----
network interface show -vserver cluster
----
+
[source, cli]
----
network device-discovery show -protocol cdp
----
+
[source, cli]
----
show cdp neighbors
----
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*
Node: node1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-03
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


Node: node1-04
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e7a       Cluster      Cluster          up   9000  auto/100000 healthy false
e7b       Cluster      Cluster          up   9000  auto/100000 healthy false


cluster1::*> *network interface show -vserver cluster*

          Logical         Status     Network            Current       Current Is
Vserver   Interface       Admin/Oper Address/Mask       Node          Port    Home
--------- --------------- ---------- ------------------ ------------- ------- ----
Cluster
          node1-01_clus1  up/up      169.254.209.69/16  node1-01      e7a     true
          node1-01_clus2  up/up      169.254.49.125/16  node1-01      e7b     true
          node1-02_clus1  up/up      169.254.47.194/16  node1-02      e7b     true
          node1-02_clus2  up/up      169.254.19.183/16  node1-02      e7a     false
          .
          .
          .

cluster1::> *network device-discovery show -protocol cdp*

Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1-01/cdp
            e10a   cs1(FLMXXXXXXXX)          Ethernet1/16/3    N9K-C9364D-GX2A
            e10b   cs2(FDOXXXXXXXX)          Ethernet1/16/3    N9K-C9364D-GX2A
            e11a   cs1(FLMXXXXXXXX)          Ethernet1/16/4    N9K-C9364D-GX2A
            e11b   cs2(FDOXXXXXXXX)          Ethernet1/16/4    N9K-C9364D-GX2A
            e1a    cs1(FLMXXXXXXXX)          Ethernet1/16/1    N9K-C9364D-GX2A
            e1b    cs2(FDOXXXXXXXX)          Ethernet1/16/1    N9K-C9364D-GX2A
            .
            .
            .
            e7a    cs1(FLMXXXXXXXX)          Ethernet1/16/2    N9K-C9364D-GX2A
            e7b    cs2(FDOXXXXXXXX)          Ethernet1/16/2    N9K-C9364D-GX2A
.
.
.

cs1# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID            Local Intrfce  Hldtme Capability  Platform      Port ID
newcs2(FDOXXXXXXXX)   Eth1/63        179    R S I s     N9K-C9332D-GX2B   Eth1/31
newcs2(FDOXXXXXXXX)   Eth1/64        179    R S I s     N9K-C9332D-GX2B   Eth1/32
node1-01              Eth1/4/1       123    H           AFX-1K            e1a
node1-01              Eth1/4/2       123    H           AFX-1K            e7a
node1-01              Eth1/4/3       123    H           AFX-1K            e10a
node1-01              Eth1/4/4       123    H           AFX-1K            e11a
node1-02              Eth1/9/1       138    H           AFX-1K            e1a
node1-02              Eth1/9/2       138    H           AFX-1K            e7a
node1-02              Eth1/9/3       138    H           AFX-1K            e10a
node1-02              Eth1/9/4       138    H           AFX-1K            e11a
node1-03              Eth1/15/1      138    H           AFX-1K            e1a
node1-03              Eth1/15/2      138    H           AFX-1K            e7a
node1-03              Eth1/15/3      138    H           AFX-1K            e10a
node1-03              Eth1/15/4      138    H           AFX-1K            e11a
node1-04              Eth1/16/1      173    H           AFX-1K            e1a
node1-04              Eth1/16/2      173    H           AFX-1K            e7a
node1-04              Eth1/16/3      173    H           AFX-1K            e10a
node1-04              Eth1/16/4      173    H           AFX-1K            e11a

Total entries displayed: 18


newcs2# *show cdp neighbors*

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1(FDOXXXXXXXX)   Eth1/63        179    R S I s     N9K-C9332D-GX2B   Eth1/31
cs1(FDOXXXXXXXX)   Eth1/64        179    R S I s     N9K-C9332D-GX2B   Eth1/32
node1-01           Eth1/4/1       123    H           AFX-1K            e1a
node1-01           Eth1/4/2       123    H           AFX-1K            e7a
node1-01           Eth1/4/3       123    H           AFX-1K            e10a
node1-01           Eth1/4/4       123    H           AFX-1K            e11a
node1-02           Eth1/9/1       138    H           AFX-1K            e1a
node1-02           Eth1/9/2       138    H           AFX-1K            e7a
node1-02           Eth1/9/3       138    H           AFX-1K            e10a
node1-02           Eth1/9/4       138    H           AFX-1K            e11a
node1-03           Eth1/15/1      138    H           AFX-1K            e1a
node1-03           Eth1/15/2      138    H           AFX-1K            e7a
node1-03           Eth1/15/3      138    H           AFX-1K            e10a
node1-03           Eth1/15/4      138    H           AFX-1K            e11a
node1-04           Eth1/16/1      173    H           AFX-1K            e1a
node1-04           Eth1/16/2      173    H           AFX-1K            e7a
node1-04           Eth1/16/3      173    H           AFX-1K            e10a
node1-04           Eth1/16/4      173    H           AFX-1K            e11a

Total entries displayed: 18
----
====


.. *HA 포트*
+
... 모든 HA 포트가 정상 상태로 작동하는지 확인하세요.
+
`ha interconnect status show -node <node-name>`

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *ha interconnect status show -node node1-01*
  (system ha interconnect status show)

                       Node: node1-01
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE

cluster1::*> *ha interconnect status show -node node1-02*
  (system ha interconnect status show)

                       Node: node1-02
              Link 0 Status: up
              Link 1 Status: up
           Is Link 0 Active: true
           Is Link 1 Active: true
         IC RDMA Connection: up
                       Slot: 0
             Debug Firmware: no


Interconnect Port 0 :
                  Port Name: e1a-17
                        MTU: 4096
           Link Information: ACTIVE


Interconnect Port 1 :
                  Port Name: e1b-18
                        MTU: 4096
           Link Information: ACTIVE
.
.
.
----
====


.. *저장 포트*
+
... 모든 스토리지 포트가 정상 상태로 작동하는지 확인하세요.
+
[source, cli]
----
storage port show -port-type ENET
----
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage port show -port-type ENET*


                                      Speed
Node               Port Type  Mode    (Gb/s) State    Status
------------------ ---- ----- ------- ------ -------- -----------
node1-01
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-02
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
node1-03
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
node1-04
                   e10a ENET  -          100 enabled  online
                   e10b ENET  -          100 enabled  online
                   e11a ENET  -          100 enabled  online
                   e11b ENET  -          100 enabled  online
16 entries were displayed.
----
====


.. *보관 선반 포트*
+
... 모든 저장 선반 포트가 정상 상태로 작동하는지 확인하세요.
+
[source, cli]
----
storage shelf port show
----
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show*

Shelf ID Module State        Internal?
----- -- ------ ------------ ---------
1.1
       0 A      connected    false
       1 A      connected    false
       2 A      connected    false
       3 A      connected    false
       4 A      connected    false
       5 A      connected    false
       6 A      connected    false
       7 A      connected    false
       8 B      connected    false
       9 B      connected    false
      10 B      connected    false
      11 B      connected    false
      12 B      connected    false
      13 B      connected    false
      14 B      connected    false
      15 B      connected    false

16 entries were displayed.
----
====
... 모든 저장 선반 포트의 연결 상태를 확인하세요.
+
[source, cli]
----
storage shelf port show -fields remote-device,remote-port,connector-state
----
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *storage shelf port show -fields remote-device,remote-port,connector-state*

shelf id connector-state remote-port    remote-device
----- -- --------------- -------------- -----------------
1.1   0  connected       Ethernet1/17/1 CX9332D-cs1
1.1   1  connected       Ethernet1/15/1 CX9364D-cs1
1.1   2  connected       Ethernet1/17/2 CX9332D-cs1
1.1   3  connected       Ethernet1/15/2 CX9364D-cs1
1.1   4  connected       Ethernet1/17/3 CX9332D-cs1
1.1   5  connected       Ethernet1/15/3 CX9364D-cs1
1.1   6  connected       Ethernet1/17/4 CX9332D-cs1
1.1   7  connected       Ethernet1/15/4 CX9364D-cs1
1.1   8  connected       Ethernet1/19/1 CX9332D-cs1
1.1   9  connected       Ethernet1/17/1 CX9364D-cs1
1.1   10 connected       Ethernet1/19/2 CX9332D-cs1
1.1   11 connected       Ethernet1/17/2 CX9364D-cs1
1.1   12 connected       Ethernet1/19/3 CX9332D-cs1
1.1   13 connected       Ethernet1/17/3 CX9364D-cs1
1.1   14 connected       Ethernet1/19/4 CX9332D-cs1
1.1   15 connected       Ethernet1/17/4 CX9364D-cs1

16 entries were displayed.
----
====




. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화합니다.
+
'System node AutoSupport invoke-node * -type all-message maINT=end'



.다음 단계
스위치를 교체한 후에는link:../switch-cshm/config-overview.html["스위치 상태 모니터링 구성"] .
