= 요구사항 검토
:allow-uri-read: 




== 요구사항 검토

.필요한 것
* 스위치가 없는 2노드 구성의 경우:
+
** 스위치가 없는 2노드 구성이 올바르게 설정 및 작동합니다.
** 노드는 ONTAP 9.8 이상을 실행하고 있다.
** 모든 클러스터 포트는 * UP * 상태입니다.
** 모든 클러스터 논리 인터페이스(LIF)는 * UP * 상태 및 홈 포트에 있습니다.


* Cisco Nexus 9336C-FX2 스위치 구성의 경우:
+
** 두 스위치 모두 관리 네트워크 연결을 사용합니다.
** 클러스터 스위치에 대한 콘솔 액세스가 있습니다.
** Nexus 9336C-FX2 노드 간 스위치 및 스위치 간 연결은 Twinax 또는 파이버 케이블을 사용합니다.
+
을 참조하십시오 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - 스위치"^] 케이블 연결에 대한 자세한 내용은 를 참조하십시오.



* ISL(Inter-Switch Link) 케이블은 두 9336C-FX2 스위치에서 포트 1/35 및 1/36 에 연결됩니다.
* 두 9336C-FX2 스위치의 초기 사용자 정의가 완료되어 다음과 같은 작업이 가능합니다.
+
** 9336C-FX2 스위치는 최신 버전의 소프트웨어를 실행하고 있습니다.
** RCF(Reference Configuration Files)가 스위치에 적용됩니다. SMTP, SNMP, SSH 등의 사이트 사용자 지정은 새 스위치에서 구성됩니다.




.예를 참조하십시오
이 절차의 예에서는 다음과 같은 클러스터 스위치 및 노드 명명법을 사용합니다.

* 9336C-FX2 스위치의 이름은 CS1과 CS2입니다.
* 클러스터 SVM의 이름은 노드 1과 노드 2입니다.
* LIF의 이름은 노드 1의 node1_clus1 및 node1_clus2이고, 노드 2의 node2_clus1 및 node2_clus2입니다.
* 'cluster1:: *>' 프롬프트는 클러스터의 이름을 나타냅니다.
* 이 절차에 사용되는 클러스터 포트는 e0a 및 e0b입니다.


을 참조하십시오 https://hwu.netapp.com["Hardware Universe"^] 플랫폼을 위한 클러스터 포트에 대한 자세한 내용은 를 참조하십시오.



== 스위치를 마이그레이션합니다



=== 1단계: 마이그레이션 준비

. 이 클러스터에서 AutoSupport가 활성화되어 있는 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
'System node AutoSupport invoke-node * -type all-message maINT=xh'

+
여기서 x는 유지 보수 기간(시간)입니다.

+

NOTE: AutoSupport 메시지는 유지보수 기간 동안 자동 케이스 생성이 억제되도록 이 유지보수 작업의 기술 지원에 알립니다.

. 권한 수준을 고급으로 변경하고 계속할 것인지 묻는 메시지가 표시되면 y를 입력합니다.
+
세트 프리빌리지 고급

+
고급 프롬프트('*>')가 나타납니다.





=== 2단계: 포트 및 케이블 연결 구성

. 새 클러스터 스위치 CS1과 CS2 모두에서 ISL 포트가 아닌 모든 노드 대상 포트를 비활성화합니다.
+
ISL 포트를 비활성화하지 마십시오.

+
.예제 보기
[%collapsible]
====
다음 예에서는 스위치 CS1에서 노드 방향 포트 1부터 34까지 비활성 상태를 보여 줍니다.

[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/7-34
cs1(config-if-range)# shutdown
----
====
. 두 9336C-FX2 스위치 CS1과 CS2 사이의 ISL과 ISL의 물리적 포트가 포트 1/35 및 1/36에서 작동하는지 확인합니다.
+
'포트-채널 요약

+
.예제 보기
[%collapsible]
====
다음 예에서는 스위치 CS1에서 ISL 포트가 작동 중인 것을 보여 줍니다.

[listing]
----
cs1# show port-channel summary

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
다음 예에서는 스위치 CS2에서 ISL 포트가 작동 중인 것을 보여 줍니다.

[listing]
----
(cs2)# show port-channel summary

Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)
----
====
. 인접 장치 목록을 표시합니다.
+
CDP 이웃의 성전

+
이 명령은 시스템에 연결된 장치에 대한 정보를 제공합니다.

+
.예제 보기
[%collapsible]
====
다음 예에서는 스위치 CS1의 인접 장치를 나열합니다.

[listing]
----
cs1# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
다음 예에서는 스위치 CS2의 인접 장치를 나열합니다.

[listing]
----
cs2# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
cs1                Eth1/35        177    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        177    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 2
----
====
. 모든 클러스터 포트가 작동하는지 확인합니다.
+
네트워크 포트 표시 - IPSpace 클러스터

+
각 포트는 Link에, Health Status에 대해서는 Healthy로 표시되어야 합니다.

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.
----
====
. 모든 클러스터 LIF가 작동 중인지 확인합니다.
+
'network interface show-vserver cluster'

+
각 클러스터 LIF가 표시되어야 합니다 `true` 용 `Is Home` 그리고 가 있습니다 `Status Admin/Oper` 위/위

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -vserver Cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
====
. 모든 클러스터 LIF에서 자동 복구가 설정되었는지 확인합니다.
+
'network interface show-vserver Cluster-fields auto-revert'

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -vserver Cluster -fields auto-revert

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true

4 entries were displayed.
----
====
. 9336C-FX2 스위치가 지원하는 적절한 케이블을 사용하여 노드 1의 클러스터 포트 e0a에서 케이블을 분리한 다음 클러스터 스위치 CS1의 포트 1에 e0a를 연결합니다.
+
를 클릭합니다 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - 스위치"^] 케이블 연결에 대한 자세한 내용은 에 나와 있습니다.

. 9336C-FX2 스위치가 지원하는 적절한 케이블을 사용하여 노드 2의 클러스터 포트 e0a에서 케이블을 분리한 다음 클러스터 스위치 CS1의 포트 2에 e0a를 연결합니다.
. 클러스터 스위치 CS1에서 모든 노드 대상 포트를 활성화합니다.
+
.예제 보기
[%collapsible]
====
다음 예에서는 스위치 CS1에서 포트 1/1에서 1/34 사이의 포트가 활성화되어 있음을 보여 줍니다.

[listing]
----
cs1# config
Enter configuration commands, one per line. End with CNTL/Z.
cs1(config)# interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/7-34
cs1(config-if-range)# no shutdown
----
====
. 모든 클러스터 LIF가 작동 중이고 "홈"에 대해 "참"으로 표시되는지 확인합니다.
+
'network interface show-vserver cluster'

+
.예제 보기
[%collapsible]
====
다음 예에서는 모든 LIF가 node1과 node2에 있으며 "홈" 결과가 true인 것을 보여 줍니다.

[listing]
----
cluster1::*> network interface show -vserver Cluster

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true

4 entries were displayed.
----
====
. 클러스터의 노드 상태에 대한 정보를 표시합니다.
+
'클러스터 쇼'

+
.예제 보기
[%collapsible]
====
다음 예제에는 클러스터에 있는 노드의 상태 및 자격에 대한 정보가 표시됩니다.

[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. 9336C-FX2 스위치가 지원하는 적절한 케이블을 사용하여 노드 1의 클러스터 포트 e0b에서 케이블을 분리한 다음 클러스터 스위치 CS2의 포트 1에 e0b를 연결합니다.
. 9336C-FX2 스위치가 지원하는 적절한 케이블을 사용하여 노드 2의 클러스터 포트 e0b에서 케이블을 분리한 다음 클러스터 스위치 CS2의 포트 2에 e0b를 연결합니다.
. 클러스터 스위치 CS2에서 모든 노드 대상 포트를 활성화합니다.
+
.예제 보기
[%collapsible]
====
다음 예에서는 스위치 CS2에서 포트 1/1 ~ 1/34 가 활성화되어 있음을 보여 줍니다.

[listing]
----
cs2# config
Enter configuration commands, one per line. End with CNTL/Z.
cs2(config)# interface e1/1/1-4, e1/2/1-4, e1/3/1-4, e1/4/1-4, e1/5/1-4, e1/6/1-4, e1/7-34
cs2(config-if-range)# no shutdown
----
====
. 모든 클러스터 포트가 작동하는지 확인합니다.
+
네트워크 포트 표시 - IPSpace 클러스터

+
.예제 보기
[%collapsible]
====
다음 예에서는 모든 클러스터 포트가 노드 1과 노드 2에 있음을 보여 줍니다.

[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.
----
====




=== 3단계: 구성을 확인합니다

. 모든 인터페이스가 '홈'에 대해 true로 표시되는지 확인합니다.
+
'network interface show-vserver cluster'

+

NOTE: 이 작업을 완료하는 데 몇 분 정도 걸릴 수 있습니다.

+
.예제 보기
[%collapsible]
====
다음 예에서는 모든 LIF가 node1과 node2에 있으며 "홈" 결과가 true인 것을 보여 줍니다.

[listing]
----
cluster1::*> network interface show -vserver Cluster

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true

4 entries were displayed.
----
====
. 두 노드 모두 각 스위치에 하나씩 연결되어 있는지 확인합니다.
+
CDP 이웃의 성전

+
.예제 보기
[%collapsible]
====
다음 예에서는 두 스위치에 대해 적절한 결과를 보여 줍니다.

[listing]
----
(cs1)# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           FAS2980       e0a
node2              Eth1/2         133    H           FAS2980       e0a
cs2                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs2                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 4

(cs2)# show cdp neighbors

Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         133    H           FAS2980       e0b
node2              Eth1/2         133    H           FAS2980       e0b
cs1                Eth1/35        175    R S I s     N9K-C9336C    Eth1/35
cs1                Eth1/36        175    R S I s     N9K-C9336C    Eth1/36

Total entries displayed: 4
----
====
. 클러스터에서 검색된 네트워크 장치에 대한 정보를 표시합니다.
+
네트워크 디바이스 검색 표시 프로토콜 CDP

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster1::*> network device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               N9K-C9336C
            e0b    cs2                       0/2               N9K-C9336C
node1      /cdp
            e0a    cs1                       0/1               N9K-C9336C
            e0b    cs2                       0/1               N9K-C9336C

4 entries were displayed.
----
====
. 설정이 비활성화되었는지 확인합니다.
+
'network options switchless-cluster show'

+

NOTE: 명령이 완료되는 데 몇 분 정도 걸릴 수 있습니다. '3분 수명 만료' 메시지가 표시될 때까지 기다립니다.

+
.예제 보기
[%collapsible]
====
다음 예제의 false 출력은 구성 설정이 비활성화되어 있음을 보여 줍니다.

[listing]
----
cluster1::*> network options switchless-cluster show
Enable Switchless Cluster: false
----
====
. 클러스터에서 노드 구성원의 상태를 확인합니다.
+
'클러스터 쇼'

+
.예제 보기
[%collapsible]
====
다음 예는 클러스터에 있는 노드의 상태 및 적격성에 대한 정보를 보여줍니다.

[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. 원격 클러스터 인터페이스의 연결을 확인합니다.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
를 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령입니다.

`network interface check cluster-connectivity start` 및 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
* 참고: * 몇 초 동안 기다린 후 `show` 명령을 실행하여 세부 정보를 표시합니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스에 대해 을 사용할 수도 있습니다 `cluster ping-cluster -node <name>` 연결 상태를 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step7]] 권한 수준을 admin으로 다시 변경합니다.
+
'Set-Privilege admin'입니다

. ONTAP 9.8 이상의 경우 다음 명령을 사용하여 스위치 관련 로그 파일을 수집하기 위한 이더넷 스위치 상태 모니터 로그 수집 기능을 활성화합니다.
+
System switch ethernet log setup-password와 system switch ethernet log enable-collection

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster1::*> system switch ethernet log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> system switch ethernet log setup-password

Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system switch ethernet log setup-password

Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system switch ethernet log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster1::*>
----
====
+

NOTE: 이러한 명령에서 오류가 반환되면 NetApp 지원에 문의하십시오.

. ONTAP 릴리스 9.5P16, 9.6P12 및 9.7P10 이상의 패치 릴리스의 경우 다음 명령을 사용하여 스위치 관련 로그 파일을 수집하기 위한 이더넷 스위치 상태 모니터 로그 수집 기능을 활성화합니다.
+
System cluster-switch log setup-password와 system cluster-switch log enable-collection

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster1::*> system cluster-switch log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> system cluster-switch log setup-password

Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system cluster-switch log setup-password

Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> system cluster-switch log enable-collection

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] y

Enabling cluster switch log collection.

cluster1::*>
----
====
+

NOTE: 이러한 명령에서 오류가 반환되면 NetApp 지원에 문의하십시오.

. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화합니다.
+
'System node AutoSupport invoke-node * -type all-message maINT=end'


