= ONTAP 모니터링할 수 있도록 스위치 항목을 만듭니다.
:allow-uri-read: 




== ONTAP 모니터링할 수 있도록 스위치 항목을 만듭니다.

사용하다 `system switch ethernet create` 지정된 이더넷 스위치에 대한 모니터링을 수동으로 구성하고 활성화하는 명령입니다.  ONTAP 스위치를 자동으로 추가하지 않거나, 이전에 스위치를 제거했다가 다시 추가하려는 경우 이 기능이 유용합니다.

[source, cli]
----
system switch ethernet create -device DeviceName -address 1.2.3.4 -snmp-version SNMPv2c -community-or-username cshm1! -model NX3132V -type cluster-network
----
일반적인 예로는 IP 주소가 1.2.3.4이고 SNMPv2c 자격 증명이 *cshm1!*로 설정된 [DeviceName]이라는 스위치를 추가하는 것입니다.  사용 `-type storage-network` 대신에 `-type cluster-network` 스토리지 스위치를 구성하는 경우.



== 스위치를 삭제하지 않고 모니터링을 비활성화합니다.

특정 스위치에 대한 모니터링을 일시 중지하거나 중지하지만 향후 모니터링을 위해 계속 유지하려는 경우 해당 스위치를 수정하십시오. `is-monitoring-enabled-admim` 삭제하는 대신 매개변수를 삭제하세요.

예를 들어:

[source, cli]
----
system switch ethernet modify -device DeviceName -is-monitoring-enabled-admin false
----
이를 통해 새로운 알림이나 재검색을 생성하지 않고도 스위치 세부 정보와 구성을 보존할 수 있습니다.



== 더 이상 필요하지 않은 스위치를 제거하세요

사용 `system switch ethernet delete` 연결이 끊어졌거나 더 이상 필요하지 않은 스위치를 삭제하려면:

[source, cli]
----
system switch ethernet delete -device DeviceName
----
기본적으로 이 명령은 ONTAP 현재 CDP 또는 LLDP를 통해 스위치를 감지하지 못하는 경우에만 성공합니다.  검색된 스위치를 제거하려면 다음을 사용하세요. `-force` 매개변수:

[source, cli]
----
system switch ethernet delete -device DeviceName -force
----
언제 `-force` 이 사용되면 ONTAP 다시 감지하면 스위치가 자동으로 다시 추가될 수 있습니다.
