= 연결된 이더넷 스위치 모니터링 확인
:allow-uri-read: 




== 연결된 이더넷 스위치 모니터링 확인

연결된 이더넷 스위치가 모니터링되고 있는지 확인하려면 다음을 실행하세요.

[source, cli]
----
system switch ethernet show
----
만약 `Model` 열에는 *OTHER* 또는 `IS Monitored` 필드에 *false*가 표시되면 ONTAP 스위치를 모니터링할 수 없습니다.  *OTHER* 값은 일반적으로 ONTAP 해당 스위치의 상태 모니터링을 지원하지 않음을 나타냅니다.

그만큼 `IS Monitored` 필드는 지정된 이유로 *false*로 설정됩니다. `Reason` 필드.

[NOTE]
====
스위치가 명령 출력에 나열되지 않으면 ONTAP 해당 스위치를 발견하지 못했을 가능성이 높습니다.  스위치 케이블이 올바르게 연결되었는지 확인하세요.  필요한 경우 스위치를 수동으로 추가할 수 있습니다.  보다link:monitor-manage.html["이더넷 스위치 모니터링 관리"] 자세한 내용은.

====


== 펌웨어 및 RCF 버전이 최신인지 확인하세요

스위치가 최신 지원 펌웨어를 실행하고 있는지, 호환 가능한 참조 구성 파일(RCF)이 적용되었는지 확인하세요.  자세한 내용은 다음에서 확인할 수 있습니다.https://mysupport.netapp.com/site/downloads["NetApp 지원 다운로드 페이지"^] .

기본적으로 상태 모니터는 모니터링을 위해 커뮤니티 문자열 *cshm1!*과 함께 SNMPv2c를 사용하지만 SNMPv3도 구성할 수 있습니다.

기본 SNMPv2c 커뮤니티 문자열을 변경해야 하는 경우, 원하는 SNMPv2c 커뮤니티 문자열이 스위치에 구성되어 있는지 확인하세요.

[source, cli]
----
system switch ethernet modify -device SwitchA -snmp-version SNMPv2c -community-or-username newCommunity!
----

NOTE: 보다link:config-snmpv3.html["선택 사항: SNMPv3 구성"] SNMPv3를 사용하도록 구성하는 방법에 대한 자세한 내용은 다음을 참조하세요.



== 관리 네트워크 연결 확인

스위치의 관리 포트가 관리 네트워크에 연결되어 있는지 확인하세요.

ONTAP SNMP 쿼리를 수행하고 로그를 수집하려면 올바른 관리 포트 연결이 필요합니다.
