= 새로운 스위치 지원
:allow-uri-read: 




== 새로운 스위치 지원

[cols="25h,~,~"]
|===
| 스위치 | 설명 | 시작 가능 


 a| 
32포트 400GbE 포트 Cisco 스위치(X190300-CS-PI 및 X190300-PE)
 a| 
Cisco 9332D-GX2B 클러스터 내/HA/스토리지 스위치 지원.
 a| 
ONTAP 9.17.1



 a| 
64포트 400GbE 포트 Cisco 스위치(X190310-CS-PI)
 a| 
Cisco 9364D-GX2A 클러스터 내/HA/스토리지 스위치 지원.
 a| 
ONTAP 9.17.1



 a| 
12포트 10/25/40/100GbE Cisco Nexus 9336C-FX2-T 클러스터 및 스토리지 스위치(X190212-CS-PE 및 X190212-CS-PI)
 a| 
10/25/40/100GbE 클러스터 구성과 100GbE 스토리지(스위치 연결 스토리지) 구성을 지원합니다.
 a| 
ONTAP 9.10.1



 a| 
12포트 10/25/40/100GbE Cisco Nexus 9336C-FX2-T 클러스터 및 스토리지 스위치(X190212-CS-PE 및 X190212-CS-PI)
 a| 
10/25/40/100GbE 클러스터 구성과 100GbE 스토리지(스위치 연결 스토리지) 구성을 지원합니다.
 a| 
ONTAP 9.10.1



 a| 
16포트 100GbE NVIDIA 스위치(X190006-PE 및 X190006-PI)
 a| 
NVIDIA SN2100 클러스터 상호 연결 스위치 및 스토리지 스위치 지원( MetroCluster IP 구성 지원 포함)
 a| 
ONTAP 9.10.1



 a| 
36포트 100GbE Cisco 스위치(X190200-CS-PE 및 X190200-CS-PI)
 a| 
동일한 Cisco Nexus 9336C-FX2 스위치 쌍에서 공유 인프라(클러스터, HA 및 스위치 연결 스토리지)를 지원하며 MetroCluster IP 구성도 지원합니다.
 a| 
ONTAP 9.9.1



 a| 
36포트 100GbE Cisco 스위치(X190200-CS-PE 및 X190200-CS-PI), (X190210-FE-PE 및 X190210-FE-PI)
 a| 
Cisco Nexus 9336C-FX2 클러스터 상호 연결 스위치와 스토리지 스위치는 AFF 및 ASA 스토리지 시스템은 물론 프런트엔드 데이터 연결을 지원합니다.
 a| 
ONTAP 9.8



 a| 
Broadcom BES-53248 스위치(X190005 및 X190005R)
 a| 
Broadcom BES-53248 클러스터 상호 연결 스위치는 10/25GbE 및 40/100GbE 포트가 있는 AFF/ FAS 컨트롤러를 지원합니다.
 a| 
ONTAP 9.8



 a| 
36포트 100GbE Cisco 스위치(X190200) 및 32포트 100GbE Cisco 스위치(X190100 및 X190100R)
 a| 
Cisco Nexus 3232C 스토리지 스위치는 NS224 NVMe 드라이브 선반을 AFF 및 ASA 스토리지 시스템에 연결할 수 있도록 지원합니다.

* AFF A800/ AFF ASA A800
* AFF A700/ AFF ASA A700
* AFF A400/ AFF ASA A400
* AFF A320

 a| 
ONTAP 9.8

|===