= 
:allow-uri-read: 


ONTAP AFX 시스템에서 실행되는 ONTAP 버전과 스위치의 NX-OS 버전에 따라 스위치에서 지원하는 RCF 버전이 결정됩니다. RCF 버전에는 포트 속도 구성이 미리 설정되어 있으며, 이 구성에 따라 브레이크아웃 모드(4x100GbE)와 비브레이크아웃 모드에서 작동하는 스위치 포트 수가 결정됩니다.

[NOTE]
====
지원되는 RCF 버전의 최신 목록은 link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["NetApp Cisco 이더넷 스위치"^] 페이지를 참조하십시오.

스위치 포트 정보는 https://hwu.netapp.com["NetApp Hardware Universe"^]에서도 확인할 수 있습니다.

====
* AFX 1K 시스템을 사용하는 경우 RCF 10.0 이상이 지원됩니다.
* AFX 2K 시스템을 사용하는 경우 RCF 10.1 이상이 지원됩니다.
* RCF 10.0은 하나의 파일을 가지고 있으며 공유 스위치를 지원합니다 `Cluster-HA-Storage AFX RCF_10.0`.
+
예를 들어, 다음 표는 이 RCF 파일에 대한 스위치 포트의 사전 설정 그룹화, 포트 속도 및 사용량을 보여줍니다.

+
[cols="1,2"]
|===
| 스위치 포트 그룹 | 포트 속도 및 사용량 


 a| 
이더넷1/1/1-4에서 이더넷1/30/1-4로
 a| 
클러스터, HA 및 스토리지 연결을 위한 4x100GbE 모드



 a| 
이더넷1/31, 이더넷1/32
 a| 
400GbE ISL

|===
* RCF 10.1은 AFX 1K 및 AFX 2K 시스템의 다양한 사용 사례에 맞는 여러 파일을 제공합니다. AFX 1K 또는 AFX 2K 시스템 구성(공유, 스토리지 전용 또는 클러스터 및 HA 전용)에서 스위치를 사용하는 방법에 따라 적절한 RCF 파일을 선택하십시오.
+
예를 들어, AFX 2K 시스템에서 스위치를 공유 스위치로 사용하는 경우 해당 사용 사례에 적합한 RCF 파일을 사용합니다. 적합한 RCF 파일은  `RCF-v10.1-NX9332D-GX2B-CL1-ST1-100GBR15-400G15.txt`와 유사한 이름일 수 있습니다. 다음 표는 이 RCF 파일에 대한 스위치 포트의 사전 설정 그룹, 포트 속도 및 사용 용도를 보여줍니다.

+
[cols="1,2"]
|===
| 스위치 포트 그룹 | 포트 속도 및 사용량 


 a| 
이더넷1/1/1-4에서 이더넷1/15/1-4로
 a| 
클러스터 내, HA 및 스토리지 셸프 연결을 위한 4x100GbE 모드



 a| 
Ethernet1/16~Ethernet1/30
 a| 
클러스터 내 연결, 고가용성(HA) 및 스토리지 연결을 위한 400GbE 모드



 a| 
이더넷1/31, 이더넷1/32
 a| 
400GbE 클러스터 내 ISL 연결

|===

