---
permalink: switch-cisco-9332d-gx2b/configure-install-nxos-9332d.html 
sidebar: sidebar 
keywords: procedure, install, nx-os, software, nexus, cluster, switch, install the nx-os software - cisco nexus 9332d-gc2b 
summary: Cisco Nexus 9332D-GX2B 스위치에 NX-OS를 설치하는 것은 새로운 AFX 1K 또는 AFX 2K 시스템 설치, 스위치 교체 또는 스위치를 공장 기본 설정으로 재설정하는 과정의 일부입니다. 
---
= NX-OS 설치 - Cisco Nexus 9332D-GX2B
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9332D-GX2B 스위치에 NX-OS를 설치하는 것은 새로운 AFX 1K 또는 AFX 2K 시스템 설치, 스위치 교체 또는 스위치를 공장 기본 설정으로 재설정하는 과정의 일부입니다.

.시작하기 전에
* 스위치가 켜져 있어야 하고 link:configure-complete-initial-setup-9332d.html["스위치 초기 설정 완료"] 절차를 완료해야 합니다.
* 새로운 AFX 시스템 설치 또는 스위치 교체의 일환으로 스위치에 NX-OS를 설치하는 경우, 스위치에 설치된 NX-OS 버전이 NetApp에서 지원하는 최신 버전인지 확인하십시오.
+
** 스위치에 현재 NetApp에서 지원하는 버전이 설치되어 있는 경우 NX-OS를 설치할 필요가 없습니다. RCF를 설치해야 합니다. link:configure-install-upgrade-rcf-overview-9332d.html["RCF 설치 또는 업그레이드 개요"]부터 시작하십시오.
** 스위치에 현재 NetApp에서 지원하는 버전이 없는 경우, 이 절차를 계속 진행하여 NX-OS를 설치하십시오.


* 스위치 교체 또는 공장 초기화 과정에서 스위치에 NX-OS를 설치하는 경우, 클러스터가 완전히 정상적으로 작동하는지, 즉 로그에 오류가 없거나 유사한 문제가 없는지 확인하십시오.



NOTE: 새로운 AFX 시스템 설치의 일부로 NX-OS를 설치하는 경우, AFX 시스템 설치 및 설정 단계에서는 AFX 시스템의 컨트롤러 전원이 켜져 있지 않으므로 이 요구 사항을 건너뛸 수 있습니다.

.이 작업에 관하여
* AFX 시스템에서 실행 중인 ONTAP 버전에 따라 스위치에서 지원되는 NX-OS 버전이 결정됩니다.
+
** AFX 1K 시스템의 스위치에서 지원되는 ONTAP 버전을 실행하는 경우 NX-OS 10.4.2 이상이 지원됩니다.
** ONTAP 9.19.1GA 이상 버전을 실행하는 AFX 2K 시스템의 스위치는 NX-OS 10.6 이상 버전을 지원합니다.
+
지원되는 NX-OS 버전의 최신 목록은 link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["NetApp Cisco 이더넷 스위치"^] 페이지를 참조하십시오.



* 이 절차는 Cisco Nexus 9000 Series Switches 명령어만 사용합니다.
* 이 절차의 예시에서는 첫 번째 스위치를 cs1, 두 번째 스위치를 cs2로 지칭합니다.
* 새로운 AFX 1K 또는 AFX 2K 시스템 설치의 일부로 스위치를 설치한 경우, 이 절차에서는 첫 번째 스위치(cs1)에 NX-OS를 설치한 다음 두 번째 스위치(cs2)에 대해 동일한 단계를 반복하도록 안내합니다.
* 이 절차에 제시된 예시는 RCF 10.0을 실행하는 스위치가 있는 AFX 1K 시스템을 기준으로 합니다. AFX 2K 시스템을 사용하는 경우 입력 및 출력이 다를 수 있습니다.




[[step-1-prepare-to-install-the-nx-os]]
== 1단계: NX-OS 설치 준비

NX-OS를 스위치에 설치하기 전에 지원되는 NX-OS 버전이 설치된 서버에 액세스할 수 있는지 확인하고, NX-OS를 다운로드하고, 파일 전송을 위해 관리 네트워크에 연결한 다음, 서버 연결을 확인하십시오.

.단계
. HTTP, FTP 또는 TFTP 서버에 액세스할 수 있어야 합니다. 이러한 서버 중 하나에 액세스하면 지원되는 NX-OS 버전을 다운로드할 수 있습니다.
. 해당  https://software.cisco.com/download/home["Cisco 소프트웨어 다운로드"^] 페이지에서 스위치에 맞는 NX-OS 버전을 다운로드하십시오.
. (파일 전송을 위해) 스위치를 관리 네트워크에 연결하십시오.
. ping 명령어를 사용하여 NX-OS를 호스팅하는 서버에 대한 연결 상태를 확인하십시오.
+
`ping <IP address>`

+
.예를 보여주세요
[%collapsible]
====
이 예제에서는 스위치가 IP 주소 172.19.2.1의 서버에 도달할 수 있는지 확인합니다.

[listing, subs="+quotes"]
----
cs1# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====




[[step-2-install-the-nx-os]]
== 2단계: NX-OS 설치

NX-OS를 설치하려면 먼저 첫 번째 스위치(cs1)에 NX-OS 버전을 설치 및 확인하고, EPLD 이미지를 업그레이드 및 확인합니다. 그런 다음 새 AFX 시스템 설치의 일부로 NX-OS를 설치하는 경우 두 번째 스위치(cs2)에서 이러한 단계를 반복합니다.

. NX-OS 및 EPLD 이미지를 첫 번째 스위치에 복사합니다.
+
이 명령은 두 번 사용합니다. 첫 번째는 NX-OS 버전을 복사하는 데 사용하고, 두 번째는 EPLD 버전을 복사하는 데 사용합니다.

+
`copy <protocol>: bootflash: vrf management`

+
.예를 보여주세요
[%collapsible]
====
이 예제에서는 SFTP를 사용합니다.

[listing, subs="+quotes"]
----
cs1# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos.10.4.2.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *root*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
root@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/nxos.10.4.2.bin  /bootflash/nxos.10.4.2.bin
/code/nxos.10.4.2.bin  100% 1261MB   9.3MB/s   02:15
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.

cs1# *copy sftp: bootflash: vrf management*
Enter source filename: */code/n9000-epld.10.4.2.F.img*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/n9000-epld.10.4.2.F.img  /bootflash/n9000-epld.10.4.2.F.img
/code/n9000-epld.10.4.2.F.img  100%  161MB   9.5MB/s   00:16
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. NX-OS의 실행 중인 버전을 확인하십시오.
+
`show version`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.4(1) [Feature Release]
  Host NXOS: version 10.4(1)
  BIOS compile time:  11/25/2024
  NXOS image file is: bootflash:///nxos64-cs.10.4.1.F.bin
  NXOS compile time:  11/30/2023 12:00:00 [12/14/2023 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco Nexus9000 C9332D-GX2B Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLMXXXXXXXX
  Device name: cs2
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Jun  5 15:55:08 2025
  Reason: Reset Requested by CLI command reload
  System version: 10.4(1)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):

cs1#
----
====
. NX-OS 이미지를 설치합니다.
+
이미지 파일을 설치하면 스위치를 재부팅할 때마다 이미지 파일이 로드됩니다.

+
`install all nxos bootflash:nxos.<version number>.bin`

+
.예를 보여주세요
[%collapsible]
====
이 예제에서는 NX-OS 버전 10.4.2를 사용합니다.

[listing, subs="+quotes"]
----
cs1# *install all nxos bootflash:nxos.10.4.2.bin*

Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.10.4.2.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.10.4.2.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.10.4.2.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  Bootable  Impact          Install-type  Reason
------  --------  --------------- ------------  ---------
  1     yes       Disruptive      Reset         Default upgrade is not hitless



Images will be upgraded according to following table:

Module   Image    Running-Version(pri:alt)                 New-Version         Upg-Required
------- --------- ---------------------------------------- ------------------- ------------
  1      nxos     10.4(1)                                  10.4(2)             Yes
  1      bios     xx.xx.:xx.xx                             xxx                 No


Switch will be reloaded for disruptive upgrade.

Do you want to continue with the installation (y/n)? [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS

Finishing the upgrade, switch will reboot in 10 seconds.
----
====
. 스위치가 재부팅된 후 NX-OS의 새 버전을 확인하십시오.
+
`show version`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2025, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.


Software
  BIOS: version 01.14
  NXOS: version 10.4(2) [Feature Release]
  Host NXOS: version 10.4(2)
  BIOS compile time:  11/25/2024
  NXOS image file is: bootflash:///nxos64-cs.10.4.2.F.bin
  NXOS compile time:  11/30/2023 12:00:00 [12/14/2023 05:25:50]
  NXOS boot mode: LXC


Hardware
  cisco Nexus9000 C9332D-GX2B Chassis
  Intel(R) Xeon(R) CPU D-1633N @ 2.50GHz with 32802156 kB of memory.
  Processor Board ID FLMXXXXXXXX
  Device name: cs1
  bootflash:  115802886 kB


Kernel uptime is 5 day(s), 2 hour(s), 13 minute(s), 21 second(s)


Last reset at 3580 usecs after Thu Jun  5 15:55:08 2025
  Reason: Reset Requested by CLI command reload
  System version: 10.4(2)
  Service:


plugin
  Core Plugin, Ethernet Plugin


Active Package(s):

cs1#
----
====
. 다음 명령어를 사용하여 EPLD 이미지를 업그레이드하십시오.
+
`show version module 1 epld`

+
`install epld bootflash:n9000-epld.<version>.img module all`

+
마지막 명령이 실행된 후 스위치가 재부팅됩니다.

+
.예를 보여주세요
[%collapsible]
====
이 예제에서는 EPLD 버전 10.4.2.F를 사용합니다.

[listing, subs="+quotes"]
----
cs1# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI   FPGA                        0x7
IO   FPGA                        0x17
MI   FPGA2                       0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2

cs1# *install epld bootflash:n9000-epld.10.4.2.F.img module all*
Compatibility check:
Module        Type         Upgradable        Impact    Reason
------  ------------------ ----------------- --------- -----------
     1         SUP         Yes       disruptive  Module Upgradable

Retrieving EPLD versions.... Please wait.
Images will be upgraded according to following table:
Module  Type   EPLD              Running-Version   New-Version  Upg-Required
------- ------ ----------------- ----------------- ------------ ------------
     1  SUP    MI FPGA           0x07              0x07         No
     1  SUP    IO FPGA           0x17              0x19         Yes
     1  SUP    MI FPGA2          0x02              0x02         No
The above modules require upgrade.
The switch will be reloaded at the end of the upgrade
Do you want to continue (y/n) ?  [n] *y*

Proceeding to upgrade Modules.

Starting Module 1 EPLD Upgrade

Module 1 : IO FPGA [Programming] : 100.00% (     64 of      64 sectors)
Module 1 EPLD upgrade is successful.
Module   Type  Upgrade-Result
-------- ----- --------------
     1   SUP   Success

EPLDs upgraded.

Module 1 EPLD upgrade is successful.
----
====
. 스위치를 재부팅한 후 로그인하여 새 버전의 EPLD가 성공적으로 로드되었는지 확인하십시오.
+
`show version module 1 epld`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cs1# *show version module 1 epld*

EPLD Device                     Version
---------------------------------------
MI   FPGA                        0x7
IO   FPGA                        0x19
MI   FPGA2                       0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
----
====
. 새로운 AFX 시스템 설치의 일부로 NX-OS를 설치하는 경우, 스위치 cs2에 NX-OS 및 EPLD 이미지를 설치하려면 다음 단계를 반복하십시오.


.다음은 무엇인가요?
스위치에 NX-OS를 설치한 후에는 link:configure-install-upgrade-rcf-overview-9332d.html["RCF 설치 또는 업그레이드 개요"]부터 시작하여 RCF를 설치합니다.
