---
permalink: switch-cisco-9332d-gx2b/install-upgrade-rcf-overview-cluster.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 9332d-gx2b 
summary: Nexus 9332D-GX2B 스위치를 처음 설정한 후 RCF를 설치할 수 있습니다. 이 절차를 사용하여 RCF 버전을 업그레이드할 수도 있습니다. 
---
= RCF(Reference Configuration File) 개요를 설치 또는 업그레이드합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nexus 9332D-GX2B 스위치를 처음 설정한 후 참조 구성 파일(RCF)을 설치합니다. 스위치에 기존 RCF 파일 버전이 설치되어 있는 경우 RCF 버전을 업그레이드합니다.

RCF를 설치하거나 업그레이드할 때 자세한 내용은 기술 자료 문서를 link:https://kb.netapp.com/on-prem/Switches/Cisco-KBs/How_to_clear_configuration_on_a_Cisco_interconnect_switch_while_retaining_remote_connectivity["원격 연결을 유지하면서 Cisco 상호 연결 스위치의 구성을 지우는 방법"^]참조하십시오.

.사용 가능한 RCF 구성
* *클러스터-HA-스토리지* - 포트(NX9332D-GX2B-RCF-v10.0-Shared.txt)에서 공유 클러스터/HA/스토리지 트래픽을 지원합니다.


특정 포트 및 VLAN 사용에 대한 자세한 내용은 RCF의 배너 및 중요 참고 사항 섹션을 참조하십시오.

.추천 문서
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치(NSS)"^]
+
NetApp Support 사이트에서 지원되는 ONTAP 및 RCF 버전은 스위치 호환성 표를 참조하십시오. RCF의 명령 구문과 특정 버전의 NX-OS에 있는 구문 사이에 명령 종속성이 있을 수 있습니다.

* link:https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html["Cisco Nexus 9000 시리즈 스위치"^]
+
Cisco 스위치 업그레이드 및 다운그레이드 절차에 대한 자세한 내용은 Cisco 웹 사이트에 있는 해당 소프트웨어 및 업그레이드 가이드를 참조하십시오.



.예를 참조하십시오
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 두 Cisco 스위치의 이름은 CS1과 CS2입니다.
* 노드 이름은 node1-01, node1-02, node1-03, node1-04입니다.
* 클러스터 LIF 이름은 node1-01_clus1, node1-01_clus2, node1-02_clus1, node1-02_clus2, node1-03_clus1, node1-03_clus2, node1-04_clus1 및 node1-04_clus2입니다.
* 'cluster1:: *>' 프롬프트는 클러스터의 이름을 나타냅니다.


를 참조하십시오 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] 플랫폼에서 올바른 포트를 확인하세요.


NOTE: 명령 출력은 ONTAP의 릴리즈별로 다를 수 있습니다.

.사용된 명령
이 절차를 수행하려면 ONTAP 명령과 Cisco Nexus 9000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 표시되지 않는 한 ONTAP 명령이 사용됩니다.

.다음 단계
RCF 설치 또는 RCF 업그레이드 절차를 검토한 후link:install-rcf-software-9332d-cluster.html["RCF를 설치하다"] 또는link:upgrade-rcf-software-9332d-cluster.html["RCF를 업그레이드하세요"] 필요에 따라.
