---
permalink: switch-cisco-9332d-gx2b/install-switches-9332d.html 
sidebar: sidebar 
keywords: switches, hardware installation, Cisco Nexus, 9332D-GX2B switches 
summary: 새로운 AFX 1K 또는 AFX 2K 시스템 설치의 일부로 Cisco Nexus 9332D-GX2B 스위치를 설치하는 과정에는 스위치를 랙이나 캐비닛에 설치하고, 시스템 컨트롤러 및 셸프에 케이블을 연결한 다음 전원을 켜는 작업이 포함됩니다. 
---
= Cisco Nexus 9332D-GX2B 스위치 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새로운 AFX 1K 또는 AFX 2K 시스템 설치의 일부로 Cisco Nexus 9332D-GX2B 스위치를 설치하는 과정에는 스위치를 랙이나 캐비닛에 설치하고, 시스템 컨트롤러 및 셸프에 케이블을 연결한 다음 전원을 켜는 작업이 포함됩니다.

.시작하기 전에
스위치 준비 단계를 완료해야 합니다 link:install-prepare-9332d.html["스위치 설치 준비"].

.이 작업에 관하여
AFX 시스템 설명서 사이트에 있는 해당 AFX 1K 또는 AFX 2K 시스템 설치 및 설정 워크플로를 사용하여 시스템 하드웨어를 설치 및 케이블 연결하고 스위치의 전원을 켜십시오.

시스템 설치 및 설정 워크플로에는 다음과 같은 지침이 포함됩니다.

* 사이트 준비, 상자 풀기, 상자 내용물과 포장 명세서 비교, 지원 혜택을 받기 위한 시스템 등록에 대한 지침입니다.
* NetApp 캐비닛 또는 통신 랙에 스위치, 컨트롤러 및 스토리지 셸프를 설치하는 방법에 대한 지침입니다.
* 컨트롤러와 스위치 연결부, 스토리지 셸프와 스위치 연결부를 포함한 시스템 케이블 연결 방법에 대한 지침입니다.


.단계
. AFX 1K 또는 AFX 2K 시스템 설치 및 설정 워크플로의 일부로 스위치를 설치하십시오.
+
** AFX 1K 시스템의 경우 link:https://docs.netapp.com/us-en/ontap-afx/install-setup/install-setup-workflow.html["AFX 1K 설치 및 설정 워크플로"^]로 이동하십시오.
** AFX 2K 시스템의 경우 link:https://docs.netapp.com/us-en/ontap-afx/install-afx-2k/install-setup-workflow.html["AFX 2K 설치 및 설정 워크플로"^]로 이동하십시오.





NOTE: 스위치를 설치한 후에는 AFX 설치 및 설정 워크플로 지침에 따라 스위치를 구성하기 위해 이 스위치 설명서로 다시 이동하게 됩니다.

.다음은 무엇인가요?
AFX 1K 또는 AFX 2K 시스템 설치의 일부로 스위치를 설치, 케이블 연결 및 전원을 켠 후 link:install-configure-switches-in-afx-workflow-9332d.html#configure-switches["스위치를 구성합니다"] 한 다음 link:install-configure-switches-in-afx-workflow-9332d.html#complete-afx-system-setup["AFX 시스템 설정을 완료합니다"].
