---
permalink: switch-cisco-9332d-gx2b/setup-switch-9332d-cluster.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9332d-gx2b 
summary: Cisco Nexus 9332D-GX2B 스위치를 구성하려면 다음 절차를 따르세요. 
---
= 9332D-GX2B 스위치 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9332D-GX2B 스위치를 구성하려면 다음 절차를 따르세요.

.시작하기 전에
다음 사항을 확인하세요.

* 스위치를 켰습니다.
* 설치 사이트의 HTTP, FTP 또는 TFTP 서버에 액세스하여 해당 NX-OS 및 참조 구성 파일(RCF) 릴리스를 다운로드합니다.
* 적용 가능한 NX-OS 버전은 다음에서 다운로드합니다. https://software.cisco.com/download/home["Cisco 소프트웨어 다운로드"^] 페이지.


[IMPORTANT]
====
* NX-OS 10.4.2는 ONTAP 클러스터의 Cisco Nexus 9332D-GX2B 스위치에서 지원되는 유일한 버전입니다.
* NX-OS 버전을 지원되지 않는 버전으로 업그레이드하거나 다운그레이드하지 마세요. 현재는 10.4.2만 지원됩니다.


====
* 적용 가능한 라이센스, 네트워크 및 구성 정보, 케이블.
* NetApp 지원 사이트에서 다운로드한 적용 가능한 NetApp 공유 네트워크 및 관리 네트워크 RCF http://mysupport.netapp.com/["mysupport.netapp.com"^] . 모든 Cisco 공유 네트워크 및 관리 네트워크 스위치는 표준 Cisco 공장 기본 구성으로 제공됩니다. 이러한 스위치에도 최신 버전의 NX-OS 소프트웨어가 있지만 RCF가 로드되어 있지 않습니다.
* link:required-documentation-9332d-cluster.html["필수 스위치 및 ONTAP 문서"].


.단계
. 공유 네트워크 스위치의 초기 구성을 수행합니다.
+
스위치를 처음 부팅할 때 다음 초기 설정 질문에 적절한 답변을 제공하세요.  사이트의 보안 정책은 활성화할 응답과 서비스를 정의합니다.

+
[cols="1,2"]
|===
| 즉각적인 | 응답 


 a| 
자동 프로비저닝을 중단하고 일반 설정을 계속하시겠습니까?  (예/아니요)
 a| 
*예*라고 대답하세요.  기본값은 아니요입니다.



 a| 
안전한 비밀번호 표준을 시행하고 싶으신가요?  (예/아니요)
 a| 
*예*라고 대답하세요.  기본값은 '예'입니다.



 a| 
관리자 비밀번호를 입력하세요.
 a| 
기본 비밀번호는 "`admin`"입니다. 새롭고 강력한 비밀번호를 만들어야 합니다.  약한 비밀번호는 거부될 수 있습니다.



 a| 
기본 구성 대화 상자를 표시하시겠습니까?  (예/아니요)
 a| 
스위치의 초기 구성에서 *예*로 응답합니다.



 a| 
다른 로그인 계정을 만드시겠습니까?  (예/아니요)
 a| 
귀하의 답변은 대체 관리자에 대한 귀하 사이트의 정책에 따라 달라집니다.  기본값은 *아니요*입니다.



 a| 
읽기 전용 SNMP 커뮤니티 문자열을 구성하시겠습니까?  (예/아니요)
 a| 
*아니요*라고 대답하세요.  기본값은 아니요입니다.



 a| 
읽기-쓰기 SNMP 커뮤니티 문자열을 구성하시겠습니까?  (예/아니요)
 a| 
*아니요*라고 대답하세요.  기본값은 아니요입니다.



 a| 
스위치 이름을 입력하세요.
 a| 
최대 63자의 영숫자로 구성된 스위치 이름을 입력하세요.



 a| 
대역외(mgmt0) 관리 구성을 계속하시겠습니까?  (예/아니요)
 a| 
해당 프롬프트에서 *예* (기본값)로 응답합니다.  mgmt0 IPv4 주소: 프롬프트에서 IP 주소 ip_address를 입력합니다.



 a| 
기본 게이트웨이를 구성하시겠습니까?  (예/아니요)
 a| 
*예*라고 대답하세요.  default-gateway: 프롬프트의 IPv4 주소에 default_gateway를 입력합니다.



 a| 
고급 IP 옵션을 구성하시겠습니까?  (예/아니요)
 a| 
*아니요*라고 대답하세요.  기본값은 아니요입니다.



 a| 
Telnet 서비스를 활성화하시겠습니까?  (예/아니요)
 a| 
*아니요*라고 대답하세요.  기본값은 아니요입니다.



 a| 
SSH 서비스를 활성화하셨나요?  (예/아니요)
 a| 
*예*라고 대답하세요.  기본값은 '예'입니다.


NOTE: CSHM(Ethernet Switch Health Monitor)의 로그 수집 기능을 사용할 경우 SSH를 사용하는 것이 좋습니다.  보안 강화를 위해 SSHv2도 권장됩니다.



 a| 
생성하려는 SSH 키 유형(dsa/rsa/rsa1)을 입력합니다.
 a| 
기본값은 *rsa*입니다.



 a| 
키 비트 수(1024-2048)를 입력하세요.
 a| 
1024에서 2048까지 키 비트 수를 입력하세요.



 a| 
NTP 서버를 구성하시겠습니까?  (예/아니요)
 a| 
*아니요*라고 대답하세요.  기본값은 아니요입니다.



 a| 
기본 인터페이스 계층(L3/L2) 구성
 a| 
*L2*로 응답하세요.  기본값은 L2입니다.



 a| 
기본 스위치 포트 인터페이스 상태(shut/noshut) 구성
 a| 
*안 돼*라고 대답하세요.  기본값은 noshut입니다.



 a| 
CoPP 시스템 프로필 구성(엄격/중간/관대/고밀도)
 a| 
*엄격하게* 대응하세요.  기본값은 엄격합니다.



 a| 
구성을 편집하시겠습니까?  (예/아니요)
 a| 
이 시점에서 새로운 구성을 볼 수 있습니다.  방금 입력한 구성을 검토하고 필요한 변경 사항을 적용합니다.  구성에 만족하는 경우 프롬프트에서 *아니요*로 응답하세요.  구성 설정을 편집하려면 *예*로 응답하세요.



 a| 
이 구성을 사용하고 저장하시겠습니까?  (예/아니요)
 a| 
구성을 저장하려면 *예*로 응답하세요.  이렇게 하면 킥스타트와 시스템 이미지가 자동으로 업데이트됩니다.


NOTE: 이 단계에서 구성을 저장하지 않으면 다음에 스위치를 재부팅할 때 변경 사항이 적용되지 않습니다.

|===
. 설치가 끝나면 나타나는 화면에서 선택한 구성을 확인하고, 구성을 저장하세요.
. 공유 네트워크 스위치의 버전을 확인하고 필요한 경우 스위치에서 NetApp 지원 버전의 소프트웨어를 다운로드합니다. https://software.cisco.com/download/home["Cisco 소프트웨어 다운로드"^] 페이지.


.다음은 무엇인가요?
스위치를 구성한 후에는 link:install-nxos-overview-9332d-cluster.html["NX-OS 소프트웨어와 RCF 설치를 준비합니다"].
