---
permalink: switch-cisco-9336c-fx2/configure-software-overview-9336c-cluster.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Cisco Nexus 9336C-FX2 클러스터 스위치의 소프트웨어 구성 개요 
---
= Cisco Nexus 9336C-FX2 클러스터 스위치용 소프트웨어 설치 워크플로우
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9336C-FX2 스위치용 소프트웨어를 설치 및 구성하고 RCF(Reference Configuration File)를 설치 또는 업그레이드하려면 다음 단계를 수행하십시오.

. link:install-nxos-overview-9336c-cluster.html["NX-OS 소프트웨어 및 RCF 설치 준비"].
. link:install-nxos-software-9336c-cluster.html["NX-OS 소프트웨어를 설치합니다"].
. link:install-nxos-rcf-9336c-cluster.html["RCF(Reference Configuration File) 설치 또는 업그레이드"].
+
Nexus 9336C-FX2 스위치를 처음 설정한 후 RCF를 설치합니다. 이 절차를 사용하여 RCF 버전을 업그레이드할 수도 있습니다.

+
.사용 가능한 RCF 구성
다음 표에서는 다양한 구성에 사용할 수 있는 RCF에 대해 설명합니다. 구성에 적용할 RCF를 선택합니다.

+
특정 포트 및 VLAN 사용에 대한 자세한 내용은 RCF의 배너 및 중요 참고 사항 섹션을 참조하십시오.

+
[cols="1,2"]
|===
| RCF 이름입니다 | 설명 


 a| 
2-클러스터-HA-브레이크아웃
 a| 
공유 클러스터 + HA 포트를 사용하는 노드를 포함하여 8개 이상의 노드로 구성된 ONTAP 클러스터 2개를 지원합니다.



 a| 
4-클러스터-HA-브레이크아웃
 a| 
공유 클러스터 + HA 포트를 사용하는 노드를 포함하여 4개 이상의 노드로 구성된 ONTAP 클러스터 4개를 지원합니다.



 a| 
1-클러스터-HA
 a| 
모든 포트는 40/100GbE용으로 구성됩니다. 포트에서 공유 클러스터/HA 트래픽을 지원합니다. AFF A320, AFF A250 및 FAS500f 시스템에 필요 또한 모든 포트를 전용 클러스터 포트로 사용할 수 있습니다.



 a| 
1-클러스터-HA-브레이크아웃
 a| 
포트는 4x10GbE 브레이크아웃, 4x25GbE 브레이크아웃(100GbE 스위치의 RCF 1.6 이상) 및 40/100GbE용으로 구성됩니다. 공유 클러스터/HA 포트를 사용하는 AFF A320, AFF A250 및 FAS500f 시스템과 같은 노드를 위해 포트에서 공유 클러스터/HA 트래픽을 지원합니다. 또한 모든 포트를 전용 클러스터 포트로 사용할 수 있습니다.



 a| 
Cluster-HA-스토리지
 a| 
포트는 클러스터 + HA의 경우 40/100GbE용으로, 클러스터용 4x10GbE 브레이크아웃, 클러스터 + HA의 경우 4x25GbE 브레이크아웃, 각 스토리지 HA 쌍에 대해 100GbE용으로 구성됩니다.



 a| 
클러스터
 a| 
4x10GbE 포트(브레이크아웃)와 40/100GbE 포트를 서로 다른 두 가지 유형의 RCF AFF A320, AFF A250 및 FAS500f 시스템을 제외한 모든 FAS/AFF 노드가 지원됩니다.



 a| 
스토리지
 a| 
모든 포트는 100GbE NVMe 스토리지 연결용으로 구성됩니다.

|===

