---
permalink: switch-cisco-9336c-fx2/configure-switch-overview-9336c-cluster.html 
sidebar: sidebar 
keywords: BES-53248 switches, initial installation, configure switch-cisco-9336c-fx2 switch 
summary: Cisco Nexus 9336C-FX2 클러스터 스위치의 설치 및 구성 개요 
---
= Cisco Nexus 9336C-FX2 클러스터 스위치의 설치 및 구성 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 9336C-FX2 클러스터 스위치는 Cisco Nexus 9000 플랫폼의 일부이며 NetApp 시스템 캐비닛에 설치할 수 있습니다. 클러스터 스위치를 사용하면 2개 이상의 노드로 ONTAP 클러스터를 구축할 수 있습니다.



== 초기 구성 개요

ONTAP를 실행하는 시스템에서 Cisco Nexus 9336C-FX2 스위치를 처음 구성하려면 다음 단계를 수행하십시오.

. link:setup-worksheet-9336c-cluster.html["Cisco Nexus 9336C-FX2 케이블링 워크시트를 작성하십시오"]..
+
샘플 케이블 연결 워크시트는 스위치에서 컨트롤러까지 권장되는 포트 할당의 예를 제공합니다. 빈 워크시트에는 클러스터 설정에 사용할 수 있는 템플릿이 제공됩니다.

. link:install-switch-9336c-cluster.html["스위치를 장착하십시오"]..
+
스위치 하드웨어를 설정합니다.

. link:setup-switch-9336c-cluster.html["9336C-FX2 클러스터 스위치를 구성합니다"]..
+
Cisco Nexus 9336C-FX2 스위치를 설정합니다.

. link:install-switch-and-passthrough-panel-9336c-cluster.html["NetApp 캐비닛에 Cisco Nexus 9336C-FX2 스위치를 설치합니다"]..
+
구성에 따라 Cisco Nexus 9336C-FX2 스위치 및 패스스루 패널을 스위치에 포함된 표준 브래킷과 함께 NetApp 캐비닛에 설치할 수 있습니다.

. link:install-nxos-overview-9336c-cluster.html["NX-OS 소프트웨어 및 RCF 설치를 준비합니다"]..
+
Cisco NX-OS 소프트웨어 설치 및 RCFs(Reference Configuration File)에 대한 사전 절차를 따르십시오.

. link:install-nxos-software-9336c-cluster.html["NX-OS 소프트웨어를 설치 또는 업그레이드합니다"]..
+
Nexus 9336C-FX2 클러스터 스위치에 NX-OS 소프트웨어를 설치 또는 업그레이드합니다.

. link:install-nxos-rcf-9336c-cluster.html["RCF를 설치하거나 업그레이드합니다"]..
+
Nexus 9336C-FX2 스위치를 처음 설정한 후 RCF를 설치하거나 업그레이드합니다. 이 절차를 사용하여 RCF 버전을 업그레이드할 수도 있습니다.

. link:configure-ssh.html["Nexus 9336C-FX2 클러스터 스위치에서 SSH를 사용하도록 설정합니다"]..
+
이더넷 스위치 상태 모니터(CSHM) 및 로그 수집 기능을 사용하는 경우 스위치에서 SSH를 사용하도록 설정합니다.





== 추가 정보

설치 또는 유지 관리를 시작하기 전에 다음을 검토하십시오.

* link:configure-reqs-9336c-cluster.html["구성 요구 사항"]
* link:components-9336c-cluster.html["부품 및 부품 번호"]
* link:required-documentation-9336c-cluster.html["필수 문서"]
* link:smart-call-9336c-cluster.html["Smart Call Home 요구 사항"]

