---
permalink: switch-cisco-9336c-fx2/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, nexus, ontap, install the cluster switch health monitor (csm) configuration file for 92300yc switches - cisco nexus 9336c-fx2' 
summary: 이 절차를 사용하여 Nexus 92300YC 클러스터 스위치의 클러스터 스위치 상태 모니터링에 해당하는 구성 파일을 설치할 수 있습니다. 
---
= 클러스터 SHM(Switch Health Monitor) 구성 파일을 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 절차에 따라 Nexus 9336C-FX2 클러스터 스위치의 SHM(클러스터 스위치 상태 모니터링)에 해당하는 구성 파일을 설치하십시오.

.필요한 것
9336C-FX2 클러스터 스위치용 SHM을 설정하기 전에 ONTAP 클러스터가 작동 중이고 실행 중인지 확인하십시오.


NOTE: SHM에서 사용할 수 있는 모든 기능을 사용하려면 SSH를 활성화해야 합니다.

.단계
. 해당 ONTAP 릴리스 버전을 기준으로 클러스터 SHM 구성 zip 파일을 다운로드합니다. 이 파일은 에서 사용할 수 있습니다 https://mysupport.netapp.com/NOW/cgi-bin/software/["NetApp 소프트웨어 다운로드"^] 페이지.
+
.. 소프트웨어 다운로드 페이지에서 * 상태 모니터 구성 파일 전환 * 을 선택합니다
.. Platform = * ONTAP * 를 선택하고 * Go! * 를 선택합니다
.. ONTAP용 상태 모니터 구성 파일 전환 페이지에서 * 보기 및 다운로드 * 를 선택합니다
.. ONTAP용 스위치 상태 모니터 구성 파일 > 설명 페이지에서 해당 클러스터 스위치 모델에 대해 * 다운로드 * 를 선택합니다(예: * Cisco Nexus 9336C-FX2 *)
.. 최종 사용자 사용권 계약 페이지에서 * 동의 * 를 선택합니다
.. ONTAP용 스위치 상태 모니터 구성 파일 > 다운로드 페이지에서 해당 구성 파일(예: * Cisco_Nexus_9336C-FX2.zip *)을 선택합니다


. 해당 zip 파일을 내부 웹 서버에 업로드하면 IP 주소가 x.x.x.x 입니다
+
내부 웹 서버 IP 주소 192.168.2.20의 경우 /usr/download 디렉토리가 있다고 가정하면 SCP를 사용하여 zip 파일을 웹 서버에 업로드할 수 있습니다.

+
[listing]
----
% scp Cisco_Nexus_9336C-FX2.zip admin@192.168.2.20:/usr/download/Cisco_Nexus_9336C-FX2.zip
----
. 클러스터의 ONTAP 시스템 중 하나에서 고급 모드 설정에 액세스합니다.
+
`set-privilege advanced`

+
[listing]
----
cluster1::> set -privilege advanced
----
. switch 상태 monitor configure 명령을 실행합니다 `system cluster-switch configure-health-monitor -node * -package-url X.X.X.X/location_to_download_zip_file`:
+
[listing]
----
cluster1::> system cluster-switch configure-health-monitor -node * -package-url 192.168.2.20/usr/download/Cisco_Nexus_9336C-FX2.zip
----
. 명령 출력에 "downloaded package processed successfully" 텍스트 문자열이 포함되어 있는지 확인합니다. 오류가 발생하면 NetApp 지원 팀에 문의하십시오.
. 명령을 실행합니다 `system cluster-switch show` ONTAP 시스템에서 모니터링되는 필드가 "True"로 설정된 상태에서 클러스터 스위치가 검색되는지 확인합니다.
+
[listing]
----
cluster1::> system cluster-switch show
----
+

NOTE: 언제든지 이전 버전의 ONTAP로 되돌릴 경우 SHM 구성 파일을 다시 설치하여 9336C-FX2 클러스터 스위치의 SHM을 활성화해야 합니다.


