---
permalink: switch-cisco-9336c-fx2/setup-switch-9336c-cluster.html 
sidebar: sidebar 
keywords: require, configuration, information, documentation, cluster, management, network, switches, set up the switches - cisco nexus 9336c-fx2 
summary: 다음 절차에 따라 Cisco Nexus 9336C-FX2 스위치를 설정하고 구성합니다. 
---
= 9336C-FX2 클러스터 스위치를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 절차에 따라 Cisco Nexus 9336C-FX2 스위치를 구성합니다.

.필요한 것
* 설치 사이트에서 HTTP, FTP 또는 TFTP 서버에 액세스하여 해당 NX-OS 및 RCF(Reference Configuration File) 릴리즈를 다운로드합니다.
* 관련 라이센스, 네트워크 및 구성 정보, 케이블.
* 완료되었습니다 link:setup-worksheet-9336c-cluster.html["케이블 연결 워크시트"].
* 해당 NetApp 클러스터 네트워크 및 관리 네트워크 RCFs는 NetApp Support 사이트 에서 다운로드할 수 있습니다 http://mysupport.netapp.com/["mysupport.netapp.com"^]. 모든 Cisco 클러스터 네트워크 및 관리 네트워크 스위치는 표준 Cisco 공장 출하시 기본 구성으로 제공됩니다. 이러한 스위치에는 최신 버전의 NX-OS 소프트웨어도 있지만 RCFs가 로드되지 않았습니다.
* link:required-documentation-9336c-cluster.html["필수 스위치 및 ONTAP 문서"].


.단계
. 클러스터 네트워크 스위치의 초기 구성을 수행합니다.
+
스위치를 처음 부팅할 때 다음과 같은 초기 설정 질문에 대해 적절한 응답을 제공합니다. 사이트의 보안 정책은 사용할 응답 및 서비스를 정의합니다.

+
[cols="1,2"]
|===
| 메시지가 표시됩니다 | 응답 


 a| 
자동 프로비저닝을 중단하고 일반 설정으로 계속하시겠습니까? (예/아니요)
 a| 
yes * 로 응답합니다. 기본값은 no 입니다



 a| 
보안 암호 표준을 적용하시겠습니까? (예/아니요)
 a| 
yes * 로 응답합니다. 기본값은 yes입니다.



 a| 
admin의 암호를 입력합니다.
 a| 
기본 암호는 ""admin""이며 강력한 새 암호를 만들어야 합니다. 약한 암호는 거부될 수 있습니다.



 a| 
기본 구성 대화 상자를 입력하시겠습니까? (예/아니요)
 a| 
스위치의 초기 구성에서 * yes * 로 응답합니다.



 a| 
다른 로그인 계정을 만드시겠습니까? (예/아니요)
 a| 
대체 관리자에 대한 사이트 정책에 따라 답이 달라집니다. 기본값은 * no * 입니다.



 a| 
읽기 전용 SNMP 커뮤니티 문자열을 구성하시겠습니까? (예/아니요)
 a| 
응답 * 없음 *. 기본값은 no 입니다



 a| 
읽기-쓰기 SNMP 커뮤니티 문자열을 구성하시겠습니까? (예/아니요)
 a| 
응답 * 없음 *. 기본값은 no 입니다



 a| 
스위치 이름을 입력합니다.
 a| 
63자의 영숫자로 제한되는 스위치 이름을 입력합니다.



 a| 
대역 외(mgmt0) 관리 구성을 계속하시겠습니까? (예/아니요)
 a| 
이 프롬프트에서 * yes * (기본값)로 응답합니다. mgmt0 IPv4 주소: 프롬프트에서 IP 주소:ip_address를 입력합니다.



 a| 
기본 게이트웨이를 구성하시겠습니까? (예/아니요)
 a| 
yes * 로 응답합니다. default-gateway: 프롬프트의 IPv4 주소에 default_gateway를 입력합니다.



 a| 
고급 IP 옵션을 구성하시겠습니까? (예/아니요)
 a| 
응답 * 없음 *. 기본값은 no 입니다



 a| 
텔넷 서비스를 활성화하시겠습니까? (예/아니요)
 a| 
응답 * 없음 *. 기본값은 no 입니다



 a| 
SSH 서비스를 활성화했습니까? (예/아니요)
 a| 
yes * 로 응답합니다. 기본값은 yes입니다.


NOTE: CSHM(Cluster Switch Health Monitor)을 로그 수집 기능에 사용할 때는 SSH를 사용하는 것이 좋습니다. SSHv2는 향상된 보안에도 권장됩니다.



 a| 
생성하려는 SSH 키 유형(DSA/RSA/rsa1)을 입력합니다.
 a| 
기본값은 * RSA * 입니다.



 a| 
키 비트 수(1024 - 2048)를 입력합니다.
 a| 
1024에서 2048까지의 키 비트 수를 입력합니다.



 a| 
NTP 서버를 구성하시겠습니까? (예/아니요)
 a| 
응답 * 없음 *. 기본값은 no 입니다



 a| 
기본 인터페이스 계층 구성(L3/L2)
 a| 
L2 * 로 응답합니다. 기본값은 L2입니다.



 a| 
기본 스위치 포트 인터페이스 상태 구성(종료/종료)
 a| 
응답: * NOshut *. 기본값은 noshut 입니다.



 a| 
CoPP 시스템 프로필 구성(엄격한/보통/관대함/조밀함)
 a| 
엄격한 * 으로 응답합니다. 기본값은 strict 입니다.



 a| 
구성을 편집하시겠습니까? (예/아니요)
 a| 
이제 새 구성이 표시됩니다. 방금 입력한 구성을 검토하고 필요에 따라 변경합니다. 구성에 만족하면 프롬프트에 * NO * 로 응답합니다. 구성 설정을 편집하려면 * 예 * 로 응답하십시오.



 a| 
이 구성을 사용하여 저장하시겠습니까? (예/아니요)
 a| 
구성을 저장하려면 * yes * 로 응답합니다. 그러면 킥스타트 및 시스템 이미지가 자동으로 업데이트됩니다.


NOTE: 이 단계에서 구성을 저장하지 않으면 다음에 스위치를 재부팅할 때 변경 내용이 적용되지 않습니다.

|===
. 설정 끝에 나타나는 디스플레이에서 선택한 구성을 확인하고 구성을 저장했는지 확인합니다.
. 클러스터 네트워크 스위치의 버전을 확인하고 필요한 경우 NetApp 지원 소프트웨어 버전을 스위치에 다운로드합니다.
+
NetApp 지원 소프트웨어 버전을 다운로드할 경우 _NetApp 클러스터 네트워크 스위치 참조 구성 파일_을 다운로드하여 5단계에서 저장한 구성과 병합해야 합니다. 에서 파일과 지침을 다운로드할 수 있습니다 https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^] 페이지.

. 네트워크 스위치에서 소프트웨어 버전을 확인하고 필요한 경우 NetApp 지원 소프트웨어 버전을 스위치에 다운로드합니다. 자체 스위치가 있는 경우 을 참조하십시오 https://cisco.com["Cisco 사이트"^].
+
NetApp 지원 소프트웨어 버전을 다운로드할 경우 _NetApp 관리 네트워크 스위치 참조 구성 파일_을 다운로드하여 이전에 저장한 구성과 병합해야 합니다. 에서 파일 및 지침을 다운로드할 수 있습니다 https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^] 페이지.



.다음 단계
필요에 따라 할 수 있습니다 link:install-switch-and-passthrough-panel-9336c-cluster.html["NetApp 캐비닛에 Cisco Nexus 9336C-FX2 스위치를 설치합니다"]. 그렇지 않으면 로 이동합니다 link:install-nxos-overview-9336c-cluster.html["NX-OS 및 RCF 설치 준비"].
