---
permalink: switch-cisco-9336c-fx2/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, nexus, ontap, install the cluster switch health monitor (csm) configuration file for 92300yc switches - cisco nexus 9336c-fx2' 
summary: 이 절차를 사용하여 Nexus 92300YC 클러스터 스위치의 클러스터 스위치 상태 모니터링에 해당하는 구성 파일을 설치할 수 있습니다. ONTAP 릴리즈 9.5P7 및 이전 버전 9.6P2 및 이전 버전에서는 클러스터 스위치 상태 모니터 구성 파일을 별도로 다운로드해야 합니다. ONTAP 릴리즈 9.5P8 이상, 9.6P3 이상 및 9.7 이상에서는 클러스터 스위치 상태 모니터 구성 파일이 ONTAP와 함께 번들로 제공됩니다. 
---
= 92300YC 스위치용 CSHM(Cluster Switch Health Monitor) 구성 파일을 설치합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
이 절차를 사용하여 Nexus 92300YC 클러스터 스위치의 클러스터 스위치 상태 모니터링에 해당하는 구성 파일을 설치할 수 있습니다. ONTAP 릴리즈 9.5P7 및 이전 버전 9.6P2 및 이전 버전에서는 클러스터 스위치 상태 모니터 구성 파일을 별도로 다운로드해야 합니다. ONTAP 릴리즈 9.5P8 이상, 9.6P3 이상 및 9.7 이상에서는 클러스터 스위치 상태 모니터 구성 파일이 ONTAP와 함께 번들로 제공됩니다.

92300YC 클러스터 스위치에 대한 스위치 상태 모니터를 설정하기 전에 ONTAP 클러스터가 작동 중이고 실행 중인지 확인해야 합니다.


NOTE: CSHM에서 사용 가능한 모든 기능을 사용하려면 SSH를 활성화하는 것이 좋습니다.

. 해당 ONTAP 릴리스 버전을 기반으로 클러스터 스위치 상태 모니터 구성 zip 파일을 다운로드합니다. 이 파일은 에서 사용할 수 있습니다 https://mysupport.netapp.com/NOW/cgi-bin/software/["NetApp 소프트웨어 다운로드"^] 페이지.
+
.. 소프트웨어 다운로드 페이지에서 * 상태 모니터 구성 파일 전환 * 을 선택합니다
.. Platform= * ONTAP * 를 선택하고 * Go! * 를 클릭합니다
.. ONTAP용 상태 모니터 구성 파일 전환 페이지에서 * 보기 및 다운로드 * 를 클릭합니다
.. ONTAP용 스위치 상태 모니터 구성 파일 - 설명 페이지에서 해당 클러스터 스위치 모델에 대해 * 다운로드 * 를 클릭합니다(예: * Cisco Nexus 92300YC *)
.. 최종 사용자 사용권 계약 페이지에서 * 동의 * 를 클릭합니다
.. ONTAP용 스위치 상태 모니터 구성 파일 - 다운로드 페이지에서 해당 구성 파일(예: * cisco_nNexus_92300YC.zip *)을 선택합니다


. 해당 zip 파일을 내부 웹 서버에 업로드하면 IP 주소가 x.x.x.x 입니다
+
내부 웹 서버 IP 주소 192.168.2.20의 경우 /usr/download 디렉토리가 있다고 가정하면 SCP를 사용하여 zip 파일을 웹 서버에 업로드할 수 있습니다.

+
[listing]
----
% scp Cisco_Nexus_92300YC.zip admin@192.168.2.20:/usr/download/Cisco_Nexus_92300YC.zip
----
. 고급 명령 set-privilege를 사용하여 클러스터의 ONTAP 시스템 중 하나에서 고급 모드 설정에 액세스합니다.
+
[listing]
----
cluster1::> set -privilege advanced
----
. 스위치 상태 모니터 configure 명령을 실행합니다. system cluster -switch configure -health-monitor -node * -package -url X.X.X/location_to_download_zip_file:
+
[listing]
----
cluster1::> system cluster-switch configure-health-monitor -node * -package-url 192.168.2.20/usr/download/Cisco_Nexus_92300YC.zip
----
. 명령 출력에 "downloaded package processed successfully" 텍스트 문자열이 포함되어 있는지 확인합니다. 오류가 발생하면 NetApp 지원 팀에 문의하십시오.
. ONTAP 시스템에서 system cluster-switch show 명령을 실행하고 모니터링되는 필드가 "True"로 설정된 상태에서 클러스터 스위치가 검색되는지 확인합니다.
+
[listing]
----
cluster1::> system cluster-switch show
----
+

NOTE: 언제든지 이전 버전의 ONTAP로 되돌릴 경우 92300YC 클러스터 스위치의 스위치 상태 모니터링을 활성화하려면 CSHM 구성 파일을 다시 설치해야 합니다.


