---
permalink: switch-bes-53248/configure-efos-software.html 
sidebar: sidebar 
keywords: BES-53248 cluster switches,installing EFOS software 
summary: 'BES-53248 클러스터 스위치에 EFOS(Ethernet Fabric OS) 소프트웨어를 설치하려면 다음 단계를 따르십시오.' 
---
= EFOS 소프트웨어를 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 클러스터 스위치에 EFOS(Ethernet Fabric OS) 소프트웨어를 설치하려면 다음 단계를 따르십시오.

EFOS 소프트웨어에는 이더넷 및 IP 인프라스트럭처 시스템 개발을 위한 고급 네트워킹 기능 및 프로토콜 세트가 포함되어 있습니다. 이 소프트웨어 아키텍처는 철저한 패킷 검사나 분리를 필요로 하는 애플리케이션을 사용하는 모든 네트워크 조직 장치에 적합합니다.



== 설치 준비

.시작하기 전에
* 이 절차는 새 설치에만 적합합니다.
* 에서 클러스터 스위치에 해당하는 Broadcom EFOS 소프트웨어를 다운로드합니다 https://www.broadcom.com/support/bes-switch["Broadcom Ethernet 스위치 지원"^] 사이트.
* 를 확인합니다 link:configure-install-initial.html["BES-53248 클러스터 스위치가 구성되었습니다"].




== 소프트웨어를 설치합니다

다음 방법 중 하나를 사용하여 EFOS 소프트웨어를 설치합니다.

* <<방법 1: EFOS 설치>>. 대부분의 경우에 사용합니다.
* <<방법 2: ONIE 모드로 EFOS를 설치합니다>>. 한 EFOS 버전이 FIPS를 준수하고 다른 EFOS 버전이 FIPS를 준수하지 않는 경우 사용합니다.




=== 방법 1: EFOS 설치

다음 단계를 수행하여 EFOS 소프트웨어를 설치합니다.

.단계
. 스위치 직렬 콘솔 포트에 로그인하거나 SSH로 연결합니다.
. "ping" 명령을 사용하여 EFOS, 라이센스 및 RCF 파일을 호스팅하는 서버에 대한 연결을 확인합니다.
+
.예제 보기
[%collapsible]
====
이 예에서는 스위치가 IP 주소 172.19.2.1로 서버에 연결되어 있는지 확인합니다.

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. 이미지 파일을 스위치에 다운로드합니다.
+
지원되는 복사 프로토콜에 대한 자세한 내용은 다음 표를 참조하십시오.

+
|===


| * 프로토콜 * | * 필수 조건 * 


 a| 
TFTP(Trivial File Transfer Protocol)
 a| 
없음



 a| 
SFTP(SSH 파일 전송 프로토콜)
 a| 
소프트웨어 패키지가 보안 관리를 지원해야 합니다



 a| 
FTP
 a| 
암호가 필요합니다



 a| 
XMODEM
 a| 
없음



 a| 
와이모뎀주식회사
 a| 
없음



 a| 
Zmodem입니다
 a| 
없음



 a| 
SCP(Secure Copy Protocol)
 a| 
소프트웨어 패키지가 보안 관리를 지원해야 합니다



 a| 
HTTP
 a| 
기본 WGET 유틸리티를 사용할 수 있는 경우 선택한 플랫폼에서 CLI 기반 파일 전송이 지원됩니다



 a| 
HTTPS
 a| 
기본 WGET 유틸리티를 사용할 수 있는 경우 선택한 플랫폼에서 CLI 기반 파일 전송이 지원됩니다

|===
+
이미지 파일을 활성 이미지로 복사하는 것은 재부팅할 때 해당 이미지가 실행 중인 EFOS 버전을 설정한다는 것을 의미합니다. 이전 이미지는 백업으로 사용할 수 있습니다.

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1//tmp/EFOS-3.10.0.3.stk active*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.10.0.3.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. 활성 및 백업 구성에 대한 부팅 이미지를 표시합니다.
+
'How bootvar'입니다

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*

Image Descriptions

 active :
 backup :

 Images currently available on Flash
--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------
    1      3.7.0.4     3.7.0.4     3.7.0.4           3.10.0.3
----
====
. 스위치를 재부팅합니다.
+
다시 로드

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
====
. 다시 로그인하여 EFOS 소프트웨어의 새 버전을 확인합니다.
+
'How version'입니다

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show version*

Switch: 1

System Description............................. BES-53248A1, 3.10.0.3, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... BES-53248A1,
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.10.0.3
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
====
. 설치를 완료합니다.
다음 5단계에 따라 스위치를 재구성합니다.
+
.. link:configure-licenses.html["라이센스를 설치합니다"]
.. link:configure-install-rcf.html["RCF 파일을 설치합니다"]
.. link:configure-ssh.html["SSH를 활성화합니다"]
.. link:CSHM_log_collection.html["로그 수집을 활성화합니다"]
.. link:CSHM_snmpv3.html["모니터링을 위한 SNMPv3을 구성합니다"]


. 파트너 스위치에서 1-7단계를 반복합니다.




=== 방법 2: ONIE 모드로 EFOS를 설치합니다

한 EFOS 버전이 FIPS를 준수하고 다른 EFOS 버전이 FIPS를 준수하지 않는 경우 다음 단계를 수행할 수 있습니다. 이러한 단계는 스위치가 부팅되지 않는 경우 ONIE에서 비 FIPS 또는 FIPS 호환 EFOS 3.7.x.x 이미지를 설치하는 데 사용할 수 있습니다.

.단계
. 스위치의 직렬 포트에 연결된 콘솔에 연결합니다.
. 스위치를 ONIE 설치 모드로 부팅합니다.
+
부팅하는 동안 메시지가 표시되면 ONIE를 선택합니다.

+
.예제 보기
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
ONIE * 를 선택하면 스위치가 로드되고 몇 가지 선택 사항이 표시됩니다. OS 설치 * 를 선택합니다.

+
.예제 보기
[%collapsible]
====
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
====
+
스위치가 ONIE 설치 모드로 부팅됩니다.

. ONIE 검색을 중지하고 이더넷 인터페이스를 구성합니다.
+
다음 메시지가 나타나면 * Enter * 를 눌러 ONIE 콘솔을 호출합니다.

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIE 검색이 계속되고 메시지가 콘솔에 인쇄됩니다.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. 스위치 관리 포트의 이더넷 인터페이스를 구성하고 를 사용하여 라우트를 추가합니다 `ifconfig eth0 <ipAddress> netmask <netmask> up` 및 `route add default gw <gatewayAddress>`
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. ONIE 설치 파일을 호스팅하는 서버에 연결할 수 있는지 확인합니다.
+
`ping`

+
.예제 보기
[%collapsible]
====
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
====
. 새 스위치 소프트웨어를 설치합니다.
+
`ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64`

+
.예제 보기
[%collapsible]
====
[listing]
----
ONIE:/ # onie-nos-install http://50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http://50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http://50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
====
+
소프트웨어가 스위치를 설치한 다음 재부팅합니다. 스위치가 새 EFOS 버전으로 정상적으로 재부팅되도록 합니다.

. 로그인하여 새 스위치 소프트웨어가 설치되었는지 확인합니다.
+
'How bootvar'입니다

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
 1      3.7.0.4     3.7.0.4    3.7.0.4        3.10.0.3
(cs2) #
----
====
. 설치를 완료합니다.
스위치는 구성이 적용되지 않은 상태로 재부팅되고 공장 기본값으로 재설정됩니다. 다음 6단계에 따라 스위치를 재구성합니다.
+
.. link:configure-install-initial.html["스위치를 구성합니다"]
.. link:configure-licenses.html["라이센스를 설치합니다"]
.. link:configure-install-rcf.html["RCF 파일을 설치합니다"]
.. link:configure-ssh.html["SSH를 활성화합니다"]
.. link:CSHM_log_collection.html["로그 수집을 활성화합니다"]
.. link:CSHM_snmpv3.html["모니터링을 위한 SNMPv3을 구성합니다"]


. 파트너 스위치에서 1-8단계를 반복합니다.

