---
permalink: switch-bes-53248/configure-reqs-bes53248.html 
sidebar: sidebar 
keywords: bes, cluster, switch, port, assignment, table, configure, bes-53428 cluster switch port assignments - bes-53428 switches 
summary: BES-53248 클러스터 스위치 포트 할당 표를 참조하여 클러스터를 구성할 수 있습니다. 
---
= BES-53248 클러스터 스위치의 구성 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 스위치 설치 및 유지 보수의 경우 EFOS 및 ONTAP 지원 및 구성 요구 사항을 검토하십시오.



== EFOS 및 ONTAP 지원

를 참조하십시오 https://hwu.netapp.com/Switch/Index["NetApp Hardware Universe를 참조하십시오"^] 및 https://mysupport.netapp.com/site/info/broadcom-cluster-switch["Broadcom은 호환성 매트릭스를 전환합니다"^] BES-53248 스위치와의 EFOS 및 ONTAP 호환성 정보 EFOS 및 ONTAP 지원은 BES-53248 스위치의 특정 시스템 유형에 따라 다를 수 있습니다. 모든 BES-52348 스위치 장비 유형에 대한 자세한 내용은 을 참조하십시오 link:components-bes53248.html["BES-53248 클러스터 스위치의 구성 요소 및 부품 번호"].



== 구성 요구 사항

클러스터를 구성하려면 클러스터 스위치에 맞는 케이블 및 케이블 커넥터 수와 유형이 필요합니다. 처음 구성하는 클러스터 스위치의 유형에 따라 포함된 콘솔 케이블을 사용하여 스위치 콘솔 포트에 연결해야 합니다.



=== 클러스터 스위치 포트 할당

Broadcom 지원 BES-53248 클러스터 스위치 포트 할당 표를 클러스터 구성 지침으로 사용할 수 있습니다.

[cols="1,2"]
|===
| 스위치 포트 | 포트 사용 


 a| 
01-16번
 a| 
10/25GbE 클러스터 포트 노드, 기본 구성



 a| 
17-48
 a| 
10/25GbE 클러스터 포트 노드, 라이센스 포함



 a| 
49-54로 이동합니다
 a| 
40/100GbE 클러스터 포트 노드 및 라이센스 포함, 오른쪽에서 왼쪽 추가



 a| 
55-56
 a| 
100GbE 클러스터 ISL(Inter-Switch Link) 포트, 기본 구성

|===
를 참조하십시오 https://hwu.netapp.com/Switch/Index["Hardware Universe"] 스위치 포트에 대한 자세한 내용은 을 참조하십시오.



=== 포트 그룹 속도 제한

* BES-53248 클러스터 스위치에서 48개의 10/25GbE(SFP28/SFP+) 포트를 다음과 같이 12개의 4 포트 그룹으로 통합합니다. 포트 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44 및 45-48로 이동합니다.
* SFP28/SFP+ 포트 속도는 4포트 그룹의 모든 포트에서 동일한(10GbE 또는 25GbE)여야 합니다.




=== 추가 요구 사항

* 추가 라이센스를 구입한 경우 를 참조하십시오 link:configure-licenses.html["새로 라이센스 포트를 활성화합니다"] 를 참조하십시오.
* SSH가 활성 상태인 경우 명령을 실행한 후 수동으로 다시 활성화해야 합니다 `erase startup-config` 스위치를 재부팅합니다.

