---
permalink: switch-bes-53248/configure-install-initial.html 
sidebar: sidebar 
keywords: switches initial setup,initial setup,efos download 
summary: 이 절차를 사용하여 BES-53248 클러스터 스위치의 초기 설치를 수행할 수 있습니다. 
---
= BES-53248 클러스터 스위치를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 클러스터 스위치의 초기 설정을 수행하려면 다음 단계를 수행하십시오.

.시작하기 전에
* 에 설명된 대로 하드웨어가 설치됩니다 link:install-hardware-bes53248.html["하드웨어를 설치합니다"].
* 다음을 검토했습니다.
+
** link:configure-reqs-bes53248.html["구성 요구 사항"]
** link:components-bes53248.html["부품 및 부품 번호"]
** link:required-documentation-bes53248.html["문서화 요구 사항"]




.예를 참조하십시오
구성 절차의 예에서는 다음과 같은 스위치 및 노드 명명법을 사용합니다.

* NetApp 스위치 이름은 입니다 `cs1` 및 `cs2`. 두 번째 스위치인 _CS2._에서 업그레이드가 시작됩니다
* 클러스터 LIF 이름은 node1의 node1_clus1 및 node1_clus2, node2의 node2_clus1 및 node2_clus2 입니다.
* IPspace 이름이 Cluster입니다.
* 'cluster1::>' 프롬프트는 클러스터의 이름을 나타냅니다.
* 각 노드의 클러스터 포트 이름은 입니다 `e0a` 및 `e0b`. 를 참조하십시오 https://hwu.netapp.com/Home/Index["NetApp Hardware Universe를 참조하십시오"^] 플랫폼에 지원되는 실제 클러스터 포트의 경우
* NetApp 스위치에 지원되는 ISL(Inter-Switch Link)은 포트 0/55 및 0/56입니다.
* NetApp 스위치에 지원되는 노드 연결은 기본 라이센스로 포트 0/1~0/16 입니다.
* 이 예에서는 2개의 노드를 사용하지만 클러스터에 최대 24개의 노드를 포함할 수 있습니다.


.단계
. 직렬 포트를 호스트 또는 직렬 포트에 연결합니다.
. 관리 포트(스위치 왼쪽에 있는 RJ-45 렌치 포트)를 TFTP 서버가 있는 동일한 네트워크에 연결합니다.
. 콘솔에서 호스트측 직렬 설정을 지정합니다.
+
** 115200 보드
** 8 데이터 비트
** 1 정지 비트
** 패리티: 없음
** 흐름 제어: 없음


. 스위치에 로 로그인합니다 `admin` 암호를 묻는 메시지가 나타나면 * Enter * 를 누릅니다. 기본 스위치 이름은 * routing * 입니다. 프롬프트에서 를 입력합니다 `enable`. 이렇게 하면 스위치 구성을 위한 관리자 EXEC 모드에 액세스할 수 있습니다.
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
User: *admin*
Password:
(Routing)> *enable*
Password:
(Routing)#
----
====
. 스위치 이름을 * CS2 * 로 변경합니다.
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
(Routing)# *hostname cs2*
(cs2)#
----
====
. 고정 IP 주소를 설정하려면 예에서와 같이 'erviceport protocol', 'network protocol', 'erviceport IP' 명령어를 사용한다.
+
serviceport는 기본적으로 DHCP를 사용하도록 설정됩니다. IP 주소, 서브넷 마스크 및 기본 게이트웨이 주소는 자동으로 할당됩니다.

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *serviceport protocol none*
(cs2)# *network protocol none*
(cs2)# *serviceport ip ipaddr netmask gateway*
----
====
. 다음 명령을 사용하여 결과를 확인합니다.
+
서비스서비스

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *show serviceport*
Interface Status............................... Up
IP Address..................................... 172.19.2.2
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 172.19.2.254
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe71:123c/64
IPv6 Default Router............................ fe80::20b:45ff:fea9:5dc0
Configured IPv4 Protocol....................... DHCP
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:71:12:3C
----
====
. 도메인 및 이름 서버 구성:
+
'설정'을 클릭합니다

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2) (Config)# *ip domain name company.com*
(cs2) (Config)# *ip name server 10.10.99.1 10.10.99.2*
(cs2) (Config)# *exit*
(cs2) (Config)#
----
====
. NTP 서버를 구성합니다.
+
.. 시간대 및 시간 동기화(SNTP) 구성:
+
'NTP'입니다

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)#
(cs2) (Config)# *sntp client mode unicast*
(cs2) (Config)# *sntp server 10.99.99.5*
(cs2) (Config)# *clock timezone -7*
(cs2) (Config)# *exit*
(cs2) (Config)#
----
====
+

NOTE: EFOS 버전 3.10.0.3 이상에서는 명령을 사용합니다 `ntp`.

.. 시간을 수동으로 구성합니다.
+
시계

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2) (Config)# *no sntp client mode*
(cs2) (Config)# *clock summer-time recurring 1 sun mar 02:00 1 sun nov 02:00 offset 60 zone EST*
(cs2) (Config)# *clock timezone -5 zone EST*
(cs2) (Config)# *clock set 07:00:00
(cs2) (Config)# *clock set 10/20/2020*

(cs2) (Config)# *show clock*

07:00:11 EST(UTC-5:00) Oct 20 2020
No time source

(cs2) (Config)# *exit*

(cs2)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====




.다음 단계
link:configure-efos-software.html["EFOS 소프트웨어를 설치합니다"].
