---
permalink: switch-bes-53248/configure-licenses.html 
sidebar: sidebar 
keywords: bes, cluster, switch, base, model, license, 10gbe, 25gbe, 100gbe, port, add, purchasing, purchase, install licenses for bes-53248 cluster switches - bes-53248 switches 
summary: BES-53248 클러스터 스위치 기본 모델은 10GbE 또는 25GbE 포트 16개와 100GbE 포트 2개에 대해 라이센스가 부여됩니다. 라이센스를 더 구매하여 새 포트를 추가할 수 있습니다. 
---
= BES-53248 클러스터 스위치용 라이센스를 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 클러스터 스위치 기본 모델은 10GbE 또는 25GbE 포트 16개와 100GbE 포트 2개에 대해 라이센스가 부여됩니다. 라이센스를 더 구매하여 새 포트를 추가할 수 있습니다.

BES-53248 클러스터 스위치에서 다음 라이센스를 사용할 수 있습니다.

[cols="1,2,3"]
|===
| 사용권 유형 | 라이센스 세부 정보 | 지원되는 펌웨어 버전입니다 


 a| 
SW-BES-53248A1-G1-8P-LIC
 a| 
Broadcom 8P 10-25,2P40-100 라이센스 키, X190005/R
 a| 
EFOS 3.4.3.3 이상



 a| 
SW-BES-53248A1-G1-16P-LIC
 a| 
Broadcom 16P 10-25,4P40-100 라이센스 키, X190005/R
 a| 
EFOS 3.4.3.3 이상



 a| 
SW-BES-53248A1-G1-24P-LIC
 a| 
Broadcom 24P 10-25,6P40-100 라이센스 키, X190005/R
 a| 
EFOS 3.4.3.3 이상



 a| 
SW-BES54248-40-100G-LIC
 a| 
Broadcom 6포트 40G100G 라이센스 키, X190005/R
 a| 
EFOS 3.4.4.6 이상



 a| 
SW-BES53248-8P-10G25G-LIC
 a| 
Broadcom 8PORT 10G25G 라이센스 키, X190005/R
 a| 
EFOS 3.4.4.6 이상



 a| 
SW-BES53248-16P-1025G-LIC
 a| 
Broadcom 16Port 10G25G 라이센스 키, X190005/R
 a| 
EFOS 3.4.4.6 이상



 a| 
SW-BES53248-24P-1025G-LIC
 a| 
Broadcom 24Port 10G25G 라이센스 키, X190005/R
 a| 
EFOS 3.4.4.6 이상

|===
.단계
. 클러스터 스위치를 관리 네트워크에 연결합니다.
. "ping" 명령을 사용하여 EFOS, 라이센스 및 RCF 파일을 호스팅하는 서버에 대한 연결을 확인합니다.
+
이 예에서는 스위치가 IP 주소 172.19.2.1로 서버에 연결되어 있는지 확인합니다.

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. 스위치 CS2에서 현재 라이센스 사용을 확인합니다.
+
'How license'입니다

+
[listing, subs="+quotes"]
----
(cs2)# *show license*
Reboot needed.................................. No
Number of active licenses...................... 0

License Index  License Type     Status
-------------- ---------------- -----------

No license file found.
----
. 라이센스 파일을 설치합니다. 다음 예에서는 SFTP를 사용하여 라이센스 파일을 키 인덱스 1에 복사합니다.
+
이 단계를 반복하여 더 많은 라이선스를 로드하고 다른 키 인덱스 번호를 사용합니다.

+
[listing, subs="+quotes"]
----
(cs2)# *copy sftp://root@172.19.2.1/var/lib/tftpboot/license.dat nvram:license-key 1*
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... /var/lib/tftpboot/
Filename....................................... license.dat
Data Type...................................... license

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) *y*

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...


License Key transfer operation completed successfully. System reboot is required.
----
. 현재 라이센스 정보를 모두 표시하고 스위치 CS2가 재부팅되기 전에 라이센스 상태를 확인합니다.
+
'How license'입니다

+
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. Yes
Number of active licenses...................... 0


License Index  License Type      Status
-------------- ----------------- -------------------------------
1              Port              License valid but not applied
----
. 라이센스가 있는 모든 포트 표시:
+
'모두 포트 보기|분리 제외'

+
스위치가 재부팅될 때까지 추가 라이센스 파일의 포트는 표시되지 않습니다.

+
[listing, subs="+quotes"]
----
(cs2)# *show port all \| exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable   Auto                  Down   Enable  Enable long
0/2              Disable   Auto                  Down   Enable  Enable long
0/3              Disable   Auto                  Down   Enable  Enable long
0/4              Disable   Auto                  Down   Enable  Enable long
0/5              Disable   Auto                  Down   Enable  Enable long
0/6              Disable   Auto                  Down   Enable  Enable long
0/7              Disable   Auto                  Down   Enable  Enable long
0/8              Disable   Auto                  Down   Enable  Enable long
0/9              Disable   Auto                  Down   Enable  Enable long
0/10             Disable   Auto                  Down   Enable  Enable long
0/11             Disable   Auto                  Down   Enable  Enable long
0/12             Disable   Auto                  Down   Enable  Enable long
0/13             Disable   Auto                  Down   Enable  Enable long
0/14             Disable   Auto                  Down   Enable  Enable long
0/15             Disable   Auto                  Down   Enable  Enable long
0/16             Disable   Auto                  Down   Enable  Enable long
0/55             Disable   Auto                  Down   Enable  Enable long
0/56             Disable   Auto                  Down   Enable  Enable long
----
. 스위치를 재부팅합니다.
+
다시 로드

+
[listing, subs="+quotes"]
----
(cs2)# *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .

Configuration Saved!
Are you sure you would like to reset the system? (y/n) *y*
----
. 새 라이센스가 활성화되어 있는지 확인하고 라이센스가 적용되었는지 확인합니다.
+
'How license'입니다

+
[listing, subs="+quotes"]
----
(cs2)# *show license*

Reboot needed.................................. No
Number of installed licenses................... 1
Total Downlink Ports enabled................... 16
Total Uplink Ports enabled..................... 8

License Index  License Type              Status
-------------- ------------------------- -----------------------------------
1              Port                      License applied
----
. 모든 새 포트를 사용할 수 있는지 확인합니다.
+
'모두 포트 보기|분리 제외'

+
[listing, subs="+quotes"]
----
(cs2)# *show port all \| exclude Detach*

                 Admin     Physical   Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode       Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Disable    Auto                 Down   Enable  Enable long
0/2              Disable    Auto                 Down   Enable  Enable long
0/3              Disable    Auto                 Down   Enable  Enable long
0/4              Disable    Auto                 Down   Enable  Enable long
0/5              Disable    Auto                 Down   Enable  Enable long
0/6              Disable    Auto                 Down   Enable  Enable long
0/7              Disable    Auto                 Down   Enable  Enable long
0/8              Disable    Auto                 Down   Enable  Enable long
0/9              Disable    Auto                 Down   Enable  Enable long
0/10             Disable    Auto                 Down   Enable  Enable long
0/11             Disable    Auto                 Down   Enable  Enable long
0/12             Disable    Auto                 Down   Enable  Enable long
0/13             Disable    Auto                 Down   Enable  Enable long
0/14             Disable    Auto                 Down   Enable  Enable long
0/15             Disable    Auto                 Down   Enable  Enable long
0/16             Disable    Auto                 Down   Enable  Enable long
0/49             Disable   100G Full             Down   Enable  Enable long
0/50             Disable   100G Full             Down   Enable  Enable long
0/51             Disable   100G Full             Down   Enable  Enable long
0/52             Disable   100G Full             Down   Enable  Enable long
0/53             Disable   100G Full             Down   Enable  Enable long
0/54             Disable   100G Full             Down   Enable  Enable long
0/55             Disable   100G Full             Down   Enable  Enable long
0/56             Disable   100G Full             Down   Enable  Enable long
----



CAUTION: 추가 라이센스를 설치할 때는 새 인터페이스를 수동으로 구성해야 합니다. RCF를 기존의 작동 중인 프로덕션 스위치에 다시 적용하는 것은 바람직하지 않습니다.
