---
permalink: switch-bes-53248/configure-reqs-bes53248.html 
sidebar: sidebar 
keywords: bes, cluster, switch, port, assignment, table, configure, bes-53428 cluster switch port assignments - bes-53428 switches 
summary: BES-53248 클러스터 스위치 포트 할당 표를 가이드로 사용하여 클러스터를 구성할 수 있습니다. 
---
= BES-53248 클러스터 스위치에 대한 구성 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 스위치 설치 및 유지관리를 위해서는 EFOS 및 ONTAP 지원과 구성 요구 사항을 검토하세요.



== EFOS 및 ONTAP 지원

를 참조하십시오 https://hwu.netapp.com/Switch/Index["NetApp Hardware Universe"^] 그리고 https://mysupport.netapp.com/site/info/broadcom-cluster-switch["Broadcom 스위치 호환성 매트릭스"^] BES-53248 스위치와의 EFOS 및 ONTAP 호환성 정보입니다.  EFOS 및 ONTAP 지원은 BES-53248 스위치의 특정 머신 유형에 따라 달라질 수 있습니다.  모든 BES-52348 스위치 머신 유형에 대한 자세한 내용은 다음을 참조하세요.link:components-bes53248.html["BES-53248 클러스터 스위치의 구성 요소 및 부품 번호"] .



== 구성 요구 사항

클러스터를 구성하려면 클러스터 스위치에 적합한 수와 유형의 케이블과 케이블 커넥터가 필요합니다.  처음 구성하는 클러스터 스위치의 유형에 따라, 포함된 콘솔 케이블을 사용하여 스위치 콘솔 포트에 연결해야 합니다.



=== 클러스터 스위치 포트 할당

Broadcom에서 지원하는 BES-53248 클러스터 스위치 포트 할당 표를 클러스터 구성 가이드로 사용할 수 있습니다.

[cols="1,2"]
|===
| 스위치 포트 | 포트 사용 


 a| 
01-16
 a| 
10/25GbE 클러스터 포트 노드, 기본 구성



 a| 
17-48
 a| 
라이센스가 포함된 10/25GbE 클러스터 포트 노드



 a| 
49-54
 a| 
라이센스가 있는 40/100GbE 클러스터 포트 노드가 오른쪽에서 왼쪽으로 추가됩니다.



 a| 
55-56
 a| 
100GbE 클러스터 Inter-Switch Link(ISL) 포트, 기본 구성

|===
를 참조하십시오 https://hwu.netapp.com/Switch/Index["Hardware Universe"] 스위치 포트에 대한 자세한 내용은 다음을 참조하세요.



=== 포트 그룹 속도 제한

* BES-53248 클러스터 스위치에서는 48개의 10/25GbE(SFP28/SFP+) 포트가 다음과 같이 12 x 4포트 그룹으로 결합됩니다. 포트 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44, 45-48.
* SFP28/SFP+ 포트 속도는 4포트 그룹의 모든 포트에서 동일해야 합니다(10GbE 또는 25GbE).




=== 추가 요구 사항

* 추가 라이센스를 구매하는 경우 다음을 참조하세요.link:configure-licenses.html["새로 라이센스된 포트 활성화"] 자세한 활성화 방법은 다음을 참조하세요.
* SSH가 활성화되어 있는 경우 명령을 실행한 후 수동으로 다시 활성화해야 합니다. `erase startup-config` 스위치를 재부팅합니다.


.다음은 무엇입니까?
구성 요구 사항을 검토한 후 다음을 확인할 수 있습니다. link:components-bes53248.html["구성 요소 및 부품 번호"].
