---
permalink: switch-bes-53248/configure-ssh.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, bes, enable ssh on bes-53248 cluster switches - bes-53248 switches 
summary: '클러스터 스위치 상태 모니터(CSHM) 및 로그 수집 기능을 사용하려면 SSH가 필요합니다. BES-53248 클러스터 스위치에서 SSH를 활성화하려면 먼저 SSH 키를 생성한 다음 SSH를 활성화합니다.' 
---
= BES-53248 클러스터 스위치에서 SSH 활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CSHM(Ethernet Switch Health Monitor) 및 로그 수집 기능을 사용하는 경우 SSH 키를 생성한 다음 클러스터 스위치에서 SSH를 활성화해야 합니다.

.단계
. SSH가 비활성화되어 있는지 확인하세요.
+
`show ip ssh`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Disabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SSH Public Key Authentication Mode: ........... Disabled
SCP server Administrative Mode: ............... Disabled
----
====
+
** SSH가 비활성화되어 있지 않으면 다음과 같이 비활성화합니다.
+
`no ip ssh server enable`

+
`no ip scp server enable`

+
[NOTE]
====
*** EFOS 3.12 이상에서는 SSH가 비활성화되면 활성 SSH 세션이 손실되므로 콘솔 액세스가 필요합니다.
*** EFOS 3.11 및 이전 버전의 경우 SSH 서버를 비활성화한 후에도 현재 SSH 세션이 계속 열려 있습니다.


====
+

WARNING: 키를 수정하기 전에 SSH를 비활성화해야 합니다. 그렇지 않으면 스위치에서 경고가 보고됩니다.



. 구성 모드에서 SSH 키를 생성합니다.
+
`crypto key generate`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *config*

(switch) (Config)# *crypto key generate rsa*

Do you want to overwrite the existing RSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate dsa*

Do you want to overwrite the existing DSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate ecdsa 521*

Do you want to overwrite the existing ECDSA keys? (y/n): *y*
----
====
. 구성 모드에서 ONTAP 로그 수집에 대한 AAA 권한을 설정합니다.
+
`aaa authorization commands "noCmdAuthList" none`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch) (Config)# *aaa authorization commands "noCmdAuthList" none*
(switch) (Config)# *exit*
----
====
. SSH/SCP를 다시 활성화합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *ip ssh server enable*
(switch)# *ip scp server enable*
(switch)# *ip ssh pubkey-auth*
----
====
. 다음 변경 사항을 startup-config에 저장합니다.
+
`write memory`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. SSH 키 암호화(FIPS 모드에만 해당):
+

CAUTION: FIPS 모드에서는 보안을 위해 키를 암호로 암호화해야 합니다.  암호화된 키가 없으면 애플리케이션이 시작되지 않습니다.  키는 다음 명령을 사용하여 생성되고 암호화됩니다.

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch) *configure*
(switch) (Config)# *crypto key encrypt write rsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch) (Config)# *crypto key encrypt write dsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch)(Config)# *crypto key encrypt write ecdsa passphrase _<passphase>_*

The key will be encrypted and saved on NVRAM.
This will result in saving all existing configuration also.
Do you want to continue? (y/n): *y*

Config file 'startup-config' created successfully.

(switch) (Config)# *end*
(switch)# *write memory*

This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 스위치를 재부팅하세요:
+
`reload`

. SSH가 활성화되어 있는지 확인하세요.
+
`show ip ssh`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Enabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SSH Public Key Authentication Mode: ........... Enabled
SCP server Administrative Mode: ............... Enabled
----
====


.다음은 무엇인가요?
SSH를 활성화한 후에는 다음을 수행할 수 있습니다. link:../switch-cshm/config-overview.html["스위치 상태 모니터링 구성"].
