---
permalink: switch-bes-53248/configure-log-collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation 
summary: 클러스터 스위치 상태 모니터 로그 수집 기능은 ONTAP에서 스위치 관련 로그 파일을 수집하는 데 사용됩니다. 여기에 설명된 대로 BES-53248 클러스터 스위치 CLI를 사용하여 환경을 설정해야 합니다. 
---
= 로그 수집 기능을 활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP에서 스위치 관련 로그 파일을 수집하는 데 사용되는 로그 수집 기능을 활성화할 수 있습니다.

BES-53248 클러스터 스위치 CLI를 사용하여 환경을 설정했는지 확인합니다.



== ONTAP 9.8 이상

다음 명령을 사용하여 로그 수집 기능을 사용하도록 설정합니다.

System switch ethernet log setup-password와 system switch ethernet log enable-collection

.단계
. '시스템 스위치 이더넷 로그 설정 - 암호'를 입력합니다
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
====
. 입력: `system switch ethernet log enable-collection`
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
====




== ONTAP 9.5P15, 9.6P11, 9.7P8 이상 패치 릴리스

다음 명령을 사용하여 로그 수집 기능을 사용하도록 설정합니다.

System cluster-switch log setup-password와 system cluster-switch log enable-collection

.단계
. 'system cluster-switch log setup-password'를 입력합니다
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
====
. 입력: `system cluster-switch log enable-collection`
+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.
----
====



NOTE: 현재 로그 수집 명령을 사용할 수 없습니다. 을 참조하십시오 link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1225042["버그 1225042"^] 를 참조하십시오.


CAUTION: 이러한 명령에서 오류가 반환되면 NetApp 지원에 문의하십시오.

.다음 단계
스위치를 업그레이드하는 경우 로 이동합니다 link:replace-verify.html["업그레이드 구성을 확인합니다"].
