---
permalink: switch-bes-53248/CSHM_log_collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,SSh key,crypto key generation,BES-53248 Broadcom setup,BES-53248 switches configuration,EFOS 
summary: '이더넷 스위치 상태 모니터(CSHM) 로그 수집 기능은 ONTAP 의 클러스터 또는 스토리지 네트워크 스위치에서 로그를 수집하는 데 사용됩니다.' 
---
= 이더넷 스위치 상태 모니터링 로그 수집
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이더넷 스위치 상태 모니터(CSHM)는 클러스터 및 스토리지 네트워크 스위치의 작동 상태를 보장하고 디버깅 목적으로 스위치 로그를 수집하는 역할을 합니다.  이 절차에서는 스위치에서 자세한 *지원* 로그 수집을 설정하고 시작하는 과정을 안내하고 AutoSupport 에서 수집하는 *주기적* 데이터의 매시간 수집을 시작합니다.

.시작하기 전에
* 로그 수집 기능을 사용하려면 ONTAP 버전 9.10.1P15, 9.11.1P12 또는 9.12.1 이상과 EFOS 3.8.0.2 이상을 실행해야 합니다.
* 스위치에 대해 스위치 상태 모니터링을 활성화해야 합니다.  이를 확인하려면 다음을 확인하세요. `Is Monitored:` 필드는 출력에서 *true*로 설정됩니다. `system switch ethernet show` 명령.


.단계
. 로그 수집을 설정하려면 각 스위치에 대해 다음 명령을 실행합니다.  로그 수집을 위해 스위치 이름, 사용자 이름, 비밀번호를 입력하라는 메시지가 표시됩니다.
+
`system switch ethernet log setup-password`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *<return>*
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs2*
Would you like to specify a user other than admin for log collection? {y|n}: *n*

Enter the password: *<enter switch password>*
Enter the password again: *<enter switch password>*
----
====
. 로그 수집을 시작하려면 다음 명령을 실행하세요. 이때 DEVICE를 이전 명령에서 사용한 스위치로 바꾸세요.  이렇게 하면 두 가지 유형의 로그 수집이 시작됩니다. 자세한 *지원* 로그와 *주기적* 데이터의 시간별 수집입니다.
+
`system switch ethernet log modify -device _<switch-name>_ -log-request true`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log modify -device cs1 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*> *system switch ethernet log modify -device cs2 -log-request true*

Do you want to modify the cluster switch log collection configuration? {y|n}: [n] *y*

Enabling cluster switch log collection.
----
====
+
10분간 기다린 후 로그 수집이 완료되었는지 확인하세요.

+
`system switch ethernet log show`

+

CAUTION: 이러한 명령 중 하나라도 오류를 반환하거나 로그 수집이 완료되지 않으면 NetApp 지원팀에 문의하세요.



.문제 해결
로그 수집 기능에서 보고된 다음 오류 상태 중 하나가 발생하는 경우(출력에서 확인 가능) `system switch ethernet log show` ), 해당 디버그 단계를 시도해 보세요.

|===


| *로그 수집 오류 상태* | *해결* 


 a| 
*RSA 키가 없습니다*
 a| 
ONTAP SSH 키를 다시 생성합니다. NetApp 지원팀에 문의하세요.



 a| 
*비밀번호 변경 오류*
 a| 
자격 증명을 확인하고, SSH 연결을 테스트하고, ONTAP SSH 키를 다시 생성합니다.  스위치 설명서를 검토하거나 NetApp 지원팀에 문의하여 지침을 받으세요.



 a| 
*FIPS에는 ECDSA 키가 없습니다*
 a| 
FIPS 모드가 활성화된 경우 다시 시도하기 전에 스위치에서 ECDSA 키를 생성해야 합니다.



 a| 
*기존 로그 발견*
 a| 
스위치에서 이전 로그 수집 파일을 제거합니다.



 a| 
*스위치 덤프 로그 오류*
 a| 
스위치 사용자에게 로그 수집 권한이 있는지 확인하세요.  위의 전제 조건을 참조하세요.

|===