---
permalink: switch-bes-53248/CSHM_snmpv3.html 
sidebar: sidebar 
keywords: SNMP,SNMPv3,SNMPv3 setup,BES-53248 Broadcom setup,BES-3248 switches configuration,EFOS 
summary: 'SNMPv3은 이더넷 스위치 상태 모니터(CSHM)와 함께 사용할 수 있습니다.' 
---
= SNMPv3을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이더넷 스위치 상태 모니터링(CSHM)을 지원하는 SNMPv3를 구성하려면 다음 절차를 따르십시오.

.이 작업에 대해
다음 명령은 Broadcom BES-53248 스위치에서 SNMPv3 사용자 이름을 구성합니다.

* 인증 없음 *:'net add snmp-server username_snmpv3_user_auth-none'입니다
* MD5/SHA 인증의 경우 *:'net add snmp-server username_SNMPv3_user_[auth-MD5|auth-sha]_AUTH-password_'
* AES/DES 암호화를 사용한 * MD5/SHA 인증의 경우 *:'net add snmp-server username_SNMPv3_user_[auth-MD5|auth-sha]_AUTH-password_[encrypt-aes|encrypt-des]_PRIV-password_'


다음 명령은 ONTAP 측에서 SNMPv3 사용자 이름을 구성합니다. ' cluster1: * > security login create -user -or -group -name_SNMPv3_user_ -application snmp-authentication-method USM -remote-switch-ipaddress_address _'

다음 명령을 실행하면 CSHM에서 SNMPv3 사용자 이름이 설정됩니다.
`cluster1::*> system switch ethernet modify -device _DEVICE_ -snmp-version SNMPv3 -community-or-username _SNMPv3_USER_`

.단계
. 인증 및 암호화를 사용하도록 스위치에서 SNMPv3 사용자를 설정합니다.
+
`net show snmp status`

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
(sw1)(Config)# *snmp-server user <username> network-admin auth-md5 <password> priv-aes128 <password>*

(cs1)(Config)# *show snmp user snmp*

     Name            Group Name      Auth Priv
                                     Meth Meth    Remote Engine ID
----------------- ------------------ ---- ------ -------------------------
<username>        network-admin      MD5  AES128 8000113d03d8c497710bee
----
====
. ONTAP 측에서 SNMPv3 사용자를 설정합니다.
+
`security login create -user-or-group-name <username> -application snmp -authentication-method usm -remote-switch-ipaddress 10.231.80.212`

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *security login create -user-or-group-name <username> -application snmp -authentication-method usm -remote-switch-ipaddress 10.231.80.212*

Enter the authoritative entity's EngineID [remote EngineID]:

Which authentication protocol do you want to choose (none, md5, sha, sha2-256)
[none]: *md5*

Enter the authentication protocol password (minimum 8 characters long):

Enter the authentication protocol password again:

Which privacy protocol do you want to choose (none, des, aes128) [none]: *aes128*

Enter privacy protocol password (minimum 8 characters long):
Enter privacy protocol password again:
----
====
. 새로운 SNMPv3 사용자와 함께 모니터링하도록 CSHM을 구성합니다.
+
`system switch ethernet show-all -device "sw1" -instance`

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show-all -device "sw1 (b8:59:9f:09:7c:22)" -instance*

                                   Device Name: sw1
                                    IP Address: 10.228.136.24
                                  SNMP Version: SNMPv2c
                                 Is Discovered: true
DEPRECATED-Community String or SNMPv3 Username: -
           Community String or SNMPv3 Username: cshm1!
                                  Model Number: BES-53248
                                Switch Network: cluster-network
                              Software Version: 3.9.0.2
                     Reason For Not Monitoring: None  *<---- should display this if SNMP settings are valid*
                      Source Of Switch Version: CDP/ISDP
                                Is Monitored ?: true
                   Serial Number of the Device: QTFCU3826001C
                                   RCF Version: v1.8X2 for Cluster/HA/RDMA

cluster1::*>
cluster1::*> *system switch ethernet modify -device "sw1" -snmp-version SNMPv3 -community-or-username <username>*
----
====
. 새로 생성된 SNMPv3 사용자로 쿼리할 일련 번호가 CSHM 폴링 기간이 완료된 후 이전 단계에서 자세히 설명한 일련 번호와 동일한지 확인합니다.
+
`system switch ethernet polling-interval show`

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet polling-interval show*
         Polling Interval (in minutes): 5

cluster1::*> *system switch ethernet show-all -device "sw1" -instance*
                                   Device Name: sw1
                                    IP Address: 10.228.136.24
                                  SNMP Version: SNMPv3
                                 Is Discovered: true
DEPRECATED-Community String or SNMPv3 Username: -
           Community String or SNMPv3 Username: <username>
                                  Model Number: BES-53248
                                Switch Network: cluster-network
                              Software Version: 3.9.0.2
                     Reason For Not Monitoring: None  *<---- should display this if SNMP settings are valid*
                      Source Of Switch Version: CDP/ISDP
                                Is Monitored ?: true
                   Serial Number of the Device: QTFCU3826001C
                                   RCF Version: v1.8X2 for Cluster/HA/RDMA
----
====

