---
permalink: switch-bes-53248/migrate-cn1610.html 
sidebar: sidebar 
keywords: CN1610, CN1610 replacing, migrate from CN1610 
summary: 클러스터에서 기존 CN1610 클러스터 스위치를 Broadcom 지원 BES-53248 클러스터 스위치로 교체하려면 특정 작업 순서를 수행해야 합니다. 
---
= CN1610 클러스터 스위치를 BES-53248 클러스터 스위치로 마이그레이션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 내의 CN1610 클러스터 스위치를 Broadcom 지원 BES-53248 클러스터 스위치로 마이그레이션하려면 마이그레이션 요구 사항을 검토한 다음 마이그레이션 절차를 따르세요.

다음 클러스터 스위치가 지원됩니다.

* CN1610
* BES-53248




== 검토 요구 사항

구성이 다음 요구 사항을 충족하는지 확인하세요.

* BES-53248 스위치의 일부 포트는 10GbE에서 실행되도록 구성되어 있습니다.
* 노드에서 BES-53248 클러스터 스위치로의 10GbE 연결은 계획, 마이그레이션 및 문서화되었습니다.
* 클러스터가 완벽하게 작동합니다(로그에 오류나 이와 유사한 문제가 없어야 함).
* BES-53248 스위치의 초기 사용자 정의가 완료되어 다음이 가능해졌습니다.
+
** BES-53248 스위치는 최신 권장 버전의 EFOS 소프트웨어를 실행하고 있습니다.
** 스위치에 참조 구성 파일(RCF)이 적용되었습니다.
** DNS, NTP, SMTP, SNMP, SSH 등 모든 사이트 사용자 정의는 새 스위치에서 구성됩니다.






=== 노드 연결

클러스터 스위치는 다음 노드 연결을 지원합니다.

* NetApp CN1610: 포트 0/1~0/12(10GbE)
* BES-53248: 포트 0/1-0/16(10GbE/25GbE)
+

NOTE: 추가 포트는 포트 라이선스를 구매하여 활성화할 수 있습니다.





=== ISL 포트

클러스터 스위치는 다음과 같은 ISL(스위치 간 링크) 포트를 사용합니다.

* NetApp CN1610: 포트 0/13~0/16(10GbE)
* BES-53248: 포트 0/55-0/56(100GbE)


그만큼 link:https://hwu.netapp.com/Home/Index["_NetApp 하드웨어 유니버스_"^] 이 문서에는 ONTAP 호환성, 지원되는 EFOS 펌웨어 및 BES-53248 클러스터 스위치와의 케이블 연결에 대한 정보가 포함되어 있습니다. 보다 link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["HWU에 없는 추가 정보 중 장비를 설치하는 데 필요한 정보는 무엇입니까?"^] 스위치 설치 요구 사항에 대한 자세한 내용은 다음을 참조하십시오.



=== ISL 케이블링

적절한 ISL 케이블링은 다음과 같습니다.

* *시작:* CN1610 대 CN1610(SFP+ 대 SFP+)의 경우, 4개의 SFP+ 광섬유 또는 구리 직접 연결 케이블.
* *최종:* BES-53248 대 BES-53248(QSFP28 대 QSFP28)의 경우 QSFP28 광 트랜시버/광섬유 또는 구리 직접 연결 케이블 2개.




== 스위치 마이그레이션

CN1610 클러스터 스위치를 BES-53248 클러스터 스위치로 마이그레이션하려면 다음 절차를 따르세요.

.예시에 관하여
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 이 예제에서는 두 개의 노드를 사용하며, 각 노드는 두 개의 10GbE 클러스터 상호 연결 포트를 배포합니다. `e0a` 그리고 `e0b` .
* 명령 출력은 ONTAP 소프트웨어 릴리스에 따라 달라질 수 있습니다.
* 교체할 CN1610 스위치는 다음과 같습니다. `CL1` 그리고 `CL2` .
* CN1610 스위치를 대체하는 BES-53248 스위치는 다음과 같습니다. `cs1` 그리고 `cs2` .
* 노드는 `node1` 그리고 `node2` .
* 스위치 CL2는 먼저 cs2로 대체되고, 그 다음에 CL1은 cs1로 대체됩니다.
* BES-53248 스위치에는 지원되는 버전의 RCF(Reference Configuration File)와 EFOS(Ethernet Fabric OS)가 미리 로드되어 있으며, ISL 케이블이 포트 55와 56에 연결되어 있습니다.
* 클러스터 LIF 이름은 다음과 같습니다. `node1_clus1` 그리고 `node1_clus2` node1의 경우 `node2_clus1` 그리고 `node2_clus2` 노드2의 경우.


.이 작업에 관하여
이 절차는 다음 시나리오를 다룹니다.

* 클러스터는 두 개의 CN1610 클러스터 스위치에 연결된 두 개의 노드로 시작됩니다.
* CN1610 스위치 CL2는 BES-53248 스위치 cs2로 교체됩니다.
+
** 클러스터 노드의 포트를 종료합니다.  클러스터 불안정성을 방지하려면 모든 포트를 동시에 종료해야 합니다.
** CL2에 연결된 모든 노드의 모든 클러스터 포트에서 케이블을 분리한 다음, 지원되는 케이블을 사용하여 포트를 새 클러스터 스위치 cs2에 다시 연결합니다.


* CN1610 스위치 CL1은 BES-53248 스위치 cs1로 교체됩니다.
+
** 클러스터 노드의 포트를 종료합니다.  클러스터 불안정성을 방지하려면 모든 포트를 동시에 종료해야 합니다.
** CL1에 연결된 모든 노드의 모든 클러스터 포트에서 케이블을 분리한 다음, 지원되는 케이블을 사용하여 포트를 새 클러스터 스위치 cs1에 다시 연결합니다.





NOTE: 이 절차 중에는 작동 중인 ISL(스위치 간 링크)이 필요하지 않습니다. 이는 RCF 버전 변경으로 인해 ISL 연결에 일시적으로 영향을 미칠 수 있기 때문에 설계된 기능입니다. 중단 없는 클러스터 운영을 보장하기 위해 다음 절차에서는 대상 스위치에서 단계를 수행하는 동안 모든 클러스터 LIF를 운영 파트너 스위치로 마이그레이션합니다.



=== 1단계: 마이그레이션 준비

. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
여기서 x는 유지 관리 기간(시간)입니다.

+

NOTE: AutoSupport 메시지는 기술 지원팀에 이 유지 관리 작업을 알려 유지 관리 기간 동안 자동 케이스 생성이 억제되도록 합니다.

+
다음 명령은 2시간 동안 자동 케이스 생성을 억제합니다.

+
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. 계속할지 묻는 메시지가 나타나면 *y*를 입력하여 권한 수준을 고급으로 변경합니다.
+
`set -privilege advanced`

+
고급 프롬프트(*>)가 나타납니다.





=== 2단계: 포트 및 케이블 구성

. 새 스위치에서 스위치 cs1과 cs2 사이에 ISL이 케이블로 연결되어 있고 정상인지 확인하세요.
+
`show port-channel`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 ISL 포트가 스위치 cs1에서 *작동*하고 있음을 보여줍니다.

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
다음 예에서는 ISL 포트가 스위치 cs2에서 *작동*하고 있음을 보여줍니다.

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. 기존 클러스터 스위치에 연결된 각 노드의 클러스터 포트를 표시합니다.
+
`network device-discovery show -protocol cdp`

+
.예를 보여주세요
[%collapsible]
====
다음 예제에서는 각 클러스터 상호 연결 스위치에 대해 각 노드에 구성된 클러스터 상호 연결 인터페이스의 수를 표시합니다.

[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    CL2                       0/2               CN1610
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    CL2                       0/1               CN1610
----
====
. 각 클러스터 인터페이스의 관리 또는 운영 상태를 확인합니다.
+
.. 모든 클러스터 포트가 있는지 확인하십시오. `up` 와 함께 `healthy` 상태:
+
`network port show -ipspace Cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
.. 모든 클러스터 인터페이스(LIF)가 홈 포트에 있는지 확인하세요.
+
`network interface show -vserver Cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
----
====


. 클러스터가 두 클러스터 스위치에 대한 정보를 모두 표시하는지 확인합니다.


[role="tabbed-block"]
====
.ONTAP 9.8 이상
--
ONTAP 9.8부터 다음 명령을 사용하세요. `system switch ethernet show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet show -is-monitoring-enabled-operational true*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP
cluster1::*>
----
--
.ONTAP 9.7 및 이전 버전
--
ONTAP 9.7 및 이전 버전의 경우 다음 명령을 사용하세요. `system cluster-switch show -is-monitoring-enabled-operational true`

[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch show -is-monitoring-enabled-operational true*
Switch                        Type             Address       Model
----------------------------- ---------------- ------------- --------
CL1                           cluster-network  10.10.1.101   CN1610
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP

CL2                           cluster-network  10.10.1.102   CN1610
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: 1.3.0.3
    Version Source: ISDP
cluster1::*>
----
--
====
. [[step5]]클러스터 LIF에서 자동 되돌리기를 비활성화합니다.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. 클러스터 스위치 CL2에서 클러스터 LIF를 장애 조치하기 위해 노드의 클러스터 포트에 연결된 포트를 종료합니다.
+
[listing, subs="+quotes"]
----
(CL2)# *configure*
(CL2)(Config)# *interface 0/1-0/16*
(CL2)(Interface 0/1-0/16)# *shutdown*
(CL2)(Interface 0/1-0/16)# *exit*
(CL2)(Config)# *exit*
(CL2)#
----
. 클러스터 LIF가 클러스터 스위치 CL1에 호스팅된 포트로 장애 조치되었는지 확인합니다. 몇 초 정도 걸릴 수 있습니다.
+
`network interface show -vserver Cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0a     false
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0a     false
----
====
. 클러스터가 정상인지 확인하세요.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. 모든 클러스터 노드 연결 케이블을 기존 CL2 스위치에서 새로운 cs2 스위치로 옮깁니다.
. cs2로 이동된 네트워크 연결의 상태를 확인하세요:
+
`network port show -ipspace Cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
이동된 모든 클러스터 포트는 다음과 같아야 합니다. `up` .

. 클러스터 포트에서 이웃 정보를 확인하세요.
+
`network device-discovery show -protocol cdp`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    CL1                       0/2               CN1610
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    CL1                       0/1               CN1610
            e0b    cs2                       0/1               BES-53248
----
====
. Switch cs2 관점에서 스위치 포트 연결이 정상인지 확인하세요.
+
[listing, subs="+quotes"]
----
cs2# *show interface all*
cs2# *show isdp neighbors*
----
. 클러스터 스위치 CL1에서 클러스터 LIF를 장애 조치하기 위해 노드의 클러스터 포트에 연결된 포트를 종료합니다.
+
[listing, subs="+quotes"]
----
(CL1)# *configure*
(CL1)(Config)# *interface 0/1-0/16*
(CL1)(Interface 0/1-0/16)# *shutdown*
(CL1)(Interface 0/13-0/16)# *exit*
(CL1)(Config)# *exit*
(CL1)#
----
+
모든 클러스터 LIF는 cs2 스위치로 장애 조치됩니다.

. 클러스터 LIF가 스위치 cs2에 호스팅된 포트로 장애 조치되었는지 확인합니다. 몇 초 정도 걸릴 수 있습니다.
+
`network interface show -vserver Cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*
            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0b     false
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0b     false
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. 클러스터가 정상인지 확인하세요.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *cluster show*
Node       Health  Eligibility   Epsilon
---------- ------- ------------- -------
node1      true    true          false
node2      true    true          false
----
====
. 클러스터 노드 연결 케이블을 CL1에서 새로운 cs1 스위치로 옮깁니다.
. cs1로 이동된 네트워크 연결의 상태를 확인하세요.
+
`network port show -ipspace Cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
+
이동된 모든 클러스터 포트는 다음과 같아야 합니다. `up` .

. 클러스터 포트에서 이웃 정보를 확인하세요.
+
`network device-discovery show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
----
====
. 스위치 cs1의 관점에서 스위치 포트 연결이 정상인지 확인하세요.
+
[listing, subs="+quotes"]
----
cs1# *show interface all*
cs1# *show isdp neighbors*
----
. cs1과 cs2 사이의 ISL이 여전히 작동하는지 확인하세요.
+
`show port-channel`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 ISL 포트가 스위치 cs1에서 *작동*하고 있음을 보여줍니다.

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
다음 예에서는 ISL 포트가 스위치 cs2에서 *작동*하고 있음을 보여줍니다.

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. 클러스터의 스위치 테이블에서 교체된 CN1610 스위치가 자동으로 제거되지 않으면 해당 스위치를 삭제합니다.


[role="tabbed-block"]
====
.ONTAP 9.8 이상
--
ONTAP 9.8부터 다음 명령을 사용하세요. `system switch ethernet delete -device _device-name_`

[listing]
----
cluster::*> system switch ethernet delete -device CL1
cluster::*> system switch ethernet delete -device CL2
----
--
.ONTAP 9.7 및 이전 버전
--
ONTAP 9.7 및 이전 버전의 경우 다음 명령을 사용하세요. `system cluster-switch delete -device _device-name_`

[listing]
----
cluster::*> system cluster-switch delete -device CL1
cluster::*> system cluster-switch delete -device CL2
----
--
====


=== 3단계: 구성 확인

. 클러스터 LIF에서 자동 되돌리기를 활성화합니다.
+
[listing, subs="+quotes"]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true
----
. 스위치 cs2에서 모든 클러스터 포트를 종료하고 다시 시작하여 홈 포트에 없는 모든 클러스터 LIF의 자동 복귀를 트리거합니다.
+
[listing, subs="+quotes"]
----
cs2> *enable*
cs2# *configure*
cs2(config)# *interface 0/1-0/16*
cs2(config-if-range)# *shutdown*

(Wait for 5-10 seconds before re-enabling the ports)

cs2(config-if-range)# *no shutdown*

(After executing the no shutdown command, the nodes detect the change and begin to auto-revert the cluster LIFs to their home ports)

cs2(config-if-range)# *exit*
cs2(config)# *exit*
cs2#
----
. 클러스터 LIF가 홈 포트로 되돌아갔는지 확인하세요(1분 정도 걸릴 수 있음).
+
`network interface show -vserver Cluster`

+
클러스터 LIF 중 홈 포트로 복귀되지 않은 것이 있으면 수동으로 복귀시킵니다. LIF를 소유한 로컬 노드의 각 노드 관리 LIF 또는 SP/ BMC 시스템 콘솔에 연결해야 합니다.

+
`network interface revert -vserver Cluster -lif *`

. 클러스터가 정상인지 확인하세요.
+
`cluster show`

. 원격 클러스터 인터페이스의 연결성을 확인하세요.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
당신은 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령:

`network interface check cluster-connectivity start`그리고 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*참고:* 실행하기 전에 몇 초 동안 기다리십시오. `show` 세부 정보를 표시하는 명령입니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2_clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none

node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스의 경우 다음을 사용할 수도 있습니다. `cluster ping-cluster -node <name>` 연결성을 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step6]] 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
[listing, subs="+quotes"]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----


.다음은 무엇인가요?
스위치를 마이그레이션한 후에는 다음을 수행할 수 있습니다. link:../switch-cshm/config-overview.html["스위치 상태 모니터링 구성"].
