---
permalink: switch-bes-53248/migrate-to-2n-switched.html 
sidebar: sidebar 
keywords: two-node switchless clusters,migrating to a two-node switched BES-53248 cluster environment,BES-53248 switches,migrating two-node switched clusters,2-node 
summary: 스위치가 없는 2노드 클러스터가 있는 경우 중단 없이 Broadcom 지원 BES-53248 클러스터 스위치를 포함하는 2노드 스위치 클러스터로 마이그레이션할 수 있습니다. 문서화된 프로세스는 광 또는 Twinax 포트를 사용하는 모든 클러스터 노드 포트에 대해 작동하지만, 노드가 클러스터 네트워크 포트에 온보드 10GBASE-T RJ45 포트를 사용하는 경우 이 스위치에서 지원되지 않습니다. 
---
= Broadcom 지원 BES-53248 클러스터 스위치를 사용하여 2노드 스위치 클러스터로 마이그레이션합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스위치가 없는 2노드 클러스터가 있는 경우 중단 없이 Broadcom 지원 BES-53248 클러스터 스위치를 포함하는 2노드 스위치 클러스터로 마이그레이션할 수 있습니다. 문서화된 프로세스는 광 또는 Twinax 포트를 사용하는 모든 클러스터 노드 포트에 대해 작동하지만, 노드가 클러스터 네트워크 포트에 온보드 10GBASE-T RJ45 포트를 사용하는 경우 이 스위치에서 지원되지 않습니다.

대부분의 시스템에는 각 컨트롤러에 전용 클러스터 네트워크 포트 2개가 필요합니다.

에 설명된 대로 BES-53248 클러스터 스위치가 설정되어 있는지 확인합니다 link:replace-requirements.html["Broadcom 지원 BES-53248 스위치 설정 및 구성"^] 마이그레이션 프로세스를 시작하기 전에


NOTE: 마이그레이션이 완료된 후 BES-53248 클러스터 스위치용 CSHM(Cluster Switch Health Monitor)을 지원하기 위해 필요한 구성 파일을 설치해야 할 수 있습니다.

을 참조하십시오 http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-sw-ix8-setup/GUID-211616A4-C962-464A-A70E-5E057D7B13E1.html["CSHM(Cluster Switch Health Monitor) 구성 파일 설치"^] Broadcom에서 지원하는 BES-53248 스위치_가이드의 _스위치 설정 및 구성 안내서 를 참조하십시오.

또한 를 참조하십시오 link:configure-health-monitor.html["CSHM(Cluster Switch Health Monitor) 구성 파일을 설치합니다"] 및 link:configure-log-collection["클러스터 스위치 로그 수집 기능을 구성합니다"] 스위치 관련 로그 파일을 수집하는 데 사용되는 클러스터 상태 스위치 로그 수집을 활성화하는 데 필요한 단계를 확인합니다.
