---
permalink: switch-bes-53248/migrate-to-2n-switched.html 
sidebar: sidebar 
keywords: two-node switchless clusters, migrating to a two-node switched BES-53248 cluster environment,BES-53248 switches, migrating two-node switched clusters,2-node 
summary: 2노드 스위치리스 클러스터가 있는 경우 중단 없이 Broadcom 지원 BES-53248 클러스터 스위치를 포함하는 2노드 스위치 클러스터로 마이그레이션할 수 있습니다. 
---
= 스위치된 NetApp 클러스터 환경으로 마이그레이션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존의 2노드 _스위치리스_ 클러스터 환경이 있는 경우 Broadcom에서 지원하는 BES-53248 클러스터 스위치를 사용하여 2노드 _스위치_ 클러스터 환경으로 마이그레이션할 수 있습니다. 이를 통해 클러스터에서 두 개 이상의 노드를 확장할 수 있습니다.

마이그레이션 프로세스는 광 포트나 Twinax 포트를 사용하는 모든 클러스터 노드 포트에서 작동하지만, 노드가 클러스터 네트워크 포트에 온보드 10GBASE-T RJ45 포트를 사용하는 경우 이 스위치에서는 지원되지 않습니다.



== 검토 요구 사항

클러스터 환경에 대한 다음 요구 사항을 검토하세요.

* 대부분의 시스템은 각 컨트롤러에 전용 클러스터 네트워크 포트가 두 개 필요하다는 점을 알아두세요.
* BES-53248 클러스터 스위치가 설명된 대로 설정되었는지 확인하십시오.link:replace-switch-reqs.html["요구 사항 교체"] 이 마이그레이션 프로세스를 시작하기 전에.
* 2노드 스위치리스 구성의 경우 다음 사항을 확인하세요.
+
** 2노드 스위치리스 구성이 올바르게 설정되고 작동하고 있습니다.
** 노드는 ONTAP 9.5P8 이상을 실행합니다.  40/100GbE 클러스터 포트에 대한 지원은 EFOS 펌웨어 버전 3.4.4.6 이상부터 시작됩니다.
** 모든 클러스터 포트가 *작동* 상태입니다.
** 모든 클러스터 논리 인터페이스(LIF)는 *작동* 상태이며 홈 포트에 있습니다.


* Broadcom 지원 BES-53248 클러스터 스위치 구성의 경우 다음을 확인하세요.
+
** BES-53248 클러스터 스위치는 두 스위치 모두에서 완벽하게 작동합니다.
** 두 스위치 모두 관리 네트워크 연결 기능을 갖추고 있습니다.
** 클러스터 스위치에 콘솔로 접근할 수 있습니다.
** BES-53248 노드 간 스위치와 스위치 간 연결은 Twinax 또는 파이버 케이블을 사용합니다.
+
그만큼 link:https://hwu.netapp.com/Home/Index["_NetApp 하드웨어 유니버스_"^] 이 문서에는 ONTAP 호환성, 지원되는 EFOS 펌웨어 및 BES-53248 스위치와의 케이블 연결에 대한 정보가 포함되어 있습니다. 보다 link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["HWU에 없는 추가 정보 중 장비를 설치하는 데 필요한 정보는 무엇입니까?"^] 스위치 설치 요구 사항에 대한 자세한 내용은 다음을 참조하십시오.



* ISL(Inter-Switch Link) 케이블은 두 BES-53248 스위치의 포트 0/55와 0/56에 연결됩니다.
* 두 BES-53248 스위치의 초기 사용자 정의가 완료되어 다음과 같은 결과가 나왔습니다.
+
** BES-53248 스위치는 최신 버전의 소프트웨어를 실행하고 있습니다.
** BES-53248 스위치를 구매하면 옵션으로 포트 라이선스가 설치됩니다.
** 참조 구성 파일(RCF)은 스위치에 적용됩니다.


* 모든 사이트 사용자 정의(SMTP, SNMP, SSH)는 새 스위치에서 구성됩니다.


.포트 그룹 속도 제약
* 48개의 10/25GbE(SFP28/SFP+) 포트는 다음과 같이 12 x 4포트 그룹으로 결합됩니다. 포트 1-4, 5-8, 9-12, 13-16, 17-20, 21-24, 25-28, 29-32, 33-36, 37-40, 41-44, 45-48.
* SFP28/SFP+ 포트 속도는 4포트 그룹의 모든 포트에서 동일해야 합니다(10GbE 또는 25GbE).
* 4포트 그룹의 속도가 다르면 스위치 포트가 올바르게 작동하지 않습니다.




== 클러스터 환경으로 마이그레이션

.예시에 관하여
이 절차의 예에서는 다음 클러스터 스위치와 노드 명명법을 사용합니다.

* BES-53248 스위치의 이름은 다음과 같습니다. `cs1` 그리고 `cs2` .
* 클러스터 SVM의 이름은 다음과 같습니다. `node1` 그리고 `node2` .
* LIF의 이름은 다음과 같습니다. `node1_clus1` 그리고 `node1_clus2` 노드 1에서 `node2_clus1` 그리고 `node2_clus2` 각각 노드 2에 있습니다.
* 그만큼 `cluster1::*>` 프롬프트는 클러스터의 이름을 나타냅니다.
* 이 절차에서 사용되는 클러스터 포트는 다음과 같습니다. `e0a` 그리고 `e0b` .
+
그만큼 https://hwu.netapp.com/Home/Index["_NetApp 하드웨어 유니버스_"^] 플랫폼의 실제 클러스터 포트에 대한 최신 정보가 포함되어 있습니다.





=== 1단계: 마이그레이션 준비

. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
여기서 x는 유지 관리 기간(시간)입니다.

+

NOTE: AutoSupport 메시지는 기술 지원팀에 이 유지 관리 작업을 알려 유지 관리 기간 동안 자동 케이스 생성이 억제되도록 합니다.

+
다음 명령은 2시간 동안 자동 케이스 생성을 억제합니다.

+
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. 계속할지 묻는 메시지가 나타나면 *y*를 입력하여 권한 수준을 고급으로 변경합니다.
+
`set -privilege advanced`

+
고급 프롬프트(`*>` )이 나타납니다.





=== 2단계: 포트 및 케이블 구성

. 새로운 클러스터 스위치 cs1과 cs2 모두에서 활성화된 모든 노드 연결 포트(ISL 포트 제외)를 비활성화합니다.
+

NOTE: ISL 포트를 비활성화하면 안 됩니다.

+
다음 예에서는 스위치 cs1에서 노드에 연결된 포트 1~16이 비활성화되어 있음을 보여줍니다.

+
[listing, subs="+quotes"]
----
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *shutdown*
(cs1)(Interface 0/1-0/16)# *exit*
(cs1)(Config)# *exit*
----
. 두 BES-53248 스위치 cs1과 cs2 사이의 ISL과 ISL의 물리적 포트가 작동 중인지 확인하세요.
+
`show port-channel`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 ISL 포트가 스위치 cs1에서 작동 중임을 보여줍니다.

[listing, subs="+quotes"]
----
(cs1)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
다음 예에서는 ISL 포트가 스위치 cs2에서 작동 중임을 보여줍니다.

[listing, subs="+quotes"]
----
(cs2)# *show port-channel 1/1*
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. 이웃 장치 목록을 표시합니다.
+
`show isdp neighbors`

+
이 명령은 시스템에 연결된 장치에 대한 정보를 제공합니다.

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 스위치 cs1의 인접 장치를 나열합니다.

[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
다음 예에서는 스위치 cs2의 인접 장치를 나열합니다.

[listing, subs="+quotes"]
----
(cs2)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
====
. 모든 클러스터 포트가 작동 중인지 확인하세요.
+
`network port show -ipspace Cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy
----
====
. 모든 클러스터 LIF가 작동 중인지 확인하세요.
+
`network interface show -vserver Cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical      Status     Network            Current       Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node          Port    Home
----------- ------------ ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2         e0b     true
----
====
. 클러스터 LIF에서 자동 되돌리기를 비활성화합니다.
+
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*
----
. 노드 1의 클러스터 포트 e0a에서 케이블을 분리한 다음, BES-53248 스위치에서 지원하는 적절한 케이블을 사용하여 e0a를 클러스터 스위치 cs1의 포트 1에 연결합니다.
+
그만큼 https://hwu.netapp.com/Home/Index["_NetApp 하드웨어 유니버스_"^] 케이블링에 대한 자세한 정보가 포함되어 있습니다.

. 노드2의 클러스터 포트 e0a에서 케이블을 분리한 다음, BES-53248 스위치에서 지원하는 적절한 케이블을 사용하여 e0a를 클러스터 스위치 cs1의 포트 2에 연결합니다.
. 클러스터 스위치 cs1에서 모든 노드 연결 포트를 활성화합니다.
+
다음 예에서는 스위치 cs1에서 포트 1~16이 활성화되어 있음을 보여줍니다.

+
[listing, subs="+quotes"]
----
(cs1)# *configure*
(cs1)(Config)# *interface 0/1-0/16*
(cs1)(Interface 0/1-0/16)# *no shutdown*
(cs1)(Interface 0/1-0/16)# *exit*
(cs1)(Config)# *exit*
----
. 모든 클러스터 포트가 작동 중인지 확인하세요.
+
`network port show -ipspace Cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. 모든 클러스터 LIF가 작동 중인지 확인하세요.
+
`network interface show -vserver Cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true
----
====
. 클러스터의 노드 상태에 대한 정보를 표시합니다.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 클러스터 내 노드의 상태와 적격성에 대한 정보를 표시합니다.

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. 노드 1의 클러스터 포트 e0b에서 케이블을 분리한 다음, BES-53248 스위치에서 지원하는 적절한 케이블을 사용하여 e0b를 클러스터 스위치 cs2의 포트 1에 연결합니다.
. 노드2의 클러스터 포트 e0b에서 케이블을 분리한 다음, BES-53248 스위치에서 지원하는 적절한 케이블을 사용하여 e0b를 클러스터 스위치 cs2의 포트 2에 연결합니다.
. 클러스터 스위치 cs2에서 모든 노드 연결 포트를 활성화합니다.
+
다음 예에서는 스위치 cs2에서 포트 1~16이 활성화되어 있음을 보여줍니다.

+
[listing, subs="+quotes"]
----
(cs2)# *configure*
(cs2)(Config)# *interface 0/1-0/16*
(cs2)(Interface 0/1-0/16)# *no shutdown*
(cs2)(Interface 0/1-0/16)# *exit*
(cs2)(Config)# *exit*
----
. 모든 클러스터 포트가 작동 중인지 확인하세요.
+
`network port show -ipspace Cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====




=== 3단계: 구성 확인

. 클러스터 LIF에서 자동 되돌리기를 활성화합니다.
+
[listing, subs="+quotes"]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert true
----
. 스위치 cs2에서 모든 클러스터 포트를 종료하고 다시 시작하여 홈 포트에 없는 모든 클러스터 LIF의 자동 복귀를 트리거합니다.
+
[listing, subs="+quotes"]
----
cs2> *enable*
cs2# *configure*
cs2(config)# *interface 0/1-0/16*
cs2(config-if-range)# *shutdown*

(Wait for 5-10 seconds before re-enabling the ports)

cs2(config-if-range)# *no shutdown*

(After executing the no shutdown command, the nodes detect the change and begin to auto-revert the cluster LIFs to their home ports)

cs2(config-if-range)# *exit*
cs2(config)# *exit*
cs2#
----
. 클러스터 LIF가 홈 포트로 되돌아갔는지 확인하세요(1분 정도 걸릴 수 있음).
+
`network interface show -vserver Cluster`

+
클러스터 LIF 중 홈 포트로 복귀되지 않은 것이 있으면 수동으로 복귀시킵니다. LIF를 소유한 로컬 노드의 각 노드 관리 LIF 또는 SP/ BMC 시스템 콘솔에 연결해야 합니다.

+
`network interface revert -vserver Cluster -lif *`

. 모든 인터페이스가 표시되는지 확인하세요 `true` ~을 위한 `Is Home` :
+
`network interface show -vserver Cluster`

+

NOTE: 완료하는 데 몇 분 정도 걸릴 수 있습니다.

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true
----
====
. 두 노드 모두 각 스위치에 하나의 연결이 있는지 확인하세요.
+
`show isdp neighbors`

+
.예를 보여주세요
[%collapsible]
====
다음 예는 두 스위치에 대한 적절한 결과를 보여줍니다.

[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform -- Port ID
-------------- ------------ --------- ------------ ----------- ----------
node1          0/1          175       H            FAS2750     e0a
node2          0/2          157       H            FAS2750     e0a
cs2            0/55         178       R            BES-53248   0/55
cs2            0/56         178       R            BES-53248   0/56


(cs2)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform    Port ID
-------------- ------------ --------- ------------ ----------- ------------
node1          0/1          137       H            FAS2750     e0b
node2          0/2          179       H            FAS2750     e0b
cs1            0/55         175       R            BES-53248   0/55
cs1            0/56         175       R            BES-53248   0/56
----
====
. 클러스터에서 검색된 네트워크 장치에 대한 정보를 표시합니다.
+
`network device-discovery show -protocol cdp`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
----
====
. 설정이 비활성화되었는지 확인하세요.
+
`network options switchless-cluster show`

+

NOTE: 명령을 완료하는 데 몇 분이 걸릴 수 있습니다.  '3분 유효기간 만료' 공지를 기다리세요.

+
그만큼 `false` 다음 예제의 출력은 구성 설정이 비활성화되었음을 보여줍니다.

+
[listing, subs="+quotes"]
----
cluster1::*> network options switchless-cluster show
Enable Switchless Cluster: *false*
----
. 클러스터의 노드 멤버 상태를 확인하세요.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 클러스터 내 노드의 상태와 적격성에 대한 정보를 보여줍니다.

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. 원격 클러스터 인터페이스의 연결성을 확인하세요.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
당신은 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령:

`network interface check cluster-connectivity start`그리고 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*참고:* 실행하기 전에 몇 초 동안 기다리십시오. `show` 세부 정보를 표시하는 명령입니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2_clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none

node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스의 경우 다음을 사용할 수도 있습니다. `cluster ping-cluster -node <name>` 연결성을 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node node2*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step10]]권한 수준을 다시 관리자로 변경합니다.
+
`set -privilege admin`

. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster1::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
+
자세한 내용은 다음을 참조하세요. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetApp KB 문서: 예약된 유지 관리 기간 동안 자동 케이스 생성을 억제하는 방법"^]



.다음은 무엇인가요?
스위치를 마이그레이션한 후에는 다음을 수행할 수 있습니다. link:../switch-cshm/config-overview.html["스위치 상태 모니터링 구성"].
