---
permalink: switch-bes-53248/migrate-to-2n-switched-overview.html 
sidebar: sidebar 
keywords: two-node switchless cluster environments,migrating to a two-node switched BES-53248 cluster environment,switchless cluster environments,tnsc,TNSC,2-node 
summary: 기존의 2노드 스위치가 없는 클러스터 환경이 있는 경우 Broadcom 지원 BES-53248 클러스터 스위치를 사용하여 2노드 스위치 클러스터 환경으로 마이그레이션하여 클러스터의 2개 노드 이상으로 확장할 수 있습니다. 
---
= Broadcom에서 지원하는 BES-53248 클러스터 스위치를 사용하여 Switched NetApp 클러스터 환경으로 마이그레이션합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
기존의 2노드 스위치가 없는 클러스터 환경이 있는 경우 Broadcom 지원 BES-53248 클러스터 스위치를 사용하여 2노드 스위치 클러스터 환경으로 마이그레이션하여 클러스터의 2개 노드 이상으로 확장할 수 있습니다.

스위치가 없는 2노드 구성:

* 스위치가 없는 2노드 구성이 올바르게 설정 및 작동해야 합니다.
* 노드는 ONTAP 9.5P8 이상을 실행해야 합니다. 40/100 GbE 클러스터 포트 지원은 EFOS 펌웨어 버전 3.4.4.6 이상에서 시작됩니다.
* 모든 클러스터 포트는 UP 상태여야 합니다.
* 모든 클러스터 논리 인터페이스(LIF)는 홈 포트와 위쪽 상태여야 합니다.


Broadcom 지원 BES-53248 클러스터 스위치 구성:

* BES-53248 클러스터 스위치는 두 스위치 모두에서 완전히 작동해야 합니다.
* 두 스위치 모두 관리 네트워크 연결이 있어야 합니다.
* 클러스터 스위치에 대한 콘솔 액세스가 있어야 합니다.
* BES-53248 노드 간 스위치 및 스위치 간 연결은 Twinax 또는 파이버 케이블을 사용해야 합니다.
+
__NetApp__Hardware Universe에는 ONTAP 호환성, 지원되는 EFOS 펌웨어, BES-53248 스위치 케이블 연결에 대한 정보가 포함되어 있습니다.

+
https://hwu.netapp.com/Switch/Index["Hardware Universe - 스위치"^]

* ISL(Inter-Switch Link) 케이블은 두 BES-53248 스위치의 포트 0/55 및 0/56 포트에 연결해야 합니다.
* 두 BES-53248 스위치의 초기 사용자 정의를 완료해야 합니다. 따라서 다음을 수행합니다.
+
** BES-53248 스위치는 최신 버전의 소프트웨어를 실행하고 있습니다
** BES-53248 스위치에는 옵션 포트 라이센스가 설치되어 있습니다(구입한 경우)
** RCF(Reference Configuration Files)가 스위치에 적용되었습니다
+
SMTP, SNMP, SSH 등의 사이트 사용자 지정은 새 스위치에서 구성해야 합니다.





이 절차의 예에서는 다음과 같은 클러스터 스위치 및 노드 명명법을 사용합니다.

* BES-53248 스위치의 이름은 CS1, CS2입니다.
* 클러스터 SVM의 이름은 노드1과 노드2입니다.
* LIF의 이름은 노드 1의 node1_clus1 및 node1_clus2, 노드 2의 node2_clus1 및 node2_clus2 입니다.
* 'cluster1:: *>' 프롬프트는 클러스터의 이름을 나타냅니다.
* 이 절차에 사용되는 클러스터 포트는 e0a 및 e0b입니다.
+
_Hardware Universe_에는 플랫폼의 실제 클러스터 포트에 대한 최신 정보가 들어 있습니다.

+
https://hwu.netapp.com["Hardware Universe"^]



.단계
. 이 클러스터에서 AutoSupport가 활성화되어 있는 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
'System node AutoSupport invoke-node * -type all-message maINT=xh'

+
여기서 x는 유지 보수 기간(시간)입니다.

+

NOTE: AutoSupport 메시지는 유지보수 기간 동안 자동 케이스 생성이 억제되도록 이 유지보수 작업의 기술 지원에 알립니다.

+
다음 명령을 실행하면 2시간 동안 자동 케이스가 생성되지 않습니다.

+
[listing]
----
cluster1::*> system node autosupport invoke -node \* -type all -message MAINT=2h
----
. 권한 수준을 고급으로 변경하고 계속할 것인지 묻는 메시지가 표시되면 * y * 를 입력합니다.
+
세트 프리빌리지 고급

+
고급 프롬프트('*>')가 나타납니다.

. 새 클러스터 스위치 CS1 * 및 * CS2 모두에서 활성화된 노드 방향 포트(ISL 포트 아님)를 모두 비활성화합니다.
+

NOTE: ISL 포트를 비활성화해서는 안 됩니다.

+
다음 예에서는 스위치 CS1에서 노드 방향 포트 1부터 16까지 비활성 상태를 보여 줍니다.

+
[listing]
----
(cs1)# configure
(cs1)(Config)# interface 0/1-0/16
(cs1)(Interface 0/1-0/16)# shutdown
(cs1)(Interface 0/1-0/16)# exit
(cs1)(Config)# exit
----
. 두 BES-53248 스위치 CS1과 CS2 사이의 ISL과 ISL의 물리적 포트가 "작동" 상태인지 확인합니다.
+
항로를 선택합니다

+
다음 예에서는 스위치 CS1에서 ISL 포트가 작동 중인 것을 보여 줍니다.

+
[listing]
----
(cs1)# show port-channel 1/1
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs1) #
----
+
다음 예에서는 스위치 CS2에서 ISL 포트가 작동 중인 것을 보여 줍니다.

+
[listing]
----
(cs2)# show port-channel 1/1
Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------  -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
(cs2) #
----
. 인접 장치 목록을 표시합니다.
+
'ISDP 네이버 표시

+
이 명령은 시스템에 연결된 장치에 대한 정보를 제공합니다.

+
다음 예에서는 스위치 CS1의 인접 장치를 나열합니다.

+
[listing]
----
(cs1)# show isdp neighbors

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
+
다음 예에서는 스위치 CS2의 인접 장치를 나열합니다.

+
[listing]
----

(cs2)# show isdp neighbors

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf     Holdtime  Capability   Platform    Port ID
-------------- -------- --------- ------------ ----------- ---------
cs2            0/55     176       R            BES-53248   0/55
cs2            0/56     176       R            BES-53248   0/56
----
. 모든 클러스터 포트가 'UP' 상태인지 확인합니다.
+
네트워크 포트 표시 - IPSpace 클러스터

+
각 항구는 건강상태에 대한 Link와 Healthy로 표시되어야 합니다.

+
[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node2

                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.
----
. 모든 클러스터 LIF가 '작동' 및 'network interface show-vserver Cluster'인지 확인합니다
+
각 클러스터 LIF는 '홈'에 대해 '참'으로 표시되어야 하며 '위/위'의 '상태 관리자/작업'이 있어야 합니다

+
[listing]
----

cluster1::*> network interface show -vserver Cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
. 모든 클러스터 LIF에서 'auto-revert'가 활성화되어 있는지 확인합니다. 'network interface show-vserver Cluster-fields auto-revert'
+
[listing]
----
cluster1::*> network interface show -vserver Cluster -fields auto-revert

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true

4 entries were displayed.
----
. 노드 1의 클러스터 포트 e0a에서 케이블을 분리한 다음, BES-53248 스위치가 지원하는 적절한 케이블을 사용하여 클러스터 스위치 CS1의 포트 1에 e0a를 연결합니다.
+
케이블 연결에 대한 자세한 내용은 _NetApp Hardware Universe_를 참조하십시오.

+
https://hwu.netapp.com/Switch/Index["Hardware Universe - 스위치"^]

. 노드 2의 클러스터 포트 e0a에서 케이블을 분리한 다음, BES-53248 스위치가 지원하는 적절한 케이블을 사용하여 클러스터 스위치 CS1의 포트 2에 e0a를 연결합니다.
. 클러스터 스위치 CS1에서 모든 노드 대상 포트를 활성화합니다.
+
다음 예에서는 스위치 CS1에서 포트 1 ~ 16이 활성화되어 있음을 보여 줍니다.

+
[listing]
----
(cs1)# configure
(cs1)(Config)# interface 0/1-0/16
(cs1)(Interface 0/1-0/16)# no shutdown
(cs1)(Interface 0/1-0/16)# exit
(cs1)(Config)# exit
----
. 모든 클러스터 LIF가 작동 중이고 "홈"에 대해 "참"으로 표시되는지 확인합니다.
+
'network interface show-vserver cluster'

+
다음 예에서는 모든 LIF가 node1과 node2에 있고 "홈" 결과가 "참"임을 보여 줍니다.

+
[listing]
----
cluster1::*> network interface show -vserver Cluster

         Logical      Status     Network            Current     Current Is
Vserver  Interface    Admin/Oper Address/Mask       Node        Port    Home
-------- ------------ ---------- ------------------ ----------- ------- ----
Cluster
         node1_clus1  up/up      169.254.209.69/16  node1       e0a     true
         node1_clus2  up/up      169.254.49.125/16  node1       e0b     true
         node2_clus1  up/up      169.254.47.194/16  node2       e0a     true
         node2_clus2  up/up      169.254.19.183/16  node2       e0b     true

4 entries were displayed.
----
. 클러스터의 노드 상태에 대한 정보를 표시합니다.
+
'클러스터 쇼'

+
다음 예제에는 클러스터에 있는 노드의 상태 및 자격에 대한 정보가 표시됩니다.

+
[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
. BES-53248 스위치가 지원하는 적절한 케이블을 사용하여 노드 1의 클러스터 포트 e0b에서 케이블을 분리한 다음 클러스터 스위치 CS2의 포트 1에 e0b를 연결합니다.
. BES-53248 스위치가 지원하는 적절한 케이블을 사용하여 노드 2의 클러스터 포트 e0b에서 케이블을 분리한 다음 클러스터 스위치 CS2의 포트 2에 e0b를 연결합니다.
. 클러스터 스위치 CS2에서 모든 노드 대상 포트를 활성화합니다.
+
다음 예에서는 스위치 CS2에서 포트 1부터 16까지 활성화되었음을 보여 줍니다.

+
[listing]
----
(cs2)# configure
(cs2)(Config)# interface 0/1-0/16
(cs2)(Interface 0/1-0/16)# no shutdown
(cs2)(Interface 0/1-0/16)# exit
(cs2)(Config)# exit
----
. 모든 클러스터 포트가 'UP' 상태인지 확인합니다.
+
네트워크 포트 표시 - IPSpace 클러스터

+
다음 예에서는 모든 클러스터 포트가 노드 1과 노드 2에 있음을 보여 줍니다.

+
[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false

4 entries were displayed.
----
. 모든 인터페이스가 '홈'에 대해 '참'으로 표시되는지 확인합니다.
+
'network interface show-vserver cluster'

+

NOTE: 이 작업을 완료하는 데 몇 분 정도 걸릴 수 있습니다.

+
다음 예에서는 모든 LIF가 node1과 node2에 있고 "홈" 결과가 "참"임을 보여 줍니다.

+
[listing]
----
cluster1::*> network interface show -vserver Cluster

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e0b     true

4 entries were displayed.
----
. 두 노드 모두 각 스위치에 하나씩 연결되어 있는지 확인합니다.
+
'ISDP 네이버 표시

+
다음 예에서는 두 스위치에 대해 적절한 결과를 보여 줍니다.

+
[listing]
----
(cs1)# show isdp neighbors

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform -- Port ID
-------------- ------------ --------- ------------ ----------- ----------
node1          0/1          175       H            FAS2750     e0a
node2          0/2          157       H            FAS2750     e0a
cs2            0/55         178       R            BES-53248   0/55
cs2            0/56         178       R            BES-53248   0/56


(cs2)# show isdp neighbors

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID      Intf         Holdtime  Capability   Platform    Port ID
-------------- ------------ --------- ------------ ----------- ------------
node1          0/1          137       H            FAS2750     e0b
node2          0/2          179       H            FAS2750     e0b
cs1            0/55         175       R            BES-53248   0/55
cs1            0/56         175       R            BES-53248   0/56
----
. 클러스터에서 검색된 네트워크 장치에 대한 정보를 표시합니다.
+
네트워크 디바이스 검색 표시 프로토콜 CDP

+
[listing]
----
cluster1::*> network device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248

4 entries were displayed.
----
. 설정이 비활성화되었는지 확인합니다.
+
'network options switchless-cluster show'

+

NOTE: 명령이 완료되는 데 몇 분 정도 걸릴 수 있습니다. '3분 수명 만료' 메시지가 표시될 때까지 기다립니다.

+
다음 예제의 "false" 출력은 구성 설정이 비활성화되어 있음을 보여 줍니다.

+
[listing]
----
cluster1::*> network options switchless-cluster show
Enable Switchless Cluster: false
----
. 클러스터에서 노드 구성원의 상태를 확인합니다.
+
'클러스터 쇼'

+
다음 예는 클러스터에 있는 노드의 상태 및 적격성에 대한 정보를 보여줍니다.

+
[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
. 다음 명령을 사용하여 클러스터 네트워크가 완벽하게 연결되어 있는지 확인합니다.
+
'cluster ping-cluster-node_node-name_'

+
[listing]
----
cluster1::*> cluster ping-cluster -node local

Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 192.168.168.26 node1 e0a
Cluster node1_clus2 192.168.168.27 node1 e0b
Cluster node2_clus1 192.168.168.28 node2 e0a
Cluster node2_clus2 192.168.168.29 node2 e0b
Local = 192.168.168.28 192.168.168.29
Remote = 192.168.168.26 192.168.168.27
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 4 path(s):
    Local 192.168.168.28 to Remote 192.168.168.26
    Local 192.168.168.28 to Remote 192.168.168.27
    Local 192.168.168.29 to Remote 192.168.168.26
    Local 192.168.168.29 to Remote 192.168.168.27
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. 권한 수준을 admin으로 다시 변경합니다.
+
'Set-Privilege admin'입니다

. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화합니다.
+
'System node AutoSupport invoke-node * -type all-message maINT=end'

+
[listing]
----
cluster1::*> system node autosupport invoke -node \* -type all -message MAINT=END
----


에서 클러스터 스위치 로그 수집 기능 구성 _ 을(를) 참조하십시오 http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-sw-ix8-setup/home.html["Broadcom 지원 BES-53248 스위치에 대한 스위치 설정 및 구성 설명서"^] 스위치 관련 로그 파일을 수집하는 데 사용되는 클러스터 상태 스위치 로그 수집을 활성화하는 데 필요한 단계를 확인합니다.

* 관련 정보 *

https://hwu.netapp.com["Hardware Universe"^]

http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-sw-ix8-setup/home.html["Broadcom 지원 BES-53248 스위치에 대한 스위치 설정 및 구성 설명서"^]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetApp KB 문서: 예약된 유지 관리 창에서 자동 케이스 생성을 억제하는 방법"^]
