---
permalink: switch-bes-53248/replace-switch.html 
sidebar: sidebar 
keywords: replace, replacing, defective, broadcom-supported, bes, cluster, switch, network, nondisruptive, procedure, ndu, replace a broadcom-supported bes-53428 cluster switch - bes-53428 switches 
summary: '클러스터 네트워크에서 결함이 있는 Broadcom 지원 BES-53248 클러스터 스위치를 교체하는 것은 무중단 절차\(NDU\)입니다.' 
---
= Broadcom 지원 BES-53248 클러스터 스위치를 교체합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 네트워크에서 결함이 있는 Broadcom 지원 BES-53248 클러스터 스위치를 교체하려면 다음 단계를 수행하십시오. 이 절차는 NDU(무중단 절차)입니다.

.예를 참조하십시오
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 기존 BES-53248 스위치의 이름은 CS1, CS2입니다.
* 새로운 BES-53248 스위치의 이름은 newcs2입니다.
* 노드 이름은 노드1과 노드2입니다.
* 각 노드의 클러스터 포트 이름은 e0a, e0b 입니다.
* 클러스터 LIF 이름은 node1의 node1_clus1 및 node1_clus2, node2의 node2_clus1 및 node2_clus2 입니다.
* 모든 클러스터 노드의 변경 프롬프트는 'cluster1:::>'입니다


.토폴로지 정보
이 절차는 다음과 같은 클러스터 네트워크 토폴로지를 기반으로 합니다.

.토폴로지 예를 보여 줍니다
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false


Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false


cluster1::> *network interface show -vserver Cluster*
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true


cluster1::> *network device-discovery show -protocol cdp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       0/2               BES-53248
            e0b    cs2                       0/2               BES-53248
node1      /cdp
            e0a    cs1                       0/1               BES-53248
            e0b    cs2                       0/1               BES-53248
----
[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater

Device ID                Intf      Holdtime  Capability Platform         Port ID
------------------------ --------- --------- ---------- ---------------- ---------
node1                    0/1       175       H          FAS2750          e0a
node2                    0/2       152       H          FAS2750          e0a
cs2                      0/55      179       R          BES-53248        0/55
cs2                      0/56      179       R          BES-53248        0/56


(cs2)# show isdp neighbors

Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater

Device ID                Intf      Holdtime  Capability Platform         Port ID
------------------------ --------- --------- ---------- ---------------- ---------
node1                    0/1       129       H          FAS2750          e0b
node2                    0/2       165       H          FAS2750          e0b
cs1                      0/55      179       R          BES-53248        0/55
cs1                      0/56      179       R          BES-53248        0/56
----
====
.단계
. 를 검토합니다 link:replace-switch-reqs.html["교체 요구 사항"].
. 이 클러스터에서 AutoSupport가 활성화되어 있는 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
'System node AutoSupport invoke-node * -type all-message maINT=xh'

+
여기서 _x_는 유지보수 기간(시간)입니다.

+

NOTE: AutoSupport 메시지는 유지보수 기간 동안 자동 케이스 생성이 억제되도록 이 유지보수 작업의 기술 지원에 알립니다.

. 적절한 RCF(Reference Configuration File)와 이미지를 스위치에 설치하고 newcs2를 설치한 후 필요한 사이트 준비를 합니다.
+
필요한 경우 새 스위치에 적합한 버전의 RCF 및 EFOS 소프트웨어를 확인, 다운로드 및 설치합니다. 새 스위치가 올바르게 설정되어 있고 RCF 및 EFOS 소프트웨어 업데이트가 필요하지 않은 경우 2단계를 계속 진행하십시오.

+
.. 에서 클러스터 스위치에 해당하는 Broadcom EFOS 소프트웨어를 다운로드할 수 있습니다 https://www.broadcom.com/support/bes-switch["Broadcom Ethernet 스위치 지원"^] 사이트. 다운로드 페이지의 단계에 따라 설치할 ONTAP 소프트웨어 버전에 대한 EFOS 파일을 다운로드합니다.
.. 에서 적절한 RCF를 사용할 수 있습니다 https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom 클러스터 스위치"^] 페이지. 다운로드 페이지의 단계에 따라 설치하는 ONTAP 소프트웨어 버전에 맞는 올바른 RCF를 다운로드하십시오.


. 새 스위치에서 로 로그인합니다 `admin` 노드 클러스터 인터페이스(포트 1에서 16)에 연결되는 모든 포트를 종료합니다.
+

NOTE: 추가 포트에 대한 추가 라이센스를 구입한 경우 이 포트도 종료합니다.

+
교체 중인 스위치가 작동하지 않고 전원이 꺼져 있는 경우 클러스터 노드의 LIF는 각 노드의 다른 클러스터 포트로 페일오버했어야 합니다.

+

NOTE: "활성화" 모드로 들어가려면 비밀번호가 필요하지 않습니다.

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
User: *admin*
Password:
(newcs2)> *enable*
(newcs2)# *config*
(newcs2)(config)# *interface 0/1-0/16*
(newcs2)(interface 0/1-0/16)# *shutdown*
(newcs2)(interface 0/1-0/16)# *exit*
(newcs2)(config)# *exit*
(newcs2)#
----
====
. 모든 클러스터 LIF에 '자동 되돌리기'가 설정되어 있는지 확인합니다.
+
'network interface show-vserver Cluster-fields auto-revert'

+
.토폴로지 예를 보여 줍니다
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster -fields auto-revert*

Logical
Vserver   Interface    Auto-revert
--------- ------------ ------------
Cluster   node1_clus1  true
Cluster   node1_clus2  true
Cluster   node2_clus1  true
Cluster   node2_clus2  true
----
====
. BES-53248 스위치 CS1에서 ISL 포트 0/55 및 0/56 종료:
+
.토폴로지 예를 보여 줍니다
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *config*
(cs1)(config)# *interface 0/55-0/56*
(cs1)(interface 0/55-0/56)# *shutdown*
----
====
. BES-53248 CS2 스위치에서 모든 케이블을 분리한 다음 BES-53248 newcs2 스위치의 동일한 포트에 연결합니다.
. CS1과 newcs2 스위치 사이에 ISL 포트 0/55 및 0/56을 가져와 포트 채널 작동 상태를 확인합니다.
+
포트 채널 1/1의 링크 상태는 * UP * 이어야 하며 모든 구성원 포트는 포트 활성 머리글 아래에 True여야 합니다.

+
.예제 보기
[%collapsible]
====
이 예에서는 ISL 포트 0/55 및 0/56을 활성화하고 스위치 CS1의 포트 채널 1/1에 대한 링크 상태를 표시합니다.

[listing, subs="+quotes"]
----
(cs1)# *config*
(cs1)(config)# *interface 0/55-0/56*
(cs1)(interface 0/55-0/56)# *no shutdown*
(cs1)(interface 0/55-0/56)# *exit*
(cs1)# *show port-channel 1/1*

Local Interface................................ 1/1
Channel Name................................... Cluster-ISL
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Dynamic
Port-channel Min-links......................... 1
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port       Port
Ports  Timeout       Speed      Active
------ ------------- ---------- -------
0/55   actor/long    100G Full  True
       partner/long
0/56   actor/long    100G Full  True
       partner/long
----
====
. 새 스위치 newcs2에서 노드 클러스터 인터페이스(포트 1에서 16)에 연결된 모든 포트를 다시 사용하도록 설정합니다.
+

NOTE: 추가 포트에 대한 추가 라이센스를 구입한 경우 이 포트도 종료합니다.

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
User:admin
Password:
(newcs2)> *enable*
(newcs2)# *config*
(newcs2)(config)# *interface 0/1-0/16*
(newcs2)(interface 0/1-0/16)# *no shutdown*
(newcs2)(interface 0/1-0/16)# *exit*
(newcs2)(config)# *exit*
----
====
. 포트 e0b가 * UP * 인지 확인:
+
네트워크 포트 표시 - IPSpace 클러스터

+
.예제 보기
[%collapsible]
====
출력은 다음과 비슷해야 합니다.

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e0a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000  healthy  false

Node: node2
                                                                        Ignore
                                                   Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ----- ----------- -------- -------
e0a       Cluster      Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000  auto/auto   -        false
----
====
. 이전 단계에서 사용한 것과 같은 노드에서 노드 1의 클러스터 LIF 노드 1_clus2가 자동 되돌아갈 때까지 기다립니다.
+
.예제 보기
[%collapsible]
====
이 예제에서 노드 1의 LIF node1_clus2는 "홈"이 "참"이고 포트가 e0b이면 성공적으로 되돌려집니다.

다음 명령을 실행하면 두 노드의 LIF에 대한 정보가 표시됩니다. 첫 번째 노드 가져오기는 두 클러스터 인터페이스에 대해 "홈"이 "참"이고 노드 1의 "e0a"와 "e0b"의 예에서 올바른 포트 할당을 표시하는 경우 성공합니다.

[listing, subs="+quotes"]
----
cluster::> *network interface show -vserver Cluster*

            Logical      Status     Network            Current    Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node       Port    Home
----------- ------------ ---------- ------------------ ---------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1      e0a     true
            node1_clus2  up/up      169.254.49.125/16  node1      e0b     true
            node2_clus1  up/up      169.254.47.194/16  node2      e0a     true
            node2_clus2  up/up      169.254.19.183/16  node2      e0a     false
----
====
. 클러스터의 노드에 대한 정보를 표시합니다.
+
'클러스터 쇼'

+
.예제 보기
[%collapsible]
====
이 예에서는 이 클러스터의 노드 1과 노드2의 노드 상태가 "참"임을 보여 줍니다.

[listing, subs="+quotes"]
----
cluster1::> *cluster show*
Node   Health   Eligibility   Epsilon
------ -------- ------------  --------
node1  true     true          true
node2  true     true          true
----
====
. 다음 클러스터 네트워크 구성을 확인합니다.
+
네트워크 포트 쇼

+
네트워크 인터페이스 쇼

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*
Node: node1
                                                                       Ignore
                                       Speed(Mbps)            Health   Health
Port      IPspace     Broadcast Domain Link MTU   Admin/Oper  Status   Status
--------- ----------- ---------------- ---- ----- ----------- -------- ------
e0a       Cluster     Cluster          up   9000  auto/10000  healthy  false
e0b       Cluster     Cluster          up   9000  auto/10000  healthy  false

Node: node2
                                                                       Ignore
                                        Speed(Mbps)           Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  healthy  false
e0b       Cluster      Cluster          up   9000 auto/10000  healthy  false


cluster1::> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true
4 entries were displayed.
----
====
. 클러스터 네트워크가 정상인지 확인합니다.
+
'ISDP 네이버 표시

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs1)# *show isdp neighbors*
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
S - Switch, H - Host, I - IGMP, r - Repeater
Device ID    Intf    Holdtime    Capability    Platform    Port ID
---------    ----    --------    ----------    --------    --------
node1        0/1     175         H             FAS2750     e0a
node2        0/2     152         H             FAS2750     e0a
newcs2       0/55    179         R             BES-53248   0/55
newcs2       0/56    179         R             BES-53248   0/56

(newcs2)# *show isdp neighbors*
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
S - Switch, H - Host, I - IGMP, r - Repeater

Device ID    Intf    Holdtime    Capability    Platform    Port ID
---------    ----    --------    ----------    --------    --------
node1        0/1     129         H             FAS2750     e0b
node2        0/2     165         H             FAS2750     e0b
cs1          0/55    179         R             BES-53248   0/55
cs1          0/56    179         R             BES-53248   0/56
----
====
. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화합니다.
+
'System node AutoSupport invoke-node * -type all-message maINT=end'



.다음 단계
스위치를 교체한 후에는 다음을 수행할 수 있습니다. link:../switch-cshm/config-overview.html["스위치 상태 모니터링 구성"].
