---
permalink: switch-bes-53248/replace-edit-rcf.html 
sidebar: sidebar 
keywords: activating licenses,additional licenses,licenses in the RCF,edit rcf 
summary: 새로 라이센스가 부여된 포트를 활성화하려면 최신 버전의 RCF를 편집하고 해당 포트 세부 정보의 주석을 해제해야 합니다. 기본 라이센스는 포트 0/1 - 0/16 및 0/55 - 0/56 을 활성화하며, 새로 라이센스가 부여된 포트는 사용 가능한 라이센스의 유형과 수에 따라 포트 0/17 - 0/54 사이에 있게 됩니다. 
---
= RCF(Reference Configuration File) 편집
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새로 라이센스가 부여된 포트를 활성화하려면 최신 버전의 RCF를 편집하고 해당 포트 세부 정보의 주석을 해제해야 합니다. 기본 라이센스는 포트 0/1 - 0/16 및 0/55 - 0/56 을 활성화하며, 새로 라이센스가 부여된 포트는 사용 가능한 라이센스의 유형과 수에 따라 포트 0/17 - 0/54 사이에 있게 됩니다.


NOTE: 이전에 설치된 RCF를 편집하려고 하면 RCF의 다른 영역에 대한 기존 구성이 있으므로 프로세스가 실패할 수 있습니다. 를 참조하십시오  a previously installed RCF file.

BES-53248 클러스터 스위치에서 사용할 수 있는 라이센스 유형에 대한 자세한 내용은 을 참조하십시오 link:configure-licenses.html["BES-53248 클러스터 스위치용 라이센스 설치"].

예를 들어, SW-BES54248-40-100G-LIC 라이센스를 활성화하려면 RCF에서 다음 섹션의 주석을 해제해야 합니다.

[listing]
----
.
.
!
! 2-port or 6-port 40/100GbE node port license block
!
interface 0/49
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/50
no shutdown
description "40/100GbE Node Port"
!speed 100G full-duplex
speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/51
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/52
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/53
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
interface 0/54
no shutdown
description "40/100GbE Node Port"
speed 100G full-duplex
!speed 40G full-duplex
service-policy in WRED_100G
spanning-tree edgeport
mtu 9216
switchport mode trunk
datacenter-bridging
priority-flow-control mode on
priority-flow-control priority 5 no-drop
exit
exit
!
.
.
----

NOTE: 0/49에서 0/54까지의 고속 포트에서는 각 포트에 대해 코멘트를 하지 않고 각 포트에 대해 RCF에 하나의 * 속도 * 라인만을 주석으로 표시하되, 다음 중 하나를 수행합니다.

* 속도 100G 전이중
* 속도 40G 전이중


예를 참조하십시오.

17/0/48 사이의 저속 포트의 경우, 적절한 라이센스가 활성화된 경우 전체 8포트 섹션의 설명을 해제하십시오.



== 이전에 설치된 RCF 파일을 편집합니다

이전에 설치된 RCF 파일을 편집하고 'cript apply' 명령을 실행한 후 다음과 같은 오류 메시지가 나타날 수 있습니다.

[listing, subs="+quotes"]
----
(CS1)# *script apply BES-53248_RCF_v1.6-Cluster-HA.scr*
Are you sure you want to apply the configuration script? (y/n) *y*
----
y * 를 선택하면 다음과 같은 오류 메시지가 나타납니다.

[listing]
----
config
 ...
 match cos 5
 Unrecognized command : match cos 5
 Error! in configuration script file at line number 40.
 CLI Command :: match cos 5.
 Aborting script.
----
이 문제를 방지하거나 해결하려면 다음 옵션 중 하나를 선택합니다.

* 오류를 방지하려면 다음 절차를 따르십시오.
+
.. 새 포트 구성만 포함하는 두 번째 RCF를 생성합니다.
.. 두 번째 RCF를 스위치에 복사합니다.
.. '스크립트 적용' 명령을 사용하여 스위치에 스크립트를 적용합니다.


* 오류를 해결하려면 다음 기술 문서를 참조하십시오. link:++https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Storage_Systems%2FFabric%252C_Interconnect_and_Management_Switches%2FError%2521_in_configuration_script_file_at_line_number_XX_when_applying_a_new_RCF%20%20%20++["오류! 새로운 RCF를 적용할 때 라인 번호 XX에 있는 구성 스크립트 파일"^]

