---
permalink: switch-bes-53248/replace-install-rcf.html 
sidebar: sidebar 
keywords: rcf,install rcf,bes-53248 switch 
summary: BES-53248 클러스터 스위치를 처음 설정하고 새 라이센스 또는 라이센스를 적용한 후 RCF를 설치할 수 있습니다. 이전 버전에서 RCF를 업그레이드하는 경우 파일이 효과적으로 병합되고 여기에 설명된 단계를 완료합니다. 
---
= RCF(Reference Configuration File) 설치
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 클러스터 스위치를 처음 설정하고 새 라이센스 또는 라이센스를 적용한 후 RCF를 설치할 수 있습니다. 이전 버전에서 RCF를 업그레이드하는 경우 Broadcom 스위치 설정을 재설정하고 기본 구성을 수행하여 RCF를 다시 적용해야 합니다. RCF를 업그레이드하거나 변경하려면 항상 이 작업을 수행해야 합니다. 다음을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/Error!_in_configuration_script_file_at_line_number_XX_when_applying_a_new_RCF["KB 문서를 참조하십시오"^] 를 참조하십시오.



== Broadcom IP 스위치를 출하 시 기본값으로 재설정합니다

새 스위치 소프트웨어 버전과 RCFs를 설치하기 전에 Broadcom 스위치 설정을 지우고 기본 구성을 수행해야 합니다.

.이 작업에 대해
* 각 클러스터 스위치에서 이 단계를 반복해야 합니다.
* 직렬 콘솔을 사용하여 스위치에 연결해야 합니다.
* 이 작업은 관리 네트워크의 구성을 재설정합니다.


.단계
. 상승된 권한의 명령 프롬프트('#')로 변경합니다
+
[listing]
----
(cs2)> enable
(cs2) #
----
. 시작 구성을 지우고 배너를 제거합니다
+
.. 시작 구성을 지웁니다.
+
* 'erase startup-config' *

+
[listing]
----
(cs2) #erase startup-config
Are you sure you want to clear the configuration? (y/n) y
(cs2) #
----
+
이 명령은 배너를 지우지 않습니다.

.. 배너 제거:
+
"세트 피너 없음" *

+
[listing]
----
(cs2) #configure
(cs2)(Config) # no set clibanner
(cs2)(Config) #
----


. 스위치를 재부팅합니다. * '(CS2) #reload * '
+
[listing]
----
Are you sure you would like to reset the system? (y/n) y
----
+

NOTE: 스위치를 다시 로드하기 전에 저장되지 않은 구성이나 변경된 구성을 저장할지 묻는 메시지가 나타나면 * No * 를 선택합니다.

. 스위치가 다시 로드될 때까지 기다린 다음 스위치에 로그인합니다.
+
기본 사용자는 ""admin""이고 암호가 설정되어 있지 않습니다. 다음과 유사한 프롬프트가 표시됩니다.

+
[listing]
----
(Routing)>
----
. 상승된 권한의 명령 프롬프트로 변경합니다.
+
"활성화"를 선택합니다

+
[listing]
----
Routing)> enable
(Routing) #
----
. service port protocol을 none으로 설정한다.
+
'저빙항프로토콜 없음

+
[listing]
----
(Routing) #serviceport protocol none
Changing protocol mode will reset ip configuration.
Are you sure you want to continue? (y/n) y

(Routing) #
----
. IP 주소를 서비스 포트에 할당합니다.
+
'erviceport IP_IP-address__netmask__gateway_'

+
다음 예에서는 서브넷 "255.255.255.0" 및 게이트웨이 "10.10.10.1"이 있는 서비스 포트에 할당된 IP 주소 "10.10.10.10"을 보여 줍니다.

+
[listing]
----
(Routing) #serviceport ip 10.10.10.10 255.255.255.0 10.10.10.1
----
. 서비스 포트가 올바르게 구성되었는지 확인합니다.
+
서비스서비스

+
다음 예에서는 포트가 작동 가능하며 올바른 주소가 할당되었음을 보여 줍니다.

+
[listing]
----
(Routing) #show serviceport

Interface Status............................... Up
IP Address..................................... 10.10.10.10
Subnet Mask.................................... 255.255.255.0
Default Gateway................................ 10.10.10.1
IPv6 Administrative Mode....................... Enabled
IPv6 Prefix is ................................ fe80::dac4:97ff:fe56:87d7/64
IPv6 Default Router............................ fe80::222:bdff:fef8:19ff
Configured IPv4 Protocol....................... None
Configured IPv6 Protocol....................... None
IPv6 AutoConfig Mode........................... Disabled
Burned In MAC Address.......................... D8:C4:97:56:87:D7

(Routing) #
----
. 필요한 경우 SSH 서버를 구성합니다.
+

NOTE: RCF 파일은 텔넷 프로토콜을 비활성화합니다. SSH 서버를 구성하지 않으면 직렬 포트 연결을 통해서만 브리지에 액세스할 수 있습니다.

+
.. RSA 키를 생성합니다.
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate rsa
----
.. DSA 키 생성(선택 사항)
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate dsa
----
.. FIPS 호환 버전의 EFOS를 사용하는 경우 ECDSA 키를 생성합니다. 다음 예제에서는 길이가 256인 키를 만듭니다. 유효한 값은 256, 384 또는 521입니다.
+
[listing]
----
(Routing) #configure
(Routing) (Config)#crypto key generate ecdsa 256
----
.. SSH 서버를 활성화합니다.
+
필요한 경우 구성 컨텍스트를 종료합니다.

+
[listing]
----
(Routing) (Config)#end
(Routing) #ip ssh server enable
----
+

NOTE: 키가 이미 있으면 덮어쓸지 묻는 메시지가 나타날 수 있습니다.



. 필요한 경우 도메인 및 이름 서버를 구성합니다.
+
'설정'을 클릭합니다

+
다음 예에서는 IP domain과 IP name server 명령을 보여 줍니다.

+
[listing]
----
(Routing) # configure
(Routing) (Config)#ip domain name lab.netapp.com
(Routing) (Config)#ip name server 10.99.99.1 10.99.99.2
(Routing) (Config)#exit
(Routing) (Config)#
----
. 필요한 경우 시간대 및 시간 동기화(SNTP)를 구성합니다.
+
다음 예에서는 SNTP 서버의 IP 주소와 상대 시간대 등을 지정하는 'sNTP' 명령어를 보여준다.

+
[listing]
----
(Routing) #
(Routing) (Config)#sntp client mode unicast
(Routing) (Config)#sntp server 10.99.99.5
(Routing) (Config)#clock timezone -7
(Routing) (Config)#exit
(Routing) (Config)#
----
. 스위치 이름 구성:
+
호스트 이름 CS2

+
스위치 프롬프트에는 새 이름이 표시됩니다.

+
[listing]
----
(Routing) # hostname cs2

(cs2) #
----
. 구성을 저장합니다.
+
쓰기 메모리

+
다음 예와 유사한 프롬프트 및 출력이 표시됩니다.

+
[listing]
----
(cs2) #write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .


Configuration Saved!

(cs2) #
----
. 다른 클러스터 스위치에 대해 이전 단계를 반복합니다.




== RCF(Reference Configuration File) 설치

.단계
. 클러스터 스위치를 관리 네트워크에 연결합니다.
. ping 명령을 사용하여 EFOS, 라이센스 및 RCF를 호스팅하는 서버에 대한 연결을 확인합니다.
+
연결에 문제가 있으면 라우팅되지 않은 네트워크를 사용하여 IP 주소 192.168.x 또는 172.19.x를 사용하여 서비스 포트를 구성합니다 나중에 서비스 포트를 운영 관리 IP 주소로 재구성할 수 있습니다.

+
이 예에서는 스위치가 IP 주소 172.19.2.1로 서버에 연결되어 있는지 확인합니다.

+
[listing]
----
(cs2) # ping 172.19.2.1
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. copy 명령을 사용하여 BES-53248 클러스터 스위치에 RCF를 설치합니다.
+
[listing]
----
(cs2) # copy http://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr

Remote Password ********

Mode........................................... HTTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... BES-53248_RCF_v1.6-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_RCF_v1.6-Cluster-HA.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...

Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
+

NOTE: 환경에 따라 copy 명령에 "+copy와 같은 이중 슬래시를 사용해야 할 수도 있습니다 http://172.19.2.1//tmp/BES-53248_RCF_v1.6-Cluster-HA.txt[] NVRAM: 스크립트 BES-53248_RCF_v1.6 - Cluster-HA.SCR+'.

+

NOTE: 스크립트를 호출하기 전에 '.scr' 확장자를 파일 이름의 일부로 설정해야 합니다. 이 확장은 EFOS 운영 체제의 확장입니다. 스위치는 스크립트가 스위치에 다운로드되면 자동으로 스크립트의 유효성을 검사하며 출력은 콘솔로 전달됩니다. 또한 콘솔 화면에 맞게 '.scr'의 이름을 변경하여 가독성을 높일 수도 있습니다(예: '+copy) http://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt[] NVRAM: 스크립트 RCF_v1.6 - Cluster-HA.scr+'.

. 스크립트가 다운로드되어 지정한 파일 이름에 저장되었는지 확인합니다.
+
'스크립트 목록'

+
[listing]
----
(cs2) # script list

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
BES-53248_RCF_v1.6-Cluster-HA.scr        2241         2020 09 30 05:41:00

1 configuration script(s) found.
----
. 스위치에 스크립트를 적용합니다.
+
'스크립트 적용'

+
[listing]
----
(cs2) # script apply BES-53248_RCF_v1.6-Cluster-HA.scr

Are you sure you want to apply the configuration script? (y/n) y

The system has unsaved changes.
Would you like to save them now? (y/n) y
Config file 'startup-config' created successfully .
Configuration Saved!

Configuration script 'BES-53248_RCF_v1.6-Cluster-HA.scr' applied.
----
. RCF를 적용한 후 추가 라이센스에 대한 포트를 확인합니다.
+
'모두 포트 보기|분리 제외'

+
[listing]
----
(cs2) # show port all \| exclude Detach

                 Admin     Physical     Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode         Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Enable    Auto                    Down   Enable  Enable long
0/2              Enable    Auto                    Down   Enable  Enable long
0/3              Enable    Auto                    Down   Enable  Enable long
0/4              Enable    Auto                    Down   Enable  Enable long
0/5              Enable    Auto                    Down   Enable  Enable long
0/6              Enable    Auto                    Down   Enable  Enable long
0/7              Enable    Auto                    Down   Enable  Enable long
0/8              Enable    Auto                    Down   Enable  Enable long
0/9              Enable    Auto                    Down   Enable  Enable long
0/10             Enable    Auto                    Down   Enable  Enable long
0/11             Enable    Auto                    Down   Enable  Enable long
0/12             Enable    Auto                    Down   Enable  Enable long
0/13             Enable    Auto                    Down   Enable  Enable long
0/14             Enable    Auto                    Down   Enable  Enable long
0/15             Enable    Auto                    Down   Enable  Enable long
0/16             Enable    Auto                    Down   Enable  Enable long
0/49             Enable    40G Full                Down   Enable  Enable long
0/50             Enable    40G Full                Down   Enable  Enable long
0/51             Enable    100G Full               Down   Enable  Enable long
0/52             Enable    100G Full               Down   Enable  Enable long
0/53             Enable    100G Full               Down   Enable  Enable long
0/54             Enable    100G Full               Down   Enable  Enable long
0/55             Enable    100G Full               Down   Enable  Enable long
0/56             Enable    100G Full               Down   Enable  Enable long
----
. 스위치에서 변경 사항이 적용되었는지 확인합니다.
+
'show running-config'를 선택합니다

+
[listing]
----
(cs2) # show running-config
----
. 스위치를 재부팅할 때 시작 구성이 되도록 실행 중인 구성을 저장합니다.
+
쓰기 메모리

+
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
. 스위치를 재부팅하고 실행 중인 구성이 올바른지 확인합니다.
+
다시 로드

+
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n) y

System will now restart!
----

