---
permalink: switch-bes-53248/replace-prepare-controller.html 
sidebar: sidebar 
keywords: BES-53248 switches,preparing for upgrade,upgrade bes-53248 switch 
summary: 이 절차를 사용하여 BES-53248 클러스터 스위치 업그레이드를 위한 컨트롤러를 준비할 수 있습니다. 
---
= 클러스터 스위치의 업그레이드를 위해 컨트롤러를 준비합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 절차를 사용하여 BES-53248 클러스터 스위치 업그레이드를 위한 컨트롤러를 준비할 수 있습니다.

.단계
. 클러스터 스위치를 관리 네트워크에 연결합니다.
. ping 명령을 사용하여 EFOS, 라이센스 및 RCF를 호스팅하는 서버에 대한 연결을 확인합니다.
+
이 문제가 발생하면 라우팅되지 않은 네트워크를 사용하여 IP 주소 192.168.x 또는 172.19.x를 사용하여 서비스 포트를 구성합니다 나중에 서비스 포트를 운영 관리 IP 주소로 재구성할 수 있습니다.

+
이 예에서는 스위치가 IP 주소 172.19.2.1로 서버에 연결되어 있는지 확인합니다.

+
[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. 클러스터 포트가 정상 상태이며 명령을 사용하여 링크가 있는지 확인합니다.
+
네트워크 포트 표시 - IPSpace 클러스터

+
다음 예는 Link 값이 Up 이고 Health Status가 Healthy인 모든 포트의 출력 유형을 보여줍니다.

+
[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
------ ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
-----  ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false
----
. 클러스터 LIF가 관리 및 운영 측면에서 홈 포트에 상주하고 있는지 확인하려면 다음 명령을 사용하십시오.
+
'network interface show-vserver cluster'

+
이 예제에서 '-vserver' 매개 변수는 클러스터 포트와 연결된 LIF에 대한 정보를 표시합니다. '상태 관리/작업'은 반드시 가동되어야 하며 '홈'은 진실이어야 합니다.

+
[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster*

          Logical      Status     Network             Current       Current Is
Vserver   Interface    Admin/Oper Address/Mask        Node          Port    Home
--------- ----------   ---------- ------------------  ------------- ------- ----
Cluster
          node1_clus1
                       up/up      169.254.217.125/16  node1         e0a     true
          node1_clus2
                       up/up      169.254.205.88/16   node1         e0b     true
          node2_clus1
                       up/up      169.254.252.125/16  node2         e0a     true
          node2_clus2
                       up/up      169.254.110.131/16  node2         e0b     true
----

