---
permalink: switch-bes-53248/replace-install-rcf.html 
sidebar: sidebar 
keywords: rcf,install rcf,bes-53248 switch 
summary: BES-53248 클러스터 스위치를 처음 설정하고 새 라이센스 또는 라이센스를 적용한 후 RCF를 설치할 수 있습니다. 이전 버전에서 RCF를 업그레이드하는 경우 파일이 효과적으로 병합되고 여기에 설명된 단계를 완료합니다. 
---
= RCF(Reference Configuration File) 설치
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 클러스터 스위치를 처음 설정하고 새 라이센스 또는 라이센스를 적용한 후 RCF를 설치할 수 있습니다. 이전 버전에서 RCF를 업그레이드하는 경우 파일이 효과적으로 병합되고 여기에 설명된 단계를 완료합니다.

.단계
. 클러스터 스위치를 관리 네트워크에 연결합니다.
. ping 명령을 사용하여 EFOS, 라이센스 및 RCF를 호스팅하는 서버에 대한 연결을 확인합니다.
+
연결에 문제가 있으면 라우팅되지 않은 네트워크를 사용하여 IP 주소 192.168.x 또는 172.19.x를 사용하여 서비스 포트를 구성합니다 나중에 서비스 포트를 운영 관리 IP 주소로 재구성할 수 있습니다.

+
이 예에서는 스위치가 IP 주소 172.19.2.1로 서버에 연결되어 있는지 확인합니다.

+
[listing]
----
(cs2) # ping 172.19.2.1
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. copy 명령을 사용하여 BES-53248 클러스터 스위치에 RCF를 설치합니다.
+
[listing]
----
(cs2) # copy http://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt nvram:script BES-53248_RCF_v1.6-Cluster-HA.scr

Remote Password ********

Mode........................................... HTTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... BES-53248_RCF_v1.6-Cluster-HA.txt
Data Type...................................... Config Script
Destination Filename........................... BES-53248_RCF_v1.6-Cluster-HA.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. Please wait...

Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
+

NOTE: 환경에 따라 copy 명령에 "+copy와 같은 이중 슬래시를 사용해야 할 수도 있습니다 http://172.19.2.1//tmp/BES-53248_RCF_v1.6-Cluster-HA.txt[] NVRAM: 스크립트 BES-53248_RCF_v1.6 - Cluster-HA.SCR+'.

+

NOTE: 스크립트를 호출하기 전에 '.scr' 확장자를 파일 이름의 일부로 설정해야 합니다. 이 확장은 EFOS 운영 체제의 확장입니다. 스위치는 스크립트가 스위치에 다운로드되면 자동으로 스크립트의 유효성을 검사하며 출력은 콘솔로 전달됩니다. 또한 콘솔 화면에 맞게 '.scr'의 이름을 변경하여 가독성을 높일 수도 있습니다(예: '+copy) http://172.19.2.1/tmp/BES-53248_RCF_v1.6-Cluster-HA.txt[] NVRAM: 스크립트 RCF_v1.6 - Cluster-HA.scr+'.

. 스크립트가 다운로드되어 지정한 파일 이름에 저장되었는지 확인합니다.
+
'스크립트 목록'

+
[listing]
----
(cs2) # script list

Configuration Script Name                  Size(Bytes)  Date of Modification
-----------------------------------------  -----------  --------------------
BES-53248_RCF_v1.6-Cluster-HA.scr        2241         2020 09 30 05:41:00

1 configuration script(s) found.
----
. 스위치에 스크립트를 적용합니다.
+
'스크립트 적용'

+
[listing]
----
(cs2) # script apply BES-53248_RCF_v1.6-Cluster-HA.scr

Are you sure you want to apply the configuration script? (y/n) y

The system has unsaved changes.
Would you like to save them now? (y/n) y
Config file 'startup-config' created successfully .
Configuration Saved!

Configuration script 'BES-53248_RCF_v1.6-Cluster-HA.scr' applied.
----
. RCF를 적용한 후 추가 라이센스에 대한 포트를 확인합니다.
+
'모두 포트 보기|분리 제외'

+
[listing]
----
(cs2) # show port all \| exclude Detach

                 Admin     Physical     Physical   Link   Link    LACP   Actor
Intf      Type   Mode      Mode         Status     Status Trap    Mode   Timeout
--------- ------ --------- ---------- ---------- ------ ------- ------ --------
0/1              Enable    Auto                    Down   Enable  Enable long
0/2              Enable    Auto                    Down   Enable  Enable long
0/3              Enable    Auto                    Down   Enable  Enable long
0/4              Enable    Auto                    Down   Enable  Enable long
0/5              Enable    Auto                    Down   Enable  Enable long
0/6              Enable    Auto                    Down   Enable  Enable long
0/7              Enable    Auto                    Down   Enable  Enable long
0/8              Enable    Auto                    Down   Enable  Enable long
0/9              Enable    Auto                    Down   Enable  Enable long
0/10             Enable    Auto                    Down   Enable  Enable long
0/11             Enable    Auto                    Down   Enable  Enable long
0/12             Enable    Auto                    Down   Enable  Enable long
0/13             Enable    Auto                    Down   Enable  Enable long
0/14             Enable    Auto                    Down   Enable  Enable long
0/15             Enable    Auto                    Down   Enable  Enable long
0/16             Enable    Auto                    Down   Enable  Enable long
0/49             Enable    40G Full                Down   Enable  Enable long
0/50             Enable    40G Full                Down   Enable  Enable long
0/51             Enable    100G Full               Down   Enable  Enable long
0/52             Enable    100G Full               Down   Enable  Enable long
0/53             Enable    100G Full               Down   Enable  Enable long
0/54             Enable    100G Full               Down   Enable  Enable long
0/55             Enable    100G Full               Down   Enable  Enable long
0/56             Enable    100G Full               Down   Enable  Enable long
----
. 스위치에서 변경 사항이 적용되었는지 확인합니다.
+
'show running-config'를 선택합니다

+
[listing]
----
(cs2) # show running-config
----
. 스위치를 재부팅할 때 시작 구성이 되도록 실행 중인 구성을 저장합니다.
+
쓰기 메모리

+
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
. 스위치를 재부팅하고 실행 중인 구성이 올바른지 확인합니다.
+
다시 로드

+
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n) y

System will now restart!
----

