---
permalink: switch-bes-53248/replace-configure-log-collection.html 
sidebar: sidebar 
keywords: log collection feature,collect switch-related log files,ssh,crypto key 
summary: 클러스터 스위치 상태 모니터 로그 수집 기능은 ONTAP에서 스위치 관련 로그 파일을 수집하는 데 사용됩니다. 여기에 설명된 대로 BES-53248 클러스터 스위치 CLI를 사용하여 환경을 설정해야 합니다. 
---
= 클러스터 스위치 로그 수집 기능을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 스위치 상태 모니터 로그 수집 기능은 ONTAP에서 스위치 관련 로그 파일을 수집하는 데 사용됩니다. 여기에 설명된 대로 BES-53248 클러스터 스위치 CLI를 사용하여 환경을 설정해야 합니다.

.단계
. SSH 키를 생성합니다.
+
* "암호화 키 생성" *

+
[listing, subs="+quotes"]
----
(switch)# *show ip ssh*
SSH Configuration

Administrative Mode: .......................... Disabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SCP server Administrative Mode: ............... Disabled

(switch)# *config*

(switch) (Config)# *crypto key generate rsa*

Do you want to overwrite the existing RSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate dsa*

Do you want to overwrite the existing DSA keys? (y/n): *y*


(switch) (Config)# *crypto key generate ecdsa 521*

Do you want to overwrite the existing ECDSA keys? (y/n): *y*

(switch) (Config)# *aaa authorization commands "noCmdAuthList" none*
(switch) (Config)# *exit*
(switch)# *ip ssh server enable*
(switch)# *ip ssh pubkey-auth*
(switch)# *ip scp server enable*
(switch)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.
Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
. SSH가 활성화되었는지 확인합니다.
+
"IP ssh를 표시합니다." *

+
[listing, subs="+quotes"]
----
(switch)# *show ip ssh*

SSH Configuration

Administrative Mode: .......................... Enabled
SSH Port: ..................................... 22
Protocol Level: ............................... Version 2
SSH Sessions Currently Active: ................ 0
Max SSH Sessions Allowed: ..................... 5
SSH Timeout (mins): ........................... 5
Keys Present: ................................. DSA(1024) RSA(1024) ECDSA(521)
Key Generation In Progress: ................... None
SCP server Administrative Mode: ............... Disabled
----
. ONTAP 9.8 이상의 경우 명령을 사용하여 스위치 관련 로그 파일을 수집하는 클러스터 스위치 상태 모니터 로그 수집 기능을 사용하도록 설정합니다.
+
System switch ethernet log setup-password와 system switch ethernet log enable-collection

+
'시스템 스위치 이더넷 로그 설정 - 암호'를 입력합니다

+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
+
'시스템 스위치 이더넷 로그 Enable-collection'이 그 뒤를 따랐습니다

+
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
. ONTAP 9.5P15, 9.6P11, 9.7P8 이상 패치 릴리스의 경우 다음 명령을 사용하여 스위치 관련 로그 파일을 수집하는 클러스터 스위치 상태 모니터 로그 수집 기능을 사용하도록 설정합니다.
+
System cluster-switch log setup-password와 system cluster-switch log enable-collection

+
'system cluster-switch log setup-password'를 입력합니다

+
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*cs1*
*cs2*

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
+
'system cluster-switch log enable-collection'이 그 뒤에 나옵니다

+
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.
----
+

NOTE: 현재 로그 수집 명령을 사용할 수 없습니다. 을 참조하십시오 link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1225042["버그 1225042"^] 를 참조하십시오.

+

CAUTION: 이러한 명령에서 오류가 반환되면 NetApp 지원에 문의하십시오.


