---
permalink: switch-bes-53248/replace-install-efos.html 
sidebar: sidebar 
keywords: BES-53248 switches,installing EFOS software,efos 
summary: 이 절차를 사용하여 BES-53248 클러스터 스위치에 EFOS 소프트웨어를 설치할 수 있습니다. Broadcom Ethernet 스위치 지원 사이트에서 클러스터 스위치에 해당하는 Broadcom EFOS 소프트웨어를 다운로드할 수 있습니다. 
---
= EFOS 소프트웨어를 설치합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
이 절차를 사용하여 BES-53248 클러스터 스위치에 EFOS 소프트웨어를 설치할 수 있습니다. Broadcom Ethernet 스위치 지원 사이트에서 클러스터 스위치에 해당하는 Broadcom EFOS 소프트웨어를 다운로드할 수 있습니다.



==== 이 작업에 대해

====
* 다음 사항에 유의하십시오. *

* EFOS 3.4.x.x에서 EFOS 3.7.x.x 이상으로 업그레이드할 경우 스위치에서 EFOS 3.4.4.6(또는 이후 3.4.x.x 릴리즈)이 실행되고 있어야 합니다. 그 전에 릴리스를 실행 중인 경우 먼저 스위치를 EFOS 3.4.4.6(또는 그 이상 3.4.x.x 릴리스)로 업그레이드한 다음 스위치를 EFOS 3.7.x.x 이상으로 업그레이드하십시오.
* EFOS 3.4.x.x 및 3.7.x.x 이상의 구성은 다릅니다. EFOS 버전을 3.4.x.x에서 3.7.x.x 이상으로 변경하거나 그 반대로 변경하려면 스위치를 출고 시 기본값으로 재설정하고 해당 EFOS 버전의 RCF 파일을 (다시) 적용해야 합니다. 이 절차를 수행하려면 직렬 콘솔 포트를 통해 액세스해야 합니다.
* EFOS 버전 3.7.x.x 이상부터는 FIPS를 준수하지 않는 버전과 FIPS 호환 버전을 사용할 수 있습니다. FIPS를 준수하지 않는 버전에서 로 이동하거나 FIPS를 준수하는 버전으로 전환할 때 다른 단계가 적용됩니다. FIPS를 준수하지 않는 버전에서 FIPS를 준수하는 버전으로 또는 그 반대로 EFOS를 변경하면 스위치가 공장 출하 시 기본값으로 재설정됩니다. 이 절차를 수행하려면 직렬 콘솔 포트를 통해 액세스해야 합니다.


====
|===


| * 절차 * | * 현재 EFOS 버전 * | * 새로운 EFOS 버전 * | * 고급 단계 * 


 a| 
FIPS를 준수하지 않는 두 버전 간에 EFOS를 업그레이드하는 단계
 a| 
3.4.x.x
 a| 
3.4.x.x
 a| 
방법 1을 사용하여 새 EFOS 이미지 설치) 구성 및 라이센스 정보가 보존됩니다



 a| 
3.4.4.6(또는 그 이상 3.4.x.x)
 a| 
3.7.x.x 이상 비 FIPS 규격
 a| 
방법 1을 사용하여 EFOS를 업그레이드합니다. 스위치를 출고 시 기본값으로 재설정하고 EFOS 3.7.x.x 이상에 RCF 파일을 적용합니다



.2+| 3.7.x.x 이상 비 FIPS 규격  a| 
3.4.4.6(또는 그 이상 3.4.x.x)
 a| 
방법 1을 사용하여 EFOS를 다운그레이드합니다. 스위치를 출고 시 기본값으로 재설정하고 EFOS 3.4.x.x의 RCF 파일을 적용합니다



 a| 
3.7.x.x 이상 비 FIPS 규격
 a| 
방법 1을 사용하여 새 EFOS 이미지를 설치합니다. 구성 및 라이센스 정보가 유지됩니다



 a| 
3.7.x.x 이상 FIPS 규격
 a| 
3.7.x.x 이상 FIPS 규격
 a| 
방법 1을 사용하여 새 EFOS 이미지를 설치합니다. 구성 및 라이센스 정보가 유지됩니다



 a| 
FIPS 호환 EFOS 버전으로 업그레이드 단계
 a| 
FIPS 비호환
 a| 
FIPS 규격
 a| 
방법 2를 사용하여 EFOS 이미지 설치 스위치 구성 및 라이센스 정보가 손실됩니다.



 a| 
FIPS 규격
 a| 
FIPS 비호환

|===

IMPORTANT: BES-53248 클러스터 스위치를 EFOS 3.3.x.x 또는 3.4.x.x에서 EFOS 3.7.0.4 또는 3.8.0.2로 업그레이드한 후 ISL(Inter-Switch Link) 및 포트 채널이 * DOWN * 상태로 표시됩니다. 자세한 내용은 다음을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/Fabric%2C_Interconnect_and_Management_Switches/BES-53248_Cluster_Switch_NDU_failed_upgrade_to_EFOS_3.7.0.4_and_later["KB 문서를 참조하십시오"^] 를 참조하십시오.

.단계
. BES-53248 클러스터 스위치를 관리 네트워크에 연결합니다.
. "ping" 명령을 사용하여 EFOS, 라이센스 및 RCF 파일을 호스팅하는 서버에 대한 연결을 확인합니다.
+
이 예에서는 스위치가 IP 주소 172.19.2.1로 서버에 연결되어 있는지 확인합니다.

+
[listing]
----
(cs2) # ping 172.19.2.1
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. CS2에서 현재 활성 이미지 백업:
+
'How bootvar'입니다

+
[listing, subs="+quotes"]
----
(cs2) # *show bootvar*

 Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup        current-active    next-active
--------------------------------------------------------------------

    1      3.4.3.3     Q.10.22.1     3.4.3.3           3.4.3.3
(cs2) # *copy active backup*
Copying active to backup
Management access will be blocked for the duration of the operation
Copy operation successful

(cs2) # *show bootvar*

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup      current-active    next-active
--------------------------------------------------------------------

    1      3.4.3.3     3.4.3.3     3.4.3.3           3.4.3.3
(cs2) #
----
. 실행 중인 EFOS 소프트웨어 버전을 확인합니다.
+
'How version'입니다

+
[listing, subs="+quotes"]
----
(cs2) # *show version*

Switch: 1

System Description............................. Quanta IX8-B 48x25GB SFP 8x100GB QSFP, 3.4.3.3, Linux 4.4.117-ceeeb99d, 2016.05.00.04
Machine Type................................... Quanta IX8-B 48x25GB SFP 8x100GB QSFP
Machine Model.................................. IX8-B
Serial Number.................................. QTFCU38260014
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:12:3D
Software Version............................... 3.4.3.3
Operating System............................... Linux 4.4.117-ceeeb99d
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----
. 이미지 파일을 스위치에 다운로드합니다.
+
이미지 파일을 활성 이미지로 복사하는 것은 재부팅할 때 해당 이미지가 실행 중인 EFOS 버전을 설정한다는 것을 의미합니다. 이전 이미지는 백업으로 사용할 수 있습니다.

+
[listing]
----
(cs2) # copy sftp://root@172.19.2.1//tmp/EFOS-3.4.4.6.stk active
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 172.19.2.1
Path........................................... //tmp/
Filename....................................... EFOS-3.4.4.6.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
SFTP Code transfer starting...


File transfer operation completed successfully.
----
. 활성 및 백업 구성에 대한 부팅 이미지를 표시합니다.
+
'How bootvar'입니다

+
[listing, subs="+quotes"]
----
(cs2) # *show bootvar*

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     3.4.3.3     3.4.3.3            3.4.3.3            3.4.4.6
----
. 스위치를 재부팅합니다.
+
다시 로드

+
[listing, subs="+quotes"]
----
(cs2) # *reload*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully .
Configuration Saved!
System will now restart!
----
. 다시 로그인하여 EFOS 소프트웨어의 새 버전을 확인합니다.
+
'How version'입니다

+
[listing, subs="+quotes"]
----
(cs2) # *show version*

Switch: 1

System Description............................. x86_64-quanta_common_rglbmc-r0, 3.4.4.6, Linux 4.4.211-28a6fe76, 2016.05.00.04
Machine Type................................... x86_64-quanta_common_rglbmc-r0
Machine Model.................................. BES-53248
Serial Number.................................. QTFCU38260023
Maintenance Level.............................. A
Manufacturer................................... 0xbc00
Burned In MAC Address.......................... D8:C4:97:71:0F:40
Software Version............................... 3.4.4.6
Operating System............................... Linux 4.4.211-28a6fe76
Network Processing Device...................... BCM56873_A0
CPLD Version................................... 0xff040c03

Additional Packages............................ BGP-4
...............................................	QOS
...............................................	Multicast
............................................... IPv6
............................................... Routing
............................................... Data Center
............................................... OpEN API
............................................... Prototype Open API
----




== ONIE OS 설치를 사용하여 EFOS를 업그레이드합니다

한 EFOS 버전이 FIPS를 준수하고 다른 EFOS 버전이 FIPS를 준수하지 않는 경우 다음 단계를 수행할 수 있습니다. 이러한 단계는 스위치가 부팅되지 않는 경우 ONIE에서 비 FIPS 또는 FIPS 호환 EFOS 3.7.x.x 이미지를 설치하는 데 사용할 수 있습니다.


NOTE: 이 기능은 EFOS 3.7.x.x 이상 비 FIPS 준수 버전에서만 사용할 수 있습니다.

.단계
. 스위치를 ONIE 설치 모드로 부팅합니다.
+
부팅 중에 다음 화면이 나타나면 ONIE를 선택합니다.

+
[listing]
----
+--------------------------------------------------------------------+
|EFOS                                                                |
|*ONIE                                                               |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
ONIE" * 를 선택하면 스위치가 로드되고 다음 선택 사항이 표시됩니다.

+
[listing]
----
+--------------------------------------------------------------------+
|*ONIE: Install OS                                                   |
| ONIE: Rescue                                                       |
| ONIE: Uninstall OS                                                 |
| ONIE: Update ONIE                                                  |
| ONIE: Embed ONIE                                                   |
| DIAG: Diagnostic Mode                                              |
| DIAG: Burn-In Mode                                                 |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
|                                                                    |
+--------------------------------------------------------------------+
----
+
이제 스위치가 ONIE 설치 모드로 부팅됩니다.

. ONIE 검색을 중지하고 이더넷 인터페이스를 구성합니다.
+
다음 메시지가 나타나면 <Enter> 키를 눌러 ONIE 콘솔을 호출합니다.

+
[listing]
----
Please press Enter to activate this console. Info: eth0:  Checking link... up.
 ONIE:/ #
----
+

NOTE: ONIE 검색이 계속 진행되어 메시지가 콘솔에 인쇄됩니다.

+
[listing]
----
Stop the ONIE discovery
ONIE:/ # onie-discovery-stop
discover: installer mode detected.
Stopping: discover... done.
ONIE:/ #
----
. 이더넷 인터페이스를 구성하고 'ifconfig eth0 <IPAddress> netmask <netmask> up' 및 'route add default GW <gatewayAddress>'를 사용하여 라우트를 추가합니다
+
[listing]
----
ONIE:/ # ifconfig eth0 10.10.10.10 netmask 255.255.255.0 up
ONIE:/ # route add default gw 10.10.10.1
----
. ONIE 설치 파일을 호스팅하는 서버에 연결할 수 있는지 확인합니다.
+
[listing]
----
ONIE:/ # ping 50.50.50.50
PING 50.50.50.50 (50.50.50.50): 56 data bytes
64 bytes from 50.50.50.50: seq=0 ttl=255 time=0.429 ms
64 bytes from 50.50.50.50: seq=1 ttl=255 time=0.595 ms
64 bytes from 50.50.50.50: seq=2 ttl=255 time=0.369 ms
^C
--- 50.50.50.50 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.369/0.464/0.595 ms
ONIE:/ #
----
. 새 스위치 소프트웨어를 설치합니다.
+
[listing]
----
ONIE:/ # onie-nos-install http:// 50.50.50.50/Software/onie-installer-x86_64
discover: installer mode detected.
Stopping: discover... done.
Info: Fetching http:// 50.50.50.50/Software/onie-installer-3.7.0.4 ...
Connecting to 50.50.50.50 (50.50.50.50:80)
installer            100% |*******************************| 48841k  0:00:00 ETA
ONIE: Executing installer: http:// 50.50.50.50/Software/onie-installer-3.7.0.4
Verifying image checksum ... OK.
Preparing image archive ... OK.
----
+
소프트웨어가 설치되고 스위치를 재부팅합니다. 스위치가 새 EFOS 버전으로 정상적으로 재부팅되도록 합니다.

. 새 스위치 소프트웨어 'How bootvar'가 설치되어 있는지 확인합니다
+
[listing, subs="+quotes"]
----
(cs2) # *show bootvar*
Image Descriptions
active :
backup :
Images currently available on Flash
---- 	----------- -------- --------------- ------------
unit 	active 	    backup   current-active  next-active
---- 	----------- -------- --------------- ------------
1 	  3.7.0.4     3.7.0.4  3.7.0.4         3.7.0.4
(cs2) #
----
. 설치를 완료합니다.
+
구성이 적용되지 않고 스위치가 재부팅되고 출하 시 기본값으로 재설정됩니다.



* 관련 정보 *

https://www.broadcom.com/support/bes-switch["Broadcom Ethernet 스위치 지원"^]
