---
permalink: switch-bes-53248/replace-upgrade.html 
sidebar: sidebar 
keywords: BES-53248 switches,upgrading,BES-53248 switches 
summary: 'BES-53248 클러스터 스위치 업그레이드는 컨트롤러를 업그레이드하기 위한 준비, EFOS 소프트웨어, 라이센스 및 RCF(Reference Configuration File)\ 설치 등으로 시작됩니다. 설치 후 무중단 업그레이드\(NDU\) 및 무중단 운영\(NDO\) 환경에서 컨트롤러 구성을 복원할 수 있습니다.' 
---
= NDO/NDU 환경에서 BES-53248 클러스터 스위치를 업그레이드합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 클러스터 스위치 업그레이드는 컨트롤러를 업그레이드하기 위한 준비, EFOS 소프트웨어, 라이센스 및 RCF(Reference Configuration File)를 설치하는 것부터 시작됩니다. 설치 후 NDU(무중단 업그레이드) 및 NDO(무중단 운영) 환경에서 컨트롤러 구성을 복원할 수 있습니다.

기존 NetApp BES-53248 클러스터 스위치에 EFOS 소프트웨어, 라이센스 및 RCF 파일을 설치하기 전에 다음 조건이 충족되어야 합니다.

* 클러스터가 완전하게 작동하는 클러스터여야 합니다(오류 로그 메시지 또는 기타 문제 없음).
* 클러스터에는 결함이 있는 클러스터 NIC(네트워크 인터페이스 카드)가 포함되어 있지 않아야 합니다.
* 두 클러스터 스위치에 연결된 모든 포트가 작동해야 합니다.
* 모든 클러스터 포트가 작동 중이어야 합니다.
* 모든 클러스터 LIF는 관리 및 운영 측면에서 홈 포트에 있어야 합니다.
* ONTAP의 cluster ping-cluster-node node1의 advanced 권한 명령은 모든 경로에서 "PMTU 통신보다 큼"이 성공했음을 나타내야 합니다.
* RCF 및 EFOS 버전의 명령 구문 간에는 명령 의존성이 있을 수 있습니다.


지원되는 EFOS, RCF 및 ONTAP 버전은 NetApp BES-53248 스위치 페이지의 스위치 호환성 표를 참조하십시오. http://mysupport.netapp.com/site["NetApp BES-53248 스위치"^].

이 절차는 작동 중인 클러스터에 적용되며 NDU 및 NDO가 가능합니다. 이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* NetApp 스위치 이름은 CS1, CS2입니다.
* 이 절차에 사용된 예에서는 두 번째 스위치인 _CS2._에서 업그레이드를 시작합니다
* 클러스터 LIF 이름은 node1의 node1_clus1 및 node1_clus2, node2의 node2_clus1 및 node2_clus2 입니다.
* IPspace 이름이 Cluster입니다.
* 'cluster1::>' 프롬프트는 클러스터의 이름을 나타냅니다.
* 각 노드의 클러스터 포트 이름은 e0a, e0b 입니다.
+
플랫폼에서 지원되는 실제 클러스터 포트는 __Hardware Universe__을(를) 참조하십시오.

+
https://hwu.netapp.com/Home/Index["NetApp Hardware Universe를 참조하십시오"^]

* NetApp 클러스터 스위치에 지원되는 ISL(Inter-Switch Link)은 포트 0/55 및 0/56입니다.
* NetApp 클러스터 스위치에 지원되는 노드 연결은 기본 라이센스로 포트 0/1~0/16 포트입니다.
* 이 절차의 예에서는 2개의 노드를 사용하지만 하나의 클러스터에 최대 24개의 노드를 포함할 수 있습니다.
* 이 섹션의 모든 절차를 반복하여 다른 스위치 * CS1 * 에서 EFOS 소프트웨어 및 RCF 파일을 업그레이드합니다.

