---
permalink: switch-bes-53248/replace-configure-new-switch.html 
sidebar: sidebar 
keywords: BES-53248 switches,initial installation,new install 
summary: 이 장에 설명된 단계를 완료하여 새 BES-53248 클러스터 스위치를 구성할 수 있습니다. 
---
= 새 BES-53248 클러스터 스위치를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 장에 설명된 단계를 완료하여 새 BES-53248 클러스터 스위치를 구성할 수 있습니다.

ONTAP를 실행하는 시스템에 BES-53248 클러스터 스위치를 설치하는 것은 스위치가 관리 인터페이스를 통해 통신할 수 있도록 IP 주소 및 구성을 설정하는 것에서 시작됩니다. 그런 다음 필요에 따라 이더넷 패브릭 OS(EFOS) 소프트웨어, 참조 구성 파일(RCF) 및 기타 라이센스를 설치할 수 있습니다. 이 절차는 컨트롤러를 추가하기 전에 BES-53248 스위치를 준비하는 데 사용됩니다. 또한 BES-53248 클러스터 스위치용 CSHM(Cluster Switch Health Monitor)을 지원하기 위해 필요한 구성 파일을 설치해야 할 수도 있습니다. 을 참조하십시오 link:configure-health-monitor.html["CSHM(Cluster Switch Health Monitor) 구성 파일을 설치합니다"] 를 참조하십시오.

이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* NetApp 스위치 이름은 CS1 및 CS2입니다.
* 이 절차에 사용된 예에서는 두 번째 스위치인 _CS2._에서 업그레이드를 시작합니다
* 클러스터 LIF 이름은 노드 1의 경우 node1_clus1 및 node1_clus2이고, 노드 2의 경우 node2_clus1 및 node2_clus2입니다.
* IPspace 이름이 Cluster입니다.
* 'cluster1::>' 프롬프트는 클러스터의 이름을 나타냅니다.
* 각 노드의 클러스터 포트 이름은 e0a 및 e0b입니다.
+
를 참조하십시오 https://hwu.netapp.com/Home/Index["NetApp Hardware Universe를 참조하십시오"^] 플랫폼에 지원되는 실제 클러스터 포트의 경우

* NetApp 스위치에 지원되는 ISL(Inter-Switch Link)은 포트 0/55 및 0/56입니다.
* NetApp 스위치에 지원되는 노드 연결은 기본 라이센스로 포트 0/1~0/16 입니다.
* 이 절차의 예에서는 2개의 노드를 사용하지만 하나의 클러스터에 최대 24개의 노드를 포함할 수 있습니다.

