---
permalink: switch-bes-53248/replace-upgrade.html 
sidebar: sidebar 
keywords: BES-53248 switches,upgrading,BES-53248 switches 
summary: 'BES-53248 클러스터 스위치 업그레이드는 컨트롤러를 업그레이드하기 위한 준비, EFOS 소프트웨어, 라이센스 및 RCF(Reference Configuration File)\ 설치 등으로 시작됩니다. 설치 후 무중단 업그레이드\(NDU\) 및 무중단 운영\(NDO\) 환경에서 컨트롤러 구성을 복원할 수 있습니다.' 
---
= BES-53248 클러스터 스위치를 업그레이드합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
BES-53248 클러스터 스위치를 업그레이드하려면 다음 단계를 수행하십시오.

이 절차는 작동 중인 클러스터에 적용되며 NDU(무중단 업그레이드) 및 NDO(무중단 운영) 환경을 지원합니다.



== 요구사항 검토

기존 NetApp BES-53248 클러스터 스위치에 EFOS 소프트웨어, 라이센스 및 RCF 파일을 설치하기 전에 다음 사항을 확인하십시오.

* 클러스터가 완전하게 작동하는 클러스터입니다(오류 로그 메시지 또는 기타 문제 없음).
* 클러스터에는 결함이 있는 클러스터 NIC(네트워크 인터페이스 카드)가 포함되어 있지 않습니다.
* 두 클러스터 스위치에 연결된 모든 포트가 작동합니다.
* 모든 클러스터 포트가 작동 중입니다.
* 모든 클러스터 LIF는 관리 및 운영 측면에서 홈 포트에 있습니다.
* 각 노드에 있는 처음 두 개의 클러스터 LIF는 별도의 NIC에 구성되어 있으며 별도의 클러스터 스위치 포트에 연결됩니다.
* ONTAP `cluster ping-cluster -node node1` 고급 권한 명령은 을 나타냅니다 `larger than PMTU communication` 모든 경로에서 성공합니다.



NOTE: RCF 및 EFOS 버전의 명령 구문 간에는 명령 의존성이 있을 수 있습니다.


NOTE: 스위치 호환성은 의 호환성 표를 참조하십시오 https://mysupport.netapp.com/site/products/all/details/broadcom-cluster-switches/downloads-tab["Broadcom 클러스터 스위치"^] 지원되는 EFOS, RCF 및 ONTAP 버전에 대한 페이지입니다.



== 컨트롤러를 준비합니다

BES-53248 클러스터 스위치 업그레이드를 위해 컨트롤러를 준비하려면 다음 절차를 따르십시오.

.단계
. 클러스터 스위치를 관리 네트워크에 연결합니다.
. ping 명령을 사용하여 EFOS, 라이센스 및 RCF를 호스팅하는 서버에 대한 연결을 확인합니다.
+
이 문제가 발생하면 라우팅되지 않은 네트워크를 사용하여 IP 주소 192.168.x 또는 172.19.x를 사용하여 서비스 포트를 구성합니다 나중에 서비스 포트를 운영 관리 IP 주소로 재구성할 수 있습니다.

+
.예제 보기
[%collapsible]
====
이 예에서는 스위치가 IP 주소 172.19.2.1로 서버에 연결되어 있는지 확인합니다.

[listing, subs="+quotes"]
----
(cs2)# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
====
. 클러스터 포트가 정상 상태이며 명령을 사용하여 링크가 있는지 확인합니다.
+
네트워크 포트 표시 - IPSpace 클러스터

+
.예제 보기
[%collapsible]
====
다음 예는 Link 값이 Up 이고 Health Status가 Healthy인 모든 포트의 출력 유형을 보여줍니다.

[listing, subs="+quotes"]
----
cluster1::> *network port show -ipspace Cluster*

Node: node1
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
------ ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                    Ignore
                                               Speed(Mbps) Health   Health
Port   IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
-----  ------------ ---------------- ---- ---- ----------- -------- ------
e0a    Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b    Cluster      Cluster          up   9000  auto/10000 healthy  false
----
====
. 클러스터 LIF가 관리 및 운영 측면에서 홈 포트에 상주하고 있는지 확인하려면 다음 명령을 사용하십시오.
+
'network interface show-vserver cluster'

+
.예제 보기
[%collapsible]
====
이 예제에서 '-vserver' 매개 변수는 클러스터 포트와 연결된 LIF에 대한 정보를 표시합니다. '상태 관리/작업'은 반드시 가동되어야 하며 '홈'은 진실이어야 합니다.

[listing, subs="+quotes"]
----
cluster1::> *network interface show -vserver Cluster*

          Logical      Status     Network             Current       Current Is
Vserver   Interface    Admin/Oper Address/Mask        Node          Port    Home
--------- ----------   ---------- ------------------  ------------- ------- ----
Cluster
          node1_clus1
                       up/up      169.254.217.125/16  node1         e0a     true
          node1_clus2
                       up/up      169.254.205.88/16   node1         e0b     true
          node2_clus1
                       up/up      169.254.252.125/16  node2         e0a     true
          node2_clus2
                       up/up      169.254.110.131/16  node2         e0b     true
----
====




== 소프트웨어를 설치합니다

다음 지침에 따라 소프트웨어를 설치합니다.

. link:configure-efos-software.html["EFOS 소프트웨어를 설치합니다"]. BES-53248 클러스터 스위치에서 이더넷 패브릭 OS(EFOS) 소프트웨어를 다운로드하여 설치합니다.
. link:configure-licenses.html["BES-53248 클러스터 스위치용 라이센스를 설치합니다"]. 필요에 따라 라이센스를 추가로 구입하여 설치하여 새 포트를 추가합니다. 스위치 기본 모델은 10GbE 또는 25GbE 포트 16개와 100GbE 포트 2개에 대해 라이센스가 부여됩니다.
. link:configure-install-rcf.html["RCF(Reference Configuration File) 설치"]. BES-53248 클러스터 스위치에 RCF를 설치 또는 업그레이드한 다음 RCF를 적용한 후 포트를 추가 라이센스에 대해 확인합니다.
. link:configure-health-monitor.html["CSHM(Cluster Switch Health Monitor) 구성 파일을 설치합니다"]. 클러스터 스위치 상태 모니터링에 해당하는 구성 파일을 설치합니다.
. link:configure-ssh.html["BES-53248 클러스터 스위치에서 SSH를 활성화합니다"]. CSHM(Cluster Switch Health Monitor) 및 로그 수집 기능을 사용하는 경우 스위치에서 SSH를 사용하도록 설정합니다.
. link:configure-log-collection.html["로그 수집 기능을 활성화합니다"]. 이 기능을 사용하여 ONTAP에서 스위치 관련 로그 파일을 수집할 수 있습니다.

