---
permalink: switch-bes-53248/replace-required-documentation.html 
sidebar: sidebar 
keywords: documentation requirements, BES-53248 switches,cluster switches 
summary: Cluster-Mode 구성을 설정하려면 특정 스위치 및 컨트롤러 설명서가 필요합니다. 
---
= BES-53248 클러스터 스위치 필수 설명서
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cluster-Mode 구성을 설정하려면 특정 스위치 및 컨트롤러 설명서가 필요합니다.

BES-53248 클러스터 스위치를 설정하려면 Broadcom 지원 사이트에서 제공되는 다음 문서가 필요합니다. https://www.broadcom.com/support/bes-switch["Broadcom Ethernet 스위치 제품 라인"^]

[cols="1,2"]
|===
| 문서 제목 | 설명 


 a| 
_EFOS 관리자 가이드 v3.4.3_
 a| 
일반적인 네트워크에서 BES-53248 스위치를 사용하는 방법의 예를 제공합니다.



 a| 
_EFOS CLI 명령 참조 v3.4.3_
 a| 
에서는 BES-53248 소프트웨어를 보고 구성하는 데 사용하는 CLI(Command-Line Interface) 명령에 대해 설명합니다.



 a| 
_EFOS 시작 안내서 v3.4.3_
 a| 
BES-53248 스위치에 대한 자세한 내용은 에 나와 있습니다.



 a| 
_EFOS SNMP 참조 가이드 v3.4.3_
 a| 
일반적인 네트워크에서 BES-53248 스위치를 사용하는 방법의 예를 제공합니다.



 a| 
_EFOS 배율 매개 변수 및 값 v3.4.3_
 a| 
지원되는 플랫폼에서 EFOS 소프트웨어를 제공하고 유효성을 검사하는 기본 확장 매개 변수에 대해 설명합니다.



 a| 
_EFOS 기능 사양 v3.4.3_
 a| 
지원되는 플랫폼의 EFOS 소프트웨어 사양에 대해 설명합니다.



 a| 
_EFOS 릴리스 정보 v3.4.3_
 a| 
BES-53248 소프트웨어에 대한 릴리스 관련 정보를 제공합니다.

|===
ONTAP 시스템을 설정하려면 NetApp Support 사이트 에서 다음 문서가 필요합니다 http://mysupport.netapp.com/["mysupport.netapp.com"^]

[cols="1,2"]
|===
| 이름 | 설명 


 a| 
https://hwu.netapp.com/Home/Index["NetApp Hardware Universe를 참조하십시오"^]
 a| 
시스템 캐비닛을 비롯한 모든 NetApp 하드웨어의 전력 및 사이트 요구사항에 대해 설명합니다.



 a| 
컨트롤러별 설치 및 설정 지침 _
 a| 
에서는 NetApp 하드웨어를 설치하는 방법에 대해 설명합니다.



 a| 
ONTAP 9
 a| 
ONTAP 9 릴리즈의 모든 측면에 대해 자세히 설명합니다.

|===