---
permalink: switch-cisco-3132q-v/cn1610-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Cisco Nexus 3132q-v 스위치를 구성하기 전에 프로세스 개요 및 명명법을 검토하십시오. 
---
= 마이그레이션 요구 사항
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3132Q-V 스위치는 AFF 또는 FAS 클러스터에서 클러스터 스위치로 사용할 수 있습니다. 클러스터 스위치를 사용하면 2개 이상의 노드로 ONTAP 클러스터를 구축할 수 있습니다.

[NOTE]
====
이 절차를 수행하려면 ONTAP 명령과 Cisco Nexus 3000 시리즈 스위치 명령을 모두 사용해야 합니다. ONTAP 명령은 별도의 표시가 없는 한 사용됩니다.

====
자세한 내용은 다음을 참조하십시오.

* https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 및 CN1610 설명 페이지"^]
* https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치 설명 페이지"^]
* http://hwu.netapp.com["Hardware Universe"^]




== CN1610 요구 사항

지원되는 클러스터 스위치는 다음과 같습니다.

* NetApp CN1610
* Cisco Nexus 3132Q-V


클러스터 스위치는 다음과 같은 노드 연결을 지원합니다.

* NetApp CN1610: 포트 0/1~0/12(10GbE)
* Cisco Nexus 3132Q-V: 포트 e1/1-30(40/100 GbE)


클러스터 스위치는 다음과 같은 ISL(Inter-Switch Link) 포트를 사용합니다.

* NetApp CN1610: 포트 0/13~0/16(10GbE)
* Cisco Nexus 3132Q-V: 포트 e1/31-32(40/100 GbE)
+
를 클릭합니다 link:https://hwu.netapp.com/["Hardware Universe"^] Nexus 3132Q-V 스위치에 대한 지원되는 케이블 연결에 대한 자세한 내용은 다음을 참조하십시오.

* 10GbE 클러스터 연결이 있는 노드는 QSFP-SFP+ 광 파이버 브레이크아웃 케이블 또는 QSFP-SFP+ 구리 브레이크아웃 케이블이 필요합니다
* 40/100 GbE 클러스터 연결이 있는 노드에는 광 파이버 케이블 또는 QSFP/QSFP28 구리 직접 연결 케이블이 있는 지원되는 QSFP/QSFP28 광 모듈이 필요합니다


적절한 ISL 케이블 연결은 다음과 같습니다.

* 시작: CN1610(SFP+에서 SFP+로), SFP+ 광 파이버 4개 또는 구리 직접 연결 케이블
* 중간: Nexus 3132Q-V(QSFP - 4 SFP+ 브레이크아웃)에 대한 CN1610의 경우 QSFP - SFP+ 광 파이버 또는 구리 브레이크아웃 케이블 1개
* 마지막: Nexus 3132Q-V - Nexus 3132Q-V(QSFP28 - QSFP28), 2개의 QSFP28 광 파이버 또는 구리 직접 연결 케이블


NetApp twinax 케이블은 Cisco Nexus 3132Q-V 스위치와 호환되지 않습니다.

현재 CN1610 구성에서 클러스터 노드-스위치 연결 또는 ISL 연결에 NetApp twinax 케이블을 사용하고, 현재 환경에서 Twinax를 계속 사용하려면 Cisco 케이블을 확보해야 합니다. 또는 ISL 연결과 클러스터 노드 간 접속 모두에 광 Fibre 케이블을 사용할 수 있습니다.

.사용된 예제에 대해 설명합니다
이 절차의 예에서는 CN1610 스위치를 Cisco Nexus 3132Q-V 스위치로 교체하는 방법을 설명합니다. 이전 버전의 다른 Cisco 스위치에 대해 이 단계를 수정할 수 있습니다.

이 절차에서는 다음과 같은 스위치 및 노드 명명법을 사용합니다.

* 명령 출력은 ONTAP의 릴리즈별로 다를 수 있습니다.
* 교체할 CN1610 스위치는 * CL1 * 및 * CL2 * 입니다.
* CN1610 스위치를 대체하는 Nexus 3132Q-V 스위치는 * C1 * 및 * C2 * 입니다.
* * n1_clus1 * 은 노드 * n1 * 의 클러스터 스위치 1(CL1 또는 C1)에 연결된 첫 번째 클러스터 논리 인터페이스(LIF)입니다.
* * n1_clus2 * 는 노드 * n1 * 의 클러스터 스위치 2(CL2 또는 C2)에 연결된 첫 번째 클러스터 LIF입니다.
* * n1_clus3 * 은 노드 * n1 * 의 클러스터 스위치 2(CL2 또는 C2)에 연결된 두 번째 LIF입니다.
* * n1_clus4 * 는 노드 * n1 * 의 클러스터 스위치 1(CL1 또는 C1)에 연결된 두 번째 LIF입니다.
* 10GbE 및 40/100 GbE 포트 수는 에서 사용할 수 있는 RCFs(참조 구성 파일)에 정의되어 있습니다 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] 페이지.
* 노드는 * n1 *, * n2 *, * n3 * 및 * n4 * 입니다.


이 절차의 예에서는 4개의 노드를 사용합니다.

* 2개 노드에서 4개의 10GbE 클러스터 인터커넥트 포트 * e0a *, * e0b *, * e0c * 및 * e0d * 를 사용합니다.
* 다른 2개 노드는 2개의 40GbE 클러스터 인터커넥트 포트 * e4a * 및 * e4e * 를 사용합니다.
+
에는 link:https://hwu.netapp.com/["Hardware Universe"^]플랫폼의 실제 클러스터 포트가 나와 있습니다.



.다음 단계
link:cn5596-prepare-to-migrate.html["마이그레이션을 준비합니다"]..
