---
permalink: switch-cisco-3132q-v/cn1610-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Cisco Nexus 3132q-v 스위치를 구성하기 전에 프로세스 개요와 명명법을 살펴보세요. 
---
= 이주 요구 사항
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3132Q-V 스위치는 AFF 또는 FAS 클러스터에서 클러스터 스위치로 사용할 수 있습니다. 클러스터 스위치를 사용하면 두 개 이상의 노드로 ONTAP 클러스터를 구축할 수 있습니다.

[NOTE]
====
이 절차에서는 ONTAP 명령과 Cisco Nexus 3000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 지정되지 않는 한 ONTAP 명령을 사용합니다.

====
자세한 내용은 다음을 참조하세요.

* https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 및 CN1610 설명 페이지"^]
* https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치 설명 페이지"^]
* http://hwu.netapp.com["Hardware Universe"^]




== CN1610 요구 사항

다음 클러스터 스위치가 지원됩니다.

* NetApp CN1610
* Cisco 넥서스 3132Q-V


클러스터 스위치는 다음 노드 연결을 지원합니다.

* NetApp CN1610: 포트 0/1~0/12(10GbE)
* Cisco Nexus 3132Q-V: 포트 e1/1-30(40/100GbE)


클러스터 스위치는 다음과 같은 ISL(스위치 간 링크) 포트를 사용합니다.

* NetApp CN1610: 포트 0/13~0/16(10GbE)
* Cisco Nexus 3132Q-V: 포트 e1/31-32(40/100GbE)
+
그만큼link:https://hwu.netapp.com/["Hardware Universe"^] Nexus 3132Q-V 스위치에 지원되는 케이블에 대한 정보가 포함되어 있습니다.

* 10GbE 클러스터 연결이 있는 노드에는 QSFP-SFP+ 광섬유 분기 케이블 또는 QSFP-SFP+ 구리 분기 케이블이 필요합니다.
* 40/100GbE 클러스터 연결이 있는 노드에는 광섬유 케이블 또는 QSFP/QSFP28 구리 직접 연결 케이블이 있는 지원되는 QSFP/QSFP28 광 모듈이 필요합니다.


적절한 ISL 케이블링은 다음과 같습니다.

* 시작: CN1610 대 CN1610(SFP+ 대 SFP+)의 경우 4개의 SFP+ 광섬유 또는 구리 직접 연결 케이블
* 임시: CN1610에서 Nexus 3132Q-V(QSFP에서 4개의 SFP+ 브레이크아웃으로)로의 경우, QSFP에서 SFP+ 광섬유 또는 구리 브레이크아웃 케이블 1개
* 최종: Nexus 3132Q-V에서 Nexus 3132Q-V(QSFP28에서 QSFP28)로의 경우 두 개의 QSFP28 광섬유 또는 구리 직접 연결 케이블


NetApp Twinax 케이블은 Cisco Nexus 3132Q-V 스위치와 호환되지 않습니다.

현재 CN1610 구성에서 클러스터-노드-스위치 연결 또는 ISL 연결에 NetApp Twinax 케이블을 사용하고 해당 환경에서 Twinax를 계속 사용하려면 Cisco Twinax 케이블을 구매해야 합니다.  또는 ISL 연결과 클러스터-노드-스위치 연결 모두에 광섬유 케이블을 사용할 수 있습니다.

.사용된 예에 관하여
이 절차의 예에서는 CN1610 스위치를 Cisco Nexus 3132Q-V 스위치로 교체하는 방법을 설명합니다.  이러한 단계(수정 사항 포함)는 다른 오래된 Cisco 스위치에도 사용할 수 있습니다.

이 절차에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 명령 출력은 ONTAP 릴리스에 따라 달라질 수 있습니다.
* 교체할 CN1610 스위치는 *CL1*과 *CL2*입니다.
* CN1610 스위치를 대체할 Nexus 3132Q-V 스위치는 *C1*과 *C2*입니다.
* *n1_clus1*은 노드 *n1*의 클러스터 스위치 1(CL1 또는 C1)에 연결된 첫 번째 클러스터 논리 인터페이스(LIF)입니다.
* *n1_clus2*는 노드 *n1*의 클러스터 스위치 2(CL2 또는 C2)에 연결된 첫 번째 클러스터 LIF입니다.
* *n1_clus3*는 노드 *n1*의 클러스터 스위치 2(CL2 또는 C2)에 연결된 두 번째 LIF입니다.
* *n1_clus4*는 노드 *n1*의 클러스터 스위치 1(CL1 또는 C1)에 연결된 두 번째 LIF입니다.
* 10GbE 및 40/100GbE 포트의 수는 다음에서 사용 가능한 참조 구성 파일(RCF)에 정의되어 있습니다. https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] 페이지.
* 노드는 *n1*, *n2*, *n3*, *n4*입니다.


이 절차의 예에서는 4개의 노드를 사용합니다.

* 두 노드는 4개의 10GbE 클러스터 상호 연결 포트(*e0a*, *e0b*, *e0c*, *e0d*)를 사용합니다.
* 나머지 두 노드는 두 개의 40GbE 클러스터 상호 연결 포트인 *e4a*와 *e4e*를 사용합니다.
+
그만큼link:https://hwu.netapp.com/["Hardware Universe"^] 플랫폼의 실제 클러스터 포트를 나열합니다.



.다음은 무엇인가요?
link:cn5596-prepare-to-migrate.html["이주 준비"].
