---
permalink: switch-cisco-3132q-v/cn5596-prepare-to-migrate.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: Cisco Nexus 3132q-v 스위치를 AFF 또는 FAS 클러스터에서 클러스터 스위치로 사용할 수 있습니다. 
---
= Nexus 5596 스위치에서 Nexus 3132Q-V 스위치로 마이그레이션을 준비하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 단계에 따라 Cisco Nexus 3132Q-V 스위치로의 마이그레이션을 위해 Cisco Nexus 5596 스위치를 준비하십시오.

.단계
. 이 클러스터에서 AutoSupport가 활성화되어 있으면 'system node AutoSupport invoke -node * -type all-message maINT=xh' AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다
+
_x_는 유지보수 기간(시간)입니다.

+

NOTE: 이 메시지는 유지보수 작업 중에 자동 케이스 생성이 억제되도록 이 유지보수 작업의 기술 지원 부서에 알립니다.

. 구성에 있는 장치에 대한 정보를 표시합니다.
+
네트워크 디바이스 발견 쇼

+
.예제 보기
[%collapsible]
====
다음 예는 각 클러스터 인터커넥트 스위치에 대해 각 노드에 구성된 클러스터 인터커넥트 인터페이스 수를 보여 줍니다.

[listing]
----
cluster::> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e0a    CL1                 Ethernet1/1      N5K-C5596UP
            e0b    CL2                 Ethernet1/1      N5K-C5596UP
            e0c    CL2                 Ethernet1/2      N5K-C5596UP
            e0d    CL1                 Ethernet1/2      N5K-C5596UP
n2         /cdp
            e0a    CL1                 Ethernet1/3      N5K-C5596UP
            e0b    CL2                 Ethernet1/3      N5K-C5596UP
            e0c    CL2                 Ethernet1/4      N5K-C5596UP
            e0d    CL1                 Ethernet1/4      N5K-C5596UP
8 entries were displayed.
----
====
. 각 클러스터 인터페이스의 관리 또는 운영 상태 확인:
+
.. 네트워크 포트 속성을 표시합니다.
+
네트워크 포트 쇼

+
.예제 보기
[%collapsible]
====
다음 예는 시스템의 네트워크 포트 속성을 표시합니다.

[listing]
----
cluster::*> network port show –role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000 auto/10000  -        -
e0b       Cluster      Cluster          up   9000 auto/10000  -        -
e0c       Cluster      Cluster          up   9000 auto/10000  -        -
e0d       Cluster      Cluster          up   9000 auto/10000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 -        -
e0b       Cluster      Cluster          up   9000  auto/10000 -        -
e0c       Cluster      Cluster          up   9000  auto/10000 -        -
e0d       Cluster      Cluster          up   9000  auto/10000 -        -
8 entries were displayed.
----
====
.. 논리 인터페이스에 대한 정보 표시: + "network interface show"
+
.예제 보기
[%collapsible]
====
다음 예에서는 시스템의 모든 LIF에 대한 일반 정보를 표시합니다.

[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0b     true
            n1_clus3   up/up      10.10.0.3/24       n1            e0c     true
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0b     true
            n2_clus3   up/up      10.10.0.7/24       n2            e0c     true
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
.. 검색된 클러스터 스위치에 대한 정보 표시: + 'system cluster-switch show
+
.예제 보기
[%collapsible]
====
다음 예는 클러스터에 알려진 클러스터 스위치와 해당 관리 IP 주소를 표시합니다.

[listing]
----
cluster::*> system cluster-switch show

Switch                        Type               Address         Model
----------------------------- ------------------ --------------- ---------------
CL1                           cluster-network    10.10.1.101     NX5596
     Serial Number: 01234567
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP
CL2                           cluster-network    10.10.1.102     NX5596
     Serial Number: 01234568
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.1(1)N1(1)
    Version Source: CDP

2 entries were displayed.
----
====


. 클러스터 LIF clus1과 clus2의 두 노드에서 '-auto-revert' 매개 변수를 'false'로 설정합니다.
+
네트워크 인터페이스 수정

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert false
----
====
. 필요에 따라 새 3132Q-V 스위치에 적절한 RCF 및 이미지가 설치되었는지 확인하고 사용자 및 암호, 네트워크 주소 등과 같은 필수 사이트 사용자 지정을 수행합니다.
+
이때 두 스위치를 모두 준비해야 합니다. RCF 및 이미지를 업그레이드해야 하는 경우 다음 단계를 따르십시오.

+
.. 로 이동합니다 link:http://support.netapp.com/NOW/download/software/cm_switches/["Cisco 이더넷 스위치"^] 페이지로 이동합니다.
.. 스위치 및 필요한 소프트웨어 버전을 해당 페이지의 표에 기록합니다.
.. RCF의 적절한 버전을 다운로드합니다.
.. 설명 * 페이지에서 * 계속 * 을 선택하고 사용권 계약에 동의한 다음 * 다운로드 * 페이지의 지침에 따라 RCF를 다운로드합니다.
.. 해당 버전의 이미지 소프트웨어를 다운로드합니다.
+
__ONTAP 8.x 이상 클러스터 및 관리 네트워크 스위치 참조 구성 파일 __다운로드 페이지를 참조하여 적절한 버전을 선택합니다.

+
올바른 버전을 찾으려면 _ONTAP 8.x 이상 클러스터 네트워크 스위치 다운로드 페이지_를 참조하십시오.



. 교체할 두 번째 Nexus 5596 스위치에 연결된 LIF 마이그레이션:
+
네트워크 인터페이스 마이그레이션

+
.예제 보기
[%collapsible]
====
다음 예에서는 n1과 n2 를 보여 주지만 LIF 마이그레이션은 모든 노드에서 수행되어야 합니다.

[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1 –
destination-node n1 -destination-port e0a
cluster::*> network interface migrate -vserver Cluster -lif n1_clus3 -source-node n1 –
destination-node n1 -destination-port e0d
cluster::*> network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2 –
destination-node n2 -destination-port e0a
cluster::*> network interface migrate -vserver Cluster -lif n2_clus3 -source-node n2 –
destination-node n2 -destination-port e0d
----
====
. 클러스터의 상태 확인:
+
네트워크 인터페이스 쇼

+
.예제 보기
[%collapsible]
====
다음 예에서는 이전 'network interface migrate' 명령의 결과를 보여 줍니다.

[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e0a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e0a     false
            n1_clus3   up/up      10.10.0.3/24       n1            e0d     false
            n1_clus4   up/up      10.10.0.4/24       n1            e0d     true
            n2_clus1   up/up      10.10.0.5/24       n2            e0a     true
            n2_clus2   up/up      10.10.0.6/24       n2            e0a     false
            n2_clus3   up/up      10.10.0.7/24       n2            e0d     false
            n2_clus4   up/up      10.10.0.8/24       n2            e0d     true
8 entries were displayed.
----
====
. 스위치 CL2에 물리적으로 연결된 클러스터 인터커넥트 포트를 종료합니다.
+
네트워크 포트 수정

+
.예제 보기
[%collapsible]
====
다음 명령을 실행하면 n1과 n2 에서 지정된 포트가 종료되지만 모든 노드에서 포트가 종료되어야 합니다.

[listing]
----
cluster::*> network port modify -node n1 -port e0b -up-admin false
cluster::*> network port modify -node n1 -port e0c -up-admin false
cluster::*> network port modify -node n2 -port e0b -up-admin false
cluster::*> network port modify -node n2 -port e0c -up-admin false
----
====
. 원격 클러스터 인터페이스의 연결을 확인합니다.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
를 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령입니다.

`network interface check cluster-connectivity start` 및 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
* 참고: * show 명령을 실행하기 전에 몇 초 동안 기다린 후 세부 정보를 표시합니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2        n2_clus1      none
       3/5/2022 19:21:20 -06:00   n1_clus2        n2_clus2      none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2        n1_clus1      none
       3/5/2022 19:21:20 -06:00   n2_clus2        n1_clus2      none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스에 대해 을 사용할 수도 있습니다 `cluster ping-cluster -node <name>` 연결 상태를 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node n1*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e0a	10.10.0.1
Cluster n1_clus2 n1		e0b	10.10.0.2
Cluster n1_clus3 n1		e0c	10.10.0.3
Cluster n1_clus4 n1		e0d	10.10.0.4
Cluster n2_clus1 n2		e0a	10.10.0.5
Cluster n2_clus2 n2		e0b	10.10.0.6
Cluster n2_clus3 n2		e0c	10.10.0.7
Cluster n2_clus4 n2		e0d	10.10.0.8

Local = 10.10.0.1 10.10.0.2 10.10.0.3 10.10.0.4
Remote = 10.10.0.5 10.10.0.6 10.10.0.7 10.10.0.8
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 16 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 16 path(s):
    Local 10.10.0.1 to Remote 10.10.0.5
    Local 10.10.0.1 to Remote 10.10.0.6
    Local 10.10.0.1 to Remote 10.10.0.7
    Local 10.10.0.1 to Remote 10.10.0.8
    Local 10.10.0.2 to Remote 10.10.0.5
    Local 10.10.0.2 to Remote 10.10.0.6
    Local 10.10.0.2 to Remote 10.10.0.7
    Local 10.10.0.2 to Remote 10.10.0.8
    Local 10.10.0.3 to Remote 10.10.0.5
    Local 10.10.0.3 to Remote 10.10.0.6
    Local 10.10.0.3 to Remote 10.10.0.7
    Local 10.10.0.3 to Remote 10.10.0.8
    Local 10.10.0.4 to Remote 10.10.0.5
    Local 10.10.0.4 to Remote 10.10.0.6
    Local 10.10.0.4 to Remote 10.10.0.7
    Local 10.10.0.4 to Remote 10.10.0.8
Larger than PMTU communication succeeds on 16 path(s)
RPC status:
4 paths up, 0 paths down (tcp check)
4 paths up, 0 paths down (udp check)
----
--
====
. [[step10]] 활성 Nexus 5596 스위치의 ISL 포트 41 - 48을 종료합니다. CL1:
+
.예제 보기
[%collapsible]
====
다음 예에서는 Nexus 5596 스위치 CL1에서 ISL 포트 41 ~ 48을 종료하는 방법을 보여 줍니다.

[listing]
----
(CL1)# configure
(CL1)(Config)# interface e1/41-48
(CL1)(config-if-range)# shutdown
(CL1)(config-if-range)# exit
(CL1)(Config)# exit
(CL1)#
----
====
+
Nexus 5010 또는 5020을 교체하는 경우 ISL에 적합한 포트 번호를 지정하십시오.

. CL1과 C2 사이에 임시 ISL을 구축합니다.
+
.예제 보기
[%collapsible]
====
다음 예에서는 CL1과 C2 간에 임시 ISL을 설정하는 방법을 보여 줍니다.

[listing]
----
C2# configure
C2(config)# interface port-channel 2
C2(config-if)# switchport mode trunk
C2(config-if)# spanning-tree port type network
C2(config-if)# mtu 9216
C2(config-if)# interface breakout module 1 port 24 map 10g-4x
C2(config)# interface e1/24/1-4
C2(config-if-range)# switchport mode trunk
C2(config-if-range)# mtu 9216
C2(config-if-range)# channel-group 2 mode active
C2(config-if-range)# exit
C2(config-if)# exit
----
====


.다음 단계
link:cn5596-configure-ports.html["포트를 구성합니다"]..
