---
permalink: switch-cisco-3132q-v/cn5596-migrate-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Cisco Nexus 3132q-v 스위치를 구성하기 전에 프로세스 개요 및 명명법을 검토하십시오. 
---
= 마이그레이션 요구 사항
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3132Q-V 스위치는 AFF 또는 FAS 클러스터에서 클러스터 스위치로 사용할 수 있습니다. 클러스터 스위치를 사용하면 2개 이상의 노드로 ONTAP 클러스터를 구축할 수 있습니다.

[NOTE]
====
이 절차를 수행하려면 ONTAP 명령과 Cisco Nexus 3000 시리즈 스위치 명령을 모두 사용해야 합니다. ONTAP 명령은 별도의 표시가 없는 한 사용됩니다.

====
자세한 내용은 다음을 참조하십시오.

* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^]
* link:http://hwu.netapp.com["Hardware Universe"^]




== Cisco Nexus 5596 요구 사항

클러스터 스위치는 노드 연결에 다음 포트를 사용합니다.

* Nexus 5596: 포트 1/1-40(10GbE)
* Nexus 3132Q-V: 포트 1/1-30(10/40/GbE)


클러스터 스위치는 다음과 같은 ISL(Inter-Switch Link) 포트를 사용합니다.

* Nexus 5596: 포트 1/41-48개(10GbE)
* Nexus 3132Q-V: 포트 1/31-32(100/GbE)


에는 link:https://hwu.netapp.com/["_Hardware Universe _"^]Nexus 3132Q-V 스위치 케이블 연결에 대한 정보가 포함되어 있습니다.

* 10GbE 클러스터 연결이 있는 노드는 QSFP-SFP+ 광 파이버 브레이크아웃 케이블 또는 QSFP-SFP+ 구리 브레이크아웃 케이블이 필요합니다.
* 40/100 GbE 클러스터 연결이 있는 노드에는 파이버 케이블 또는 QSFP/QSFP28 구리 직접 연결 케이블이 있는 지원되는 QSFP/QSFP28 광 모듈이 필요합니다.


클러스터 스위치는 적절한 ISL 케이블 연결을 사용합니다.

* 시작:Nexus 5596(SFP+에서 SFP+로)
+
** 8x SFP+ 파이버 또는 구리 직접 연결 케이블


* 중간: Nexus 5596 - Nexus 3132Q-V(QSFP - 4xSFP+ 브레이크아웃)
+
** QSFP-SFP+ 파이버 브레이크아웃 또는 구리 브레이크아웃 케이블 1개


* 최종: Nexus 3132Q-V - Nexus 3132Q-V(QSFP28 - QSFP28)
+
** QSFP28 파이버 또는 구리 직접 연결 케이블 2개


* Nexus 3132Q-V 스위치에서 QSFP/QSFP28 포트는 40/100 기가비트 이더넷 또는 4개의 10기가비트 이더넷 모드로 작동할 수 있습니다.
+
기본적으로 40기가비트 이더넷 모드에는 32개의 포트가 있습니다. 이러한 40기가비트 이더넷 포트에는 2 튜플 명명 규칙이 적용됩니다. 예를 들어, 두 번째 40기가비트 이더넷 포트의 번호는 1/2로 지정됩니다.

+
구성을 40기가비트 이더넷에서 10기가비트 이더넷으로 변경하는 프로세스를 _breakout_이라고 하며, 구성을 10기가비트 이더넷에서 40기가비트 이더넷으로 변경하는 프로세스를 _breakin_이라고 합니다.

+
40/100 기가비트 이더넷 포트를 10기가비트 이더넷 포트로 분리하면 3 튜플 명명 규칙을 사용하여 결과 포트에 번호가 지정됩니다. 예를 들어, 두 번째 40/100 기가비트 이더넷 포트의 분리 포트는 1/2/1, 1/2/2, 1/2/3 및 1/2/4로 번호가 지정됩니다.

* Nexus 3132Q-V 스위치 왼쪽에는 1/33 및 1/34라고 하는 SFP+ 포트 2개가 있습니다.
* Nexus 3132Q-V 스위치에서 일부 포트를 10GbE 또는 40/100GbE에서 실행하도록 구성했습니다.
+
[NOTE]
====
'interface breakout module 1 port 1-6 map 10g-4x' 명령어를 이용하여 처음 6개의 포트를 4x10 GbE 모드로 분리할 수 있다. 마찬가지로 'no interface breakout module 1 port 1-6 map 10g-4x' 명령을 사용하여 브레이크아웃 구성에서 처음 6개의 QSFP+ 포트를 다시 그룹화할 수 있습니다.

====
* 귀사는 계획, 마이그레이션 작업을 완료했으며 노드에서 Nexus 3132Q-V 클러스터 스위치까지 10GbE 및 40/100 GbE 연결에 대한 필수 문서를 읽었습니다.
* 이 절차에서 지원되는 ONTAP 및 NX-OS 버전은 다음과 같습니다.link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^] .


.사용된 예제에 대해 설명합니다
이 절차의 예에서는 Cisco Nexus 5596 스위치를 Cisco Nexus 3132Q-V 스위치로 교체하는 방법을 설명합니다. 이전 버전의 다른 Cisco 스위치에 대해 이 단계를 수정할 수 있습니다.

이 절차에서는 다음과 같은 스위치 및 노드 명명법을 사용합니다.

* 명령 출력은 ONTAP의 릴리즈별로 다를 수 있습니다.
* 교체할 Nexus 5596 스위치는 * CL1 * 및 * CL2 * 입니다.
* Nexus 5596 스위치를 대체하는 Nexus 3132Q-V 스위치는 * C1 * 및 * C2 * 입니다.
* * n1_clus1 * 은 노드 * n1 * 의 클러스터 스위치 1(CL1 또는 C1)에 연결된 첫 번째 클러스터 논리 인터페이스(LIF)입니다.
* * n1_clus2 * 는 노드 * n1 * 의 클러스터 스위치 2(CL2 또는 C2)에 연결된 첫 번째 클러스터 LIF입니다.
* * n1_clus3 * 은 노드 * n1 * 의 클러스터 스위치 2(CL2 또는 C2)에 연결된 두 번째 LIF입니다.
* * n1_clus4 * 는 노드 * n1 * 의 클러스터 스위치 1(CL1 또는 C1)에 연결된 두 번째 LIF입니다.
* 10GbE 및 40/100GbE 포트의 수는 다음에서 사용 가능한 참조 구성 파일(RCF)에 정의되어 있습니다.link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco ® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] .
* 노드는 * n1 *, * n2 *, * n3 * 및 * n4 * 입니다.


이 절차의 예에서는 4개의 노드를 사용합니다.

* 2개 노드에서 4개의 10GbE 클러스터 인터커넥트 포트 * e0a *, * e0b *, * e0c * 및 * e0d * 를 사용합니다.
* 다른 2개 노드는 2개의 40GbE 클러스터 인터커넥트 포트 * e4a * 및 * e4e * 를 사용합니다.
+
에는 link:https://hwu.netapp.com/["_Hardware Universe _"^]플랫폼의 실제 클러스터 포트가 나와 있습니다.



.시나리오가 포함되어 있습니다
이 절차에서는 다음 시나리오에 대해 설명합니다.

* 클러스터는 2개의 Nexus 5596 클러스터 스위치에서 연결되고 작동하는 2개의 노드로 시작됩니다.
* C2로 교체할 클러스터 스위치 CL2(1-19단계):
+
** CL2에 연결된 모든 노드의 모든 클러스터 포트 및 LIF의 트래픽은 첫 번째 클러스터 포트 및 CL1에 연결된 LIF로 마이그레이션됩니다.
** CL2에 연결된 모든 노드의 모든 클러스터 포트에서 케이블 연결을 끊고 지원되는 분리 케이블을 사용하여 포트를 새 클러스터 스위치 C2에 다시 연결합니다.
** CL1과 CL2 사이의 ISL 포트 간 케이블을 분리한 다음 지원되는 분리 케이블을 사용하여 CL1에서 C2로의 포트를 다시 연결합니다.
** 모든 노드의 C2에 연결된 모든 클러스터 포트 및 LIF의 트래픽을 되돌릴 수 있습니다.


* 클러스터 스위치 CL2를 C2로 교체합니다.
+
** CL1에 연결된 모든 노드의 모든 클러스터 포트 또는 LIF의 트래픽은 C2에 연결된 두 번째 클러스터 포트 또는 LIF로 마이그레이션됩니다.
** CL1에 연결된 모든 노드의 모든 클러스터 포트에서 케이블을 뽑고 지원되는 분리 케이블을 사용하여 새 클러스터 스위치 C1에 다시 연결합니다.
** CL1과 C2 사이의 ISL 포트 간 케이블 연결을 끊고 지원되는 케이블 연결을 사용하여 C1에서 C2로 다시 연결합니다.
** 모든 노드의 C1에 연결된 모든 클러스터 포트 또는 LIF의 트래픽을 되돌릴 수 있습니다.


* 클러스터 세부 정보를 보여주는 예시와 함께 FAS9000 노드 2개가 클러스터에 추가되었습니다.


.다음 단계
link:cn5596-prepare-to-migrate.html["마이그레이션을 준비합니다"]..
