---
permalink: switch-cisco-3132q-v/concept-migrate-from-a-cisco-5596-switch-to-a-cisco-nexus-3232c.html 
sidebar: sidebar 
keywords: replace, cisco nexus 5596 cluster switch, 3132q-v 
summary: Cisco Nexus 5596 클러스터 스위치를 Cisco Nexus 3132Q-V 클러스터 스위치로 교체할 때 특정 구성 정보, 포트 연결 및 케이블 연결 요구 사항을 알고 있어야 합니다. 
---
= Cisco Nexus 5596 클러스터 스위치를 Cisco Nexus 3132Q-V 클러스터 스위치로 교체합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 5596 클러스터 스위치를 Cisco Nexus 3132Q-V 클러스터 스위치로 교체할 때 특정 구성 정보, 포트 연결 및 케이블 연결 요구 사항을 알고 있어야 합니다.

* 지원되는 클러스터 스위치는 다음과 같습니다.
+
** Nexus 5596
** Nexus 3132Q-V


* 10GbE 및 40/100 GbE 포트 수는 에서 사용할 수 있는 RCFs(참조 구성 파일)에 정의되어 있습니다 https://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/netapp_cnmn/download.shtml["Cisco ® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] 페이지.
* 클러스터 스위치는 노드 연결에 다음 포트를 사용합니다.
+
** 포트 e1/1-40(10GbE): Nexus 5596
** 포트 e1/1-30(40/100 GbE): Nexus 3132Q-V


* 클러스터 스위치는 다음과 같은 ISL(Inter-Switch Link) 포트를 사용합니다.
+
** 포트 e1/41-48(10GbE): Nexus 5596
** 포트 e1/31-32(40/100 GbE): Nexus 3132Q-V


* Hardware Universe_에는 Nexus 3132Q-V 스위치에 대해 지원되는 케이블 연결에 대한 정보가 포함되어 있습니다.
+
** 10GbE 클러스터 연결이 있는 노드는 QSFP-SFP+ 광 파이버 브레이크아웃 케이블 또는 QSFP-SFP+ 구리 브레이크아웃 케이블이 필요합니다.
** 40/100 GbE 클러스터 연결이 있는 노드에는 파이버 케이블 또는 QSFP/QSFP28 구리 직접 연결 케이블이 있는 지원되는 QSFP/QSFP 28광학 모듈이 필요합니다.


* 클러스터 스위치는 적절한 ISL 케이블 연결을 사용합니다.
+
** 시작: Nexus 5596 ~ Nexus 5596(SFP+ ~ SFP+)
+
*** 8x SFP+ 파이버 또는 구리 직접 연결 케이블


** 중간: Nexus 5596 - Nexus 3132Q-V(QSFP - 4xSFP+ 브레이크아웃)
+
*** QSFP-SFP+ 파이버 브레이크아웃 또는 구리 브레이크아웃 케이블 1개


** 최종: Nexus 3132Q-V - Nexus 3132Q-V(QSFP28 - QSFP28)
+
*** QSFP28 파이버 또는 구리 직접 연결 케이블 2개




* Nexus 3132Q-V 스위치에서 QSFP/QSFP28 포트를 40/100 기가비트 이더넷 또는 4 x10 기가비트 이더넷 모드로 작동할 수 있습니다.
+
기본적으로 40기가비트 이더넷 모드에는 32개의 포트가 있습니다. 이러한 40기가비트 이더넷 포트에는 2 튜플 명명 규칙이 적용됩니다. 예를 들어, 두 번째 40기가비트 이더넷 포트의 번호는 1/2로 지정됩니다. 구성을 40기가비트 이더넷에서 10기가비트 이더넷으로 변경하는 프로세스를 _breakout_이라고 하며, 구성을 10기가비트 이더넷에서 40기가비트 이더넷으로 변경하는 프로세스를 _breakin_이라고 합니다. 40/100 기가비트 이더넷 포트를 10기가비트 이더넷 포트로 분리하면 3 튜플 명명 규칙을 사용하여 결과 포트에 번호가 지정됩니다. 예를 들어, 두 번째 40기가비트 이더넷 포트의 분리 포트는 1/2/1, 1/2/2, 1/2/3 및 1/2/4로 번호가 지정됩니다.

* Nexus 3132Q-V 스위치의 왼쪽에는 해당 QSFP28 포트에 멀티플렉싱된 4개의 SFP+ 포트 세트가 있습니다.
+
기본적으로 RCF는 QSFP28 포트를 사용하도록 구성되었습니다.

+
[NOTE]
====
"hardware profile front portmode SFP-plus" 명령을 사용하여 Nexus 3132Q-V 스위치의 QSFP 포트 대신 4개의 SFP+ 포트를 활성화할 수 있습니다. 마찬가지로 "Hardware profile front portmode qsfp" 명령을 사용하여 4개의 SFP+ 포트 대신 QSFP 포트를 사용하도록 Nexus 3132Q-V 스위치를 재설정할 수 있습니다.

====
* Nexus 3132Q-V 스위치의 일부 포트가 10GbE 또는 40/100 GbE에서 실행되도록 구성했습니다.
+
[NOTE]
====
'interface breakout module 1 port 1-6 map 10g-4x' 명령어를 이용하여 처음 6개의 포트를 4x10 GbE 모드로 분리할 수 있다. 마찬가지로 'no interface breakout module 1 port 1-6 map 10g-4x' 명령을 사용하여 브레이크아웃 구성에서 처음 6개의 QSFP+ 포트를 다시 그룹화할 수 있습니다.

====
* 계획, 마이그레이션을 마치고 노드에서 Nexus 3132Q-V 클러스터 스위치로의 10GbE 및 40/100GbE 연결에 대한 필수 설명서를 읽었습니다.
* 이 절차에서 지원되는 ONTAP 및 NX-OS 버전은 _Cisco 이더넷 스위치_ 페이지에 있습니다.
+
http://support.netapp.com/NOW/download/software/cm_switches/["Cisco 이더넷 스위치"^]


