---
permalink: switch-cisco-3132q-v/concept-migrate-a-cn1610-switch-to-a-cisco-nexus-3232c-cluster-switch.html 
sidebar: sidebar 
keywords: replace, cn1610 cluster switches, cisco nexus 3132q-v 
summary: CN1610 클러스터 스위치를 Cisco Nexus 3132Q-V 클러스터 스위치로 교체할 때 특정 구성 정보, 포트 연결 및 케이블 연결 요구사항을 알고 있어야 합니다. 
---
= CN1610 클러스터 스위치를 Cisco Nexus 3132Q-V 클러스터 스위치로 교체합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
CN1610 클러스터 스위치를 Cisco Nexus 3132Q-V 클러스터 스위치로 교체할 때 특정 구성 정보, 포트 연결 및 케이블 연결 요구사항을 알고 있어야 합니다.

* 지원되는 클러스터 스위치는 다음과 같습니다.
+
** NetApp CN1610
** Cisco Nexus 3132Q-V


* 클러스터 스위치는 다음과 같은 노드 연결을 지원합니다.
+
** NetApp CN1610: 포트 0/1~0/12(10GbE)
** Cisco Nexus 3132Q-V: 포트 e1/1-30 (40/100 GbE)


* 클러스터 스위치는 다음과 같은 ISL(Inter-Switch Link) 포트를 사용합니다.
+
** NetApp CN1610: 포트 0/13~0/16(10GbE)
** Cisco Nexus 3132Q-V: 포트 e1/31-32(40/100 GbE)


* 를 클릭합니다 link:https://hwu.netapp.com/["Hardware Universe"^] Nexus 3132Q-V 스위치에 대한 지원되는 케이블 연결에 대한 자세한 내용은 다음을 참조하십시오.
+
** 10GbE 클러스터 연결이 있는 노드는 QSFP-SFP+ 광 파이버 브레이크아웃 케이블 또는 QSFP-SFP+ 구리 브레이크아웃 케이블이 필요합니다
** 40/100 GbE 클러스터 연결이 있는 노드에는 광 파이버 케이블 또는 QSFP/QSFP28 구리 직접 연결 케이블이 있는 지원되는 QSFP/QSFP28 광 모듈이 필요합니다


* 적절한 ISL 케이블 연결은 다음과 같습니다.
+
** 시작: CN1610(SFP+에서 SFP+로), SFP+ 광 파이버 4개 또는 구리 직접 연결 케이블
** 중간: Nexus 3132Q-V(QSFP - 4 SFP+ 브레이크아웃)에 대한 CN1610의 경우 QSFP - SFP+ 광 파이버 또는 구리 브레이크아웃 케이블 1개
** 마지막: Nexus 3132Q-V - Nexus 3132Q-V(QSFP28 - QSFP28), 2개의 QSFP28 광 파이버 또는 구리 직접 연결 케이블


* NetApp twinax 케이블은 Cisco Nexus 3132Q-V 스위치와 호환되지 않습니다.
+
현재 CN1610 구성에서 클러스터 노드-스위치 연결 또는 ISL 연결에 NetApp twinax 케이블을 사용하고, 현재 환경에서 Twinax를 계속 사용하려면 Cisco 케이블을 확보해야 합니다. 또는 ISL 연결과 클러스터 노드 간 접속 모두에 광 Fibre 케이블을 사용할 수 있습니다.

* Nexus 3132Q-V 스위치에서 QSFP/QSFP28 포트를 40/100Gb 이더넷 또는 4x 10Gb 이더넷 모드로 작동할 수 있습니다.
+
기본적으로 40/100Gb 이더넷 모드에는 32개의 포트가 있습니다. 이러한 40Gb 이더넷 포트에는 2튜플 명명 규칙이 적용됩니다. 예를 들어, 두 번째 40Gb 이더넷 포트의 번호는 1/2로 지정됩니다. 구성을 40Gb 이더넷에서 10Gb 이더넷으로 변경하는 프로세스를 _breakout_이라고 하며, 구성을 10Gb 이더넷에서 40Gb 이더넷으로 변경하는 프로세스를 _breakin_이라고 합니다. 10Gb 이더넷 포트로 40/100 Gb 이더넷 포트를 분리하면 결과 포트에 3개의 Tuple 명명 규칙을 사용하여 번호가 지정됩니다. 예를 들어, 두 번째 40Gb 이더넷 포트의 브레이크아웃 포트는 1/2/1, 1/2/2, 1/2/3 및 1/2/4로 번호가 지정됩니다.

* Nexus 3132Q-V 스위치의 왼쪽에는 첫 번째 QSFP 포트에 멀티플렉싱된 4개의 SFP+ 포트 세트가 있습니다.
+
기본적으로 RCF(Reference Configuration File)는 첫 번째 QSFP 포트를 사용하도록 구성되어 있습니다.

+
"hardware profile front portmode SFP-plus" 명령을 사용하여 Nexus 3132Q-V 스위치의 QSFP 포트 대신 4개의 SFP+ 포트를 활성화할 수 있습니다. 마찬가지로 "Hardware profile front portmode qsfp" 명령을 사용하여 4개의 SFP+ 포트 대신 QSFP 포트를 사용하도록 Nexus 3132Q-V 스위치를 재설정할 수 있습니다.

+

NOTE: 처음 4개의 SFP+ 포트를 사용하면 첫 번째 40GbE QSFP 포트가 비활성화됩니다.

* 10GbE 또는 40/100 GbE에서 실행되도록 Nexus 3132Q-V 스위치의 일부 포트를 구성해야 합니다.
+
'interface breakout module 1 port 1-6 map 10g-4x' 명령을 사용하여 처음 6개 포트를 4x 10GbE 모드로 분리할 수 있습니다. 마찬가지로 "no interface breakout module 1 port 1-6 map 10g-4x" 명령을 사용하여 _breakout_configuration에서 처음 6개의 QSFP+ 포트를 다시 그룹화할 수 있습니다.

* 계획, 마이그레이션을 완료한 후 노드에서 Nexus 3132Q-V 클러스터 스위치까지 10GbE 및 40/100 GbE 연결에 대한 필수 설명서를 읽어야 합니다.
* 이 절차에서 지원되는 ONTAP 및 NX-OS 버전이 에 나열되어 있습니다 link:http://support.netapp.com/NOW/download/software/cm_switches/["Cisco 이더넷 스위치"^] 페이지.
* 이 절차에서 지원되는 ONTAP 및 FASTPATH 버전은 에 나열되어 있습니다 link:http://support.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 및 CN1610 스위치"^] 페이지.

