---
permalink: switch-cisco-3132q-v/index.html 
sidebar: sidebar 
keywords: Cisco, 3132Q-V 
summary: 2노드 스위치 클러스터로 마이그레이션 
---
= 개요 및 요구사항: Cisco Nexus 3132Q-V 스위치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3132Q-V 스위치 설치 및 유지 보수에 대해서는 모든 요구 사항 및 권장 설명서를 참조하십시오.



== 작업 개요

Cisco Nexus 3132Q-V 스위치를 AFF 또는 FAS 클러스터의 클러스터 스위치로 사용할 수 있습니다. 설치 및 유지 보수 작업은 다음과 같습니다.

* Cisco Nexus 3132Q-V 클러스터 스위치에 NX-OS 및 참조 구성 파일(RCFs)을 설치합니다.
* Cisco Nexus 3132Q-V 클러스터 스위치를 사용하여 스위치가 없는 2노드 클러스터 환경에서 2노드 스위치 환경으로 마이그레이션
* 클러스터의 결함이 있는 Cisco Nexus 3132Q-V 스위치를 교체하고 스위치 운영 체제 및 참조 구성 파일을 다운로드합니다.
* Cisco Nexus 5596, Nexus 5020 또는 Nexus 5010 클러스터 스위치를 Cisco Nexus 3132Q-V 스위치로 대체합니다.
* NetApp CN1610 스위치를 Cisco Nexus 3132Q-V 클러스터 스위치로 교체합니다.




== 구성 요구 사항

클러스터를 구성하려면 스위치에 맞는 케이블 및 케이블 커넥터 수와 유형이 필요합니다. 처음 구성하는 스위치의 유형에 따라 포함된 콘솔 케이블을 사용하여 스위치 콘솔 포트에 연결해야 합니다. 또한 특정 네트워크 정보를 제공해야 합니다.



== 네트워크 요구 사항

모든 스위치 구성에 대해 다음 네트워크 정보가 필요합니다.

* 관리 네트워크 트래픽을 위한 IP 서브넷입니다.
* 각 스토리지 시스템 컨트롤러 및 해당하는 모든 스위치의 호스트 이름 및 IP 주소
* 대부분의 스토리지 시스템 컨트롤러는 이더넷 서비스 포트(렌치 아이콘)에 연결하여 e0M 인터페이스를 통해 관리됩니다. AFF A800 및 AFF A700 시스템에서 e0M 인터페이스는 전용 이더넷 포트를 사용합니다.


을 참조하십시오 https://hwu.netapp.com["Hardware Universe"^] 최신 정보를 확인하십시오.



== Smart Call Home 요구 사항

Smart Call Home은 네트워크의 하드웨어 및 소프트웨어 구성 요소를 모니터링하여 중요한 시스템 상태에 대한 이메일 기반 알림을 생성합니다. 장치에서 이벤트가 발생하면 Smart Call Home이 대상 프로필에 구성된 모든 수신자에게 경고를 표시합니다.

스마트 Call Home 시스템과 이메일을 사용하여 통신하려면 클러스터 네트워크 스위치를 구성해야 합니다. Cisco의 내장된 Smart Call Home 지원 기능을 활용하기 위해 선택적으로 클러스터 네트워크 스위치를 설정할 수 있습니다.

Smart Call Home 기능을 사용하기 전에 다음 사항을 고려하십시오.

* 이메일 서버가 있어야 합니다.
* 스위치는 이메일 서버에 대한 IP 연결이 있어야 합니다.
* 연락처 이름(SNMP 서버 연락처), 전화 번호 및 주소 정보를 구성해야 합니다. 이는 수신된 메시지의 출처를 확인하는 데 필요합니다.
* CCO ID는 해당 회사의 해당 Cisco SMARTnet Service 계약과 연결되어야 합니다.
* 장치를 등록하려면 Cisco SMARTnet Service가 있어야 합니다.


를 클릭합니다 http://www.cisco.com/c/en/us/products/switches/index.html["Cisco 지원 사이트"^] Smart Call Home을 구성하는 명령에 대한 정보를 포함합니다.



== 문서화 요구 사항

3132Q-V 스위치 및 ONTAP 클러스터를 설정하려면 특정 스위치 및 컨트롤러 설명서가 필요합니다.



=== 스위치 설명서

Cisco Nexus 3132Q-V 스위치를 설정하려면 에서 다음 설명서를 참조하십시오 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Cisco Nexus 3000 시리즈 스위치 지원"^] 페이지.

[cols="1,2"]
|===
| 문서 제목 | 설명 


 a| 
_Nexus 3000 시리즈 하드웨어 설치 가이드 _
 a| 
사이트 요구 사항, 스위치 하드웨어 세부 정보 및 설치 옵션에 대한 자세한 내용은 에 나와 있습니다.



 a| 
_Cisco Nexus 3000 시리즈 스위치 소프트웨어 구성 가이드_(스위치에 설치된 NX-OS 릴리즈에 대한 가이드 선택)
 a| 
ONTAP 작동을 위해 스위치를 구성하기 전에 필요한 초기 스위치 구성 정보를 제공합니다.



 a| 
_Cisco Nexus 3000 시리즈 NX-OS 소프트웨어 업그레이드 및 다운그레이드 가이드_(스위치에 설치된 NX-OS 릴리즈에 대한 가이드 선택)
 a| 
필요한 경우 스위치를 ONTAP 지원 스위치 소프트웨어로 다운그레이드하는 방법에 대한 정보를 제공합니다.



 a| 
_Cisco Nexus 3000 시리즈 NX-OS 명령 참조 마스터 색인 _
 a| 
Cisco에서 제공하는 다양한 명령 참조에 대한 링크를 제공합니다.



 a| 
_Cisco Nexus 3000 MIB 참조 _
 a| 
에서는 Nexus 3000 스위치의 MIB(Management Information Base) 파일에 대해 설명합니다.



 a| 
_Nexus 3000 시리즈 NX-OS 시스템 메시지 참조 _
 a| 
Cisco Nexus 3000 시리즈 스위치, 정보 스위치 및 기타 링크, 내부 하드웨어 또는 시스템 소프트웨어의 문제를 진단하는 데 도움이 되는 시스템 메시지에 대해 설명합니다.



 a| 
_Cisco Nexus 3000 시리즈 NX-OS 릴리즈 노트(스위치에 설치된 NX-OS 릴리즈에 대한 참고 사항 선택) _
 a| 
Cisco Nexus 3000 시리즈의 기능, 버그 및 제한에 대해 설명합니다.



 a| 
Cisco Nexus 6000, Cisco Nexus 5000 시리즈, Cisco Nexus 3000 시리즈 및 Cisco Nexus 2000 시리즈에 대한 규정, 규정 준수 및 안전 정보
 a| 
Nexus 3000 시리즈 스위치에 대한 국제 기관의 규정 준수, 안전 및 법적 정보를 제공합니다.

|===


=== ONTAP 시스템 설명서

ONTAP 시스템을 설정하려면 에서 사용 중인 운영 체제 버전에 대한 다음 문서가 필요합니다 https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9 문서 센터"^].

[cols="1,2"]
|===
| 이름 | 설명 


 a| 
컨트롤러별 설치 및 설정 지침 _
 a| 
에서는 NetApp 하드웨어를 설치하는 방법에 대해 설명합니다.



 a| 
ONTAP 설명서
 a| 
ONTAP 릴리스의 모든 측면에 대한 자세한 내용은 에 나와 있습니다.



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
NetApp 하드웨어 구성 및 호환성 정보를 제공합니다.

|===


=== 레일 키트 및 캐비닛 설명서

NetApp 캐비닛에 3132Q-V Cisco 스위치를 설치하려면 다음 하드웨어 설명서를 참조하십시오.

[cols="1,2"]
|===
| 이름 | 설명 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["42U 시스템 캐비닛, 상세 가이드"^]
 a| 
42U 시스템 캐비닛과 관련된 FRU에 대해 설명하고 유지보수 및 FRU 교체 지침을 제공합니다.



 a| 
link:task-install-a-cisco-nexus-3232c-cluster-switch-and-pass-through-panel-in-a-netapp-cabinet.html["NetApp 캐비닛에 Cisco Nexus 3132Q-V 스위치를 설치합니다"^]
 a| 
4포스트 NetApp 캐비닛에 Cisco Nexus 3132Q-V 스위치를 설치하는 방법에 대해 설명합니다.

|===