---
permalink: switch-cisco-3132q-v/index.html 
sidebar: sidebar 
keywords: Cisco, 3132Q-V 
summary: 2노드 스위치 클러스터로 마이그레이션 
---
= Cisco Nexus 3132Q-V 스위치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3132Q-V 스위치를 AFF 또는 FAS 클러스터의 클러스터 스위치로 사용할 수 있습니다.

* Cisco Nexus 3132Q-V 클러스터 스위치에 NX-OS 및 참조 구성 파일(RCFs)을 설치할 수 있습니다.
* Cisco Nexus 3132Q-V 클러스터 스위치를 사용하여 스위치가 없는 2노드 클러스터 환경에서 2노드 스위치 환경으로 마이그레이션할 수 있습니다.
* 결함이 있는 Cisco Nexus 3132Q-V 스위치를 클러스터에서 교체하고 스위치 운영 체제 및 참조 구성 파일을 다운로드할 수 있습니다.
* Cisco Nexus 5596, Nexus 5020 또는 Nexus 5010 클러스터 스위치를 Cisco Nexus 3132Q-V 스위치로 교체할 수 있습니다.
* NetApp CN1610 스위치를 Cisco Nexus 3132Q-V 클러스터 스위치로 교체할 수 있습니다.


.사용 가능한 설명서
다음 표에는 Cisco Nexus 3132Q-V 스위치에 사용할 수 있는 설명서가 나열되어 있습니다.

|===


| 제목 | 설명 


 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3132q-v/task-install-a-cisco-nexus-3232c-cluster-switch-and-pass-through-panel-in-a-netapp-cabinet.html["_NetApp ® 캐비닛에 Cisco ® Nexus 3132Q-V 클러스터 스위치 및 통과 패널을 설치합니다"^]
 a| 
전원 커넥터가 섀시 전면에 있고 배전 장치가 섀시 후면에 있는 시스템 캐비닛에 통과 패널을 설치하는 방법에 대해 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9336c-fx2/setup-switches.html["_Cisco ® Nexus 3132Q-V 클러스터 스위치 _ 를 설정합니다"^]
 a| 
Cisco Nexus 3132Q-V 클러스터 스위치를 설정하고 구성하는 방법에 대해 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3132q-v/task-install-nx-os-software-and-rcfs-on-cisco-nexus-3132q-v-cluster-switches.html["_NX-OS 및 참조 구성 파일(RCFs)_을 설치합니다"^]
 a| 
Nexus 3132Q-V 클러스터 스위치에 NX-OS 및 참조 구성 파일(RCFs)을 설치하는 방법에 대해 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3132q-v/concept-migrate-from-a-cisco-5596-switch-to-a-cisco-nexus-3232c.html["_Cisco Nexus 5596 클러스터 스위치를 Cisco Nexus 3132Q-V 클러스터 스위치 _ 로 교체합니다"^]
 a| 
이전 Cisco 스위치를 사용하는 환경에서 Cisco 3132Q-V 스위치를 사용하는 환경으로 마이그레이션하는 방법에 대해 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3132q-v/concept-migrate-a-cn1610-switch-to-a-cisco-nexus-3232c-cluster-switch.html["_CN1610 클러스터 스위치를 Cisco Nexus 3132Q-V 클러스터 스위치 _ 로 교체합니다"^]
 a| 
CN1610 스위치를 Cisco Nexus 3132Q-V 클러스터 스위치로 교체하는 절차를 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3132q-v/concept-migrate-from-a-two-node-switchless-cluster-to-a-cluster-with-cisco-nexus-3232c-cluster-switches.html["_2노드 스위치 없는 클러스터에서 마이그레이션 _"^]
 a| 
Cisco Nexus 3132Q-V 클러스터 스위치를 사용하여 스위치가 없는 2노드 클러스터 환경에서 2노드 스위치 환경으로 마이그레이션하는 방법에 대해 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-3132q-v/concept-replace-cisco-nexus-3132q-v-cluster-switches.html["_Cisco Nexus 3132Q-V 클러스터 스위치 _ 를 교체하십시오"^]
 a| 
클러스터에서 결함이 있는 Cisco Nexus 3132Q-V 스위치를 교체하고 스위치 운영 체제 및 참조 구성 파일을 다운로드하는 절차를 설명합니다.

|===