---
permalink: switch-cisco-3132q-v/migrate-switchless-to-switched-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Cisco Nexus 3132q-v 스위치를 구성하기 전에 프로세스 개요 및 명명법을 검토하십시오. 
---
= 마이그레이션 요구 사항
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
스위치가 없는 2노드 클러스터가 있는 경우 2노드 스위치 있는 클러스터로 마이그레이션하기 위한 해당 요구사항을 보려면 다음 절차를 검토하십시오.

[NOTE]
====
이 절차를 수행하려면 ONTAP 명령과 Cisco Nexus 3000 시리즈 스위치 명령을 모두 사용해야 합니다. ONTAP 명령은 별도의 표시가 없는 한 사용됩니다.

====
자세한 내용은 다음을 참조하십시오.

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 및 CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^]
* link:http://hwu.netapp.com["Hardware Universe"^]


.포트 및 노드 연결
Cisco Nexus 3132Q-V 클러스터 스위치를 사용하여 2노드 스위치 클러스터로 마이그레이션할 때 포트 및 노드 연결 및 케이블 연결 요구 사항을 이해해야 합니다.

* 클러스터 스위치는 ISL(Inter-Switch Link) 포트 e1/31-32를 사용합니다.
* 를 클릭합니다 link:https://hwu.netapp.com/["Hardware Universe"^] Nexus 3132Q-V 스위치에 대한 지원되는 케이블 연결에 대한 자세한 내용은 다음을 참조하십시오.
+
** 10GbE 클러스터 연결이 있는 노드에는 브레이크아웃 파이버 케이블이 있는 QSFP 광 모듈 또는 QSFP-SFP+ 구리 브레이크아웃 케이블이 필요합니다.
** 40GbE 클러스터 연결을 사용하는 노드는 지원되는 QSFP/QSFP28 광 모듈과 파이버 케이블 또는 QSFP/QSFP28 구리 직접 연결 케이블이 필요합니다.
** 클러스터 스위치는 2개의 QSFP28 파이버 또는 구리 직접 연결 케이블과 같은 적절한 ISL 케이블을 사용합니다.


* Nexus 3132Q-V에서 QSFP 포트를 40Gb 이더넷 또는 4x10Gb 이더넷 모드로 작동할 수 있습니다.
+
기본적으로 40Gb 이더넷 모드에는 32개의 포트가 있습니다. 이러한 40Gb 이더넷 포트에는 2튜플 명명 규칙이 적용됩니다. 예를 들어, 두 번째 40Gb 이더넷 포트의 번호는 1/2로 지정됩니다. 구성을 40Gb 이더넷에서 10Gb 이더넷으로 변경하는 프로세스를 _breakout_이라고 하며, 구성을 10Gb 이더넷에서 40Gb 이더넷으로 변경하는 프로세스를 _breakin_이라고 합니다. 40Gb 이더넷 포트를 10Gb 이더넷 포트로 분할하면 결과 포트에 3개의 튜플 명명 규칙을 사용하여 번호가 지정됩니다. 예를 들어, 두 번째 40Gb 이더넷 포트의 브레이크아웃 포트는 1/2/1, 1/2/2, 1/2/3 및 1/2/4로 번호가 지정됩니다.

* Nexus 3132Q-V의 왼쪽에는 첫 번째 QSFP 포트에 멀티플렉싱된 4개의 SFP+ 포트 세트가 있습니다.
+
기본적으로 RCF는 첫 번째 QSFP 포트를 사용하도록 구성되었습니다.

+
"hardware profile front portmode SFP-plus" 명령을 사용하여 Nexus 3132Q-V의 QSFP 포트 대신 4개의 SFP+ 포트를 활성화할 수 있습니다. 마찬가지로 "Hardware profile front portmode qsfp" 명령을 사용하여 4개의 SFP+ 포트 대신 QSFP 포트를 사용하도록 Nexus 3132Q-V를 재설정할 수 있습니다.

* Nexus 3132Q-V의 포트 중 일부를 10GbE 또는 40GbE에서 실행하도록 구성했는지 확인합니다.
+
'interface breakout module 1 port 1-6 map 10g-4x' 명령어를 사용하여 처음 6개 포트를 4x10 GbE 모드로 분리할 수 있다. 마찬가지로 'no interface breakout module 1 port 1-6 map 10g-4x' 명령을 사용하여 브레이크아웃 구성에서 처음 6개의 QSFP+ 포트를 다시 그룹화할 수 있습니다.

* 10GbE 및 40GbE 포트의 수는 다음에서 사용 가능한 참조 구성 파일(RCF)에 정의되어 있습니다.link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco ® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] .


.시작하기 전에
* 구성이 올바르게 설정되고 작동합니다.
* ONTAP 9.4 이상을 실행하는 노드
* 의 모든 클러스터 포트 `up` 상태.
* Cisco Nexus 3132Q-V 클러스터 스위치가 지원됩니다.
* 기존 클러스터 네트워크 구성에는 다음이 있습니다.
+
** Nexus 3132 클러스터 인프라는 두 스위치 모두에서 중복되고 완전히 작동합니다.
** 최신 RCF 및 NX-OS 버전을 스위치에서 사용할 수 있습니다.
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^]이 절차에서 지원되는 ONTAP 및 NX-OS 버전에 대한 정보가 있습니다.

** 두 스위치 모두에서 관리 접속 구성
** 두 스위치에 대한 콘솔 액세스
** 마이그레이션되지 않고 'UP' 상태에 있는 모든 클러스터 논리 인터페이스(LIF)
** 스위치의 초기 사용자 정의.
** 모든 ISL 포트가 활성화되고 케이블로 연결됩니다.




또한 노드에서 Nexus 3132Q-V 클러스터 스위치로의 10GbE 및 40GbE 연결에 대한 필수 문서를 계획, 마이그레이션 및 읽어야 합니다.

.사용된 예제에 대해 설명합니다
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* Nexus 3132Q-V 클러스터 스위치, C1 및 C2.
* 노드는 n1과 n2 이다.


[NOTE]
====
이 절차의 예에서는 각각 2개의 40GbE 클러스터 인터커넥트 포트 * e4a * 및 * e4e * 를 사용하는 2개의 노드를 사용합니다. 는 link:https://hwu.netapp.com/["Hardware Universe"^]사용자 플랫폼의 클러스터 포트에 대한 세부 정보를 제공합니다.

====
이 절차에서는 다음 시나리오에 대해 설명합니다.

* * n1_clus1 * 은 노드 * n1 * 의 클러스터 스위치 C1에 연결되는 첫 번째 클러스터 논리 인터페이스(LIF)입니다.
* * n1_clus2 * 는 노드 * n1 * 용 클러스터 스위치 C2에 연결되는 첫 번째 클러스터 LIF입니다.
* * n2_clus1 * 은 노드 * n2 * 용 클러스터 스위치 C1에 연결되는 첫 번째 클러스터 LIF입니다.
* * n2_clus2 * 는 노드 * n2 * 용 클러스터 스위치 C2에 연결되는 두 번째 클러스터 LIF입니다.
* 10GbE 및 40GbE 포트의 수는 다음에서 사용 가능한 참조 구성 파일(RCF)에 정의되어 있습니다.link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco ® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] .


[NOTE]
====
이 절차를 수행하려면 ONTAP 명령과 Cisco Nexus 3000 시리즈 스위치 명령을 모두 사용해야 합니다. ONTAP 명령은 별도의 표시가 없는 한 사용됩니다.

====
* 스위치가 없는 2노드 클러스터 설정에서 2개의 노드가 연결되어 작동하는 상태에서 클러스터가 시작됩니다.
* 첫 번째 클러스터 포트가 C1로 이동됩니다.
* 두 번째 클러스터 포트가 C2로 이동됩니다.
* 스위치가 없는 2노드 클러스터 옵션은 사용하지 않도록 설정됩니다.


.다음 단계
link:migrate-switchless-prepare-to-migrate.html["마이그레이션을 준비합니다"]..
