---
permalink: switch-cisco-3132q-v/migrate-switchless-prepare-to-migrate.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: Cisco Nexus 3132q-v 스위치를 AFF 또는 FAS 클러스터에서 클러스터 스위치로 사용할 수 있습니다. 
---
= 스위치가 없는 클러스터에서 스위치 클러스터로의 마이그레이션을 준비합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 단계를 따라 스위치가 없는 클러스터를 2노드 스위치 클러스터로의 마이그레이션을 준비하십시오.

.단계
. 이 클러스터에서 AutoSupport가 활성화되어 있는 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
'System node AutoSupport invoke-node * -type all-message maINT=xh'

+
_x_는 유지보수 기간(시간)입니다.

+
[NOTE]
====
AutoSupport 메시지는 유지보수 기간 동안 자동 케이스 생성이 억제되도록 이 유지보수 작업의 기술 지원에 알립니다.

====
. 각 클러스터 인터페이스의 관리 또는 운영 상태 확인:
+
.. 네트워크 포트 속성을 표시합니다.
+
네트워크 포트 쇼

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====
.. 논리 인터페이스에 대한 정보를 표시합니다.
+
네트워크 인터페이스 쇼

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====


. 필요에 따라 새 3132Q-V 스위치에 적절한 RCFs 및 이미지가 설치되어 있는지 확인하고 사용자 및 암호, 네트워크 주소 등과 같은 필수 사이트 사용자 지정을 수행합니다.
+
이때 두 스위치를 모두 준비해야 합니다. RCF 및 이미지 소프트웨어를 업그레이드해야 하는 경우 다음 단계를 따라야 합니다.

+
.. 로 이동합니다 link:http://support.netapp.com/NOW/download/software/cm_switches/["Cisco 이더넷 스위치"^] 페이지로 이동합니다.
.. 스위치 및 필요한 소프트웨어 버전을 해당 페이지의 표에 기록합니다.
.. 적절한 버전의 RCF를 다운로드합니다.
.. 설명 * 페이지에서 * 계속 * 을 선택하고 사용권 계약에 동의한 다음 * 다운로드 * 페이지의 지침에 따라 RCF를 다운로드합니다.
.. 해당 버전의 이미지 소프트웨어를 다운로드합니다.


. 설명 * 페이지에서 * 계속 * 을 선택하고 사용권 계약에 동의한 다음 * 다운로드 * 페이지의 지침에 따라 RCF를 다운로드합니다.


.다음 단계
link:migrate-switchless-configure-ports.html["포트를 구성합니다"]..
