---
permalink: switch-cisco-3132q-v/migrate-switchless-configure-ports.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: Cisco Nexus 3132q-v 스위치를 AFF 또는 FAS 클러스터에서 클러스터 스위치로 사용할 수 있습니다. 
---
= 스위치가 없는 클러스터에서 스위치 클러스터로 마이그레이션하도록 포트를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스위치가 없는 2노드 클러스터에서 2노드 스위치 클러스터로 마이그레이션하도록 포트를 구성하려면 다음 단계를 따르십시오.

.단계
. Nexus 3132Q-V 스위치 C1 및 C2에서 모든 노드 대상 포트 C1 및 C2를 비활성화하지만 ISL 포트는 비활성화하지 않습니다.
+
.예제 보기
[%collapsible]
====
다음 예에서는 RCF에서 지원되는 구성을 사용하여 Nexus 3132Q-V 클러스터 스위치 C1 및 C2에서 포트 1부터 30까지 비활성화되는 것을 보여 줍니다 `NX3132_RCF_v1.1_24p10g_26p40g.txt`:

[listing]
----
C1# copy running-config startup-config
[########################################] 100%
Copy complete.
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# shutdown
C1(config-if-range)# exit
C1(config)# exit

C2# copy running-config startup-config
[########################################] 100%
Copy complete.
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. 지원되는 케이블 연결을 사용하여 C1의 포트 1/31 및 1/32를 C2의 동일한 포트에 연결합니다.
. ISL 포트가 C1 및 C2에서 작동하는지 확인합니다.
+
'포트-채널 요약

+
.예제 보기
[%collapsible]
====
[listing]
----
C1# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)

C2# show port-channel summary
Flags: D - Down         P - Up in port-channel (members)
       I - Individual   H - Hot-standby (LACP only)
       s - Suspended    r - Module-removed
       S - Switched     R - Routed
       U - Up (port-channel)
       M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-        Type   Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)      Eth    LACP      Eth1/31(P)   Eth1/32(P)
----
====
. 스위치에 있는 인접 장치 목록을 표시합니다.
+
CDP 이웃의 성전

+
.예제 보기
[%collapsible]
====
[listing]
----
C1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C2                 Eth1/31        174    R S I s     N3K-C3132Q-V  Eth1/31
C2                 Eth1/32        174    R S I s     N3K-C3132Q-V  Eth1/32

Total entries displayed: 2

C2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute

Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
C1                 Eth1/31        178    R S I s     N3K-C3132Q-V  Eth1/31
C1                 Eth1/32        178    R S I s     N3K-C3132Q-V  Eth1/32

Total entries displayed: 2
----
====
. 각 노드의 클러스터 포트 연결을 표시합니다.
+
네트워크 디바이스 발견 쇼

+
.예제 보기
[%collapsible]
====
다음 예는 스위치가 없는 2노드 클러스터 구성을 보여줍니다.

[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    n2                  e4a              FAS9000
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    n1                  e4a              FAS9000
            e4e    n1                  e4e              FAS9000
----
====
. clus1 인터페이스를 clus2를 호스팅하는 물리적 포트로 마이그레이션합니다.
+
네트워크 인터페이스 마이그레이션

+
각 로컬 노드에서 이 명령을 실행합니다.

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus1 -source-node n1
-destination-node n1 -destination-port e4e
cluster::*> network interface migrate -vserver Cluster -lif n2_clus1 -source-node n2
-destination-node n2 -destination-port e4e
----
====
. 클러스터 인터페이스 마이그레이션 확인:
+
네트워크 인터페이스 쇼

+
.예제 보기
[%collapsible]
====
[listing]
----

cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4e     false
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4e     false
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 두 노드 모두에서 클러스터 포트 clus1 LIF를 종료합니다.
+
네트워크 포트 수정

+
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin false
cluster::*> network port modify -node n2 -port e4a -up-admin false
----
. 원격 클러스터 인터페이스의 연결을 확인합니다.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
를 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령입니다.

`network interface check cluster-connectivity start` 및 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
* 참고: * show 명령을 실행하기 전에 몇 초 동안 기다린 후 세부 정보를 표시합니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2        n2_clus1      none
       3/5/2022 19:21:20 -06:00   n1_clus2        n2_clus2      none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2        n1_clus1      none
       3/5/2022 19:21:20 -06:00   n2_clus2        n1_clus2      none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스에 대해 을 사용할 수도 있습니다 `cluster ping-cluster -node <name>` 연결 상태를 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node n1*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e4a	10.10.0.1
Cluster n1_clus2 n1		e4e	10.10.0.2
Cluster n2_clus1 n2		e4a	10.10.0.3
Cluster n2_clus2 n2		e4e	10.10.0.4

Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step10]] n1 노드의 e4a에서 케이블을 분리합니다.
+
실행 중인 구성을 참조하여 Nexus 3132Q-V에서 지원되는 케이블을 사용하여 스위치 C1(이 예에서는 포트 1/7)의 첫 번째 40GbE 포트를 n1의 e4a에 연결할 수 있습니다

+

NOTE: 새 Cisco 클러스터 스위치에 케이블을 다시 연결할 때 사용되는 케이블은 Cisco에서 지원하는 광섬유 또는 케이블이어야 합니다.

. 노드 n2의 e4a에서 케이블을 분리합니다.
+
지원되는 케이블 연결을 사용하여 실행 중인 구성을 참조하여 다음 사용 가능한 C1, 포트 1/8의 40GbE 포트에 e4a를 연결할 수 있습니다.

. C1에서 모든 노드 연결 포트를 활성화합니다.
+
.예제 보기
[%collapsible]
====
다음 예에서는 RCF에서 지원되는 구성을 사용하여 Nexus 3132Q-V 클러스터 스위치 C1 및 C2에서 포트 1~30을 사용하는 것을 보여 줍니다 `NX3132_RCF_v1.1_24p10g_26p40g.txt`:

[listing]
----
C1# configure
C1(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C1(config-if-range)# no shutdown
C1(config-if-range)# exit
C1(config)# exit
----
====
. 각 노드에서 첫 번째 클러스터 포트 e4a를 활성화합니다.
+
네트워크 포트 수정

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node n1 -port e4a -up-admin true
cluster::*> network port modify -node n2 -port e4a -up-admin true
----
====
. 클러스터가 두 노드에 모두 있는지 확인합니다.
+
네트워크 포트 쇼

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====
. 각 노드에서 마이그레이션된 모든 클러스터 인터커넥트 LIF를 되돌립니다.
+
네트워크 인터페이스 복원

+
.예제 보기
[%collapsible]
====
다음 예에서는 마이그레이션된 LIF가 홈 포트로 되돌아가는 것을 보여 줍니다.

[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus1
cluster::*> network interface revert -vserver Cluster -lif n2_clus1
----
====
. 모든 클러스터 인터커넥트 포트가 이제 홈 포트로 되돌려졌는지 확인합니다.
+
네트워크 인터페이스 쇼

+
현재 포트 열에 나열된 모든 포트에 대해 "홈"이라는 값이 표시되어야 합니다. 표시된 값이 false이면 포트가 복구되지 않은 것입니다.

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 각 노드의 클러스터 포트 연결을 표시합니다.
+
네트워크 디바이스 발견 쇼

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3132Q-V
            e4e    n2                  e4e              FAS9000
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3132Q-V
            e4e    n1                  e4e              FAS9000
----
====
. 각 노드의 콘솔에서 clus2를 포트 e4a로 마이그레이션합니다.
+
네트워크 인터페이스 마이그레이션

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver Cluster -lif n1_clus2 -source-node n1
-destination-node n1 -destination-port e4a
cluster::*> network interface migrate -vserver Cluster -lif n2_clus2 -source-node n2
-destination-node n2 -destination-port e4a
----
====
. 두 노드 모두에서 클러스터 포트 clus2 LIF를 종료합니다.
+
네트워크 포트 수정

+
다음 예는 두 노드에서 종료되는 지정된 포트를 보여줍니다.

+
[listing]
----
cluster::*> network port modify -node n1 -port e4e -up-admin false
cluster::*> network port modify -node n2 -port e4e -up-admin false
----
. 클러스터 LIF 상태를 확인합니다.
+
네트워크 인터페이스 쇼

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4a     false
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4a     false
4 entries were displayed.
----
====
. 노드 n1의 e4e에서 케이블을 분리합니다.
+
실행 중인 구성을 참조하여 Nexus 3132Q-V에서 지원되는 케이블을 사용하여 스위치 C2(이 예에서는 포트 1/7)의 첫 번째 40GbE 포트를 n1의 e4e에 연결할 수 있습니다

. 노드 n2의 e4e에서 케이블을 분리합니다.
+
지원되는 케이블 연결을 사용하여 실행 중인 구성을 참조하여 e4e를 C2, 포트 1/8에서 사용 가능한 다음 40 GbE 포트에 연결할 수 있습니다.

. C2에서 모든 노드 대상 포트를 활성화합니다.
+
.예제 보기
[%collapsible]
====
다음 예에서는 RCF에서 지원되는 구성을 사용하여 Nexus 3132Q-V 클러스터 스위치 C1 및 C2에서 포트 1~30을 사용하는 것을 보여 줍니다 `NX3132_RCF_v1.1_24p10g_26p40g.txt`:

[listing]
----
C2# configure
C2(config)# int e1/1/1-4,e1/2/1-4,e1/3/1-4,e1/4/1-4,e1/5/1-4,e1/6/1-4,e1/7-30
C2(config-if-range)# no shutdown
C2(config-if-range)# exit
C2(config)# exit
----
====
. 각 노드에서 두 번째 클러스터 포트 e4e를 활성화합니다.
+
네트워크 포트 수정

+
다음 예에서는 지정된 포트가 표시되는 것을 보여 줍니다.

+
[listing]
----
cluster::*> network port modify -node n1 -port e4e -up-admin true
cluster::*> network port modify -node n2 -port e4e -up-admin true
----
. 각 노드에서 마이그레이션된 모든 클러스터 인터커넥트 LIF를 되돌립니다.
+
네트워크 인터페이스 복원

+
다음 예에서는 마이그레이션된 LIF가 홈 포트로 되돌아가는 것을 보여 줍니다.

+
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
. 모든 클러스터 인터커넥트 포트가 이제 홈 포트로 되돌려졌는지 확인합니다.
+
네트워크 인터페이스 쇼

+
현재 포트 열에 나열된 모든 포트에 대해 "홈"이라는 값이 표시되어야 합니다. 표시된 값이 false이면 포트가 복구되지 않은 것입니다.

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster
 (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            n1_clus1   up/up      10.10.0.1/24       n1            e4a     true
            n1_clus2   up/up      10.10.0.2/24       n1            e4e     true
            n2_clus1   up/up      10.10.0.3/24       n2            e4a     true
            n2_clus2   up/up      10.10.0.4/24       n2            e4e     true
4 entries were displayed.
----
====
. 모든 클러스터 인터커넥트 포트가 'UP' 상태인지 확인합니다.
+
네트워크 포트 show-role cluster

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster
  (network port show)
Node: n1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -

Node: n2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e4a       Cluster      Cluster          up   9000 auto/40000  -        -
e4e       Cluster      Cluster          up   9000 auto/40000  -        -
4 entries were displayed.
----
====


.다음 단계
link:migrate-switchless-complete-migration.html["마이그레이션을 완료하십시오"]..
