---
permalink: switch-cisco-3132q-v/migrate-switchless-complete-migration.html 
sidebar: sidebar 
keywords: cisco 3132q-v, cluster switches 
summary: Cisco Nexus 3132q-v 스위치를 AFF 또는 FAS 클러스터에서 클러스터 스위치로 사용할 수 있습니다. 
---
= 스위치가 없는 2노드 클러스터에서 2노드 스위치 클러스터로 마이그레이션을 완료합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 단계를 따라 스위치가 없는 클러스터에서 2노드 스위치 클러스터로 마이그레이션을 완료합니다.

.단계
. 각 클러스터 포트가 각 노드에서 연결되는 클러스터 스위치 포트 번호를 표시합니다.
+
네트워크 디바이스 발견 쇼

+
.예제 보기
[%collapsible]
====
[listing]
----
	cluster::*> network device-discovery show
            Local  Discovered
Node        Port   Device              Interface        Platform
----------- ------ ------------------- ---------------- ----------------
n1         /cdp
            e4a    C1                  Ethernet1/7      N3K-C3132Q-V
            e4e    C2                  Ethernet1/7      N3K-C3132Q-V
n2         /cdp
            e4a    C1                  Ethernet1/8      N3K-C3132Q-V
            e4e    C2                  Ethernet1/8      N3K-C3132Q-V
----
====
. 검색 및 모니터링되는 클러스터 스위치 표시:
+
'system cluster-switch show'

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster::*> system cluster-switch show

Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
C1                          cluster-network    10.10.1.101      NX3132V
     Serial Number: FOX000001
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

C2                          cluster-network      10.10.1.102    NX3132V
     Serial Number: FOX000002
      Is Monitored: true
            Reason:
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    7.0(3)I4(1)
    Version Source: CDP

2 entries were displayed.
----
====
. 모든 노드에서 스위치가 없는 2노드 구성 설정을 사용하지 않도록 설정합니다.
+
'네트워크 옵션 스위치 없는 클러스터'

+
[listing]
----
network options switchless-cluster modify -enabled false
----
. 를 확인합니다 `switchless-cluster` 옵션이 비활성화되었습니다.
+
[listing]
----
network options switchless-cluster show
----
. 원격 클러스터 인터페이스의 연결을 확인합니다.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
를 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령입니다.

`network interface check cluster-connectivity start` 및 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
* 참고: * show 명령을 실행하기 전에 몇 초 동안 기다린 후 세부 정보를 표시합니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source          Destination       Packet
Node   Date                       LIF             LIF               Loss
------ -------------------------- --------------- ----------------- -----------
n1
       3/5/2022 19:21:18 -06:00   n1_clus2        n2_clus1      none
       3/5/2022 19:21:20 -06:00   n1_clus2        n2_clus2      none

n2
       3/5/2022 19:21:18 -06:00   n2_clus2        n1_clus1      none
       3/5/2022 19:21:20 -06:00   n2_clus2        n1_clus2      none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스에 대해 을 사용할 수도 있습니다 `cluster ping-cluster -node <name>` 연결 상태를 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node n1*
Host is n1
Getting addresses from network interface table...
Cluster n1_clus1 n1		e4a	10.10.0.1
Cluster n1_clus2 n1		e4e	10.10.0.2
Cluster n2_clus1 n2		e4a	10.10.0.3
Cluster n2_clus2 n2		e4e	10.10.0.4

Local = 10.10.0.1 10.10.0.2
Remote = 10.10.0.3 10.10.0.4
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 1500 byte MTU on 32 path(s):
    Local 10.10.0.1 to Remote 10.10.0.3
    Local 10.10.0.1 to Remote 10.10.0.4
    Local 10.10.0.2 to Remote 10.10.0.3
    Local 10.10.0.2 to Remote 10.10.0.4
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
1 paths up, 0 paths down (tcp check)
1 paths up, 0 paths down (ucp check)
----
--
====
. [[step6]] 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화합니다.
+
'System node AutoSupport invoke-node * -type all-message maINT=end'



.다음 단계
link:../switch-cshm/config-overview.html["스위치 상태 모니터링을 구성합니다"]..
