---
permalink: switch-cisco-3132q-v/migrate-switchless-to-switched-requirements.html 
sidebar: sidebar 
keywords: install, cisco nexus 3132q-v switch, 
summary: Cisco Nexus 3132q-v 스위치를 구성하기 전에 프로세스 개요와 명명법을 살펴보세요. 
---
= 이주 요구 사항
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
2노드 스위치리스 클러스터가 있는 경우 2노드 스위치 클러스터로 마이그레이션하는 데 적용되는 요구 사항을 알아보려면 이 절차를 검토하세요.

[NOTE]
====
이 절차에서는 ONTAP 명령과 Cisco Nexus 3000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 지정되지 않는 한 ONTAP 명령을 사용합니다.

====
자세한 내용은 다음을 참조하세요.

* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 및 CN1610"^]
* link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^]
* link:http://hwu.netapp.com["Hardware Universe"^]


.포트 및 노드 연결
Cisco Nexus 3132Q-V 클러스터 스위치를 사용하여 2노드 스위치 클러스터로 마이그레이션하는 경우 포트 및 노드 연결과 케이블 요구 사항을 이해해야 합니다.

* 클러스터 스위치는 ISL(Inter-Switch Link) 포트 e1/31-32를 사용합니다.
* 그만큼link:https://hwu.netapp.com/["Hardware Universe"^] Nexus 3132Q-V 스위치에 지원되는 케이블에 대한 정보가 포함되어 있습니다.
+
** 10GbE 클러스터 연결이 있는 노드에는 브레이크아웃 파이버 케이블이 있는 QSFP 광 모듈이나 QSFP-SFP+ 구리 브레이크아웃 케이블이 필요합니다.
** 40GbE 클러스터 연결이 있는 노드에는 파이버 케이블이나 QSFP/QSFP28 구리 직접 연결 케이블이 있는 지원되는 QSFP/QSFP28 광 모듈이 필요합니다.
** 클러스터 스위치는 적절한 ISL 케이블, 즉 2개의 QSFP28 파이버 또는 구리 직접 연결 케이블을 사용합니다.


* Nexus 3132Q-V에서는 QSFP 포트를 40Gb 이더넷 또는 4x10Gb 이더넷 모드로 작동할 수 있습니다.
+
기본적으로 40Gb 이더넷 모드에는 32개의 포트가 있습니다.  이 40Gb 이더넷 포트는 2-튜플 명명 규칙에 따라 번호가 매겨집니다.  예를 들어, 두 번째 40Gb 이더넷 포트는 1/2로 번호가 매겨집니다.  40Gb 이더넷에서 10Gb 이더넷으로 구성을 변경하는 과정을 _breakout_이라고 하고, 10Gb 이더넷에서 40Gb 이더넷으로 구성을 변경하는 과정을 _breakin_이라고 합니다.  40Gb 이더넷 포트를 10Gb 이더넷 포트로 분리하면 생성되는 포트에는 3-튜플 명명 규칙을 사용하여 번호가 지정됩니다.  예를 들어, 두 번째 40Gb 이더넷 포트의 브레이크아웃 포트는 1/2/1, 1/2/2, 1/2/3, 1/2/4로 번호가 매겨집니다.

* Nexus 3132Q-V의 왼쪽에는 첫 번째 QSFP 포트에 멀티플렉싱된 4개의 SFP+ 포트 세트가 있습니다.
+
기본적으로 RCF는 첫 번째 QSFP 포트를 사용하도록 구성되어 있습니다.

+
Nexus 3132Q-V의 경우 QSFP 포트 대신 4개의 SFP+ 포트를 활성화할 수 있습니다. `hardware profile front portmode sfp-plus` 명령.  마찬가지로, 다음을 사용하여 Nexus 3132Q-V를 재설정하여 4개의 SFP+ 포트 대신 QSFP 포트를 사용할 수 있습니다. `hardware profile front portmode qsfp` 명령.

* Nexus 3132Q-V의 일부 포트를 10GbE 또는 40GbE로 실행하도록 구성했는지 확인하세요.
+
다음을 사용하여 첫 번째 6개 포트를 4x10 GbE 모드로 분리할 수 있습니다. `interface breakout module 1 port 1-6 map 10g-4x` 명령.  마찬가지로, 다음을 사용하여 브레이크아웃 구성에서 처음 6개의 QSFP+ 포트를 다시 그룹화할 수 있습니다. `no interface breakout module 1 port 1-6 map 10g-4x` 명령.

* 10GbE 및 40GbE 포트의 수는 다음에서 사용 가능한 참조 구성 파일(RCF)에 정의되어 있습니다.link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco ® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] .


.시작하기 전에
* 구성이 올바르게 설정되고 작동합니다.
* ONTAP 9.4 이상을 실행하는 노드.
* 모든 클러스터 포트 `up` 상태.
* Cisco Nexus 3132Q-V 클러스터 스위치가 지원됩니다.
* 기존 클러스터 네트워크 구성은 다음과 같습니다.
+
** 두 스위치 모두에서 중복되고 완벽하게 작동하는 Nexus 3132 클러스터 인프라입니다.
** 스위치에 최신 RCF 및 NX-OS 버전을 설치하세요.
+
link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 이더넷 스위치"^]이 절차에서 지원되는 ONTAP 및 NX-OS 버전에 대한 정보가 있습니다.

** 두 스위치 모두에서 관리 연결이 가능합니다.
** 두 스위치 모두에 콘솔로 접근 가능.
** 모든 클러스터 논리 인터페이스(LIF) `up` 마이그레이션되지 않은 상태.
** 스위치의 초기 사용자 정의.
** 모든 ISL 포트가 활성화되고 케이블이 연결되었습니다.




또한 노드에서 Nexus 3132Q-V 클러스터 스위치로의 10GbE 및 40GbE 연결에 대한 필수 설명서를 계획, 마이그레이션하고 읽어야 합니다.

.사용된 예에 관하여
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* Nexus 3132Q-V 클러스터 스위치, C1 및 C2.
* 노드는 n1과 n2입니다.


[NOTE]
====
이 절차의 예에서는 두 개의 노드를 사용하며, 각 노드는 두 개의 40GbE 클러스터 상호 연결 포트 *e4a*와 *e4e*를 사용합니다.  그만큼link:https://hwu.netapp.com/["Hardware Universe"^] 플랫폼의 클러스터 포트에 대한 세부 정보가 있습니다.

====
이 절차는 다음과 같은 시나리오를 다룹니다.

* *n1_clus1*은 노드 *n1*의 클러스터 스위치 C1에 연결된 첫 번째 클러스터 논리 인터페이스(LIF)입니다.
* *n1_clus2*는 노드 *n1*의 클러스터 스위치 C2에 연결된 첫 번째 클러스터 LIF입니다.
* *n2_clus1*은 노드 *n2*의 클러스터 스위치 C1에 연결된 첫 번째 클러스터 LIF입니다.
* *n2_clus2*는 노드 *n2*의 클러스터 스위치 C2에 연결되는 두 번째 클러스터 LIF입니다.
* 10GbE 및 40GbE 포트의 수는 다음에서 사용 가능한 참조 구성 파일(RCF)에 정의되어 있습니다.link:https://mysupport.netapp.com/site/products/all/details/cisco-cluster-storage-switch/downloads-tab["Cisco ® 클러스터 네트워크 스위치 참조 구성 파일 다운로드"^] .


[NOTE]
====
이 절차에서는 ONTAP 명령과 Cisco Nexus 3000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 지정되지 않는 한 ONTAP 명령을 사용합니다.

====
* 클러스터는 두 개의 노드가 연결되어 2노드 스위치리스 클러스터 설정으로 작동하는 것으로 시작합니다.
* 첫 번째 클러스터 포트는 C1로 이동됩니다.
* 두 번째 클러스터 포트는 C2로 이동됩니다.
* 2노드 스위치리스 클러스터 옵션이 비활성화되었습니다.


.다음은 무엇인가요?
link:migrate-switchless-prepare-to-migrate.html["이주 준비"].
