---
permalink: switch-cisco-3132q-v/required-documentation-3132q.html 
sidebar: sidebar 
keywords: Cisco, 3132Q-V 
summary: Cisco Nexus 3132Q-V 스위치 설치 및 유지 보수에 대해서는 모든 권장 설명서를 참조하십시오. 
---
= Cisco Nexus 3132Q-V 스위치에 대한 설명서 요구사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3132Q-V 스위치 설치 및 유지 보수에 대해서는 모든 권장 설명서를 참조하십시오.



== 스위치 설명서

Cisco Nexus 3132Q-V 스위치를 설정하려면 에서 다음 설명서를 참조하십시오 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/series.html["Cisco Nexus 3000 시리즈 스위치 지원"^] 페이지.

[cols="1,2"]
|===
| 문서 제목 | 설명 


 a| 
_Nexus 3000 시리즈 하드웨어 설치 가이드 _
 a| 
사이트 요구 사항, 스위치 하드웨어 세부 정보 및 설치 옵션에 대한 자세한 내용은 에 나와 있습니다.



 a| 
_Cisco Nexus 3000 시리즈 스위치 소프트웨어 구성 가이드_(스위치에 설치된 NX-OS 릴리즈에 대한 가이드 선택)
 a| 
ONTAP 작동을 위해 스위치를 구성하기 전에 필요한 초기 스위치 구성 정보를 제공합니다.



 a| 
_Cisco Nexus 3000 시리즈 NX-OS 소프트웨어 업그레이드 및 다운그레이드 가이드_(스위치에 설치된 NX-OS 릴리즈에 대한 가이드 선택)
 a| 
필요한 경우 스위치를 ONTAP 지원 스위치 소프트웨어로 다운그레이드하는 방법에 대한 정보를 제공합니다.



 a| 
_Cisco Nexus 3000 시리즈 NX-OS 명령 참조 마스터 색인 _
 a| 
Cisco에서 제공하는 다양한 명령 참조에 대한 링크를 제공합니다.



 a| 
_Cisco Nexus 3000 MIB 참조 _
 a| 
에서는 Nexus 3000 스위치의 MIB(Management Information Base) 파일에 대해 설명합니다.



 a| 
_Nexus 3000 시리즈 NX-OS 시스템 메시지 참조 _
 a| 
Cisco Nexus 3000 시리즈 스위치, 정보 스위치 및 기타 링크, 내부 하드웨어 또는 시스템 소프트웨어의 문제를 진단하는 데 도움이 되는 시스템 메시지에 대해 설명합니다.



 a| 
_Cisco Nexus 3000 시리즈 NX-OS 릴리즈 노트(스위치에 설치된 NX-OS 릴리즈에 대한 참고 사항 선택) _
 a| 
Cisco Nexus 3000 시리즈의 기능, 버그 및 제한에 대해 설명합니다.



 a| 
Cisco Nexus 6000, Cisco Nexus 5000 시리즈, Cisco Nexus 3000 시리즈 및 Cisco Nexus 2000 시리즈에 대한 규정, 규정 준수 및 안전 정보
 a| 
Nexus 3000 시리즈 스위치에 대한 국제 기관의 규정 준수, 안전 및 법적 정보를 제공합니다.

|===


== ONTAP 시스템 설명서

ONTAP 시스템을 설정하려면 운영 체제 버전에 대한 다음 문서가 필요합니다.  https://docs.netapp.com/ontap-9/index.jsp["ONTAP 9"^] .

[cols="1,2"]
|===
| 이름 | 설명 


 a| 
컨트롤러별 설치 및 설정 지침 _
 a| 
에서는 NetApp 하드웨어를 설치하는 방법에 대해 설명합니다.



 a| 
ONTAP 설명서
 a| 
ONTAP 릴리스의 모든 측면에 대한 자세한 내용은 에 나와 있습니다.



 a| 
https://hwu.netapp.com["Hardware Universe"^]
 a| 
NetApp 하드웨어 구성 및 호환성 정보를 제공합니다.

|===


== 레일 키트 및 캐비닛 설명서

NetApp 캐비닛에 3132Q-V Cisco 스위치를 설치하려면 다음 하드웨어 설명서를 참조하십시오.

[cols="1,2"]
|===
| 이름 | 설명 


 a| 
https://library.netapp.com/ecm/ecm_download_file/ECMM1280394["42U 시스템 캐비닛, 상세 가이드"^]
 a| 
42U 시스템 캐비닛과 관련된 FRU에 대해 설명하고 유지보수 및 FRU 교체 지침을 제공합니다.



 a| 
link:install-cisco-nexus-3132qv.html["NetApp 캐비닛에 Cisco Nexus 3132Q-V 스위치를 설치합니다"^]
 a| 
4포스트 NetApp 캐비닛에 Cisco Nexus 3132Q-V 스위치를 설치하는 방법에 대해 설명합니다.

|===