---
permalink: switch-cisco-3232c-storage/install-rcf-software-3232c-storage.html 
sidebar: sidebar 
keywords: ssh, requirement, cluster, switch, health, monitor, cshm, log, collection, feature, cisco 3232c 
summary: '클러스터 스위치 상태 모니터(CSHM) 및 로그 수집 기능을 사용하려면 SSH가 필요합니다. Cisco 3232c 클러스터 스위치에서 SSH를 활성화하려면 먼저 SSH 키를 생성한 다음 SSH를 활성화합니다.' 
---
= 참조 구성 파일(RCF) 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nexus 3232C 스위치를 처음 설정한 후 참조 구성 파일(RCF)을 설치합니다.

.시작하기 전에
다음 설치 및 연결을 확인하세요.

* 스위치 구성의 현재 백업입니다.
* 완벽하게 작동하는 클러스터(로그에 오류나 유사한 문제가 없음).
* 현재의 RCF.
* 스위치에 대한 콘솔 연결. RCF를 설치할 때 필요합니다.


.이 작업에 관하여
이 절차에서는 ONTAP 명령과 Cisco Nexus 3000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 지정되지 않는 한 ONTAP 명령을 사용합니다.

link:prepare-install-cisco-nexus-3232c-storage.html["NX-OS 및 RCF 설치 준비"]에서 절차를 완료한 후 아래 단계를 따르십시오.



== 1단계: 스위치에 RCF 설치

. SSH 또는 시리얼 콘솔을 사용하여 스위치 s2에 로그인하십시오.
. FTP, TFTP, SFTP 또는 SCP와 같은 전송 프로토콜 중 하나를 사용하여 RCF를 스위치 s2의 bootflash에 복사하십시오. Cisco 명령에 대한 자세한 내용은 https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^]에서 해당 가이드를 참조하십시오.
+
.예를 보여주세요
[%collapsible]
====
이 예에서는 TFTP를 사용하여 스위치 s2의 bootflash에 RCF를 복사하는 방법을 보여줍니다.

[listing, subs="+quotes"]
----
s2# *copy tftp: bootflash: vrf management*
Enter source filename: *NX3232C-RCF-v1.13-1-Storage.txt*
Enter hostname for the tftp server: *172.22.201.50*
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
====
. 이전에 다운로드한 RCF를 부트플래시에 적용합니다.
+
Cisco 명령에 대한 자세한 내용은 해당 가이드를 참조하세요. https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-installation-guides-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^] .

+
.예를 보여주세요
[%collapsible]
====
이 예시는 스위치 s2에 RCF 파일 `NX9336C-FX2-RCF-v1.13-1-Storage.txt`이 설치되는 과정을 보여줍니다.

[listing, subs="+quotes"]
----
s2# *copy NX9336C-FX2-RCF-v1.13-1-Storage.txt running-config echo-commands*
----
====
+
[NOTE]
====
RCF의 *Installation notes*, *Important Notes* 및 *banner* 섹션을 철저히 읽어야 합니다. 스위치의 올바른 구성 및 작동을 확인하려면 이러한 지침을 읽고 따라야 합니다.

====
. 배너 출력을 검사합니다. `show banner motd` 명령.  스위치의 올바른 구성과 작동을 확인하려면 *중요 참고 사항* 아래의 지침을 읽고 따라야 합니다.
. RCF가 올바른 최신 버전인지 확인하세요.
+
`show running-config`

+
올바른 RCF가 있는지 확인하기 위해 출력을 확인할 때 다음 정보가 올바른지 확인하세요.

+
** RCF 배너
** 노드 및 포트 설정
** 사용자 정의
+
출력은 사이트 구성에 따라 달라집니다.  포트 설정을 확인하고 설치한 RCF에 대한 특정 변경 사항이 있는지 릴리스 노트를 참조하세요.



. 스위치 구성에 이전의 사용자 정의를 다시 적용합니다.
. RCF 버전과 스위치 설정이 올바른지 확인한 후 복사하세요. `running-config` 파일을 `startup-config` 파일.
+
`s2# copy running-config startup-config [########################################] 100% Copy complete`

. 스위치 s2를 재부팅합니다.
+
`s2# *reload*`

+
`This command will reboot the system. (y/n)?  [n] *y*`

. 스위치 s1에서 1단계부터 8단계까지 반복합니다.
. ONTAP 클러스터의 모든 노드의 노드 스토리지 포트와 스토리지 셸프 포트를 스위치 s1 및 s2에 연결합니다.




== 2단계: 스위치 연결 확인

. 스위치 포트가 *up* 상태인지 확인하십시오.
+
`show interface brief`

. 다음 명령을 사용하여 노드 스토리지 포트와 스토리지 쉘프 포트가 올바른 VLAN에 있는지 확인합니다.
+
`show vlan brief`

+
`show interface trunk`





== 3단계: ONTAP 클러스터 설정

NetApp System Manager를 사용하여 새 클러스터를 설정할 것을 권장합니다.

System Manager는 노드 관리 IP 주소 할당, 클러스터 초기화, 로컬 계층 생성, 프로토콜 구성, 초기 스토리지 프로비저닝을 포함하여 클러스터 설정 및 구성을 위한 간단하고 쉬운 워크플로를 제공합니다.

참조하다 https://docs.netapp.com/us-en/ontap/task_configure_ontap.html["System Manager를 사용하여 새 클러스터에 ONTAP 구성"] 설정 지침은 여기를 참조하세요.

.다음은 무엇인가요?
RCF를 설치한 후에는 다음을 수행할 수 있습니다. link:configure-ssh-keys.html["SSH 구성을 확인하세요"].
