---
permalink: switch-cisco-3232c-storage/upgrade-3232c-storage-switches.html 
sidebar: sidebar 
keywords: upgrade, cisco nexus, 3232c storage switch 
summary: 'Cisco NX-OS 소프트웨어와 참조 구성 파일(RCF)은 Cisco Nexus 3232C 스토리지 스위치에서 업그레이드할 수 있습니다.' 
---
= Cisco Nexus 3232C 스토리지 스위치 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 3232C 스위치에서 Cisco NX-OS 소프트웨어와 참조 구성 파일(RCF)을 업그레이드하려면 다음 단계를 따르세요.



== 검토 요구 사항

.시작하기 전에
스토리지 스위치에서 NX-OS 소프트웨어와 RCF를 업그레이드하기 전에 다음 조건이 충족되는지 확인하세요.

* 스위치는 완벽하게 작동합니다(로그에 오류나 이와 유사한 문제가 없어야 함).
* NX-OS만 설치하고 현재 RCF 버전을 유지하는 경우, 원하는 부트 이미지를 반영하도록 RCF에서 원하는 부트 변수를 확인하거나 설정해야 합니다.
+
현재 부트 이미지를 반영하도록 부트 변수를 변경해야 하는 경우 RCF를 다시 적용하기 전에 변경해야 합니다. 이렇게 하면 향후 재부팅 시 올바른 버전이 인스턴스화됩니다.

* link:http://www.cisco.com/en/US/products/ps9670/prod_installation_guides_list.html["Cisco Nexus 3000 시리즈 스위치"^] 페이지에서 제공되는 적절한 소프트웨어 및 업그레이드 가이드를 참조하여 Cisco 스토리지 업그레이드 및 다운그레이드 절차에 대한 전체 문서를 확인했습니다.
* 10GbE 및 40/100GbE 포트 수는 link:https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco® 이더넷 스위치"^] 페이지에서 제공되는 RCF(Reference Configuration File)에 정의되어 있습니다.




== 스위치를 교체하세요

.예시에 관하여
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 두 개의 저장 스위치의 이름은 S1과 S2입니다.
* 노드는 node1과 node2입니다.


이 절차의 예에서는 두 개의 노드를 사용합니다. 두 개의 저장 포트가 있는 노드1과 두 개의 저장 포트가 있는 노드2입니다. 를 참조하십시오link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] 플랫폼에서 올바른 저장 포트를 확인하세요. 보다 link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["HWU에 없는 추가 정보 중 장비를 설치하는 데 필요한 정보는 무엇입니까?"^] 스위치 설치 요구 사항에 대한 자세한 내용은 다음을 참조하십시오.


NOTE: 이 절차에서는 ONTAP 명령과 Cisco Nexus 3000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 지정되지 않는 한 ONTAP 명령을 사용합니다.  명령 출력은 ONTAP 릴리스에 따라 달라질 수 있습니다.



=== 1단계: 스위치 및 포트의 상태 확인

. AutoSupport 가 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_는 유지 관리 기간(시간)입니다.

+

NOTE: AutoSupport 메시지는 기술 지원팀에 이 유지 관리 작업을 알려 유지 관리 기간 동안 자동 케이스 생성이 억제되도록 합니다.

. 스토리지 스위치를 사용할 수 있는지 확인하세요.
+
`system switch ethernet show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
S1
                            storage-network    172.17.227.5     NX3232C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(3)
    Version Source: CDP

S2
                            storage-network    172.17.227.6     NX3232C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(3)
    Version Source: CDP

2 entries were displayed.
storage::*>
----
====
. 노드 포트가 정상적이고 작동하는지 확인하세요.
+
`storage port show -port-type ENET`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ----------- ----
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
====
. 스토리지 스위치나 케이블 문제가 없는지 확인하세요.
+
`system health alert show -instance`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====




=== 2단계: RCF를 Cisco 스위치 S2로 복사

. FTP, HTTP, TFTP, SFTP 또는 SCP 중 하나의 전송 프로토콜을 사용하여 스위치 S2의 RCF를 스위치 부트플래시에 복사합니다.
+
Cisco 명령에 대한 자세한 내용은 link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^]의 해당 가이드를 참조하십시오.

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 HTTP를 사용하여 RCF를 스위치 S2의 부트플래시에 복사하는 방법을 보여줍니다.

[listing, subs="+quotes"]
----
S2# *copy http://172.16.10.1//cfg/Nexus_3232C_RCF_v1.6-Storage.txt bootflash: vrf management*
% Total    % Received % Xferd  Average  Speed   Time    Time     Time                          Current
                               Dload    Upload  Total   Spent    Left                          Speed
  100        3254       100    3254     0       0       8175     0 --:--:-- --:--:-- --:--:-   8301
Copy complete, now saving to disk (please wait)...
Copy complete.
S2#
----
====
. 이전에 다운로드한 RCF를 부트플래시에 적용합니다.
+
`copy bootflash:`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 RCF 파일을 보여줍니다. `Nexus_3232C_RCF_v1.6-Storage.txt` 스위치 S2에 설치 중:

[listing, subs="+quotes"]
----
S2# *copy Nexus_3232C_RCF_v1.6-Storage.txt running-config echo-commands*
----
====
. RCF 파일이 올바른 최신 버전인지 확인하세요.
+
`show running-config`

+
올바른 RCF가 있는지 확인하기 위해 출력을 확인할 때 다음 정보가 올바른지 확인하세요.

+
** RCF 배너
** 노드 및 포트 설정
** 사용자 정의
+
출력은 사이트 구성에 따라 달라집니다.  포트 설정을 확인하고 설치한 RCF에 대한 특정 변경 사항이 있는지 릴리스 노트를 참조하세요.

+
[NOTE]
====
배너 출력에서 `show banner motd` 명령을 실행하려면 *중요 참고 사항* 섹션의 지침을 읽고 따라 스위치의 적절한 구성과 작동을 확인해야 합니다.

====
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
S2# show banner motd

******************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : Cisco Nexus 3232C
* Filename : Nexus_3232C_RCF_v1.6-Storage.txt
* Date     : Oct-20-2020
* Version  : v1.6
*
* Port Usage : Storage configuration
* Ports  1-32: Controller and Shelf Storage Ports
* Ports 33-34: Disabled
*
* IMPORTANT NOTES*
* - This RCF utilizes QoS and requires TCAM re-configuration, requiring RCF
*   to be loaded twice with the Storage Switch rebooted in between.
*
* - Perform the following 4 steps to ensure proper RCF installation:
*
*   (1) Apply RCF first time, expect following messages:
*       - Please save config and reload the system...
*       - Edge port type (portfast) should only be enabled on ports...
*       - TCAM region is not configured for feature QoS class IPv4 ingress...
*
*   (2) Save running-configuration and reboot Cluster Switch
*
*   (3) After reboot, apply same RCF second time and expect following messages:
*       - % Invalid command at '^' marker
*       - Syntax error while parsing...
*
*   (4) Save running-configuration again
******************************************************************************
S2#
----
====
+

NOTE: 처음으로 RCF를 적용할 때 *오류: VSH 명령을 쓸 수 없습니다* 메시지가 나타날 것으로 예상되며 무시해도 됩니다.



. 소프트웨어 버전과 스위치 설정이 올바른지 확인한 후 복사하세요. `running-config` 파일을 `startup-config` 스위치 S2의 파일입니다.
+
Cisco 명령에 대한 자세한 내용은 link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^]의 해당 가이드를 참조하십시오.

+
.예를 보여주세요
[%collapsible]
====
다음 예는 다음을 보여줍니다. `running-config` 파일이 성공적으로 복사되었습니다 `startup-config` 파일:

[listing]
----
S2# copy running-config startup-config
[########################################] 100% Copy complete.
----
====




=== 3단계: NX-OS 이미지를 Cisco 스위치 S2에 복사하고 재부팅합니다.

. NX-OS 이미지를 스위치 S2에 복사합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
S2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/nxos.9.3.4.bin*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/nxos.9.3.4.bin  /bootflash/nxos.9.3.4.bin
/code/nxos.9.3.4.bin  100% 1261MB   9.3MB/s   02:15
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.

cs2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/n9000-epld.9.3.4.img*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/n9000-epld.9.3.4.img  /bootflash/n9000-epld.9.3.4.img
/code/n9000-epld.9.3.4.img  100%  161MB   9.5MB/s   00:16
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
====
. 다음에 스위치 S2를 재부팅할 때 새 버전이 로드되도록 시스템 이미지를 설치하세요.
+
다음 출력에 표시된 대로 스위치는 10초 후에 새 이미지로 재부팅됩니다.

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
S2# *install all nxos bootflash:nxos.9.3.4.bin*
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive

Verifying image bootflash:/nxos.9.3.4.bin for boot variable "nxos".
[####################] 100% -- SUCCESS

Verifying image type.
[####################] 100% -- SUCCESS

Preparing "nxos" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Preparing "bios" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS

Performing module support checks.
[####################] 100% -- SUCCESS

Notifying services about system upgrade.
[####################] 100% -- SUCCESS


Compatibility check is done:
Module  bootable          Impact  Install-type  Reason
------  --------  --------------  ------------  ------
     1       yes      disruptive         reset  default upgrade is not hitless


Images will be upgraded according to following table:
Module       Image                  Running-Version(pri:alt)           New-Version  Upg-Required
------  ----------  ----------------------------------------  --------------------  ------------
     1        nxos                                    9.3(3)                9.3(4)           yes
     1        bios     v08.37(01/28/2020):v08.23(09/23/2015)    v08.38(05/29/2020)            no


Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n] *y*
input string too long
Do you want to continue with the installation (y/n)?  [n] *y*

Install is in progress, please wait.

Performing runtime checks.
[####################] 100% -- SUCCESS

Setting boot variables.
[####################] 100% -- SUCCESS

Performing configuration copy.
[####################] 100% -- SUCCESS

Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS


Finishing the upgrade, switch will reboot in 10 seconds.
S2#
----
====
. 구성을 저장합니다.
+
Cisco 명령에 대한 자세한 내용은 link:https://www.cisco.com/c/en/us/support/switches/nexus-3000-series-switches/products-command-reference-list.html["Cisco Nexus 3000 시리즈 NX-OS 명령 참조"^]의 해당 가이드를 참조하십시오.

+
시스템을 재부팅하라는 메시지가 표시됩니다.

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
S2# *copy running-config startup-config*
[########################################] 100% Copy complete.
S2# *reload*
This command will reboot the system. (y/n)?  [n] *y*
----
====
. 스위치에 새로운 NX-OS 버전 번호가 있는지 확인하세요.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
S2# *show version*
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.

Software
  BIOS: version 08.38
 NXOS: version 9.3(4)
  BIOS compile time:  05/29/2020
  NXOS image file is: bootflash:///nxos.9.3.4.bin
  NXOS compile time:  4/28/2020 21:00:00 [04/29/2020 02:28:31]


Hardware
  cisco Nexus3000 C3232C Chassis (Nexus 9000 Series)
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K

  Device name: S2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)

Last reset at 157524 usecs after Mon Nov  2 18:32:06 2020
  Reason: Reset due to upgrade
  System version: 9.3(3)
  Service:

plugin
  Core Plugin, Ethernet Plugin

Active Package(s):

S2#
----
====




=== 4단계: 스위치 및 포트의 상태를 다시 확인합니다.

. 재부팅 후 스토리지 스위치를 사용할 수 있는지 다시 확인하세요.
+
`system switch ethernet show`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system switch ethernet show*
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- ---------------
S1
                            storage-network    172.17.227.5     NX3232C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

S2
                            storage-network    172.17.227.6    NX3232C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(4)
    Version Source: CDP

2 entries were displayed.
storage::*>
----
====
. 재부팅 후 스위치 포트가 정상적이고 작동하는지 확인하세요.
+
`storage port show -port-type ENET`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *storage port show -port-type ENET*
                                      Speed                       VLAN
Node               Port Type  Mode    (Gb/s) State    Status        ID
------------------ ---- ----- ------- ------ -------- ----------- ----
node1
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
node2
                   e3a  ENET  storage    100 enabled  online        30
                   e3b  ENET  storage      0 enabled  offline       30
                   e7a  ENET  storage      0 enabled  offline       30
                   e7b  ENET  storage    100 enabled  online        30
----
====
. 클러스터에 스토리지 스위치나 케이블 문제가 없는지 다시 확인하세요.
+
`system health alert show -instance`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
storage::*> *system health alert show -instance*
There are no entries matching your query.
----
====
. 스위치 S1에서 NX-OS 소프트웨어와 RCF를 업그레이드하려면 절차를 반복합니다.
. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.다음은 무엇인가요?
스위치를 업그레이드한 후 link:../switch-cshm/config-overview.html["스위치 상태 모니터링 구성"]할 수 있습니다.
