---
permalink: switch-netapp-cn1610/install-fastpath-rcf-831.html 
sidebar: sidebar 
keywords: fastpath, software, install, netapp cluster switches, rcfs, ontap 
summary: 'ONTAP 8.3.1 이상 버전을 위해 NetApp CN1610 클러스터 스위치에 FASTPATH 소프트웨어와 참조 구성 파일(RCF)을 설치하십시오.' 
---
= ONTAP 8.3.1 이상 버전을 위한 NetApp CN1610 클러스터 스위치에 FASTPATH 소프트웨어 및 RCF 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 8.3.1 이상 버전을 위해 NetApp CN1610 클러스터 스위치에 FASTPATH 소프트웨어와 참조 구성 파일(RCF)을 설치하십시오.

NetApp CN1601 관리 스위치와 ONTAP 8.3.1 이상을 실행하는 CN1610 클러스터 스위치의 설치 단계는 동일합니다. 단, 두 모델은 서로 다른 소프트웨어와 RCF가 필요합니다.



[[review-requirements]]
== 검토 요구 사항

.시작하기 전에
다음 사항이 있는지 확인하세요.

* 스위치 구성의 현재 백업입니다.
* 완벽하게 작동하는 클러스터(로그에 오류가 없고 클러스터 네트워크 인터페이스 카드(NIC)에 결함이 있거나 유사한 문제가 없음).
* 클러스터 스위치의 포트 연결이 완벽하게 작동합니다.
* 모든 클러스터 포트가 설정되었습니다.
* 모든 클러스터 논리 인터페이스(LIF)가 설정되어 있어야 합니다(마이그레이션되지 않았어야 함).
* 성공적인 통신 경로: ONTAP(권한: 고급) `cluster ping-cluster -node node1` 명령은  `larger than PMTU communication`이(가) 모든 경로에서 성공적임을 나타내야 합니다.
* FASTPATH, RCF 및 ONTAP의 지원되는 버전.
+
지원되는 FASTPATH, RCF 및 ONTAP 버전에 대한 정보는 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 및 CN1610 스위치"^] 페이지의 스위치 호환성 표를 참조하십시오.





[[install-the-fastpath-software]]
== FASTPATH 소프트웨어를 설치합니다.

다음 절차는 클러스터형 Data ONTAP 8.2 구문을 사용합니다. 따라서 클러스터 Vserver, LIF 이름 및 CLI 출력은 Data ONTAP 8.3과 다릅니다.

RCF 버전과 FASTPATH 버전의 명령 구문 간에 명령 종속성이 있을 수 있습니다.


NOTE: RCF 버전 1.2에서는 보안상의 이유로 Telnet 지원이 명시적으로 비활성화되었습니다. RCF 1.2 설치 중 연결 문제를 방지하려면 SSH(Secure Shell)가 활성화되어 있는지 확인하십시오. The https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp CN1610 스위치 관리자 가이드"^]에는 SSH에 대한 자세한 내용이 있습니다.

.예시에 관하여
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* NetApp 스위치 두 개의 이름은 각각 cs1과 cs2입니다.
* 클러스터 논리 인터페이스(LIF) 이름은 노드 1의 경우 node1_clus1 및 node1_clus2이고, 노드 2의 경우 node2_clus1 및 node2_clus2입니다. (클러스터에는 최대 24개의 노드를 구성할 수 있습니다.)
* 스토리지 가상 머신(SVM)의 이름은 Cluster입니다.
* 그만큼 `cluster1::*>` 프롬프트는 클러스터의 이름을 나타냅니다.
* 각 노드의 클러스터 포트는 e0a와 e0b로 명명됩니다.
+
link:https://hwu.netapp.com/["Hardware Universe"^]에는 플랫폼에서 지원되는 실제 클러스터 포트에 대한 자세한 정보가 있습니다.

* 지원되는 스위치 간 링크(ISL)는 포트 0/13부터 0/16까지입니다.
* 지원되는 노드 연결 포트는 0/1부터 0/12까지입니다.




[[step-1-migrate-cluster]]
=== 1단계: 클러스터 마이그레이션

. 클러스터의 네트워크 포트에 대한 정보를 표시합니다.
+
`network port show -_ipspace cluster_`

+
.예를 보여주세요
[%collapsible]
====
다음 예시는 해당 명령의 출력 유형을 보여줍니다.

[listing]
----
cluster1::> network port show -ipspace cluster
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. 클러스터의 LIF에 대한 정보를 표시합니다.
+
`network interface show -_role cluster_`

+
.예를 보여주세요
[%collapsible]
====
다음 예는 클러스터의 논리 인터페이스를 보여줍니다. 이 예에서  `-role` 매개변수는 클러스터 포트와 연결된 LIF에 대한 정보를 표시합니다.

[listing]
----
cluster1::> network interface show -role cluster
  (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16    node1         e0a     true
            node1_clus2  up/up    10.254.206.128/16  node1         e0b     true
            node2_clus1  up/up    10.254.48.152/16   node2         e0a     true
            node2_clus2  up/up    10.254.42.74/16    node2         e0b     true
4 entries were displayed.
----
====
. 각 노드에서 노드 관리 LIF를 사용하여 node1_clus2를 node1의 e0a로, node2_clus2를 node2의 e0a로 마이그레이션합니다.
+
`network interface migrate`

+
각 클러스터 LIF를 소유한 컨트롤러 콘솔에서 명령을 입력해야 합니다.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster1::> network interface migrate -vserver Cluster -lif node1_clus2 -destination-node node1 -destination-port e0a
cluster1::> network interface migrate -vserver Cluster -lif node2_clus2 -destination-node node2 -destination-port e0a
----
====
+

NOTE: 이 명령에서 클러스터 이름은 대소문자를 구분하며, 각 노드에서 실행해야 합니다. 일반 클러스터 LIF에서는 이 명령을 실행할 수 없습니다.

. 노드에서  `network interface show` 명령을 사용하여 마이그레이션이 완료되었는지 확인하십시오.
+
.예를 보여주세요
[%collapsible]
====
다음 예시는 clus2가 node1 및 node2 노드의 e0a 포트로 마이그레이션되었음을 보여줍니다.

[listing]
----
cluster1::> **network interface show -role cluster**
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16   node1          e0a     true
            node1_clus2  up/up    10.254.206.128/16 node1          e0a     false
            node2_clus1  up/up    10.254.48.152/16  node2          e0a     true
            node2_clus2  up/up    10.254.42.74/16   node2          e0a     false
4 entries were displayed.
----
====
. 권한 수준을 고급으로 변경하고, 계속할지 묻는 메시지가 나타나면 y를 입력하십시오.
+
`set -privilege advanced`

+
고급 프롬프트(*>)가 나타납니다.

. 양쪽 노드에서 클러스터 포트 e0b를 종료하십시오.
+
`network port modify -node _node_name_ -port _port_name_ -up-admin false`

+
각 클러스터 LIF를 소유한 컨트롤러 콘솔에서 명령을 입력해야 합니다.

+
.예를 보여주세요
[%collapsible]
====
다음 예는 모든 노드에서 e0b 포트를 종료하는 명령을 보여줍니다.

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin false
cluster1::*> network port modify -node node2 -port e0b -up-admin false
----
====
. 두 노드 모두에서 e0b 포트가 종료되어 있는지 확인하십시오.
+
`network port show`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster1::*> network port show -role cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
4 entries were displayed.
----
====
. cs1의 ISL(Inter-Switch Link) 포트를 종료하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config)#interface 0/13-0/16
(cs1) (Interface 0/13-0/16)#shutdown
(cs1) (Interface 0/13-0/16)#exit
(cs1) (Config)#exit
----
====
. CS2에서 현재 활성 이미지를 백업합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.5     1.1.0.3            1.1.0.5            1.1.0.5

(cs2) # copy active backup
Copying active to backup
Copy operation successful
----
====




[[step-2-install-the-fastpath-software-and-rcf]]
=== 2단계: FASTPATH 소프트웨어 및 RCF 설치

. FASTPATH 소프트웨어의 실행 중인 버전을 확인하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description............................. NetApp CN1610, 1.1.0.5, Linux
                                                2.6.21.7
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.1.0.5
Operating System............................... Linux 2.6.21.7
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893

--More-- or (q)uit


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
. 스위치에 이미지 파일을 다운로드합니다.
+
이미지 파일을 활성 이미지에 복사하면 재부팅 시 해당 이미지가 실행 중인 FASTPATH 버전을 설정합니다. 이전 이미지는 백업으로 계속 사용할 수 있습니다.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) #copy sftp://root@10.22.201.50//tftpboot/NetApp_CN1610_1.2.0.7.stk active
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /tftpboot/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. 현재 활성화된 부팅 이미지 버전과 차기 활성화될 부팅 이미지 버전을 확인하십시오.
+
`show bootvar`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.8     1.1.0.8            1.1.0.8            1.2.0.7
----
====
. 스위치에 새 이미지 버전에 맞는 RCF 파일을 설치하십시오.
+
RCF 버전이 이미 올바르다면 ISL 포트를 활성화하십시오.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) #copy tftp://10.22.201.50//CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr

Mode........................................... TFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.


Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y


Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
====
+

NOTE: The `.scr` 확장자는 스크립트를 실행하기 전에 파일 이름의 일부로 설정해야 합니다. 이 확장자는 FASTPATH 운영 체제용입니다.

+
스위치는 스크립트가 스위치로 다운로드될 때 자동으로 유효성을 검사합니다. 검사 결과는 콘솔에 출력됩니다.

. 스크립트가 다운로드되어 지정한 파일 이름으로 저장되었는지 확인하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) #script list

Configuration Script Name        Size(Bytes)
-------------------------------- -----------
CN1610_CS_RCF_v1.2.scr                  2191

1 configuration script(s) found.
2541 Kbytes free.
----
====
. 스크립트를 스위치에 적용합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.2.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.2.scr' applied.
----
====
. 변경 사항이 스위치에 적용되었는지 확인한 후 저장하십시오.
+
`show running-config`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) #show running-config
----
====
. 현재 실행 중인 구성을 저장하여 스위치를 재부팅할 때 시작 구성으로 사용되도록 하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) #write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 스위치를 재부팅합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) #reload

The system has unsaved changes.
Would you like to save them now? (y/n) y

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====




[[step-3-validate-installation]]
=== 3단계: 설치 유효성 검사

. 다시 로그인한 다음 스위치에 새 버전의 FASTPATH 소프트웨어가 실행 중인지 확인하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) #show version

Switch: 1

System Description............................. NetApp CN1610, 1.2.0.7,Linux
                                                3.8.13-4ce360e8
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.2.0.7
Operating System............................... Linux 3.8.13-4ce360e8
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893
CPLD version................................... 0x5


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
+
재부팅이 완료되면 로그인하여 이미지 버전을 확인하고 실행 중인 구성을 보고 인터페이스 3/64의 설명(RCF의 버전 레이블)을 찾아야 합니다.

. 활성 스위치인 cs1에서 ISL 포트를 활성화하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config) #interface 0/13-0/16
(cs1) (Interface 0/13-0/16) #no shutdown
(cs1) (Interface 0/13-0/16) #exit
(cs1) (Config) #exit
----
====
. ISL이 정상적으로 작동하는지 확인하십시오.
+
`show port-channel 3/1`

+
링크 상태 필드는  `Up`을(를) 나타내야 합니다.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs1) #show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  False
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 모든 노드에서 클러스터 포트 e0b를 활성화하십시오.
+
`network port modify`

+
각 클러스터 LIF를 소유한 컨트롤러 콘솔에서 명령을 입력해야 합니다.

+
.예를 보여주세요
[%collapsible]
====
다음 예시는 노드1과 노드2에서 포트 e0b가 활성화되는 과정을 보여줍니다.

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin true
cluster1::*> network port modify -node node2 -port e0b -up-admin true
----
====
. 모든 노드에서 포트 e0b가 활성화되어 있는지 확인하십시오.
+
`network port show -ipspace cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster1::*> network port show -ipspace cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. LIF가 이제 두 노드 모두에서 홈 위치에 있는지 확인하십시오((`true`):
+
`network interface show -_role cluster_`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -role cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.66.82/16   node1         e0a     true
            node1_clus2  up/up    169.254.206.128/16 node1         e0b     true
            node2_clus1  up/up    169.254.48.152/16  node2         e0a     true
            node2_clus2  up/up    169.254.42.74/16   node2         e0b     true
4 entries were displayed.
----
====
. 노드 구성원의 상태를 표시합니다.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====
. 관리자 권한 수준으로 돌아가십시오:
+
`set -privilege admin`

. 이전 단계를 반복하여 다른 스위치인 cs1에 FASTPATH 소프트웨어와 RCF를 설치하십시오.

