---
permalink: switch-netapp-cn1610/install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: NetApp 스위치에 FASTPATH ​​소프트웨어를 설치하는 경우 두 번째 스위치인 cs2부터 업그레이드를 시작해야 합니다. 
---
= FASTPATH 소프트웨어 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp 스위치에 FASTPATH ​​소프트웨어를 설치하는 경우 두 번째 스위치인 _cs2_부터 업그레이드를 시작해야 합니다.



== 검토 요구 사항

.시작하기 전에
다음 사항이 있는지 확인하세요.

* 스위치 구성의 현재 백업입니다.
* 완벽하게 작동하는 클러스터(로그에 오류가 없고, 결함이 있는 클러스터 네트워크 인터페이스 카드(NIC)나 이와 유사한 문제가 없음).
* 클러스터 스위치에서 완벽하게 기능하는 포트 연결.
* 모든 클러스터 포트가 설정되었습니다.
* 모든 클러스터 논리 인터페이스(LIF)가 설정되었습니다(마이그레이션되지 않아야 함).
* 성공적인 커뮤니케이션 경로: ONTAP (권한: 고급) `cluster ping-cluster -node node1` 명령은 다음을 표시해야 합니다. `larger than PMTU communication` 모든 경로에서 성공합니다.
* FASTPATH ​​및 ONTAP 의 지원되는 버전입니다.
+
스위치 호환성 표를 꼭 확인하세요. http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 및 CN1610 스위치"^] 지원되는 FASTPATH ​​및 ONTAP 버전에 대한 페이지입니다.





== FASTPATH 설치

다음 절차에서는 클러스터형 Data ONTAP 8.2 구문을 사용합니다.  결과적으로 클러스터 Vserver, LIF 이름 및 CLI 출력은 Data ONTAP 8.3과 다릅니다.

RCF 버전과 FASTPATH 버전의 명령 구문 사이에 명령 종속성이 있을 수 있습니다.

.예시에 관하여
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 두 개의 NetApp 스위치는 cs1과 cs2입니다.
* 두 개의 클러스터 LIF는 clus1과 clus2입니다.
* V서버는 vs1과 vs2입니다.
* 그만큼 `cluster::*>` 프롬프트는 클러스터의 이름을 나타냅니다.
* 각 노드의 클러스터 포트는 e1a와 e2a로 명명됩니다.
+
https://hwu.netapp.com/["Hardware Universe"^]플랫폼에서 지원되는 실제 클러스터 포트에 대한 자세한 정보가 있습니다.

* 지원되는 ISL(Inter-Switch Links)은 포트 0/13부터 0/16까지입니다.
* 지원되는 노드 연결은 포트 0/1~0/12입니다.




=== 1단계: 클러스터 마이그레이션

. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_는 유지 관리 기간(시간)입니다.

+

NOTE: AutoSupport 메시지는 기술 지원팀에 이 유지 관리 작업을 알려 유지 관리 기간 동안 자동 케이스 생성이 억제되도록 합니다.

. 스위치에 관리자로 로그인합니다.  기본적으로 비밀번호는 없습니다.  에서 `(cs2) #` 프롬프트에서 다음을 입력하세요. `enable` 명령.  다시 말해, 기본적으로 비밀번호는 없습니다.  이를 통해 네트워크 인터페이스를 구성할 수 있는 Privileged EXEC 모드에 액세스할 수 있습니다.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
====
. 각 노드의 콘솔에서 clus2를 포트 e1a로 마이그레이션합니다.
+
`network interface migrate`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
====
. 각 노드의 콘솔에서 마이그레이션이 수행되었는지 확인하세요.
+
`network interface show`

+
다음 예에서는 clus2가 두 노드 모두에서 포트 e1a로 마이그레이션되었음을 보여줍니다.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
====




=== 2단계: FASTPATH 소프트웨어 설치

. 두 노드 모두에서 클러스터 포트 e2a를 종료합니다.
+
`network port modify`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 두 노드 모두에서 포트 e2a가 종료되는 것을 보여줍니다.

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 두 노드 모두에서 포트 e2a가 종료되었는지 확인하세요.
+
`network port show`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
====
. 활성 NetApp 스위치인 cs1의 ISL(Inter-Switch Link) 포트를 종료합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
====
. cs2에서 현재 활성화된 이미지를 백업합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
====
. 스위치에 이미지 파일을 다운로드합니다.
+
이미지 파일을 활성 이미지에 복사하면 재부팅 시 해당 이미지가 실행 중인 FASTPATH 버전을 설정합니다.  이전 이미지는 백업용으로 계속 사용할 수 있습니다.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. FASTPATH 소프트웨어의 실행 버전을 확인하세요.
+
`show version`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
====
. 활성 및 백업 구성에 대한 부팅 이미지를 확인합니다.
+
`show bootvar`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
====
. 스위치를 재부팅합니다.
+
`reload`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
====




=== 3단계: 설치 확인

. 다시 로그인하여 FASTPATH 소프트웨어의 새 버전을 확인하세요.
+
`show version`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
====
. 활성 스위치인 cs1에서 ISL 포트를 켭니다.
+
`configure`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====
. ISL이 작동하는지 확인하세요.
+
`show port-channel 3/1`

+
링크 상태 필드는 다음을 표시해야 합니다. `Up` .

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 복사하다 `running-config` 파일을 `startup-config` 소프트웨어 버전과 스위치 설정에 만족하면 파일을 다운로드하세요.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
====
. 각 노드에서 두 번째 클러스터 포트 e2a를 활성화합니다.
+
`network port modify`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
====
. 포트 e2a와 연관된 clus2를 되돌립니다.
+
`network interface revert`

+
ONTAP 소프트웨어 버전에 따라 LIF가 자동으로 되돌아갈 수 있습니다.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. LIF가 이제 홈인지 확인하세요(`true` ) 두 노드 모두에서:
+
`network interface show -_role cluster_`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. 노드의 상태를 확인하세요:
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
====
. 다른 스위치 cs1에 FASTPATH 소프트웨어를 설치하려면 이전 단계를 반복합니다.
. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`


