---
permalink: switch-netapp-cn1610/install-fastpath-software.html 
sidebar: sidebar 
keywords: install, fastpath, software 
summary: 'NetApp CN1610 클러스터 스위치에 FASTPATH 소프트웨어를 설치합니다. 두 번째 스위치(cs2)부터 업그레이드를 시작하십시오.' 
---
= NetApp CN1610 클러스터 스위치에 FASTPATH 소프트웨어를 설치합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp CN1610 클러스터 스위치에 FASTPATH 소프트웨어를 설치합니다. 두 번째 스위치인 _cs2_부터 업그레이드를 시작하십시오.



[[review-requirements]]
== 검토 요구 사항

.시작하기 전에
다음 사항이 있는지 확인하세요.

* 스위치 구성의 현재 백업입니다.
* 완벽하게 작동하는 클러스터(로그에 오류가 없고 클러스터 네트워크 인터페이스 카드(NIC)에 결함이 있거나 유사한 문제가 없음).
* 클러스터 스위치의 포트 연결이 완벽하게 작동합니다.
* 모든 클러스터 포트가 설정되었습니다.
* 모든 클러스터 논리 인터페이스(LIF)가 설정되어 있어야 합니다(마이그레이션되지 않았어야 함).
* 성공적인 통신 경로: ONTAP(권한: 고급) `cluster ping-cluster -node node1` 명령은  `larger than PMTU communication`이(가) 모든 경로에서 성공적임을 나타내야 합니다.
* 지원되는 버전의 FASTPATH 및 ONTAP.
+
지원되는 FASTPATH 및 ONTAP 버전에 대한 정보는  http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 및 CN1610 스위치"^] 페이지의 스위치 호환성 표를 참조하십시오.





[[install-fastpath]]
== FASTPATH 설치

다음 절차는 클러스터형 Data ONTAP 8.2 구문을 사용합니다. 따라서 클러스터 Vserver, LIF 이름 및 CLI 출력은 Data ONTAP 8.3과 다릅니다.

RCF 버전과 FASTPATH 버전의 명령 구문 간에 명령 종속성이 있을 수 있습니다.

.예시에 관하여
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 두 개의 NetApp 스위치는 cs1과 cs2입니다.
* 두 개의 클러스터 LIF는 clus1과 clus2입니다.
* Vserver는 vs1과 vs2입니다.
* The `cluster::*>` 프롬프트에는 클러스터 이름이 표시됩니다.
* 각 노드의 클러스터 포트는 e1a와 e2a로 명명됩니다.
+
link:https://hwu.netapp.com/["Hardware Universe"^]에는 플랫폼에서 지원되는 실제 클러스터 포트에 대한 자세한 정보가 있습니다.

* 지원되는 스위치 간 링크(ISL)는 포트 0/13부터 0/16까지입니다.
* 지원되는 노드 연결 포트는 0/1부터 0/12까지입니다.




[[step-1-migrate-cluster]]
=== 1단계: 클러스터 마이그레이션

. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all - message MAINT=xh`

+
_x_는 유지 관리 기간(시간)입니다.

+

NOTE: AutoSupport 메시지는 기술 지원팀에 이 유지 관리 작업을 알려 유지 관리 기간 동안 자동 케이스 생성이 억제되도록 합니다.

. 관리자 계정으로 스위치에 로그인하십시오. 기본적으로 비밀번호는 없습니다.  `(cs2) #` 프롬프트가 나타나면  `enable` 명령어를 입력하십시오. 마찬가지로 기본적으로 비밀번호는 없습니다. 이 명령어를 입력하면 네트워크 인터페이스를 구성할 수 있는 Privileged EXEC 모드에 접근할 수 있습니다.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # enable
Password (Enter)
(cs2) #
----
====
. 각 노드의 콘솔에서 clus2를 포트 e1a로 마이그레이션하십시오.
+
`network interface migrate`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -destnode node1 -dest-port e1a
cluster::*> network interface migrate -vserver vs2 -lif clus2 -destnode node2 -dest-port e1a
----
====
. 각 노드의 콘솔에서 마이그레이션이 완료되었는지 확인하십시오.
+
`network interface show`

+
다음 예시는 clus2가 두 노드 모두에서 e1a 포트로 마이그레이션되었음을 보여줍니다.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

         Logical    Status     Network        Current  Current  Is
Vserver  Interface  Admin/Open Address/Mask   Node     Port     Home
-------- ---------- ---------- -------------- -------- -------  ----
vs1
         clus1      up/up      10.10.10.1/16  node1    e1a      true
         clus2      up/up      10.10.10.2/16  node1    e1a      false
vs2
         clus1      up/up      10.10.10.1/16  node2    e1a      true
         clus2      up/up      10.10.10.2/16  node2    e1a      false
----
====




[[step-2-install-fastpath-software]]
=== 2단계: FASTPATH 소프트웨어 설치

. 양쪽 노드에서 클러스터 포트 e2a를 종료하십시오.
+
`network port modify`

+
.예를 보여주세요
[%collapsible]
====
다음 예시는 두 노드 모두에서 포트 e2a가 종료되는 것을 보여줍니다.

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 양쪽 노드에서 e2a 포트가 종료되어 있는지 확인하십시오.
+
`network port show`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                 Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU    Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- -----  ----------  ----------  ------------
node1
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000   true/true   full/full   auto/10000
       e2a  cluster  down 9000   true/true   full/full   auto/10000
----
====
. 활성 NetApp 스위치인 cs1의 ISL(Inter-Switch Link) 포트를 종료합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1)(config) # interface 0/13-0/16
(cs1)(Interface 0/13-0/16) # shutdown
(cs1)(Interface 0/13-0/16) # exit
(cs1)(config) # exit
----
====
. CS2에서 현재 활성 이미지를 백업합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions   .

  active:
  backup:

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.1          1.1.0.3           1.1.0.3

(cs2) # copy active backup
Copying active to backup
Copy operation successful

(cs2) #
----
====
. 스위치에 이미지 파일을 다운로드합니다.
+
이미지 파일을 활성 이미지에 복사하면 재부팅 시 해당 이미지가 실행 중인 FASTPATH 버전을 설정합니다. 이전 이미지는 백업으로 계속 사용할 수 있습니다.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.0.0.1/NetApp_CN1610_1.1.0.5.stk active


Mode...................................... TFTP
Set Server IP............................. 10.0.0.1
Path...................................... ./
Filename.................................. NetApp_CN1610_1.1.0.5.stk
Data Type................................. Code
Destination Filename...................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
TFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. FASTPATH 소프트웨어의 실행 중인 버전을 확인하십시오.
+
`show version`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description.................. Broadcom Scorpion 56820
                                     Development System - 16 TENGIG,
                                     1.1.0.3, Linux 2.6.21.7
Machine Type........................ Broadcom Scorpion 56820
                                     Development System - 16TENGIG
Machine Model....................... BCM-56820
Serial Number....................... 10611100004
FRU Number..........................
Part Number......................... BCM56820
Maintenance Level................... A
Manufacturer........................ 0xbc00
Burned In MAC Address............... 00:A0:98:4B:A9:AA
Software Version.................... 1.1.0.3
Operating System.................... Linux 2.6.21.7
Network Processing Device........... BCM56820_B0
Additional Packages................. FASTPATH QOS
                                     FASTPATH IPv6 Management
----
====
. 활성 및 백업 구성에 대한 부팅 이미지를 확인합니다.
+
`show bootvar`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

Image Descriptions

 active :
 backup :

 Images currently available on Flash

----------------------------------------------------------------------
 unit        active       backup     current-active       next-active
----------------------------------------------------------------------

    1        1.1.0.3      1.1.0.3          1.1.0.3           1.1.0.5
----
====
. 스위치를 재부팅합니다.
+
`reload`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # reload

Are you sure you would like to reset the system? (y/n)  y

System will now restart!
----
====




[[step-3-validate-installation]]
=== 3단계: 설치 유효성 검사

. 다시 로그인하여 FASTPATH 소프트웨어의 새 버전을 확인하십시오.
+
`show version`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description................... Broadcom Scorpion 56820
                                      Development System - 16 TENGIG,
                                      1.1.0.5, Linux 2.6.21.7
Machine Type......................... Broadcom Scorpion 56820
                                      Development System - 16TENGIG
Machine Model........................ BCM-56820
Serial Number........................ 10611100004
FRU Number...........................
Part Number.......................... BCM56820
Maintenance Level.................... A
Manufacturer......................... 0xbc00
Burned In MAC Address................ 00:A0:98:4B:A9:AA
Software Version..................... 1.1.0.5
Operating System..................... Linux 2.6.21.7
Network Processing Device............ BCM56820_B0
Additional Packages.................. FASTPATH QOS
                                      FASTPATH IPv6 Management
----
====
. 활성 스위치인 cs1에서 ISL 포트를 활성화하십시오.
+
`configure`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (Interface 0/13-0/16) # no shutdown
(cs1) (Interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====
. ISL이 정상적으로 작동하는지 확인하십시오.
+
`show port-channel 3/1`

+
링크 상태 필드는  `Up`을(를) 나타내야 합니다.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 소프트웨어 버전과 스위치 설정이 만족스러우면  `running-config` 파일을  `startup-config` 파일로 복사하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # write memory

This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully .

Configuration Saved!
----
====
. 각 노드에서 두 번째 클러스터 포트인 e2a를 활성화하십시오.
+
`network port modify`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> **network port modify -node node2 -port e2a -up-admin true**
----
====
. 포트 e2a와 연결된 clus2를 되돌립니다.
+
`network interface revert`

+
ONTAP 소프트웨어 버전에 따라 LIF가 자동으로 원래대로 되돌아갈 수 있습니다.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver Cluster -lif n1_clus2
cluster::*> network interface revert -vserver Cluster -lif n2_clus2
----
====
. LIF가 이제 두 노드 모두에서 홈 위치에 있는지 확인하십시오((`true`):
+
`network interface show -_role cluster_`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

          Logical    Status     Network        Current  Current Is
Vserver   Interface  Admin/Oper Address/Mask   Node     Port    Home
--------  ---------- ---------- -------------- -------- ------- ----
vs1
          clus1      up/up      10.10.10.1/24  node1    e1a     true
          clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
          clus1      up/up      10.10.10.1/24  node2    e1a     true
          clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. 노드의 상태를 확인합니다.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node                 Health  Eligibility
-------------------- ------- ------------
node1                true    true
node2                true    true
----
====
. 다른 스위치인 cs1에도 FASTPATH 소프트웨어를 설치하려면 이전 단계를 반복하십시오.
. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`


