---
permalink: switch-netapp-cn1610/install-rcf-file.html 
sidebar: sidebar 
keywords: reference configuration, file ,install, cn1610, switch, install rcf 
summary: 참조 구성 파일 RCF를 설치할 때는 먼저 클러스터 LIF를 스위치 cs2에서 다른 곳으로 마이그레이션해야 합니다. RCF 설치 및 유효성 검사가 완료되면 LIF를 다시 마이그레이션할 수 있습니다. 
---
= CN1610 스위치에 참조 구성 파일 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
참조 구성 파일(RCF)을 설치하려면 다음 절차를 따르십시오.

RCF를 설치하기 전에 먼저 클러스터 LIF를 스위치 cs2에서 다른 곳으로 마이그레이션해야 합니다. RCF 설치 및 유효성 검사가 완료되면 LIF를 다시 마이그레이션할 수 있습니다.



[[review-requirements]]
== 검토 요구 사항

.시작하기 전에
다음 사항이 있는지 확인하세요.

* 스위치 구성의 현재 백업입니다.
* 완벽하게 작동하는 클러스터(로그에 오류가 없고 클러스터 네트워크 인터페이스 카드(NIC)에 결함이 있거나 유사한 문제가 없음).
* 클러스터 스위치의 포트 연결이 완벽하게 작동합니다.
* 모든 클러스터 포트가 설정되었습니다.
* 모든 클러스터 논리 인터페이스(LIF) 설정이 완료되었습니다.
* 성공적인 통신 경로: ONTAP(권한: 고급) `cluster ping-cluster -node node1` 명령은  `larger than PMTU communication`이(가) 모든 경로에서 성공적임을 나타내야 합니다.
* 지원되는 버전의 RCF 및 ONTAP.
+
지원되는 RCF 및 ONTAP 버전에 대한 스위치 호환성 표는 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 및 CN1610 스위치"^] 페이지에서 확인하십시오.





[[install-the-rcf]]
== RCF 설치

다음 절차는 클러스터형 Data ONTAP 8.2 구문을 사용합니다. 따라서 클러스터 Vserver, LIF 이름 및 CLI 출력은 Data ONTAP 8.3과 다릅니다.

RCF 버전과 FASTPATH 버전의 명령 구문 간에 명령 종속성이 있을 수 있습니다.


NOTE: RCF 버전 1.2에서는 보안상의 이유로 Telnet 지원이 명시적으로 비활성화되었습니다. RCF 1.2 설치 중 연결 문제를 방지하려면 SSH(Secure Shell)가 활성화되어 있는지 확인하십시오. The https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp CN1610 스위치 관리자 가이드"^]에는 SSH에 대한 자세한 내용이 있습니다.

.예시에 관하여
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 두 개의 NetApp 스위치는 cs1과 cs2입니다.
* 두 개의 클러스터 LIF는 clus1과 clus2입니다.
* Vserver는 vs1과 vs2입니다.
* The `cluster::*>` 프롬프트에는 클러스터 이름이 표시됩니다.
* 각 노드의 클러스터 포트는 e1a와 e2a로 명명됩니다.
+
link:https://hwu.netapp.com/["Hardware Universe"^]에는 플랫폼에서 지원되는 실제 클러스터 포트에 대한 자세한 정보가 있습니다.

* 지원되는 스위치 간 링크(ISL)는 포트 0/13부터 0/16까지입니다.
* 지원되는 노드 연결 포트는 0/1부터 0/12까지입니다.
* FASTPATH, RCF 및 ONTAP의 지원되는 버전.
+
지원되는 FASTPATH, RCF 및 ONTAP 버전에 대한 정보는 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 및 CN1610 스위치"^] 페이지의 스위치 호환성 표를 참조하십시오.





[[step-1-migrate-cluster]]
=== 1단계: 클러스터 마이그레이션

. 현재 스위치 구성 정보를 저장합니다.
+
`write memory`

+
.예를 보여주세요
[%collapsible]
====
다음 예는 현재 스위치 구성이 스위치 cs2의 시작 구성((`startup-config`) 파일에 저장되는 것을 보여줍니다.

[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 각 노드의 콘솔에서 clus2를 포트 e1a로 마이그레이션하십시오.
+
`network interface migrate`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network interface migrate -vserver vs1 -lif clus2 -source-node node1 -destnode node1 -dest-port e1a

cluster::*> network interface migrate -vserver vs2 -lif clus2 -source-node node2 -destnode node2 -dest-port e1a
----
====
. 각 노드의 콘솔에서 마이그레이션이 완료되었는지 확인하십시오.
+
`network interface show -role cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예시는 clus2가 두 노드 모두에서 e1a 포트로 마이그레이션되었음을 보여줍니다.

[listing]
----
cluster::*> network port show -role cluster
         clus1      up/up      10.10.10.1/16   node2    e1a     true
         clus2      up/up      10.10.10.2/16   node2    e1a     false
----
====
. 양쪽 노드에서 e2a 포트를 종료하십시오.
+
`network port modify`

+
.예를 보여주세요
[%collapsible]
====
다음 예시는 두 노드 모두에서 포트 e2a가 종료되는 것을 보여줍니다.

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 양쪽 노드에서 e2a 포트가 종료되어 있는지 확인하십시오.
+
`network port show`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                  Auto-Negot  Duplex      Speed (Mbps)
Node   Port   Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ------ -------- ---- ----- ----------- ----------  -----------
node1
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
node2
       e1a    cluster  up   9000  true/true   full/full   auto/10000
       e2a    cluster  down 9000  true/true   full/full   auto/10000
----
====
. 활성 NetApp 스위치인 cs1의 ISL 포트를 종료하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config) # interface 0/13-0/16
(cs1) (interface 0/13-0/16) # shutdown
(cs1) (interface 0/13-0/16) # exit
(cs1) (config) # exit
----
====




[[step-2-install-rcf]]
=== 2단계: RCF 설치

. RCF를 스위치에 복사합니다.
+

NOTE: 스크립트를 실행하기 전에 파일 이름의 일부로  `.scr` 확장자를 설정해야 합니다. 이 확장자는 FASTPATH 운영 체제의 확장자입니다.

+
스위치는 스크립트가 스위치로 다운로드되는 동안 자동으로 유효성을 검사하며, 그 결과는 콘솔에 출력됩니다.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # copy tftp://10.10.0.1/CN1610_CS_RCF_v1.1.txt nvram:script CN1610_CS_RCF_v1.1.scr

[the script is now displayed line by line]
Configuration script validated.
File transfer operation completed successfully.
----
====
. 스크립트가 다운로드되어 지정한 파일 이름으로 저장되었는지 확인하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # script list
Configuration Script Name        Size(Bytes)
-------------------------------- -----------
running-config.scr               6960
CN1610_CS_RCF_v1.1.scr           2199

2 configuration script(s) found.
6038 Kbytes free.
----
====
. 스크립트의 유효성을 검사합니다.
+

NOTE: 다운로드 중에 스크립트의 유효성을 검사하여 각 줄이 유효한 스위치 명령줄인지 확인합니다.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # script validate CN1610_CS_RCF_v1.1.scr
[the script is now displayed line by line]
Configuration script 'CN1610_CS_RCF_v1.1.scr' validated.
----
====
. 스크립트를 스위치에 적용합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.1.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.1.scr' applied.
----
====
. 스위치에 변경 사항이 적용되었는지 확인하십시오.
+
[listing]
----
(cs2) # show running-config
----
+
이 예시에서는 스위치에  `running-config` 파일이 표시됩니다. 설정한 매개변수가 예상대로인지 확인하려면 해당 파일을 RCF 파일과 비교해야 합니다.

. 변경 사항을 저장합니다.
.  `running-config` 파일을 표준 파일로 설정합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.
----
====
. 스위치를 재부팅하고  `running-config` 파일이 올바른지 확인하십시오.
+
재부팅이 완료되면 로그인하여  `running-config` 파일을 보고 인터페이스 3/64의 설명을 찾아야 합니다. 이 설명은 RCF의 버전 레이블입니다.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # reload

The system has unsaved changes.
Would you like to save them now? (y/n) y


Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====
. 활성 스위치인 cs1에서 ISL 포트를 활성화하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs1) # configure
(cs1) (config)# interface 0/13-0/16
(cs1) (Interface 0/13-0/16)# no shutdown
(cs1) (Interface 0/13-0/16)# exit
(cs1) (config)# exit
----
====
. ISL이 정상적으로 작동하는지 확인하십시오.
+
`show port-channel 3/1`

+
링크 상태 필드는  `Up`을(를) 나타내야 합니다.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----

(cs2) # show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 양쪽 노드에서 클러스터 포트 e2a를 활성화하십시오.
+
`network port modify`

+
.예를 보여주세요
[%collapsible]
====
다음 예시는 노드1과 노드2에서 포트 e2a가 활성화되는 과정을 보여줍니다.

[listing]
----
cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====




[[step-3-validate-installation]]
=== 3단계: 설치 유효성 검사

. 두 노드 모두에서 e2a 포트가 활성화되어 있는지 확인하십시오.
+
`network port show -_role cluster_`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network port show -role cluster

                                Auto-Negot  Duplex      Speed (Mbps)
Node   Port Role     Link MTU   Admin/Oper  Admin/Oper  Admin/Oper
------ ---- -------- ---- ----  ----------- ----------  ------------
node1
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
node2
       e1a  cluster  up   9000  true/true   full/full   auto/10000
       e2a  cluster  up   9000  true/true   full/full   auto/10000
----
====
. 두 노드 모두에서 포트 e2a와 연결된 clus2를 되돌리십시오.
+
`network interface revert`

+
LIF는 사용 중인 ONTAP 버전에 따라 자동으로 되돌아갈 수 있습니다.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
. LIF가 이제 두 노드 모두에서 홈 위치에 있는지 확인하십시오((`true`):
+
`network interface show -_role cluster_`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network interface show -role cluster

        Logical    Status     Network        Current  Current Is
Vserver Interface  Admin/Oper Address/Mask   Node     Port    Home
------- ---------- ---------- -------------- -------- ------- ----
vs1
        clus1      up/up      10.10.10.1/24  node1    e1a     true
        clus2      up/up      10.10.10.2/24  node1    e2a     true
vs2
        clus1      up/up      10.10.10.1/24  node2    e1a     true
        clus2      up/up      10.10.10.2/24  node2    e2a     true
----
====
. 노드 구성원의 상태를 확인합니다.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::> cluster show

Node           Health  Eligibility
-------------- ------- ------------
node1
               true    true
node2
               true    true
----
====
. 소프트웨어 버전과 스위치 설정이 만족스러우면  `running-config` 파일을  `startup-config` 파일로 복사하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----
(cs2) # write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 이전 단계를 반복하여 다른 스위치인 cs1에 RCF를 설치하십시오.


.다음은 무엇인가요?
link:../switch-cshm/config-overview.html["스위치 상태 모니터링 구성"]
