---
permalink: switch-netapp-cn1610/install-fastpath-rcf-831.html 
sidebar: sidebar 
keywords: fastpath, software, install, netapp cluster switches, rcfs, ontap 
summary: 설치 단계는 NetApp CN1601 관리 스위치와 ONTAP 8.3.1 이상을 실행하는 CN1610 클러스터 스위치에 대해 동일합니다. 그러나 두 모델은 서로 다른 소프트웨어와 RCFs를 필요로 합니다. 
---
= ONTAP 8.3.1 이상 버전의 FASTPATH 소프트웨어와 RCF를 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 절차에 따라 ONTAP 8.3.1 이상에 FASTPATH 소프트웨어와 RCFs를 설치합니다.

설치 단계는 NetApp CN1601 관리 스위치와 ONTAP 8.3.1 이상을 실행하는 CN1610 클러스터 스위치에 대해 동일합니다. 그러나 두 모델은 서로 다른 소프트웨어와 RCFs를 필요로 합니다.



== 요구사항 검토

.필요한 것
* 스위치 구성의 현재 백업
* 완전히 작동하는 클러스터(로그에 오류 없음, 결함이 있는 클러스터 네트워크 인터페이스 카드(NIC) 또는 이와 유사한 문제 없음)
* 클러스터 스위치의 포트 연결이 완벽하게 작동합니다.
* 모든 클러스터 포트가 설정되었습니다.
* 모든 클러스터 논리 인터페이스(LIF) 설정(마이그레이션되지 않음)
* 성공적인 통신 경로: ONTAP(권한: 고급) `cluster ping-cluster -node node1` 명령에 이 사실을 표시해야 합니다 `larger than PMTU communication` 모든 경로에서 성공합니다.
* 지원되는 FASTPATH, RCF 및 ONTAP 버전
+
의 스위치 호환성 표를 참조하십시오 http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 및 CN1610 스위치"^] 지원되는 FASTPATH, RCF 및 ONTAP 버전에 대한 페이지입니다.





== FASTPATH 소프트웨어를 설치합니다

다음 절차에서는 clustered Data ONTAP 8.2 구문을 사용합니다. 따라서 클러스터 Vserver, LIF 이름 및 CLI 출력이 Data ONTAP 8.3의 결과와 다릅니다.

RCF 및 FASTPATH 버전의 명령 구문 간에는 명령 의존성이 있을 수 있습니다.


NOTE: RCF 버전 1.2에서는 보안 문제로 인해 텔넷에 대한 지원이 명시적으로 비활성화되었습니다. RCF 1.2를 설치하는 동안 연결 문제를 방지하려면 SSH(Secure Shell)가 활성화되어 있는지 확인하십시오. 를 클릭합니다 https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp CN1610 스위치 관리자 가이드"^] 에 SSH에 대한 자세한 정보가 나와 있습니다.

.예를 참조하십시오
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 두 NetApp 스위치 이름은 CS1과 CS2입니다.
* 클러스터 논리 인터페이스(LIF) 이름은 노드 1의 node1_clus1 및 node1_clus2이고, 노드 2의 node2_clus1 및 node2_clus2입니다. (클러스터에 최대 24개의 노드를 포함할 수 있음)
* SVM(스토리지 가상 시스템) 이름은 Cluster입니다.
* 'cluster1:: *>' 프롬프트는 클러스터의 이름을 나타냅니다.
* 각 노드의 클러스터 포트 이름은 e0a 및 e0b입니다.
+
https://hwu.netapp.com/["Hardware Universe"^] 에서 플랫폼에서 지원되는 실제 클러스터 포트에 대한 자세한 정보를 얻을 수 있습니다.

* 지원되는 ISL(Inter-Switch Link)은 포트 0/13 ~ 0/16입니다.
* 지원되는 노드 연결은 포트 0/1 ~ 0/12입니다.




=== 1단계: 클러스터 마이그레이션

. 클러스터의 네트워크 포트에 대한 정보를 표시합니다.
+
'network port show -_IPSpace cluster _'

+
.예제 보기
[%collapsible]
====
다음 예제는 명령의 출력 유형을 보여 줍니다.

[listing]
----
cluster1::> network port show -ipspace cluster
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. 클러스터의 LIF 정보 표시:
+
'network interface show -_role cluster _'

+
.예제 보기
[%collapsible]
====
다음 예는 클러스터의 논리 인터페이스를 보여줍니다. 이 예제에서 '-role' 매개 변수는 클러스터 포트와 연결된 LIF에 대한 정보를 표시합니다.

[listing]
----
cluster1::> network interface show -role cluster
  (network interface show)
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16    node1         e0a     true
            node1_clus2  up/up    10.254.206.128/16  node1         e0b     true
            node2_clus1  up/up    10.254.48.152/16   node2         e0a     true
            node2_clus2  up/up    10.254.42.74/16    node2         e0b     true
4 entries were displayed.
----
====
. 각 노드에서 노드 관리 LIF를 사용하여 노드 1의 node1_clus2를 노드 1의 e0a로, 노드 2의 node2_clus2를 e0a로 마이그레이션합니다.
+
네트워크 인터페이스 마이그레이션

+
각 클러스터 LIF를 소유하는 컨트롤러 콘솔에 명령을 입력해야 합니다.

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster1::> network interface migrate -vserver Cluster -lif node1_clus2 -destination-node node1 -destination-port e0a
cluster1::> network interface migrate -vserver Cluster -lif node2_clus2 -destination-node node2 -destination-port e0a
----
====
+

NOTE: 이 명령에서 클러스터의 이름은 대소문자를 구분하며 각 노드에서 명령을 실행해야 합니다. 일반 클러스터 LIF에서 이 명령을 실행할 수 없습니다.

. 노드에서 network interface show 명령을 사용하여 마이그레이션이 실행되었는지 확인합니다.
+
.예제 보기
[%collapsible]
====
다음 예제에서는 clus2가 노드 1과 노드 2의 포트 e0a로 마이그레이션되었음을 보여 줍니다.

[listing]
----
cluster1::> **network interface show -role cluster**
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    10.254.66.82/16   node1          e0a     true
            node1_clus2  up/up    10.254.206.128/16 node1          e0a     false
            node2_clus1  up/up    10.254.48.152/16  node2          e0a     true
            node2_clus2  up/up    10.254.42.74/16   node2          e0a     false
4 entries were displayed.
----
====
. 계속할 것인지 묻는 메시지가 표시되면 권한 수준을 고급으로 변경하고 y를 입력합니다.
+
세트 프리빌리지 고급

+
고급 프롬프트(*>)가 나타납니다.

. 두 노드에서 클러스터 포트 e0b 종료:
+
'network port modify -node_node_name_-port_port_name_-up-admin false'

+
각 클러스터 LIF를 소유하는 컨트롤러 콘솔에 명령을 입력해야 합니다.

+
.예제 보기
[%collapsible]
====
다음 예는 모든 노드에서 포트 e0b를 종료하는 명령을 보여줍니다.

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin false
cluster1::*> network port modify -node node2 -port e0b -up-admin false
----
====
. 두 노드에서 포트 e0b가 종료되었는지 확인:
+
네트워크 포트 쇼

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster1::*> network port show -role cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          down     9000  auto/10000
4 entries were displayed.
----
====
. CS1의 ISL(Inter-Switch Link) 포트를 종료합니다.
+
.예제 보기
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config)#interface 0/13-0/16
(cs1) (Interface 0/13-0/16)#shutdown
(cs1) (Interface 0/13-0/16)#exit
(cs1) (Config)#exit
----
====
. CS2에서 현재 활성 이미지를 백업합니다.
+
.예제 보기
[%collapsible]
====
[listing]
----
(cs2) # show bootvar

 Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.5     1.1.0.3            1.1.0.5            1.1.0.5

(cs2) # copy active backup
Copying active to backup
Copy operation successful
----
====




=== 2단계: FASTPATH 소프트웨어와 RCF를 설치합니다

. FASTPATH 소프트웨어의 실행 버전을 확인합니다.
+
.예제 보기
[%collapsible]
====
[listing]
----
(cs2) # show version

Switch: 1

System Description............................. NetApp CN1610, 1.1.0.5, Linux
                                                2.6.21.7
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.1.0.5
Operating System............................... Linux 2.6.21.7
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893

--More-- or (q)uit


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
. 이미지 파일을 스위치에 다운로드합니다.
+
이미지 파일을 활성 이미지로 복사하면 재부팅할 때 해당 이미지가 실행 중인 FASTPATH 버전을 설정하게 됩니다. 이전 이미지는 백업으로 사용할 수 있습니다.

+
.예제 보기
[%collapsible]
====
[listing]
----
(cs2) #copy sftp://root@10.22.201.50//tftpboot/NetApp_CN1610_1.2.0.7.stk active
Remote Password:********

Mode........................................... SFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /tftpboot/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type...................................... Code
Destination Filename........................... active

Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y
SFTP Code transfer starting...


File transfer operation completed successfully.
----
====
. 현재 및 다음 활성 부팅 이미지 버전을 확인합니다.
+
'How bootvar'입니다

+
.예제 보기
[%collapsible]
====
[listing]
----
(cs2) #show bootvar

Image Descriptions

 active :
 backup :


 Images currently available on Flash

--------------------------------------------------------------------
 unit      active      backup     current-active        next-active
--------------------------------------------------------------------

    1     1.1.0.8     1.1.0.8            1.1.0.8            1.2.0.7
----
====
. 스위치에 새 이미지 버전용 호환 RCF를 설치합니다.
+
RCF 버전이 이미 올바른 경우 ISL 포트를 불러옵니다.

+
.예제 보기
[%collapsible]
====
[listing]
----
(cs2) #copy tftp://10.22.201.50//CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr

Mode........................................... TFTP
Set Server IP.................................. 10.22.201.50
Path........................................... /
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr

File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.


Management access will be blocked for the duration of the transfer
Are you sure you want to start? (y/n) y


Validating configuration script...
[the script is now displayed line by line]

Configuration script validated.
File transfer operation completed successfully.
----
====
+

NOTE: 스크립트를 호출하기 전에 '.scr' 확장자를 파일 이름의 일부로 설정해야 합니다. 이 확장명은 FASTPATH 운영 체제용으로 제공됩니다.

+
스위치는 스크립트가 스위치에 다운로드될 때 자동으로 스크립트의 유효성을 검사합니다. 출력은 콘솔로 전달됩니다.

. 스크립트가 다운로드되어 지정한 파일 이름에 저장되었는지 확인합니다.
+
.예제 보기
[%collapsible]
====
[listing]
----
(cs2) #script list

Configuration Script Name        Size(Bytes)
-------------------------------- -----------
CN1610_CS_RCF_v1.2.scr                  2191

1 configuration script(s) found.
2541 Kbytes free.
----
====
. 스위치에 스크립트를 적용합니다.
+
.예제 보기
[%collapsible]
====
[listing]
----
(cs2) #script apply CN1610_CS_RCF_v1.2.scr

Are you sure you want to apply the configuration script? (y/n) y
[the script is now displayed line by line]...

Configuration script 'CN1610_CS_RCF_v1.2.scr' applied.
----
====
. 변경 사항이 스위치에 적용되었는지 확인한 후 저장합니다.
+
'show running-config'를 선택합니다

+
.예제 보기
[%collapsible]
====
[listing]
----
(cs2) #show running-config
----
====
. 실행 중인 구성을 저장하면 스위치를 재부팅할 때 시작 구성이 됩니다.
+
.예제 보기
[%collapsible]
====
[listing]
----
(cs2) #write memory
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) y

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
. 스위치를 재부팅합니다.
+
.예제 보기
[%collapsible]
====
[listing]
----
(cs2) #reload

The system has unsaved changes.
Would you like to save them now? (y/n) y

Config file 'startup-config' created successfully.
Configuration Saved!
System will now restart!
----
====




=== 3단계: 설치 확인

. 다시 로그인한 다음 스위치가 FASTPATH 소프트웨어의 새 버전을 실행하고 있는지 확인합니다.
+
.예제 보기
[%collapsible]
====
[listing]
----
(cs2) #show version

Switch: 1

System Description............................. NetApp CN1610, 1.2.0.7,Linux
                                                3.8.13-4ce360e8
Machine Type................................... NetApp CN1610
Machine Model.................................. CN1610
Serial Number.................................. 20211200106
Burned In MAC Address.......................... 00:A0:98:21:83:69
Software Version............................... 1.2.0.7
Operating System............................... Linux 3.8.13-4ce360e8
Network Processing Device...................... BCM56820_B0
Part Number.................................... 111-00893
CPLD version................................... 0x5


Additional Packages............................ FASTPATH QOS
                                                FASTPATH IPv6 Management
----
====
+
재부팅이 완료되면 로그인하여 이미지 버전을 확인하고, 실행 중인 구성을 확인하고, RCF의 버전 레이블인 인터페이스 3/64에서 설명을 찾아야 합니다.

. 활성 스위치인 CS1에서 ISL 포트를 불러옵니다.
+
.예제 보기
[%collapsible]
====
[listing]
----
(cs1) #configure
(cs1) (Config) #interface 0/13-0/16
(cs1) (Interface 0/13-0/16) #no shutdown
(cs1) (Interface 0/13-0/16) #exit
(cs1) (Config) #exit
----
====
. ISL이 작동 중인지 확인:
+
'How port-channel 3/1

+
링크 상태 필드는 '위로'를 표시해야 합니다.

+
.예제 보기
[%collapsible]
====
[listing]
----
(cs1) #show port-channel 3/1

Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  False
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 모든 노드에서 클러스터 포트 e0b 가져오기:
+
네트워크 포트 수정

+
각 클러스터 LIF를 소유하는 컨트롤러 콘솔에 명령을 입력해야 합니다.

+
.예제 보기
[%collapsible]
====
다음 예제에서는 node1 및 node2에서 포트 e0b가 표시되는 것을 보여 줍니다.

[listing]
----
cluster1::*> network port modify -node node1 -port e0b -up-admin true
cluster1::*> network port modify -node node2 -port e0b -up-admin true
----
====
. 포트 e0b가 모든 노드에서 작동하는지 확인:
+
네트워크 포트 show-IPSpace cluster

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster1::*> network port show -ipspace cluster

                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
node2
       e0a       Cluster      Cluster          up       9000  auto/10000
       e0b       Cluster      Cluster          up       9000  auto/10000
4 entries were displayed.
----
====
. LIF가 두 노드에서 홈('true')인지 확인합니다.
+
'network interface show -_role cluster _'

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster1::*> network interface show -role cluster

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.66.82/16   node1         e0a     true
            node1_clus2  up/up    169.254.206.128/16 node1         e0b     true
            node2_clus1  up/up    169.254.48.152/16  node2         e0a     true
            node2_clus2  up/up    169.254.42.74/16   node2         e0b     true
4 entries were displayed.
----
====
. 노드 구성원의 상태를 표시합니다.
+
'클러스터 쇼'

+
.예제 보기
[%collapsible]
====
[listing]
----
cluster1::*> cluster show

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
----
====
. 관리자 권한 레벨로 돌아갑니다.
+
'Set-Privilege admin'입니다

. 이전 단계를 반복하여 FASTPATH 소프트웨어와 RCF를 다른 스위치 CS1에 설치합니다.

