---
permalink: switch-netapp-cn1610/migrate-fas22xx-systems.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, fas22xx systems, single, network connection 
summary: 각 컨트롤러 모듈에 클러스터 연결을 위한 단일 백투백 10GbE 연결이 있는 기존의 2노드 스위치리스 클러스터에 FAS22xx 시스템이 있는 경우, 스위치리스 클러스터 네트워킹 옵션을 사용하여 직접 백투백 연결을 스위치 연결로 교체할 수 있습니다. 
---
= 단일 클러스터 네트워크 연결을 사용하여 FAS22xx 시스템에서 2노드 스위치 클러스터로 마이그레이션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 컨트롤러 모듈에 클러스터 연결을 위한 단일 백투백 10GbE 연결이 있는 기존의 2노드 스위치리스 클러스터에 FAS22xx 시스템이 있는 경우, 스위치리스 클러스터 네트워킹 옵션을 사용하여 직접 백투백 연결을 스위치 연결로 교체할 수 있습니다.



== 검토 요구 사항

.시작하기 전에
다음 사항이 있는지 확인하세요.

* 스위치리스 구성에서 스위치 구성으로 마이그레이션하기 위한 두 개의 클러스터 연결입니다.
* 클러스터는 정상적이며 백투백 연결로 연결된 두 개의 노드로 구성되어 있습니다.
* 노드는 ONTAP 8.2 이상을 실행합니다.
* 스위치리스 클러스터 기능은 두 개 이상의 노드에서 사용할 수 없습니다.
* 모든 클러스터 포트는 `up` 상태.


.관련 정보
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetApp KB 문서 1010449: 예약된 유지 관리 기간 동안 자동 케이스 생성을 억제하는 방법"^]



== 스위치 마이그레이션

이 절차는 스위치 없는 환경에서 직접 클러스터 연결을 제거하고 스위치에 대한 각 연결을 파트너 노드에 대한 연결로 대체하는 비중단 절차입니다.



=== 1단계: 마이그레이션 준비

. 권한 수준을 고급으로 변경하려면 다음을 입력하세요. `y` 계속하라는 메시지가 표시되면:
+
`set -privilege advanced`

+
고급 프롬프트(`*>` )이 나타납니다.

. 두 노드의 시스템 콘솔에서 노드의 클러스터 상태를 확인하세요.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 클러스터 내 노드의 상태와 적격성에 대한 정보를 표시합니다.

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. 두 노드의 시스템 콘솔에서 HA 쌍의 상태를 확인하세요. `storage failover show`
+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 node1과 node2의 상태를 보여줍니다.

[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
====
. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
`x`유지 관리 기간의 시간 단위입니다.

+

NOTE: 이 메시지는 기술 지원팀에 이 유지 관리 작업을 알리는 것으로, 유지 관리 기간 동안 자동 케이스 생성이 억제됩니다.

+
.예를 보여주세요
[%collapsible]
====
다음 명령은 2시간 동안 자동 케이스 생성을 억제합니다.

[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
====
. 스위치리스 클러스터의 현재 상태가 다음과 같은지 확인하십시오. `true` 그런 다음 스위치리스 클러스터 모드를 비활성화합니다.
+
`network options switchless-cluster modify -enabled false`

. 대상 노드를 인수합니다.
+
`storage failover takeover -ofnode _target_node_name_`

+
어느 노드가 대상 노드인지는 중요하지 않습니다.  인수되면 대상 노드는 자동으로 재부팅되고 표시됩니다. `Waiting for giveback...` 메시지.

+
활성 노드는 이제 인수된 파트너(대상) 노드에 데이터를 제공합니다.

. 손상된 노드를 인수한 후 2분 정도 기다려 인수가 성공적으로 완료되었는지 확인하세요.
. 대상 노드가 표시됨 `Waiting for giveback...` 메시지가 나타나면 종료하세요.
+
노드를 종료하는 데 사용하는 방법은 노드 서비스 프로세서(SP)를 통한 원격 관리를 사용하는지 여부에 따라 달라집니다.

+
|===
| SP 라면 | 그 다음에... 


 a| 
구성됨
 a| 
손상된 노드 SP 에 로그인한 다음 시스템의 전원을 끕니다. `system power off`



 a| 
구성되지 않았습니다
 a| 
손상된 노드 프롬프트에서 다음을 누릅니다. `Ctrl-C` , 그리고 응답합니다 `y` 노드를 중지합니다.

|===




=== 2단계: 케이블 및 포트 구성

. 각 컨트롤러 모듈에서 10GbE 클러스터 포트를 스위치리스 클러스터에 연결하는 케이블을 분리합니다.
. 10GbE 클러스터 포트를 두 컨트롤러 모듈의 스위치에 연결합니다.
. 스위치에 연결된 10GbE 클러스터 포트가 동일한 VLAN의 일부로 구성되었는지 확인합니다.
+
각 컨트롤러 모듈의 클러스터 포트를 서로 다른 스위치에 연결하려는 경우, 각 스위치에서 클러스터 포트가 연결된 포트가 동일한 VLAN으로 구성되었는지, 그리고 두 스위치 모두에서 트렁킹이 올바르게 구성되었는지 확인해야 합니다.

. 대상 노드에 저장 공간을 돌려줍니다.
+
`storage failover giveback -ofnode node2`

. 환수 작업의 진행 상황을 모니터링하세요.
+
`storage failover show-giveback`

. 반환 작업이 완료된 후 HA 쌍이 정상이고 인수가 가능한지 확인합니다.
+
`storage failover show`

+
.예를 보여주세요
[%collapsible]
====
출력은 다음과 유사해야 합니다.

[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
====
. 클러스터 포트 LIF가 올바르게 작동하는지 확인하세요.
+
`network interface show -role cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 LIF가 다음과 같은 것을 보여줍니다. `up` 노드1과 노드2에서 "Is Home" 열 결과가 다음과 같습니다. `true` :

[listing]
----

cluster::*> network interface show -role cluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
node1
            clus1        up/up    192.168.177.121/24  node1        e1a     true
node2
            clus1        up/up    192.168.177.123/24  node2        e1a     true

2 entries were displayed.
----
====
. 두 노드의 시스템 콘솔에서 노드의 클러스터 상태를 확인하세요.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 클러스터 내 노드의 상태와 적격성에 대한 정보를 표시합니다.

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. 원격 클러스터 인터페이스의 연결성을 확인하세요.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
당신은 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령:

`network interface check cluster-connectivity start`그리고 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*참고:* 실행하기 전에 몇 초 동안 기다리십시오. `show` 세부 정보를 표시하는 명령입니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스의 경우 다음을 사용할 수도 있습니다. `cluster ping-cluster -node <name>` 연결성을 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====


=== 3단계: 절차 완료

. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
. 권한 수준을 다시 관리자로 변경합니다.
+
`set -privilege admin`


