---
permalink: switch-netapp-cn1610/migrate-switched-netapp-cn1610.html 
sidebar: sidebar 
keywords: migrate, switchless cluster environment, switched netapp cn1610 
summary: 기존에 2노드 스위치리스 클러스터 환경이 있는 경우 CN1610 클러스터 네트워크 스위치를 사용하여 2노드 스위치 클러스터 환경으로 마이그레이션할 수 있으며, 이를 통해 2노드 이상으로 확장할 수 있습니다. 
---
= 스위치리스 클러스터 환경에서 스위치형 NetApp CN1610 클러스터 환경으로 마이그레이션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존에 2노드 스위치리스 클러스터 환경이 있는 경우 CN1610 클러스터 네트워크 스위치를 사용하여 2노드 스위치 클러스터 환경으로 마이그레이션할 수 있으며, 이를 통해 2노드 이상으로 확장할 수 있습니다.



== 검토 요구 사항

.시작하기 전에
다음 사항이 있는지 확인하세요.

2노드 스위치리스 구성의 경우 다음 사항을 확인하세요.

* 2노드 스위치리스 구성이 올바르게 설정되고 작동하고 있습니다.
* 노드는 ONTAP 8.2 이상을 실행합니다.
* 모든 클러스터 포트는 `up` 상태.
* 모든 클러스터 논리 인터페이스(LIF)는 `up` 주와 모항에서.


CN1610 클러스터 스위치 구성의 경우:

* CN1610 클러스터 스위치 인프라는 두 스위치 모두에서 완벽하게 작동합니다.
* 두 스위치 모두 관리 네트워크 연결 기능을 갖추고 있습니다.
* 클러스터 스위치에 콘솔로 접근할 수 있습니다.
* CN1610 노드 간 스위치와 스위치 간 연결은 Twinax 또는 파이버 케이블을 사용합니다.
+
그만큼link:https://hwu.netapp.com/["Hardware Universe"^] 케이블링에 대한 자세한 정보가 포함되어 있습니다.

* ISL(Inter-Switch Link) 케이블은 두 CN1610 스위치의 포트 13~16에 연결됩니다.
* 두 CN1610 스위치의 초기 사용자 정의가 완료되었습니다.
+
SMTP, SNMP, SSH 등 이전 사이트 사용자 정의 내용은 새 스위치에 복사해야 합니다.



.관련 정보
* link:http://hwu.netapp.com["Hardware Universe"^]
* link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/docs-tab["NetApp CN1601 및 CN1610"]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMP1118645["CN1601 및 CN1610 스위치 설정 및 구성"^]
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetApp KB 문서 1010449: 예약된 유지 관리 기간 동안 자동 케이스 생성을 억제하는 방법"^]




== 스위치 마이그레이션

.예시에 관하여
이 절차의 예에서는 다음 클러스터 스위치와 노드 명명법을 사용합니다.

* CN1610 스위치의 이름은 cs1과 cs2입니다.
* LIF의 이름은 clus1과 clus2입니다.
* 노드의 이름은 node1과 node2입니다.
* 그만큼 `cluster::*>` 프롬프트는 클러스터의 이름을 나타냅니다.
* 이 절차에서 사용되는 클러스터 포트는 e1a와 e2a입니다.
+
그만큼link:https://hwu.netapp.com/["Hardware Universe"^] 플랫폼의 실제 클러스터 포트에 대한 최신 정보가 포함되어 있습니다.





=== 1단계: 마이그레이션 준비

. 권한 수준을 고급으로 변경하려면 다음을 입력하세요. `y` 계속하라는 메시지가 표시되면:
+
`set -privilege advanced`

+
고급 프롬프트(*>)가 나타납니다.

. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
_x_는 유지 관리 기간(시간)입니다.

+

NOTE: AutoSupport 메시지는 기술 지원팀에 이 유지 관리 작업을 알려 유지 관리 기간 동안 자동 케이스 생성이 억제되도록 합니다.

+
.예를 보여주세요
[%collapsible]
====
다음 명령은 2시간 동안 자동 케이스 생성을 억제합니다.

[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
====




=== 2단계: 포트 구성

. 새로운 클러스터 스위치 cs1과 cs2에서 노드에 연결된 모든 포트(ISL 포트 제외)를 비활성화합니다.
+
ISL 포트를 비활성화하면 안 됩니다.

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 스위치 cs1에서 노드에 연결된 포트 1~12가 비활성화되어 있음을 보여줍니다.

[listing]
----

(cs1)> enable
(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
다음 예에서는 스위치 cs2에서 노드에 연결된 포트 1~12가 비활성화되어 있음을 보여줍니다.

[listing]
----

(c2)> enable
(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
====
. 두 CN1610 클러스터 스위치 cs1과 cs2 사이의 ISL과 ISL의 물리적 포트가 동일한지 확인하십시오. `up` :
+
`show port-channel`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 ISL 포트가 다음과 같은 것을 보여줍니다. `up` 스위치 cs1에서:

[listing]
----

(cs1)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
다음 예에서는 ISL 포트가 다음과 같은 것을 보여줍니다. `up` 스위치 cs2에서:

[listing]
----

(cs2)# show port-channel 3/1
Local Interface................................ 3/1
Channel Name................................... ISL-LAG
Link State..................................... Up
Admin Mode..................................... Enabled
Type........................................... Static
Load Balance Option............................ 7
(Enhanced hashing mode)

Mbr    Device/       Port      Port
Ports  Timeout       Speed     Active
------ ------------- --------- -------
0/13   actor/long    10G Full  True
       partner/long
0/14   actor/long    10G Full  True
       partner/long
0/15   actor/long    10G Full  True
       partner/long
0/16   actor/long    10G Full  True
       partner/long
----
====
. 이웃 장치 목록을 표시합니다.
+
`show isdp neighbors`

+
이 명령은 시스템에 연결된 장치에 대한 정보를 제공합니다.

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 스위치 cs1의 인접 장치를 나열합니다.

[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16
----
다음 예에서는 스위치 cs2의 인접 장치를 나열합니다.

[listing]
----

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
====
. 클러스터 포트 목록을 표시합니다.
+
`network port show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 사용 가능한 클러스터 포트를 보여줍니다.

[listing]
----

cluster::*> network port show -ipspace Cluster
Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0c       Cluster      Cluster          up   9000  auto/10000 healthy  false
e0d       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e4b       Cluster      Cluster          up   9000  auto/10000 healthy  false
12 entries were displayed.
----
====
. 각 클러스터 포트가 해당 파트너 클러스터 노드의 해당 포트에 연결되어 있는지 확인하세요.
+
`run * cdpd show-neighbors`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 클러스터 포트 e1a와 e2a가 클러스터 파트너 노드의 동일한 포트에 연결되어 있음을 보여줍니다.

[listing]
----

cluster::*> run * cdpd show-neighbors
2 entries were acted on.

Node: node1
Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node2           e1a                    FAS3270           137   H
e2a    node2           e2a                    FAS3270           137   H


Node: node2

Local  Remote          Remote                 Remote           Hold  Remote
Port   Device          Interface              Platform         Time  Capability
------ --------------- ---------------------- ---------------- ----- ----------
e1a    node1           e1a                    FAS3270           161   H
e2a    node1           e2a                    FAS3270           161   H
----
====
. 모든 클러스터 LIF가 있는지 확인하십시오. `up` 그리고 운영:
+
`network interface show -vserver Cluster`

+
각 클러스터 LIF는 다음을 표시해야 합니다. `true` ``집`` 열에.

+
.예를 보여주세요
[%collapsible]
====
[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up      10.10.10.1/16 node1         e1a     true
            clus2      up/up      10.10.10.2/16 node1         e2a     true
node2
            clus1      up/up      10.10.11.1/16 node2         e1a     true
            clus2      up/up      10.10.11.2/16 node2         e2a     true

4 entries were displayed.
----
====
+

NOTE: 10단계부터 13단계까지의 다음 수정 및 마이그레이션 명령은 로컬 노드에서 수행해야 합니다.

. 모든 클러스터 포트가 있는지 확인하십시오. `up` :
+
`network port show -ipspace Cluster`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> network port show -ipspace Cluster

                                       Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link  MTU   Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ----- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. 설정하다 `-auto-revert` 매개변수 `false` 두 노드의 클러스터 LIF clus1 및 clus2에서:
+
`network interface modify`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert false
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert false
----
====
+

NOTE: 릴리스 8.3 이상의 경우 다음 명령을 사용하세요. `network interface modify -vserver Cluster -lif * -auto-revert false`

. 원격 클러스터 인터페이스의 연결성을 확인하세요.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
당신은 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령:

`network interface check cluster-connectivity start`그리고 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*참고:* 실행하기 전에 몇 초 동안 기다리십시오. `show` 세부 정보를 표시하는 명령입니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스의 경우 다음을 사용할 수도 있습니다. `cluster ping-cluster -node <name>` 연결성을 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step10]] 각 노드의 콘솔에서 clus1을 포트 e2a로 마이그레이션합니다.
+
`network interface migrate`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 clus1을 node1과 node2의 포트 e2a로 마이그레이션하는 프로세스를 보여줍니다.

[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus1 -source-node node1 -dest-node node1 -dest-port e2a
cluster::*> network interface migrate -vserver node2 -lif clus1 -source-node node2 -dest-node node2 -dest-port e2a
----
====
+

NOTE: 릴리스 8.3 이상의 경우 다음 명령을 사용하세요. `network interface migrate -vserver Cluster -lif clus1 -destination-node node1 -destination-port e2a`

. 마이그레이션이 수행되었는지 확인하세요.
+
`network interface show -vserver Cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예제에서는 clus1이 node1과 node2의 포트 e2a로 마이그레이션되었는지 확인합니다.

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e2a     false
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e2a     false
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
====
. 두 노드 모두에서 클러스터 포트 e1a를 종료합니다.
+
`network port modify`

+
.예를 보여주세요
[%collapsible]
====
다음 예제에서는 node1과 node2에서 포트 e1a를 종료하는 방법을 보여줍니다.

[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin false
cluster::*> network port modify -node node2 -port e1a -up-admin false
----
====
. 포트 상태를 확인하세요:
+
`network port show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 포트 e1a가 `down` node1과 node2에서:

[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        down  9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. 노드 1의 클러스터 포트 e1a에서 케이블을 분리한 다음, CN1610 스위치에서 지원하는 적절한 케이블을 사용하여 e1a를 클러스터 스위치 cs1의 포트 1에 연결합니다.
+
그만큼link:https://hwu.netapp.com/Switch/Index["Hardware Universe"^] 케이블링에 대한 자세한 정보가 포함되어 있습니다.

. 노드2의 클러스터 포트 e1a에서 케이블을 분리한 다음, CN1610 스위치에서 지원하는 적절한 케이블을 사용하여 e1a를 클러스터 스위치 cs1의 포트 2에 연결합니다.
. 클러스터 스위치 cs1에서 모든 노드 연결 포트를 활성화합니다.
+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 스위치 cs1에서 포트 1~12가 활성화되어 있음을 보여줍니다.

[listing]
----

(cs1)# configure
(cs1)(Config)# interface 0/1-0/12
(cs1)(Interface 0/1-0/12)# no shutdown
(cs1)(Interface 0/1-0/12)# exit
(cs1)(Config)# exit
----
====
. 각 노드에서 첫 번째 클러스터 포트 e1a를 활성화합니다.
+
`network port modify`

+
.예를 보여주세요
[%collapsible]
====
다음 예제에서는 node1과 node2에서 포트 e1a를 활성화하는 방법을 보여줍니다.

[listing]
----

cluster::*> network port modify -node node1 -port e1a -up-admin true
cluster::*> network port modify -node node2 -port e1a -up-admin true
----
====
. 모든 클러스터 포트가 있는지 확인하십시오. `up` :
+
`network port show -ipspace Cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 모든 클러스터 포트가 `up` node1과 node2에서:

[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. 두 노드 모두에서 이전에 마이그레이션된 clus1을 e1a로 되돌립니다.
+
`network interface revert`

+
.예를 보여주세요
[%collapsible]
====
다음 예제에서는 clus1을 node1과 node2의 포트 e1a로 되돌리는 방법을 보여줍니다.

[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus1
cluster::*> network interface revert -vserver node2 -lif clus1
----
====
+

NOTE: 릴리스 8.3 이상의 경우 다음 명령을 사용하세요. `network interface revert -vserver Cluster -lif <nodename_clus<N>>`

. 모든 클러스터 LIF가 있는지 확인하십시오. `up` , 운영 및 표시 `true` "집" 열에서:
+
`network interface show -vserver Cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 모든 LIF가 `up` 노드1과 노드2에서 "Is Home" 열 결과가 다음과 같습니다. `true` :

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e2a     true
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e2a     true

4 entries were displayed.
----
====
. 클러스터의 노드 상태에 대한 정보를 표시합니다.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 클러스터 내 노드의 상태와 적격성에 대한 정보를 표시합니다.

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. 각 노드의 콘솔에서 clus2를 포트 e1a로 마이그레이션합니다.
+
`network interface migrate`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 clus2를 node1과 node2의 포트 e1a로 마이그레이션하는 프로세스를 보여줍니다.

[listing]
----

cluster::*> network interface migrate -vserver node1 -lif clus2 -source-node node1 -dest-node node1 -dest-port e1a
cluster::*> network interface migrate -vserver node2 -lif clus2 -source-node node2 -dest-node node2 -dest-port e1a
----
====
+

NOTE: 릴리스 8.3 이상의 경우 다음 명령을 사용하세요. `network interface migrate -vserver Cluster -lif node1_clus2 -dest-node node1 -dest-port e1a`

. 마이그레이션이 수행되었는지 확인하세요.
+
`network interface show -vserver Cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예제에서는 clus2가 node1과 node2의 포트 e1a로 마이그레이션되었는지 확인합니다.

[listing]
----

cluster::*> network interface show -vserver Cluster
            Logical    Status     Network       Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask  Node          Port    Home
----------- ---------- ---------- ------------- ------------- ------- ----
node1
            clus1      up/up    10.10.10.1/16   node1         e1a     true
            clus2      up/up    10.10.10.2/16   node1         e1a     false
node2
            clus1      up/up    10.10.11.1/16   node2         e1a     true
            clus2      up/up    10.10.11.2/16   node2         e1a     false

4 entries were displayed.
----
====
. 두 노드 모두에서 클러스터 포트 e2a를 종료합니다.
+
`network port modify`

+
.예를 보여주세요
[%collapsible]
====
다음 예제에서는 node1과 node2에서 포트 e2a를 종료하는 방법을 보여줍니다.

[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin false
cluster::*> network port modify -node node2 -port e2a -up-admin false
----
====
. 포트 상태를 확인하세요:
+
`network port show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 포트 e2a가 `down` node1과 node2에서:

[listing]
----

cluster::*> network port show -role cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        down  9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. 노드 1의 클러스터 포트 e2a에서 케이블을 분리한 다음, CN1610 스위치에서 지원하는 적절한 케이블을 사용하여 e2a를 클러스터 스위치 cs2의 포트 1에 연결합니다.
. 노드2의 클러스터 포트 e2a에서 케이블을 분리한 다음, CN1610 스위치에서 지원하는 적절한 케이블을 사용하여 e2a를 클러스터 스위치 cs2의 포트 2에 연결합니다.
. 클러스터 스위치 cs2에서 모든 노드 연결 포트를 활성화합니다.
+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 스위치 cs2에서 포트 1~12가 활성화되어 있음을 보여줍니다.

[listing]
----

(cs2)# configure
(cs2)(Config)# interface 0/1-0/12
(cs2)(Interface 0/1-0/12)# no shutdown
(cs2)(Interface 0/1-0/12)# exit
(cs2)(Config)# exit
----
====
. 각 노드에서 두 번째 클러스터 포트 e2a를 활성화합니다.
+
.예를 보여주세요
[%collapsible]
====
다음 예제에서는 node1과 node2에서 포트 e2a를 활성화하는 방법을 보여줍니다.

[listing]
----

cluster::*> network port modify -node node1 -port e2a -up-admin true
cluster::*> network port modify -node node2 -port e2a -up-admin true
----
====
. 모든 클러스터 포트가 있는지 확인하십시오. `up` :
+
`network port show -ipspace Cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 모든 클러스터 포트가 `up` node1과 node2에서:

[listing]
----

cluster::*> network port show -ipspace Cluster
                                      Auto-Negot  Duplex     Speed (Mbps)
Node   Port   Role         Link   MTU Admin/Oper  Admin/Oper Admin/Oper
------ ------ ------------ ---- ----- ----------- ---------- ------------
node1
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000
node2
       e1a    clus1        up    9000  true/true  full/full   auto/10000
       e2a    clus2        up    9000  true/true  full/full   auto/10000

4 entries were displayed.
----
====
. 두 노드 모두에서 clus2(이전에 마이그레이션됨)를 e2a로 되돌립니다.
+
`network interface revert`

+
.예를 보여주세요
[%collapsible]
====
다음 예제에서는 clus2를 node1과 node2의 포트 e2a로 되돌리는 방법을 보여줍니다.

[listing]
----

cluster::*> network interface revert -vserver node1 -lif clus2
cluster::*> network interface revert -vserver node2 -lif clus2
----
====
+

NOTE: 릴리스 8.3 이상에서는 명령이 다음과 같습니다.
`cluster::*> network interface revert -vserver Cluster -lif node1_clus2` 그리고
`cluster::*> network interface revert -vserver Cluster -lif node2_clus2`





=== 3단계: 구성 완료

. 모든 인터페이스가 표시되는지 확인하세요. `true` "집" 열에서:
+
`network interface show -vserver Cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 모든 LIF가 `up` 노드1과 노드2에서 "Is Home" 열 결과가 다음과 같습니다. `true` :

[listing]
----

cluster::*> network interface show -vserver Cluster

             Logical    Status     Network            Current     Current Is
Vserver      Interface  Admin/Oper Address/Mask       Node        Port    Home
-----------  ---------- ---------- ------------------ ----------- ------- ----
node1
             clus1      up/up      10.10.10.1/16      node1       e1a     true
             clus2      up/up      10.10.10.2/16      node1       e2a     true
node2
             clus1      up/up      10.10.11.1/16      node2       e1a     true
             clus2      up/up      10.10.11.2/16      node2       e2a     true
----
====
. 원격 클러스터 인터페이스의 연결성을 확인하세요.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
당신은 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령:

`network interface check cluster-connectivity start`그리고 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*참고:* 실행하기 전에 몇 초 동안 기다리십시오. `show` 세부 정보를 표시하는 명령입니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스의 경우 다음을 사용할 수도 있습니다. `cluster ping-cluster -node <name>` 연결성을 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[3단계]] 두 노드 모두 각 스위치에 두 개의 연결이 있는지 확인합니다.
+
`show isdp neighbors`

+
.예를 보여주세요
[%collapsible]
====
다음 예는 두 스위치에 대한 적절한 결과를 보여줍니다.

[listing]
----

(cs1)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e1a
node2                  0/2          163       H            FAS3270   e1a
cs2                    0/13         11        S            CN1610    0/13
cs2                    0/14         11        S            CN1610    0/14
cs2                    0/15         11        S            CN1610    0/15
cs2                    0/16         11        S            CN1610    0/16

(cs2)# show isdp neighbors
Capability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge,
                  S - Switch, H - Host, I - IGMP, r - Repeater
Device ID              Intf         Holdtime  Capability   Platform  Port ID
---------------------- ------------ --------- ------------ --------- ------------
node1                  0/1          132       H            FAS3270   e2a
node2                  0/2          163       H            FAS3270   e2a
cs1                    0/13         11        S            CN1610    0/13
cs1                    0/14         11        S            CN1610    0/14
cs1                    0/15         11        S            CN1610    0/15
cs1                    0/16         11        S            CN1610    0/16
----
====
. 구성에 있는 장치에 대한 정보를 표시합니다.
+
`network device discovery show`

. 고급 권한 명령을 사용하여 두 노드 모두에서 2노드 스위치리스 구성 설정을 비활성화합니다.
+
`network options detect-switchless modify`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 스위치리스 구성 설정을 비활성화하는 방법을 보여줍니다.

[listing]
----

cluster::*> network options detect-switchless modify -enabled false
----
====
+

NOTE: 릴리스 9.2 이상에서는 구성이 자동으로 변환되므로 이 단계를 건너뜁니다.

. 설정이 비활성화되었는지 확인하세요.
+
`network options detect-switchless-cluster show`

+
.예를 보여주세요
[%collapsible]
====
그만큼 `false` 다음 예제의 출력은 구성 설정이 비활성화되었음을 보여줍니다.

[listing]
----

cluster::*> network options detect-switchless-cluster show
Enable Switchless Cluster Detection: false
----
====
+

NOTE: 릴리스 9.2 이상에서는 다음까지 기다리십시오. `Enable Switchless Cluster` false로 설정됩니다.  최대 3분 정도 걸릴 수 있습니다.

. 각 노드에서 클러스터 clus1과 clus2를 자동으로 되돌리도록 구성하고 확인합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing]
----

cluster::*> network interface modify -vserver node1 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node1 -lif clus2 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus1 -auto-revert true
cluster::*> network interface modify -vserver node2 -lif clus2 -auto-revert true
----
====
+

NOTE: 릴리스 8.3 이상의 경우 다음 명령을 사용하세요. `network interface modify -vserver Cluster -lif * -auto-revert true` 클러스터의 모든 노드에서 자동 복귀를 활성화합니다.

. 클러스터의 노드 멤버 상태를 확인하세요.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 클러스터 내 노드의 상태와 적격성에 대한 정보를 보여줍니다.

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false
----
====
. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
. 권한 수준을 다시 관리자로 변경합니다.
+
`set -privilege admin`


