---
permalink: switch-netapp-cn1610/migrate-fas22xx-systems.html 
sidebar: sidebar 
keywords: migrate, two-node switched cluster, fas22xx systems, single, network connection 
summary: 단일 클러스터 네트워크 연결을 사용하는 스위치가 없는 클러스터에서 NetApp CN1610 클러스터 스위치를 사용하는 스위치 클러스터로 FAS22xx 시스템을 마이그레이션합니다. 
---
= NetApp CN1610 클러스터 스위치를 사용하여 FAS22xx 시스템을 스위치 클러스터로 마이그레이션합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
컨트롤러당 단일 10GbE 연결을 사용하는 2노드 스위치가 없는 클러스터에서 NetApp CN1610 클러스터 스위치를 사용하는 스위치 클러스터로 FAS22xx 시스템을 마이그레이션합니다.



[[review-requirements]]
== 검토 요구 사항

.시작하기 전에
다음 사항이 있는지 확인하세요.

* 스위치가 없는 구성에서 스위치가 있는 구성으로 마이그레이션하기 위한 두 개의 클러스터 연결.
* 클러스터는 정상 작동 중이며, 백투백 연결로 연결된 두 개의 노드로 구성되어 있습니다.
* 노드가 ONTAP 8.2 이상을 실행하고 있습니다.
* 스위치가 없는 클러스터 기능은 노드가 두 개 이상일 경우 사용할 수 없습니다.
* 모든 클러스터 포트가  `up` 상태입니다.


.관련 정보
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_suppress_automatic_case_creation_during_scheduled_maintenance_windows["NetApp KB 문서 1010449: 예약된 유지 관리 기간 동안 자동 케이스 생성을 억제하는 방법"^]



[[migrate-the-switches]]
== 스위치 마이그레이션

이 절차는 스위치가 없는 환경에서 클러스터의 직접 연결을 제거하고 스위치에 대한 각 연결을 파트너 노드에 대한 연결로 대체하는 비중단 절차입니다.



[[step-1-prepare-for-migration]]
=== 1단계: 마이그레이션 준비

. 권한 수준을 고급으로 변경하려면 다음을 입력하세요. `y` 계속하라는 메시지가 표시되면:
+
`set -privilege advanced`

+
고급 프롬프트(`*>` )이 나타납니다.

. 두 노드 중 하나의 시스템 콘솔에서 노드의 클러스터 상태를 확인하십시오.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 클러스터 내 노드의 상태와 적격성에 대한 정보를 표시합니다.

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. 각 노드의 시스템 콘솔에서 HA 페어의 상태를 확인하십시오. `storage failover show`
+
.예를 보여주세요
[%collapsible]
====
다음 예시는 node1과 node2의 상태를 보여줍니다.

[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
====
. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
`x`은(는) 유지보수 윈도우의 기간(시간 단위)입니다.

+

NOTE: 이 메시지는 기술 지원에 해당 유지보수 작업을 알리므로 유지보수 윈도우 동안 자동 케이스 생성이 억제됩니다.

+
.예를 보여주세요
[%collapsible]
====
다음 명령은 2시간 동안 자동 케이스 생성을 억제합니다.

[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
====
. 스위치가 없는 클러스터의 현재 상태가 `true`인지 확인한 후 스위치가 없는 클러스터 모드를 비활성화하십시오.
+
`network options switchless-cluster modify -enabled false`

. 대상 노드를 인수하십시오:
+
`storage failover takeover -ofnode _target_node_name_`

+
어떤 노드가 대상 노드인지는 중요하지 않습니다. 대상 노드가 장악되면 자동으로 재부팅되고  `Waiting for giveback...` 메시지가 표시됩니다.

+
현재 활성 노드는 인수된 파트너(대상) 노드에 대한 데이터를 제공하고 있습니다.

. 손상된 노드를 인수한 후 2분 정도 기다려 인수 작업이 성공적으로 완료되었는지 확인하십시오.
. 대상 노드에  `Waiting for giveback...`메시지가 표시되면 해당 노드를 종료하십시오.
+
노드를 종료하는 방법은 노드 서비스 프로세서(SP)를 통한 원격 관리를 사용하는지 여부에 따라 다릅니다.

+
|===
| SP인 경우 | 그 다음에... 


 a| 
구성됨
 a| 
손상된 노드 SP에 로그인한 다음 시스템 전원을 끄십시오. `system power off`



 a| 
구성되지 않았습니다
 a| 
손상된 노드 프롬프트에서  `Ctrl-C`를 누른 다음  `y`로 응답하여 노드를 중지하십시오.

|===




[[step-2-configure-cables-and-ports]]
=== 2단계: 케이블 및 포트 구성

. 각 컨트롤러 모듈에서 10GbE 클러스터 포트를 스위치가 없는 클러스터에 연결하는 케이블을 분리합니다.
. 두 컨트롤러 모듈 모두에서 10GbE 클러스터 포트를 스위치에 연결하십시오.
. 스위치에 연결된 10GbE 클러스터 포트가 동일한 VLAN에 속하도록 구성되어 있는지 확인하십시오.
+
각 컨트롤러 모듈의 클러스터 포트를 서로 다른 스위치에 연결하려는 경우, 각 스위치에서 클러스터 포트가 연결되는 포트가 동일한 VLAN으로 구성되어 있는지, 그리고 두 스위치 모두에서 트렁킹이 올바르게 구성되어 있는지 확인해야 합니다.

. 대상 노드에 저장 공간을 반환합니다.
+
`storage failover giveback -ofnode node2`

. 반환 작업의 진행 상황을 모니터링합니다.
+
`storage failover show-giveback`

. 반환 작업이 완료되면 HA 쌍이 정상 상태이고 테이크오버가 가능한지 확인합니다.
+
`storage failover show`

+
.예를 보여주세요
[%collapsible]
====
출력은 다음과 유사해야 합니다.

[listing]
----

Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node1          node2          true      Connected to node2
node2          node1          true      Connected to node1

2 entries were displayed.
----
====
. 클러스터 포트 LIF가 올바르게 작동하는지 확인하십시오.
+
`network interface show -role cluster`

+
.예를 보여주세요
[%collapsible]
====
다음 예시는 LIF가 `up` node1과 node2에 있고 "Is Home" 열의 결과가 `true`임을 보여줍니다.

[listing]
----

cluster::*> network interface show -role cluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
node1
            clus1        up/up    192.168.177.121/24  node1        e1a     true
node2
            clus1        up/up    192.168.177.123/24  node2        e1a     true

2 entries were displayed.
----
====
. 두 노드 중 하나의 시스템 콘솔에서 노드의 클러스터 상태를 확인하십시오.
+
`cluster show`

+
.예를 보여주세요
[%collapsible]
====
다음 예에서는 클러스터 내 노드의 상태와 적격성에 대한 정보를 표시합니다.

[listing]
----

cluster::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

2 entries were displayed.
----
====
. 원격 클러스터 인터페이스의 연결성을 확인하세요.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
당신은 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령:

`network interface check cluster-connectivity start`그리고 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*참고:* 실행하기 전에 몇 초 동안 기다리십시오. `show` 세부 정보를 표시하는 명령입니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스의 경우 다음을 사용할 수도 있습니다. `cluster ping-cluster -node <name>` 연결성을 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e0a
Cluster node1_clus2 169.254.49.125 node1 e0b
Cluster node2_clus1 169.254.47.194 node2 e0a
Cluster node2_clus2 169.254.19.183 node2 e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====


[[step-3-complete-the-procedure]]
=== 3단계: 절차 완료

. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`

+
.예를 보여주세요
[%collapsible]
====
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----
====
. 권한 수준을 다시 관리자로 변경합니다.
+
`set -privilege admin`


