---
permalink: switch-netapp-cn1610/prepare-install-fastpath-rcfs.html 
sidebar: sidebar 
keywords: install, fastpath, software, rcfs, netapp cluster switch 
summary: 'NetApp CN1610 클러스터 스위치에 FASTPATH ​​소프트웨어와 참조 구성 파일(RCF)을 설치해야 합니다.' 
---
= NetApp 클러스터 스위치에 FASTPATH ​​소프트웨어 및 RCF 설치 준비
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp CN1610 클러스터 스위치에 FASTPATH ​​소프트웨어와 참조 구성 파일(RCF)을 설치해야 합니다.

.시작하기 전에
* 클러스터는 완벽하게 기능하는 클러스터여야 합니다.
* 결함이 있는 클러스터 네트워크 인터페이스 카드(NIC)가 없어야 하며, 클러스터 스위치에 연결된 모든 포트가 작동해야 합니다.
* 모든 클러스터 포트가 작동 중이어야 합니다.
* 모든 클러스터 논리 인터페이스(LIF)는 작동 중이어야 하며 마이그레이션되어서는 안 됩니다.
* ONTAP (권한: 고급) `cluster ping-cluster -node node1` 명령은 다음을 표시해야 합니다. `larger than PMTU communication` 모든 경로에서 성공합니다.
* 스위치 호환성 표를 참조해야 합니다. http://mysupport.netapp.com/NOW/download/software/cm_switches_ntap/["NetApp CN1601 및 CN1610 스위치"^] 지원되는 FASTPATH, RCF 및 ONTAP 버전에 대한 페이지입니다.
+
RCF 버전과 FASTPATH 버전의 명령 구문 사이에 명령 종속성이 있을 수 있습니다.




NOTE: RCF 버전 1.2에서는 보안 문제로 인해 Telnet 지원이 명시적으로 비활성화되었습니다.  RCF 1.2를 설치하는 동안 연결 문제를 방지하려면 Secure Shell(SSH)이 활성화되어 있는지 확인해야 합니다.  그만큼 https://library.netapp.com/ecm/ecm_get_file/ECMP1117874["NetApp® CN1610 스위치 관리자 가이드"^] SSH에 대한 자세한 정보가 있습니다.

.이 작업에 관하여
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 이 문서의 절차에서는 클러스터형 Data ONTAP 8.2 구문을 사용합니다.  결과적으로 클러스터 Vserver, LIF 이름 및 CLI 출력은 Data ONTAP 8.3과 다릅니다.
* 두 개의 NetApp 스위치는 cs1과 cs2입니다.
* 두 개의 클러스터 LIF는 clus1과 clus2입니다.
* V서버는 vs1과 vs2입니다.
* 그만큼 `cluster::*>` 프롬프트는 클러스터의 이름을 나타냅니다.
* 각 노드의 클러스터 포트는 e1a와 e2a로 명명됩니다.
+
그만큼 https://hwu.netapp.com/["Hardware Universe"^] 플랫폼에서 지원되는 실제 클러스터 포트에 대한 자세한 정보가 있습니다.

* NetApp 클러스터 스위치에서 지원되는 ISL(Inter-Switch Links)은 포트 0/13~0/16입니다.
* NetApp 클러스터 스위치에서 지원되는 노드 연결은 포트 0/1~0/12입니다.


이 절차는 두 부분으로 구성됩니다.

* link:install-fastpath-software.html["FASTPATH 소프트웨어 설치"]FASTPATH 소프트웨어를 설치하는 방법을 설명합니다.
* link:install-rcf-file.html["CN1610 스위치에 RCF 설치"]RCF를 설치하는 방법을 설명합니다.

