---
permalink: switch-netapp-cn1610/replace-cn1610-switch.html 
sidebar: sidebar 
keywords: replace, netapp cn1610, cluster switch 
summary: 결함이 있는 NetApp CN1610 클러스터 스위치를 교체합니다. 이 작업은 시스템 중단 없이 진행됩니다. 
---
= NetApp CN1610 클러스터 스위치 교체
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp CN1610 클러스터 스위치를 클러스터 운영을 중단하지 않고 클러스터 네트워크에서 교체합니다. 이 비중단 교체 절차(NDU)는 교체 스위치를 준비하고 고장난 스위치에서 연결을 마이그레이션하는 과정을 포함합니다.



[[review-requirements]]
== 검토 요구 사항

.시작하기 전에
스위치 교체를 수행하기 전에 현재 환경과 교체 스위치에서 스위치 교체를 수행하기 전에 기존 클러스터 및 네트워크 인프라에 대해 다음 조건이 충족되어야 합니다.

* 기존 클러스터는 최소한 하나의 클러스터 스위치가 완전히 연결된 상태로, 완벽하게 작동하는지 확인해야 합니다.
* 클러스터의 모든 포트가 활성화되어 있어야 합니다.
* 클러스터의 모든 논리 인터페이스(LIF)는 활성화되어 있어야 하며 마이그레이션되지 않았어야 합니다.
* ONTAP 클러스터 `ping-cluster -node node1` 명령은 모든 경로에서 기본 연결 및 PMTU보다 큰 통신이 성공적으로 이루어졌음을 나타내야 합니다.




[[enable-console-logging]]
== 콘솔 로깅 활성화

NetApp 사용 중인 장치에서 콘솔 로깅을 활성화하고 스위치를 교체할 때 다음 작업을 수행할 것을 강력히 권장합니다.

* 유지관리 중에는 AutoSupport 활성화해 두세요.
* 유지보수 전후에 유지보수 AutoSupport를 실행하여 유지보수 기간 동안 케이스 생성을 비활성화하십시오. 자세한 내용은 이 기술 자료 문서 link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["SU92: 예약된 유지 관리 기간 동안 자동 케이스 생성을 억제하는 방법"^]를 참조하십시오.
* 모든 CLI 세션에 대한 세션 로깅을 활성화합니다.  세션 로깅을 활성화하는 방법에 대한 지침은 이 기술 자료 문서의 "세션 출력 로깅" 섹션을 검토하세요.link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP 시스템에 대한 최적의 연결을 위해 PuTTY를 구성하는 방법"^] .




[[replace-the-switch]]
== 스위치를 교체하세요

.이 작업에 관하여
클러스터 LIF가 호스팅되는 노드에서 클러스터 LIF를 마이그레이션하는 명령을 실행해야 합니다.

이 절차의 예에서는 다음 클러스터 스위치와 노드 명명법을 사용합니다.

* 두 CN1610 클러스터 스위치의 이름은  `cs1`와  `cs2`입니다.
* 교체해야 할 CN1610 스위치(결함이 있는 스위치)의 이름은 `old_cs1`입니다.
* 새로운 CN1610 스위치(교체용 스위치)의 이름은 `new_cs1`입니다.
* 교체되지 않는 파트너 스위치의 이름은 `cs2`입니다.


.단계
. 시작 구성 파일이 실행 중인 구성 파일과 일치하는지 확인합니다. 교체 과정에서 사용할 수 있도록 이 파일들을 로컬에 저장해야 합니다.
+
다음 예시의 구성 명령은 FASTPATH 1.2.0.7에 대한 것입니다.

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)> *enable*
(old_cs1)# *show running-config*
(old_cs1)# *show startup-config*
----
====
. 실행 중인 구성 파일의 복사본을 만듭니다.
+
다음 예시의 명령어는 FASTPATH 1.2.0.7 버전에 대한 것입니다.

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *show running-config filename.scr*
Config script created successfully.
----
====



NOTE:  `CN1610_CS_RCF_v1.2.scr`을 제외한 모든 파일 이름을 사용할 수 있습니다. 파일 이름은 *.scr* 확장자를 가져야 합니다.

. [[step3]]교체를 준비하기 위해 스위치의 실행 중인 구성 파일을 외부 호스트에 저장합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(old_cs1)# *copy nvram:script filename.scr scp://<Username>@<remote_IP_address>/path_to_file/filename.scr*
----
====
. 스위치와 ONTAP 버전이 호환성 매트릭스에서 일치하는지 확인합니다. 자세한 내용은 link:https://mysupport.netapp.com/site/info/netapp-cluster-switch["NetApp CN1601 및 CN1610 스위치"^]을 참조하십시오.
. NetApp 지원 사이트의 link:https://mysupport.netapp.com/site/products/all/details/netapp-cluster-switches/downloads-tab["소프트웨어 다운로드 페이지"^]에서 NetApp 클러스터 스위치를 선택하여 적절한 RCF 및 FASTPATH 버전을 다운로드하십시오.
. 새 스위치에서 사용할 수 있도록 FASTPATH, RCF 및 저장된 구성 `.scr` 파일을 사용하여 TFTP(Trivial File Transfer Protocol) 서버를 설정합니다.
. 스위치 오른쪽의 "IOIOI"라고 표시된 RJ-45 커넥터인 직렬 포트를 터미널 에뮬레이션이 가능한 호스트에 연결하십시오.
. 호스트에서 시리얼 터미널 연결 설정을 구성하십시오.
+
.. 9600 baud
.. 8개의 데이터 비트
.. 1 정지 비트
.. 패리티: 없음
.. 흐름 제어: 없음


. 관리 포트(스위치 왼쪽에 있는 RJ-45 렌치 포트)를 TFTP 서버가 있는 동일한 네트워크에 연결합니다.
. TFTP 서버가 있는 네트워크에 연결할 준비를 하십시오.
+
DHCP(동적 호스트 구성 프로토콜)를 사용하는 경우, 현재 스위치에 IP 주소를 구성할 필요가 없습니다. 서비스 포트는 기본적으로 DHCP를 사용하도록 설정되어 있습니다. 네트워크 관리 포트는 IPv4 및 IPv6 프로토콜 설정에서 '없음'으로 설정되어 있습니다. 렌치 포트가 DHCP 서버가 있는 네트워크에 연결되어 있는 경우, 서버 설정은 자동으로 구성됩니다.

+
고정 IP 주소를 설정하려면 serviceport protocol, network protocol 및 serviceport ip 명령을 사용해야 합니다.

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *serviceport ip <ipaddr> <netmask> <gateway>*
----
====
. 선택적으로, TFTP 서버가 랩톱에 있는 경우 표준 이더넷 케이블을 사용하여 CN1610 스위치를 랩톱에 연결한 다음 동일 네트워크에서 다른 IP 주소로 네트워크 포트를 구성합니다.
+
 `ping` 명령어를 사용하여 주소를 확인할 수 있습니다. 연결이 설정되지 않으면 라우팅되지 않은 네트워크를 사용하고 서비스 포트를 IP 192.168.x 또는 172.16.x로 구성하십시오. 나중에 서비스 포트를 운영 관리 IP 주소로 다시 구성할 수 있습니다.

. 선택적으로, 새 스위치에 맞는 RCF 및 FASTPATH 소프트웨어 버전을 확인하고 설치하십시오. 새 스위치가 올바르게 설정되었고 RCF 및 FASTPATH 소프트웨어 업데이트가 필요하지 않은 경우 13단계로 진행하십시오.
+
.. 새 스위치 설정을 확인하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show version*
----
====
.. RCF 파일을 새 스위치에 다운로드합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/CN1610_CS_RCF_v1.2.txt nvram:script CN1610_CS_RCF_v1.2.scr*
Mode.	TFTP
Set Server IP.	172.22.201.50
Path.	/
Filename....................................... CN1610_CS_RCF_v1.2.txt
Data Type...................................... Config Script
Destination Filename........................... CN1610_CS_RCF_v1.2.scr
File with same name already exists.
WARNING:Continuing with this command will overwrite the existing file.

Management access will be blocked for the duration of the transfer Are you sure you want to start? (y/n) y

File transfer in progress. Management access will be blocked for the duration of the transfer. please wait...
Validating configuration script...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script validated.
File transfer operation completed successfully.
----
====
.. RCF 파일이 스위치에 다운로드되었는지 확인하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script list*
Configuration Script Nam   Size(Bytes)
-------------------------- -----------
CN1610_CS_RCF_v1.1.scr            2191
CN1610_CS_RCF_v1.2.scr            2240
latest_config.scr                 2356

4 configuration script(s) found.
2039 Kbytes free.
----
====


. CN1610 스위치에 RCF를 적용하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply CN1610_CS_RCF_v1.2.scr*
Are you sure you want to apply the configuration script? (y/n) *y*
...
(the entire script is displayed line by line)
...
description "NetApp CN1610 Cluster Switch RCF v1.2 - 2015-01-13"
...
Configuration script 'CN1610_CS_RCF_v1.2.scr' applied. Note that the script output will go to the console.
After the script is applied, those settings will be active in the running-config file. To save them to the startup-config file, you must use the write memory command, or if you used the reload answer yes when asked if you want to save the changes.
----
====
+
.. 실행 중인 구성 파일을 저장하여 스위치를 재부팅할 때 시작 구성 파일로 사용되도록 하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
This operation may take a few minutes.
Management interfaces will not be available during this time.

Are you sure you want to save? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. 이미지를 CN1610 스위치에 다운로드하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/NetApp_CN1610_1.2.0.7.stk active*
Mode.	TFTP
Set Server IP.	tftp_server_ip_address
Path.	/
Filename....................................... NetApp_CN1610_1.2.0.7.stk
Data Type.	Code
Destination Filename.	active

Management access will be blocked for the duration of the transfer

Are you sure you want to start? (y/n) *y*

TFTP Code transfer starting...

File transfer operation completed successfully.
----
====
.. 스위치를 재부팅하여 새 활성 부팅 이미지를 실행하십시오.
+
6단계의 명령이 새 이미지를 반영하려면 스위치를 재부팅해야 합니다. 재부팅 명령을 입력한 후에는 두 가지 가능한 응답 화면이 나타날 수 있습니다.

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *reload*
The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved! System will now restart!
.
.
.
Cluster Interconnect Infrastructure

User:admin Password: (new_cs1) >*enable*
----
====
.. 저장된 구성 파일을 기존 스위치에서 새 스위치로 복사합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *copy tftp://<server_ip_address>/<filename>.scr nvram:script <filename>.scr*
----
====
.. 이전에 저장한 구성을 새 스위치에 적용합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *script apply <filename>.scr*
Are you sure you want to apply the configuration script? (y/n) *y*

The system has unsaved changes.
Would you like to save them now? (y/n) *y*

Config file 'startup-config' created successfully.

Configuration Saved!
----
====
.. 실행 중인 구성 파일을 시작 구성 파일에 저장합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *write memory*
----
====


. 이 클러스터에서 AutoSupport가 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제하십시오:
`system node autosupport invoke -node * -type all - message MAINT=xh`
+
_x_는 유지 관리 기간(시간)입니다.

+
[NOTE]
====
AutoSupport 메시지는 기술 지원팀에 이 유지 관리 작업을 알려 유지 관리 기간 동안 자동 케이스 생성이 억제되도록 합니다.

====
. 새 스위치 new_cs1에서 관리자 사용자로 로그인한 다음 노드 클러스터 인터페이스에 연결된 모든 포트(포트 1~12)를 종료하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
User:*admin*
Password:
(new_cs1)> *enable*
(new_cs1)#
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/1-0/12)# *shutdown*
(new_cs1)(interface 0/1-0/12)# *exit*
(new_cs1)# *write memory*
----
====
. old_cs1 스위치에 연결된 포트에서 클러스터 LIF를 마이그레이션합니다.
+
각 클러스터 LIF를 현재 노드의 관리 인터페이스에서 마이그레이션해야 합니다.

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *set -privilege advanced*
cluster::> *network interface migrate -vserver <vserver_name> -lif <Cluster_LIF_to_be_moved> - sourcenode <current_node> -dest-node <current_node> -dest-port <cluster_port_that_is_UP>*
----
====
. 클러스터 LIF가 각 노드의 적절한 클러스터 포트로 모두 이동되었는지 확인하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::> *network interface show -role cluster*
----
====
. 교체한 스위치에 연결된 클러스터 포트를 종료하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node <node_name> -port <port_to_admin_down> -up-admin false*
----
====
. 클러스터의 상태를 확인합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. 포트가 비활성화되어 있는지 확인하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster ping-cluster -node <node_name>*
----
====
. 스위치 cs2에서 ISL 포트 13번부터 16번까지를 비활성화하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *shutdown*
(cs2)# *show port-channel 3/1*
----
====
. 스토리지 관리자가 스위치 교체 준비가 되었는지 확인하십시오.
. old_cs1 스위치에서 모든 케이블을 분리한 다음, new_cs1 스위치의 동일한 포트에 케이블을 연결하십시오.
. cs2 스위치에서 ISL 포트 13~16을 활성화하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(cs2)# *config*
(cs2)(config)# *interface 0/13-0/16*
(cs2)(interface 0/13-0/16)# *no shutdown*
----
====
. 새 스위치에서 클러스터 노드와 연결된 포트를 활성화하십시오.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)# *config*
(new_cs1)(config)# *interface 0/1-0/12*
(new_cs1)(interface 0/13-0/16)# *no shutdown*
----
====
. 단일 노드에서 교체된 스위치에 연결된 클러스터 노드 포트를 활성화한 다음 링크가 활성화되었는지 확인합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network port modify -node node1 -port <port_to_be_onlined> -up-admin true*
cluster::*> *network port show -role cluster*
----
====
. 25단계에서 해당 포트와 연결된 클러스터 LIF를 동일 노드에서 되돌립니다.
+
이 예시에서 node1의 LIF는 "Is Home" 열이 true이면 성공적으로 되돌려집니다.

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *network interface revert -vserver node1 -lif <cluster_lif_to_be_reverted>*
cluster::*> *network interface show -role cluster*
----
====
. 첫 번째 노드의 클러스터 LIF가 활성화되어 홈 포트로 되돌아간 경우, 25단계와 26단계를 반복하여 클러스터의 다른 노드에서 클러스터 포트를 활성화하고 클러스터 LIF를 홈 포트로 되돌리십시오.
. 클러스터의 노드에 대한 정보를 표시합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster::*> *cluster show*
----
====
. 교체한 스위치의 시작 구성 파일과 실행 구성 파일이 올바른지 확인하십시오. 이 구성 파일은 1단계의 출력과 일치해야 합니다.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
(new_cs1)> *enable*
(new_cs1)# *show running-config*
(new_cs1)# *show startup-config*
----
====
. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화하세요.
+
`system node autosupport invoke -node * -type all -message MAINT=END`


