---
permalink: get-started/learn-switch-concept.html 
sidebar: sidebar 
keywords:  
summary: 클러스터, 스토리지 및 공유 스위치에 대해 알아보십시오. 
---
= AFX 시스템, 클러스터, 스토리지 및 공유 스위치에 대해 알아보세요.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp 클러스터 전체에서 데이터와 네트워크 인터페이스를 중단 없이 이동할 수 있는 기능을 갖춘 내부 통신을 제공하는 AFX 시스템, 클러스터, 스토리지 및 공유 스위치를 제공합니다.

“프런트 엔드” 스위치는 호스트 스토리지에 대한 연결을 제공하는 반면 “백 엔드” 클러스터 스위치는 둘 이상의 NetApp 컨트롤러 간 연결을 제공합니다.


NOTE: NetApp에서 검증된 백 엔드 스위치(NetApp에서 주문)만 지원됩니다.



== AFX 시스템 스위치

AFX 시스템 스위치를 사용하면 빠르고 에너지 효율적이며 공간을 절약하는 네트워크 스위치를 만들 수 있습니다.  크기가 작고 포트 밀도가 높아 대규모 네트워크를 처리하는 데 이상적입니다.  포트는 다양한 속도를 지원하며 여러 개의 연결로 분할될 수 있습니다.  NetApp 에서 지원하는 AFX 시스템 스위치는 다음과 같습니다.

* Cisco 넥서스 9332D-GX2B
* Cisco 넥서스 9364D-GX2A




== 클러스터 스위치

클러스터 스위치를 사용하면 2개 이상의 노드로 ONTAP 클러스터를 구축할 수 있습니다. NetApp 지원 클러스터 스위치에는 다음이 포함됩니다.

* Broadcom BES-53248
* Cisco Nexus 9336C-FX2
* nVidia SN2100




== 스토리지 스위치

스토리지 스위치를 사용하면 SAN(Storage Area Network)에서 서버와 스토리지 어레이 간에 데이터를 라우팅할 수 있습니다. NetApp 지원 스토리지 스위치는 다음과 같습니다.

* Cisco Nexus 9336C-FX2
* nVidia SN2100




== 공유 스위치

공유 스위치를 사용하면 공유 클러스터 및 스토리지 RCF 사용을 지원하여 클러스터 및 스토리지 기능을 공유 스위치 구성으로 결합할 수 있습니다. NetApp 지원 공유 스위치는 다음과 같습니다.

* Cisco Nexus 9336C-FX2




== 이용 종료

다음 스토리지 스위치를 더 이상 구매할 수 없지만 여전히 지원됩니다.

* Cisco Nexus 3232C
* Cisco Nexus 3132Q-V
* Cisco Nexus 92300YC
* NetApp CN1610

