---
permalink: get-started/learn-switch-concept.html 
sidebar: sidebar 
keywords:  
summary: 클러스터, 스토리지, 공유 스위치에 대해 알아보세요. 
---
= ONTAP 시스템 스위치에 대해 알아보기
:allow-uri-read: 


[role="lead"]
NetApp 클러스터 전체에서 데이터와 네트워크 인터페이스를 중단 없이 이동할 수 있는 기능을 갖춘 내부 통신을 제공하는 AFX 시스템, 클러스터, 스토리지 및 공유 스위치를 제공합니다.

"프런트엔드" 스위치는 호스트 스토리지에 대한 연결을 제공하는 반면, "백엔드" 클러스터 스위치는 두 개 이상의 NetApp 컨트롤러 간의 연결을 제공합니다.


NOTE: NetApp 검증한 백엔드 스위치( NetApp 에서 주문)만 지원됩니다.


CAUTION: 스위치를 업그레이드하는 경우 NetApp은 ONTAP 소프트웨어 업그레이드를 먼저 완료한 다음 스위치 소프트웨어 업그레이드를 수행할 것을 권장합니다.



[[afx-systems-switches]]
== AFX 시스템 스위치

AFX 시스템 스위치를 사용하면 빠르고 에너지 효율적이며 공간 절약형 네트워크 스위치를 구축할 수 있습니다. 작은 크기와 높은 포트 밀도로 대규모 네트워크 관리에 이상적입니다. 포트는 다양한 속도를 지원하며 여러 연결로 분할할 수 있습니다. NetApp에서 지원하는 AFX 시스템 스위치는 다음과 같습니다.

* Cisco Nexus 9808
* Cisco 넥서스 9332D-GX2B
* Cisco 넥서스 9364D-GX2A




[[cluster-switches]]
== 클러스터 스위치

클러스터 스위치를 사용하면 두 개 이상의 노드로 ONTAP 클러스터를 구축할 수 있습니다. NetApp 에서 지원하는 클러스터 스위치는 다음과 같습니다.

* 브로드컴 BES-53248
* Cisco 넥서스 9336C-FX2
* NVIDIA SN2100




[[storage-switches]]
== 스토리지 스위치

스토리지 스위치를 사용하면 SAN(Storage Area Network)에서 서버와 스토리지 어레이 간에 데이터를 라우팅할 수 있습니다.  NetApp 에서 지원하는 스토리지 스위치는 다음과 같습니다.

* Cisco 넥서스 9336C-FX2
* NVIDIA SN2100




[[shared-switches]]
== 공유 스위치

공유 스위치를 사용하면 공유 클러스터 및 스토리지 RCF 사용을 지원하여 클러스터와 스토리지 기능을 공유 스위치 구성으로 결합할 수 있습니다.  NetApp 에서 지원하는 공유 스위치는 다음과 같습니다.

* Cisco 넥서스 9336C-FX2




[[end-of-availability-switches]]
== 사용 가능 종료 스위치

더 이상 구매할 수 없지만 여전히 지원되는 스위치 목록은 link:../eoa/index.html["사용 가능 종료 스위치"]을(를) 참조하십시오.
