---
permalink: switch-cisco-92300/92300-overview.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: 두 개 이상의 노드가 있는 ONTAP 클러스터를 구축하려면 지원되는 클러스터 네트워크 스위치가 두 개 필요합니다.  선택 사항인 추가 관리 스위치를 사용할 수 있습니다. 
---
= Cisco Nexus 92300YC 스위치 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
두 개 이상의 노드가 있는 ONTAP 클러스터를 구축하려면 지원되는 클러스터 네트워크 스위치가 두 개 필요합니다.  선택 사항인 추가 관리 스위치를 사용할 수 있습니다.

Cisco Nexus 92300YC 스위치(X190003/R)는 스위치와 함께 제공되는 표준 브래킷을 사용하여 NetApp 시스템 캐비닛이나 타사 캐비닛에 설치할 수 있습니다.

다음 표에는 92300YC 스위치, 팬, 전원 공급 장치의 부품 번호와 설명이 나와 있습니다.

[cols="1,2"]
|===
| 부품 번호 | 설명 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PTSX(PTSX = 포트 측 배기)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PSIN(PSIN = 포트 측 흡입구)



 a| 
X-NXA-FAN-35CFM-B
 a| 
팬, Cisco N9K 포트 측 흡입 공기 흐름



 a| 
X-NXA-FAN-35CFM-F
 a| 
팬, Cisco N9K 포트 측 배기 공기 흐름



 a| 
X-NXA-PAC-650W-B
 a| 
전원 공급 장치, Cisco 650W - 포트 측 흡입구



 a| 
X-NXA-PAC-650W-F
 a| 
전원 공급 장치, Cisco 650W - 포트 측 배기

|===
Cisco Nexus 92300YC 스위치 공기 흐름 세부 정보:

* 포트 측 배기 공기 흐름(표준 공기) -- 차가운 공기는 냉각 통로의 팬과 전원 공급 모듈을 통해 섀시로 들어오고 뜨거운 통로의 섀시 포트 쪽을 통해 배출됩니다.  파란색으로 표시된 좌현 측 배기 공기 흐름입니다.
* 포트 측 흡입 공기 흐름(역방향 공기) -- 차가운 공기는 차가운 통로의 포트 끝을 통해 섀시로 들어오고 뜨거운 통로의 팬과 전원 공급 장치를 통해 배출됩니다.  부르고뉴 색상의 좌현 흡입구 공기 흐름.


.사용 가능한 문서
다음 표에는 Cisco Nexus 92300YC 스위치에 대해 제공되는 문서가 나열되어 있습니다.

|===


| 제목 | 설명 


 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-overview-cisco-92300.html["Cisco® Nexus 92300YC 클러스터 스위치 설정_"^]
 a| 
Cisco Nexus 92300YC 클러스터 스위치를 설정하고 구성하는 방법을 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-nxos-overview.html["_NX-OS 및 참조 구성 파일(RCF) 설치_"^]
 a| 
Nexus 92300YC 클러스터 스위치에 NX-OS 및 참조 구성 파일(RCF)을 설치하는 방법을 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/configure-install-initial.html["_새로운 Cisco Nexus 92300YC 스위치 구성_"^]
 a| 
이전 Cisco 스위치를 사용하는 환경에서 Cisco 92300YC 스위치를 사용하는 환경으로 마이그레이션하는 방법을 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-92300yc.html["_이전 Cisco 스위치에서 Cisco Nexus 92300YC 스위치로 마이그레이션_"^]
 a| 
이전 Cisco 스위치를 Cisco Nexus 92300YC 클러스터 스위치로 교체하는 절차를 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-2n-switched.html["_2노드 스위치리스 클러스터에서 마이그레이션_"^]
 a| 
Cisco Nexus 92300YC 클러스터 스위치를 사용하여 2노드 스위치리스 클러스터 환경에서 2노드 스위치 환경으로 마이그레이션하는 방법을 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/replace-92300yc.html["Cisco Nexus 92300YC 클러스터 스위치 교체_"^]
 a| 
클러스터에서 결함이 있는 Cisco Nexus 92300YC 스위치를 교체하고 스위치 운영 체제와 참조 구성 파일을 다운로드하는 절차를 설명합니다.

|===