---
permalink: switch-cisco-92300/92300-overview.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: 2개 이상의 노드로 ONTAP 클러스터를 구축하려면 두 개의 지원되는 클러스터 네트워크 스위치가 필요합니다. 선택 사항인 관리 스위치를 추가로 사용할 수 있습니다. 
---
= Cisco Nexus 92300YC 스위치 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
2개 이상의 노드로 ONTAP 클러스터를 구축하려면 두 개의 지원되는 클러스터 네트워크 스위치가 필요합니다. 선택 사항인 관리 스위치를 추가로 사용할 수 있습니다.

Cisco Nexus 92300YC 스위치(X190003/R)는 NetApp 시스템 캐비닛 또는 타사 캐비닛에 스위치와 함께 제공되는 표준 브래킷을 사용하여 설치할 수 있습니다.

다음 표에는 92300YC 스위치, 팬 및 전원 공급 장치에 대한 부품 번호 및 설명이 나와 있습니다.

[cols="1,2"]
|===
| 부품 번호 | 설명 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PTSX(PTSX = Port Side Exhaust)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PSIN(PSIN = 포트쪽 입수)



 a| 
X-NXA-FAN-35CFM-B
 a| 
팬, Cisco N9K 포트 쪽 흡입 공기 흐름



 a| 
X-NXA-FAN-35CFM-F
 a| 
팬, Cisco N9K 포트 측 배기 공기 흐름



 a| 
X-NXA-PAC-650W-B
 a| 
전원 공급 장치, Cisco 650W 포트 측면 흡입구



 a| 
X-NXA-PAC-650W-F
 a| 
전원 공급 장치, Cisco 650W 포트 측면 배기

|===
Cisco Nexus 92300YC 스위치 공기 흐름 세부 정보:

* 포트 쪽 배기 공기 흐름(표준 공기) - 차가운 공기는 차가운 통로에 있는 팬 및 전원 공급 장치 모듈을 통해 섀시에 들어가고 뜨거운 통로에 있는 섀시의 포트 끝을 통해 배출됩니다. 파란색 색상이 있는 포트 쪽 배기구 공기 흐름
* 포트 쪽 흡입 공기 흐름(역풍) -- 차가운 공기는 차가운 통로의 포트 끝을 통해 섀시에 유입되고 뜨거운 통로의 팬 및 전원 공급 장치 모듈을 통해 배출됩니다. 버건디 색상의 포트 쪽 흡입 공기 흐름


.기타 지원되는 스위치
* Nexus 3232C
+
스위치와 함께 제공된 사용자 지정 브래킷을 사용하여 Cisco Nexus 3232C 스위치(X190100) NetApp 시스템 캐비닛을 설치하거나, 스위치에 포함되어 있는 표준 브래킷이 있는 랙에 설치할 수 있습니다.

* Nexus 3132Q-V
+
Cisco Nexus 3132Q-V 스위치(X190001)를 NetApp 시스템 캐비닛 또는 타사 캐비닛에 설치하고 스위치에 포함된 표준 브래킷을 사용할 수 있습니다.



다음 클러스터 스위치는 더 이상 NetApp에서 사용할 수 없지만 Cisco에서는 제한적으로 지원합니다.

* Nexus 5596UP/5596T
+
Cisco Nexus 5596UP 스위치(X1967-R6) 또는 5596T(X1989-R6)를 스위치와 함께 제공된 사용자 지정 브래킷이 있는 NetApp 시스템 캐비닛에 설치하거나 스위치에 포함되어 있는 표준 브래킷이 있는 랙에 설치할 수 있습니다.

+
Nexus 5596UP 스위치는 1개 또는 2개의 16포트 확장 모듈(X1988-R6)도 지원합니다.

+
Nexus 5596T 스위치는 FAS2520의 클러스터 인터커넥트 스위치로만 지원되며 무중단 하드웨어 업그레이드를 수행하는 데 사용하도록 설계되었습니다.

+
http://support.netapp.com/info/communications/ECMP12454150.html["공급 종료"] 세부 정보.



다음 표에는 Cisco Nexus 92300YC 스위치에 사용할 수 있는 설명서가 나와 있습니다.

|===


| 제목 | 설명 


 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9336c-fx2/setup-switches.html["_Cisco ® Nexus 92300YC 클러스터 스위치 설정 _"^]
 a| 
Cisco Nexus 92300YC 클러스터 스위치를 설정하고 구성하는 방법에 대해 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/install-nxos-overview.html["_NX-OS 및 참조 구성 파일(RCFs)_을 설치합니다"^]
 a| 
Nexus 92300YC 클러스터 스위치에 NX-OS 및 참조 구성 파일(RCFs)을 설치하는 방법에 대해 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/configure-overview.html["_새 Cisco Nexus 92300YC 스위치 _ 를 구성합니다"^]
 a| 
이전 Cisco 스위치를 사용하는 환경에서 Cisco 92300YC 스위치를 사용하는 환경으로 마이그레이션하는 방법에 대해 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-92300yc-overview.html["_ 이전 Cisco 스위치에서 Cisco Nexus 92300YC 스위치로 마이그레이션 _"^]
 a| 
이전 Cisco 스위치를 Cisco Nexus 92300YC 클러스터 스위치로 교체하는 절차를 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/migrate-to-2n-switched.html["_2노드 스위치 없는 클러스터에서 마이그레이션 _"^]
 a| 
Cisco Nexus 92300YC 클러스터 스위치를 사용하여 스위치가 없는 2노드 클러스터 환경에서 2노드 스위치 환경으로 마이그레이션하는 방법을 설명합니다.



 a| 
https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-92300/replace-92300yc.html["_Cisco Nexus 92300YC 클러스터 스위치 _ 를 교체하십시오"^]
 a| 
에서는 클러스터의 결함 있는 Cisco Nexus 92300YC 스위치를 교체하고 스위치 운영 체제 및 참조 구성 파일을 다운로드하는 절차를 설명합니다.

|===