---
permalink: switch-cisco-92300/components-92300.html 
sidebar: sidebar 
keywords: cisco nexus 92300YC 
summary: 두 개 이상의 노드가 있는 ONTAP 클러스터를 구축하려면 지원되는 클러스터 네트워크 스위치가 두 개 필요합니다.  선택 사항인 추가 관리 스위치를 사용할 수 있습니다. 
---
= Cisco Nexus 92300YC 스위치의 구성 요소 및 부품 번호
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cisco Nexus 92300YC 스위치 설치 및 유지관리를 위해서는 모든 스위치 구성 요소와 부품 번호를 검토하세요. 를 참조하십시오 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] 자세한 내용은. 보다 link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["HWU에 없는 추가 정보 중 장비를 설치하는 데 필요한 정보는 무엇입니까?"^] 스위치 설치 요구 사항에 대한 자세한 내용은 다음을 참조하십시오.

다음 표에는 92300YC 스위치, 팬, 전원 공급 장치의 부품 번호와 설명이 나와 있습니다.

[cols="1,2"]
|===
| 부품 번호 | 설명 


 a| 
190003
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PTSX(PTSX = 포트 측 배기)



 a| 
190003R
 a| 
Cisco 92300YC, CLSW, 48Pt10/25GB, 18Pt100G, PSIN(PSIN = 포트 측 흡입구)



 a| 
X-NXA-FAN-35CFM-B
 a| 
팬, Cisco N9K 포트 측 흡입 공기 흐름



 a| 
X-NXA-FAN-35CFM-F
 a| 
팬, Cisco N9K 포트 측 배기 공기 흐름



 a| 
X-NXA-PAC-650W-B
 a| 
전원 공급 장치, Cisco 650W - 포트 측 흡입구



 a| 
X-NXA-PAC-650W-F
 a| 
전원 공급 장치, Cisco 650W - 포트 측 배기

|===
Cisco Nexus 92300YC 스위치 공기 흐름 세부 정보:

* 포트 측 배기 공기 흐름(표준 공기) -- 차가운 공기는 냉각 통로의 팬과 전원 공급 모듈을 통해 섀시로 들어오고 뜨거운 통로의 섀시 포트 쪽을 통해 배출됩니다.  파란색으로 표시된 좌현 측 배기 공기 흐름입니다.
* 포트 측 흡입 공기 흐름(역방향 공기) -- 차가운 공기가 차가운 통로의 포트 끝을 통해 섀시로 들어오고 뜨거운 통로의 팬과 전원 공급 장치를 통해 배출됩니다.  부르고뉴 색상의 좌현 흡입구 공기 흐름.


.다음은 무엇입니까?
구성 요소와 부품 번호를 확인한 후 다음을 검토할 수 있습니다. link:required-documentation-92300.html["필수 서류"].
