---
permalink: switch-cisco-92300/install-nxos-rcf.html 
sidebar: sidebar 
keywords: install rcf,rcf configure 
summary: '초기 설정 후 Cisco Nexus 92300YC 클러스터 스위치에 참조 구성 파일(RCF)을 설치하십시오.' 
---
= Cisco Nexus 92300YC 클러스터 스위치에 RCF 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
초기 설정 후 Cisco Nexus 92300YC 클러스터 스위치에 참조 구성 파일(RCF)을 설치하십시오. RCF는 클러스터 작동에 필요한 포트 할당 및 네트워크 설정을 정의합니다.

.스위치 및 노드 명명법
이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 두 Cisco 스위치의 이름은  `cs1`와  `cs2`입니다.
* 노드 이름은 다음과 같습니다. `node1` 그리고 `node2` .
* 클러스터 LIF 이름은 node1의 경우  `node1_clus1` 및  `node1_clus2`, node2의 경우  `node2_clus1` 및  `node2_clus2`입니다.
* 그만큼 `cluster1::*>` 프롬프트는 클러스터의 이름을 나타냅니다.
* 각 노드의 클러스터 포트는 다음과 같이 명명됩니다. `e0a` 그리고 `e0b` .
+
사용 중인 플랫폼에서 지원되는 실제 클러스터 포트에 대한 자세한 내용은 link:https://hwu.netapp.com/Home/Index["Hardware Universe"^]을(를) 참조하십시오. 스위치 설치 요구 사항에 대한 자세한 내용은 link:https://kb.netapp.com/Support/General_Support/What_additional_information_do_I_need_to_install_my_equipment_that_is_not_in_HWU["HWU에 없는 추가 정보 중 장비를 설치하는 데 필요한 정보는 무엇입니까?"^]를 참조하십시오.



.지원되는 포트 및 노드 연결
* Nexus 92300YC 스위치에서 지원하는 스위치 간 링크(ISL)는 1/65번 포트와 1/66번 포트입니다.
* Nexus 92300YC 스위치에서 지원하는 노드 연결 포트는 1/1부터 1/66까지입니다.
* 이 절차의 예제에서는 두 개의 노드를 사용합니다. 이 노드들은 두 개의 10GbE 클러스터 인터커넥트 포트 `e0a` 및 `e0b`를 사용합니다. 플랫폼에서 올바른 클러스터 포트를 확인하려면 link:https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^]을(를) 참조하십시오.


.시작하기 전에
* 최신 RCF가 있어야 합니다.
* 클러스터는 완벽하게 작동해야 합니다(로그에 오류가 있거나 유사한 문제가 없어야 합니다).
* NX-OS만 설치하고 현재 RCF 버전을 유지하는 경우, 원하는 부팅 이미지를 반영하도록 RCF에서 원하는 부팅 구성을 확인하거나 설정해야 합니다.
* 현재 부트 이미지를 반영하도록 부트 구성을 변경해야 하는 경우 RCF를 다시 적용하기 전에 변경해야 합니다. 이렇게 하면 향후 재부팅 시 올바른 버전이 인스턴스화됩니다.
* 지원되는 ONTAP, NX-OS 및 RCF 버전에 대한 https://support.netapp.com/NOW/download/software/cm_switches/["Cisco 이더넷 스위치"^] 페이지의 스위치 호환성 표를 참조해야 합니다.
* RCF의 명령 구문과 NX-OS 버전에서 발견되는 명령 구문 사이에 명령 종속성이 있을 수 있습니다.


.이 작업에 관하여
이 절차에서는 ONTAP 명령과 Cisco Nexus 9000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 지정되지 않는 한 ONTAP 명령을 사용합니다.

명령 출력은 ONTAP 릴리스에 따라 달라질 수 있습니다.

.단계
. 클러스터 스위치를 관리 네트워크에 연결합니다.
. ping 명령어를 사용하여 RCF를 호스팅하는 서버에 대한 연결 상태를 확인하십시오.
+
이 예제에서는 스위치가 IP 주소 172.19.2.1의 서버에 도달할 수 있는지 확인합니다.

+
[listing, subs="+quotes"]
----
cs2# *ping 172.19.2.1*
Pinging 172.19.2.1 with 0 bytes of data:

Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. RCF 파일을 Nexus 92300YC 스위치에 복사하십시오.
+
[listing, subs="+quotes"]
----
cs2# *copy sftp: bootflash: vrf management*
Enter source filename: */code/Nexus_92300YC_RCF_v1.0.2.txt*
Enter hostname for the sftp server: *172.19.2.1*
Enter username: *user1*

Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/Nexus_92300YC_RCF_v1.0.2.txt  /bootflash/nxos.9.2.2.bin
/code/Nexus_92300YC_R  100% 9687   530.2KB/s   00:00
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
. RCF 파일을 스위치의 실행 중인 구성과 병합합니다.
+
[listing, subs="+quotes"]
----
cs2# *copy bootflash:Nexus_92300YC_RCF_v1.0.2.txt running-config*

Disabling ssh: as its enabled right now:
 generating ecdsa key(521 bits)......
generated ecdsa key

Enabling ssh: as it has been disabled
 this command enables edge port type (portfast) by default on all interfaces. You
 should now disable edge port type (portfast) explicitly on switched ports leading to hubs,
 switches and bridges as they may create temporary bridging loops.

Edge port type (portfast) should only be enabled on ports connected to a single
 host. Connecting hubs, concentrators, switches, bridges, etc...  to this
 interface when edge port type (portfast) is enabled, can cause temporary bridging loops.
 Use with CAUTION

Edge Port Type (Portfast) has been configured on Ethernet1/1 but will only
 have effect when the interface is in a non-trunking mode.

...

Copy complete, now saving to disk (please wait)...
Copy complete.
----
. 스위치에서 RCF가 성공적으로 병합되었는지 확인하십시오.
+
`show running-config`

+
[listing, subs="+quotes"]
----
cs2# *show running-config*
!Command: show running-config
!Running configuration last done at: Wed Apr 10 06:32:27 2019
!Time: Wed Apr 10 06:36:00 2019

version 9.2(2) Bios:version 05.33
switchname cs2
vdc cs2 id 1
  limit-resource vlan minimum 16 maximum 4094
  limit-resource vrf minimum 2 maximum 4096
  limit-resource port-channel minimum 0 maximum 511
  limit-resource u4route-mem minimum 248 maximum 248
  limit-resource u6route-mem minimum 96 maximum 96
  limit-resource m4route-mem minimum 58 maximum 58
  limit-resource m6route-mem minimum 8 maximum 8

feature lacp

no password strength-check
username admin password 5 $5$HY9Kk3F9$YdCZ8iQJ1RtoiEFa0sKP5IO/LNG1k9C4lSJfi5kesl
6  role network-admin
ssh key ecdsa 521

banner motd #
********************************************************************************
*                                                                              *
*  Nexus 92300YC Reference Configuration File (RCF) v1.0.2 (10-19-2018)        *
*                                                                              *
*  Ports 1/1  - 1/48: 10GbE Intra-Cluster Node Ports                           *
*  Ports 1/49 - 1/64: 40/100GbE Intra-Cluster Node Ports                       *
*  Ports 1/65 - 1/66: 40/100GbE Intra-Cluster ISL Ports                        *
*                                                                              *
********************************************************************************
----
. 스위치를 재부팅할 때 시작 구성이 되도록 실행 구성을 저장합니다.
+
[listing, subs="+quotes"]
----
cs2# *copy running-config startup-config*

[########################################] 100%
Copy complete, now saving to disk (please wait)...
Copy complete.
----
. ONTAP 9.6P8 이상 버전에서는 다음 명령어를 사용하여 스위치 관련 로그 파일을 수집하는 이더넷 스위치 상태 모니터링 로그 수집 기능을 활성화하십시오. `system cluster-switch log setup-password` 및 `system cluster-switch log enable-collection`
+
[listing, subs="+quotes"]
----
cluster1::*> *system cluster-switch log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system cluster-switch log setup-password*

Enter the switch name: *cs2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system cluster-switch log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
. 스위치를 재부팅하고 실행 구성이 올바른지 확인하세요.
+
`reload`

+
[listing, subs="+quotes"]
----
cs2# *reload*

This command will reboot the system. (y/n)?  [n] *y*
----

