---
permalink: switch-cisco-92300/install-nxos-overview.html 
sidebar: sidebar 
keywords: install nx-os rcf cisco nx 92300yc cluster switch 
summary: 'Cisco NX-OS 소프트웨어와 참조 구성 파일(RCF)은 Cisco Nexus 92300YC 클러스터 스위치에 설치되어야 합니다.' 
---
= NX-OS 소프트웨어 및 참조 구성 파일(RCF) 설치를 준비합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NX-OS 소프트웨어와 참조 구성 파일(RCF)을 설치하기 전에 다음 절차를 따르세요.

.시작하기 전에
다음 사항이 있는지 확인하세요.

* 완벽하게 작동하는 클러스터(로그에 오류나 유사한 문제가 없음).
* 적절한 소프트웨어 및 업그레이드 가이드는 다음에서 제공됩니다. https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/series.html#InstallandUpgrade["Cisco Nexus 9000 시리즈 스위치"^] .


.예시에 관하여
이 절차의 예에서는 두 개의 노드를 사용합니다.  이 노드는 두 개의 10GbE 클러스터 상호 연결 포트를 사용합니다. `e0a` 그리고 `e0b` .  를 참조하십시오 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe"^] 플랫폼에서 올바른 클러스터 포트를 확인하세요.

이 절차의 예에서는 다음 스위치 및 노드 명명법을 사용합니다.

* 두 Cisco 스위치의 이름은 다음과 같습니다. `cs1` 그리고 `cs2` .
* 노드 이름은 다음과 같습니다. `node1` 그리고 `node2` .
* 클러스터 LIF 이름은 다음과 같습니다. `node1_clus1` 그리고 `node1_clus2` node1 및 `node2_clus1` 그리고 `node2_clus2` 노드2의 경우.
* 그만큼 `cluster1::*>` 프롬프트는 클러스터의 이름을 나타냅니다.


.이 작업에 관하여
이 절차에서는 ONTAP 명령과 Cisco Nexus 9000 시리즈 스위치 명령을 모두 사용해야 합니다. 달리 지정되지 않는 한 ONTAP 명령을 사용합니다.  명령 출력은 ONTAP 릴리스에 따라 달라질 수 있습니다.

.단계
. 계속할지 묻는 메시지가 나타나면 *y*를 입력하여 권한 수준을 고급으로 변경합니다.
+
`set -privilege advanced`

+
고급 프롬프트(`*>` )이 나타납니다.

. 이 클러스터에서 AutoSupport 활성화된 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
`system node autosupport invoke -node * -type all -message MAINT=xh`

+
여기서 _x_는 유지 관리 기간(시간)입니다.

+

NOTE: AutoSupport 메시지는 기술 지원팀에 이 유지 관리 작업을 알려 유지 관리 기간 동안 자동 케이스 생성이 억제되도록 합니다.

+
다음 명령은 2시간 동안 자동 케이스 생성을 억제합니다.

+
[listing]
----
cluster1:> **system node autosupport invoke -node * -type all -message MAINT=2h**
----
. 각 클러스터 상호 연결 스위치에 대해 각 노드에 구성된 클러스터 상호 연결 인터페이스 수를 표시합니다. `network device-discovery show -protocol cdp`
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol cdp*

 Node/      Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e0a    cs1                       Eth1/2            N9K-C92300YC
            e0b    cs2                       Eth1/2            N9K-C92300YC
node1      /cdp
            e0a    cs1                       Eth1/1            N9K-C92300YC
            e0b    cs2                       Eth1/1            N9K-C92300YC

4 entries were displayed.
----
====
. 각 클러스터 인터페이스의 관리 또는 운영 상태를 확인합니다.
+
.. 네트워크 포트 속성을 표시합니다. `network port show –ipspace Cluster`
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node2
                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

Node: node1
                                                  Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
--------- ------------ ---------------- ---- ---- ----------- --------
e0a       Cluster      Cluster          up   9000  auto/10000 healthy
e0b       Cluster      Cluster          up   9000  auto/10000 healthy

4 entries were displayed.
----
====
.. LIF에 대한 정보를 표시합니다. `network interface show -vserver Cluster`
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e0a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e0b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e0a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e0b     true

4 entries were displayed.
----
====


. 원격 클러스터 인터페이스의 연결성을 확인하세요.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
당신은 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령:

`network interface check cluster-connectivity start`그리고 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
*참고:* 실행하기 전에 몇 초 동안 기다리십시오. `show` 세부 정보를 표시하는 명령입니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스의 경우 다음을 사용할 수도 있습니다. `cluster ping-cluster -node <name>` 연결성을 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1     e0a
Cluster node1_clus2 169.254.49.125 node1     e0b
Cluster node2_clus1 169.254.47.194 node2     e0a
Cluster node2_clus2 169.254.19.183 node2     e0b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step6]] 모든 클러스터 LIF에서 자동 복귀 명령이 활성화되어 있는지 확인하세요.
+
`network interface show -vserver Cluster -fields auto-revert`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster -fields auto-revert*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true

4 entries were displayed.
----
====


.다음은 무엇인가요?
NX-OS 소프트웨어와 RCF를 설치할 준비가 되면 다음을 수행할 수 있습니다. link:install-nxos-software.html["NX-OS 소프트웨어를 설치하세요"].
