---
permalink: switch-nvidia-sn2100-storage/configure-overview-sn2100-storage.html 
sidebar: sidebar 
keywords: sn2100 SN2100 switches setup, sn2100 SN2100 switches install, cumulus linux 
summary: NVIDIA SN2100 스위치를 구성하기 전에 절차 개요를 검토하십시오. 
---
= NVIDIA SN2100 스토리지 스위치의 구성 프로세스 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVIDIA SN2100은 SAN(Storage Area Network)의 서버와 스토리지 어레이 간에 데이터를 라우팅할 수 있는 스토리지 스위치입니다.



== 초기 구성 개요

ONTAP를 실행하는 시스템에서 NVIDIA SN2100 스위치를 구성하려면 다음 단계를 수행하십시오.

. link:install-hardware-sn2100-storage.html["NVIDIA SN2100 스위치용 하드웨어를 설치합니다"].
+
지침은 _NVIDIA 스위치 설치 안내서_에서 확인할 수 있습니다.

. link:configure-sn2100-storage.html["스위치를 구성합니다"].
+
지침은 NVIDIA 설명서를 참조하십시오.

. link:cabling-considerations-sn2100-storage.html["케이블 연결 및 구성 고려 사항을 검토합니다"].
+
광 연결, QSA 어댑터 및 스위치 포트 속도에 대한 요구 사항을 검토합니다.

. link:install-cable-shelves-sn2100-storage.html["NS224 쉘프를 스위치 연결 스토리지로 케이블로 연결합니다"].
+
NS224 드라이브 쉘프를 직접 연결 스토리지가 아닌 스위치 연결 스토리지로 케이블로 연결해야 하는 시스템이 있는 경우 다음 절차를 따르십시오.

. link:install-cumulus-mode-sn2100-storage.html["Cumulus 모드에서 Cumulus Linux를 설치합니다"] 또는 link:install-onie-mode-sn2100-storage.html["ONIE 모드에서 Cumulus Linux를 설치합니다"].
+
스위치가 Cumulus Linux 또는 ONIE를 실행 중일 경우 Cumulus Linux(CL) OS를 설치할 수 있습니다.

. link:install-rcf-sn2100-storage.html["참조 구성 파일 스크립트를 설치합니다"].
+
클러스터링과 스토리지 애플리케이션에 사용 가능한 RCF 스크립트는 두 가지가 있습니다.





== 추가 정보

설치 또는 유지 관리를 시작하기 전에 다음을 검토하십시오.

* link:configure-reqs-sn2100-storage.html["구성 요구 사항"]
* link:components-sn2100-storage.html["부품 및 부품 번호"]
* link:required-documentation-sn2100-storage.html["필수 문서"]

