---
permalink: switch-nvidia-sn2100-storage/install-onie-mode-sn2100-storage.html 
sidebar: sidebar 
keywords: install cumulus onie mode, sn2100 SN2100 switches setup, cumulus linux, onie mode 
summary: 'Cumulus Linux(CL) OS는 스위치가 Cumulus Linux 또는 ONIE를 실행하는 경우 설치할 수 있습니다.' 
---
= ONIE 모드로 Cumulus Linux 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스위치가 ONIE 모드에서 실행 중일 때 Cumulus Linux(CL) OS를 설치하려면 다음 절차를 따르세요.


NOTE: Cumulus Linux(CL) OS는 스위치가 Cumulus Linux 또는 ONIE를 실행할 때 설치할 수 있습니다(참조).link:install-cumulus-mode-sn2100-storage.html["Cumulus 모드로 설치"] ).

.이 작업에 관하여
ONIE(Open Network Install Environment)를 사용하면 네트워크 설치 프로그램 이미지를 자동으로 검색할 수 있어 Cumulus Linux를 설치할 수 있습니다.  이를 통해 Cumulus Linux와 같은 운영 체제를 선택하여 스위치를 보호하는 시스템 모델이 용이해집니다.  ONIE를 사용하여 Cumulus Linux를 설치하는 가장 쉬운 방법은 로컬 HTTP 검색을 사용하는 것입니다.


NOTE: 호스트가 IPv6를 지원하는 경우 웹 서버를 실행 중인지 확인하세요.  호스트가 IPv4를 지원하는 경우 웹 서버 외에도 DHCP를 실행하고 있는지 확인하세요.

이 절차는 관리자가 ONIE에서 부팅한 후 Cumulus Linux를 업그레이드하는 방법을 보여줍니다.

.단계
. 웹 서버의 루트 디렉토리에 Cumulus Linux 설치 파일을 다운로드합니다.  이 파일의 이름을 바꾸세요 `onie-installer` .
. 이더넷 케이블을 사용하여 호스트를 스위치의 관리 이더넷 포트에 연결합니다.
. 스위치를 켜세요.  스위치는 ONIE 이미지 설치 프로그램을 다운로드하고 부팅합니다.  설치가 완료되면 Cumulus Linux 로그인 프롬프트가 터미널 창에 나타납니다.
+

NOTE: Cumulus Linux를 설치할 때마다 전체 파일 시스템 구조가 지워지고 다시 빌드됩니다.

. SN2100 스위치를 재부팅합니다.
+
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *sudo reboot*
----
. GNU GRUB 화면에서 *Esc* 키를 눌러 일반 부팅 프로세스를 중단하고 *ONIE*를 선택한 후 *Enter* 키를 누릅니다.
. 다음 화면에서 *ONIE: OS 설치*를 선택하세요.
. ONIE 설치 프로그램 검색 프로세스는 자동 설치를 검색하여 실행됩니다.  *Enter*를 눌러 프로세스를 일시적으로 중지하세요.
. 검색 프로세스가 중지된 경우:
+
[listing, subs="+quotes"]
----
ONIE:/ # *onie-stop*
discover: installer mode detected.
Stopping: discover...start-stop-daemon: warning: killing process 427:
No such process done.
----
. 네트워크에서 DHCP 서비스가 실행 중인 경우 IP 주소, 서브넷 마스크 및 기본 게이트웨이가 올바르게 할당되었는지 확인하세요.
+
`ifconfig eth0`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0*
eth0   Link encap:Ethernet  HWaddr B8:CE:F6:19:1D:F6
       inet addr:10.233.204.71  Bcast:10.233.205.255  Mask:255.255.254.0
       inet6 addr: fe80::bace:f6ff:fe19:1df6/64 Scope:Link
       UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
       RX packets:21344 errors:0 dropped:2135 overruns:0 frame:0
       TX packets:3500 errors:0 dropped:0 overruns:0 carrier:0
       collisions:0 txqueuelen:1000
       RX bytes:6119398 (5.8 MiB)  TX bytes:472975 (461.8 KiB)
       Memory:dfc00000-dfc1ffff

ONIE:/ # *route*
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.233.204.1    0.0.0.0         UG    0      0      0   eth0
10.233.204.0    *               255.255.254.0   U     0      0      0   eth0
----
====
. IP 주소 지정 체계가 수동으로 정의된 경우 다음을 수행하세요.
+
[listing, subs="+quotes"]
----
ONIE:/ # *ifconfig eth0 10.233.204.71 netmask 255.255.254.0*
ONIE:/ # *route add default gw 10.233.204.1*
----
. 9단계를 반복하여 정적 정보가 올바르게 입력되었는지 확인합니다.
. Cumulus Linux 설치:
+
[listing, subs="+quotes"]
----
ONIE:/ # *route*

  Kernel IP routing table

  ONIE:/ # *onie-nos-install http://_<web-server>/<path>_/cumulus-linux-4.4.3-mlx-amd64.bin*

  Stopping: discover... done.
  Info: Attempting http://10.60.132.97/x/eng/testbedN,svl/nic/files/cumulus-linux-4.4.3-mlx-amd64.bin ...
  Connecting to 10.60.132.97 (10.60.132.97:80)
  installer            100% |*******************************|   552M  0:00:00 ETA
  ...
  ...
----
. 설치가 완료되면 스위치에 로그인하세요.
+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus login: *cumulus*
Password: *cumulus*
You are required to change your password immediately (administrator enforced)
Changing password for cumulus.
Current password: *cumulus*
New password: *<new_password>*
Retype new password: *<new_password>*
----
====
. Cumulus Linux 버전을 확인하세요:
+
`net show version`

+
.예를 보여주세요
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@cumulus:mgmt:~$ *net show version*
NCLU_VERSION=1.0-cl4.4.3u4
DISTRIB_ID="Cumulus Linux"
DISTRIB_RELEASE=*4.4.3*
DISTRIB_DESCRIPTION=*"Cumulus Linux 4.4.3”*
----
====


.다음은 무엇인가요?
ONIE 모드에서 Cumulus Linux를 설치한 후에는 다음을 수행할 수 있습니다.link:install-rcf-sn2100-storage.html["RCF 스크립트를 설치하거나 업그레이드합니다."] .
