---
permalink: switch-nvidia-sn2100-storage/migrate-2n-switched-sn2100-storage.html 
sidebar: sidebar 
keywords: two-node switchless cluster environments,migrating to a two-node switched NVIDIA SN2100 cluster environment,switchless cluster environments,NVIDIA SN2100 switches 
summary: 스위치가 없는 기존 2노드 클러스터 환경이 구축된 경우 NVIDIA SN2100 스위치를 사용하여 2노드 스위치 클러스터 환경으로 마이그레이션하여 클러스터 내 2개 노드 이상으로 확장할 수 있습니다. 
---
= NVIDIA SN2100 클러스터 스위치를 사용하여 2노드 스위치 클러스터로 마이그레이션합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스위치가 없는 기존 2노드 클러스터 환경이 구축된 경우 NVIDIA SN2100 스위치를 사용하여 2노드 스위치 클러스터 환경으로 마이그레이션하여 클러스터 내 2개 노드 이상으로 확장할 수 있습니다.

사용하는 절차는 각 컨트롤러에 전용 클러스터 네트워크 포트가 2개 있는지, 각 컨트롤러에 단일 클러스터 포트가 있는지 여부에 따라 다릅니다. 문서화된 프로세스는 광 또는 Twinax 포트를 사용하는 모든 노드에 대해 작동하지만, 노드에서 클러스터 네트워크 포트에 온보드 10GBASE-T RJ45 포트를 사용하는 경우 이 스위치에서 지원되지 않습니다.



== 요구사항 검토

.필요한 것
스위치가 없는 2노드 구성의 경우 다음을 확인하십시오.

* 스위치가 없는 2노드 구성이 올바르게 설정 및 작동합니다.
* 노드에서 ONTAP 9.10.1P3 이상이 실행되고 있습니다.
* 모든 클러스터 포트가 작동 상태입니다.
* 모든 클러스터 논리 인터페이스(LIF)는 홈 포트 및 작동 상태입니다.


NVIDIA SN2100 클러스터 스위치 구성의 경우 다음 사항을 확인합니다.

* 두 스위치 모두 관리 네트워크 연결을 사용합니다.
* 클러스터 스위치에 대한 콘솔 액세스가 있습니다.
* NVIDIA SN2100 노드 간 스위치 및 스위치 간 연결은 Twinax 또는 파이버 케이블을 사용합니다.
+

NOTE: 을 참조하십시오 link:cabling-considerations-sn2100-storage.html["케이블 연결 및 구성 고려 사항"] 주의 사항 및 자세한 내용은

+
를 클릭합니다 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - 스위치"^] 케이블 연결에 대한 자세한 내용은 에 나와 있습니다.

* ISL(Inter-Switch Link) 케이블은 두 NVIDIA SN2100 스위치 모두에서 포트 swp15 및 swp16에 연결됩니다.
* 두 SN2100 스위치의 초기 사용자 지정이 완료되어 다음과 같은 작업이 가능합니다.
+
** SN2100 스위치는 최신 버전의 Cumulus Linux를 실행하고 있습니다
** RCF(Reference Configuration Files)가 스위치에 적용되었습니다
** SMTP, SNMP, SSH 등의 사이트 사용자 지정은 새 스위치에 구성됩니다.






== 스위치를 마이그레이션합니다

.예를 참조하십시오
이 절차의 예에서는 다음과 같은 클러스터 스위치 및 노드 명명법을 사용합니다.

* SN2100 스위치의 이름은 _SW1_와 _SW2_입니다.
* 클러스터 SVM의 이름은_node1_and_node2_입니다.
* LIF의 이름은 노드 1의 _node1_clus1_과 _node1_clus2_이고, 노드 2의 _node2_clus1_과 _node2_clus2_입니다.
* 'cluster1:: *>' 프롬프트는 클러스터의 이름을 나타냅니다.
* 이 절차에 사용되는 클러스터 포트는 _e3a_와 _e3b_입니다.
* 브레이크아웃 포트는 SWP [port]s [브레이크아웃 포트 0-3] 형식을 사용합니다. 예를 들어 swp1의 4개의 브레이크아웃 포트는 _swp1s0_, _swp1s1_, _swp1s2_ 및 _swp1s3_입니다.
+
를 클릭합니다 https://hwu.netapp.com["Hardware Universe"^] 에는 해당 플랫폼의 실제 클러스터 포트에 대한 최신 정보가 나와 있습니다.





=== 1단계: 마이그레이션 준비

. 이 클러스터에서 AutoSupport가 활성화되어 있는 경우 AutoSupport 메시지를 호출하여 자동 케이스 생성을 억제합니다.
+
'System node AutoSupport invoke-node * -type all-message maINT=xh'

+
여기서 _x_는 유지보수 기간(시간)입니다.

. 권한 수준을 고급으로 변경하고 계속할 것인지 묻는 메시지가 표시되면 y를 입력합니다.
+
세트 프리빌리지 고급

+
고급 프롬프트('*>')가 나타납니다.





=== 2단계: 케이블 및 포트 구성

. 새 클러스터 스위치 SW1과 SW2에서 모든 노드 대상 포트(ISL 포트 아님)를 비활성화합니다.
+
ISL 포트를 비활성화해서는 안 됩니다.

+
.예제 보기
[%collapsible]
====
다음 명령을 실행하면 스위치 SW1 및 SW2의 노드 대상 포트가 비활성화됩니다.

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*

cumulus@sw2:~$ *net add interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. 두 SN2100 스위치 SW1과 SW2 사이의 ISL과 ISL의 물리적 포트가 포트 swp15와 swp16에서 작동하는지 확인합니다.
+
`net show interface`

+
.예제 보기
[%collapsible]
====
다음 예에서는 스위치 SW1에서 ISL 포트가 작동 중인 것을 보여 줍니다.

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface*

State  Name       Spd   MTU    Mode        LLDP         Summary
-----  ---------  ----  -----  ----------  -----------  -----------------------
...
...
UP     swp15      100G  9216   BondMember  sw2 (swp15)  Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  sw2 (swp16)  Master: cluster_isl(UP)
----
+ 다음 예에서는 스위치 SW2에서 ISL 포트가 작동 중인 것을 보여 줍니다.

를 누릅니다

[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface*

State  Name       Spd   MTU    Mode        LLDP         Summary
-----  ---------  ----  -----  ----------  -----------  -----------------------
...
...
UP     swp15      100G  9216   BondMember  sw1 (swp15)  Master: cluster_isl(UP)
UP     swp16      100G  9216   BondMember  sw1 (swp16)  Master: cluster_isl(UP)
----
====
. 모든 클러스터 포트가 작동하는지 확인합니다.
+
네트워크 포트 쇼

+
각 포트는 Link에, Health Status에 대해서는 Healthy로 표시되어야 합니다.

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network port show*

Node: node1

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

----
====
. 모든 클러스터 LIF가 작동 중인지 확인합니다.
+
네트워크 인터페이스 쇼

+
각 클러스터 LIF는 '홈'에 대해 '상태 관리/작업'이 UP/UP인 '상태 관리/작업'에 대해 '참'으로 표시되어야 합니다

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface show -vserver Cluster*

            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- -----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
----
====
. 클러스터 LIF에서 자동 되돌리기 사용 안 함:
+
'network interface modify -vserver Cluster-lif * -auto-revert false'

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network interface modify -vserver Cluster -lif * -auto-revert false*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   false
          node1_clus2   false
          node2_clus1   false
          node2_clus2   false

----
====
. 노드 1의 클러스터 포트 e3a에서 케이블을 분리한 다음, SN2100 스위치가 지원하는 적절한 케이블을 사용하여 클러스터 스위치 SW1의 포트 3에 e3a를 연결합니다.
+
를 클릭합니다 https://hwu.netapp.com/SWITCH/INDEX["Hardware Universe - 스위치"^] 케이블 연결에 대한 자세한 내용은 에 나와 있습니다.

. 노드 2의 클러스터 포트 e3a에서 케이블을 분리한 다음, SN2100 스위치가 지원하는 적절한 케이블을 사용하여 클러스터 스위치 SW1의 포트 4에 e3a를 연결합니다.
. 스위치 SW1에서 모든 노드 대상 포트를 활성화합니다.
+
.예제 보기
[%collapsible]
====
다음 명령을 실행하면 스위치 SW1의 모든 노드 대상 포트가 설정됩니다.

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net del interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw1:~$ *net pending*
cumulus@sw1:~$ *net commit*
----
====
. 스위치 SW1에서 모든 포트가 작동하는지 확인합니다.
+
`net show interface all`

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP            Summary
-----  --------- ----  -----  ---------- --------------- --------
...
DN     swp1s0    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s1    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s2    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s3    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s0    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s1    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s2    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s3    25G   9216   Trunk/L2                   Master: br_default(UP)
UP     swp3      100G  9216   Trunk/L2    node1 (e3a)    Master: br_default(UP)
UP     swp4      100G  9216   Trunk/L2    node2 (e3a)    Master: br_default(UP)
...
...
UP     swp15     100G  9216   BondMember  swp15          Master: cluster_isl(UP)
UP     swp16     100G  9216   BondMember  swp16          Master: cluster_isl(UP)
...
----
====
. 모든 클러스터 포트가 작동하는지 확인합니다.
+
네트워크 포트 표시 - IPSpace 클러스터

+
.예제 보기
[%collapsible]
====
다음 예에서는 모든 클러스터 포트가 노드 1과 노드 2에 있음을 보여 줍니다.

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

----
====
. 클러스터의 노드 상태에 대한 정보를 표시합니다.
+
'클러스터 쇼'

+
.예제 보기
[%collapsible]
====
다음 예제에는 클러스터에 있는 노드의 상태 및 자격에 대한 정보가 표시됩니다.

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          false
node2                true    true          false

----
====
. 노드 1의 클러스터 포트 e3b에서 케이블을 분리한 다음, SN2100 스위치가 지원하는 적절한 케이블을 사용하여 클러스터 스위치 SW2의 포트 3에 e3b를 연결합니다.
. 노드 2의 클러스터 포트 e3b에서 케이블을 분리한 다음, SN2100 스위치가 지원하는 적절한 케이블을 사용하여 클러스터 스위치 SW2의 포트 4에 e3b를 연결합니다.
. 스위치 SW2에서 모든 노드 대상 포트를 활성화합니다.
+
.예제 보기
[%collapsible]
====
다음 명령을 사용하면 스위치 SW2에서 노드 연결 포트를 사용할 수 있습니다.

[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net del interface swp1s0-3, swp2s0-3, swp3-14 link down*
cumulus@sw2:~$ *net pending*
cumulus@sw2:~$ *net commit*
----
====
. 스위치 SW2에서 모든 포트가 작동하는지 확인합니다.
+
`net show interface all`

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cumulus@sw2:~$ *net show interface all*

State  Name      Spd   MTU    Mode       LLDP            Summary
-----  --------- ----  -----  ---------- --------------- --------
...
DN     swp1s0    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s1    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s2    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp1s3    10G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s0    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s1    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s2    25G   9216   Trunk/L2                   Master: br_default(UP)
DN     swp2s3    25G   9216   Trunk/L2                   Master: br_default(UP)
UP     swp3      100G  9216   Trunk/L2    node1 (e3b)    Master: br_default(UP)
UP     swp4      100G  9216   Trunk/L2    node2 (e3b)    Master: br_default(UP)
...
...
UP     swp15     100G  9216   BondMember  swp15          Master: cluster_isl(UP)
UP     swp16     100G  9216   BondMember  swp16          Master: cluster_isl(UP)
...
----
====
. 두 스위치 SW1과 SW2에서 두 노드 모두 각 스위치에 하나씩 연결되어 있는지 확인합니다.
+
`net show lldp`

+
.예제 보기
[%collapsible]
====
다음 예에서는 스위치 SW1과 SW2에 대해 적절한 결과를 보여 줍니다.

[listing, subs="+quotes"]
----
cumulus@sw1:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3a
swp4       100G   Trunk/L2    node2              e3a
swp15      100G   BondMember  sw2                swp15
swp16      100G   BondMember  sw2                swp16

cumulus@sw2:~$ *net show lldp*

LocalPort  Speed  Mode        RemoteHost         RemotePort
---------  -----  ----------  -----------------  -----------
swp3       100G   Trunk/L2    node1              e3b
swp4       100G   Trunk/L2    node2              e3b
swp15      100G   BondMember  sw1                swp15
swp16      100G   BondMember  sw1                swp16
----
====




=== 3단계: 절차를 완료합니다

. 클러스터에서 검색된 네트워크 장치에 대한 정보를 표시합니다.
+
`net device-discovery show -protocol lldp`

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *network device-discovery show -protocol lldp*
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface     Platform
----------- ------ ------------------------- ------------  ----------------
node1      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp3          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp3          -
node2      /lldp
            e3a    sw1 (b8:ce:f6:19:1a:7e)   swp4          -
            e3b    sw2 (b8:ce:f6:19:1b:96)   swp4          -
----
====
. 모든 클러스터 포트가 작동하는지 확인합니다.
+
네트워크 포트 표시 - IPSpace 클러스터

+
.예제 보기
[%collapsible]
====
다음 예에서는 모든 클러스터 포트가 노드 1과 노드 2에 있음을 보여 줍니다.

[listing, subs="+quotes"]
----
cluster1::*> *network port show -ipspace Cluster*

Node: node1
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

Node: node2
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/10000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/10000 healthy  false

----
====
. 모든 클러스터 LIF에서 자동 되돌리기 사용:
+
`net interface modify -vserver Cluster -lif * -auto-revert true`

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *net interface modify -vserver Cluster -lif * -auto-revert true*

          Logical
Vserver   Interface     Auto-revert
--------- ------------- ------------
Cluster
          node1_clus1   true
          node1_clus2   true
          node2_clus1   true
          node2_clus2   true
----
====
. 모든 인터페이스가 '홈'에 대해 true로 표시되는지 확인합니다.
+
`net interface show -vserver Cluster`

+

NOTE: 이 작업을 완료하는 데 1분 정도 걸릴 수 있습니다.

+
.예제 보기
[%collapsible]
====
다음 예에서는 모든 LIF가 node1과 node2에 있으며 "홈" 결과가 true인 것을 보여 줍니다.

[listing, subs="+quotes"]
----
cluster1::*> *net interface show -vserver Cluster*

          Logical      Status     Network            Current    Current Is
Vserver   Interface    Admin/Oper Address/Mask       Node       Port    Home
--------- ------------ ---------- ------------------ ---------- ------- ----
Cluster
          node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
          node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
          node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
          node2_clus2  up/up      169.254.19.183/16  node2      e3b     true

----
====
. 설정이 비활성화되었는지 확인합니다.
+
'network options switchless-cluster show'

+
.예제 보기
[%collapsible]
====
다음 예제의 false 출력은 구성 설정이 비활성화되어 있음을 보여 줍니다.

[listing, subs="+quotes"]
----
cluster1::*> *network options switchless-cluster show*
Enable Switchless Cluster: *false*
----
====
. 클러스터에서 노드 구성원의 상태를 확인합니다.
+
'클러스터 쇼'

+
.예제 보기
[%collapsible]
====
다음 예는 클러스터에 있는 노드의 상태 및 적격성에 대한 정보를 보여줍니다.

[listing, subs="+quotes"]
----
cluster1::*> *cluster show*

Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  --------
node1                true    true          false
node2                true    true          false
----
====
. 원격 클러스터 인터페이스의 연결을 확인합니다.


[role="tabbed-block"]
====
.ONTAP 9.9.1 이상
--
를 사용할 수 있습니다 `network interface check cluster-connectivity` 클러스터 연결에 대한 접근성 검사를 시작한 다음 세부 정보를 표시하는 명령입니다.

`network interface check cluster-connectivity start` 및 `network interface check cluster-connectivity show`

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity start*
----
* 참고: * 몇 초 동안 기다린 후 `show` 명령을 실행하여 세부 정보를 표시합니다.

[listing, subs="+quotes"]
----
cluster1::*> *network interface check cluster-connectivity show*
                                  Source           Destination      Packet
Node   Date                       LIF              LIF              Loss
------ -------------------------- ---------------- ---------------- -----------
node1
       3/5/2022 19:21:18 -06:00   node1_clus2      node2-clus1      none
       3/5/2022 19:21:20 -06:00   node1_clus2      node2_clus2      none
node2
       3/5/2022 19:21:18 -06:00   node2_clus2      node1_clus1      none
       3/5/2022 19:21:20 -06:00   node2_clus2      node1_clus2      none
----
--
.모든 ONTAP 릴리스
--
모든 ONTAP 릴리스에 대해 을 사용할 수도 있습니다 `cluster ping-cluster -node <name>` 연결 상태를 확인하는 명령:

`cluster ping-cluster -node <name>`

[listing, subs="+quotes"]
----
cluster1::*> *cluster ping-cluster -node local*
Host is node1
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:

Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)

Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
--
====
. [[step8]] 다음 명령을 사용하여 스위치 관련 로그 파일을 수집하기 위해 이더넷 스위치 상태 모니터 로그 수집 기능을 활성화합니다.
+
System switch ethernet log setup-password와 system switch ethernet log enable-collection

+
'시스템 스위치 이더넷 로그 설정 - 암호'를 입력합니다

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log setup-password*
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
*sw1*
*sw2*

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw1*
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>

cluster1::*> *system switch ethernet log setup-password*

Enter the switch name: *sw2*
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] *y*

Enter the password: <enter switch password>
Enter the password again: <enter switch password>
----
====
+
그 뒤에 다음 사항이 있습니다.

+
System switch Ethernet log enable-collection

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log enable-collection*

Do you want to enable cluster log collection for all nodes in the cluster?
{y|n}: [n] *y*

Enabling cluster switch log collection.

cluster1::*>
----
====
+

NOTE: 이러한 명령에서 오류가 반환되면 NetApp 지원에 문의하십시오.

. 스위치 로그 수집 기능을 시작합니다.
+
`system switch ethernet log collect -device *`

+
10분간 기다린 후 다음 명령을 사용하여 로그 수집이 성공했는지 확인합니다.

+
`system switch ethernet log show`

+
.예제 보기
[%collapsible]
====
[listing, subs="+quotes"]
----
cluster1::*> *system switch ethernet log show*
Log Collection Enabled: true

Index  Switch                       Log Timestamp        Status
------ ---------------------------- -------------------  ---------    
1      sw1 (b8:ce:f6:19:1b:42)      4/29/2022 03:05:25   complete   
2      sw2 (b8:ce:f6:19:1b:96)      4/29/2022 03:07:42   complete
----
====
. 권한 수준을 admin으로 다시 변경합니다.
+
'Set-Privilege admin'입니다

. 자동 케이스 생성을 억제한 경우 AutoSupport 메시지를 호출하여 다시 활성화합니다.
+
'System node AutoSupport invoke-node * -type all-message maINT=end'


