---
permalink: switch-nvidia-sn2100-storage/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, ontap, install the cluster switch health monitor (csm) configuration file for sn2100 switches' 
summary: 이 절차를 사용하여 NVIDIA SN2100 스토리지 스위치의 클러스터 스위치 상태 모니터링을 위한 해당 구성 파일을 설치할 수 있습니다. 
---
= 이더넷 스위치 상태 모니터 구성 파일을 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 절차에 따라 NVIDIA 클러스터 스위치의 이더넷 스위치 상태 모니터링을 위한 해당 구성 파일을 설치하십시오. 지원되는 모델:

* X190006-PE
* X190006-PI



NOTE: 이 설치 절차는 ONTAP 9.10.1 이상에 적용됩니다.

.시작하기 전에
* 를 실행하고 모델에 * 기타 * 가 표시되는지 확인하여 구성 파일을 다운로드해야 하는지 `system switch ethernet show` 확인합니다.
+
구성 파일을 적용한 후에도 모델에 * 기타 * 가 계속 표시되면 NetApp 지원에 문의하십시오.

* ONTAP 클러스터가 작동 중이고 실행 중인지 확인합니다.
* CSHM에서 사용할 수 있는 모든 기능을 사용하려면 SSH를 활성화합니다.


.단계
. 해당 ONTAP 릴리스 버전을 기반으로 이더넷 스위치 상태 모니터 구성 zip 파일을 다운로드합니다. 이 파일은 페이지에서 사용할 수 https://mysupport.netapp.com/site/info/nvidia-cluster-switch["NVIDIA 이더넷 스위치"^] 있습니다.
+
.. NVIDIA SN2100 소프트웨어 다운로드 페이지에서 * Nvidia CSHM File * 을 선택합니다.
.. 주의/읽어야 함 페이지에서 동의할 확인란을 선택합니다.
.. 최종 사용자 사용권 계약 페이지에서 동의할 확인란을 선택하고 * Accept & Continue * 를 클릭합니다.
.. Nvidia CSHM 파일 - 다운로드 페이지에서 해당 구성 파일을 선택합니다. 다음 파일을 사용할 수 있습니다.




[role="tabbed-block"]
====
.ONTAP 9.15.1 이상
--
* X190006-PE.zip
* X190006-PI.zip


--
.ONTAP 9.11.1 ~ 9.14.1
--
* X190006-PE_PRIOR_9.15.1.zip
* X190006-PI_PRIOR_9.15.1.zip


--
====
. [[step2]] 해당 zip 파일을 내부 웹 서버에 업로드합니다.
. 클러스터의 ONTAP 시스템 중 하나에서 고급 모드 설정에 액세스합니다.
+
세트 프리빌리지 고급

. switch 상태 monitor configure 명령을 실행합니다.
+
[listing, subs="+quotes"]
----
cluster1::> *system cluster-switch configure-health-monitor -node * -package-url 192.168.2.20/usr/download/_[filename.zip]_*
----
. 명령 출력이 ONTAP 버전에 대한 다음 텍스트로 끝나는지 확인합니다.


[role="tabbed-block"]
====
.ONTAP 9.15.1 이상
--
이더넷 스위치 상태 모니터링이 구성 파일을 설치했습니다.

--
.ONTAP 9.11.1 ~ 9.14.1
--
shm이 구성 파일을 설치했습니다.

--
.ONTAP 9.10.1
--
CSHM 다운로드 패키지가 성공적으로 처리되었습니다.

--
====
오류가 발생하면 NetApp 지원 팀에 문의하십시오.

. [[step6]] 다음 단계를 완료하기 전에 를 실행하여 찾은 이더넷 스위치 상태 모니터 폴링 간격을 최대 2배까지 기다립니다 `system switch ethernet polling-interval show`.
. ONTAP 시스템에서 명령을 `system switch ethernet show` 실행하고 모니터링되는 필드가 * True * 로 설정되어 있고 일련 번호 필드가 * Unknown * 으로 표시되지 않는 상태에서 클러스터 스위치가 검색되는지 확인합니다.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet show*
----


.다음 단계
link:../switch-cshm/config-overview.html["스위치 상태 모니터링을 구성합니다"]..
