---
permalink: switch-nvidia-sn2100-storage/setup-install-cshm-file.html 
sidebar: sidebar 
keywords: 'install, applicable, configuration, file, cluster, switch, health, monitor, ontap, install the cluster switch health monitor (csm) configuration file for sn2100 switches' 
summary: 이 절차를 사용하여 NVIDIA SN2100 스토리지 스위치의 클러스터 스위치 상태 모니터링에 적용되는 구성 파일을 설치할 수 있습니다. 
---
= 이더넷 스위치 상태 모니터 구성 파일 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Follow this procedure to install the applicable configuration file for Ethernet switch health monitoring of NVIDIA cluster switches.  지원되는 모델은 다음과 같습니다.

* MSN2100-CB2FC
* MSN2100-CB2RC
* X190006-PE
* X190006-PI



NOTE: 이 설치 절차는 ONTAP 9.10.1 이상에 적용됩니다.

.시작하기 전에
* 다음을 실행하여 구성 파일을 다운로드해야 하는지 확인하세요. `system switch ethernet show` 그리고 모델에 *OTHER*가 표시되는지 확인합니다.
+
구성 파일을 적용한 후에도 모델에 *OTHER*가 계속 표시되는 경우 NetApp 지원팀에 문의하세요.

* ONTAP 클러스터가 실행 중인지 확인하세요.
* CSHM에서 제공하는 모든 기능을 사용하려면 SSH를 활성화하세요.
* 지우다 `/mroot/etc/cshm_nod/nod_sign/` 모든 노드의 디렉토리:
+
.. 노드셸을 입력하세요:
+
`system node run -node <name>`

.. 고급 권한으로 변경:
+
`priv set advanced`

.. 구성 파일을 나열하세요 `/etc/cshm_nod/nod_sign` 예배 규칙서.  해당 디렉토리가 존재하고 구성 파일을 포함하고 있으면 파일 이름이 나열됩니다.
+
`ls /etc/cshm_nod/nod_sign`

.. 연결된 스위치 모델에 해당하는 모든 구성 파일을 삭제합니다.
+
확실하지 않은 경우 위에 나열된 지원 모델의 모든 구성 파일을 제거한 다음, 동일한 모델의 최신 구성 파일을 다운로드하여 설치하세요.

+
`rm /etc/cshm_nod/nod_sign/<filename>`

.. 삭제된 구성 파일이 더 이상 디렉토리에 없는지 확인하세요.
+
`ls /etc/cshm_nod/nod_sign`





.단계
. 해당 ONTAP 릴리스 버전에 따라 이더넷 스위치 상태 모니터 구성 zip 파일을 다운로드합니다.  이 파일은 다음에서 사용할 수 있습니다. https://mysupport.netapp.com/site/info/nvidia-cluster-switch["NVIDIA 이더넷 스위치"^] 페이지.
+
.. NVIDIA SN2100 소프트웨어 다운로드 페이지에서 *Nvidia CSHM 파일*을 선택합니다.
.. 주의/필수 읽기 페이지에서 동의하려면 확인란을 선택하세요.
.. 최종 사용자 라이선스 계약 페이지에서 동의하는 확인란을 선택하고 *동의 및 계속*을 클릭합니다.
.. Nvidia CSHM 파일 - 다운로드 페이지에서 해당 구성 파일을 선택합니다.  다음 파일을 사용할 수 있습니다.




[role="tabbed-block"]
====
.ONTAP 9.15.1 이상
--
* MSN2100-CB2FC-v1.4.zip
* MSN2100-CB2RC-v1.4.zip
* X190006-PE-v1.4.zip
* X190006-PI-v1.4.zip


--
.ONTAP 9.11.1부터 9.14.1까지
--
* MSN2100-CB2FC_PRIOR_R9.15.1-v1.4.zip
* MSN2100-CB2RC_PRIOR_R9.15.1-v1.4.zip
* X190006-PE_PRIOR_9.15.1-v1.4.zip
* X190006-PI_PRIOR_9.15.1-v1.4.zip


--
====
. [[step2]]해당하는 zip 파일을 내부 웹 서버에 업로드합니다.
. 클러스터의 ONTAP 시스템 중 하나에서 고급 모드 설정에 액세스합니다.
+
`set -privilege advanced`

. 스위치 상태 모니터 구성 명령을 실행합니다.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet configure-health-monitor*
----
. ONTAP 버전에 대한 명령 출력이 다음 텍스트로 끝나는지 확인하세요.


[role="tabbed-block"]
====
.ONTAP 9.15.1 이상
--
이더넷 스위치 상태 모니터링이 구성 파일을 설치했습니다.

--
.ONTAP 9.11.1부터 9.14.1까지
--
SHM이 구성 파일을 설치했습니다.

--
.ONTAP 9.10.1
--
CSHM에서 다운로드한 패키지가 성공적으로 처리되었습니다.

--
====
오류가 발생하면 NetApp 지원팀에 문의하세요.

. [[step6]]Ethernet 스위치 상태 모니터 폴링 간격의 최대 2배까지 기다립니다. 다음을 실행하여 찾습니다. `system switch ethernet polling-interval show` 다음 단계를 완료하기 전에.
. 명령을 실행하세요 `system switch ethernet configure-health-monitor show` ONTAP 시스템에서 클러스터 스위치가 모니터링 필드가 *True*로 설정되어 있고 일련 번호 필드에 *Unknown*이 표시되지 않는지 확인합니다.
+
[listing, subs="+quotes"]
----
cluster1::> *system switch ethernet configure-health-monitor show*
----


.다음은 무엇인가요?
CSHM 파일을 설치한 후에는 다음을 수행할 수 있습니다.link:../switch-cshm/config-overview.html["스위치 상태 모니터링 구성"] .
